### ISSUE TITLE
Allow Surfingkeys to be partially disabled

### ISSUE THREAD

**Issue by dylan-conlin** [brookhong/Surfingkeys#100]
Vimium can be partially disabled via a setting allowing specific keys to be "passed through". For example, on facebook.com, by specifying j and k as my pass through keys, I can use all of my vimium bindings except for j and k.

This would allow us to use a site's native keybindings (for sites like gmail, inbox.google.com, facebook, and reddit) as well as our Surfingkeys bindings.

**Comment by brookhong** [comment]
`se` to open settings, then add settings like below to disable j for facebook.com.

    if (window.location.origin === "https://www.facebook.com/") {
        unmap('j');
    }

**Comment by dylan-conlin** [comment]
Thank you, this works well enough!

**Comment by anka-213** [comment]
I needed to remove the final slash in the url for it to work for me:

```
if (window.location.origin === "https://www.duckduckgo.com") {
    unmap('h');
    unmap('j');
    unmap('k');
    unmap('l');
}
```

**Comment by brookhong** [comment]
@anka-213  You're right, I revised my last comments. Thanks

**Comment by JSpenced** [comment]
Is it possible to do this but only allow certain keys when it is disabled? So by default all keys are disable but if surfingkeys is disabled just a few specific keys are enabled as well as `alt+s`.

**Comment by brookhong** [comment]
`Alt-s` will disable Surfingkeys completely, to disable most keys except some one, please use `unmapAllExcept`, such as

    unmapAllExcept(['E','R','T'], /google.com|twitter.com/);

**Comment by JSpenced** [comment]
Yeah but the option is to disable all surfing keys but `alt-s` or when enabled `unmapAllExcept` certain keys. Ideally, I want to have a mode where all the keys are enabled. Then when I toggle with `alt-s` that all the keys are disabled except the keys specified. I guess a function like `mapWhenDisabled` just for when it's disabled you can still for example use `x` to close windows. 

I don't use surfingkeys by default for some sites but when disabled. I would still like `x` to close windows or certain other keys to work.

```
mapWhenDisabled(['E','R','T'], /google.com|twitter.com/);
```

**Comment by davidhdez** [comment]
I want just to unmap 'j' and 'k' in google, but I can't, please help me. I follow all the instructions that are here, but I can't.
