### ISSUE TITLE
Open default search engine after Enter not working most of the time

### ISSUE THREAD

**Issue by duranivan** [brookhong/Surfingkeys#1004]
Recently I noticed that after hitting `enter` in the omnibar, it tries to open a website url and not the default engine. This was not happening before but recently.

For example, if I type "this is", and there is some suggestion from the history, it will try to open the url `https://this%20is/`, instead of the search engine with the sentence "this is", even though the suggestion is not selected. 

If there is no suggestion for the typed sentence or word, then it will open the search engine as expected. However, most of the time it happens that there is some suggestion.

**Comment by brookhong** [comment]
Looks like we need revert https://github.com/brookhong/Surfingkeys/pull/940.
