### ISSUE TITLE
Vim编辑模式对中文输入法兼容不好

### ISSUE THREAD

**Issue by wujunchuan** [brookhong/Surfingkeys#101]
第二行,我每次按d 空格,会将前一次的内容重复输入一遍再插入新添加的文字
![image](https://cloud.githubusercontent.com/assets/7511631/19100806/9a8efed4-8af4-11e6-9cec-a371985bbd7a.png)

**Comment by brookhong** [comment]
https://github.com/ajaxorg/ace/issues/3097

https://github.com/ajaxorg/ace/issues/3099
