### ISSUE TITLE
How to make Surfingkeys work with local files?

### ISSUE THREAD

**Issue by ZaxonXP** [brookhong/Surfingkeys#1011]
## Error details

SurfingKeys: 0.9.45

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.145 Safari/537.36 Vivaldi/2.6.1566.49
OS: Linux Debian 10 Buster

URL: file:///user/home/file.html

## Context

I would like to use Surfingkeys with the local HTML files, but I do not know how. Can you please tell me how to configure it?

Regards,
Piotr

**Comment by for-coursera** [comment]
`chrome://extensions` -> SurfingKeys -> Details -> Allow access to file URLs?
