### ISSUE TITLE
网页中点击pdf无法正常打开

### ISSUE THREAD

**Issue by ggllioio** [brookhong/Surfingkeys#1017]
## Error details

SurfingKeys: 0.9.46

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3887.7 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

网页中点击pdf无法正常打开。扩展地址末尾会变成“about:blank"，报错”PDF.js v1.8.355 (build: e9cbfbcc)
Message: Unexpected server response (0) while retrieving PDF "about:blank".“本地pdf文件打开正常。
例如：打开
[http://www.ti.com/lit/pdf/SLYT701?jktype=tech_docs](url)
带pdf的链接，会跳转到
[chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html?r=about:blank](url)
无法正常打开pdf。
望修复。谢谢！

**Comment by zuxfoucault** [comment]
have the same issue too

**Comment by brookhong** [comment]
This should have been fixed in 0.9.48.
