### ISSUE TITLE
regression: disabled/enabled status is ignored

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#1018]
## Error details

Something seems to have regressed recently with SurfingKeys, because I am often finding that it does not respond to any shortcuts until I press `Alt-S` twice to [toggle it off and on again](https://www.youtube.com/watch?v=nn2FB1P_Mn8).

Unfortunately so far I haven't spotted any pattern and can't pin out down to anything more concrete, but I thought it was worth reporting in case there could be any recent changes which might have caused this, or if there is anything I can do to debug next time it happens.  I'll update this issue if I figure out any more details.

Maybe worth noting that this kind of problem with enable/disable has happened several times before as per #382, so I still think regression tests would be helpful.

SurfingKeys: 0.9.46

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

URL: many different pages

## Context

No obvious context yet.

**Comment by aspiers** [comment]
Actually the problem is worse than I realised - the *opposite* also sometimes happens, i.e. SurfingKeys responds to shortcuts when it is disabled.

**Comment by brookhong** [comment]
Thanks for reporting.

The commit https://github.com/brookhong/Surfingkeys/commit/b2c7cdcfbd7478ab77ad3deb6d808781da7a5ddb seems to affect toggling Surfingkeys from dropdown menu by clicking the extension icon in browser's toolbar.

It is weird that toggling from setting script is broken.

**Comment by aspiers** [comment]
OK I have noticed something else significant.  If I hit `Alt-S` in one tab, it affects *all* tabs, even if each tab is on a completely different domain.  Does that help debug it?

This is a major regression, because it used to be possible to enable/disable per domain, and that is an important feature since some domains like youtube etc. have their own keyboard shortcuts and need to have SurfingKeys disabled by default.

**Comment by brookhong** [comment]
@aspiers 
Thanks, that helps.

I have uploaded a new release 0.9.47 on Chrome Store, please have a try.

**Comment by aspiers** [comment]
Cool thanks, it seems fixed!  Although I don't see any entries in the changelog since 0.9.42?

**Comment by brookhong** [comment]
Just updated the changelog in https://github.com/brookhong/Surfingkeys/commit/017c4570a1ebb0e46268a3b90fbcc2f6f269baa1
