### ISSUE TITLE
How to open a new tab and automatically focus on Firefox's own address bar?

### ISSUE THREAD

**Issue by clarkwang** [brookhong/Surfingkeys#1019]
Sometimes I'd like to use Firefox's own autocomplete functionality to search history, bookmarks, tags, keywords etc. I searched a lot but did not find a way with Surfingkeys to open a new tab and automatically focus on Firefox's own address bar. For now I have to press `on` to open a new tab and then press `CTRL-L` to focus on the addr bar.

Thanks.

**Comment by brw** [comment]
I noticed the same behavior using Vivaldi. I wonder if there's something that can be done about it, it's a little annoying.

**Comment by clarkwang** [comment]
inactive for quite long. closing...
