### ISSUE TITLE
In the new Chromium-based Edge, link to Register-inline-query keeps triggering at strange times

### ISSUE THREAD

**Issue by drk-mtr** [brookhong/Surfingkeys#1021]
I'm  using an unsupported browser that is in preview, so please feel free to close this as it may well be that it's not a Surfingkeys issue.

## Error details

SurfingKeys: 0.9.47
Browser: Edge Version 78.0.249.1 (Official build) dev (64-bit), Windows 10 1903
URL: Any

## Context

- Select some text e.g. the title header on this issue itself.
- This page opens unexpectedly: https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query

It's hitting this but I haven't worked out why yet:
https://github.com/brookhong/Surfingkeys/blob/f27a6cd30df285b05d78922a201b9e71912edd0e/content_scripts/front.js#L260

THANK  YOU for the brilliant plugin.

**Comment by arizzubair** [comment]
Does it occur after selection by double click?

**Comment by brookhong** [comment]
Looks like you have turned on the feature `mouse select to query` for `github.com`, you could use `yj` to dump all runtime settings into clipboard, then paste it into some text editor to search keyword `mouseSelectToQuery`, which will tell you which websites you have turned on the feature for.

`;q` is the shortcut to toggle the feature on current site, please refer to https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js#L219

**Comment by drk-mtr** [comment]
It was exactly as you've suggested above. Apologies, I didn't realise this was a feature and assumed it was an issue as I was using a beta browser. Thanks for the pointers! I'll close the issue now.
