### ISSUE TITLE
No PDF files can be viewed in Chrome, even with the Surfingkeys PDF viewer disabled

### ISSUE THREAD

**Issue by abastardi** [brookhong/Surfingkeys#1026]
## Error details

SurfingKeys: 0.9.47

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

URL: Any link to a PDF file (for example, http://www.pdf995.com/samples/pdf.pdf)

## Context

Whenever the URL of a PDF is loaded in the browser, Surfingkeys attempts to load `about:blank` instead of the PDF URL. If the Surfingkeys PDF viewer is enabled, the final URL in the address bar is _always_ `chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html?r=about:blank` (for _every_ PDF URL).

What is even worse is that even if the Surfingkeys PDF viewer is disabled or if Surfingkeys itself is disabled, the browser extension still intercepts PDF URLs and instead attempts to load `about:blank` in the built-in Chrome PDF viewer. This means that as long as Surfingkeys is installed and activated in the browser, _it is impossible to view any PDFs in the browser, even with the built-in Chrome PDF viewer_. This is a major problem for the usage of Surfingkeys.

**Comment by robotenique** [comment]
I get the same problem...

**Comment by echristopherson** [comment]
Same thing here, on a Win7 Enterprise PC and a Win10 Home one.

**Comment by 8utl3r** [comment]
Ditto, pixelbook for me. Same pdf at same address works fine on my phone.

**Comment by mkaradja** [comment]
I get the exact same issue. Only thing that works is to disable the extension entirely from the extensions menu. I'm on Chrome Version 77.0.3865.75 (Official Build) (64-bit).

**Comment by brookhong** [comment]
Thanks guys.

This was fixed in 0.9.48.

**Comment by mkaradja** [comment]
Amazing, thanks so much.

**Comment by abastardi** [comment]
Wow, that was fast! Thanks a lot. Seems to be working fine now.
