### ISSUE TITLE
Disable certain keys for domain

### ISSUE THREAD

**Issue by haoyangnz** [brookhong/Surfingkeys#1030]
Can we disable certain keys for domain, such as `r` for slack, instead of blacklisting slack altogether.

**Comment by clarkwang** [comment]
What about this?

```
if (_isDomainApplicable(/feedly.com/) ) {
    unmap('r');
}
```

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-unmap-many-keys-for-some-sites

**Comment by clarkwang** [comment]
> Please refer to https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-unmap-many-keys-for-some-sites

`unmapAllExcept()` is good for unmapping most (or many) keybindings. It's not convenient to unmap only a few bindings. :)

**Comment by haoyangnz** [comment]
> What about this?
> 
> ```
> if (_isDomainApplicable(/slack.com/) ) {
>     unmap('r');
> }
> ```

@clarkwang I think this particular feature not being easily accessible has been a major reason why a lot of people that tried surfingkeys are uninstalling/returning to vimium. Would be good to consider a front end feature for it.

**Comment by haoyangnz** [comment]
☝️ @brookhong Can we reopen this as a feature request to have this on the front end? Or is the vision of this project for advanced users only?

**Comment by clarkwang** [comment]
> ☝️ @brookhong Can we reopen this as a feature request to have this on the front end? Or is the vision of this project for advanced users only?

Agree. It's not quite user friendly. I'm not a web developer but now I have learn JavaScript to write my own Surfingkeys conf file. :)

**Comment by clarkwang** [comment]
Ideally the conf file should look like this:

    map j SrollDown
    map k ScrollUp
    map f FollowLinks
    ...
