### ISSUE TITLE
Duplicate the active tab as a background tab

### ISSUE THREAD

**Issue by Dark-Magician** [brookhong/Surfingkeys#1032]
Is it possible to duplicate the active tab as a background tab?

**Comment by brookhong** [comment]
If you press `yt`, then current active tab will be put background, a new duplicate tab will be active, I see no difference from what you need, except the positions of these 2 tabs.

**Comment by Dark-Magician** [comment]
Duplicating tabs in that manner is jarring and interrupting because I must wait for the new active tab, i.e. the clone, to finish loading. Also, as you stated, the positions of the tabs change.

**Comment by brookhong** [comment]
`yT` is introduced in 0.9.49 to duplicate current tab in background.
