### ISSUE TITLE
Add option to enable just some shortcuts.

### ISSUE THREAD

**Issue by akrasuski1** [brookhong/Surfingkeys#104]
I like this extension, but `f` and `/` keys are probably enough for me. I'm annoyed when I'm typing some text and can't really type `<` character without repeating it twice - several other keys do that too. I would love to have ability to select just a subset of shortcuts to be enabled.

**Comment by brookhong** [comment]
`se` to open settings, then add below line,

    iunmap('<'); // to remove Ctrl-i mapping in insert mode

also try to use `unmap` to disable keys in normal mode.

**Comment by akrasuski1** [comment]
That's not bad, but it's a bit exhausting to disable all the shortcuts I don't use (and I'm sure I will find some of them similarly getting into way in the future, which will force me to repeat the whole procedure for the new key). It would be nice if there was a way to disable all mappings and only add the few I actually use - either by disabling loading default.js or (if possible) in the user script, loop over existing bindings and disable them all.

**Comment by brookhong** [comment]
unmapAllExcept(['f', '/', '?']);

Above API added in 0.6.3. The example is to unmap all except those in the list.

**Comment by akrasuski1** [comment]
Thanks! That solves the issue completely.
