### ISSUE TITLE
pdf_viewer error

### ISSUE THREAD

**Issue by bedisdover** [brookhong/Surfingkeys#1040]
## Error details

Online pdf & local file both output this error in devtools:

```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
    at t (pdf_viewer.js:5)
    at e.value (pdf_viewer.js:5)
    at new e (pdf_viewer.js:5)
    at pdf_viewer.js:1
    at new Promise (<anonymous>)
    at Object._initializeViewerComponents (pdf_viewer.js:1)
    at pdf_viewer.js:1
```

SurfingKeys: 0.9.48

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

URL:  every pdf in my case

## Context

Just open pdf file in Chrome

**Comment by pacomas** [comment]
It happens to me too:

> PDF.js v1.8.355 (build: e9cbfbcc)
> Message: Invalid PDF structure

**Comment by bedisdover** [comment]
Solved after upgrading Chrome :)
