### ISSUE TITLE
Copy image's URL?

### ISSUE THREAD

**Issue by for-coursera** [brookhong/Surfingkeys#1042]
## Context

When browsing a page with images, is it possible to copy the URLs for these images as it's possible to copy the URLs for links with `ya` / `yma`?

I'm probably missing something very obvious because I couldn't find any info on that :). So, I do apologize in advance :)

## Details:

SurfingKeys: 0.9.48

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

URL: e.g., this one: https://www.bbc.com/sport/football/49865134 -- the header image for the article is a photo of Cristiano Ronaldo scoring. Can I copy this image's URL somehow?

Thank you.

**Comment by brookhong** [comment]
You could add below in your settings:

    mapkey('ye', '#7Copy src URL of an image', function() {
        Hints.create('img[src]', function(element, event) {
            Clipboard.write(element.src);
        });
    });
    mapkey('yme', '#7Copy multiple link URLs to the clipboard', function() {
        var linksToYank = [];
        Hints.create('img[src]', function(element) {
            linksToYank.push(element.src);
            Clipboard.write(linksToYank.join('\n'));
        }, {multipleHits: true});
    });

**Comment by for-coursera** [comment]
Thank you so much! :)

**Comment by snowman** [comment]
But how to copy the image blob?

**Comment by jsr-p** [comment]
@snowman  better late than never; this function works for me:

```javascript
api.mapkey('yi', 'Copy image to clipboard', function() {
    api.Hints.create("img", function(element) {
        // Create an off-screen canvas
        const canvas = document.createElement("canvas");
        const context = canvas.getContext("2d");
        
        // Create a new Image object
        const img = new Image();
        img.crossOrigin = "Anonymous"; // Handle cross-origin images

        img.onload = function() {
            // Set canvas dimensions to match the image
            canvas.width = img.width;
            canvas.height = img.height;

            // Draw the image onto the canvas
            context.drawImage(img, 0, 0);

            // Convert the canvas content to a PNG blob
            canvas.toBlob(function(blob) {
                const item = new ClipboardItem({ "image/png": blob });
                navigator.clipboard.write([item]).then(function() {
                    console.log("Image copied to clipboard!");
                }).catch(function(e) {
                    console.log("Failed to copy image: " + e);
                });
            }, "image/png");
        };

        // Set the source of the image to trigger the onload event
        img.src = element.src;
    });
});
```

**Comment by Fred-Vatin** [comment]
Thanks @jsr-p. Works perfectly and saving as png with transparent support is awesome.

Here is my version that add the key to the clipboard and notifies if copy is success or fail.
```js
mapkey("yE", "#7Copy image to clipboard", function () {
	Hints.create("img", function (element) {
		// Create an off-screen canvas
		const canvas = document.createElement("canvas");
		const context = canvas.getContext("2d");

		// Create a new Image object
		const img = new Image();
		img.crossOrigin = "Anonymous"; // Handle cross-origin images

		img.onload = function () {
			// Set canvas dimensions to match the image
			canvas.width = img.width;
			canvas.height = img.height;

			// Draw the image onto the canvas
			context.drawImage(img, 0, 0);

			// Convert the canvas content to a PNG blob
			canvas.toBlob(function (blob) {
				const timeout = 3000;
				const item = new ClipboardItem({ "image/png": blob });
				navigator.clipboard
					.write([item])
					.then(function () {
						Front.showBanner("Image copied to clipboard!", timeout);
					})
					.catch(function (e) {
						Front.showBanner("Failed to copy image: " + e, timeout);
					});
			}, "image/png");
		};

		// Set the source of the image to trigger the onload event
		img.src = element.src;
	});
})
```
