### ISSUE TITLE
Setting font size for hinting?

### ISSUE THREAD

**Issue by larsks** [brookhong/Surfingkeys#1048]
## Prelude
* Could you find answer in below documents? No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes.

## Error details

SurfingKeys: 0.9.48

Browser: brave-browser-0.69.135-1.x86_64 on Fedora 30

URL: All of them

## Context

The font size that SurfingKey uses for link hinting is too small on my monitor. I was hoping I could change the font size by setting the `font-size` property for `.sk_theme`, e.g:

```
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 16pt;
    background: #24272e;
    color: #abb2bf;
}
```

But that didn't seem to have any effect. Is there a way to make the link hints larger?

**Comment by mrjackphil** [comment]
You can find a description here. 
https://github.com/brookhong/Surfingkeys#styling

So, you can add something like this
```
Hints.style('font-size: 10pt;')
```
into your settings file and it will increase font-size

**Comment by julienxaop** [comment]
Could we reopen this issue since the proposed solution (Hints.style('font-size: 10pt;')) wont work anymore .

Thanks.

**Comment by VioletJewel** [comment]
yeah. what's the style setting or option for this?

**Comment by VioletJewel** [comment]
got it finally

```javascript
api.Hints.style(
  "border: solid 0px #C38A22;padding: 1px;background: #b16286",
  "text"
);
```
