### ISSUE TITLE
按 `t` 列出标签页的速度有点慢

### ISSUE THREAD

**Issue by deerainw** [brookhong/Surfingkeys#1049]
按下 `t` 列出所有标签页的速度比较慢, 搜索框出现后基本都需要再等上 0.5 秒才会列出标签, 但是 `T` 的表现就很快.
是因为 `t` 的列表还要搜索书签和历史记录的缘故吗, 可不可以在设置中让 `t` 只加载当前打开的标签?

**Comment by brookhong** [comment]
是的，`t`需要搜索更多URL数据。
你可以在设置中增加

    map("t", "T");

如果不需要overlay这种显示方式，希望跟`t`的显示方式一样，可以再加入

    settings.tabsThreshold = 0;

**Comment by deerainw** [comment]
@brookhong 

谢谢!!

还有一个问题, 既然 `t` 是按最近使用的顺序来列出标签页, 可不可以考虑默认选中下面的第一个候选项? 也就是 `map("t", "t ↓")` 这样的感觉.

虽然有 `<Ctrl-6>` , 但是我往往并不知道上一个标签到底是哪个, 所以大多数时候都是按下 `t` 之后还需要再按一下 ↓ 然后回车, 如果可以省掉按 ↓ 这一下就很人性化了, 而且默认光标下移一格也不会影响搜索框内的输入或是继续向下选择.

**Comment by vmvz** [comment]
> @brookhong
> 
> 谢谢!!
> 
> 还有一个问题, 既然 `t` 是按最近使用的顺序来列出标签页, 可不可以考虑默认选中下面的第一个候选项? 也就是 `map("t", "t ↓")` 这样的感觉.
> 
> 虽然有 `<Ctrl-6>` , 但是我往往并不知道上一个标签到底是哪个, 所以大多数时候都是按下 `t` 之后还需要再按一下 `↓` 然后回车, 如果可以省掉按 `↓` 这一下就很人性化了, 而且默认光标下移一格也不会影响搜索框内的输入或是继续向下选择.

非常赞同这个建议, 默认第一个结果是最好的, 和 alfred 一样,这样就很舒服了

**Comment by vmvz** [comment]
> 是的，`t`需要搜索更多URL数据。
> 你可以在设置中增加
> 
> ```
> map("t", "T");
> ```
> 
> 如果不需要overlay这种显示方式，希望跟`t`的显示方式一样，可以再加入
> 
> ```
> settings.tabsThreshold = 0;
> ```

目前macOS 选择也无法用 ctrl + 数字呀
