### ISSUE TITLE
Tab selection only shows current window's tabs

### ISSUE THREAD

**Issue by igorrafael** [brookhong/Surfingkeys#105]
[This line](https://github.com/brookhong/Surfingkeys/blob/75301a143f6531b04065ad15fe6dea64f536cdb5/background.js#L412) restricts the tab query to the current window. In my use case, it would be interesting to see tabs from all windows.

I can implement this alternate behaviour myself but I don't want to mess the 'getTabs' function as it is used in the "Open an URL" command. Do you have any recommendations or pointers about how I should add this function before submitting a pull request?

**Comment by brookhong** [comment]
Thanks.

I have made `getTabs` to accept input queryInfo, you could use it as below to get all Tabs for all windows,

    runtime.command({
        action: 'getTabs',
        queryInfo: {}
    }, function(response) {
        console.log(response);
    });

https://github.com/brookhong/Surfingkeys/blob/9cd2d92ae7d63a6dbeb97d27591b0ea203175148/background.js#L411

**Comment by igorrafael** [comment]
Much appreciated!
