### ISSUE TITLE
Use easymotion to change scroll target

### ISSUE THREAD

**Issue by masaeedu** [brookhong/Surfingkeys#1053]
Hello. Thanks for a very useful extension, it's changed my browsing experience completely (for the better).

I have some issues with scrolling still, so that's basically the only reason I end up needing to reach for my mouse. Basically the issue is that there's too many scroll targets on the average webpage, so cycling through them one by one using `cs` makes it very tedious to move around.

Would it be possible to construct some kind of tree model of the DOM and provide easymotion style shortcuts (the kind you get when you try to pick a clickable element using `f`), for choosing the scroll target when using `cs`?

**Comment by adberard** [comment]
`;fs` Display hints to focus scrollable elements

**Comment by masaeedu** [comment]
@adberard Thanks!
