### ISSUE TITLE
help: a keyboard shortcut for back button dropdown

### ISSUE THREAD

**Issue by rubaboo** [brookhong/Surfingkeys#1054]
I would like to be able to open tab history (a drop-down that appears when right-clicking the back button) using a keyboard shortcut, Alt+Down for example. I think it's possible to add a custom shortcut using Surfingkeys extension, but I need a piece of code that invokes the drop-down. Would you be able to provide the code?

I realize this is not strictly an issue with Surfingkeys, but I don't know where else to turn for help. I miss this shortcut a lot, I used to have it in keyconfig long time ago, and I tried the code I had in keyconfig with Surfingkeys, but it didn't work.

**Comment by lennonwoo** [comment]
Hi, that's an interesting question. The current tab history is useful for user. But as far as I know, the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) doesn't provide an interface for the developer to get this information due to privacy reasons. And the Surfingkeys' history acquires the whole browser history.

Maybe the Surfingkeys could save every tab history into its cache to implement this function?

**Comment by brookhong** [comment]
Maybe `H`(Open opened URL in current tab) could help you.

**Comment by rubaboo** [comment]
`H` does show history (although I'd prefer most recent on top), but it opens a new tab. I want to stay in the same tab. I could also just press back button repeatedly, but from the drop-down I can go right where I want in history, without revisiting each step.
@lennonwoo I just want to invoke the drop-down of the Back button. I don't know anything about developing for Firefox, but that sort of thing used to be possible in the old Firefox, before WebExtensions. I would think if there is any API involved, it's not History API, but some sort of API that calls the same event that happens when I right-click the Back button.

**Comment by rubaboo** [comment]
Ok, here is some silly pseudo-code I made to illustrate my point. Is something like this not possible?
```
mapkey('Alt+Down', 'Show tab history', function() {
    BackButtonDropdown.show();
}
```

**Comment by lennonwoo** [comment]
Year, old Firefox provides more freedom for users, and I missing the time to use Vimperator, we can even open a terminal then execute scripts in Firefox. Currently, there seems no way to display the current tab's history as we right-click the Back button via mouse, maybe add some hook when we navigate websites in Surfingkeys internal would work. But we could change Surfingkeys' default setting to display history most recent on top via
`settings.historyMUOrder = false;` and mapkey to open url in current tab via
```
mapkey('<Alt-ArrowDown>', 'Show tab history', function () {
    Front.openOmnibar({type: "History", tabbed: false})
});
```

**Comment by LakeishaKowalczyk** [comment]
@rubaboo 
Shift-Enter to open selected item in current tab and close omnibar.

**Comment by rubaboo** [comment]
@LakeishaKowalczyk 
Thanks, that is almost what I was looking for. Would be awesome if it would move in history, instead of appending a duplicate into it.
