### ISSUE TITLE
API question about switch tabs

### ISSUE THREAD

**Issue by Wsine** [brookhong/Surfingkeys#1056]
Sorry for not using the template to create this issue.

I got used to use alt/command + number_key to switch to tab index, e.g. alt + 1 to switch to the first tab. However, this hotkey is not the same in Windows platform. The default is ctrl + num.

When i am trying to create advanced setting for Surfingkeys, it seems that there is no api for user to switch to specific tab. I just look at the description about [Switch-tabs](https://github.com/brookhong/Surfingkeys#switch-tabs) in REAMDE. Is it possible to do so?

Looking forward for your reply.

With regrads

**Comment by brookhong** [comment]
You could use a number followed with `T` to switch to the target tab, such as `12T` will switch to the 12th tab. Related issue https://github.com/brookhong/Surfingkeys/issues/548

**Comment by Wsine** [comment]
I have got the solution from vimium. link is here -> https://github.com/philc/vimium/issues/3417. 

hope that help for someone with similar need.
