### ISSUE TITLE
火狐中「t」地址栏的两个问题

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [brookhong/Surfingkeys#1058]
可不可以支持火狐内置书签的「关键词」
比如输入「ytb」打开「youtube.com」
![图片](https://user-images.githubusercontent.com/14090545/67706108-18cd7d00-f9f3-11e9-94f6-f46a9523c769.png)

当历史记录数量「庞大」时，地址栏会有明显的卡顿
因为有几百兆的历史文件，每次按「t」都会卡顿两秒左右．卡顿的过程中输入框会丢失键击，反应迟顿
有没有可能优化一下性能（使用内置的地址栏时，反应是实时的）
或者默认不展示书签与历史候选列表，按「Tab」再进行搜索
或者在后台载入历史记录的时候，使其不会影响到输入框接受键击与显示字符．候选列表延迟两秒显示应该没有太大影响，反正输入需要搜索的内容，也要用一些时间

现在暂时用 「Alt-d」代替「t」来用，不好用，伐开心 😢

**Comment by crocket** [comment]
`b`
