### ISSUE TITLE
Surfingkeys blocks website

### ISSUE THREAD

**Issue by JennyDracos** [brookhong/Surfingkeys#1063]
## Error details

SurfingKeys: 0.9.49
Browser: Firefox 70.0 Windows 10
URL: https://dostmann-electronic.de/home.html

## Context

When loading certain websites, I am unable to access almost any link on the page.  This includes via hinting and via direct clicking.  It also doesn't matter whether SurfingKeys is enabled for the site or not.  The only way I can access the page is to disable the extension in Firefox and reload the page.

**Comment by brookhong** [comment]
Should have been fixed in 0.9.51
