### ISSUE TITLE
Firenvim integration

### ISSUE THREAD

**Issue by adelin-b** [brookhong/Surfingkeys#1064]
I
![Peek 2019-11-01 19-49](https://user-images.githubusercontent.com/23508913/68048637-452e1580-fce1-11e9-8099-aa3af6b40db0.gif)
 think this gif will be pretty much self-explanatory

The integration could be :
- [ ] replace the ace editor or embed firenvim in it
  - [ ] zf
  - [ ] i
  - [ ] I
  - [ ] C-i
  - [ ] gi

https://github.com/glacambre/firenvim

**Comment by hbt** [comment]
@adberard  what's the name of the autocomplete plugin you are using in the gif?

Thanks

**Comment by adberard** [comment]
@hbt coc.nvim with coc-browser plugin, it provide current webpage words as completion source.
