### ISSUE TITLE
网页有些内容不能自动加载

### ISSUE THREAD

**Issue by SpecN997** [brookhong/Surfingkeys#1065]
## Error details
在比如https://www.youtube.com/user/LinusTechTips/videos 的【视频】（【首页】和【播放列表】之间）页面，往下翻页的时候，顶部图片并不会随上滚动并消失，下方的视频缩略图在若干行后开始灰色并不加载，拉到最底并不会加载更久之前的视频。同样类似情况还发生在https://t.bilibili.com/ ，往下拉之后会出现灰色像是没有加载出来的内容一样。似乎是chrome升级到78之后出现的问题，但并不确定。
症状在禁用插件之后消失。

SurfingKeys: 0.9.51

Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

URL: <https://www.youtube.com/user/*/videos>,<https://t.bilibili.com>

## Context

**Comment by rovo98** [comment]
遇到同样的问题， Surfingkeys 升级到 0.9.51 之后出现的。我的猜测，可能有些网页内容的加载（懒加载）依赖于滚动事件，而 Surfingkeys 对特定情况下对滚动事件进行了阻止控制。(只是简单看过 0.9.51 的更新的 commit，没有看过完整的代码)

https://github.com/brookhong/Surfingkeys/blob/22c96bdb4d98a61b619977d38880ede0d3bbad32/content_scripts/normal.js#L143-L153

https://github.com/brookhong/Surfingkeys/blob/22c96bdb4d98a61b619977d38880ede0d3bbad32/content_scripts/utils.js#L468-L478

https://github.com/brookhong/Surfingkeys/blob/22c96bdb4d98a61b619977d38880ede0d3bbad32/content_scripts/front.js#L531-L542


似乎因为某些原因，而阻止滚动事件的触发。

只有在 ``suppressScrollEvent === 0`` 情况下，才可能再次触发滚动事件，使得内容继续加载

实际测试时，当页面出现懒加载时（在确保所有请求资源全部完成的情况下），多次反复滚动是可以再次触发滚动事件的，使内容得以完成加载。

但是，有时却始终无法完成内容的加载 (``suppressScrollEvent > 0``吧)

测试网站：https://www.bilibili.com/

browser: chrome 78 ,  linux

**Comment by brookhong** [comment]
刚发了0.9.52，你们试试，我测了下https://www.youtube.com/user/LinusTechTips/videos。

**Comment by rovo98** [comment]
> 刚发了0.9.52，你们试试，我测了下[https://www.youtube.com/user/LinusTechTips/videos。](https://www.youtube.com/user/LinusTechTips/videos%E3%80%82)

问题已解决

**Comment by SpecN997** [comment]
已解决，感谢两位。
