### ISSUE TITLE
0.9.53更新后autocmd失效

### ISSUE THREAD

**Issue by feng84** [brookhong/Surfingkeys#1068]
环境：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

案例：https://music.163.com 完全失效，https://www.google.com 有时失效

可能：好像是 content_scripts.js 有时省略加载

我对整个插件不太了解，作者有空看看能修复不 ，谢谢！

**Comment by feng84** [comment]
虽然 _initContent 在前，但 applySettings 在 callback 里，导致在设置 AutoCommands 前， AutoCommands 已经被处理了

        setTimeout(function () {
            // to avoid conflict with pdf extension: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/
            for (var p in AutoCommands) {
                var c = AutoCommands[p];
                if (c.regex.test(window.location.href)) {
                    c.code();
                }
            }
        }, 0);

我现在 setTimeout 为 1000 绕过去了

**Comment by brookhong** [comment]
这个autocmd似乎有点多余，我在想要不要删掉这个API。因为用户其实完全可以写成

    if (window.origin === "https://translate.google.com") {
        // your code for the domain
    }

**Comment by brookhong** [comment]
Fixed in 0.9.54.

**Comment by feng84** [comment]
这个修改能加载 autocmd，但 document 还没完全准备好， 对 dom 的操作放在事件 DOMContentLoaded 里就能正常工作了。

if (window.origin === "https://translate.google.com") {
    // your code for the domain
    document.addEventListener('DOMContentLoaded', function (e) { action });
}
也是如此
