### ISSUE TITLE
I keep triggering an unknown menu

### ISSUE THREAD

**Issue by benjamin-thomas** [brookhong/Surfingkeys#1070]
## Prelude
* Could you find answer in documentation? --> no

## Error details

SurfingKeys: `0.9.53`

Browser: `Version 78.0.3904.70 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)`
Window manager: `i3`

## Context

Please see the following screenshot:

![image](https://user-images.githubusercontent.com/1557738/68477236-35f11f80-022d-11ea-9216-01b86f1e1a23.png)

I've been using SurfingKeys for some time, but lately I keep triggering this popup menu. Over and over, it's very frustrating. Sometimes, there is some kind of delay because I haven't pressed any keys for a few seconds, then this menu pops up.

I don't think this is SurfingKeys's fault, however I'm lost, don't know what to look for.

Could you please tell me the name of this function/or the default keybindings that's suppose to trigger this? So I can disable it. I did look around.

Thanks, and sorry for polluting the issue tracker.

**Comment by brookhong** [comment]
You could add below in your setting to disable rich hints(the popup menu).

    settings.richHintsForKeystroke = 0;

But the problem is why there is some unexpected key event in your browser, SurfingKeys only show the rich hints when there is key event firing.

**Comment by benjamin-thomas** [comment]
For sure. Thanks I'll let you know how it goes.

Under normal circumstances, which key combination would trigger this popup menu please? I'm not sure I follow what's going on here.

**Comment by brookhong** [comment]
Surfingkeys displays key stroke for all key combinations, please see https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/normal.js#L279

You could open `Inspect` tool and use below code to check what key event is fired on the earth.

        window.addEventListener("keydown", function (event) {
            console.log(event);
        }, true);

**Comment by benjamin-thomas** [comment]
Yeah the problem is that popup takes the whole height and masks the show keystroke dialogue (I think).

And the triggering is kind of random. I'm window switching or tab switching all over the place, and I suspect some kind of modifier key or combination of modifier keys triggers that state.

Thanks for the snippet suggestion, although I don't think I'll be able to inject that snippet on every page visit (my workflow involves opening many many tabs, closing windows, reopen more tabs, etc. and I'll randomly hit that "bug")

**Comment by benjamin-thomas** [comment]
@brookhong I'm closing this as disabling "rich hints" did the trick for me.

That problem was not easily reproducible but I'm pretty sure it was caused by the `MetaLeft` key I use to switch virtual desktops.

    KeyboardEvent {isTrusted: true, key: "Meta", code: "MetaLeft", location: 1, ctrlKey: false, …}

The "rich hint" triggers (I see a little black and empty square) once I move out of my browser window then resumes oddly once I put the window back into focus.
