### ISSUE TITLE
Unsuccessful focus of a scrollable element

### ISSUE THREAD

**Issue by n0amso1** [brookhong/Surfingkeys#1071]
## Prelude
* Could you find answer in below documents? No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes.

## Error details

SurfingKeys: 0.9.53

Browser: Firefox 70.0.1, Arch

URL: https://i3wm.org/docs/user-contributed/workspace-current-output.html

## Context

I was trying to scroll left on the inner scrollable element containing the script on the website by pressing `;fs` and then selecting the scrollable.  
Surprisingly, the scrollable wasn't focused, so when scrolling left nothing happened, and scrolling down actually scrolled the entire page.

**Comment by TheGreatMcPain** [comment]
I'm also experiencing this.

Same version of firefox (70.0.1), but on Gentoo.

**Comment by brookhong** [comment]
Fixed in 0.9.54.
