### ISSUE TITLE
Uncaught TypeError: Cannot read property 'skScrollBy' of undefined

### ISSUE THREAD

**Issue by LKC314** [brookhong/Surfingkeys#1072]
## Error details

SurfingKeys: 0.9.53

Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3962.2 Safari/537.36

URL: https://loj.ac

## Context

When using the page scroll shortcut provided by Surfingkeys, the scroll bar disappears. Then, the shortcut keys provided by Surfingkeys and the native arrow keys can't scroll the page. The only way I know of scrolling the page is to refresh the page and drag the scroll bar with the mouse.

When open the Console with F12, the error "Uncaught TypeError: Cannot read property 'skScrollBy' of undefined" is sometimes displayed, but sometimes there are no errors in the Console (the page cannot be scrolled yet).

When an error is displayed:

```
Uncaught TypeError: Cannot read property 'skScrollBy' of undefined
    at l.a.scroll (modules.min.js:1)
    at modules.min.js:1
```

**Comment by brookhong** [comment]
Fixed in 0.9.54.
