### ISSUE TITLE
Default mappings firing on page load

### ISSUE THREAD

**Issue by yusufaktepe** [brookhong/Surfingkeys#1073]
## Error details

SurfingKeys: 0.9.53

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

URL: *
## Context

After the latest update, SurfingKeys default mappings fires if I press them while page is loading.
For example; if I press down "s" key, it opens stackoverflow even though I unmapped and replaced this key in my config.

**Comment by brookhong** [comment]
Fixed in 0.9.54.
