### ISSUE TITLE
Surfingkeys interferes with Daum Dic.

### ISSUE THREAD

**Issue by demokritos** [brookhong/Surfingkeys#1075]
## Prelude
* Could you find answer in below documents?
No, I couldn't.

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes, but I couldn't find.

## Error details

SurfingKeys: 0.9.53

Browser: Firefox 70.0.1 (Arch Linux)

URL: https://dic.daum.net/word/view.do?wordid=eew000000170&q=hello

## Context

The site of the above URL is a dictionary site. In that page, Clicking on words in the definition, like 'expression' or 'greeting', shows a popup. However, if Surfingkeys is enabled, the popup does not keep showing, but immediately disappears.

**Comment by brookhong** [comment]
Fixed in 0.9.54.
