### ISSUE TITLE
Reload settings from file?

### ISSUE THREAD

**Issue by for-coursera** [brookhong/Surfingkeys#1078]
Is it possible to reload settings from a given file (re-read a config)? I tried something like this:

    const srcPath = "file:///Users/me/.surfrc";
    mapkey("sr", "#0Reload settings", function() {
        RUNTIME('loadSettingsFromUrl', {
            url: srcPath
        }, function(res) {
            Front.showBanner(res.status + ' to load settings from ' + srcPath, 900);
        });
    });

but it doesn't seem to work :(

**Comment by brookhong** [comment]
You could just refresh your page, as long as you have specified the source path of your config file in settings.

But there is no way to reload settings after page loaded.

**Comment by for-coursera** [comment]
Surfingkeys is the best! Thanks :)
