### ISSUE TITLE
[Feature Request] Support press f like Vimium.

### ISSUE THREAD

**Issue by kevinhwang91** [brookhong/Surfingkeys#1084]
In Surfingkeys, press `f` and follow the hint but combine `shift` with the last char of hint will open a new tab like an action `af', This action in Vimium will open a new tab but stay in the current tab like 'gf'. Please make an option to compatible with this action, because many guys have used Vimium long time.

**Comment by ahartschen** [comment]
You can do this already.

Go to advanced settings and put `map('F', 'C');`

Now 'F' will function the same way it does on Vimium.

**Comment by kevinhwang91** [comment]
> You can do this already.
> 
> Go to advanced settings and put `map('F', 'C');`
> 
> Now 'F' will function the same way it does on Vimium.

I'm sorry, you don't get my point. Please try to press `f` and then press char with `shift` to follow the hint, you will find different actions between Surfingkeys and Vimium.
