### ISSUE TITLE
t 标签页结果 如何快速选择结果, 只能方向键吗?

### ISSUE THREAD

**Issue by vmvz** [brookhong/Surfingkeys#1085]
t to search bookmarks/history urls

![image](https://user-images.githubusercontent.com/1652700/69768811-1bbbb900-11bd-11ea-9e99-224439f8ee08.png)

如何快速选择结果, 只能方向键吗?谢谢

**Comment by Dligenz** [comment]
同问，当标签超过10个就无法通过快捷键切换标签了，是否只能方向键切换
![2019-12-15_002046](https://user-images.githubusercontent.com/36071624/70851516-18207580-1ed1-11ea-8859-1044176c9171.png)

**Comment by Dligenz** [comment]
同问，是否超过10个标签页之后就没有快捷键快速选取了
 
![2019-12-15_002419](https://user-images.githubusercontent.com/36071624/70851536-56b63000-1ed1-11ea-837d-42f8694919f8.png)

**Comment by Dligenz** [comment]
同问，如何快速切换

**Comment by DrakeXiang** [comment]
You can use `tab` and `shift+tab` to navigate through results

**Comment by joy2fun** [comment]
try `control+n` `control+p`
