### ISSUE TITLE
Firefox 72.0b1 无限自动刷新页面

### ISSUE THREAD

**Issue by McGiRG3z** [brookhong/Surfingkeys#1087]
刚更新Firefox Beta至最新版72.0b1，该扩展会导致任何网页都无限自动刷新。请开发者核查。

**Comment by Stvad** [comment]
I believe it's a duplicate of https://github.com/brookhong/Surfingkeys/issues/1076

**Comment by brookhong** [comment]
Fixed in 0.9.55
