### ISSUE TITLE
pdf gets converted to html

### ISSUE THREAD

**Issue by tractatusviii** [brookhong/Surfingkeys#1088]
Absolutely love this extension! Wish you guys all the best
keep bumping into this issue though: 
every time i want to download a pdf i opened in chrome i have to disable surfingkeys for a brief spell and reload the page(pdf doc) because the pdf is converted to html, i assume for the crawling purposes and such, but it's still hella annoying.

**Comment by brookhong** [comment]
You could press `;s` to turn off built-in pdf viewer from Surfingkeys, then you could use pdf viewer from Chrome itself.

**Comment by tractatusviii** [comment]
The more you know! Thanks a ton!
