### ISSUE TITLE
open link in background and rapid links launch?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#109]
Hi!

I just discovered surfingkeys and i must say im blown away..maybe this is *finally* the extension that allows me to leave vimperator and join the dark side (chrome :)).

i have many question but ill start with this. i saw the 'f' works as usual to launch/follow links. Yet how does one open links in the background ('F' in most vim like browser extensions)? also is there a way to launch several links at once before the hint view closes?

thx alot

Z

**Comment by brookhong** [comment]
Thanks.

Please see https://github.com/brookhong/Surfingkeys/wiki

    map('F', 'gf');

will let you use `F` as vimium.

To launch several links, you could use `cf` (continuously follow).
