### ISSUE TITLE
I can't remap 'x' to "<Ctrl-w>" and 'X' to "<Ctrl-Shift-t>".

### ISSUE THREAD

**Issue by crocket** [brookhong/Surfingkeys#1095]
## Error details

SurfingKeys: 0.9.54

Browser: Vivaldi 2.9.1705.41 Gentoo Linux

URL: Anywhere

## Context

When I close the last tab in `x`, it triggers exit confirmation dialog.
`Ctrl-w` doesn't try to close the window with the last tab.
When I reopen the recently closed tab with `X`, it respawns the tab at the right side.
`Ctrl-Shift-t` restores the tab in its original position. The original position can be to the left of the current tab.

I tried to mimick Ctrl-w and Ctrl-Shift-t with x and X.

```
map('x', '<Ctrl-w>');
map('X', '<Ctrl-Shift-t>');
```

This doesn't work.

**Comment by crocket** [comment]
It seems `map` only remaps keyboard shortcuts that were bound by `mapkeys`.
Unless I have access to vivaldi API, I cannot simulate the effect of `Ctrl-w` and `Ctrl-Shift-t` in vivaldi.

**Comment by hoohyaIII** [comment]
// try this?
map( '<Ctrl-w>','x');
map('<Ctrl-Shift-t>','X' );

**Comment by crocket** [comment]
I stopped using surfingkeys a while ago.
