### ISSUE TITLE
dejk滚动总是在更小的层面上，而不是对整个页面

### ISSUE THREAD

**Issue by fysly** [brookhong/Surfingkeys#1098]
比如浏览[知乎](https://www.zhihu.com/question/345303450)时对某个回答按了「收起」，但Surfingkeys总是选择在该回答里滚动，而不是正常地滚动整个外部页面。又比如[百度贴吧](http://tieba.baidu.com/p/6379853183)等，有些长图默认是折叠的，Surfingkeys也总是会去滚动这个本不该被滚动的图片。再比如[少数派](https://sspai.com)等网站，滚动功能一定概率会失效。

之前使用Vimium完全没遇到过上述这些问题。

可能不太好理解，于是录了一个视频展示：在知乎问题页面对某回答点了收起后，再使用dejk进行滚动就会产生这种表现。
https://www.dropbox.com/s/bizw0gcwcqywige/surfingkeys-dejk.mp4?dl=0

**Comment by brookhong** [comment]
这个问题在最新版本里已经解决了。
