### ISSUE TITLE
combined omnibar?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#110]
Hi again

i wonder if there is anyway to get a combined omnibar?  that is when pressing 't'  alongside the launch from history ,if no history is available use default search engine to search for the current string?

thx again for your amazing work, really enjoying using it!

Z

**Comment by brookhong** [comment]
![ffa](https://cloud.githubusercontent.com/assets/288207/21723596/ffccd634-d46b-11e6-9919-23ee2b6525db.gif)

**Comment by zeltak** [comment]
looks great! any documentation on this?

thx!!

Z

**Comment by brookhong** [comment]
Released in 0.7.0

Please have a try.

**Comment by zeltak** [comment]
cool works really well! 

thx so much!

Z
