### ISSUE TITLE
Surfingkeys能动态调用本地文件吗？这样我修改本地js文件，自动执行最新的代码

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#1102]
如题，因为具体实现的js代码要反复调试，
目前调试是刷新Surfingkeys，再刷新网页，再按键调试，太麻烦了。

**Comment by brookhong** [comment]
请看https://github.com/brookhong/Surfingkeys/issues/1078

**Comment by hyaray** [comment]
感谢帮助！！！
我是想实现配置文件不变，函数执行定义在B文件，
每次运行f函数都读取B文件的f函数执行，这样可行吗？
这样我修改B文件后，Surfingkeys和网页都不用再刷新，就已经执行新的内容了。
我的 Tampermonkey 也是这样设计的，配置和执行分开两个文件保存，体验相当好。
