### ISSUE TITLE
Scrolling-related problems with privacy.resistFingerprinting enabled in Firefox

### ISSUE THREAD

**Issue by papersplease** [brookhong/Surfingkeys#1107]
## Error details

SurfingKeys: 0.9.55

Browser: Firefox 71.0 on Windows 10 build 1903 (18372.476) x64

## Context

Enabling privacy.resistFingerprinting in Firefox's about:config seems to break the smooth scrolling in this addon. Scrolling with j/k/d/u becomes jerky. `G` and `gg` don't scroll to the bottom and top of the page anymore. On the other side, mouse scrolling, or using ↑/↓/PgUp/PgDn (native hotkeys) works perfectly smooth as expected.

Additionally, some key combinations don't always work (such as `gg`), I suspect it might break something else as well.

Edit: it seems the problem is with the input as well, for example `<Alt-i>` also doesn't work.

**Comment by JingYenLoh** [comment]
Great find, I've been stuck with this issue for a while. Could this also be related to #979 ?

**Comment by papersplease** [comment]
I've found that the Surfingkeys doesn't recognise `<Alt>` at all while resistFingerprinting is enabled, so any command requiring it won't work. Sequential combinations like `<23j>` or `<gg>` either glitch or don't work. `<Shift>` seems to be working fine for me.

**Comment by brookhong** [comment]
With `resistFingerprinting` enabled, smooth scrolling works fine on my environment ( Firefox 68.6, MacOS 10.14).

But `Alt-s` does get broken, and the reason is that `event.keyCode` is set to 0 when Alt key is held by Firefox, the data from key event looks like below:

    event.key: "ß"
    event.keyCode: 0

**Comment by papersplease** [comment]
Apparently that feature breaks `Alt` by design. Remapping seems to be the only workaround. https://bugzilla.mozilla.org/show_bug.cgi?id=1598862#c3

Different implementations of smooth scrolling also behave erratically almost everywhere in 73.0 on Windows, mostly due to reduced timer precision and additional jitter introduced by this. So not a Surfingkeys issue as well I guess.
