### ISSUE TITLE
feature request - go to last scroll position

### ISSUE THREAD

**Issue by P4ndemic** [brookhong/Surfingkeys#1110]
Similar to what cvim provides "mapping name: lastScrollPosition"
https://github.com/1995eaton/chromium-vim

As an example of the functionality: 
you are scrolled to somewhere in the middle of a page
you press gg to get to the top of the page
now you want to get back to where you just were -> lastScrollPosition

Thank you for taking the time to review the feature request.

EDIT: I found out that something similar can be achieved by putting a mark before you jump to the top for the example above. Still would be great if those marks could get set automatically when any "jump" action is performed

**Comment by brookhong** [comment]
You could use [vim-like marks](https://github.com/brookhong/Surfingkeys#vim-like-marks)

**Comment by P4ndemic** [comment]
yes thank you for your answer, I also use them, but it sometimes happens that I "involuntarily" jump to the top of the page. It's probably caused by some wrong window focusing in Gitlab, but I thought fixing that issue might be hard / quite specific to Gitlab with different windows in the active browser tab. 

For example when I do code-review on Gitlab, write a comment and then after sending the comment try to scroll down, surfing keys focuses another window or something of the sort, jumping to the top of the page. Similar things happen in similar plugins as well, but the "hack" with jumping to the last position is also a fix for probably a harder underlying problem to fix

**Comment by Tanath** [comment]
I'm also used to having this feature. I keep pressing `'` `'` out of habit before I figure out it doesn't work with Surfingkeys.

**Comment by ankitp4t3l** [comment]
I'm thinking one could personally map jump commands such as `gg` or `G` to perform the jump *and* the mark creation. I'll have to hunt for the mark creation function though.
