### ISSUE TITLE
Error when "load unpacked" on chrome

### ISSUE THREAD

**Issue by ahlearn** [brookhong/Surfingkeys#1111]
I would like to use the latest version downloaded from github by "load unpacked" on chrome, but I got the following error message:
  `Could not load javascript 'content_scripts/modules.min.js' for content script`
I couldn't find that file from the github page.  If I remove that line from manifest.json, I got other error after loading.  Did I miss something? Any help appreciated!

**Comment by brookhong** [comment]
You can not simply load the source, you need run `npm run build` first, then load `<Surfingkeys_root>/dist/Chrome-extension/`.

If you work on Firefox, run `npm run build firefox`, then load `<Surfingkeys_root>/dist/Firefox-extension/`.
