### ISSUE TITLE
Youtube sidebar cannot be scrolled by j and k.

### ISSUE THREAD

**Issue by crocket** [brookhong/Surfingkeys#1112]
# Error details

SurfingKeys: 0.9.54

Browser: Vivaldi 2.10.1745.21 (Chrome 79.0.3945.94) Gentoo Linux

URL: https://www.youtube.com

## Context

After pressing `;fs` and choosing the hint for the youtube sidebar, `j` and `k` don't scroll the sidebar.

This issue doesn't exist on

* Firefox 68.2.0esr (64-bit)
* Google chrome 78.0.3904.108
* Brave 1.0.1 (Chromium 78.0.3904.108)

**Comment by crocket** [comment]
I realized that this issue was caused because `j` and `k` was passed to vimium.

**Comment by x61** [comment]
@crocket, how did you resolve this issue?

**Comment by crocket** [comment]
I don't use this extension. So, I can't tell. But, it seems that I was using vimium and surfingkeys simultaneously.

vimium could conflict with surfingkeys.
