### ISSUE TITLE
`su` and `sU` are ignored in the first try.

### ISSUE THREAD

**Issue by crocket** [brookhong/Surfingkeys#1116]
## Error details

SurfingKeys: 0.9.54

Browser: Vivaldi 2.10.1745.21 on Gentoo Linux

## Context

After I visit a web page, if I press `su` or `sU`, edit the URL, and press enter, nothing happens.
If I do it again, a modified URL is visited.

**Comment by brookhong** [comment]
Fixed in 0.9.56.

**Comment by crocket** [comment]
Excellent.
