### ISSUE TITLE
Feature request: allow unmapping of number keys

### ISSUE THREAD

**Issue by Avi0** [brookhong/Surfingkeys#1117]
Hi,

Can you add functionality of unmapping the number keys? I don't need the repeat functionality at all, but I want to pass the number keys directly to the web page (useful on YouTube, for example).

Or, if unmapping number keys is impossible, maybe an option to disable the repeat function?

**Comment by brookhong** [comment]
Search `digitForRepeat` in the [README.md](https://github.com/brookhong/Surfingkeys/blob/master/README.md)
