### ISSUE TITLE
Reddit issue

### ISSUE THREAD

**Issue by Philipp0205** [brookhong/Surfingkeys#1118]
First of all thank you for this extention, Surfingkeys is great. 
There is another issue about reddit but this one different.

Everytime I scroll down reddit this happens: 

![reddit_bug_short](https://user-images.githubusercontent.com/36603238/71560885-9f442080-2a6f-11ea-8adb-00e29e4abe36.gif)

A workaroung is to use `cS` but this is annoying. 
Thanks!

**Comment by brookhong** [comment]
Could you please provide the URL of the page in the animation?

**Comment by Philipp0205** [comment]
Yes, it is [https://www.reddit.com/](https://www.reddit.com/).

**Comment by brookhong** [comment]
I know the site, but on which specific page?

**Comment by Philipp0205** [comment]
For me it's every reddit feed that has pictures in it. When it reloads post the focus will switch to a picture and scroll it instead of the whole page. You can try it on the current reddit startpage.

**Comment by brookhong** [comment]
Just had a new release 0.9.57, which should have addressed this issue, please have a try.

**Comment by Philipp0205** [comment]
Works like a charm now. Thank you!
