### ISSUE TITLE
When your customizations are loaded from a URL how do you refresh them?

### ISSUE THREAD

**Issue by vonHabsi** [brookhong/Surfingkeys#1121]
When I create my own key mappings in the Advanced mode on Firefox it is easier to use a normal text editor which saves to a URL than in the browser textbox.

Is there a way to refresh and test the changes you are making without reopening the browser?

**Comment by brookhong** [comment]
You need not reopen your browser to test your setting snippets, just go to a tab, reload the page to try your new key mappings.

Your setting snippets are executed on every page load.

**Comment by vonHabsi** [comment]
I am referring to the case when the settings are from an http URL. If say I'm using emacs, and the file is saved via TRAMP to the remote URL, will every page load try to read the settings from the remote URL?

Because that will slow down page loading unless some caching is employed

**Comment by brookhong** [comment]
It does read the settings from your specified remote URL on every page load, thus remote URL is not the best practice so far.
