### ISSUE TITLE
Do customizations in settings file run in the context of background or content scripts?

### ISSUE THREAD

**Issue by vonHabsi** [brookhong/Surfingkeys#1123]
I am new to working with addons and I believe some kinds of functions will work with content scripts and some with background scripts but not both.

Do the customizations in settings file run in the context of background or content scripts?

**Comment by brookhong** [comment]
It is executed in context of content script, and with some settings passed to background, please refer to https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/content_scripts.js#L338
