### ISSUE TITLE
Half page up / down?

### ISSUE THREAD

**Issue by max-sixty** [brookhong/Surfingkeys#1124]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

https://github.com/brookhong/Surfingkeys/issues/122: Closed issue whose contents is no longer accurate (`d` / `e` are now full page up / down)

## Error details

SurfingKeys: 0.9.55

Browser: Firefox on MacOS

## Context

Is there a mapping for half page up / down? Is there a mapping I could add for it? 
Half page down was my most used key in Tridactyl. Thanks.

**Comment by brookhong** [comment]
`d` / `e`  are half page down / up,  they are not full page actions.

**Comment by max-sixty** [comment]
Are you sure? On the readme it states it's a page (and that's also what happens in my browser)

![image](https://user-images.githubusercontent.com/5635139/72006777-53873900-321e-11ea-9c2f-631166750264.png)

**Comment by max-sixty** [comment]
(you're the maintainer, so maybe people saying "Are you sure" to basic questions is frustrating; I'm trying to square your comment with the readme and what I see on my computer)

**Comment by max-sixty** [comment]
I actually think you're right (and the readme is wrong), but that if the key is held down for more than a moment, it continues scrolling; unlike cVim / vimium / Tridactyl (or normal scroll keys), where the key operates like a more traditional repeat delay.

Does that sound accurate?

**Comment by max-sixty** [comment]
`settings.scrollFriction = 10;` fixed my problem! Thanks. 

Feel free to close, or leave open as a Readme issue

**Comment by brookhong** [comment]
Yes, you're right, there is an error in the document, thanks, will fix that soon.
