### ISSUE TITLE
Dictionary of mapkey-bindable objects and methods, mermaid

### ISSUE THREAD

**Issue by tractatusviii** [brookhong/Surfingkeys#1128]
Hi, @brookhong! I'm absolutely in love with this extension, the more so the more I use it. 
Was wondering if there is a comprehensive list of js functions you can map to mapkey in settings? 
I sort of get what the _Front_ object is and what _showPopup_ method does from the name, but it'd be tremendous if there was a general list of these things. 

I'm asking because i was trying to remap Mermaid to something else than ``Ctrl-Alt-d``( that one just scrolls the page down for me for some reason) and realized i'm not sure what method to call on what.
<3

**Comment by brookhong** [comment]
Sorry, there is no such list, but https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js could be help resource. And for the Mermaid binding, you could try something like

    map(';d', '<Ctrl-Alt-d>');

**Comment by tractatusviii** [comment]
This is super useful.
