### ISSUE TITLE
chrome dark mode flag makes link tags unreadable

### ISSUE THREAD

**Issue by imjuststeve** [brookhong/Surfingkeys#1129]
The latest flag chrome provides dark mode at:
chrome://flags/#enable-force-dark

The popup tags that let you select links are white text on yellow, and hard to read

SurfingKeys: 0.9.57

Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit) - Windows 10

URL: test.com

Context
Just trying to navigate with chrome's chrome://flags/#enable-force-dark enabled

**Comment by brookhong** [comment]
Add below into your setting snippet to change hints style:

    Hints.style('border: solid 3px #552a48; color:#efe1eb; background: none; background-color: #552a48;');



![image](https://user-images.githubusercontent.com/288207/72121104-02e61c00-3395-11ea-87ab-56107082efff.png)

**Comment by imjuststeve** [comment]
Worked like a charm. Ty.

**Comment by imjuststeve** [comment]
Unfortunately the 'v' hint's are also unreadable, I'm sure it's a similar fix?

**Comment by brookhong** [comment]
For the `v` hints, you could set the 2nd parameter `text` of `Hints.style`, such as

    Hints.style("border: solid 3px #707070; color:#efe1eb; background: none; background-color: #707070;", "text");

**Comment by imjuststeve** [comment]
Thanks again!
