### ISSUE TITLE
SurfingKeys neglects a specific URL on a certain page.

### ISSUE THREAD

**Issue by vonHabsi** [brookhong/Surfingkeys#1130]
On the webpage https://tkainrad.dev/posts/managing-my-personal-knowledge-base/ a particular URL is ignored by the link selection keys, whether `f`, `af` or `cf`.

The particular link is [public fraction of my bookmarks database](https://www.notion.so/tkpersonal/047517457f70471a91a9dac793b8d51b?v=802c2ec373fa43d0b7caf16ed8bfccda) and for some reason it is never selected.

The versions are:

Surfing Keys 0.9.57 (both Firefox and Chrome)

Firefox 73.0 beta 2

Chrome - 75.0.3770.142 (Official Build) (64-bit)

I have tried the page with Tridactyl and it works fine.

Is it an unusual Heisenbug, or does the page have some settings that cause it to be ignored

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/72120871-4e4bfa80-3394-11ea-896f-1223978f376f.png)

This is what it behaves on my laptop.

**Comment by vonHabsi** [comment]
I have checked again and that URL appears twice on the page. There is another one just before the end of section **4. Native Bookmark Sources**, which is the one I'm referring to.

[Imgur](https://imgur.com/oLqrEW5)

On closer examination it seems that it has actually been selected but the paragraph been formatted in a way that causes the highlight to display on the paragraph rather than directly over the URL.

**Comment by vonHabsi** [comment]
I am closing this because its not a showstopper, but more of an internal implementation detail which @brookhong may deal with if its a priority. The comparison with Tridactyl is intresting though.

**Comment by vonHabsi** [comment]
I am closing this because its not a showstopper, but more of an internal implementation detail which @brookhong may deal with if its a priority. The comparison with Tridactyl is intresting though.
