### ISSUE TITLE
'yv' cannot copy hint text starts with "A " or "I "

### ISSUE THREAD

**Issue by purhaze** [brookhong/Surfingkeys#1131]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: 0.9.57

Browser: Chrome 79.0.3945.117 Windows 10

## Context

'yv' cannot copy hint text starts with "A " or "I ".

**Comment by brookhong** [comment]
I can not reproduce this, try to reset your settings.
