### ISSUE TITLE
Google 搜索改版，拨号盘乱了，

### ISSUE THREAD

**Issue by toure00** [brookhong/Surfingkeys#1132]
![image](https://user-images.githubusercontent.com/33457469/72514055-f0824b80-3888-11ea-90c1-293a85f7962c.png)
如图，第一行的 url 原来在最下面，现在被改到上面了，拨号时，显得非常凌乱，不容易按到自己想打开的链接，有什么办法解决这么问题吗

**Comment by loyalpartner** [comment]
settings.hintAlign = "left";

**Comment by brookhong** [comment]
0.9.59已经解决。
