### ISSUE TITLE
question: choose tab order

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#1138]
how to make the first element (tab) found when searching for a tab? Now 0 element is selected ie search in the search engine. you have to press the arrow down key to open the first found tab.

**Comment by brookhong** [comment]
Is `settings.focusFirstCandidate` what you want? Please find related info from the doc.

Arrow down is not the only way, you could also use `Tab` and `Shift-Tab`.

**Comment by D1mon** [comment]
Yes. that's what I need. thanks.
