### ISSUE TITLE
图形生成器在mac打开报错

### ISSUE THREAD

**Issue by xuoutput** [brookhong/Surfingkeys#1140]
## Error details

![image](https://user-images.githubusercontent.com/16385443/72773239-6ac41e80-3c41-11ea-86a2-f35aa8a71d33.png)

SurfingKeys: <Ctrl-Alt-d>打开图形生成器

Browser: <79.0.3945.130 (Official Build) (64-bit)><macOS Version 10.14.5 (Build 18F132)>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

<Ctrl-Alt-d>打开图形生成器后报错

**Comment by brookhong** [comment]
这是正常的，它会在页面加载时从剪贴板里读取并渲染成图形，这样做的原因是方便在其他编辑器里编辑完成之后复制，来到这个图形生成器刷新页面就能更新图形。
