### ISSUE TITLE
Command Omnibar

### ISSUE THREAD

**Issue by ArchieMaclean** [brookhong/Surfingkeys#1141]
## Error details

SurfingKeys: 0.9.57

Browser: Chrome

Command omnibar doesn't work in the pdf viewer - any values that are evaluated are not shown. 
For example, type `:4*2` - the result is not given.

**Comment by brookhong** [comment]
Yes, it is expected after `unsafe-eval` was removed from `content_security_policy` of the extension, and no plan to fix it.

**Comment by ArchieMaclean** [comment]
Ok 👍
