### ISSUE TITLE
how to bind key like "Space + num" to go the nth num tab?

### ISSUE THREAD

**Issue by loyalpartner** [brookhong/Surfingkeys#1142]
hello, this plugin is usefull, i already cant leave it.
i have a question, i want to bind `space` 1-9 to switch the nth tab,  i have try it use
```
Normal.feedkeys("99E")
Normal.feedkeys("R")
```
but it not work.

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-go-to-nth-tab

**Comment by megalithic** [comment]
@brookhong how can we rebind that though? 

i've tried just:
```js 
map('<Ctrl-2>', '2T');
```
also:
```js
map('<Ctrl-2>', Normal.feedkeys("2T"));
```

as well as:
```js
mapkey('<Ctrl-2>', "", function() { 
  Normal.feedkeys("2T"); 
});
```

None of these methods are working; is there a proper way?

**Comment by loyalpartner** [comment]
@megalithic tks anyway,  i already use this method
