### ISSUE TITLE
Hint box is in wrong position on google search result page

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#1144]
![image](https://user-images.githubusercontent.com/5415510/73591286-b7540780-4527-11ea-9ace-09f0edcf3f0a.png)

**Comment by loyalpartner** [comment]
```settings.hintAlign = "left"```

**Comment by yech1990** [comment]
still not work with this new settings

![image](https://user-images.githubusercontent.com/5415510/73729752-97fbeb00-4770-11ea-84d6-84d0fc177fcd.png)

**Comment by Empyreans** [comment]
Check your settings again, this fix works for me.

**Comment by brookhong** [comment]
This should have been fixed in 0.9.59 even without customization of `settings.hintAlign`.
