### ISSUE TITLE
how to open url in page body plain text

### ISSUE THREAD

**Issue by ddatsh** [brookhong/Surfingkeys#1146]
1. xxxxx: https://111/222
2. yyy : https://222/111

such as https://gocn.vip/question/6727

**Comment by for-coursera** [comment]
unmap('F');
    mapkey('F', '#1Open a text link', function() {
        Hints.create(runtime.conf.clickablePat, function(element) {
            window.location.assign(element[2]);
        }, {statusLine: "Open detected links from text"});
    });

**Comment by brookhong** [comment]
`O` to open detected links from text

**Comment by for-coursera** [comment]
So, then I just remapped it this way :)

Thanks, @brookhong!
