### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by AdamWagner** [brookhong/Surfingkeys#1149]
## Error details

The error `Uncaught TypeError: Cannot read property 'postMessage' of null` is displayed 3 times in the console when following any link hint.

```
Navigated to https://github.com/brookhong/Surfingkeys/issues/1118
VM725 modules.min.js:2 Uncaught TypeError: Cannot read property 'postMessage' of null
    at e (VM725 modules.min.js:2)
e @ VM725 modules.min.js:2
postMessage (async)
(anonymous) @ VM725 modules.min.js:3
Promise.then (async)
e.postTopMessage @ VM725 modules.min.js:3
(anonymous) @ VM726 front.js:1
Promise.then (async)
e @ VM726 front.js:1
o.showStatus @ VM726 front.js:1
o.showStatus @ VM725 modules.min.js:1
exit @ VM725 modules.min.js:1
g.dispatchMouseClick @ VM725 modules.min.js:2
n @ VM725 modules.min.js:2
(anonymous) @ VM725 modules.min.js:2
t @ VM725 modules.min.js:1
keydown @ VM725 modules.min.js:1
```

SurfingKeys: 0.9.57

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

URL: All urls

## Context

To reproduce:

1. Navigate to a google results search page
2. Press `f` to activate hints
3. Select any hint

Result: Three `Cannot read property 'postMessage' of null` errors appear in console.

**Comment by brookhong** [comment]
I can not reproduce this.
