### ISSUE TITLE
Alt (Meta) getting blocked

### ISSUE THREAD

**Issue by formbi-kupiec** [brookhong/Surfingkeys#1151]
When I use key combinations with the Meta key, surfingkeys blocks it. That is, if I make something like M-s, surfingkeys doesn't toggle, if I do M-9 it uses 9 as a numerical argument and so on.
It's not a problem with the keyboard nor my window manager.
SurfingKeys: 0.9.5.7

Browser: IceCat 68.4.1esr

**Comment by brookhong** [comment]
It looks like a same issue described in https://github.com/brookhong/Surfingkeys/issues/1107#issuecomment-590033852, which is a bug of Firefox, since IceCat is a rebranding of Firefox.
