### ISSUE TITLE
Latest update broken (0.9.58, 2020-02-16)

### ISSUE THREAD

**Issue by clarkwang** [brookhong/Surfingkeys#1153]
This morning I found Surfingkeys is kind of broken in Chrome (in both Windows and macOS). Just checked update history and found it's updated last night. Could you double check if there is any disruptive changes in latest update?

For example, in Gmail, I unmapped most of keybindings and remapped `,F` to `C`. This used to work quite well but today it stopped working. For now it does not recognize some (not all) links in emails.

**Comment by clarkwang** [comment]
See this example, most of links are not recognized:

![link-hint-broken](https://user-images.githubusercontent.com/157076/74618564-653cf400-516d-11ea-9eb4-119e3ec6aefc.png)

**Comment by clarkwang** [comment]
I know very little about web/html and has no idea what's the difference between these links. I can forward some problematic emails to you for debugging if necessary.

**Comment by brookhong** [comment]
Please provide the URL of your page.

**Comment by clarkwang** [comment]
Manually built 0.9.57 and it works fine for me. So this is a regression in 0.9.58.

**Comment by clarkwang** [comment]
Any update?

**Comment by brookhong** [comment]
Fixed in 0.9.59.

**Comment by clarkwang** [comment]
> Fixed in 0.9.59.

Verified and it works fine. Thanks!
