### ISSUE TITLE
能支持下The Great Suspender插件挂起标签页内使用g[0-9]跳转标签页？

### ISSUE THREAD

**Issue by dslztx** [brookhong/Surfingkeys#1154]
The Great Suspender插件挂起一个标签页A，能支持下在A中能够使用g[0-9]跳转标签页吗？现在是不支持的，只能用Chrome自带的跳转快捷键进行相邻标签页跳转

**Comment by brookhong** [comment]
这个是不可能的，因为浏览器为了安全限制在插件A的页面里执行插件B的脚本，而被The Great Suspender插件挂起的标签页其实是加载了一个它的页面。
