### ISSUE TITLE
哪里有分享操作常见控件的方法吗？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#1156]
比如用QQ登录其他网页时，会跳转到 graph.qq.com/* 页面，
如果一键选择电脑已登录的QQ登录
当然这种用 Tampermonkey 自动化更好，只是不知道如何实现，
故来此咨询大佬，希望能得到答案，再次感谢！！

**Comment by brookhong** [comment]
可以看看https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text
