### ISSUE TITLE
反复调试您以扇贝词典为例的脚本,总是注册不成功,提示说'Front'没有定义

### ISSUE THREAD

**Issue by flowerhood** [brookhong/Surfingkeys#1158]
https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query

你好,我按照这上面的指引,复制到油猴脚本里反复调试您以扇贝词典为例的脚本,总是注册不成功,提示说'Front'没有定义,每次按Q或/模式下按q,都跳转到上面的url地址,Front是不是另外的脚本里面的函数还是需要其他更复杂的配置才行?盼指教

**Comment by brookhong** [comment]
不是油猴脚本，是Surfingkeys的插件配置里，按`se`打开，然后勾选`Advanced mode`。
