### ISSUE TITLE
输入<需要按两次，以及希望添加一个功能

### ISSUE THREAD

**Issue by Leoongithub** [brookhong/Surfingkeys#116]
第一次按<会在右下角显示，这样设计有什么原因吗。

另外希望添加将鼠标移动到某个元素上的功能（类似f打开链接的操作），因为网页有的内容需要鼠标移动到特定位置才会显示。

**Comment by brookhong** [comment]
看看这个，https://github.com/brookhong/Surfingkeys/issues/83

简单说，就是在配置里加一行：

    iunmap('<');

**Comment by Leoongithub** [comment]
谢谢，第一个问题解决了，但是其实我还是不太明白为什么 < 键会影响到 Ctrl+i ，是具体实现的原因吗？

**Comment by brookhong** [comment]
是的，因为`<Ctrl-i>`这样的组合键使用尖括号包起来的。

0.6.4里加了mouseover: `<Ctrl-h>`, mouseout:`<Ctrl-j>`

**Comment by brookhong** [comment]
0.6.5以后，不需要`iunmap('<');`就能一次输入<了
