### ISSUE TITLE
Page scroll seldom works on Github

### ISSUE THREAD

**Issue by cbrwizard** [brookhong/Surfingkeys#117]
Hey, nice extension. It has a good editor for inputs which is awesome compared to vimium, but looks like it lacks in page navigation compared to it.

For instance, while navigating Github I quite often find that none of the scrolling keys work. Sometimes a page reload helps, sometimes a new tab creation does. This is quite unstable for me, what can be the reason here?

**Comment by brookhong** [comment]
Does @sivan 's comment in https://github.com/brookhong/Surfingkeys/issues/65 help you? 

    I solve this problem by disable Experimental Web Platform features at chrome://flags/

If that does not help, you can try to disable smooth scrolling with below line in settings:

    settings.smoothScroll = false;

**Comment by cbrwizard** [comment]
I checked and turned out I had Experimental Web Platform features already disabled. But I decided to click 'reset to defaults' button there and after that - no more bugs. Something there helped, thanks for the tip!
