### ISSUE TITLE
Unreadable text in bookmark box 

### ISSUE THREAD

**Issue by janacm** [brookhong/Surfingkeys#1182]
<img width="537" alt="Screen Shot 2020-03-30 at 10 29 19 AM" src="https://user-images.githubusercontent.com/2055312/77924398-9e3ead00-7271-11ea-9c62-e68dd1c472b7.png">

Is the text color customizable for the omnibox? The text seems to be white on gray background which is clearly unreadable.

Please let me know if you have any suggestion. Excellent app btw, huge fan.

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/wiki/Color-Themes for example.

**Comment by janacm** [comment]
Thanks!
