### ISSUE TITLE
move tab first/last?

### ISSUE THREAD

**Issue by gliptak** [brookhong/Surfingkeys#1186]
I might have missed in the documentation. Is there functionality/key binding to move current tab first/last (in the same window)?

**Comment by brookhong** [comment]
`99<<` should do the magic.

`<<` moves current tab left, `99` makes it repeat 99 times, so here I assume you had less than 99 tabs opened, otherwise you would have to make the number bigger.

**Comment by gliptak** [comment]
Thanks @brookhong A "direct" shortcut might be of value too

**Comment by agguser** [comment]
`moveTab` runtime should also accept `index` property (e.g. `api.RUNTIME('moveTab', {index: 0})` to move to first tab, instead of `api.RUNTIME('moveTab', {step: -9999})`) .

By the way, is there a way to access `chrome` object in settings? (e.g. to directly call `chrome.tabs.move()`)
