### ISSUE TITLE
Input becomes blocked when searchbox loses focus

### ISSUE THREAD

**Issue by maksim-ka** [brookhong/Surfingkeys#1187]
Surfingkeys version: 0.9.60
Browser: Firefox for Manjaro Linux 73.0.1 (64-bit)
URL: everywhere

When focus is lost from searchbox('/') e.g. through clicking on the page, than no more input is possible - you can't use surfingkeys anymore and can't use the page with the mouse to open links, focus input fields (only scrolling works). Search mode (ESC) can't be exited till searchbox is focused again. Than searching is working fine again.

Steps to reproduce:

1. start a search ( type: /) type something if you feel like so but don't hit enter
2. click with mouse on the page
3. now no surfingkeys work till you click on the searchbox from surfingkeys agaiin 

the only workaround I know so far is to focus the searchbox manually with the mouse or reload the page.

#375, #190, #124
I guess these people encountered this problem as well

**Comment by 1w3j** [comment]
For me it works using the TAB key
