### ISSUE TITLE
如何关闭Surfingkeys探测无法打开的网页

### ISSUE THREAD

**Issue by Tback1** [brookhong/Surfingkeys#1191]
某些网站无法访问，这时surfingkeys会弹出一个Chrome内部网页来选择加入代理或者reload。

我原本有其他拓展会处理这个问题无需surfingkeys，但是弹出的内部网页覆盖了原网页，其他拓展就无法处理网址了，这个功能用某条语句关闭么？

是settings.interceptedErrors 除了404 502 这几个被ban的返回值之外都写进去么？

**Comment by wasmetqall** [comment]
@Tback1 +1，有同样的需求

**Comment by platoer** [comment]
是的，经常出现这个问题。怎么取消和解决那？

**Comment by DoTime** [comment]
问题+1
Proxy SwitchyOmega遇到404页面可以直接更新当前网页为系统代理吗?

**Comment by brookhong** [comment]
Fixed in 0.9.61 which is pending review on chrome web store.

**Comment by ewgasdf** [comment]
8天了还没审核通过吗？

**Comment by DoTime** [comment]
> 8天了还没审核通过吗？
我也等着呢

**Comment by Tback1** [comment]
> > 8天了还没审核通过吗？
> > 我也等着呢

@DoTime 10天了~~~还没过~~是被google卡住了么?实在不行放个zip打包版本先替换吧

**Comment by YuefengLi** [comment]
12 天了😂
