### ISSUE TITLE
Automatically select first result in new tab omnibar to avoid delay

### ISSUE THREAD

**Issue by leliamesteban** [brookhong/Surfingkeys#1192]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes

## Error details

<--! **You can simply click dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.**
![image](https://user-images.githubusercontent.com/288207/39614555-6048977e-4fa3-11e8-8476-46203af7c4d6.png) -->

SurfingKeys: <version>

Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

When I press t to open the omnibar to open a new tab, there's a delay between me typing what I want to open and the results appearing beneath it. 

For example, if I press `tnews.ycombinator.com`, there will be a short delay from when I stop writing to when the result appears and I can press tab to select it and enter to open it. If I don't type the whole website, there's a chance that the results won't be accurate and I will have to wait again. If instead of having to press tab, the first result in the dropdown was already selected, the delay would be a lot less significant, since I wouldn't have to wait to press Tab. Would this be possible?

**Comment by richardtkemp** [comment]
I believe the answer is in fact on https://github.com/brookhong/Surfingkeys/blob/master/README.md

You should add the following to your settings

```
// Whether to focus first candidate of matched result in Omnibar
settings.focusFirstCandidate=true
```

**Comment by leliamesteban** [comment]
Thank you! That fixed it.

**Comment by MD7GIT** [comment]
This is so useful! thank you!
