### ISSUE TITLE
Can you configure the automatic post-translation reading function

### ISSUE THREAD

**Issue by zzzzzlucky** [brookhong/Surfingkeys#1195]
翻译后就会自动阅读，而且会和内置的扇贝发音重叠，就是一个单词会读两次。
1、能够关闭自动阅读么
2、重复阅读这个bug能否修复

it will be read automatically every time after the translation. a word will be read twice.
1. Can we choose to turn off auto-reading
2. Can the problem of repeated reading be fixed

**Comment by brookhong** [comment]
`settings.autoSpeakOnInlineQuery` was introduced and set false by default now.
