### ISSUE TITLE
为什么我用空格搜索tab的时候会alert('/*我是蓝翔的*/')

### ISSUE THREAD

**Issue by goldenages1989** [brookhong/Surfingkeys#12]
rt

**Comment by brookhong** [comment]
两种可能。
一种是你改了配置，`se`打开看看，贴上来也可以，还有一种你真的是蓝翔的。

**Comment by goldenages1989** [comment]
应该是我自己电脑的问题，我在我的mac上装了之后就没这个问题。但是在我出问题的机器上卸载了surfingkeys就不会alert了。我基本上没有配置什么东西。用的都是default setting
