### ISSUE TITLE
This webpage is not available

### ISSUE THREAD

**Issue by 0x018** [brookhong/Surfingkeys#1200]
## Error details
open `localhost` but redirect to `chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/error.html`

```
This webpage is not available
net::ERR_CONNECTION_REFUSED
http://localhost:19999/
r to reload.
p to toggle localhost:19999 in list that would be accessed through proxy.
```
SurfingKeys: 0.9.60

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

URL: localhost:any port
## Context

chrome 

Key mappings:Advanced mode 

```
unmap("<Ctrl-6>");
unmap("<Ctrl-j>");
unmap("<Ctrl-h>");
unmap("<Ctrl-z>");
unmap("<Ctrl-c>");
unmap("<Ctrl-v>");
unmap("<Ctrl-t>");
unmap("<Ctrl-n>");
unmap("<Ctrl-r>");
unmap("<Ctrl-l>");
settings.language="zh-CN";
settings.stealFocusOnLoad=false;
```
Mode: clear

**Comment by brookhong** [comment]
Fixed in 0.9.63
