### ISSUE TITLE
bug: b搜索标签，ctrl+p可以切换。但是ctrl+n就不行了。会打开新的浏览器

### ISSUE THREAD

**Issue by fanlushuai** [brookhong/Surfingkeys#1204]
bug: b搜索标签，ctrl+p可以切换。但是ctrl+n就不行了。会打开新的浏览器
当关闭刚刚错误打开的新浏览器窗口后，原始页面上 会出现部分快捷键的功能失效
j,k滚动是可以的。但是shift+? 。还有b打开书签等都是失效的。
必须重新加载页面才能使用

**Comment by fanlushuai** [comment]
ctrl+n真是一个痛点。不知道能不能解决

**Comment by hoohyaIII** [comment]
`;e`编辑设置：
`<Ctrl-b>', '<Ctrl-n>`替换掉这个命令

**Comment by brookhong** [comment]
关于`ctrl-n`和`ctrl-p`，可以看看https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html

**Comment by fanlushuai** [comment]
> 关于`ctrl-n`和`ctrl-p`，可以看看https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html

我尝试了一下。是无法登陆浏览器账号吗？

**Comment by fanlushuai** [comment]
ahk script to sovled it


``` ahk
#IfWinActive ahk_exe chrome.exe  ; 配合地址栏，和搜索栏，以及surfingkeys。使用ctrl+n 和p 来切换下拉菜单

^n::NumpadDown

^p::NumpadUp

Esc::                ; 两次Esc，从地址栏回到页面选中
Send, {Esc 2}
Return
#IfWinActive ; 关闭上下文敏感

```
