### ISSUE TITLE
建议：og使用谷歌搜索的时候。不仅仅是搜索。实现类似地址栏的功能。ctrl+enter能补全域名跳转

### ISSUE THREAD

**Issue by fanlushuai** [brookhong/Surfingkeys#1209]
建议：og使用谷歌搜索的时候。不仅仅是搜索。实现类似地址栏的功能。ctrl+enter能补全域名跳转

**Comment by fanlushuai** [comment]
这个东西主要用来替换地址栏。因为ctrl+L到地址栏之后。页面都获取不到焦点了。能走但是回不来了。如果能替换掉地址栏，就不存在这种问题了。

**Comment by brookhong** [comment]
这个功能已经有了，比如你输入`abc.com`，你会看到第一个就是网址。另外想让焦点回到页面，可以看看https://brookhong.github.io/2018/11/18/bring-focus-back-to-page-content-from-address-bar-cn.html

**Comment by fanlushuai** [comment]
平常一般使用浏览器访问的时候，会直接使用补全网址的快捷键。比如：github。一般直接就是github然后ctrl+enter。不需要后面的.com；我没发现有这个功能。这个个人认为还是比较强烈的需求。
