### ISSUE TITLE
search.bilibili.com 页面异常

### ISSUE THREAD

**Issue by weakbeing** [brookhong/Surfingkeys#121]
插件启用的状态下，在b站的搜索结果页面里点击如“最多点击”，“10分钟以下”之类的筛选会没有反应，甚至不能对搜索结果翻页。点击这些按钮后地址栏的地址会变动，但页面没有变化。停用插件后正常。使用chrome和vivaldi均是同样的情况。

**Comment by brookhong** [comment]
谢谢
0.6.5修正了。
