### ISSUE TITLE
Windows 10 1809 环境下，此插件有可能导致活动窗口不置顶

### ISSUE THREAD

**Issue by matrix-ops** [brookhong/Surfingkeys#1210]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

<--! **You can simply click dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.**
![image](https://user-images.githubusercontent.com/288207/39614555-6048977e-4fa3-11e8-8476-46203af7c4d6.png) -->

SurfingKeys: 最新版 0.9.60

Browser: Firefox 68、Firefox 76、Chrome 80

URL: <The_URL_Where_You_Find_The_Issue>

## Context

就比如现在Chrome或者Firefox处于最顶层，此时我再用鼠标点击任务栏其他的程序，正常情况下，被点击的这个程序应该越过Chrome或者Firefox被置于顶层；但是在安装了最新版Surfingkeys的情况下，这两个浏览器将一直占据顶层，除非回到桌面，重新点击其他程序。

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
`SurfingKeys` 没有能力做到这个的。
