### ISSUE TITLE
怎么关闭替换浏览器错误页面的这个功能？

### ISSUE THREAD

**Issue by lirikirikiri** [brookhong/Surfingkeys#1211]
![image](https://user-images.githubusercontent.com/10389204/79684194-14777380-8262-11ea-8ca6-81d922a58e6e.png)

**Comment by 023Sparrow** [comment]
同遇到这个问题，设置里的代理选项一直是clear

**Comment by in-out** [comment]
等0.9.61吧 google在review
[https://github.com/brookhong/Surfingkeys/issues/1191#issuecomment-612625179](url)

**Comment by lirikirikiri** [comment]
不是代理的问题，我只是希望不要替换自身的错误页面。

**Comment by Mr-Rude** [comment]
附议，体验不太好，建议取消这个功能或者自行选择是否开启。

**Comment by snowman** [comment]
+1

This disadvantage is **annoying** 😭 😢  , sometimes it'll lose the original page url, cause refresh results in page "chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/error.html" man times!!!

**Comment by Tback1** [comment]
> 等0.9.61吧 google在review
> [#1191 (comment)](https://github.com/brookhong/Surfingkeys/issues/1191#issuecomment-612625179)

审核好几天了~什么时候能通过啊? 另外这个功能有时会导致one-tab的页面无法打开,提示被阻止....

**Comment by tkkcc** [comment]
这个功能确实解决了我的痛点

**Comment by brookhong** [comment]
0.9.63已经被Chrome Web Store审核通过了。

**Comment by smyle10** [comment]
> 0.9.63已经被Chrome Web Store审核通过了。

我的需求刚好相反，请问这个error.html页面在0.9.63里要怎么开启啊？临时设置代理还是很方便的
前几天还OK的（不确定版本），但现在页面加载失败时又显示为chrome默认的错误页面了。还得自己手动添加代理，很不方便
