### ISSUE TITLE
Close active window?

### ISSUE THREAD

**Issue by chrish-21** [brookhong/Surfingkeys#1213]
SurfingKeys: 0.9.60

Browser: Chromium 81.0.4044.113  Manjaro Linux

## Context
I want to close only the active window after running a function.

- I tried 'quit', but is closes all windows
- I tried RUNTIME('tabOnly') followed by RUNTIME('closeTab') but it doesn't close the last tab, because in my function I'm opening an external application and the last tab then isn't active anymore.

Here is my current code:
```
mapkey('cu', '#1Copy all tabs', function(){
    RUNTIME('getTabs', {queryInfo: {currentWindow: true}}, function(response) {
        const tabs = response.tabs.filter(tab => !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://'))
        const activeTab = [`** [[${window.location.href}][${window.location.title || window.location.href}]]`]
        const links = activeTab.concat(tabs.map(tab => `** [[${tab.url}][${tab.title || tab.url}]]`))
        Clipboard.write(links.join('\n'))
        location.href='org-protocol:///capture?template=b'
        RUNTIME('tabOnly')
        RUNTIME('closeTab')
    })
})
```

**Comment by brookhong** [comment]
Try below, the trick here is to make use of repeation of background actions.

    mapkey('cu', '#1Copy all tabs', function(){
        RUNTIME('getTabs', {queryInfo: {currentWindow: true}}, function(response) {
            const tabs = response.tabs.filter(tab => !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://'))
            const activeTab = [`** [[${window.location.href}][${window.location.title || window.location.href}]]`]
            const links = activeTab.concat(tabs.map(tab => `** [[${tab.url}][${tab.title || tab.url}]]`))
            Clipboard.write(links.join('\n'))
            location.href='org-protocol:///capture?template=b'
            RUNTIME.repeats = response.tabs.length + 1;
            RUNTIME('closeTab')
        })
    })

**Comment by chrish-21** [comment]
Thanks that worked!
Only issue I had now is, that the window gets closed, before the external application gets called. I fixed that by using setTimeout to wait 200ms before closing the window. It's a bit hacky but it works:

```
mapkey('cu', '#1Copy all tabs', function(){
    RUNTIME('getTabs', {queryInfo: {currentWindow: true}}, function(response) {
        const tabs = response.tabs.filter(tab => !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://'))
        const activeTab = [`** [[${window.location.href}][${window.location.title || window.location.href}]]`]
        const links = activeTab.concat(tabs.map(tab => `** [[${tab.url}][${tab.title || tab.url}]]`))
        Clipboard.write(links.join('\n'))
        location.href='org-protocol:///capture?template=b'
        setTimeout(function(){
          RUNTIME.repeats = response.tabs.length + 1;
          RUNTIME('closeTab')
        }, 200)
    })
})```
