### ISSUE TITLE
Tear off tab into new window?

### ISSUE THREAD

**Issue by max-sixty** [brookhong/Surfingkeys#1214]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

✅ 
 
## Details

Is there any shortcut to tear off a tab into its own window? I couldn't find this in the docs, at least searching for "tear off"

Vimium has this as `W` fyi

Thanks again for the awesome extension!

---
SurfingKeys: 0.9.54
Browser: Firefox, MacOS

**Comment by brookhong** [comment]
`W` should work, please see https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js#L360

**Comment by max-sixty** [comment]
Ah it does! Thanks!
