### ISSUE TITLE
The vim editor is behaving differently

### ISSUE THREAD

**Issue by daraul** [brookhong/Surfingkeys#1216]
SurfingKeys: 0.9.63

Browser: Firefox 75.0 - Arch Linux

URL: *

## Context

The vim editor for textboxes no longer behaves like vim does. The `/` key no longer searches, and I can't use `:wq` to save and exit, though now `:w` seems to do that. The changelog doesn't seem to reflect these changes either (in fact, it has no changelog at all for `0.9.63`, nor does that tag seem to exist in this repository).

I noticed this behavior over the past few days maybe Monday the earliest, and I do see an untagged commit labelled as `0.9.62`: https://github.com/brookhong/Surfingkeys/commit/71815db27780ef5aa837780116237ad06511e717

Here's the add-on page in firefox: 
![image](https://user-images.githubusercontent.com/2440975/80278195-52d9bc00-86c2-11ea-8e52-766b2ab348b7.png)

**Comment by brookhong** [comment]
A dependency `ACE` was upgraded in 0.9.63, will look into this.

**Comment by brookhong** [comment]
Fixed in 0.9.64

**Comment by daraul** [comment]
Can confirm. Thanks!
