### ISSUE TITLE
How to adjust font size in visual mode: hint, and in omnibar input

### ISSUE THREAD

**Issue by zuxfoucault** [brookhong/Surfingkeys#1235]
Thanks for the work!

I could adjust the font size in omnibar search results by the following setting, but it seems not to affect the input font size?
```
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #282828;
    color: #ebdbb2;
} 
```
Also, the following setting could adjust the hint font size in normal mode, but how to adjust hint font size in visual mode?
```
Hints.style('font-size: 20px;'); 
```
Thanks!

**Comment by brookhong** [comment]
Change font size for input of omnibar:

    .sk_theme #sk_omnibarSearchArea input {
        font-size: 30px;
    }


Change font size for text Hints:

    Hints.style("font-size: 20px;", "text");

**Comment by zuxfoucault** [comment]
Thanks a lot!
