### ISSUE TITLE
T for choose tab doesn't work properly

### ISSUE THREAD

**Issue by control-freak** [brookhong/Surfingkeys#1238]
## Error details

SurfingKeys: 0.9.64

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

Command "T" for "choose tabs" option doesn't work normally. if i click left mouse after i press "T" only then it shows up. 

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Thanks, will be fixed in next release.
