### ISSUE TITLE
Input focus loss

### ISSUE THREAD

**Issue by brunosabenca** [brookhong/Surfingkeys#124]
Whenever I focus the search field on [Inbox](https://inbox.google.com/u/0/) using the mouse, the search field loses focus after the recent searches dropdown slides out and I have to re-focus the search field.

If I use SurfingKeys' go to edit box function, the search field gains focus but it doesn't trigger the dropdown until I start typing the search term, at which point it loses focus after the first character is input.

I noticed that at the time the focus is lost the page URL is changed from `https://inbox.google.com/u/0/` to `https://inbox.google.com/u/0/search/`.

Toggling SurfingKeys off for the site provides no change in behavior. Only disabling the extension entirely restores the normal behavior.

**Comment by hypnoglow** [comment]
I confirm this. This also applies for search fields on other sites e.g. https://vk.com/audio

**Comment by brookhong** [comment]
Thanks, fixed in 0.6.5.
