### ISSUE TITLE
enable/disable SurfingKeys does not apply to embedded iframe

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#1244]
## Error details

Enabling/disabling Surfingkeys via `Alt-S` has broken again.  This is the 8th time it has happened (see #167, #168, #169, #170, #182, #382, #1018).  I'm not sure why it keeps happening, but as before I **strongly** recommend coding some regression tests so that it can never happen again.

On this occasion the breakage applies to pages with embedded `<iframe>` elements - SurfingKeys only gets disabled for the containing page, not within the iframe.

SurfingKeys: 0.9.64

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36

URL: https://codepen.io/GBora/pen/VLYyzY (or any page with an `<iframe>` element

### How to reproduce

- Enable Surfingkeys
- Go to https://codepen.io/GBora/pen/VLYyzY
- Press `w` until the smallest `iframe` (the weather page) is highlighted
- Press `Alt-S` to disable Surfingkeys.
- Press `f`

### Observed behaviour

Surfingkeys displays the hint letters for links as normal after pressing `f`.  Also it doesn't display the normal disable message after pressing `Alt-S` when the iframe is selected.

### Expected behaviour

When Surfingkeys is disabled, it should **never, EVER** react to any of its keyboard shortcuts, except for `Alt-S` to reenable it.

Also, when pressing `Alt-S` it should **always** display a message to show that Surfingkeys has been enabled or disabled.

**Comment by brookhong** [comment]
Hey @aspiers, thanks for your report.

Your point is valid that we need regression tests, but the behavior of this time is not a regression. In my thoughts, toggling Surfingkeys is not supported in iframe. Say you have disabled Surfingkeys in a frame, then `w` won't work, which means you have to reach your mouse to leave the frame.

Anyway my thoughts might not suit others, I could make it work in frames if I see a strong reason.

**Comment by aspiers** [comment]
@brookhong Thanks a lot for the quick response!

> Say you have disabled Surfingkeys in a frame, then w won't work, which means you have to reach your mouse to leave the frame.

I don't quite follow this logic.  If a user disables Surfingkeys then why would they expect to be able to leave the frame without a mouse?  If Surfingkeys was not installed, surely it would be the same situation.

However if that was really a problem, they could just re-enable Surfingkeys, press `w`, then disable it again.  Or if for some reason you still consider that solution insufficient, then you could just allow `w` (and `Alt-s`) to still work, but none of the other shortcuts.  Although IMHO that would be a somewhat ugly design.

I find the current behaviour very confusing.  I expect I am not the only user who would naturally assume that `Alt-s` means "disable Surfingkeys for this whole site", not "disable Surfingkeys for this whole site, except for any iframes which might be there".  If I disable Surfingkeys, I really really want it disabled.  Any exceptions to that come as an unwelcome surprise! :wink:

**Comment by aspiers** [comment]
Thanks for the fix! Please could you release 0.9.65 so I can test it?

Also it would be great if you created git tags for each release and pushed them to GitHub :-)

**Comment by brookhong** [comment]
0.9.65 is released now.

**Comment by Inc0ns1st3nt** [comment]
on version 0.9.65, `alt-s` does not seem to work, it says 
> Surfingkeys turned ON for undefined

in an alert.
