### ISSUE TITLE
T can not use , if I switch tabs , press T can not use ,need T and click page than show tabs character

### ISSUE THREAD

**Issue by kickcodeman** [brookhong/Surfingkeys#1245]
## Error details

SurfingKeys: 0.9.64

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by deerainw** [comment]
I encountered the same problem, I can not use `T` in all browsers including chrome 83.0.4103.61.

**Comment by cyb1ove** [comment]
+, I have the same problem

**Comment by brookhong** [comment]
Fixed in 0.9.65

**Comment by deerainw** [comment]
This problem no longer exists, but favicons disappear from `T`'s overlay view
