### ISSUE TITLE
Cannot unregister all default bindings

### ISSUE THREAD

**Issue by Dessix** [brookhong/Surfingkeys#125]
When I do `unmapAllExcept();` or `unmapAllExcept([]);` at the top of an empty configuration, many windows will still exhibit the default configuration mappings, or will result in odd behaviours such as `<` bringing a small keypress-notice on the bottom right as if it had a binding.

Also, in the default configuration, `>>` and `<<` seem to vary in behaviour similarly, and I cannot reliably reproduce this particular circumstance, but it seems related to the above.

**Comment by brookhong** [comment]
`<` as a small keypress-notice on the bottom right is caused key binding like `<Ctrl-i>` in insert mode, which is got fixed in 0.6.5.

And I don't see a problem with `unmapAllExcept`, neither with `<<`.

If you could provide reliable steps to reproduce it, that would be better.

**Comment by Dessix** [comment]
This appears to be resolved in the current build, but the unbinding action does not appear to take place until after the page has loaded, indicating that the bindings are processed later than the defaults- is there any way that processing of these key events could be held over until the custom script has been run, or the info on bindings delivered sooner to ensure immediate, correct reaction to the events?

**Comment by brookhong** [comment]
Yes, user settings(described in JS) always gets executed after default settings. Otherwise `unmapAllExcept` won't make sense. If user settings goes first, `unmapAllExcept` will not unmap anything, as there is no any mapping existed.

For your second question, if you know Javascript/jQuery(jQuery is built within Surfingkeys) well, I guess you could.


    $(document).on('myEvent',function(){
        unmapAllExcept();
        map(...);
    });

**Comment by Dessix** [comment]
I'm not asking to map on an event's occurrence, so much as to just see to it that the initial bindings are processed directly before the user settings, such that they apply immediately, not after a short period of defaults.

**Comment by brookhong** [comment]
Sorry,  I don't understand what you mean by `so much as to just see to it`. I did not get your question.

**Comment by Dessix** [comment]
To summarize- Don't allow a gap between the defaults and the user configuration executing. Currently, time passes between them, but if the code that executed the defaults _immediately_ executed the user changes, with no asynchronous or multi-frame calls in between, this would not be an issue.
