### ISSUE TITLE
No way to edit URL of current tab?

### ISSUE THREAD

**Issue by Tanath** [brookhong/Surfingkeys#1255]
## Error details

SurfingKeys: 0.9.65

Browser: Chrome Beta, Linux

URL: any web page

## Context

I can find no way to edit the current URL and open it in the same tab. I used to use `sU` but that appears to be removed. I tried `;u` with both `enter` and `:w` but both open a new tab.

**Comment by iSeeU816** [comment]
There were some modifications to `s` map in this [commit](https://github.com/brookhong/Surfingkeys/commit/9677aaa5fe3928d8afd5f63022d3f14a3075b11a#diff-cf5df94562fb8a4a2f171b49ab4a0399L607).

`sU` was replaced with `;U`.

**Comment by Tanath** [comment]
Yes, I mentioned and addressed that.
