### ISSUE TITLE
Delete/clear vim-like marks

### ISSUE THREAD

**Issue by duguyipiao** [brookhong/Surfingkeys#1257]
Sometimes I create some vim-like marks by accident. Is there a way to delete them or clear all of them?

Browser: firefox 77
OS: linux

**Comment by iSeeU816** [comment]
You can call `om` to open vim-like marks in omnibar. Then highlight the one you
want to delete, after that hit `ctrl-d` (control with letter `d`).

1. Call `om`.
2. Highlight one of the marks.
  - If you have more than 10 marks, you can go to the next page with `ctrl-.`
    that control with dot character.
  - For previous page `ctrl-,` (control-comma).
3. Hit `ctrl-d` to delete it.
4. Repeat step 1 to 3 for any other marks you want to delete.

**Note:** Once you delete the mark, there is no undo I know of.

**Comment by duguyipiao** [comment]
@iSeeU816 It works perfectly. Thanks a lot!
