### ISSUE TITLE
Command window keeps the last command even when typing a new one

### ISSUE THREAD

**Issue by Dessix** [brookhong/Surfingkeys#126]
Typing `:8*2<enter>` then `:2*5<enter>` results in `:8*22*5`. Keeping the previous command can be useful, but it doesn't seem to replace it when something new is introduced. Pressing the "Up" arrow appears to clear the contents, but is disruptive to the normal flow of usage.

**Comment by brookhong** [comment]
Thanks, fixed in 0.6.5.
