### ISSUE TITLE
Chrome shows warning 'DevTools failed to load SourceMap'

### ISSUE THREAD

**Issue by frankitox** [brookhong/Surfingkeys#1260]
## Error details

SurfingKeys: 0.9.65

Browser: Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

URL: *

## Context

Hi! I'm getting a warning about a source map not found

> DevTools failed to load SourceMap: Could not load content for chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

I know it's probably not that important but it's extremely annoying. I tried adding localhost to my list of blocked sites with something like 

> settings.blacklistPattern = /.*localhost.*/g;

A working solution is removing JS source maps from DevTools, but I do need that option on for debugging purposes.

![image](https://user-images.githubusercontent.com/1985577/85046515-eda4c300-b166-11ea-95de-f3f6eb841857.png)

**Comment by AndreasNasman** [comment]
Is there a way to do this locally if the pull request won't be merged?
I tried cloning the [`purify.min.js.map`](https://raw.githubusercontent.com/cure53/DOMPurify/2.0.8/dist/purify.min.js.map) file locally (`/Users/user/Library/Application Support/Google/Chrome/Default/Extensions/gfbliohnnapiefjpjlpjnehglfpaknnc/0.9.74_0/libs`, running Mac) but that didn't work. Also, tried cloning the file directly to the `content_scripts` directory where the warning is given, but no effect there either.

**Comment by brookhong** [comment]
Should have been fixed in 1.0.
