### ISSUE TITLE
Unmap for specific domain

### ISSUE THREAD

**Issue by liberninja** [brookhong/Surfingkeys#1272]
I'm trying to unmap 'c' and 'f' on youtube but keep getting an error:

_Error found in settings: SyntaxError: expected expression, got '.'_

This is the code I'm using:
`unmap(['c','f'] /.*youtube.com/i);`

Is there an issue with the domain pattern? Nothing I try seems to work.

**Comment by userrand** [comment]
this works for me

`api.unmap("f",/www.youtube.com/);`
