### ISSUE TITLE
The hot key:"toggle Surfingkeys" can not support multi modifies with still one keystroke.

### ISSUE THREAD

**Issue by PythonYunfei** [brookhong/Surfingkeys#1274]
The hot key:"toggle Surfingkeys" can not support multi modifies with still one keystroke such as `map('<Shift-Alt-k>', '<Alt-s>');`.  Why?

**Comment by cchando** [comment]
Use the capital letter directly rather than including `'<Shift>'`.  E.g. `map('<Alt-K>', '<Alt-s>');` rather than e.g. `map('<Shift-Alt-k>', '<Alt-s>');`.
