### ISSUE TITLE
Can no longer turn Surfingkeys off

### ISSUE THREAD

**Issue by nemya9066** [brookhong/Surfingkeys#1279]
Hi I used to turn Surfingkeys off just fine when I needed to with the 'Alt-s' shortcut now when I press it It always show me this message:
>SurfingKeys turned ON for undefined

It never toggle the extension off any help?
Browser: Firefox 79.

**Comment by vcfvct** [comment]
Same issue, have to turn the off extension off instead of individual site.

**Comment by lkhphuc** [comment]
Same issue.

**Comment by masaeedu** [comment]
![similar problem](https://media.giphy.com/media/W6nxfOvOHXjoja58mb/giphy.gif)

**Comment by max-sixty** [comment]
Does anyone have a workaround or is the only fix to uninstall it?

**Comment by lkhphuc** [comment]
@max-sixty I only want to disable (some functionalities of) SurfingKey from certain websites, so I blacklist those sites in the config for now.

**Comment by brookhong** [comment]
Fixed in 0.9.66 now.

**Comment by max-sixty** [comment]
Thanks @brookhong !
