### ISSUE TITLE
How to set user-defined default search engine?

### ISSUE THREAD

**Issue by av2000ii** [brookhong/Surfingkeys#129]
Is there some way to define default search engine? As I know the default is Google. But I have to use Baidu search engine. Can you help me?

**Comment by brookhong** [comment]
What do you mean by default search engine? There is no default search engine. Every search engine has its own alias. `g` for google, `b` for baidu.

If you need baidu, just use `ob` for searching in omnibar, or `sb` to search selected text.

**Comment by av2000ii** [comment]
Let me take a example. When I type "t" to open omnibar, than input some thing, but there no correspond entry(such as no related history), then I hit Enter key. At that time, SurfingKeys will use google to search this strings. I konw I can use "b"(than Hit "tab") or other alias, But the default is Google.

**Comment by brookhong** [comment]
In 0.7.0, please add below to use baidu as default search engine.

    settings.defaultSearchEngine = 'b';

**Comment by av2000ii** [comment]
Many Thanks!
