### ISSUE TITLE
请问如何禁用补丁版chromium的字典功能？

### ISSUE THREAD

**Issue by Mehechiger** [brookhong/Surfingkeys#1291]
因为找不到联系方式所以在这里开个issue。下载了补丁版的chromium但是字典功能用不到，会不断弹出，请问如何完全禁用？谢谢

**Comment by brookhong** [comment]
打开chrome://settings/content/dict, 里面有开关

**Comment by Mehechiger** [comment]
> 打开chrome://settings/content/dict, 里面有开关

我已经block掉了，可是还是会弹出来，例如在某些插件的界面上
![Screen Shot 2020-07-22 at 11 36 57](https://user-images.githubusercontent.com/13514897/88161094-d480ad80-cc0f-11ea-8643-1aa6a059873c.png)
