### ISSUE TITLE
SurfingKeys not working on https://docs.rapid7.com/

### ISSUE THREAD

**Issue by jrichman-r7** [brookhong/Surfingkeys#1292]
## Error details

SurfingKeys: 0.9.65

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40

URL: https://docs.rapid7.com/

## Context

Tried using any hotkeys at all. jk do not work, f does not work, etc.

**Comment by brookhong** [comment]
It works for me. Did you turn off the extension on the site? If yes, press `Alt-s` to turn it on.

![image](https://user-images.githubusercontent.com/288207/88142393-09006380-cc28-11ea-9ff4-fad86f2e40aa.png)

**Comment by jrichman-r7** [comment]
My mistake. Full reboot of OS and/or restarting of my browser seems to have fixed the issue. Thank you for the quick response. Loving SurfingKeys so far!
