### ISSUE TITLE
Totally not working on support.mozilla.org

### ISSUE THREAD

**Issue by DrakeXiang** [brookhong/Surfingkeys#1294]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: 0.9.65

Browser: FireFox Developer Edition 79.0b9 (64-bit) MacOS 10.14.6

URL: https://support.mozilla.org/en-US/

## Context

**Please replace this with a description of how you were using SurfingKeys.**
Surfingkeys works fine on ohter pages, but totally not working on support.mozilla.org

**Comment by Shamaoke** [comment]
**about:config** → **extensions.webextensions.restrictedDomains = " "**
