### ISSUE TITLE
How to use placeholder values in addSearchAlias/addSearchAliasX?

### ISSUE THREAD

**Issue by macintacos** [brookhong/Surfingkeys#1298]
While I was digging around after opening #1297, I happened upon this PR related to adding the ability for placeholder values using this extension: #424

I can't figure out how it's supposed to be utilized. Can these be passed in in the `addSearchAlias`/`addSearchAliasX` functions somehow? Can we get some examples using that syntax?

Thanks in advance for any pointers you can give me!

**Comment by brookhong** [comment]
such as `{0}` in `https://cs.chromium.org/search/?q={0}&type=cs`

**Comment by macintacos** [comment]
@brookhong Thanks! Can you put that in multiple places in the URL, or you can only make one substitution?

**Comment by brookhong** [comment]
Only one substitution for now, please see https://github.com/brookhong/Surfingkeys/blob/53546d6a35982fb2c782108127f2a81882a7ec95/content_scripts/utils.js#L438

I don't see any case to need multiple substitutions here.

**Comment by macintacos** [comment]
@brookhong I have a use case: I have a specific JQL query that searches Jira with various different conditions and such. The search term that I use is passed in twice to this search, and I'm able to do this just fine when using Chrome's custom search engines that a user can define (you can put `%s` in multiple places in the URL and it'll just go through and substitute them all with the value you passed in). While you might not have a use case for it, I definitely do.

Should I create a separate issue for this?
