### ISSUE TITLE
open selected result in new tab

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#13]
am i missing something? shift + enter doesn't open the selected results in a new tab

**Comment by brookhong** [comment]
Are you talking about something for omnibar like `t`/`oh`?
They are all opened in a new tab by default with `enter`.

**Comment by jaredbidlow** [comment]
Yes. It looks like I had an extension forcing it to open in the current tab. My other issue is that it is not possible to open in a background tab via the omnibar. I would like to open multiple bookmarks/history links while in the omnibar 






On Sat, Nov 28, 2015 at 7:46 PM -0800, "brookhong" <notifications@github.com> wrote:












Are you talking about something for omnibar like t/oh?

They are all opened in a new tab by default with enter.

**Comment by brookhong** [comment]
Thanks.

I added the function -- `ctrl+enter` to open multiple urls in background tabs from the omnibar.
