### ISSUE TITLE
unmap Ctrl-j and Ctrl-h doesn't work

### ISSUE THREAD

**Issue by saccohuo** [brookhong/Surfingkeys#130]
There are new bindings added in the new version, conflict with default hotkey of chrome, like `Ctrl-h` and `Ctrl-j`. So I want to unmap them.

However, I add the following lines into my settings, it did not work.
```
unmap('<Ctrl-h>');
unmap('<Ctrl-j>');
```

**Comment by hzysoft** [comment]
add that codes，and then click “save”

**Comment by httpsrichard** [comment]
The issue is still there. 
It seems that Ctrl-h and Ctrl-j are captured by Surfingkeys, but they just have the same action as the `f` key
