### ISSUE TITLE
[Feature Change] Make change scroll target show hints for scrollable elements

### ISSUE THREAD

**Issue by auroranil** [brookhong/Surfingkeys#1301]
To change between scroll targets, you would press `cs`. However, it is inconvenient if there are multiple scrollable elements, and especially if there are scrollable elements that are not meant to be scrollable. This is because the current behaviour of change scroll is that it traverses through a cyclic list of scroll targets, with each `cs` pressed to go to the next scroll target.

My suggestion would be to instead show hints (like for links) to allow the user to freely navigate to any other scroll target. Perhaps you can keep the box saying "Hi I'm here now!" to visually indicate which scroll target the user is currently on.

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/88925953-db5e8e80-d2a7-11ea-9ea4-25fcc6bcff50.png)

**Comment by karlredman** [comment]
Is this feature still available someplace? I've been unable to find it -even in older versions of surfingkeys.
