### ISSUE TITLE
Getting the URL of an embedded YouTube video?

### ISSUE THREAD

**Issue by 097115** [brookhong/Surfingkeys#1303]
On a page with an embedded YouTube video (in [a paused state](https://i.imgur.com/N8OdJxM.png), which means we only see a preview image for that video and a triangle-in-a-circle play button), is it possible somehow to copy the URL for that video? With some additional JS magic may be? :)

(I suspect the answer is 'NO' but it'd be great to have a confirmation anyway. Thanks :)

**Comment by brookhong** [comment]
Please try to press `w` to switch to YouTube video frame, then press `yy` to copy the url of the frame.

**Comment by 097115** [comment]
@brookhong , this only works for me if a video is already playing (or was playing and then paused). For you, it's not like this?

**Comment by Shamaoke** [comment]
@097115 
• Press `w` to switch to a YouTube video frame
• Press `ya` to call hints for copying a link URL to the clipboard
• Select the hint on the YouTube video title link — the video URL will be copied to the clipboard

**Comment by Shamaoke** [comment]
@097115 Please, provide a sample URL.

**Comment by 097115** [comment]
[For instance](https://historyporn.d3.ru/ioann-pavel-ii-primeriaet-ochki-bono-1999-god-kastel-gandolfo-italiia-2017293/#27673436). 

Looks for me [like this](https://i.imgur.com/6mWSxxJ.png): you need to click that preview pic first to actually load a YouTube frame. Until then, you can't switch frames, a YouTube frame is simply not present :)

The workaround would be to to press `f`, select a hint to start a YouTube video, which would load a YouTube frame, then somehow stop the video, and **only then** press `w` to switch to that YouTube video frame, and then press `yy` to copy the url of the frame.

But that's a bit of too much keypresses... Except if I could map all those to some additional key? Like a macro may be?

**Comment by Shamaoke** [comment]
@097115 This is **not** a YouTube video frame. This is an `img` HTML element. When you click on it, the actual YouTube video is loaded and only after that you can get its URL. You cannot get it before that, since there's no YouTube video frame on the page. That's how that web-site was programmed. So yes, `f` → `w` → `yy`/`ya`.

Btw, you can prevent YouTube video autoplay by altering the following in Firefox 79.

**`media.autoplay.default = 5`**

**`media.autoplay.blocking_policy = 2`**

**Comment by 097115** [comment]
@Shamaoke yeah, thanks for confirming.

And about that possible "macro"-like mapping -- we can't create a mapping that would be a chain of other mappings, can we?
