### ISSUE TITLE
where do I find my config file if I installed through chrome web store?

### ISSUE THREAD

**Issue by radekosmulski** [brookhong/Surfingkeys#1320]
I realize this is very basic - my apologies. But I shared quite extensively online and this is not explained anywhere as it seems...

In order to edit the config file, do I need to install from the repo?

Thank you very much for your help and apologies for this basic question

**Comment by lkblkb** [comment]
Afaik you need to just create it yourself. Open the Surfingkeys settings and you will see an 'Advanced mode' option and, after turning that on, a path showing where the config file is expected to appear. Ex.:

![image](https://user-images.githubusercontent.com/25714571/91269207-4d43ce00-e7a9-11ea-9d34-4e69283a9993.png)

Create an empty text file there and start adding settings to it.

**Comment by radekosmulski** [comment]
wow, thank you very much for your answer 🙏 really appreciate it!!!
