### ISSUE TITLE
访问ShowDoc存在性能问题

### ISSUE THREAD

**Issue by Jialang630** [brookhong/Surfingkeys#1326]
## Error details
访问：https://www.showdoc.com.cn/demo?page_id=9
CPU居高不下，内存持续飙升
![image](https://user-images.githubusercontent.com/29793747/93595859-11d4a200-f9eb-11ea-9b32-577b0de277da.png)

SurfingKeys: 0.9.67

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
那个网站本身有bug，你可以试着卸载或者禁用Surfingkeys，然后打开Inspect tool，执行下面这个

    window.postMessage({});
    
就能看到同样的效果了。
