### ISSUE TITLE
Is it possible to force some commands to work even when an input field is focused?

### ISSUE THREAD

**Issue by Madd0g** [brookhong/Surfingkeys#1327]
I'm using a few annoying web apps that force the cursor into an input field A LOT and I'm wondering if it's possible to allow some commands while in an input field.

I'm often surprised these don't work (ctrl+key, alt+key) --- I understand why letter keys and other modals shortcuts won't work, but modifier+key, maybe should work always?

These are the ones I mapped and often surprised that they don't work.

```js
mapkey('<Ctrl-6>', '#4Go to last used tab', function() {
    RUNTIME("goToLastTab");
});
map('<Alt-p>', 'RUNTIME("togglePinTab")');
map('<Alt-m>', 'RUNTIME("muteTab")');
```

**Comment by cchando** [comment]
It is indeed possible! Use "imapkey" and "imap" rather than "mapkey" and "map" for this purpose, since SurfingKeys is in input mode whenever the cursor is in an input field. Similarly, for visual mode mappings, use vmapkey and vmap, and for omnibar mappings, use cmap.

**Comment by Madd0g** [comment]
@cchando - thanks a lot! had no idea being in an input field means I could use `imapkey`, solves my problem!
