### ISSUE TITLE
keybind Hints for usability improvment idea?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#133]
Hi

Just an idea from previous browsers (qutebrowser etc) that show a visual hint when a first key in a series of presses is pressed. so if i press default 's' key a nice overlay with the possible continuation Will appear (ie):

```
sg Search selected with google
sog Search selected only in this site with google
soG  Search selected only in this site with google interactively
```
here is a screen shot in qutebrowser when pressing the 'g' key
![owzk](https://cloud.githubusercontent.com/assets/498410/20050790/d8cd1552-a4d3-11e6-8217-ef754d4ee406.png)

best

Z

**Comment by zhongkeli** [comment]
Good idea. Hope Surfingkeys can support this feature

**Comment by brookhong** [comment]
![richhints](https://cloud.githubusercontent.com/assets/288207/23294004/47732f7a-faa4-11e6-95a5-6379c8d2369f.gif)

**Comment by zeltak** [comment]
awesome! will love to test it when ready (i cant see its commited yet)

best

Z
