### ISSUE TITLE
Favicons not loading in Firefox

### ISSUE THREAD

**Issue by seanfarley** [brookhong/Surfingkeys#1332]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

Yes

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yep 

## Error details

Omnibar doesn't seem to load favicons.

SurfingKeys: 0.9.67

Browser: Firefox 81 MacOS 10.1.4.6

URL: N/A

## Context

<img width="1164" alt="Screen Shot 2020-09-30 at 10 47 24 AM" src="https://user-images.githubusercontent.com/20887/94721303-8cb28c80-030a-11eb-875f-34aecdc80e4e.png">

**Comment by xaviervalarino** [comment]
Also experiencing this issue.

**Comment by pangdaxing23** [comment]
+1 on this.
Firefox 110 on Linux 6.2.2
