### ISSUE TITLE
类 vim 提示怎么删除？

### ISSUE THREAD

**Issue by wlzxdm** [brookhong/Surfingkeys#1334]
这个类 vim 提示添加之后怎么删除？

**Comment by yxke** [comment]
试试在settings里面reset

**Comment by brookhong** [comment]
1. `om`打开类vim标示列表
1. 按`tab`键选中要删除的那个
1. 然后按`Ctrl-d`

**Comment by wlzxdm** [comment]
好的，谢谢。ctrl+d 确实也可以。


| |
→斷情戒愛-
|
|
wlzx_221941@163.com
|
签名由网易邮箱大师定制


在2020年10月7日 18:43，John Keats<notifications@github.com> 写道：

试试在settings里面reset

**Comment by wlzxdm** [comment]
> 1. `om`打开类vim标示列表
> 2. 按`tab`键选中要删除的那个
> 3. 然后按`Ctrl-d`

**Comment by wlzxdm** [comment]
> 1. `om`打开类vim标示列表
> 2. 按`tab`键选中要删除的那个
> 3. 然后按`Ctrl-d`

谢谢。好用
