### ISSUE TITLE
Omnibar custom URLs

### ISSUE THREAD

**Issue by sin2384** [brookhong/Surfingkeys#1346]
Hi, thanks for the great extension!

I'm trying to create a custom mapping for which will add my links to Omnibar. 
The problem is, I don't know how to add that list of URLs to Omnibar. Is it possible to use something like this
`Front.openOmnibar({type: "URLs", extra: "somethingCustom"});`, or is there another approach?

It would be ideal to add those URLs to Omnibar because I can search those URLs quickly. 
The list of links would look like something like this:
domain.com
domain.com/wp-admin
domain.com/wp-admin/options.php
and so on...

domain.com should be current domain name.

Thanks in advance.

**Comment by brookhong** [comment]
You could create a list of objects first:

    var myUrls = [
        {
            "title": "Home Page",
            "url": "https://domain.com"
        },
        {
            "title": "wp admin",
            "url": "https://domain.com/wp-admin"
        }
    ];

then pass it to `Front.openOmnibar` as:

    Front.openOmnibar({type: "UserURLs", extra: myUrls});

For example, below snippet is to help to launch AWS services from Omnibar:

    mapkey('ou', '#8Open AWS services', function() {
        var services = Array.from(top.document.querySelectorAll('#awsc-services-container li[data-service-href]')).map(function(li) {
            return {
                title: li.querySelector("span.service-label").textContent,
                url: li.getAttribute('data-service-href')
            };
        });
        if (services.length === 0) {
            services = Array.from(top.document.querySelectorAll('div[data-testid="awsc-nav-service-list"] li[data-testid]>a')).map(function(a) {
                return {
                    title: a.innerText,
                    url: a.href
                };
            });
        }
        Front.openOmnibar({type: "UserURLs", extra: services});
    }, {domain: /console.amazonaws|console.aws.amazon.com/i});

**Comment by sin2384** [comment]
Thank you @brookhong very much!!!
