### ISSUE TITLE
Rapid open multiple links (cf) while still be able to use j/k to move up down page?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#135]
Hi 

I dont know if this is technically possible, but in pentadactyl i remember i could launch the Rapid open link on a page and start opening links while being able to scroll the page up/down to discover new links (the hints would auto update) and be able to launch them
I found that super useful, would such a thing be possible in SK? if so should i open a "proper" request :)

thx!

Z

**Comment by axs221** [comment]
I'll give this one a try. PR coming soon.

**Comment by axs221** [comment]
@zeltak I have a PR open now that should meet your needs.

**Comment by brookhong** [comment]
Released in 0.7.3
