### ISSUE TITLE
Movement of cursor is reversed when setting.omnibarPosition is set to 'bottom'

### ISSUE THREAD

**Issue by catbaron0** [brookhong/Surfingkeys#1351]
If the `setting.omnibarPosition` is set to `bottom`, the omnibar appears at the bottom of the window, and the candidates appears on the top of it. Then when the UP/DOWN key is pressed, the cursor will move DOWN/UP incorrectly.

**Comment by brookhong** [comment]
Please also include below in your settings:

    cmap('<ArrowDown>', '<Shift-Tab>');
    cmap('<ArrowUp>', '<Tab>');
