### ISSUE TITLE
shortcut to make fullscreen 

### ISSUE THREAD

**Issue by cibinmathew** [brookhong/Surfingkeys#1355]
**Feature**
Is there a way to assign a custom key binding to make the page fullscreen.
Home keys are more reachable and useful than F11 in some cases.

**Example**
Use 'af' to toggle fullscreen instead of the browser builtin key:F11

**Comment by lostrepo** [comment]
@cibinmathew see https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen/#Examples to add own mapping

**Comment by cibinmathew** [comment]
@lostrepo Is there a way to make the page go fullscreen for normal pages(not video fullscreen).

**Comment by cibinmathew** [comment]
Found one for whole page as well.
https://www.w3schools.com/howto/howto_js_fullscreen.asp

**Comment by Shamaoke** [comment]
@cibinmathew I'm interested in it as well. Could you, please, say how did you implement it?

**Comment by cibinmathew** [comment]
I got the below one working and is bound to `q`. Not tested with other than Chrome.

```

/* View in fullscreen */
function openFullscreen() {
    var elem = document.documentElement;
  if (elem.requestFullscreen) {
    elem.requestFullscreen();
  } else if (elem.webkitRequestFullscreen) { /* Safari */
    elem.webkitRequestFullscreen();
  } else if (elem.msRequestFullscreen) { /* IE11 */
    elem.msRequestFullscreen();
  }
}

/* Close fullscreen */
function closeFullscreen() {
    var elem = document.documentElement;
  if (document.exitFullscreen) {
    document.exitFullscreen();
  } else if (document.webkitExitFullscreen) { /* Safari */
    document.webkitExitFullscreen();
  } else if (document.msExitFullscreen) { /* IE11 */
    document.msExitFullscreen();
  }
}


function openFullscreen_toggle() {
  if (!document.fullscreenElement) {
    openFullscreen();
  } else {
    closeFullscreen();
  }
}

mapkey('q', 'full screen', function() {
    openFullscreen_toggle(); 
});

```

**Comment by Shamaoke** [comment]
@cibinmathew That works in Firefox as well. Thank you very much!

**Comment by Shamaoke** [comment]
@cibinmathew If we don't care other browsers, I think it's legit to shorten the code to oneliner.

```javascript
mapkey( 'q', '#3Toggle fullscreen', ( ) => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen() )j
```

**Comment by cibinmathew** [comment]
Yeah, other mentioned browsers are not supported by surfingkeys as well :-)

**Comment by 097115** [comment]
@Shamaoke , @cibinmathew 

Speaking of fullscreen, it seems to reset if we switch tabs, isn't it?

Or do you use some other way to toggle it nowadays? :) (sorry for a bit of necrobumping...)

**Comment by Shamaoke** [comment]
@097115 As time has shown, our solution has enough flaws. Here are some, which I have found:

  • When in the fullscreen mode, the Esc button brings the browser back into the normal mode

  • When in the fullscreen mode, the Alt-Tab button brings the browser back into the normal mode

  • When in the fullscreen mode, navigating to another web-page (e. g. by clicking a link) brings the browser back into the normal mode

  • If a web-page contains frames, going to fullscreen results in only one frame is displayed in the viewport

  • Web-page contents jitter when going to the fullscreen mode

Because of the aforementioned flaws, I've never used this method of toggling the fullscreen mode a lot.

I've not been able to solve the problem with changing the fullscreen shortcuts so far. But, it's still relevant for me.

**Comment by 097115** [comment]
@Shamaoke 

But the browser's native fullscreen does work for you, doesn't have all the mentioned problems, and you just don't like the native mapping, `<F11>`, is this correct?

If so, then the solution is to remap `<F11>` on the system level, not in the surfingkeys.

On Linux, you can do it with [xkeysnail](https://github.com/mooz/xkeysnail), for instance, where you can even define a scope -- like, do a mapping only in a specified application, or in a group of applications (macOS has BetterTouchTool, which allows the similar thing).

On a downside, with xkeysnail you won't be able to use `af` for such a mapping, but you can sure define something like `<C-f>`, for example, or even introduce a multiple stroke emacs-like binding, like `<C-x>f`.

(My task was a bit more difficult, I wanted to use `<F11>` in surfingkeys  for my own purposes, so

  - I mapped `<F10>` to `<F11>` in xkeysnail
  - Then I mapped `<F11>` to `<Alt-F11>` also in xkeysnail
  - And then I mapped `<Alt-F11>` to my own function in surfingkeys

As a result, pressing `<F10>` now toggles browser's native fullscreen, and pressing `<F11>` launches my custom function.)

**Comment by Shamaoke** [comment]
@097115 There's another app similar to xkeysnail. It's [xremap](https://github.com/k0kubun/xremap). I haven't had time to look into it yet. Perhaps, the thing with specific type of key remapping that you are talking about is available there.
