### ISSUE TITLE
Support for Safari?

### ISSUE THREAD

**Issue by ashkrosh** [brookhong/Surfingkeys#1361]
Hi
Is there any plan to support Safari in future?

Best

**Comment by e-volusian** [comment]
Probably not. Check out Vimari

https://apps.apple.com/us/app/vimari/id1480933944?ls=1&mt=12

**Comment by VMatrix1900** [comment]
> Probably not. Check out Vimari
> 
> https://apps.apple.com/us/app/vimari/id1480933944?ls=1&mt=12

Why not? Apple introduces a way to convert chrome plugin to safari extension.

**Comment by e-volusian** [comment]
I assume you're talking about [this](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari). I don't know if or how well it does or doesn't work. I do know that other popular chrome extensions such as RES have [explicitly stated] (https://redditenhancementsuite.com/safari/) that:

```
due to a large lack of API support that RES relies on, to get RES working on Safari at this time would require significant time and support investments that the development team does not have
```
 
I don't blame them. As an end user, it's just easier to use existing alternatives for surfingkeys-equivalent functionality on macos.

**Comment by brookhong** [comment]
Here it comes https://apps.apple.com/us/app/surfingkeys/id1599827286 , but It is not free.

So far due to lack of some webextension APIs, some shortcuts are not available, but most of functions are good. I will keep an eye on Apple's update on webextension APIs , and make those missing features available as soon as the APIs are ready.

**Comment by ivanddm** [comment]
You are awesome man! Thanks a lot for this 🙏🏻

**Comment by ivanddm** [comment]
Quick question.

I've been trying the Safari extension and overall is working quite well. However it seems like "map" and "mapkey" functions are not available, right? If I try something like `map('q', 'E');` I get this popup:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/20104703/145875675-8c15ac37-98ff-4743-8e4a-23dbf18da72c.png">

Setttings like `settings.scrollStepSize = 130;` are working fine though.

Finally, the standard shortcut for the omnibar `t` is not available. I wonder why as the extensions has omnibar support.

In any case, thanks again for this as it makes Safari usable for me.

**Comment by brookhong** [comment]
@ivanddm 

About the api such as `map`, please see https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

`t` is not available because the APIs like `chrome.history` and `chrome.bookmarks` is still missing from Safari, we're looking forward to those API from Apple.

**Comment by ivanddm** [comment]
@brookhong Thanks a lot for the clarification about migrating the settings from 0.9.74 to 1.0. `map` and `mapkey` are working for me now as expected 👍🏻

**Comment by aureusx** [comment]
Are you able to offer the extension in App Stores outside the US as well? Is there a reason for this limitation? I would love to use Surfingkeys in Safari!

**Comment by Massolari** [comment]
I'm in Brazil and I can't download it too. It says the extension is not available in my region
