### ISSUE TITLE
Triggering hints (or any other overlay) causes white page when using Github with dark theme

### ISSUE THREAD

**Issue by paradox460** [brookhong/Surfingkeys#1363]
## Error details

Whenever I hit any key that triggers any sort of overlay (hints, leader keys, omnibox, etc) the entire page is rendered white.

Looking in the chrome console, if I set the iframe that surfingkeys renders stuff in as `opacity: 0`, everything goes back to normal

SurfingKeys: 0.9.68

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

URL: https://github.com

**Comment by WANDEX** [comment]
I confirm, thanks for creating this issue, disabling github dark theme really helped me.
