### ISSUE TITLE
Open hints on current tab

### ISSUE THREAD

**Issue by silencial** [brookhong/Surfingkeys#1365]
Is there any way to open hints on current tab? I added this mapping but it didn't work.

```
mapkey('of', '#1Open a link in current tab', function() {
    Hints.create("", Hints.dispatchMouseClick, {tabbed: false});
})
```

**Comment by cibinmathew** [comment]
Try adding active flag as well
`
mapkey('of', '#1Open a link in current tab', function() {
    Hints.create("", Hints.dispatchMouseClick, 
{ tabbed: false, active: true });
})
`

**Comment by silencial** [comment]
Tried it, still open with a new tab.

**Comment by cibinmathew** [comment]
Does this happen for all the sites?

**Comment by silencial** [comment]
Yes. I tried several websites and it all behaved the same as the default `f` key.

**Comment by brookhong** [comment]
If a link was coded to be opened in a new tab in HTML code, there is no way to open it in current tab. By default, `f` will always try to open a link in current tab if the link is not hard coded to be opened in a new tab.

**Comment by silencial** [comment]
I see. Is there any way to generate a key that can mapped to sequence of actions so we can bypass this problem? For example, first copy the link to clipboard and then open it in current tab.

**Comment by b0o** [comment]
@silencial Try this:

```js
mapkey("of", "Open link in current tab", () => Hints.create("*[href]", (e) => location.assign(e.href)));
```

**Comment by silencial** [comment]
@b0o It works perfectly! Thank you all.
