### ISSUE TITLE
Surfingkeys is causing Github to become all white

### ISSUE THREAD

**Issue by kalbasit** [brookhong/Surfingkeys#1367]
## Error details

SurfingKeys: 0.9.68

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

## Context

Surfingkeys started causing the GitHub page to go all white since yesterday. I have not changed anything on my system to cause this issue. I've disabled all other extensions leaving only Surfingkeys enabled and I still get the same issue. I can replicate the same issue with the Brave browser as well.

Video URL: https://www.awesomescreenshot.com/video/2156386?key=a31264026e72efa014bdaf19620638ab

In the above video, you can see after every reload the page shows up then becomes all white again.

**Comment by brookhong** [comment]
I can not reproduce this issue with Chrome 87.0.4280.88 under Ubuntu 19.10.

![image](https://user-images.githubusercontent.com/288207/102894744-87468780-449e-11eb-9f7a-4cd237d76fb0.png)

**Comment by kalbasit** [comment]
> I can not reproduce this issue with Chrome 87.0.4280.88 under Ubuntu 19.10.
> 
> Thanks to #1363, I can reproduce with github dark theme on.

Ah, so it's only triggered by the dark theme. Interesting, it used to work fine a couple of days ago :thinking: Thanks for looking into this.

**Comment by kalbasit** [comment]
Did this get fixed with https://github.com/brookhong/Surfingkeys/commit/09873f0bd1f0edf1b83ff75a3f48162bff69d18d? It's not released yet and I have not tried the latest master yet either.

**Comment by brookhong** [comment]
Yes, 0.9.69 was released, please upgrade to it and have a try.

**Comment by jmolero** [comment]
@brookhong I’m having the same issue in Safari. Doesn’t matter if using the light or dark theme.
