### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Jason4774** [brookhong/Surfingkeys#137]
1.这里应该是关于页面，写错了
![20161107_222328](https://cloud.githubusercontent.com/assets/19594338/20061035/f7800832-a538-11e6-8d1f-7286882b30be.png)
2.请问你gif图片中的右下角那个蓝色的按键提示是什么软件呢？
谢谢。

**Comment by brookhong** [comment]
1. 谢谢。
2. 那个软件是Mac下的，叫[keycastr](https://github.com/keycastr/keycastr)

**Comment by Jason4774** [comment]
![image](https://cloud.githubusercontent.com/assets/19594338/20083780/4d9a5d20-a599-11e6-877a-6bc2f5fe83db.png)
但是这个ctrl+1是会跳到第一个标签页，而没有show pressed key
