### ISSUE TITLE
Firefox: Omnibar -> How can I reverse the behavior of `Enter` and `Shift+Enter`?

### ISSUE THREAD

**Issue by NicholasBHubbard** [brookhong/Surfingkeys#1378]
I would like it if `Enter` would open my search in the current tab and `Shift+Enter` would open the search in a new tab.

**Comment by nemya9066** [comment]
You will need to remap all you search engine keystrokes the example below will replicate the behavior you want for google search you can remap the rest.
mapkey('og', '#8Open Search with alias google', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "g", tabbed:false});
})
You will need to add the 'tabbed:false' property to all other mappings you can get these mappings from the default.js mapping file here:
https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js

**Comment by piersolenski** [comment]
Would it be possible to add this as a global setting?
