### ISSUE TITLE
Surfingkeys not working on some "google" URLs

### ISSUE THREAD

**Issue by htrej** [brookhong/Surfingkeys#138]
For some reason, I am unable to use any keys (such as x,h,j,k,l,etc.) for Surfingkeys on _some_ google domain urls. I was going to say _any_, but I recently tried "support.google.com" and "cloud.google.com" and the keys work on those servers. For now, I can confirm that

- It's _not_ working on any google.com/* (which do not redirect to another site). Example cases:
    - the search engine home page and google search results
    - google.com/nonprofits
    - google.com/services
    - google.com/bookmarks, etc...
    - google.com/googleblog _works_ (i'm guessing it's because of the redirect to blog.google)
- _not_ working on chrome.google.com/webstore
    - Note that for the above google.com/* cases the Surfingkeys blue icon in the chrome menu were _greyed out_. But in this case, it is _not_ greyed out (still blue).
    -  Note that chrome.google.com (without webstore) is also _not_ working,
        - ^ this redirects to google.com/chrome, icon greys out.
- _not_ working on blank chrome new tab. 
    - icon remains blue
- _is_ working on sites like gsuite.google.com and play.google.com 

So far thats all that I've tested at the moment. There are many google sites to test but those give you an idea/the main pattern.

So, is there any way I could fix this?
Other things to note:
- I haven't really changed any settings other than disabling smooth scrolling. 
- But I did also change "Where to store your settings" from chrome.storage.local to chrome.storage.sync, though I'm not 100% sure what it does (I'm assuming it allows for the settings to sync with my google account?).
- I checked to make sure the above google sites were not blacklisted or anything, though I never used a blacklist.

[The about issue may or may not have been occurring since I started using your extension as I just noticed this behavior a few hours ago (in other words, I'm not sure if I "broke" the extension on these pages (though most of them I did not ever visit prior to Surfingkeys) or if it's just an issue with the extension itself. I've only just recently switched from cVim to Surfingkeys)]

**Comment by brookhong** [comment]
The icon greys out, that means Surfingkeys is disabled by pressing `<Alt-s>`.

You could turn it on by another `<Alt-s>`.

And yes, chrome.google.com -- this domain is not allowed to run content scripts from extensions by Google. Thus Surfingkeys will not work on that site.

**Comment by htrej** [comment]
Ah, that fixed it. It took a while to respond but the <kbd>Alt-s</kbd> worked at least for google search. Thanks.
