### ISSUE TITLE
Unable to remap omnibar

### ISSUE THREAD

**Issue by seanfarley** [brookhong/Surfingkeys#1381]
## Error details

SurfingKeys: 0.9.68

Browser: Firefox 84.0.1 MacOS 11.1

URL: all urls

## Context

Having the mapping `map('<Alt-x>', ':');` produces the backtrace:

```
Uncaught TypeError: s is undefined
    listResults moz-extension://c429327e-1f0c-714b-9ca1-90eef642e275/pages/omnibar.js:1
    listWords moz-extension://c429327e-1f0c-714b-9ca1-90eef642e275/pages/omnibar.js:1
    updateOmnibarResult moz-extension://c429327e-1f0c-714b-9ca1-90eef642e275/pages/front.js:1
    Front moz-extension://c429327e-1f0c-714b-9ca1-90eef642e275/pages/front.js:1
omnibar.js:1:11444
```

**Comment by seanfarley** [comment]
Also, by looking at the source code, one can use the following to acheive the same:

```js
mapkey('<Alt-x>', 'Open omnibar', function() {
  Front.openOmnibar({type: "Commands"});}
);
unmap(':');
```

But it seems more robust to have `{type: "Commands"}` be the default value for the function.

**Comment by MD7GIT** [comment]
I was trying to use '<Ctrl-t>' to open omnibar. It works with '<Ctrl-l>' and '<Alt-t>'
