### ISSUE TITLE
Github dark mode breaks most surfingkey functionality

### ISSUE THREAD

**Issue by Neylion** [brookhong/Surfingkeys#1383]
## Error details
SurfingKeys: 0.9.68
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
URL: https://github.com/

## Context

**After enabling githubs new dark mode, many surfingkeys shortcuts break and result in a completely blank/white screen until you escape out of them. For example the shortcuts "/" and "f". After disabling the dark mode things work as they should again.**

**Comment by ixzh** [comment]
> many surfingkeys shortcuts break and result in a completely blank/white screen

I think key bindings are still working, just the appears white-ish... is it because of CCS?

**Comment by brookhong** [comment]
This should be a duplicate issue of #1363, new version will be released soon to address this issue.

**Comment by brookhong** [comment]
0.9.69 was released.
