### ISSUE TITLE
hints don't show up on certain elements

### ISSUE THREAD

**Issue by joech4n** [brookhong/Surfingkeys#139]
For example on the Github pages, the "Watch" button dropdown is not clickable by hints **f** key. I also tried **q**, but it also doesn't seem to work. Any ideas why?

**Comment by joech4n** [comment]
Another example page: https://gist.github.com/joech4n/1b3d394ceb8b776f06d7
If you try to click the "Star" button (not the number next to the star).

**Comment by brookhong** [comment]
Thanks for reporting this issue.
