### ISSUE TITLE
Chat room/forum for questions?

### ISSUE THREAD

**Issue by jo-so** [brookhong/Surfingkeys#1393]
I know this is not really a bug report more like a feature request. 😉 Is there any way to talk to you and other users? Do you use any kind of chat system (like Matrix.org)?

I have some questions like “How to swap keys r↔R” or “Are the key functions accessible via name?”

**Comment by Shamaoke** [comment]
It could be realized by the use of [GitHub discussions][*]. Here's an [example][†] of how it looks like.

[*]: https://docs.github.com/en/discussions

[†]: https://github.com/github/docs/discussions

**Comment by mskar** [comment]
This issue I just opened is a great example of a use case for a chat room / forum: #1394

**Comment by brookhong** [comment]
@Shamaoke Awesome, thanks, I have enabled `Discussion` for this repo. Looks like I could close most issues now. 😃

**Comment by jo-so** [comment]
Yes. I think this solves the issue.
