### ISSUE TITLE
Opening a link in new tab navigates to undefined.com

### ISSUE THREAD

**Issue by nemwiz** [brookhong/Surfingkeys#1415]
## Error details
When navigating with Shift key pressed (to open the link in a new tab) I always get redirected to undefined.com page.
I've recorded a [small gif ](https://gifyu.com/image/VQhu) that shows an error.

SurfingKeys: 0.9.69

Browser: Mozilla Firefox for Ubuntu 85.0.1 (64-bit)

URL: This happens on every url.

**Comment by KNIX3** [comment]
For me, this only happens on certain links. I think it's attempting to open 'undefined' and the browser is redirecting that to 'undefined.com'. I can see the redirect in real time on my computer, at least.


userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

**Comment by xicod** [comment]
Happens for me also.
I did manage to find a workaround: instead of 'f', use 'gf'.
Now hitting the labels will open the link in a new tab unfocused, while holding Shift and label will also focus the new tab.
