### ISSUE TITLE
Use key sequence as escape key

### ISSUE THREAD

**Issue by borgnix** [brookhong/Surfingkeys#142]
Is there any way for SurfingKeys to map a key sequence to escape key in insert mode?
Vim supports configurations like `imap fd <esc>`
If two keystokes are close enough(like no more than 0.5s), Vim will act like receiving a <Esc>, or the keystrokes will be treated like ordinary inputs.
Can SurfingKeys support that?
Thanks!

**Comment by brookhong** [comment]
Will be released in 0.6.7

    imap(',,', "<Esc>");        // press comma twice to leave current input box.
    imap(';;', "<Ctrl-'>");     // press semicolon twice to toggle quote.

**Comment by DaanHaaz** [comment]
I hope it's okay to ask it here since it's relevant.
Typing ,, to exit an input box doesn't work.
I also tried adding this:

`imap('<Ctrl-;>', "<Esc>");`

But that doesn't work either.
Am I doing something wrong?
