### ISSUE TITLE
Firefox version "i" doesn't move focus in the Firefox website

### ISSUE THREAD

**Issue by seaspeak** [brookhong/Surfingkeys#1421]
reproduction:
1. got to https://addons.mozilla.org/en-US/firefox/
2. press "i"

In Chrome, it does work in Firefox's website.

**Comment by b0o** [comment]
This is not a bug, it's a security measure that Mozilla takes to prevent extensions from doing weird things on the `addons.mozilla.org` subdomain like installing other extensions. Chrome does the same thing on `chrome.google.com/webstore`.
