### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by StoicIndividual** [brookhong/Surfingkeys#1427]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

yes

SurfingKeys: <0.9.69>

Browser: <brave 1.21.73><Artix Linux>

## Context

I can't change the color of the beginning mark in visual mode, I tried using this in the settings:
`#sk_hints .begin {
   color: #98be65 !important;
}`
but that didn't work so I tried this:
`#sk_hints[mode=text]>div.begin {
    color: #98be65 !important;
}`
and that didn't work too, how can I change the color of the .begin mark in visual mode?

**Comment by brookhong** [comment]
This was not supported. I just committed a fix, with which you could use settings like

    Hints.style("div{border: solid 3px #707070; color:#efe1eb; background: none; background-color: #707070;} div.begin{color:red;}", "text");
