### ISSUE TITLE
Add disable on this page/domain context action

### ISSUE THREAD

**Issue by vyorkin** [brookhong/Surfingkeys#143]
It would be useful to have one, it exists in https://github.com/1995eaton/chromium-vim

**Comment by brookhong** [comment]
Why don't just use `<Alt-s>`?

**Comment by vyorkin** [comment]
@brookhong oops, thanks, missed that

**Comment by vyorkin** [comment]
though it doesn't work in all cases, e.g. when you use jsbin & vim mode pressing `<Alt-s>` will output `ß`
