### ISSUE TITLE
Any similiar solution for browsing and annotating PDF?

### ISSUE THREAD

**Issue by smilingsun** [brookhong/Surfingkeys#144]
I really appreciate the masterpiece provided by this repo, because web surfing is our daily routine.

But some reading materials are only available in PDF format, so any solution of browsing and annotating PDF using vim-like keybinding can be suggested?
 
I'm currently **almost** satisfied with ``okular``, because it provides ``configure shortcuts``,  but it lacks ``half-screen scrolling`` support, which is a little bit annoying...

**Comment by brookhong** [comment]
This should have been fixed after `pdf.js` introduced.
