### ISSUE TITLE
v0.9.73 breaks setting of label sizes

### ISSUE THREAD

**Issue by xicod** [brookhong/Surfingkeys#1444]
Hi,

Using firefox (78.10.0esr) and the latest version 0.9.73 broke setting the label sizes like so:

Hints.style('font-size: 15px;');
Hints.style('font-size: 15px;', 'text');

They just default to much smaller ones.

Downgrading to v0.9.65 restored this ability.

Thanks

**Comment by popawu** [comment]
Hi,

Same issue here with FF 88.0 & SK 0.9.73.
`Hints.style` is not respected at all, rollback to 0.9.65 fixed the issue
