### ISSUE TITLE
Firefox prevented this site from opening pop-up window.

### ISSUE THREAD

**Issue by Alexey104** [brookhong/Surfingkeys#1446]
Hi!
My browser is Firefox 88 on Arch. For a long time I had been using Vimium, but recently I found SurfingKeys and switched to it. It is a great addon, and I like it,  but there is an issue with it - some websites open external links in new tabs by default, and every time I try to open such links using SurfingKeys I get this annoying _'Firefox prevented this site from opening pop-up window'_ message at the top of the screen. I have to explicitly tell SurfingKeys to open the link in a new tab or just use mouse click to avoid this issue. Don't have such a problem with Vimium. 
Can I fix it without disabling Firefox '_Block pop-up windows_' option?

**Comment by Alexey104** [comment]
This is what I am talking about:

![Peek 2021-04-26 20-36](https://user-images.githubusercontent.com/38672094/116126747-aadd4100-a6cf-11eb-9eb8-f52e9e7a4e38.gif)

**Comment by kendisiz** [comment]
Same problem here too!

**Comment by polinom11** [comment]
I also have a problem with this. Is there really no solution?

**Comment by flyxyz123** [comment]
# my solution

add `keydown` for `dom.popup_allowed_events` in `about:config`

# steps
1. open `about:config` in url bar
2. search `dom.popup_allowed_events`
3. click pencil icon to edit the preference
4. add `keydown` in the text box 

# notes
the deafult value for `dom.popup_allowed_events` seems is:
```
change click dblclick auxclick mousedown mouseup pointerdown pointerup notificationclick reset submit touchend contextmenu
```
after edit:
```
keydown change click dblclick auxclick mousedown mouseup pointerdown pointerup notificationclick reset submit touchend contextmenu
```

# references
<https://github.com/arkenfox/user.js/blob/d9af90d05f477e5e25f8d9f545eeb7fe0a235d2a/user.js#L669>
<http://kb.mozillazine.org/About:config_entries#:~:text=dom.%20popup_allowed_events>

**Comment by Alexey104** [comment]
@flyxyz123, Yeah, it works, thank you!

**Comment by polinom11** [comment]
Thanks, works great!
