### ISSUE TITLE
Copy page URL

### ISSUE THREAD

**Issue by MaxGyver83** [brookhong/Surfingkeys#1455]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) No.
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md) No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes.

## Error details

SurfingKeys: 0.9.74

Browser: Firefox 88.0 (Ubuntu 20.04)

URL: any

## Context

This is not a bug report. It's a question.

I often copy the URL of the current page for inserting it afterwards somewhere else (p.e. in an e-mail). For this simple action I have to press `Ctrl-l`, `Ctrl-c`, then `F6` to unfocus the address bar. Can I do the same with one or two key strokes using SurfingKeys? I couldn't find how. But I suppose it's a very common task, so it might be possible to do this with SurfingKeys.

**Comment by Shamaoke** [comment]
`yy` (See other keys for working with the clipboard at the “Clipboard” section in the help popup `?`)

> This is not a bug report. It's a question.

[Github Discussions](https://github.com/brookhong/Surfingkeys/discussions) is more appropriate place for questions.
