### ISSUE TITLE
How to click on video/images?

### ISSUE THREAD

**Issue by alfonz19** [brookhong/Surfingkeys#1465]
Not sure if this is an issue or I just cannot see how to do that, but sometimes I need to click on image or on video startup playback and I cannot see a way how to do that without mouse. Is there a way?

**Comment by eugercek** [comment]
Does `q`  `Click on an Image or a button` solves your problem?

**Comment by alfonz19** [comment]
this is an old issue, I cannot remember where I had the issue. If the 'q' exist back then. On most pages 'f' or 'q' works now. I can find some where neither works, but it's more like exception. Thanks.
