### ISSUE TITLE
cannot load extension manually (Brave)

### ISSUE THREAD

**Issue by molleweide** [brookhong/Surfingkeys#1479]
Hi,

I have forked the project and am trying to load the extension by selecting the git repo under `extensions > load unpacked`.

This gives me this error 
```
Failed to load extension
File
~/code/Surfingkeys
Error
Could not load javascript 'content_scripts/modules.min.js' for content script.
Could not load manifest.
```
The same error also occurs if I try to pack the Surfingkeys extension.

I have never loaded an extension manually before so I might be missing something obvious I'm thinking. I am selecting the whole `Surfingkeys` repo directory under `load unpacked`.

**Comment by b0o** [comment]
You need to do a few things first: 

0. ensure you have node.js installed
1. Install dev dependencies with npm 
2. Build the extension with gulp 
3. Load the extension from the `dist/Chrome-extension` subdirectory:

In a terminal: 

```
$ git clone https://github.com/brookhong/Surfingkeys
$ cd Surfingkeys
$ npm install
$ gulp build # The built extension will be at dist/Chrome-extension
```

Note to anyone finding this issue in the future but interested in building for Firefox: You need to run the `gulp firefox` task rather than `gulp build`.

**Comment by molleweide** [comment]
Embarassing. I totally missed this but of course this makes sense now. Thanks for telling me b0o!
I feel like I must have been totally blind because now that I see it it is quite obvious :D

**Comment by b0o** [comment]
No worries, I'm sure this will help someone else in the future! Go ahead & close the issue if it's fixed (I don't have perms 😉)

**Comment by molleweide** [comment]
Yes! This works in Chrome/Brave but I am actually unsure of how to load it into firefox. Firefox doesn't seem to accept `.../code/Surfingkeys/dist/Firefox-extension`. I am searching around to understand why

**Comment by b0o** [comment]
I just updated my original comment, you probably need to sign the extension (you'll need a [Mozilla developer account](https://addons.mozilla.org/en-US/developers/)).

**Comment by molleweide** [comment]
oh really? well, thanks again for the info because I did not find any quick info indicating i need a developer account at first.

**Comment by b0o** [comment]
Yeah, a bit annoying but I believe it's a security measure. More info: https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/
