### ISSUE TITLE
Cannot use Surfingkeys when browsing GitHub in Firefox

### ISSUE THREAD

**Issue by syusuyly** [brookhong/Surfingkeys#1483]
SurfingKeys: Version 0.9.74
Browser: Firefox 89.0 (64-bit) Windows 10 21390.2025

Recently I switched from Microsoft Edge to Firefox and I find that when I browse GitHub projects, Surfkeyings' keymaps don't work properly. In Microsoft Edge, the predefined keymaps of GitHub are overloaded by Surfingkeys by default, but in Firefox I cannot use any keymaps defined in Surfkeyings even they are not conflicted with Github's.

**Comment by b0o** [comment]
Did you unintentionally [disable](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys) SurfingKeys on GitHub? Try to press `Alt-s` while you're on `github.com`.

**Comment by syusuyly** [comment]
Thank you for your reply. I didn't know enough about Surfingkeys denylist mechanism before. I just clicked `yj` to export the settings and found that I added github.com to the denylist unconsciously.

**Comment by b0o** [comment]
Great! I also appreciate your use of the word denylist. I opened an issue to address potentially changing that: #1486
