### ISSUE TITLE
Unable to remap 'on' to 'ont' for new tab

### ISSUE THREAD

**Issue by Fi-lho** [brookhong/Surfingkeys#1490]
## Error details

Replacing 'on' with 'ont' for newtab shortcut doesn't work:
```js
map('on', 'ont');
```

I've also tried unmaping and replacing it with the default code:
```js
unmap('on');
if (window.navigator.userAgent.indexOf("Firefox") > 0) {
    mapkey('ont', '#3Open newtab', function() {
        tabOpenLink("about:blank");
    });
} else {
    mapkey('ont', '#3Open newtab', function() {
        tabOpenLink("chrome://newtab/");
    });
}
```

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by brookhong** [comment]
Your code works for me with `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0`

**Comment by 097115** [comment]
@brookhong 

Hm... I see @Fi-lho has Firefox v.78... Could it be that [ESR](https://www.mozilla.org/en-US/firefox/78.0esr/releasenotes/) is somehow the culprit? 

I have this in my config, too:

    mapkey('\\', '#3Open home page', function () {
        tabOpenLink("https://duckduckgo.com");
    });

And while it works with Brave, it does absolutely nothing with Firefox 78.12.0esr (`Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0`)

Or may be @Fi-lho has already figured it out? :)

**Comment by Fi-lho** [comment]
> @brookhong
> 
> Hm... I see @Fi-lho has Firefox v.78... Could it be that [ESR](https://www.mozilla.org/en-US/firefox/78.0esr/releasenotes/) is somehow the culprit?
> 
> I have this in my config, too:
> 
> ```
> mapkey('\\', '#3Open home page', function () {
>     tabOpenLink("https://duckduckgo.com");
> });
> ```
> 
> And while it works with Brave, it does absolutely nothing with Firefox 78.12.0esr (`Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0`)
> 
> Or may be @Fi-lho has already figured it out? :)

I gave up after a few tries, from what @brookhong said, the extension is probably focused on the latest browser releases.
