### ISSUE TITLE
"f" works, but not "cf" or "gf"

### ISSUE THREAD

**Issue by almqq** [brookhong/Surfingkeys#1492]
## Error details
Hi, I'm a happy surfingkeys user. But one error I'm finding more and more is that while "f" correctly brings up all the links, "gf" and "cf" don't - only a small subsection of links come up. A good example of this is at https://search.brave.com/search?q=brave (do any search)

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

URL: https://search.brave.com/search?q=brave

## Context

try any search on https://search.brave.com/search

**Comment by tural-esger** [comment]
The same heppens to me ((

**Comment by brookhong** [comment]
Should have been fixed.
