### ISSUE TITLE
how change cursor color

### ISSUE THREAD

**Issue by molleweide** [brookhong/Surfingkeys#1493]
Hi,

l put this in my config file:
```
settings.theme = `
...
...
.surfingkeys_cursor {
    background-color: #CC5305;
}
`;
```

also .sk_cursor is not working either.

Ofc, if I change the color inside of content scripts.css then cursor color changes but I am thinking that this should be
in the config right??

**Comment by edshamis** [comment]
@molleweide Can you please post how you got cursor to change colour?
