### ISSUE TITLE
打开链接的提示偶尔互相遮掩。

### ISSUE THREAD

**Issue by thaoeu** [brookhong/Surfingkeys#1499]
![2021-07-14_17-25](https://user-images.githubusercontent.com/34019378/125599090-36e5be2e-ebc3-402b-8a38-18eff11ff9a5.png)
![2021-07-14_17-25_1](https://user-images.githubusercontent.com/34019378/125599101-624283fe-f40c-405b-81b7-568ba0d37033.png)
![2021-07-14_17-25_2](https://user-images.githubusercontent.com/34019378/125599111-5b18a07c-f057-47b4-8b6c-f5978454912c.png)
而且大多情况下在前面那个是网页快照。

**Comment by 0900304132** [comment]
可以按住空格 或者 按一下shift.

**Comment by thaoeu** [comment]
按 shift 确实有效，感谢。

> 可以按住空格 或者 按一下shift.
