### ISSUE TITLE
Pattern not found when searching for number

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#15]
I can't seem to search a page for numbers. "results not found" message

**Comment by brookhong** [comment]
It's not because of numbers. There is a requisite for finding in page, length of input must be longer than 2.

To have this check is to avoid poor performance in large pages. Any idea to balance this is welcomed.

**Comment by jaredbidlow** [comment]
well, this is no longer working as intended

**Comment by simonwjackson** [comment]
@brookhong This issue appears to be fixed. Requesting this issue to be closed

Confirmed in v0.9.10
