### ISSUE TITLE
International keyboards don't work

### ISSUE THREAD

**Issue by gabrielqv** [brookhong/Surfingkeys#150]
Hi, when using markers like "'m" with an international keyboard ( that requires the spacebar  so ' appears) it is not recognized by surfingkeys. any thoughs if this could be resolved? it seems like chrome catches the spacebar and the ' gets lost in time.

**Comment by brookhong** [comment]
You could refer to https://github.com/brookhong/Surfingkeys/issues/47.

**Comment by gabrielqv** [comment]
When using Ctrl+1 to check which keypress i make it shows <Dead> when i use  ' " ~ ` ^  solving this could be important as i suppose those are used for other shortcuts that would be difficult to remap and as international keyboard are a solution for non english people. thanks for the help though.

**Comment by gabrielqv** [comment]
I am sorry i didn't make it clear, when I used those keypresses it showed undefined or something like that now it shows this strange sign 
![image](https://cloud.githubusercontent.com/assets/17986440/21294337/61423c42-c508-11e6-8a21-7bb1b7ab6074.png)

**Comment by flick36** [comment]
Any solution on this?

**Comment by brookhong** [comment]
Hi, 

When it shows a pencil emoji, what actual key are you pressing?

**Comment by flick36** [comment]
the `'` char but in my keyboard in order to make ' appear, i need to hit the key and then space or some letter because that key also sets a Diacritic or acute, like: `á` in some letters

**Comment by brookhong** [comment]
Guys, please try `spk` in 0.7.1

Then press the key and see what Surfingkeys recognizes.

![image](https://cloud.githubusercontent.com/assets/288207/22069221/92685972-ddd2-11e6-932e-4fadcfd493ac.png)

**Comment by gabrielqv** [comment]
I am sorry i don't understand what is spk, still a little noobie for github...
also ctrl+1 doesn't work anymore? ( it is managing tab selection)

**Comment by brookhong** [comment]
Yes, `Ctrl-1` is replaced with `spk`, which means `Show Pressed Key`.

**Comment by gabrielqv** [comment]
I am sorry that i took so long, but the problem is in fact fixed, international keyboards don't lose their keys now!

**Comment by zoomido** [comment]
I tried `spk` and `Ctrl-1` and also searched in the code but couldn't find anything. Is this feature still in there somewhere? I'm having problems with `$` (end of line) on my swedish keyboard.

**Comment by brookhong** [comment]
No, this feature has been removed, but you could get same thing from settings.
1. `se` open settings
1. Turn off `Advanced mode`
1. `fs` to click on the key label `d`, a popup will appear.
1. now press any key, which will be displayed on the popup.
1. Just remember to press `Esc` to dismiss the popup, as you won't like to override `d` key.

**Comment by zoomido** [comment]
Okay that helps. Thank you!
