### ISSUE TITLE
View list of disabled sites

### ISSUE THREAD

**Issue by AndreasNasman** [brookhong/Surfingkeys#1501]
Is it possible to view all sites on which Surfingkeys is currently disabled? [Here](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys) it's mentioned that

> When Surfingkeys is turned off on some site by Alt-s, the status will be persisted in settings, for example,
"blocklist": {
    "https://github.com": 1
},

but which exact settings are the documentation referring to? I don't see a `blocklist` property in the settings accessible by clicking `Settings` on the extension icon or pressing `;e` (with `Advance mode` turned on).

– Andreas

**Comment by brookhong** [comment]
You can use `yj` to dump all settings data to system clipboard, paste it in some text editor, then search `blacklist`( or `blocklist` which has not been released).

**Comment by AndreasNasman** [comment]
Thanks, exactly what I was looking for! Missed it when I was looking through the keyboard shortcuts. 👌
