### ISSUE TITLE
如何映射原始的f键，让油管视频快速全屏

### ISSUE THREAD

**Issue by HZzz2** [brookhong/Surfingkeys#1502]
想通过Alt+c的组合键 映射成原始的f键，对应油管的全屏快捷键，可是在Surfingkeys里f键有特殊功能，不知道怎么设置。求教，感谢
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: <version>

Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by flyxyz123** [comment]
`pf`

https://github.com/brookhong/Surfingkeys#passthrough-mode

**Comment by HZzz2** [comment]
> `pf`
> 
> https://github.com/brookhong/Surfingkeys#passthrough-mode

感谢！

**Comment by brookhong** [comment]
`pf`应该能解决你的问题，也可以在设置页面改掉`f`键

![image](https://user-images.githubusercontent.com/288207/202899059-977b950d-ceea-4a5a-b37a-098fda843a3e.png)
