### ISSUE TITLE
为什么ctrl+j是f的效果，我能取消掉吗？

### ISSUE THREAD

**Issue by yuzhen1024** [brookhong/Surfingkeys#1503]
~

**Comment by thaoeu** [comment]
同问，和打开下载的快捷键冲突了。

**Comment by flyxyz123** [comment]
`;e` / advenced mode / 添加 `unmap('<Ctrl-j>');` / save\
注意`Ctrl`中的C要大写

**Comment by yuzhen1024** [comment]
> 只在firefox上试过
> `;e`/进阶模式/添加`unmap('<Ctrl-j>');`/保存
> 注意`Ctrl`中的C要大写

完美解决。
