### ISSUE TITLE
Disabling Surfingkeys toggle banner

### ISSUE THREAD

**Issue by AndreasNasman** [brookhong/Surfingkeys#1505]
Is there a way to disable or hide the banner that appears when toggling Surfingkeys?
<img width="1322" alt="Screen Shot 2021-07-24 at 13 31 02" src="https://user-images.githubusercontent.com/17124245/126865798-0df63a5f-007a-446a-bac6-478b29db4212.png">
I toggle Surfingkeys quite a lot on e.g. Gmail and it feels a bit distracting to have the banner shown on every toggle.

**Comment by brookhong** [comment]
Maybe you can try [Passthrough Mode](https://github.com/brookhong/Surfingkeys#passthrough-mode), so that you need not toggle it quite a lot.

**Comment by AndreasNasman** [comment]
Fits my needs perfectly, thank you!
