### ISSUE TITLE
Memrise needs a temporal disable, but github always disable my extension

### ISSUE THREAD

**Issue by gabrielqv** [brookhong/Surfingkeys#151]
Hi me again, this tool's rather cool, however there're things that i couldn't find first it feels like GitHub has disabled surfing keys... I can't even get to the input vim field, also Memrise works with some shortcuts like  the num keys I wonder if you can access the insert mode or a pass through mode so those shortcuts work,

**Comment by brookhong** [comment]
please refer to [Hotkey to toggle Surfingkeys](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys).

You may have happened to disable Surfingkeys on github.

**Comment by gabrielqv** [comment]
Yes that was it, i also discovered that pressing alt will bypass setting of surfing keys in some webpages, so it could function as a temporal disable for sites that don't have casualties. thanks :) 👍
