### ISSUE TITLE
Error in console: DevTools failed to load source map

### ISSUE THREAD

**Issue by beisu** [brookhong/Surfingkeys#1529]
![image](https://user-images.githubusercontent.com/11241488/129832216-bef6dac6-fa22-4737-b03e-c073894b6fbb.png)

**Comment by aspiers** [comment]
I noticed this too, it's spamming DevTools console a lot :-(

**Comment by aspiers** [comment]
This is a duplicate of #1260, and PR #1261 fixes it.

**Comment by brookhong** [comment]
Should have been fixed in 1.0.
