### ISSUE TITLE
Feature request: Autocompletion in input mode

### ISSUE THREAD

**Issue by BlackCapCoder** [brookhong/Surfingkeys#153]
I find myself pressing CTRL+N in insert-mode all the time, expecting surfingkeys to autocomplete something I read on the webpage. It is surprising how often it comes up, and I think it would be a really neat feature.

**Comment by brookhong** [comment]
`Ctrl+n` is a native shortcut key of Chrome, which could not been re-bound. For autocompletion in insert mode, you could use `tab`.
