### ISSUE TITLE
使用yG截长屏时无反应并使原网页滚动条失效

### ISSUE THREAD

**Issue by isyntop** [brookhong/Surfingkeys#1535]
## Error details

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

URL: <https://cn.bing.com/search?q=volatile-lfu&form=QBLH&sp=-1&pq=volatile-lfu&sc=2-12&qs=n&sk=&cvid=8BEDAC6FCDD345D68591302432E5DF3F>

## Context

**网页截长屏时，按下yG之后，网页滚动一次就没反应了，也没给截图。同时网页滚动条失灵，无法继续滚动查看，只能刷新网页。.**

https://user-images.githubusercontent.com/20900723/133885467-647bb2c7-2d97-4088-8d8e-9e85c66ecbfd.mp4

**Comment by brookhong** [comment]
Fixed in 1.0.

**Comment by wangwenqiangGitHub** [comment]
我目前版本是1.0.5还有这个问题
