### ISSUE TITLE
Feature Request: disable key map for specific site & default scroll element & insert mode shorcut

### ISSUE THREAD

**Issue by hiberabyss** [brookhong/Surfingkeys#154]
I transfer from chromium-vim to Surfingkeys and you have done a great job! It will be better if following features could be provided:

1. Support setting of disable some key maps for specific sites. Since some sites may have their own key shortcut, they can not take effect because of conflict with Surfingkeys.

2. Choose max scrollable area element as the default. Sometimes, the default scrollable element is not what I want, I have to press `cs` to switch to the right scrollable element once the page is reloaded.

3. Add "Ctrl-u" shortcut in insert mode, which would delete text to the begin of the line.

Thanks!

**Comment by brookhong** [comment]
Thanks.

1. [Hotkey to toggle Surfingkeys](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys)

2.3 will be released in 0.6.7.

**Comment by hiberabyss** [comment]
Hi @brookhong, thanks for your reply.

"Hotkey to toggle Surfingkeys" is not what I want, since it will disable all Suringkeys mappings while I only need to disable specific Surfingkeys mapping.

For example, I want to use the key mapping `[` of "Atlassian Confluence" to open the sidebar, however, I also want to use the key mapping of Surfingkeys like `j/k` to scroll.

**Comment by brookhong** [comment]
Then you could use below in your settings

    unmap("[", /github.com/);

**Comment by hiberabyss** [comment]
The setting solves my problem. Thanks very much!

**Comment by hiberabyss** [comment]
Hi @brookhong , seems 0.6.7 has been released, while item 2 still can not be supported?

Thanks!
