### ISSUE TITLE
页面加载未完成状态下，sufingkey快捷键无法使用！

### ISSUE THREAD

**Issue by sdsundmu** [brookhong/Surfingkeys#1540]
## Error details
页面加载未完成状态下，sufingkey快捷键无法使用！

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by 0900304132** [comment]
js没有加载的时候就用不了
