### ISSUE TITLE
Surfingkeys 1.0

### ISSUE THREAD

**Issue by brookhong** [brookhong/Surfingkeys#1542]
I'm refactoring the project and will release 1.0 hopefully. The goal is to

* integrate with neovim with native messaging.
* settle down the public APIs for setting snippets and document them.
* improve the build process with webpack.
* add unit tests.
* remove the `Mermaid diagram generator`, which is unnecessary for the extension.

So no more feature requests or bugs will be addressed for current release 0.9.74. The code change is big, and will need some little change in your setting snippets, but there will be no impact if you're a basic user which means you don't customize setting with snippets. As said, the code change is big, I can not provide the expected date of arrival now.

For anyone who is interested with the neovim integration, please see [Use neovim in Google Chrome / Chromium through Surfingkeys - YouTube](https://youtu.be/Sff0fm-d6Vk) for how it works.

Thanks for your attention.

![image](https://user-images.githubusercontent.com/288207/134790015-cb04ac09-b33a-427a-8a53-8b89fb70627a.png)
![image](https://user-images.githubusercontent.com/288207/134790027-9e36edf6-ba7b-419b-8c10-27d4c8f25ba4.png)

**Comment by gkzhb** [comment]
Will this refactoring migrate the extension to [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/)? Considering the [`chrome.tabGroups` APIs](https://developer.chrome.com/docs/extensions/reference/tabGroups/) rely on it.

**Comment by clarkwang** [comment]
Just found my Chrome has updated Surfingkeys to 1.0. Followed the guide at https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0 but still has some issues. Please advise how to fix:

1. The func `_isDomainApplicable()` is not available in `api`.
2. For the var `settings` should I also write `const { settings } = api`?

**Comment by clarkwang** [comment]
> Just found my Chrome has updated Surfingkeys to 1.0. Followed the guide at https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0 but still has some issues. Please advise how to fix:
> 
> 1. The func `_isDomainApplicable()` is not available in `api`.

As a workaround I copied `_isDomainApplicable()` from `src/content_scripts/common/api.js` and it worked fine.

~~~
function _isDomainApplicable(domain) {
    return !domain || domain.test(document.location.href) || domain.test(window.origin);
}
~~~

> 2. For the var `settings` should I also write `const { settings } = api`?

Tried and `settings` is still a global var so don't write `const { settings } = api`.

**Comment by aspiers** [comment]
Please can you review [my suggestions for how to make this upgrade smoother](https://github.com/brookhong/Surfingkeys/issues/1578#issuecomment-1002546857)? Thanks!

**Comment by aspiers** [comment]
Additionally, the documentation in the README.md has not been updated, even though 1.0.0 is already released - I suggest that in future the release is not done until the documentation is ready, otherwise this will inevitably cause more confusion.  Most users are much more likely to read README.md than a page in the wiki which is hard to discover.

**Comment by brookhong** [comment]
@aspiers Thanks a lot for you great suggestions, all of them make sense.

Sorry for the confusion, though such chaos is expected and I had pined this issue for mitigation almost 3 months ago, it did make me nervous when it came, as so many people are impacted, not to mention those related issues here, there are also messages coming from different channels such as email, review comments on web store and personal IM.

The root cause is that I haven't designed those public APIs well from the very beginning, which exported too much internal implementations and made settings snippets uncontrollable and unexpectable, and that is why it is the second goal of this refactoring.

Some hot fix is pending review on Chrome Web store now, hopefully it will fix some missing/broken APIs and make error message explicit that it is from Surfingkeys.

**Comment by aspiers** [comment]
Thanks a lot for listening @brookhong ! And as always, thanks for this incredibly awesome extension 😁

**Comment by Stvad** [comment]
FF version does not seem to be updated? I have a shared config, and I expect if I update it'd break the things in FF that runs the older version

**Comment by Stvad** [comment]
`addVimMapKey` does not seem to be defined in API (have been using it to remap some built-in vim behavior)

**Comment by glacambre** [comment]
@brookhong I see that you're adding "true" neovim support to Surfingkeys in v1.0. Do you still need the integration code in Firenvim, or can I remove it?

Also, I see that you re-used some of my code, would you be interested in finding a way to share code in a more permanent way? This way we could share improvements, should they happen :)

**Comment by brookhong** [comment]
@glacambre Thanks for reaching out.

No, the integration code in `Firenvim` side is not necessary now, please help to remove it. The reason I'm trying to reinvent the wheel is 
* The integrated workflow with `Firenvim` is not smooth and consistent with `Surfingkeys`.
* `Firenvim` can not repeat a key when it's being held, which means user can not hold `j` to continuously go down a line.

Then I found [vv-vim/vv: Neovim client for macOS](https://github.com/vv-vim/vv) which can repeat a key when it's being held, therefore current implementation of neovim integration basically based on two projects

* [vv-vim/vv](https://github.com/vv-vim/vv) for renderring and nvim RPC event handling
* [glacambre/firenvim](https://github.com/glacambre/firenvim) for nvim server setup

To integrate above two parts within `Surfingkeys`, there are many changes in either of them, especially in [vv-vim/vv](https://github.com/vv-vim/vv).  For nvim server setup, [Surfingkeys/server.lua](https://github.com/brookhong/Surfingkeys/blob/master/src/nvim/server/server.lua) contains all the logic, it should be possible to share code in a more permanent way as most of the code are from [firenvim/lua](https://github.com/glacambre/firenvim/tree/master/lua). My changes are

* customize a `surfingkeys://` URI scheme for writing back to browser with `rpcnotify`, rather than a temporary file.
* some other minor changes for server setup
* group all modules in one for easy setup

PS: I'm not quite happy with current neovim integration in `Surfingkeys` now, the main drawback is the render from [vv-vim/vv](https://github.com/vv-vim/vv) seems to be too heavy(it uses [pixijs/pixijs](https://github.com/pixijs/pixijs) as render engine) for an in-page editor so that it has a poorer performance than  [glacambre/firenvim](https://github.com/glacambre/firenvim), also can not be expanded to Firefox and Safari, as there are some canvas APIs not available in those browsers.

**Comment by glacambre** [comment]
>Firenvim can not repeat a key when it's being held, which means user can not hold j to continuously go down a line.

Thanks for letting me know, I wasn't aware this was an issue. It seems to work fine on linux(wayland)+firefox, what OS and browser are you using? Are you using an input method?

I'll look at Surfingkeys' code in more detail and try to figure out if I could make Firenvim integrate better :).

**Comment by wll8** [comment]
## feat: the same element should try to keep the same shortcut keys

### Press F
![image](https://user-images.githubusercontent.com/28223260/166091722-5af5b5e3-b679-4005-a137-a56513d3e897.png)

### Press ESC to operate the page, add an element, then press F
![image](https://user-images.githubusercontent.com/28223260/166091735-8195a595-61bb-4772-97e4-858803b0e131.png)

The same element has different shortcut keys. This results in the need to carefully observe the new shortcut keys again to perform the same function. If we can keep the same shortcut keys as much as possible on the same element, this will be a [real shortcut key], and we can even close our eyes and know what we are doing.

### Is there any plan?
After the shortcut key is generated for the first time, use XPATH or SELECT PATH as the sign to save the shortcut key. When generating shortcut keys again, the same flag will first obtain shortcut keys from the saved list, and only regenerate those not in the list.
