### ISSUE TITLE
Surfingkeys crashes when trying to go to "Settings"

### ISSUE THREAD

**Issue by estonyec** [brookhong/Surfingkeys#1547]
Hi, when I click on "Settings" I'm redirected to this page:
chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html.

After that Surfingkeys crashes and I need to press button "Reload" in vivaldi://extensions/ to make it work again.

SurfingKeys: 0.9.74

Browser: Vivaldi 4.3.2439.44 (Stable channel) stable (64-bit)

**Comment by chroju** [comment]
This problem is not reproduced in version 5.0.2497.24 . 👍

**Comment by brookhong** [comment]
Should have been fixed in 1.0.
