### ISSUE TITLE
vim editor cursor locating problem (vim editor 光标定位问题）

### ISSUE THREAD

**Issue by zhixin-zhao** [brookhong/Surfingkeys#1548]
## Error details
![image](https://user-images.githubusercontent.com/40470855/137864056-70d9c551-0313-4a36-86a5-5bbc2ea4c5f3.png)
when I input in vim editor, the cursor location is not consistent with the actual input position. In the picture, the cursor is acctually at the end of the line, but displays at a far position.

SurfingKeys: <version 0.9.74>

Browser: <chrome94.0.4606.71><os ubuntu18.04, windows10>

**Comment by yech1990** [comment]
This is because you are not using the monospace font, you can edit you config follow this example.

https://gist.github.com/yech1990/c1f604c3678812626de6fe389eab36fc#file-surfingkeys_config-js-L370

**Comment by zhixin-zhao** [comment]
that is helpful, thank you very much!
