### ISSUE TITLE
Make "j" and "k" scroll two steps instead of one?

### ISSUE THREAD

**Issue by MartinAyla** [brookhong/Surfingkeys#155]
Thanks for a great extension!

How can I make "j" and "k" scroll two steps instead of one by default?

(Without having to press "2j" and "2k").

**Comment by flick36** [comment]
[It's in the docs...](https://github.com/brookhong/Surfingkeys#smooth-scroll) Just add `settings.scrollStepSize = 140;` to your settings

**Comment by bluekaiser** [comment]
I noticed that as well, thing is, not sure if it's just an issue i'm experiencing, but it doesn't seem like the setting is actually sticking/working. I've tried setting it with a blank settings file and just the value and have also tried with different values (140, 300, 10000), which all move the same when I invoke via j/k. I've also confirmed that the setting is being set via yj (copy current settings)

"localPath": "",
"savedAt": 1483123838774,
"scrollStepSize": 500

*format in my6 settings
settings.scrollStepSize = 500;

**Comment by brookhong** [comment]
Thanks guys.

The setting is not released in production version(currently 0.6.7), will be released soon.

**Comment by klesh** [comment]
Oh, I'm experience the same problem here... Looking forward the new release...
I think Surfingkeys is way better and powerful than vimium except scrolling experience.

**Comment by brookhong** [comment]
0.6.8 released, closed this issue.
