### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by bmccorm2** [brookhong/Surfingkeys#1562]
I hope i am doing something wrong, but my settings will not save.  Specifically, i am trying to map "one tab left" to "J".  There are no conflicting bindings.  Next time I open chrome the setting is always back to the default "E".  Sometimes mid session it will revert back to "E" - i.e., when i try to change "one tab right" to "K".  I've changed other settings and they seem to stick, but these ones never do.

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

**Comment by slavaGanzin** [comment]
I assume you're using advanced mode.

Your surfingkeys file can't be saved from 'Settings' interface. Just edit it with your desktop editor and refresh any page.
