### ISSUE TITLE
Unmap not working with domain filter

### ISSUE THREAD

**Issue by 0WN463** [brookhong/Surfingkeys#1564]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

The FAQ said to use the domain filter, but it doesn't seem to be working

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

There was a similar opened issue, but it seemed to be abandoned 2 years ago.

## Error details

I have the following snippet in my settingssetting 

`unmap('f', /.*www.youtube.com\/watch\?.*/);`

I am trying to enable the default `f` behaviour on YouTube watch subdomain.

However, starting from the main YT page (www.youtube.com), SurfingKey's F is enabled, as expect.
But when going into a video from that page, F is still enabled.

Refreshing the page disables F as desired.
But navigating back to YT home page causes F to remain disabled.

SurfingKeys: 0.8.64

Browser: Chrome 95.0.4638.69 MacOSX

URL: www.youtube.com and the `watch` links

## Context

Browsing videos while wanting to retain the default keybindings of the video player

**Comment by brookhong** [comment]
Should have been fixed in 1.0.3
