### ISSUE TITLE
Can't map or unmap <Ctrl-i>

### ISSUE THREAD

**Issue by blisstt** [brookhong/Surfingkeys#1566]
Version 0.9.74 on Firefox + Ubuntu

I want to use `<Ctrl-Space>` instead of `<Ctrl-i>` to enter vim mode.

```
map("<Ctrl-Space>", "<Ctrl-i>");
unmap("<Ctrl-i>");
```

This works as intended when I am outside of a text field. But if I am already focused inside a text field, then the behaviour is the same as before: `<Ctrl-Space>` does nothing, and `<Ctrl-i>` enters vim mode.

How can I make it so that `<Ctrl-Space>` replaces `<Ctrl-i>` everywhere?

**Comment by brookhong** [comment]
If you are already focused inside a text field, then you are in `Insert` mode, where we need `imap`, so you would probably need another line:

    imap("<Ctrl-Space>", "<Ctrl-i>");

**Comment by blisstt** [comment]
> If you are already focused inside a text field, then you are in `Insert` mode, where we need `imap`, so you would probably need another line:
> 
> ```
> imap("<Ctrl-Space>", "<Ctrl-i>");
> ```

Thank you so much @brookhong 

I tried searching the code for `iunmapAllExcept` but this function does not exist. How can I unmap all the insert mode bindings? I prefer to just use vim bindings rather than things like `<Ctrl-e>`.

If it is not possible, feel free to close this thread and I will unbind them manually.

Thank you.
