### ISSUE TITLE
getting redirected to youtube

### ISSUE THREAD

**Issue by tfriedel** [brookhong/Surfingkeys#1570]
## Error details
I open [www.nzz.ch](http://www.nzz.ch) and if surfingkeys is enabled I get redirected to https://www.youtube.com/results?search_query=
Why? Can it be fixed or is there a workaround?

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

URL:  [www.nzz.ch](http://www.nzz.ch)

**Comment by tfriedel** [comment]
I just looked at this again and tried to eliminate other factors. I create a new firefox profile and only installed surfingkeys. Yes, the problem happens then. If I disable surfingkeys it disappears. 
Is there anything I can do to help you reproduce it, like provide a log or something?

**Comment by clarkwang** [comment]
It's weird. I can repro this on macos with Firefox. The NZZ page actually has been opened for a while and then it jumps to youtube. If I disable surfingkeys (globally) the issue disappears. Then I reenable surfingkeys and refresh the NZZ page and it'll jump to youtube again.

**Comment by clarkwang** [comment]
> It's weird. I can repro this on macos with Firefox. The NZZ page actually has been opened for a while and then it jumps to youtube. If I disable surfingkeys (globally) the issue disappears. Then I reenable surfingkeys and refresh the NZZ page and it'll jump to youtube again.

Note that the opened youtube url is `https://www.youtube.com/results?search_query=`.

**Comment by clarkwang** [comment]
It can also be repro'ed with Chrome on macos, using surfingkeys v1.0.3.
