### ISSUE TITLE
Capturing full page does not open a pop-up with a screenshot

### ISSUE THREAD

**Issue by eyehol3** [brookhong/Surfingkeys#1572]
## Prelude
* Could you find answer in below documents?

no

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

yes

## Error details
Capturing page - works as expected
Capturing full page - does not open a pop-up. It worked before though.

SurfingKeys: <version>

Browser: Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64) macOS 10.15.7

URL: everywhere

**Comment by brookhong** [comment]
Should have been fixed in 1.0.3

**Comment by eyehol3** [comment]
@brookhong it is not fixed in fact

**Comment by dapanghu** [comment]
> @brookhong it is not fixed in fact

Hi My surfingKey is in 1.0.8 but still have same issue, is your surfindkey fixed?

**Comment by dapanghu** [comment]
> Should have been fixed in 1.0.3

Hi My surfingKey is in 1.0.8 but still have same issue, yg work but yG only scroll page but doesn't show that image captured. Anything I need to do to fix this issue?

**Comment by Archie-2021** [comment]
I am using Brave on Arch Linux and having this exact same problem. Surfingkey version is 1.15.0.
