### ISSUE TITLE
the function map is not word ?like  `map('z', 'gxt'); map('c', 'gxT');` it will say: Error found in settings: ReferenceError: mapkey is not defined

### ISSUE THREAD

**Issue by cn1001wang** [brookhong/Surfingkeys#1574]
just like the title;
when I add the custom setting map `map('z', 'gxt'); map('c', 'gxT');`  it will say: Error found in settings: ReferenceError: mapkey is not defined
this is my setting
```javascript
// an example to create a new mapping `ctrl-y`
mapkey('<ctrl-y>', 'Show me the money', function() {
    Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});

map('z', 'gxt');
map('c', 'gxT');
// an example to replace `T` with `gt`, click `Default mappings` to see how `T` works.
map('gt', 'T');
// an example to remove mapkey `Ctrl-i`
unmap('<ctrl-i>');

// set theme
settings.theme = `
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #24272e;
    color: #abb2bf;
}
.sk_theme tbody {
    color: #fff;
}
.sk_theme input {
    color: #d0d0d0;
}
.sk_theme .url {
    color: #61afef;
}
.sk_theme .annotation {
    color: #56b6c2;
}
.sk_theme .omnibar_highlight {
    color: #528bff;
}
.sk_theme .omnibar_timestamp {
    color: #e5c07b;
}
.sk_theme .omnibar_visitcount {
    color: #98c379;
}
.sk_theme #sk_omnibarSearchResult ul li:nth-child(odd) {
    background: #303030;
}
.sk_theme #sk_omnibarSearchResult ul li.focused {
    background: #3e4452;
}
#sk_status, #sk_find {
    font-size: 20pt;
}`;
// click `Save` button to make above settings to take effect.</ctrl-i></ctrl-y>
```

**Comment by alswl** [comment]
+1

**Comment by cn1001wang** [comment]
when I use this before update, it worked

**Comment by genmzy** [comment]
same here

**Comment by genmzy** [comment]
https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

**Comment by alswl** [comment]
I found this test case https://github.com/brookhong/Surfingkeys/blob/4619ee232680a0c88b5239e2c5f7e5cedf985b14/tests/content_scripts/content.test.js#L122

**Comment by alswl** [comment]
```
const {
    aceVimMap,
    mapkey,
    imap,
    iunmap,
    imapkey,
    getClickableElements,
    vmapkey,
    map,
    unmap,
    cmap,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME,
} = api;
```

This works for me, put the code block in the first part of configuration.

**Comment by mizzunet** [comment]
@genmzy did you able to resolve it following that?

**Comment by mizzunet** [comment]
@alswl I did, but still have `Error found in settings: ReferenceError: addSearchAliasX is not defined` error

**Comment by vuvalini** [comment]
@mizzunet `addSearchAlias` work for me. Here's [API](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md)

**Comment by mizzunet** [comment]
For me, I guess the function name has been changed from `addSearchAliasX` to `addSearchAlias`. After editing the config according to that, resolved it

**Comment by kings2u** [comment]
Thanks everyone for the suggestions. Does anyone know how to handle the old `unmapAllExcept` function? It’s still giving me the same ReferenceError...

**Comment by mizzunet** [comment]
@kings2u https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#unmapallexcept
Try adding `unmapAllExcept` to that `const`
```
const {
...
unmapAllExcept,
}  = api;

**Comment by kings2u** [comment]
Thanks for the suggestion @mizzunet. Doing this does remove the error, but then the function no longer works to unmap keys for certain sites...

**Comment by mizzunet** [comment]
>  but then the function no longer works to unmap keys for certain sites...

I'm not sure about that. I do not use that function. I hope you find a solution

**Comment by cn1001wang** [comment]
> ```
> const {
>     aceVimMap,
>     mapkey,
>     imap,
>     iunmap,
>     imapkey,
>     getClickableElements,
>     vmapkey,
>     map,
>     unmap,
>     cmap,
>     addSearchAlias,
>     removeSearchAlias,
>     tabOpenLink,
>     readText,
>     Clipboard,
>     Front,
>     Hints,
>     Visual,
>     RUNTIME,
> } = api;
> ```
> 
> This works for me, put the code block in the first part of configuration.

Thank U

**Comment by Archie-2021** [comment]
Please can someone tell me how I can set this plugin to use system clipboard? I know the command in vim, but don't know how to add it to settings here
