### ISSUE TITLE
Error found in settings: ReferenceError: mapkey is not defined

### ISSUE THREAD

**Issue by ScottYates** [brookhong/Surfingkeys#1575]
## Error details

SurfingKeys: 1.0.0
Windows 11

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

URL: all url's

## Context

Surfingkeys requested a new permission to cooperate with "external applications" (i did not capture the exact verbiage).  After accepting the permission request from chrome, surfingkeys displays a white banner with the error "Error found in settings: ReferenceError: mapkey is not defined" at the top of every page I visit.  It stays there until I hit escape.

I can't find where mapkey was ever defined in any setting.js file, so I assume it is an internal method, but either way, it is not resolving now.

**Comment by abtxu** [comment]
same problem

**Comment by MohamedIrfanAM** [comment]
same issue

**Comment by jackmac92** [comment]
same as #1574

**Comment by genmzy** [comment]
https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

**Comment by ScottYates** [comment]
> https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

This is the solution.  Include "unmap" in the list like this at the top of your script.
This should be easier to search for.  Maybe put a sticky somewhere?

Thank you @genmzy for the point in the right direction

----------------------

const {
    aceVimMap,
    mapkey,
    unmap,
    imap,
    imapkey,
    getClickableElements,
    vmapkey,
    map,
    cmap,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME
} = api;
