### ISSUE TITLE
Sudden ReferenceError 

### ISSUE THREAD

**Issue by kings2u** [brookhong/Surfingkeys#1576]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) — No
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md) — No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes
## Error details
I haven’t changed my surfing keys config in months, but now with every page I load I get the error `Error found in settings: ReferenceError: Hints is not defined`. I do have these lines in my config:
```
Hints.characters = 'asdfgwertxcvbyuiophlnm';
Hints.scrollKeys = 'jk';
```
If I comment them out, I get a similar error: `Error found in settings: ReferenceError: Visual` is not defined, as I have the following in my config too:
```
Visual.style('marks', 'background-color: #4169e1;');
Visual.style('cursor', 'background-color: #fa4646;');
```

SurfingKeys: 1.0.0

Browser: Brave 1.33.106, Windows 10

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by jackmac92** [comment]
same as #1574

**Comment by mizzunet** [comment]
Same here after updating

**Comment by mizzunet** [comment]
For me it's, `Error found in settings: ReferenceError: addSearchAliasX  is not defined.` 
My config,
```
addSearchAliasX('b', 'brave', 'https://search.brave.com/search?q=', 'o');
addSearchAliasX('a', 'amazon', 'https://www.amazon.in/s?k=', 'o');
addSearchAliasX('f', 'flipkart', 'https://www.flipkart.com/search?q=', 'o');
addSearchAliasX('i', 'invidious', 'https://invidio.xamh.de/search?q=', 'o');
addSearchAliasX('k','kickass','https://katcr.to/usearch/','o')
addSearchAliasX('z','zooqle','https://zooqle.com/search?q=','o')
addSearchAliasX('myn','https://www.myntra.com
```

**Comment by caffeebox** [comment]
+1

**Comment by mizzunet** [comment]
@caffeebox look at #1574, there's solution
