### ISSUE TITLE
Error found in settings: ReferenceError: mapkey is not defined

### ISSUE THREAD

**Issue by 0900304132** [brookhong/Surfingkeys#1579]
## Error details

update new version on 2021-12-29. notice error 'Error found in settings: ReferenceError: mapkey is not defined'

SurfingKeys: 1.0.0

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by art-romaniuk** [comment]
The same problem.
Also `Error found in settings: ReferenceError: map is not defined` error message occurs.

SurfingKeys: 1.0.0

Browser: Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)

**Comment by art-romaniuk** [comment]
This is fixed an error https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0.
@0900304132  so you can close the issue.
