### ISSUE TITLE
Keys to navigate candidates in history/bookmark search results

### ISSUE THREAD

**Issue by liangwang** [brookhong/Surfingkeys#158]
It is similar use case for both history and bookmarks. For example, if you open history search pop up by "oh", and search for "surfingkyes", a lot of candidates will be shown as follows:
![surfingkeys](https://cloud.githubusercontent.com/assets/492743/21398608/c022ff70-c75c-11e6-84cd-490c7c5766fb.PNG)

Currently, I can only navigate through candidates by:
1. use mouse
2. use cursor keys

And both require your fingers travel away from the home row. Is there a better key mapping for the navigation, e.g. "hjkl" style or something else?

Thanks!

**Comment by liangwang** [comment]
After reading the document and doing some test, I realize that it is possible to just type `TAB` to loop through all candidates. Although it works only in one-direction to pick the next candidates, it seems good enough for now. 

There are no explicit document regarding this, can we add it somewhere?

**Comment by bluekaiser** [comment]
Just a note, usually in general with any navigation that utilizes TAB you can also invoke Shift + TAB to go in the reverse direction (example you can Alt+Tab to cycle through programs and Alt+Shift+Tab to cycle in reverse). In this case you can navigate back through the omnibar via Shift+TAB as well, if that what you were stating in regards to direction/navigation :)

**Comment by brookhong** [comment]
README updated, please see https://github.com/brookhong/Surfingkeys#omnibar
