### ISSUE TITLE
`settings.blacklistPattern` is not working

### ISSUE THREAD

**Issue by LearnDifferent** [brookhong/Surfingkeys#1581]
## Error details

`settings.blacklistPattern` is not working in Surfingkeys 1.0.0.

I've read https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0 and https://github.com/brookhong/Surfingkeys/issues/63 but still can't find the solution.

SurfingKeys: 1.0.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

## Context

Here is my settings:

```
settings.blacklistPattern = /leetcode-cn\.com/i;
```

**Comment by clarkwang** [comment]
Hit the same issue after updating to 1.0.0.

**Comment by clarkwang** [comment]
Just did a `grep` search in the Git repo but found no reference to `blacklistPattern` at all.

**Comment by brookhong** [comment]
Please use `blocklistPattern`.

**Comment by clarkwang** [comment]
> Please use `blocklistPattern`.

Just tried and this works fine.

**Comment by LearnDifferent** [comment]
> Please use `blocklistPattern`.

Thanks.

**Comment by nashbridges** [comment]
Should the https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0 guide be updated?

**Comment by HaleTom** [comment]
A hint for shorter regexes:

    settings.blocklistPattern = /((calendar|mail).google|trello|duolingo|youtube|udemy).com/i
