### ISSUE TITLE
api.vmap function don't exist

### ISSUE THREAD

**Issue by knkj28** [brookhong/Surfingkeys#1582]
## Error details
SurfingKeys: 1.0.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context
api.vmap don't exist. I was able to see this by putting `console.log(Object.keys(api))` onto Surfingkey's settings.

<img width="956" alt="Screen Shot 2021-12-29 at 20 51 38" src="https://user-images.githubusercontent.com/1201928/147659450-ec075817-1bdc-4d89-9d9e-0a2c9f43edcf.png">

**Comment by knkj28** [comment]
I figured out it's because `vmap` is not exported. 
https://github.com/brookhong/Surfingkeys/blob/f9af2f8769acec5fa42755cbe1c7ece81bdeeacc/src/content_scripts/common/api.js#L677-L712

**Comment by brookhong** [comment]
The hot fix is pending review on web store.

**Comment by knkj28** [comment]
@brookhong 
Thank you. 
I confirmed that the bug is fixed on version 1.0.1.
