### ISSUE TITLE
unmapAllExcept throws ReferenceError

### ISSUE THREAD

**Issue by usommerl** [brookhong/Surfingkeys#1583]
## Error details

SurfingKeys: 1.0.0

Browser: Chrome/96.0.4664.110, Arch Linux 5.15.10-arch1-1

URL: https://github.com

## Context

The [unmapAllExcept][1] function throws a ReferenceError regardless of the provided arguments. 

#### Settings:
```
api.unmapAllExcept(['E', 'R'], /github\.com/i);
```
#### Error message:
```
Error found in settings: ReferenceError: Trie is not defined
```

[1]: https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#unmapallexcept

**Comment by MD7GIT** [comment]
same error here

**Comment by lpanebr** [comment]
same error here.

**Comment by brookhong** [comment]
The hot fix is pending review on web store.

**Comment by usommerl** [comment]
I just installed v1.0.2 and in this version, the function works as expected. Thanks a lot!

**Comment by lpanebr** [comment]
confirmed

**Comment by newduke** [comment]
I still get the error in Brave on 1.02
