### ISSUE TITLE
SyntaxError if I load setting

### ISSUE THREAD

**Issue by The33Coder** [brookhong/Surfingkeys#1584]
## Error details

SurfingKeys: 1

Browser: Chrome : 96.0.4664.110

URL: any url

## Context

After update to version 1, the message `Error found in settings: SyntaxError: Unexpected token ':'` is displaying everything.
I comment all my code and the error persist, but if I remove the path from my local settings, the message disappear.
I have the error regardless if I add the path as file:///path/to/file or /path/to/file

**Comment by brookhong** [comment]
Can not reproduce this, maybe you missed to check `Allow access to file URLs` in chrome://extensions/ for this extension
