### ISSUE TITLE
Error found in settings: ReferenceError: ... is not defined

### ISSUE THREAD

**Issue by hari12200** [brookhong/Surfingkeys#1585]
## Error details
SurfingKeys: 1.0.0
Browser: 96.0.4664.93 (Build officiel) (64 bits)
URL: any url

## Context
After update to version 1.0.0, the message  `Error found in settings: ReferenceError: unmapAllExcept is not defined` is displaying.
Hence, I reinstalled the extension and the error disappeared. But after adding the old settings lines to the default ones, the following error appeared `Error found in settings: ReferenceError: mapkey is not defined` in the same context as the previous one. I removed the adding lines but the error persists.

**Comment by saforem2** [comment]
Same issue here

**Comment by lovejavaee** [comment]
Same issue here, after upgrading to SurfingKeys: 1.0.0
`"Error found in settings: ReferenceError: mapkey is not defined"`

**Comment by saforem2** [comment]
Fixed following suggestion from 

https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

adding

```js
const {
    aceVimMap,
    mapkey,
    imap,
    imapkey,
    getClickableElements,
    vmapkey,
    map,
    unmap,
    cmap,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME
} = api;
```
to the beginning of my `~/.surfingkeys.js` did the trick

**Comment by hari12200** [comment]
The following error `Error found in settings: ReferenceError: Trie is not defined` that appears when using `unmapAllExcept` seems to have been fixed here #1586.

**Comment by lhotsekuo** [comment]
[SurfingKeys] Error found in settings: TypeError: addSearchAliasX is not defined

...add "addSearchAliasX" to api...

[SurfingKeys] Error found in settings: TypeError: addSearchAliasX is not a function

**Comment by lhotsekuo** [comment]
addSearchAliasX was replaced with addSearchAlias...
