### ISSUE TITLE
imap not working

### ISSUE THREAD

**Issue by bluekaiser** [brookhong/Surfingkeys#159]
Hello, I was trying to implement the imap example you demonstrated (imap(',,' , "<ESC>"). But no matter what combination of letters it just won't work or invoke. I've tried making it the only entry in the settings, still nothing, i've tried it while editing the settings, textinput, textarea, no difference. I've also tested it in a way to make sure the settings was getting read/updated properly but still the binding did nothing. Has anyone else been able to get the setting to work? I'd like to bind kj to ESC for my typing purposes but nothing seems to work. The other bindings seem to be working find (map, mapkey, etc)

**Comment by brookhong** [comment]
Please note that `<Esc>` is only with the first letter uppercase.

    imap(',,', "<Esc>");


`<ESC>` won't work.

**Comment by bluekaiser** [comment]
Ah sorry for the case mismatch was typing it from memory. I've checked on my machine now and I had tested it both with <ESC> and <Esc>. I've also tried changing up the quotes/spacing but nothing

I've tried the following variations, changing which quotes I use and even played around with spacing, nothing worked :( 
imap(',,',"<Esc>");
imap(',,','<Esc>');
imap(",,","<Esc>");
imap(",,",'<Esc>');

//Even an another kind of binding just to see if it had something to do with the <Esc> or ,, characters, //nothing worked
imap('kj', 'blah');

Nothing has worked (and i've confirmed that the confirm setting file has updated by changing the default "Show me the money" keybinding). I've gotten nothing, while i'm normally editing a textbox/area or via ACE editor

I also confirm that chrome is reporting that i'm using version 0.6.7

**Comment by brookhong** [comment]
With below line in your settings

    imap(',,', "<Esc>");

Have you seen help message for `,,` in usage popover triggered by `?` as below?

You need scroll to bottom of the popover to see it.

![image](https://cloud.githubusercontent.com/assets/288207/21535110/7bc07308-cdab-11e6-9024-ba4da6614d05.png)


BTW: `imap` of Surfingkeys does not work exactly as `imap` of vim.

    imap('kj', 'blah');

won't work, if `blah` is not created with `imapkey`.

Thus, if you used `iunmap('<Esc>')` before `imap(',,', "<Esc>");` then `,,` won't work.

`imap(para1, para2)` is something like that is to create alias para1 for para2.

Please see https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/content_scripts.js#L184 for more details.

**Comment by bluekaiser** [comment]
Thanks for the further troubleshooting steps, I tried the imap again and yes it appears to work, my assumption was that it was a binding for the ACE vim editor as well but alas it's only for normal textbox/textareas (I must've done the textbox testing with <ESC> and only tested ACE with <Esc>). I can confirm that imap does indeed work. Is there any way to invoke settings/mappings on the ACE Vim editor to say have imap settings?

**Comment by brookhong** [comment]
Ah. Yes, currently `imap` is just for Surfingkeys' insert mode. It is not for ACE vim editor's insert mode. Surfingkeys and ACE vim have separate mode managements. 

Nice suggestion. I'll look into the issue.

**Comment by brookhong** [comment]
New API introduced for map in ACE editor, for example:

    aceVimMap(',,', '<Esc>', 'insert');
