### ISSUE TITLE
the bookmark is not work

### ISSUE THREAD

**Issue by Tback1** [brookhong/Surfingkeys#1592]
in the 1.0 version  Chrome 93

use B to call the bookmark ominibar
but it only can show the folder with no bookmark.you need in put any character to filter it.but this only work under the current folder,if you want to switch to any other or the subdirectory it still show nothing.

![image](https://user-images.githubusercontent.com/8872546/147721193-c44939ed-da64-4f75-ba70-044719f1c517.png)
![image](https://user-images.githubusercontent.com/8872546/147721204-ea773986-fd71-49fb-a098-8b1e826d5f8c.png)

**Comment by brookhong** [comment]
Fixed in 1.0.2
