### ISSUE TITLE
searchSelectedWith do not work after upgrade to 1.0

### ISSUE THREAD

**Issue by dapanghu** [brookhong/Surfingkeys#1597]
## Prelude
* Could you find answer in below documents?
No
    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes, find nothing

## Error details

SurfingKeys: 1.0.0

Browser: Chrome Mac OS

URL: Any website

## Context
I  have the code below in Surfing key settings  to create a short cut to search in chinese. It worked before I upgrade to 1.0.0. But after I upgrade to 1.0.0.  it never works. When I input 's'  I can see the 'search in chinese' in prompt in the bottom right corner but nothing happened when I click 'c'

```
api.unmap('sc');
api.mapkey('sc', 'search in chinese', function() {
    searchSelectedWith("https://www.google.com/search?lr=lang_zh-CN&q=");
});
```

I have verifed, other mapkey in my settings still work, like below mapkey using `tabOpenLink` works, only those using searchSelectedWith do not work 

```
api.mapkey('gt','Open ticktock', function() {
    tabOpenLink("https://www.dida365.com/#q/all/tasks");
});
```

**Comment by brookhong** [comment]
`searchSelectedWith` has been published in 1.0.3

**Comment by Caelestrasz** [comment]
你的恢复了吗，我的这行设置
mapkey(';t', '用谷歌翻译选中文本', function() {searchSelectedWith("https://translate.google.com/?hl=zn#auto/zn/");});
还是没用

**Comment by LawlietNot** [comment]
> 你的恢复了吗，我的这行设置 mapkey(';t', '用谷歌翻译选中文本', function() {searchSelectedWith("[https://translate.google.com/?hl=zn#auto/zn/");}](https://translate.google.com/?hl=zn#auto/zn/%22);%7D)); 还是没用

打开控制台看下有没有报错

**Comment by Caelestrasz** [comment]
> 歌翻译选中文本

VM69:31 Uncaught ReferenceError: searchSelectedWith is not defined
    at eval (eval at <anonymous> (content.js:3:121026), <anonymous>:31:39)
    at J.handleMapKey (content.js:3:55681)
    at content.js:3:56831
    at te (content.js:3:52597)
    at keydown (content.js:3:52767)

**Comment by dapanghu** [comment]
> 你的恢复了吗，我的这行设置 mapkey(';t', '用谷歌翻译选中文本', function() {searchSelectedWith("[https://translate.google.com/?hl=zn#auto/zn/");}](https://translate.google.com/?hl=zn#auto/zn/%22);%7D)); 还是没用

我一开始即使是升级到了1.03 还是不行，最后我把surfingkey卸载然后重装了之后就可以了（记得卸载前复制你的设定）

**Comment by dapanghu** [comment]
> 

抱歉我刚刚又研究了下，好像不是卸载重装修复的，是要把searchSelectedWith 改成api.searchSelectedWith 才行， 比如我的现在是这样的

api.mapkey('sc', 'search in chinese', function() {
    api.searchSelectedWith("https://www.google.com/search?lr=lang_zh-CN&q=");
});

**Comment by ncaq** [comment]
I use Firefox 96.0.3 and Surfingkeys 1.0.3.
I exec,

~~~js
searchSelectedWith("https://www.google.com/search?q=", false, false, "");
~~~

and I get error message.

~~~
 Error: Please use $(ref:runtime.getURL).
~~~
