### ISSUE TITLE
Keybinding for scrolling down a full page

### ISSUE THREAD

**Issue by bkudria** [brookhong/Surfingkeys#1598]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

Nope

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yep

## Error details

SurfingKeys: 1.0.2

Browser: Chrome 96.0.4664.110, macOS 12.1

URL: any

## Context

Prior to 1.0, I had: 

`mapkey('D', 'Scroll page down', () => Normal.scroll('fullPageDown'));`

to scroll down one full page. With 1.0, this API was removed. Is there a way to replicate this behavior?

I've tried:

`api.map('D', '<Space>', /./, 'Scroll page down');`
`api.map('D', '<PageDown>', /./, 'Scroll page down');`
`api.map('D', '2d', /./, 'Scroll page down');`

Is there a way to do this, or has this functionality been removed from SurfingKeys?

**Comment by joshuali925** [comment]
I have a similar need for using `Normal` to scroll top/bottom, for now I have to use `window.scrollTo` instead (you can also probably use `window.scrollBy(0, 700)` to replace `Normal.scroll('fullPageDown')`). But this won't work when switching frames/scroll targets, really hope Normal or at least scroll api is still supported.

**Comment by petobens** [comment]
@brookhong I'm also experiencing the same issue. any chance of addressing it?

**Comment by laphylee** [comment]
I use this instead:  `mapkey('D', 'Scroll a page down', () => {window.scrollTo(0, window.pageYOffset+window.innerHeight*0.9)});`

**Comment by brookhong** [comment]
Since 1.0.3, 
`U` Scroll full page up
`P` Scroll full page down

Please use `api.map` to map to your favorite key.
