### ISSUE TITLE
Missing API for Hints.scrollKeys

### ISSUE THREAD

**Issue by gvteja** [brookhong/Surfingkeys#1599]
Before the refactor, I was able to use the standard navigation keys such as j and k as Hint characters by setting `Hints.scrollKeys` to null. It looks like with the refactor, there is no equivalent way to override `scrollKeys` with nothing and as a result, I'm unable to use keys such as j and k as hint characters due to [this error](https://github.com/brookhong/Surfingkeys/blob/5b302f55da887c0f603c18acda441f139e689a71/src/content_scripts/common/hints.js#L88).

**Comment by arizzubair** [comment]
Migrate your settings : https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

**Comment by clarkwang** [comment]
See Brook's [comment](https://github.com/brookhong/Surfingkeys/issues/1595#issuecomment-1003309405) in another thread:

> And you need not set `scrollKeys` any more.

Sounds like `scrollKeys` is not customizable any more. I've removed `hjkl` from my hint chars.

**Comment by gvteja** [comment]
> Migrate your settings
I did, but unfortunately, it looks like the `scrollKeys` is not customizable any more. 

> I've removed hjkl from my hint chars.
I've done the same for now. Would prefer to keep using them like before, but is not a big blocker for me. If @brookhong confirms that there is no plan to make this customizable, then I'm good with closing this issue. Thank you brook for all the work you've put into this extension.

**Comment by brookhong** [comment]
Surfingkeys now can figure out by itself which default keys are bound to scroll in Hints mode, so there is no need of such setting. And scrolling in Hints mode now is enabled by default, if there were more requests to disable scrolling in Hints mode, we will probably add another API to help to turn it off.

**Comment by gvteja** [comment]
> Surfingkeys now can figure out by itself which default keys are bound to scroll in Hints mode

Is there a way to configure that or is that hardcoded list of keys? 
My desired workflow: I would like to keep scrolling in Hint mode, but I would like to choose which keys actually scroll: would use number keys for scrolling and j and k as regular hint characters. I don't typically scroll while in hint mode, so using numbers to access scroll for those time when I might need to would be helpful.

**Comment by brookhong** [comment]
If you want `j` / `k` as hint characters, you need `unmap` them, however it will also lead `j` / `k` unable to scroll in Normal mode.

**Comment by gvteja** [comment]
Got it. For my workflow, not being able to use j/k like before is a regression. But it's not a blocker. So am going to close this issue.
