### ISSUE TITLE
Support for Edge

### ISSUE THREAD

**Issue by zhouyangnk** [brookhong/Surfingkeys#160]
Could you guys please consider adding support for MS Edge? All the blogs I see say that most Chrome extensions could be changed support Edge with minimal 1 line changes by using Microsoft Edge Extension Toolkit.

**Comment by naefl** [comment]
bump, would be amazing. Especially considering that w/ new Windows 10 insider builds of RS5, the adoption rate of Edge vs. other browsers will uptick heavily ("Sets" feature of RS5)

**Comment by brookhong** [comment]
There is a blocking issue for Edge, https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11320212/

Fortunately, looks like it will be fixed soon.

**Comment by naefl** [comment]
@brookhong, according to the comments

> Nolan L. May 4, 2018 Microsoft Edge Team 

> This is fixed in Windows 1803, aka the April 2018 update

This is already deployed on over 60% of all windows 10 PCs, so a big userbase for you to adopt! ;)

**Comment by brookhong** [comment]
I upgraded Edge to latest, and tried to make SurfingKeys support Edge.

Though now some basic functions like following links / scrolling pages work well, but there are still some gaps.

# missing Selection.modify for Visual mode
> https://developer.mozilla.org/en-US/docs/Web/API/Selection_API

# missing Paste of execCommand for Clipboard
> https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

# APIs lack for Omnibar
* chrome.topSites
* chrome.bookmarks.getRecent

# some differences
regex.flags

**Comment by zzxqd** [comment]
能否给出自行构建edge浏览器扩展的大致步骤呢，虽然这个浏览器后续不会更新了，但有的时候还是更倾向于用edge
