### ISSUE TITLE
还是报[SurfingKeys] Error found in settings: ReferenceError: unmapAllExcept is not defined

### ISSUE THREAD

**Issue by Code-from-Internet** [brookhong/Surfingkeys#1600]
根据最近的几个 isssue 的对话，在配置文件最前面加入了以下代码：
```
const {
    aceVimMap,
    mapkey,
    imap,
    imapkey,
    getClickableElements,
    vmapkey,
    map,
    unmap,
    vunmap,
    cmap,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME
} = api;'
```
并将`Hints.characters = 'asdgwertcvuionm'; ` 改成 `Hints.characters = ("asdgwertcvuionm");`。

还是报错`[SurfingKeys] Error found in settings: ReferenceError: unmapAllExcept is not defined`。

还有，以下配置不work：
```
mapkey(',a', '#120Open Acfun', function () {
    tabOpenLink("https://www.acfun.cn/u/4075269.aspx");
});
```
原因是什么？

**Comment by Code-from-Internet** [comment]
建议作者写个脚本，能将旧版本的配置转换成新版的配置。

**Comment by clarkwang** [comment]
> 并将`Hints.characters = 'asdgwertcvuionm'; ` 改成 `Hints.characters = ("asdgwertcvuionm");`。

Should be `Hints.setCharacters("asdgwertcvuionm")`.

> 还是报错`[SurfingKeys] Error found in settings: ReferenceError: unmapAllExcept is not defined`。

`unmapAllExcept` should also be included in `const { ... } = api;`.

**Comment by clarkwang** [comment]
> 还有，以下配置不work：
> 
> ```
> mapkey(',a', '#120Open Acfun', function () {
>     tabOpenLink("https://www.acfun.cn/u/4075269.aspx");
> });
> ```
> 
> 原因是什么？

Include `tabOpenLink` in `const { ... } = api;` or use `api.tabOpenLink`.

**Comment by fabiomcosta** [comment]
Just wanted to point out that there are some places that are not talking about the fact that these functions are not globally available from the settings anymore, like https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-surfingkeys-only-on-current-site and even my settings had some default code on it that was breaking.
Using the functions from the `api` object works as expected.
