### ISSUE TITLE
api.map("g1", "1T") does not work?

### ISSUE THREAD

**Issue by clarkwang** [brookhong/Surfingkeys#1603]
I want to use `g1` to select Tab#1, `g2` for Tab#2 and so on. I tried `api.map("g1", "1T")` but it did not work. Any other way to do this?

**Comment by brookhong** [comment]
Please see #537 #413 for why.

**Comment by clarkwang** [comment]
Just tried using the `focusTabByIndex()` like this:

    api.mapkey("g2", "go to tab 2", function() {
        api.RUNTIME('focusTabByIndex', { repeats: 2 });
    });

This kind of works but it always goes to Tab #1. Seems like the `repeats` param cannot be passed this way. How can I fix this?

**Comment by megalithic** [comment]
you ever get this working @clarkwang ?? i'm looking to do similar `Ctrl-2` to map to `2T`

**Comment by clarkwang** [comment]
> you ever get this working @clarkwang ?? i'm looking to do similar `Ctrl-2` to map to `2T`

You can use `Normal.feedkeys()` like this:

~~~
api.mapkey("g1", "go to tab #1", function() {
    api.Normal.feedkeys("1T");
})
~~~
