### ISSUE TITLE
.pdf viewer gone

### ISSUE THREAD

**Issue by RedBotz** [brookhong/Surfingkeys#1604]
## Error details

I really appreciated the surfingkeys .pdf viewer - is there any way to get the .pdf viewer back?  I no longer seem to have access to it.

All the best,

R

SurfingKeys: 1.0.1

Browser: Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by zqni** [comment]
I might meet with a similar issue. The pdf viewer doesn't work properly on 1.0.1 while my Chrome is 97.0.4692.71. All the short keys don't work anymore in a pdf viewer now.
