### ISSUE TITLE
How to find the code of Surfingkeys mappings?

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#1605]
scroll to top and bottom, Surfingkeys worked well.
I want to get the code.
I found `gg` is in `content.js`, `pages\ace.js`, `pages\frontend.js`,
code in `frontend.js` is
```
t.mappings.add("gg",{annotation:"Scroll to the top of the page",feature_group:2,repeatIgnore:!0,code:t.scroll.bind(t,"top")})
```
I don't know what is `t`, please help me!

btw, I tried `window.scrollTo(0,0)`, but it's not worked in some pages.
for example: [https://www.apipost.cn](https://www.apipost.cn)

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/5b302f55da887c0f603c18acda441f139e689a71/src/content_scripts/common/default.js#L485
