### ISSUE TITLE
自编译Chromium浏览器无法登录Google帐户

### ISSUE THREAD

**Issue by SlippyJimmy** [brookhong/Surfingkeys#1608]
我现在正在使用您自编译的chromium浏览器，系统是MacOS10.15.7。其他都挺完美，但是无法登录google帐号同步书签（无论是从设置中还是浏览器右上角用户），能修复一下吗？

**Comment by flowerhood** [comment]
我连续试了2天，反复安装卸载，都是无法无法登陆google账户，我以为是我电脑的问题，重装了系统也是这样，我的系统是win10 64,我以为是chrome新版本本身的问题，直接下载官方的97版本在线安装，直接闪速进入google账户并能实现同步，但作者的这个自编译版本就是不能保存账号信息，我以为是缓存的问题，开启了所有缓存，但仍然记不住google账户信息，每次打开都跟新的一样，要手动下载安装原来的所有插件，只要退出，所有插件信息全部丢失，又要重新下载安装，折腾了2天，看来只能放弃了

**Comment by brookhong** [comment]
这是因为Google不需要所有非Google Chrome的Chromium浏览器使用他们的API了，可以看https://askubuntu.com/questions/1322559/sync-chromium-with-a-google-account-does-not-work-any-more-solutions

这个目前还没有解决方案。

**Comment by okwellok** [comment]
如果是linux的话可以参考[这里](https://nyac.at/posts/google-sync-in-chromium)可以登录同步.

**Comment by okwellok** [comment]
@brookhong 大佬你好,请问firefox能像你自编译的chromium一样在默认禁用的页面,使用surfingkeys吗?

**Comment by okwellok** [comment]
@flowerhood 我刚刚在windows11下面测试能够成功登录并同步。先参考[这里](https://nyac.at/posts/google-sync-in-chromium)申请 Google API key，再用管理员命令运行：
```
setx GOOGLE_API_KEY “API 密钥的「键」”
setx GOOGLE_DEFAULT_CLIENT_ID “客户端 ID”
setx GOOGLE_DEFAULT_CLIENT_SECRET “客户端密钥”

```
然后就可以了。
@SlippyJimmy  Mac的话，应该有类似linux环境变量的设置，参考linux的去配置或许可以？

**Comment by flowerhood** [comment]
> @flowerhood 我刚刚在windows11下面测试能够成功登录并同步。先参考[这里](https://nyac.at/posts/google-sync-in-chromium)申请 Google API key，再用管理员命令运行：
> 
> ```
> setx GOOGLE_API_KEY “API 密钥的「键」”
> setx GOOGLE_DEFAULT_CLIENT_ID “客户端 ID”
> setx GOOGLE_DEFAULT_CLIENT_SECRET “客户端密钥”
> ```
> 
> 然后就可以了。 @SlippyJimmy Mac的话，应该有类似linux环境变量的设置，参考linux的去配置或许可以？

sucess,thank you!

**Comment by akang943578** [comment]
> > @flowerhood 我刚刚在windows11下面测试能够成功登录并同步。先参考[这里](https://nyac.at/posts/google-sync-in-chromium)申请 Google API key，再用管理员命令运行：
> > ```
> > setx GOOGLE_API_KEY “API 密钥的「键」”
> > setx GOOGLE_DEFAULT_CLIENT_ID “客户端 ID”
> > setx GOOGLE_DEFAULT_CLIENT_SECRET “客户端密钥”
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后就可以了。 @SlippyJimmy Mac的话，应该有类似linux环境变量的设置，参考linux的去配置或许可以？
> 
> sucess,thank you!

现在好像不行了

**Comment by yongyuandexiaoxia** [comment]
奇怪, 我的就没事, 可以一直使用啊, 不过我在谷歌search中登录了我的账号, 但是浏览器插件什么的都是照常的, 没有出现退出后插件失效的情况
