### ISSUE TITLE
api.Hints.characters notwork

### ISSUE THREAD

**Issue by Tback1** [brookhong/Surfingkeys#1610]
```
api.Hints.characters = ("'wdiqelfjvkrunoa,.xc");
```

try this avoid use “S” , but still had S on it

**Comment by Tback1** [comment]
![Clip_20220105_233824](https://user-images.githubusercontent.com/8872546/148245731-1e64e64e-ff13-4143-832d-2cebd1aa08a8.png)

**Comment by iSeeU816** [comment]
Hello,

Check [API.md](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md) document to know what to use regarding the new v1.x of Surfingkeys.

For you situation, check this heading:
[Hints.setCharacters](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#hintssetcharacters).

(I didn't test this but it should work.)

Hope this helps.

**Comment by Tback1** [comment]
> api.Hints.characters

it must be api.Hints.characters or will pop error
[SurfingKeys] Error found in settings: ReferenceError: Hints is not defined

**Comment by mathstuf** [comment]
> it must be api.Hints.characters or will pop error

The docs need updated for this.
