### ISSUE TITLE
Omnibar history (fixed in v1.0.5)/bookmark (NOT fixed) search doesn't like spaces anymore (v1.x)

### ISSUE THREAD

**Issue by iSeeU816** [brookhong/Surfingkeys#1612]
## Update 2022-03-18; `b` issue

Surfingkeys 1.0.5.

The issue for `oh`, `t` and `T` was fixed in v1.0.5; but as @nbaudis
[mentioned below](https://github.com/brookhong/Surfingkeys/issues/1612#issuecomment-1071629825) that the `b` (Open a bookmark) command still suffer from
the same issue described in the original report down below.

Searching in Omnibar, specially for history and bookmarks, is very
important as it's the front-end of a user data; I hope, again as it
fixed for other commands, to be fixed for the `b` command. Thank you!

----------------

## Original report (2022-01-07); fixed in v1.0.5

Title (was): Omnibar history search doesn't like spaces anymore (v1.x)

Hello,

Surfingkeys 1.0.2.

Suppose you visited these links:

``` text
https://github.com/foo/bar
https://www.youtube.com/user/bar
https://gitlab.com/foo/bar
https://github.com/baz/qux
```

Invoking `oh` (Open URL from history) command then typing
`gith<space>bar`:

- Prior to v1.x:
  - This will show `https://github.com/foo/bar` as the result of the
    search.
- v1.x:
  - Nothing will shows up the moment you hit the space key as mentioned
    in the search term above.

The idea of using "gith" is to filter all history first then applying
another filter to the desired web page. This way I don't get results
from GitLab if I wanted `https://github.com/foo/bar` page. Searching
with the term "bar" alone will show a lot of false positive results, but
typing a prefix, part of website's name, `<space>` then a term is much
better to get few hits. Another example is to type `yo<space>bar` to get
history results for "bar" in YouTube website.

I noticed that `t` (Open a URL) and `T` (Choose a tab) commands are
working fine with the search term I mentioned, so the issue is only in
`oh` Omnibar.

I hope you can fix this as I'm relaying on this type of search and
filter a lot. Thank you!

**Comment by sloxy** [comment]
Did this auto-close because it was mentioned in ? I too have this valid issue.

**Comment by iSeeU816** [comment]
@sloxy You're correct and I think this is since v1.0.3.

I'm currently using v0.9.74 that I built it as I explained in #1625.
Saying that, I hope this issue get fixed so I can use the latest version as always.

**Comment by cibinmathew** [comment]
@brookhong would you be able to direct to the relevant code or any pointers on the issue. I can try to work on a pr for this.

**Comment by hytor-yang** [comment]
Seems that v1.0.5 works well?

**Comment by iSeeU816** [comment]
@hytor-yang

I can confirm that. I have tested v1.0.5 and a version based on latest commit 40a37ec4d2574408f3df82f73ebd0121931ba52c, and both worked nicely for the following commands:

- `oh` (Open URL from history).
- `t` (Open URL).
- `T` (Choose a tab).

The tests were done on a fresh browser profile and no configurations were used for Surfingkeys.

Thank you for letting me know and for whom fixed the issue.

I will close this and will be happy to re-open it if anyone have something not working regarding this issue.

**Comment by nbaudis** [comment]
So happy this got fixed for the `oh` command! The `b` (Open a bookmark) command still behaves like you described in the issue, though: no results when typing a space. iirc before v1.x `b` was able to filter by multiple search terms.

**Comment by hytor-yang** [comment]
@iSeeU816 
Glad to hear that. Thanks for the [workaround](#issuecomment-1021349587) which got me through the days before the fix. 😄

**Comment by iSeeU816** [comment]
@nbaudis

I have updated the issue's content and title. Thank you.

@hytor-yang

You're welcome!

I might look again at old version that has `b` working fine; but not
sure when.

**Comment by iSeeU816** [comment]
@nbaudis 

I discovered that using `t` (Open URL) command can search
bookmarks without issues in re. to what mention in OP.

Still, the list is clutter with other type of URLs.

My test was on latest 40a37ec that I built from upstream.

Hope this helps.
