### ISSUE TITLE
Search function broken when help window is open

### ISSUE THREAD

**Issue by DrakeXiang** [brookhong/Surfingkeys#1614]
## Error details

SurfingKeys: 1.0.2

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.43

URL: <The_URL_Where_You_Find_The_Issue>

## Context

If the help window is open and when I try search with `/`, I can only input one character to search

**Comment by stevenvynu** [comment]
HI,

Would like report about bigbang core wallet apps, it can be download and install but most of people having sync showing 0.00% only.

i think the apps got bug.

**Comment by DrakeXiang** [comment]
> HI,
> 
> Would like report about bigbang core wallet apps, it can be download and install but most of people having sync showing 0.00% only.
> 
> i think the apps got bug.

Why not open issue in  related repo 😂 
I've left that company at April last year because it couldn't pay salary, the company is not functioning at least for several months AFAIK, I'd suggest you reach out  to customer service or someone in charge first

**Comment by brookhong** [comment]
Should have been fixed in 1.0.3
