### ISSUE TITLE
Let firefox use surfingkeys on any page .Just like Brook Build of Chromium? 

### ISSUE THREAD

**Issue by okwellok** [brookhong/Surfingkeys#1616]
Has anyone patched firefox to release the restrictions on surfingkeys on the default page ?
or other way?

Thanks.
感谢.

**Comment by brookhong** [comment]
Not an issue that `Surfingkeys` can handle, and I'm not big fan of Firefox, so there would be no chance for me to hack Firefox to allowlist Surfingkeys. It would be better to discuss this in `Discussions`.
