### ISSUE TITLE
Replacement for `Normal.scroll()`?

### ISSUE THREAD

**Issue by joshuali925** [brookhong/Surfingkeys#1617]
version 1.0.3

Hi, prior to version 1.0.0 I was able to use this code to save previous scroll position before `gg` or `G`, and jump back using <code>``</code>. 

```js
var scrollX, scrollY;
mapkey('gg', 'Go to top', function() {
    var tempX = document.scrollingElement.scrollLeft;
    var tempY = document.scrollingElement.scrollTop;
    Normal.scroll('top');
    if (tempX !== document.scrollingElement.scrollLeft || tempY !== document.scrollingElement.scrollTop) {
        scrollX = tempX;
        scrollY = tempY;
    }
});
mapkey('G', 'Go to bottom', function() {
    var tempX = document.scrollingElement.scrollLeft;
    var tempY = document.scrollingElement.scrollTop;
    Normal.scroll('bottom');
    if (tempX !== document.scrollingElement.scrollLeft || tempY !== document.scrollingElement.scrollTop) {
        scrollX = tempX;
        scrollY = tempY;
    }
});
mapkey('``', 'Go to previous position', function() {
    var tempX = document.scrollingElement.scrollLeft;
    var tempY = document.scrollingElement.scrollTop;
    if (scrollX !== undefined && scrollY !== undefined)
        window.scrollTo(scrollX, scrollY);
    scrollX = tempX;
    scrollY = tempY;
});
```

This is useful as sometimes I want to peek the top/bottom of the page then come back to where I was before. Did a quick search and seems others also find this helpful (#1110 #1379), and I believe this is supported by vimium. Using `window.scrollTo` to replace `Normal.scroll` will not consider scroll targets and sometimes don't work. Is it still possible after version 1.0.0 (maybe some way to trigger original `gg` and `G`, or expose the API)? Thanks.

**Comment by cibinmathew** [comment]
+1

**Comment by joshuali925** [comment]
thanks, `Normal.scroll` is back (35558a2fc3a3a3f06c2979411c6c0ef2d61abeb5)
