### ISSUE TITLE
disabling/enabling Surfingkeys should give more obvious visual feedback

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#162]
Since the disable/enable setting is persistent per domain, it can be tricky to remember whether it's on or off in any given tab.  So when I press `Alt-s` it would be helpful if there was some visual feedback showing whether it was just enabled or disabled.  I notice that the colour of the extension icon changes but this is quite subtle, so something a bit more obvious would be nice.

**Comment by brookhong** [comment]
Thanks for the suggestion.
