### ISSUE TITLE
How to build the Chrome extension from source code?

### ISSUE THREAD

**Issue by clarkwang** [brookhong/Surfingkeys#1625]
Can we add some build instructions to the doc/wiki?

**Comment by iSeeU816** [comment]
Hello,

You can find the instructions in [CONTRIBUTING.md](https://github.com/brookhong/Surfingkeys/blob/master/CONTRIBUTING.md) file.

Actually, a few hours ago I built from source (I checked out https://github.com/brookhong/Surfingkeys/commit/db96cd5a41ba87bb328ad4add8b84695928288ca commit to get v0.9.74 as I'm missing out the functionality of `oh` command I described in https://github.com/brookhong/Surfingkeys/issues/1612).

--------

## Build from source

For reference, here are the commands that I executed on Ubuntu 20.04:

1. `sudo apt update`. To update package archives.
2. `sudo apt install -y git npm`.
3. `git clone https://github.com/brookhong/Surfingkeys`.
4. `cd Surfingkeys`.
5. `git checkout db96cd5a41ba87bb328ad4add8b84695928288ca`.
    - This will checkout the commit just before v1.x.  This is for version 0.9.74.
    - **NOTE:** Ignore this step if you want to build based on the latest commit.
      - As of writing this, the latest commit is https://github.com/brookhong/Surfingkeys/commit/767200b650f8589a830ecd26937e1c165c6e3993.
6. `npm install`.
7. `npm run build`.
    - This will build an extension in "dist/" directory tree.
8. Launch the browser you use and go to Extension page "chrome://extensions".
9. **IMPORTANT:** Disable Surfingkeys extension that you installed from Google Chrome Store.
10. Enable "Developer mode" then click "Load unpacked" and navigate to this path:
    - Prior to v1.x: "</path/to/where/you/cloned/Surfingkeys>/dist/Chrome-extension/".
    - v1.x: "</path/to/where/you/cloned/Surfingkeys>/dist/production/chrome/".
11. Restart the browser and enjoy the latest/old version you are after.

## Update the extension manually

The steps for build mentioned above won't get the extension update automatically,
so you need to follow these steps to do so:

1. `cd </path/to/where/you/cloned/Surfingkeys/>`.
2. `git pull origin`.
3. Follow steps from 6 to 11 from "Build from source" section above.

**DISCLAIMER:** Please use this for test purposes and do it on your own risk.

**Comment by clarkwang** [comment]
Thanks! I did not know it's in the CONTRIBUTING file.
