### ISSUE TITLE
disabling is not visible in settings

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#163]
https://github.com/brookhong/Surfingkeys/#hotkey-to-toggle-surfingkeys says:

> When Surfingkeys is turned off on some site by Alt-s, the status will be persisted in settings

But if I turn it off for a domain and then go to another tab and type `se` to open the settings, no such blacklist entry is visible in the settings.

**Comment by brookhong** [comment]
Data settings are not always presented in snippets.

You could use `yj` to dump all settings into clipboard, then paste it in your text editor to check out.

**Comment by aspiers** [comment]
Oh OK, I see thanks.  Is it possible to clarify that in the README somehow?  Thanks a lot!

**Comment by brookhong** [comment]
Statement added in README.
