### ISSUE TITLE
请问如何同步配置?

### ISSUE THREAD

**Issue by godefy** [brookhong/Surfingkeys#1633]
我在多台电脑下使用,应该如何同步配置?

**Comment by clarkwang** [comment]
For Chrome you can just enable Sync and Surfingkeys' settings will be saved to your Google account and be sync'ed to other computers automatically. I guess also works with Firefox Sync.

**Comment by godefy** [comment]
> For Chrome you can just enable Sync and Surfingkeys' settings will be saved to your Google account and be sync'ed to other computers automatically. I guess it also works with Firefox Sync.

thank you~

**Comment by yanzhang0219** [comment]
So the sync feature is not available for Safari on macOS and iOS, right? Will it be supported in the future? Thanks a lot.
