### ISSUE TITLE
Error: cmap function is not defined.

### ISSUE THREAD

**Issue by graydonguan** [brookhong/Surfingkeys#1639]
## Error details

SurfingKeys: 1.03

Browser: chrome 97.0.4692.99

URL: <The_URL_Where_You_Find_The_Issue>

## Context
I have write a setting file in my computer. And it is loaded in the setting site, but when I saved the settings and access the web site, there is a error come out as follow:
![image](https://user-images.githubusercontent.com/25134765/151125375-edbda43b-ccd7-4091-9dee-a57a1b73d456.png)

I want to know why the explorer said the "cmap"function is not defined. And how I can fix the problem.
**Please replace this with a description of how you were using SurfingKeys.**

**Comment by sigfriedCub1990** [comment]
> See https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

Excellent, thanks for this, I have many custom mapping and after updating I'm seeing lots of `mapkey` is not defined.

**Comment by graydonguan** [comment]
> See https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

Excellent, thanks for this!
