### ISSUE TITLE
Enter in visual mode doesn't do anything

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#164]
If I go to https://github.com/brookhong/Surfingkeys and type `/hotkey` then it jumps to the "Hotkey to toggle Surfingkeys" entry in the README's Table of Contents.  Pressing `Enter` then switches to visual (Caret) mode.  The help text displayed when pressing `?` says that pressing `Enter` in visual mode should "Click on node under cursor", but if I now press `Enter` again nothing happens.  The correct behaviour would be the same as clicking on the "Hotkey to toggle Surfingkeys" hyperlink, i.e. jumping to that section of the README.

**Comment by brookhong** [comment]
Thanks for reporting the issue.

**Comment by aspiers** [comment]
Tested and it works perfectly now, thanks a lot!
