### ISSUE TITLE
Allow loading settings from URL in Firefox

### ISSUE THREAD

**Issue by b0o** [brookhong/Surfingkeys#1647]
For some reason, the 'load settings from URL' input field is [hidden](https://github.com/brookhong/Surfingkeys/blame/3d1de8cab8584209cc6fec3ed7025e8ebab476d8/src/content_scripts/options.js#L79) on Firefox. If I inspect element and remove `display:none` from `#localPathForSettings`, my settings load perfectly fine from my URL. Can we re-enable this in Firefox? I'd be happy to send a PR.

**Comment by brookhong** [comment]
Thanks, fixed [here](https://github.com/brookhong/Surfingkeys/commit/0a608e3de795bb53c6b866d308ef320aecdcb4f4#diff-fd08845baee3a9005ed80664b7bab599632eaa5e6b7f089bb8272f3f129db44cL80), will be released soon.

**Comment by b0o** [comment]
Awesome, thank you!
