### ISSUE TITLE
Toggle SurfingKeys on current site no longer works

### ISSUE THREAD

**Issue by m-zheng** [brookhong/Surfingkeys#1649]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: <version> 1.0.3

Browser: <version><os version> Firefox 96.0

OS: Ubuntu 20.04

URL:  any website

## Context
I can no longer press `Alt-s` to disable Surfingkeys on any website. Somehow pressing `Alt-s` is the same as pressing `s`.

**Comment by clarkwang** [comment]
Could you try 1.0.4?

**Comment by m-zheng** [comment]
It works. Thanks for your help.
