### ISSUE TITLE
global <Ctrl-somekey> map as <ESC> can't work on Safari

### ISSUE THREAD

**Issue by milanglacier** [brookhong/Surfingkeys#1651]
Hi! 
I'm using surfingkeys on both Safari(I paid it via App Store) and Firefox.

I'm currently on macOS 12.0.1, macbook Air M1, Safari 15.1, firefox 96.0.3.

In firefox, the following maps work globally:

`api.map("<Ctrl-C>", "<Esc>")`,

which does not apply to Safari. Specifically, when I am on a text edit area using safari, I can't use `<C-c>` to quit the edit area, while I can do it in Firefox. I find that any keybindings like `<Ctrl-somekey>` can't emulate `<ESC>` in Safari.

**Comment by brookhong** [comment]
Please use `api.imap` since Surfingkeys is in `insert` mode when you are on a text edit area.

**Comment by milanglacier** [comment]
> Please use `api.imap` since Surfingkeys is in `insert` mode when you are on a text edit area.

This works!
Still have no idea why map does not work globally, as what it is in firefox.
