### ISSUE TITLE
PassThrough mode shortcut does not work

### ISSUE THREAD

**Issue by kinosang** [brookhong/Surfingkeys#1652]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes, maybe related to #1649.

## Error details

SurfingKeys: 1.0.3

Browser: Firefox 96.0.3 Windows 11 22509.1011

URL: X

## Context

With / Without any IME,

`Alt-i` does not work, `p` for ephemeral works.

When an `input` on screen, `Alt-i` leads to input mode instead of pass through.

**Comment by clarkwang** [comment]
Could you try 1.0.4?

**Comment by kinosang** [comment]
@clarkwang with 1.0.4, `Alt-i` still not work.

**Comment by clarkwang** [comment]
1.0.4 works fine for me with Firefox on macOS.
