### ISSUE TITLE
Error found in settings: ReferenceError: map is not defined

### ISSUE THREAD

**Issue by janacm** [brookhong/Surfingkeys#1653]
I am receiving this error: 

![image](https://user-images.githubusercontent.com/2055312/152648268-784e93c0-968d-4775-bcf7-f9bc669f93f5.png)

My settings:

![image](https://user-images.githubusercontent.com/2055312/152648294-9ef61f5a-8066-4854-b89c-cecdfb44d266.png)

Not sure why I'm getting this error.

**Comment by hkienle** [comment]
Just to confirm, this error also popped up for me on Firefox after I upgraded  to 1.0.4.
(I don't have user-defined settings, I think.)

**Comment by clarkwang** [comment]
See https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

**Comment by hkienle** [comment]
That did it for me, thanks!!
