### ISSUE TITLE
Hints have become unreadable (no contrast between background/foreground colors) when using Dark Reader

### ISSUE THREAD

**Issue by ackalker** [brookhong/Surfingkeys#1654]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes, I don't think it is related to #1343.

## Error details

When using Surfingkeys in combination with Dark Reader in dark mode, hints have become unreadable (I'm suspecting this occurred after an update to Dark Reader). 

Current look with Dark Reader enabled for this site:
![2022-02-06-125014_1920x1080_scrot](https://user-images.githubusercontent.com/429567/152687523-259cb33a-f33f-477d-a943-647a10fd93ea.png)

Current look with Dark Reader disabled for this site::
![2022-02-06-125052_1920x1080_scrot](https://user-images.githubusercontent.com/429567/152687540-a9bb1a12-a814-4a7f-8b4d-5eeaa526e14e.png)

SurfingKeys: 1.0.3

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

I first noticed the problem in the middle of a browsing session with Chromium. One moment the hints were readable, the next (after opening a new browser window) they weren't.
I next tried with Chromium with a fresh temporary user data dir (profile), and installed just Surfingkeys and Dark Reader extensions, in this sequence.
The odd thing is right after installing Dark Reader, Surfingkeys hints are still visible in all existing tabs and windows, but as soon as I open a new tab and browse to some site in it, hints become unreadable.

A simple script which I used to reproduce using a clean Chromium profile::

```bash
#!/usr/bin/bash

extensions=(
    # Surfingkeys
    https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc?hl=en-US
    # Dark Reader
    https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US
)

error() {
    echo "$*" >&2
    exit 1
}

# tmpdir=$(mktemp -d) || error "Cannot create temporary directory"
tmpdir=$HOME/tmp/chrome
mkdir -p "$tmpdir"
chromium --user-data-dir="$tmpdir" "${extensions[@]}"
# rm -rf "$tmpdir"
```

**Comment by ackalker** [comment]
Dark Reader v4.9.45 (built from Git master) has the same issue, Downgrading Dark Reader to v4.9.43 made hints visible again. I'm not sure whether to assign the issue to Surfingkeys or to Dark Reader, as Dark Reader deals with a more generic task of rendering websites in dark mode.

**Comment by lmburns** [comment]
Is there a way to change the color of the hints? I found this issue [`#323`](https://github.com/brookhong/Surfingkeys/issues/323) which mentioned that you can change the color of the hints when pressing `v`
```javascript
api.Hints.style(
  "border: solid 0px #C38A22;padding: 1px;background: #b16286",
  "text"
);
```
But I was unable to figure out how to change it when pressing `f`

**Comment by chalop** [comment]
Removing the second parameter (remove the "text" completely) makes the `f` styling work for me.

**Comment by lmburns** [comment]
@chalop Thank you, that worked for me as well

**Comment by ariel-frischer** [comment]
I had the same issue, @lmburns `api.Hints` worked for me!

**Comment by onguarde** [comment]
thanks this works, i believe this workaround important enough to be in the wiki. Saves a lot of trouble.

**Comment by brookhong** [comment]
Wiki is writable for anyone, feel free to add whatever works for you to share with others. Closing this.

**Comment by arizzubair** [comment]
This issue has been fixed in darkreader (https://github.com/darkreader/darkreader/pull/8173). It's not available until the next version is released in browser app stores. You can run master branch build of darkreader if you want to use it immediately.
