### ISSUE TITLE
Keymap | Add (escape insert-mode) | setting `<c-[>` as an <ESC> alternative to leaving insert-mode

### ISSUE THREAD

**Issue by fohrums** [brookhong/Surfingkeys#166]
**LAST-UPDATED**: `20170102@230915`
**STATEMENT**: `Newly posted, awaiting for appropriate responses.`

___

`Surfingkeys` by default uses the typical `<ESC>` to leaving insert-mode. Now that's the root way to do it, but how about having another more **vim-like way via `<c-[>` as an additional keymapping**?

# **PROBLEM**

* No way to *leave* insert-mode the vim-like way, which is `<c-[>`
  - because there is no default keymapping for it, still trying to find one that'll work

# ~~**SOLUTION**~~

* none-so-far
___

# OFFTOPIC (*why i'm giving Surfingkeys a try*)

**Surfingkeys** caught my attention by it's greater hook-intervals & interesting keymappings (*in-fact it's mappings aren't even vim-like at all*). Specifically, it's versatile search functions to make use of various search sites. One standout feature is the Markdown preview (*I now feel one with the universe*), but most importantly is it's very own built in vim-editor that works like a mini page element hovering over your text space :)

So, when comparing surfingkeys to others like `cVim / Vrome` SF had a better response-feel is what I mean by greater hook-intervals as where for cvim I had to keep refreshing in-operatable tabs way too often.

As for vrome I didn't like the plain fact that it didn't have an easy tab navigation specifically for going to next-tab as where going to previous-tab was defined; strange,... but enough for me to to not use it at all. That miniscule lacking detail did it for me to try out Surfingkeys and I am indeed struggling with it's keybindings a lot, but it's responsiveness is at this point unmatched.

One thing that's lacking in Chrome when it comes to these keybinding-keyboard-oriented extensions is an indicator allowing users to know what mode they're in. Because let's be honest..... why would one struggle to guess when they could instead simply know from the get go to prevent this hassle.

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/issues/123

add below setting:

```
map('<Ctrl-[>', '<Esc>');
```
