### ISSUE TITLE
搭配插件DarkReader情景下，按F超链接快捷键看不清

### ISSUE THREAD

**Issue by xj179** [brookhong/Surfingkeys#1666]
## Error details

SurfingKeys: 0.9.74

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

URL: <The_URL_Where_You_Find_The_Issue>

## Context
 搭配插件DarkReader深色情景下，按F超链接快捷键看不清，里面的文字看不清。显示的效果是黄色的外框，里面的字母文字显示的是白色看不清文字。surfingkeys版本号为：0.9.74

**Comment by DiorWine** [comment]
通过更改hints的颜色可以改变darkreader转化的颜色，比如
api.Hints.style('border: solid 3px #552a48; color:#efe1eb; background: none; background-color: #552a48;');
api.Hints.style("div{border: solid 3px #707070; color:#efe1eb; background: none; background-color: #707070;} div.begin{color:red;}", "text");

**Comment by xj179** [comment]
不能截图 好麻烦 。。我试了下没用啊~，咋 回事呢！ 添加 的方式如下：
// an example to create a new mapping `ctrl-y`
mapkey('<ctrl-y>', 'Show me the money', function() {
    Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});

addSearchAliasX('z', '知乎搜索', 'https://www.zhihu.com/search?type=question&q=');
mapkey('oz', '知乎', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "z"});
});

// an example to replace `T` with `gt`, click `Default mappings` to see how `T` works.
map('gt', 'T');

// an example to remove mapkey `Ctrl-i`
unmap('<ctrl-i>');

// set theme
settings.theme = `
.sk_theme {
font-family: Input Sans Condensed, Charcoal, sans-serif;
font-size: 10pt;
background: #24272e;
color: #abb2bf;
}
.sk_theme tbody {
color: #0A0E12;
}
.sk_theme input {
color: #d0d0d0;
}
.sk_theme .url {
color: #61afef;
}
.sk_theme .annotation {
color: #56b6c2;
}
.sk_theme .omnibar_highlight {
color: #528bff;
}
.sk_theme .omnibar_timestamp {
color:#303030;
}
.sk_theme .omnibar_visitcount {
color: #98c379;
}
.sk_theme #sk_omnibarSearchResult ul li:nth-child(odd) {
background: #303030;
}
.sk_theme #sk_omnibarSearchResult ul li.focused {
background: #3e4452;
}
api.Hints.style('border: solid 3px #552a48; color:#efe1eb; background: none; background-color: #552a48;');
api.Hints.style("div{border: solid 3px #707070; color:#efe1eb; background: none; background-color: #707070;} div.begin{color:red;}", "text");

#sk_status, #sk_find {
font-size: 20pt;
}`;
// click `Save` button to make above settings to take effect.</ctrl-i></ctrl-y>

请问是添加错误了嘛，不是用这 种方式添加？

**Comment by DiorWine** [comment]
sorry, 好像他在新版本更改了设置的接口，我是1.0.3版本的，你看一下之前的history里面hints怎么设置的吧

**Comment by HeisensOppings** [comment]
请问解决了吗，我也是这样dark reader它是通过反色来的，vimium可以，但还是sur好用些

**Comment by zhuchengxue** [comment]
暗色模式，可以使用chrome自带的 dark model 模式，按f键就能显示清晰了，你们可以试一下

**Comment by xj179** [comment]
> 请问解决了吗，我也是这样 dark reader 它是通过反色来的，vimium 可以，但还是 sur 好用些

还没解决呢，更新到1.0.3版本也不行~

**Comment by xj179** [comment]
> 暗色模式，可以使用 chrome 自带的 dark model 模式，按 f 键就能显示清晰了，你们可以试一下

我试了下Edge，自带的暗黑模式不能网页是暗黑模式，比如打开百度，背景色还是白的，所以不行`~

**Comment by eMe-404** [comment]
老铁们这个有解决方案了吗？

**Comment by suzghy** [comment]
最新的DR已经解决这个问题了

**Comment by xj179** [comment]
> 最新的 DR 已经解决这个问题了

嗯嗯，今天 试了下，确实修复了。DR最新版本确实修复了这个bug~
