### ISSUE TITLE
can't use Vim-like marks with 'u

### ISSUE THREAD

**Issue by brucmao** [brookhong/Surfingkeys#1667]
url_A   will 302 redirect to url_B
I want to use 'u  visit  url_A 

The second solution, I  create vim-like marks from the bookmarks, find  url_A and press `ctrl+u` will open view-source by firefox/chrome.

So, how can I get url_A  with 'u?

**Comment by b0o** [comment]
Here's a workaround. Instructions for Firefox:

1. Open your devtools (`Ctrl+Shift+i`), click on console tab
2. Click the select the SurfingKeys iframe using the button in the top right of the console:

    https://user-images.githubusercontent.com/21299126/153859168-dfcbcd7a-c9c0-4416-b491-f3ef41dcffee.mp4

3. Paste this snippet in the console, change `https://example.com` on the last line to whatever URL you want, and press enter:

```js
setMark = async (mark, url) => { 
  const storage = (browser ?? chrome).storage.local
  const { marks } = await storage.get("marks")
  await storage.set({ marks: { ...marks, [mark]: { url, scrollLeft: 0, scrollTop: 0 }}})
  return (await storage.get("marks")).marks
}

await setMark("u", "https://example.com")
```

**Comment by brucmao** [comment]
@b0o This is great. Thanks! This problem has been bothering me for a long time.

**Comment by brookhong** [comment]
You could also use `yj` to dump all settings/data from Surfingkeys into clipboard, paste into some text editor, then search `marks`.

**Comment by brucmao** [comment]
1. `yj` Copy current settings , 
2. edit the url,  
3. `;pj` Restore settings data from clipboard
