### ISSUE TITLE
icon dropdown menu doesn't work

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#167]
When I click the extension's icon, a dropdown menu appears with two items:

- Disable Surfingkeys
- Settings

However nothing happens when I click on either of them.

**Comment by brookhong** [comment]
Thanks for reporting the issue.

**Comment by aspiers** [comment]
Works perfectly now, thanks a lot!

**Comment by aspiers** [comment]
This has broken again, please can you reopen?  I think you need some regression tests.

**Comment by brookhong** [comment]
yes, regression tests help a lot here, but It takes time.

Thanks, fixed in 0.8.2
