### ISSUE TITLE
quickly disabling/enabling Surfingkeys breaks notifications

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#168]
Thanks a lot for the new notification which resolves #162 - this is great!  However I did notice one problem with it:

The notification toaster popup takes a few seconds before it vanishes again.  If I press `Alt-S` during the time it is still visible, then the toaster vanishes straight away and no further toasters pop up for every subsequent time I press `Alt-S` (even though it still disabling/enabling Surfingkeys correctly).

**Comment by brookhong** [comment]
Yes, I also noticed that.

Fixed, will be released in next version.

**Comment by brookhong** [comment]
Released in 0.6.9
