### ISSUE TITLE
请问如何屏蔽某个Surfingkeys热键(让其回归默认热键)

### ISSUE THREAD

**Issue by godefy** [brookhong/Surfingkeys#1681]
比如目前 ctrl-h 是 触发元素的鼠标移入事件。我希望能将ctrl-h 是默认的打开系统历史记录，请问该如何进行配置?
我尝试在配置里这样写：unmap('<ctrl-h>');
但是没有任何效果。

**Comment by clarkwang** [comment]
Try this:

~~~
api.unmap('<Ctrl-h>');
~~~

**Comment by godefy** [comment]
> Try this:
> 
> ```
> api.unmap('<Ctrl-h>');
> ```

谢谢，这样可以了。
但我比较疑惑，我之前是按教程里说的这样：
const {aceVimMap,mapkey,imap,imapkey,iunmap,getClickableElements,vmapkey,map,unmap,vunmap,cmap,addSearchAlias,removeSearchAlias,tabOpenLink,readText,Clipboard,Front,Hints,Visual,RUNTIME} = api;
api.unmap('<Ctrl-h>');
不知道为什么没有生效。
