### ISSUE TITLE
 [SurfingKeys] Error found in settings: ReferenceError: Hints is not defined

### ISSUE THREAD

**Issue by bs0c** [brookhong/Surfingkeys#1685]
## Error details

SurfingKeys: 1.0.4

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

I have default setting. If I add line Hints.setCharacters("abcd"). I see  the error on every windows. I saw https://github.com/brookhong/Surfingkeys/issues/1658, but I don't understand what it want from me.

**Comment by clarkwang** [comment]
Try:

~~~javascript
api.Hints.setCharacters("abcd");
~~~
