### ISSUE TITLE
cpu占用莫名升高

### ISSUE THREAD

**Issue by hezhiyang2000** [brookhong/Surfingkeys#1689]
## Error details
浏览网页时surfingkeys的cpu莫名升高了，我尝试了关闭其他所有的插件，不是冲突的问题，我没有找到能稳定复现的方法，现在的解决办法是禁用后再重新启用，就会恢复到正常的水平了。我不知道有什么可以提供给开发者分析这一问题的方法，如果有请告诉我！

SurfingKeys: 1.0.3

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

**Comment by brookhong** [comment]
是在特定网页上吗？

**Comment by hzydhz** [comment]
好像并不是，我也不能非常确定这个引发的原因，因为总是浏览着浏览着就发现风扇开转了

**Comment by 0x7a7a** [comment]
@brookhong b
我也遇到了
我怀疑是在有大量历史记录的时候使用`t`或者`oh`搜索后导致的
1. 界面会卡顿
2. dialog退出后后台是否仍然在运行这个索引?

遇到这个情况我只能重启浏览器,不然cpu就持续飙高

**Comment by brookhong** [comment]
> 2. dialog退出后后台是否仍然在运行这个索引?
不会，这个只跑一次，获得结果后就不会再跑的

如果有固定的重现步骤，能有助于定位问题。也可以尝试关闭引发问题的标签页，Surfingkeys会在某些情况下监听Dom Tree的变化事件，不确定会不会有些页面因为Dom不停变化，触发Surfingkeys的事件处理。

**Comment by 0x7a7a** [comment]
> > 2. dialog退出后后台是否仍然在运行这个索引?
> >    不会，这个只跑一次，获得结果后就不会再跑的
> 
> 如果有固定的重现步骤，能有助于定位问题。也可以尝试关闭引发问题的标签页，Surfingkeys会在某些情况下监听Dom Tree的变化事件，不确定会不会有些页面因为Dom不停变化，触发Surfingkeys的事件处理。

我明白,之前频繁遇到这个问题后我尝试修复,但也不是必现,后来莫名又正常了一段时间.
我的经验是`t`后触发机率比较高,我会继续跟踪这个问题,如果有发现会在这个issue里反馈.

**Comment by startnoob** [comment]
性能窗口看了下，在omnibar中输入一个找不出结果的字符串就会在后台不停地跑RegExp，导致占用飙升
而且字符串的多个前缀子串也会不停地跑
希望尽快解决，这个实在影响使用

**Comment by brookhong** [comment]
duplicate of #1975, closing this.
