### ISSUE TITLE
Surfingkeys turned OFF for chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#169]
Sometimes I am getting messages like these when I press `Alt-S`.  I haven't figured out why yet.

**Comment by brookhong** [comment]
The URL here is from Surfingkeys itself. It should be fixed as well in #172, after `Disabled` mode is prohibited.

**Comment by brookhong** [comment]
Released in 0.6.9
