### ISSUE TITLE
I was charged $10 for 1.0.4 when I already paid $10 for 1.0.3

### ISSUE THREAD

**Issue by zendude213** [brookhong/Surfingkeys#1696]
Charged for same app on app store. Want refund for 1.0.3

<img width="773" alt="Screen-Shot-2022-03-08-12-37-55" src="https://user-images.githubusercontent.com/59263556/157303540-600f17ff-d49d-412c-991c-73618c0a71b8.png">

<img width="785" alt="Screen-Shot-2022-03-08-12-38-46" src="https://user-images.githubusercontent.com/59263556/157303580-bd8ec2a6-cc63-4644-ab93-e72bbf30bbd5.png">

**Comment by clarkwang** [comment]
I don't think the app author can do anything about this. Call Apple.

**Comment by brookhong** [comment]
Surfingkeys 1.0.4 is a new app released, and the versions before it were revoked. The reason behind this is that the app was wrongly configured when I released Surfingkeys 1.0(I chose the Kids Category), which then caused the failure to release the App for iOS. I had communicated this issue with Apple Support several times, there is no way for them to modify the settings for original release on App Store or approve the iOS release without Kids Category removed.

The only way that Apple Support suggested is to release a new App, then it comes to the breaking change. Sorry for the confusion. As for refunding, I really don't have any experience and don't know how to, and I do see some users can upgrade from 1.0.3 to 1.0.4 without another purchase. I'll contact with Apple Support to see if there is a way to refund for old versions.

**Comment by zendude213** [comment]
Thanks. It's a good product. No need to refund

**Comment by b0o** [comment]
The same thing happened to me, except I just lost access to the app. Is there a way to get the new version without paying again?

**Comment by brookhong** [comment]
@tshu-w Could you share your experience with @b0o here?

**Comment by tshu-w** [comment]
@brookhong Hi, it is no longer possible to request a refund on the webpage because the previous purchase was made too long ago. So I simply bought another one and have not yet contacted Apple for a refund on the previous item. I think as the author you can help us contact Apple to transfer the user who bought the previous one to the new one?
