### ISSUE TITLE
addSearchAliasX does not work for v1.0.5

### ISSUE THREAD

**Issue by K-learning-C** [brookhong/Surfingkeys#1699]
## Error details
addSearchAliasX('*', '****', '*****'); does not work for v1.0.5. I'm getting following error.

_[SurfingKeys] Error found in settings: ReferenceError: addSearchAliasX is not defined_

SurfingKeys: 1.0.5

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by b0o** [comment]
`addSearchAliasX` was replaced with `api.addSearchAlias`.

See [Migrate your settings from 0.9.74 to 1.0 · brookhong/Surfingkeys Wiki](https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0).
