### ISSUE TITLE
CSS broken in reddit

### ISSUE THREAD

**Issue by xream** [brookhong/Surfingkeys#17]
disable:

![before](https://cloud.githubusercontent.com/assets/1210282/11917912/c7109022-a755-11e5-91dc-ce79385647fd.png)

enable:

![after](https://cloud.githubusercontent.com/assets/1210282/11917913/cb0e4a66-a755-11e5-9d0a-561e1cfd52b0.png)

**Comment by brookhong** [comment]
Thanks.

Fixed in 0.2.5.
