### ISSUE TITLE
disabling Surfingkeys doesn't always disable Control+i

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#170]
I've disabled Surfingkeys for a particular domain (our internal etherpad server), but when I press `Control+i` it still opens a Surfingkeys editing dialog rather than converting text into italics.  If I re-enable and then disable again, the problem is still there.  Strangely I don't see the same problem in Google Docs.

**Comment by brookhong** [comment]
Thanks for reporting this issue.

Fixed, will be released in next version.

**Comment by brookhong** [comment]
Released in 0.6.9
