### ISSUE TITLE
Selector overlaied thus can't access link by it

### ISSUE THREAD

**Issue by LintaoAmons** [brookhong/Surfingkeys#1703]
## Error details

After pressing `f`, multiple selectors show in the window, but I can't get access to it because the wanted link selector was hidden by other selectors.
![image](https://user-images.githubusercontent.com/95092244/157577025-7cc34332-3d15-4f4b-b370-f97c2e2a5e32.png)

SurfingKeys: 1.0.4
Browser: Firefox 97.0.2 (64-bit)
MacOs: MacOs Monterey Version 12.2.1
URL: [<The_URL_Where_You_Find_The_Issue>
](https://www.google.com.hk/search?q=json+path+expression+get+a+field+of+list+of+objects&newwindow=1&client=firefox-b-d&ei=jWIpYommMt-F4t4P3_GisAM&oq=json+path+expression+get+a+field+of+list+of+obj&gs_lcp=Cgdnd3Mtd2l6EAMYADIFCCEQoAEyBQghEKABOgQIABBDOgUIABCABDoECAAQHjoGCAAQCBAeOgQIABATOgYIABAeEBM6CAgAEAgQHhATOgcIIRAKEKABSgQIQRgASgQIRhgAUABYtUZg70poAXABeACAAccCiAGxKJIBCDAuMjAuNC40mAEAoAEBwAEB&sclient=gws-wiz)
> Actually this can be found in many pages

**Comment by b0o** [comment]
If you tap the shift key in this scenario, it will shuffle the z-index of hints so that you can see obscured ones.

**Comment by LintaoAmons** [comment]
> 

Thanks!~~
