### ISSUE TITLE
Add banner hint when sucessfully copy URL to clipboard

### ISSUE THREAD

**Issue by hiberabyss** [brookhong/Surfingkeys#171]
Sometimes, when press `yy`, I'm not sure whether the current page's URL is copied to clipboard successfully.

Could the banner hint be added when copy the URL successfully just like what `sr` does?

Thanks very much!

**Comment by brookhong** [comment]
Thanks for suggestion.

**Comment by brookhong** [comment]
Released in 0.6.9
