### ISSUE TITLE
Shortcut keys <ctrl+,> do not respond(快捷键<ctrl+,>没反应)

### ISSUE THREAD

**Issue by godefy** [brookhong/Surfingkeys#1710]
Under normal circumstances, in the list opened by the plugin, <ctrl+,> is to page up, and <ctrl+.> is to page down.
But when I use it, <ctrl+.> can take effect normally, but <ctrl+,> has no effect.
I don't know if it is occupied by other shortcut keys, but I couldn't find it in the settings, and I don't know how to find it.

正常情况下在插件打开的列表中，<ctrl+,>是上翻页，<ctrl+.> 是下翻页。
但我使用的时候，<ctrl+.>可以正常生效，但是<ctrl+,>没有效果。
不知道是不是被其它什么快捷键占用了，但在设置里怎么找也没找到，不知道怎么查出来。

**Comment by b0o** [comment]
What browser are you using?

**Comment by daveleeyee2022** [comment]
same here !

OS: win10
Browser: chrome
Surfingkeys: 1.0.5

both <ctrl-.>  and  <ctrl-,> don't work !

**Comment by godefy** [comment]
chrome 99.0.4844.82 64 位
Just tried it and it works fine🤣
刚才试了一下又正常了

**Comment by daveleeyee2022** [comment]
找到原因了，是跟搜狗输入法的快捷键冲突了。<ctrl-.>是中英文标点切换， <ctrl-,>是系统打开搜狗输入法的快捷键。 键位更改后， omnibar 的翻页功能已经正常。
