### ISSUE TITLE
Feature Request: Reload page without subdomain

### ISSUE THREAD

**Issue by janacm** [brookhong/Surfingkeys#1712]
Hello! 

Just like how `g?` reloads the page without the query params, can we get a feature for reloading without a subdomain?

For example:

While on `docs.GitHub.com` press `g.` to get to `GitHub.com`.

**Comment by b0o** [comment]
This can be accomplished in your configuration.

```js
api.mapkey("g.", "Go to parent domain", () => {
  const subdomains = location.host.split(".")
  const upperDomain = (subdomains.length > 2 ? subdomains.slice(1) : subdomains).join(".")
  location.assign(`${location.protocol}//${upperDomain}`)
})
```

Note the above code removes one subdomain at a time. It will refuse to remove the final domain, but it will have an issue if you are on `google.co.uk` for example and press `g.`, it will direct you to `co.uk`. Trying to fix this would require keeping a list of domains like `co.uk`, etc.

**Comment by janacm** [comment]
This is awesome thank you
