### ISSUE TITLE
请教代码，如何实现在指定的网站限制使用某个提示字符。

### ISSUE THREAD

**Issue by daveleeyee2022** [brookhong/Surfingkeys#1717]
brook你好，

在浏览 jd.com时光标乱跳，经passthrough测试，京东的页面只要输入字符“s”，光标就自动定位到第一个输入框，所以hint字符如果包含“s”，就会导致快捷键中断，那么要实现在 浏览 jd.com时hint字符屏蔽“s”，该怎么写代码？

然而，搜索命令如 sb sg 同样带有s， 也会导致命令失效，这该如何解决呢？

**Comment by brookhong** [comment]
谢谢，这个是bug，不应该通过限制提示字符来实现，下一版本会更新。
