### ISSUE TITLE
建议：默认禁用插件的pdf阅读功能 太简陋而且很难找到关闭按钮

### ISSUE THREAD

**Issue by czzonet** [brookhong/Surfingkeys#1718]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: <version>

Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

- chrome自带的阅读更好
- 虽然可以用；s关闭 可是不明显

**Comment by junjieit** [comment]
防止后来者不知道如何关闭，贴上关闭文档: https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E7%A6%81%E7%94%A8surfingkeys%E6%8F%90%E4%BE%9B%E7%9A%84pdf%E6%9F%A5%E7%9C%8B%E5%99%A8
