### ISSUE TITLE
Got blank after press f when macOS system appearance is dark

### ISSUE THREAD

**Issue by tshu-w** [brookhong/Surfingkeys#1719]
## Prelude
Both done.

## Error details

SurfingKeys: 1.0.3

Browser: Safari 15.4 (17613.1.17.1.13) macOS 12.3.1

URL: Any like https://github.com/brookhong/Surfingkeys/issues

## Context

When macOS system appearance is dark and I press `f` I got blank page.

macOS系统为 dark模式时（或者从 light 切换成 dark），按 f 页面空白。

<img width="2008" alt="Screen Shot 2022-04-01 at 19 26 32" src="https://user-images.githubusercontent.com/13161779/161254563-f3060c4b-9737-41e0-9e70-5282910f5762.png">

**Comment by brookhong** [comment]
Can not reproduce this with 1.0.4.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/288207/162569360-e3beb1d0-3cb0-4a88-a3a1-a0b9767aecc5.png">

**Comment by tshu-w** [comment]
Sorry, I find this only occurs when system switch appearance.
Here is the detailed step to reproduce it.
1. Quit safari.
2. make sure macOS system appearance is Light.
3. open this issue https://github.com/brookhong/Surfingkeys/issues/1719
4. test `f` works fine now.
5. change macOS system appearance to Dark.
6. press `f` again and got the blank page.

**Comment by brookhong** [comment]
But I still can not reproduce this by following the exact steps above, could you try to upgrade to 1.0.4?

**Comment by tshu-w** [comment]
Hi, the latest version on App Store is 1.0.3?

**Comment by jmolero** [comment]
I'm using 1.0.4 and I have the same problem. I was able to fix it by setting `color-scheme: light` instead of auto in the SurfingKeys iframe. I hope that helps.

**Comment by tshu-w** [comment]
@jmolero Thanks you for your tips. However, I'm totally newbie for surfingkeys and css, it would be much appreciated if you could share your full config.

**Comment by jmolero** [comment]
I tried adding to the config but couldn't make it work. I think it is because this property is set in the div that wraps the SurfingKeys iframe. I hope this can be fixed. I inspected the CSS and this property was set to auto. Somewhere below it was set to dark, which makes it show the white page. If setting it to light it fixes the issue.

**Comment by tshu-w** [comment]
@brookhong Hi, I found the version on MAS is still 1.0.3. Would you mind update the version which make this https://github.com/brookhong/Surfingkeys/commit/ccedde8f16111cc4c5639da5f2bfcff4b782e9b0 take effect on macOS?

**Comment by brookhong** [comment]
@tshu-w If you can't download the latest version, please see #1696, but I don't know how, please contact Apple for help.

**Comment by tshu-w** [comment]
@brookhong Hi, I download the new one and it works now.

**Comment by b0o** [comment]
It would be nice if we could find a way to fix this issue without forcing the color scheme to be `light`, as this prevents users from creating light/dark mode themes in their custom configurations.
