### ISSUE TITLE
weird popup sometimes appears

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#172]
Not sure if I'm doing something stupid, but sometimes I get random popups from SurfingKeys appearing, and I have no idea why.  For example:

![popup](https://cloud.githubusercontent.com/assets/100738/21619285/ec32a612-d1e6-11e6-9254-d0ba1f3a86c0.png)

This sounds quite similar to #115.

**Comment by aspiers** [comment]
Hmm, is this related to Google Calendar somehow?  If I reload this page and then disable SurfingKeys via the icon dropdown, then the dialog appears with this text:

    Disabled@ : TopHook,Front,Normal

If I re-enable then I cannot dismiss it via `Escape`.

**Comment by brookhong** [comment]
The popup is actually a bug informer. It shows whenever an already-pushed mode is pushed into mode stack again. In your first case, the mode is `Front`, which is for Surfingkeys' UI.

`Disabled` mode will be prohibited on Surfingkeys' UI, which will fix the problem.

**Comment by aspiers** [comment]
Ah OK, thanks! In that case, I suggest changing the message so that it is less cryptic to normal users and encourages them to take helpful action, e.g.

    <h2>Uh-oh! The SurfingKeys extension encountered a bug.</h2>

    <p>Please <a
    href="https://github.com/brookhong/Surfingkeys/issues/new?title=Front+pushed+into+mode+stack&body=%23%23+Error+details%0d%0dDisabled@+:+TopHook,Front,Normal%0d%0d%23%23+Context%0d%0d%2a%2aPlease+replace+this+with+a+description+of+how+you+were+using+SurfingKeys.%2a%2a">click
    here to start filing a new issue</a>, append a description of how
    you were using SurfingKeys before this message appeared, then
    submit it.  Thanks for your help!</p>

    <p>Error details: Disabled@ : TopHook,Front,Normal</p>

**Comment by brookhong** [comment]
Thanks, message in popup will be updated.
