### ISSUE TITLE
请问如何修改passthrough 的时间？

### ISSUE THREAD

**Issue by zhixin-zhao** [brookhong/Surfingkeys#1721]

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#normalpassthrough

**Comment by zhixin-zhao** [comment]
在setting中添加：`Normal.passThrough(500);`
刷子页面后提示错误：`[SurfingKeys] Error found in settings: ReferenceError: Normal is not defined`

**Comment by bobenson** [comment]
@zhixin-zhao 
Surfingkeys 更新后，所有的API前面需要前缀 `api.`，所以你试试 `api.Normal.passThrough(500);`

**Comment by zhixin-zhao** [comment]
在setting中添加：api.Normal.passThrough(500);
刷新页面后按下`p`，仍然显示`ephemeral (1000ms) pass through`

**Comment by brookhong** [comment]
你需要重新定义下`p`键。

    api.unmap('p');
    api.mapkey('p', '#0Enter ephemeral PassThrough mode to temporarily suppress SurfingKeys', function() {
        api.Normal.passThrough(5000);
    });
