### ISSUE TITLE
Google Chrome 

### ISSUE THREAD

**Issue by axiat** [brookhong/Surfingkeys#1722]
## Error details
Chrome打开特定网页，surfingkeys显示灰色不启动（例如虎牙）；重启chrome，surfingkeys会被自动disable。windows、mac下都出现。
其他浏览器比如firefox/edge没有这个问题）
求问如何解决，谢谢~！

SurfingKeys: 1.0.5

Browser: Chrome/100.0.4896.75 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
你可能是在这些网页上禁用了Surfingkeys，请参考https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-surfingkeys-only-on-current-site
