### ISSUE TITLE
Ipad os surfingkeys type f appear blank page in google

### ISSUE THREAD

**Issue by zempty-zhaoxuan** [brookhong/Surfingkeys#1723]
## Error details
My safari default engine is Google , when search text **in safari hit some results when type f (want to visit other links)will have a blank page occur…**

**issues occur in iPadOS 15.4.1**

![](https://raw.githubusercontent.com/zempty-zhaoxuan/pics/master/IMG_1392.jpg)

![](https://raw.githubusercontent.com/zempty-zhaoxuan/pics/master/IMG_1395.jpeg)

SurfingKeys: 1.0.4

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
It this a duplicate issue of https://github.com/brookhong/Surfingkeys/issues/1719?
