### ISSUE TITLE
How to disable the PDF Viewer?

### ISSUE THREAD

**Issue by kongse** [brookhong/Surfingkeys#1724]
I like the Native EDGE PDF Viewer.
So how to disable the surfingkeys's pdf viewer?

## Error details

SurfingKeys: 1.0.5

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-pdf-viewer-from-surfingkeys

**Comment by Riveascore** [comment]
# Disable PDF viewer from Surfingkeys
```
;s
```

**Comment by cemiu** [comment]
Alternatively, if you made use of the `unmapAllExcept` option:
```js
api.RUNTIME('updateSettings', {settings: {"noPdfViewer": 1}});
```
