### ISSUE TITLE
f改成s后f还有效

### ISSUE THREAD

**Issue by monf2022** [brookhong/Surfingkeys#1729]
## Error details
f和b站全屏键冲突

SurfingKeys: 1.0.4

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by draftman9** [comment]
> f和b站全屏键冲突

`pf`可以实现你想要的功能——在bilibili.com的视频界面用快捷键开全屏。

**Comment by bobenson** [comment]
@monf2022 
如果你只是用 `api.map('c', 'f')` 的话，并不能移除 `f` 键的绑定的，在下面再加一行 `api.ummap('f')`，这样 `f` 才会没有效果

**Comment by brookhong** [comment]
> @monf2022 如果你只是用 `api.map('c', 'f')` 的话，并不能移除 `f` 键的绑定的，在下面再加一行 `api.ummap('f')`，这样 `f` 才会没有效果

对的，不过`unmap`需要加在`map`之前
