### ISSUE TITLE
Can't submit event through Enter button on Google Calendar

### ISSUE THREAD

**Issue by ligyxy** [brookhong/Surfingkeys#173]
I am not sure if this only happens on Google Calendar, that I cannot quick submit an event by pushing Enter key on the calendar directly (not on the CREATE page). I assume that this extension overwrite the action of pushing down Enter key?

**Comment by brookhong** [comment]
Thanks for reporting the issue.

**Comment by brookhong** [comment]
Fixed in 0.6.9
