### ISSUE TITLE
append url parameters to the search_url in addSearchAlias

### ISSUE THREAD

**Issue by m-zheng** [brookhong/Surfingkeys#1731]
I am wondering if it is possible to append some url parameters to the search_url in addSearchAlias.

There are some cases that the search_url requires more parameters, such as cookieless settings. A complete example would be `www.search_engine.com/?query=%s&prfe=blablabla` where the `%s` is the placeholder for the actual query and `prfe=blablabla` is hardcoded. 

Based on the example shown in the [API](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#addsearchalias), I think the actual query is appened to the search_url by default which prevents me from appending any url parameters.

I have been trying to find the variable that stores the actual query so that I can modify the search_url before it is passed into addSearchAlias. But no luck. I may be missing something, so any help would be appreciated.

**Comment by brookhong** [comment]
Please try `https://www.search_engine.com/?query={0}&prfe=blablabla`, sorry for not putting this in the API doc, will fix it.
