### ISSUE TITLE
打开网页总是提示addSearchAliasX没有被定义

### ISSUE THREAD

**Issue by sunny-00001** [brookhong/Surfingkeys#1733]
在更新前surfingkeys一直工作正常，自从刚刚更新后，打开网页总是提示addSearchAliasX没有被定义，之前自定义的配置也全部失效，这次到底更新了什么

**Comment by brookhong** [comment]
看下这个https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0
