### ISSUE TITLE
[feature req] bring back the ability to feed a search term

### ISSUE THREAD

**Issue by Madd0g** [brookhong/Surfingkeys#1736]
With the switch the new SK API, my code that inserted a search query into the search history stopped working. It was always a little hacky, it would be nice if there was a more formal API to achieve this.

It used to inject some search terms into the search history, with the goal of just pressing 'n' to search.

This is how I used to do it before the API change:

```js
// first way
Visual.visualUpdate(query.replace(/\+/g, "|")); // this works but doesn't support escape to cancel search

//second way
Visual.visualEnter(query.replace(/\+/g, '|'));
Visual.hideCursor();
```

It would be nice if there was an easy way of doing it. For example something like this would work for me:

```js
Visual.setSearchTerm(query); //set history

Visual.startSearch(); //start searching with the last query
Visual.startSearch(query); //start searching with new query

// more options possible with either just highlighting the results, or having a visible Visual Mode cursor.
```

I think the feature of feeding a search term is very powerful, another use case for me is moving search terms from a search input to an in-page search.

Thanks!

**Comment by brookhong** [comment]
This is not a common requirement, but you could achieve that with `RUNTIME` to update `findHistory`, please refer to https://github.com/brookhong/Surfingkeys/blob/35558a2fc3a3a3f06c2979411c6c0ef2d61abeb5/src/content_scripts/common/runtime.js#L109-L135

**Comment by Madd0g** [comment]
am I doing it wrong?

```js
      RUNTIME("updateHistory", {
        type: "find",
        cmd: query.replace(/\+/g, "|"),
      });

```
