### ISSUE TITLE
Not working for google.com

### ISSUE THREAD

**Issue by DrakeXiang** [brookhong/Surfingkeys#1737]
## Error details

SurfingKeys: 1.0.5

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 OPR/86.0.4363.23

URL: <The_URL_Where_You_Find_The_Issue>

## Context

It used to be working before I reinstalled my browser and extensions, seems has something to do with google's built in shortcut, it works fine for bing or github

**Comment by brookhong** [comment]
Can not reproduce this, have you tried `Alt-s`? https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-surfingkeys-only-on-current-site

**Comment by DrakeXiang** [comment]
Thanks for replying, it might be a browser spesific issue for opera since I just tried on chrome and works fine,  I'll try report this to opera for a shot, thx
