### ISSUE TITLE
How to disable <Ctrl-1> and <Ctrl-2> action?

### ISSUE THREAD

**Issue by fancyoung** [brookhong/Surfingkeys#174]
<Ctrl-1> and <Ctrl-2> is used to select first and second tab by default, but rewrite by surfingkeys.
How to disable it's key binding in surfingkeys?

BTW, it seems there is no better way to choose first tab, why bind <Ctrl-1> and <Ctrl-2> into useless actions?

**Comment by brookhong** [comment]
Add below in your settings to disable them:

    unmap('<Ctrl-1>');
    unmap('<Ctrl-2>');

`g0` Go to the first tab
`g$` Go to the last tab

**Comment by brookhong** [comment]
Fixed in 0.6.9
