### ISSUE TITLE
Unable to disable on certain websites

### ISSUE THREAD

**Issue by tomsiwik** [brookhong/Surfingkeys#1741]
## Error details

SurfingKeys: 1.0.6

Browser: Edg/101.0.1210.39

URL: monkeytype.com

## Context

I was trying to disable the extension for mentioned url with `settings.blacklistPattern = /monkeytype.com.*/i;` however this does not seem to catch the mouse nor disable the extension. I have to manually disable the extension to make the site work again.

Thanks for helping out.

**Comment by brookhong** [comment]
It should be `blocklistPattern`.
