### ISSUE TITLE
Features Request: Jump to the currently playing tab?

### ISSUE THREAD

**Issue by okwellok** [brookhong/Surfingkeys#1748]
For example: "gp" jumps to the playing tab, "xp“ closes the playing tab
There is a firefox [addon](https://addons.mozilla.org/en-US/firefox/addon/go-to-playing-tab-2/) that implement the above features. 
[Tridactyl](https://github.com/tridactyl/tridactyl) also has similar features. "ga"

It would be nice if surfingkeys could add this feature as well.

**Comment by eugercek** [comment]
Very good idea!

**Comment by eugercek** [comment]
I've implemented this I choose `gp` for "Go to playing" and `gxp` for "Close playing". I preferred leaving closing the current tab functionality to a single key.

**Comment by okwellok** [comment]
Thank you!
