### ISSUE TITLE
Proxy Type: "PROXY" and "HTTP" confused me

### ISSUE THREAD

**Issue by shifujun** [brookhong/Surfingkeys#1751]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes.

## Error details

SurfingKeys: 1.0.6

Browser: Chrome 101.0.4951.64 macOS 12.3.1

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context

1. setup proxy with `gost -L="http://127.0.0.1:8080" -F=socks5://127.0.0.1:1080`
2. check proxy working well with `chrome --proxy-server="http://127.0.0.1:8080"`
3. set proxy in Surfingkeys setting page. When I see `Proxy Type:`, I choose `HTTP` without thinking too much, it didn't work.
4. change `Proxy Type:` to `PROXY`, it work.

I simply don't understand what is `PROXY` type, and why it's not a `HTTP` proxy.

Just share my experience :)

**Comment by clarkwang** [comment]
Some refs:

* https://en.wikipedia.org/wiki/Proxy_auto-config
* https://calomel.org/proxy_auto_config.html
* https://developer.mozilla.org/en-US/docs/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file

**Comment by shifujun** [comment]
After read them, I learn much about `PAC`. But I still have questions:

1. `PROXY` type is `PAC`, right? But I didn't setup a `PAC`.
2. Why `HTTP` type not work for my proxy, when `chrome --proxy-server` and `curl -x` all work with it?

**Comment by brookhong** [comment]
Yes, you're right.

`HTTP` is a legacy value for Firefox, which should be removed now.
