### ISSUE TITLE
Why <ctrl-y> 'Show me money' example doesn't work?

### ISSUE THREAD

**Issue by Tritaya** [brookhong/Surfingkeys#1755]
SurfingKeys: <version>

Browser: Chrome on windows

## Context

I'm using the latest version of SurfingKeys and trying to map my own keys. But even an example key binding doesn't work for me.

I didn't change anything in the default settings file in advanced mode.

**Comment by Tritaya** [comment]
I got it. Should be changed in default settings from:
```
api.mapkey('<ctrl-y>', 'Show me the money', function() {
    Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});
```
to (capitalized 'Ctrl' and add 'api' in the seecond line): 
```
api.mapkey('<Ctrl-y>', 'Show me the money', function() {
    api.Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});
```

**Comment by jiapeng123456** [comment]
我也在想呢。。。这隐藏密技还是写到说明里好一些
