### ISSUE TITLE
Tabs (open) | Vim-Like Marks (qmarks) | a way to open a qmark in a new tab

### ISSUE THREAD

**Issue by fohrums** [brookhong/Surfingkeys#176]
**LAST-UPDATED**: `20170104@215755`
**STATEMENT**: `Newly posted, awaiting for proper responses to my suggestion.`

___

Surfingkeys has the ability to add custom **qmarks** whether it's a *local* or *global* one. You could either add it via `m+<key>` or choose to view your Bookmarks (`b`) and add it through selecting which one via `CTRL+<key>`

Now, the 2-ways to open a qmark:
* **DIRECT**: `'<key>`
* **BROWSE**: `om`, upon highlighted-selection `ENTER`

Keep in mind you could use the "browse-method" to open a qmark in a new tab via `ALT+ENTER`, but that's not convenient nor fast as it doesn't utilize the function of **qmark**. So this method is far from ideal, but not saying it wasn't possible to open a qmark in a new tab.

# PROBLEM

* **Not able to open up a `qmark` in a new tab quickly**
  - *it's only able to open up on the tab focused when using the "direct-method"*

# ~~SOLUTION~~

* none-so-far
___

## REFERENCE

* [Surfingkeys (vim-like marks)](https://github.com/brookhong/Surfingkeys#vim-like-marks)

___

### NOTE

* What are `keymaps`?
  + AKA, keyboard shortcuts or hotkeys
    - specifically keymaps could be single-keys or multiple stacked hotkeys to serve as a chain (*e.g. CTRL+G -> Y, just as an example*)
* What are `qmarks`?
  + AKA Quick-marks or vim-like marks that are either pointers in-tabs or bookmarks to be opened that have an easy access through the use of their assigned respective keymaps
* What is *Local* vs. *Global* marks?
  + Local marks is a specific scrolled-position that you've placed on a previously visited tab
  + Global marks are actually bookmarks that you can alternatively open with the use of an assigned `keymap` as opposed to the traditional menu-style `Bookmarks -> "YouTube:subs"`

**Comment by brookhong** [comment]
Released in 0.6.9

For regex to match next/previous links, please use settings below:

    settings.prevLinkRegex = /((上页|上一页|<<|prev(ious)?)+)/i;
    settings.nextLinkRegex = /((下页|下一页|>>|next)+)/i;
