### ISSUE TITLE
Find regex's do not always work

### ISSUE THREAD

**Issue by marcopolo4k** [brookhong/Surfingkeys#1762]
## Error details

Find regular expressions do not always work.

I tried searching (`/`) for `trigger.*llo` on this page:
https://espanso.org/docs/matches/basics/

SurfingKeys was not able to find it.

SurfingKeys: 1.0.6

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

URL: https://espanso.org/docs/matches/basics/

**Comment by brookhong** [comment]
So far regex matching only works for the text within a same element, on the page you mentioned the target string is actually across different `span`.
