### ISSUE TITLE
Neovim doesn't open

### ISSUE THREAD

**Issue by Archie-2021** [brookhong/Surfingkeys#1771]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes
## Error details

SurfingKeys: <version>

Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**
I am using neovim right now on Firenvim to write this report, but commnad in this plugin related to neovim "ctrl-alt-i" and ";v" doesn't work. i wonder if there is a plugin or something i should install or what.

**Comment by brookhong** [comment]
Please follow the instructions here to install native message host for neovim. https://github.com/brookhong/Surfingkeys/blob/master/src/nvim/server/Readme.md

**Comment by Archie-2021** [comment]
> 

Thank you, Is there a way to use my vimrc in this? Vim or Nvim doesn't matter.
