### ISSUE TITLE
Cannot remove Control-f keybinding and make it work as system default (forward a char)

### ISSUE THREAD

**Issue by milanglacier** [brookhong/Surfingkeys#1773]
SurfingKeys: 1.0.3

Browser: Safari/Chrome, macOS 12.4

## Context

I want to make Control-f works as system default behaviro: move forward a char in mac, but I find no way to configure it to do so,

` api.unmap('<control-f>')` doesn't work at all. And if I  try alternatively: `api.imap('<Control-f>', '')`, then it will work weird:
type it the first time, it will forward a char, and type it second time, it will insert a weird char: `♡`.

**Comment by brookhong** [comment]
Please use `iunmap` such as

    api.iunmap("<Ctrl-f>");

**Comment by milanglacier** [comment]
Yes this is the correct approach!
