### ISSUE TITLE
Can't change hotkey to toggle Surfingkeys

### ISSUE THREAD

**Issue by julpec** [brookhong/Surfingkeys#1776]
I tried to change the hotkey mapping like described [here](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys) but it doesn't work.
I would like to use `<Alt-s>` for another action (go one tab right), so I used this sequence : 
```
api.unmap("<Alt-s>");
api.map("<Alt-s>", "R");
api.map("<Alt-i>", "E");
```

It works well but I lose the hotkey function.

**Comment by brookhong** [comment]
That's because you haven't created a new hotkey to toggle Surfingkeys, please use below

    api.map("<Alt-j>", "<Alt-s>");
    api.unmap("<Alt-s>");
    api.map("<Alt-s>", "R");
    api.map("<Alt-i>", "E");
    
Feel free to change `Alt-j` to some other shortcut you prefer.
