### ISSUE TITLE
surfing keys run abnormally  in dark mode

### ISSUE THREAD

**Issue by milanglacier** [brookhong/Surfingkeys#1779]
Example: open safari in nightmode, and type `f` (trying to open a new link), then the whole screen get refreshed to a white background and no text will be shown up in the screen.

archtecture: arm 64
macOS version: 12.4
safari version: 15.5 (17613.2.7.1.8)

https://user-images.githubusercontent.com/45728125/180503631-b52d942d-c600-40bc-a3ba-9ba86e254387.mov

**Comment by brookhong** [comment]
Should have been fixed in 1.0.6, duplicate issue of #1719
