### ISSUE TITLE
Using Apple/Command Key on MacOS

### ISSUE THREAD

**Issue by atomdmac** [brookhong/Surfingkeys#1782]
Is it possible to use the Command key on MacOS as part of a keybind?

**Comment by brookhong** [comment]
Yes, use `Meta` for Command key.

    api.mapkey('<Meta-b>', '#0Debug key', function() {
        api.Front.showPopup(window.location.href);
    });
    
But Surfingkeys can not override system shortcuts, such as `Command + n`.
