### ISSUE TITLE
Uncaught (in promise) Failed to connect neovim, please make sure your neovim version 0.5 or above.

### ISSUE THREAD

**Issue by hzncpa** [brookhong/Surfingkeys#1786]
Uncaught (in promise) Failed to connect neovim, please make sure your neovim version 0.5 or above.

我的sfk在浏览器中每隔一段时间就自动被禁用,检查后发现有这个报错..
如图
![sfk](https://user-images.githubusercontent.com/70250368/182887200-f9714c11-f142-4fca-829c-6973c4a956c1.png)

**Comment by brookhong** [comment]
This should have been fixed, feel free to reopen it if you still see the issue.

**Comment by keyboardset** [comment]
Same problem on edge now
