### ISSUE TITLE
Display Surfingkeys version number somewhere visible

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#179]
Would be helpful when reporting bugs to know what version I'm running.  Maybe this could be shown in the icon dropdown menu?

**Comment by brookhong** [comment]
Thanks for suggestion, version included in icon dropdown menu.

**Comment by aspiers** [comment]
The version has vanished!  Please can you reopen this?

**Comment by brookhong** [comment]
Thanks, fixed in 0.8.2
