### ISSUE TITLE
don't change key in visual mode

### ISSUE THREAD

**Issue by bs0c** [brookhong/Surfingkeys#1792]
## Error details

SurfingKeys: 1.0.6

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

Hi. I have very simple default config and I want to swap 2 keys 'j' and 'n' in visual mode. is that simple task? write this:
```
api.vmap('1','j')
api.vunmap('j')
api.vmap('j','n')
api.vunmap('n')
api.vmap('n','1')
```
It doesn't work... How can I swap it? Please give me some way...

**Comment by bs0c** [comment]
```
api.vmap('1', 'j')
api.vmap('j', 'n')
api.vmap('n', '1')
api.vunmap('1')
```
here 'n' jump down, but 'j' doesn't search forward...

**Comment by brookhong** [comment]
This is not doable for now, as `n` actually is a key in normal mode. It works in Visual mode, as it falls back to Normal mode.
