### ISSUE TITLE
crash when use search bar in chrome://settings/ and the button is useless in chrome://settings/ctrlN

### ISSUE THREAD

**Issue by teteko233** [brookhong/Surfingkeys#1794]
My English is poor, so I will report in Chinese. 我的英语不太好，所以在下面我使用中文。

1. 在设置里搜索会闪退。这个 Bug 只出现在 Windows，Debian 10 试过不会。

2. Ctrl-N/P 里的设置，重启浏览器后会失效。选择“仅当焦点在输入框时用作上下箭头”和“不做改变”这两项，在浏览器没有重启前是正常的。重启浏览器后，这两项显示选中状态，但是行为会变成默认的“始终用作上下箭头”。Windows 和 Debian 10 都会。

Browser: Brook Hong's Chromium 101.0.4951.54 

Question from blog's [comments](https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html)

**Comment by brookhong** [comment]
这两个问题应该都已经解决了。
