### ISSUE TITLE
Extension wants to change my search engine to smartwebfinders.com

### ISSUE THREAD

**Issue by zenVentzi** [brookhong/Surfingkeys#1797]
Latest chrome version, latest surfingkeys version. As I was going about my usual browser surfing, I got asked to either give permission to surfingkeys to change my search engine to smartwebfinders.com or delete the extension. What is happening? Is this by design, if yes why, or has the extension deployment been compromised?

**Comment by isaiahtaylor** [comment]
Has this extension been hacked? Does someone have time to review the source change that triggered this?

**Comment by DavidGretzschel** [comment]
see here:
https://github.com/brookhong/Surfingkeys/issues/1796

**Comment by zenVentzi** [comment]
Weird, I did an issue search with "smartwebfinders" but it didn't find your issue, thanks. Closing this one to keep track there.

**Comment by DavidGretzschel** [comment]
> Weird, I did an issue search with "smartwebfinders" but it didn't find your issue, thanks. Closing this one to keep track there.

My mistake. I wrote it without the "s" at the end. Either someone else I came across in my Google-search also made that mistake and that's where I got it from... or "smartwebfinder" (without the s) is another version or possibly something else entirely.
