### ISSUE TITLE
控制台报错 TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by 0900304132** [brookhong/Surfingkeys#1798]
## Error details

Error handling response: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at <URL>

Error handling response: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content.js:3:43821

![image](https://user-images.githubusercontent.com/10512604/185523466-15791501-774d-46c8-9007-1ce4823a4b5f.png)

![image](https://user-images.githubusercontent.com/10512604/185523641-f0228f70-5eff-42a9-b026-e33724903cca.png)

SurfingKeys: 1.0.7

Browser: Chrome 版本 104.0.5112.81（正式版本） （64 位）

**Comment by brookhong** [comment]
嗯，我也注意到了，这个错误应该只是一次性的，不会影响正常使用，下个版本会fix。

**Comment by 0900304132** [comment]
感谢

**Comment by brookhong** [comment]
1.0.8已修复
