### ISSUE TITLE
Disable SurfingKeys on this domain - is not working

### ISSUE THREAD

**Issue by AlexIvasi** [brookhong/Surfingkeys#18]
Disable SurfingKeys on this domain - it is not working.
Steps to reproduce: 
1. Open https://mail.google.com/ or https://www.linkedin.com
2. Press "Disable SurfingKeys on this domain " option in SurfingKeys menu item.
3. Reload Gmail tab 
4. Press e..g r or gi google shortcut keys - it Gmail it should trigger Gmails native keyboard shortcuts - it is not working at Linkedin either.

Note: despite the fact that menu text changes to Enable Extension on this domain - it is still not working and SurfingKeys keys are passed to that domain / site.

Please, fiix - thank you!

**Comment by brookhong** [comment]
Thanks.

Fixed in 0.2.5

**Comment by AlexIvasi** [comment]
Thank you Brook! :)
Have a great evening.
