### ISSUE TITLE
使用't'打开一个 url 是，若历史记录有这个 url 的字网址时的问题

### ISSUE THREAD

**Issue by youthcould** [brookhong/Surfingkeys#180]
举例：历史记录中有‘http://www.cnbeta.com/articles/574457.htm’
这是我用't'，然后输入框中输入 www.cnbeta.com 并按 enter，打开的不是期望的 www.cnbeta.com，而是上面的地址。建议把输入项作为默认第一选项
谢谢

**Comment by brookhong** [comment]
#229
