### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by Imymirror** [brookhong/Surfingkeys#1800]
Switch between google chrome tab, then Manually use the mouse to click the input box on the web page, for example, google search input box, It is possible to pop up the following window indefinitely

<img width="933" alt="image" src="https://user-images.githubusercontent.com/52570325/185730345-9b487fb6-bf8a-46df-85a0-dd3f7e29add0.png">

## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.7

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

URL: https://www.google.com/search?q=isotropic+material+opengl&newwindow=1&ei=XG4AY8fSDImar7wPt7a0iAw&ved=0ahUKEwjH8Nmf1dT5AhUJzYsBHTcbDcEQ4dUDCA4&uact=5&oq=isotropic+material+opengl&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEB4QFjIFCAAQhgMyBQgAEIYDMgUIABCGAzoHCAAQRxCwAzoHCAAQsAMQQzoFCAAQgAQ6CAgAEB4QDxAWSgQIQRgASgQIRhgAUIoCWP8SYMoUaAFwAXgAgAHeBYgB2wuSAQkwLjIuMi42LTGYAQCgAQHIAQrAAQE&sclient=gws-wiz

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
It seems the issue can not be reproduced every time with provided steps. 

Can anyone provide some steps that can reproduce the issue exactly?

**Comment by bernieke** [comment]
I'm not getting it anymore with 1.0.8, it was only on 1.0.7 I saw the issue.

**Comment by Imymirror** [comment]
> It seems the issue can not be reproduced every time with provided steps.
yes, It is a high incidence, but not an absolute occurrence.

> I'm not getting it anymore with 1.0.8
I am getting it with 1.0.8. 

but I upgrade chrome version recently, the chrome version is  104.0.5112.101 (Official Build) (x86_64). maybe the latest chrome cause the problem. 

In addition, when the issue occurs, press `gi`  not work too.

**Comment by bernieke** [comment]
Yeah, I spoke too soon, I keep having the issue as well, on both my computers.

**Comment by DerFisc** [comment]
This happens quite often for me as well with version 1.0.8 from the Chrome store, but I haven't seen a pattern to reproduce yet.
It happens without using any hotkeys from the extension at all. Just clicking is enough, but I only noticed it on the Google search page.

Used Browser Microsoft Edge Beta
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.17

**Comment by megalithic** [comment]
Same, happening in Brave

**Comment by ariel-frischer** [comment]
Seeing this with brave browser as well. On google search and github input fields.

**Comment by gitterspec** [comment]
Same thing with Brave after upgrading to newest version, when clicking into text inputs. Not everytime.

**Comment by hengfei-wang** [comment]
same here, very annoying. not happen everytime.

**Comment by Imymirror** [comment]
wait for https://github.com/brookhong/Surfingkeys/issues/1854 . If solved, I will close this issue.
