### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by HKing147** [brookhong/Surfingkeys#1806]
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

URL: https://mp.csdn.net/mp_blog/manage/column/columnAdd

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
duplicate of #1800
