### ISSUE TITLE
[ACE Vim editor]: Copy to clipboard?

### ISSUE THREAD

**Issue by 097115** [brookhong/Surfingkeys#1817]
When editing some text in ACE Vim editor, can we copy a selection to the system clipboard?

**Comment by 097115** [comment]
Oh, it's just system's <C-c>, right? 

And I can't create a mapping for it, correct? Like `aceVimMap('Y', SOMETHING, 'visual') to use `Y` to copy the current selection to the system clipboard?

**Comment by brookhong** [comment]
Yes, you're right.

Unfortunately there is no way to create such mapping so far.
