### ISSUE TITLE
Neovim integration not working on Linux (arch)

### ISSUE THREAD

**Issue by DominickVale** [brookhong/Surfingkeys#1818]
## Prelude
* Could you find answer in below documents? No

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes.

## Error details

SurfingKeys: 1.0.8

Browser: 5.4.2753.40 (Stable channel) stable (64-bit) on Manjaro Linux

## Context
Of course i followed the readme correctly. I checked several times. The only difference is that i'm using vivaldi, so the path for me is `.config/vivaldi/NativeMessagingHosts`
This is what shows up when trying to open neovim:
![image](https://user-images.githubusercontent.com/52491108/187680020-684a8097-2e05-4e63-ba19-9991bd25e9ee.png)

**Comment by brookhong** [comment]
A common cause for this is that the path to neovim is not in system environmental variable `PATH`.
