### ISSUE TITLE
Integrated Neovim Not Working on Brave Browser

### ISSUE THREAD

**Issue by ariel-frischer** [brookhong/Surfingkeys#1824]
## Prelude
* Could you find answer in below documents?

## Error details

No Error message just blank page 
SurfingKeys: 1.0.8

Browser: [Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (x86_64)](https://brave.com/latest/)
OS: Mac Monterey 12.4

Open Neovim command `;v` just has a blank page with no console errors or anything.
I've followed the readme at:https://github.com/brookhong/Surfingkeys/blob/master/src/nvim/server/Readme.md
Brave browser didn't have `NativeMessagingHosts` dir in user data dir located at: `/Users/MYUSERNAME/Library/Application Support/BraveSoftware/Brave-Browser` so I created that dir and added `surfingkeys.json` it didn't seem to work.

**Comment by megalithic** [comment]
Any luck @ariel-frischer ?

**Comment by ariel-frischer** [comment]
Oh yea I got it working somehow. Created the missing directory.
