### ISSUE TITLE
"<Ctrl-n>" Forward cycle through the candidates doesn't work in chrome

### ISSUE THREAD

**Issue by isaif** [brookhong/Surfingkeys#1829]
## Prelude
* Could you find answer in below documents? No

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes

## Error details

SurfingKeys: 1.0.8

Browser: Version 104.0.5112.79 (Official Build) (64-bit) Manjaro linux

## Context

Ctrl-n opens new window in chrome so I can't use this to cycle through candidates populated in omnibar.

Is there a way to make chrome pass this to surfingkeys instead?

**Comment by brookhong** [comment]
It is impossible for the extension itself to achieve that since `Ctrl-n` is a shortcut keystroke from Chrome. Please see https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html

**Comment by dansdantas** [comment]
If anyone is seeing this, on brave browser you can disable default system shortcuts in brave://settings/system/shortcuts.
