### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by yahuudang** [brookhong/Surfingkeys#1830]
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

URL: https://www.youtube.com/watch?v=42zVjsOvfmg

## Context

**最近在多个社交网站上评论时，经常会崩溃，不管是微博还是YouTube，只要是在输入框内输入内容，就可能崩溃**

**Comment by Imymirror** [comment]
(probably) Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800
