### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by dmfay** [brookhong/Surfingkeys#184]
## Error details

Modes in stack: Disabled,Insert,Normal

## Context

I have SurfingKeys disabled for a pinned JIRA tab in Vivaldi. The error message displayed when I was writing a comment in a textarea in the issue reassignment modal.

**Comment by brookhong** [comment]
There were same issues reported, please see #178 #181. It should be fixed in 0.7.0.

**Comment by dmfay** [comment]
ah! I just saw the notification to submit an issue and didn't think to look first, no worries.
