### ISSUE TITLE
Remaps without success

### ISSUE THREAD

**Issue by navakelvin** [brookhong/Surfingkeys#1846]
# Case 1
I want in visual mode caret "L" to select until the end of the line.

That is, do something like: v (to go from caret mode to range mode) and then $. Is this possible? Basically I want to speed up placing the caret on a character and selecting to the end.

I have tried this way without success:
`api.vmap('L', "v$");`

# Case 2
I want to remap Alt-o to launch Ctrl-k on Github and it will access the command palette. Possible?

What I have tried without success:

`api.map('<Alt-o>', '<Ctrl-k>', /.*github.*/i)`

Show me the way :)

**Comment by brookhong** [comment]
For your 1st case, it should be

    api.vmap("L", '$');
    
For 2nd case, it is impossible since `Ctrl-k` is not defined by Surfingkeys. But you can enter ephemeral PassThrough mode with `p`, then press `Ctrl-k` to call the action from github. See https://github.com/brookhong/Surfingkeys#passthrough-mode

**Comment by navakelvin** [comment]
> For your 1st case, it should be
> 
> ```
> api.vmap("L", '$');
> ```
> 
> For 2nd case, it is impossible since `Ctrl-k` is not defined by Surfingkeys. But you can enter ephemeral PassThrough mode with `p`, then press `Ctrl-k` to call the action from github. See https://github.com/brookhong/Surfingkeys#passthrough-mode

The first case works. However, so does not support setting a key sequence as final execution.
