### ISSUE TITLE
How to remap the "s" key for searching selected text?

### ISSUE THREAD

**Issue by franticnerd** [brookhong/Surfingkeys#1847]
I was trying to remap the search selected key from "s" to "f", so that I can for example use "fg" instead of "sg" to search on Google. 

I tried both of the following, but neither of them works: 

map("f", "s");
vmap("f", "s");

Is there any way I can change this default search key "s"?

**Comment by brookhong** [comment]
Now `map` does not work like that, there is no action bound with `s`, though there is `sg`, so it is impossible to remap the `s` key, but you can use below to remap `sg`

    map("<Ctrl-j>", "sg")

or

    api.vunmap('f'); // f is bound with the action to forward to next char in visual mode, we need unmap it first.
    api.unmap('f'); // f is bound with the action to follow links in normal mode, we need unmap it first.
    api.addSearchAlias('g', 'google', 'https://www.google.com/search?q=', 'f', 'https://www.google.com/complete/search?client=chrome-omni&gs_ri=chrome-ext&oit=1&cp=1&pgcl=7&q=', function(response) {
        var res = JSON.parse(response.text);
        return res[1];
    }); // please note the 4th parameter.

**Comment by franticnerd** [comment]
Got it, thanks for your answer. I am using 0.9.74 on firefox, confirms that a slight tweak using the old API works:

vunmap('f'); // f is bound with the action to forward to next char in visual mode, we need unmap it first.
unmap('f'); // f is bound with the action to follow links in normal mode, we need unmap it first.
addSearchAliasX('g', 'google', 'https://www.google.com/search?q=', 'f', 'https://www.google.com/complete/search?client=chrome-omni&gs_ri=chrome-ext&oit=1&cp=1&pgcl=7&q=', function(response) {
    var res = JSON.parse(response.text);
    return res[1];
}); // please note the 4th parameter.
