### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by dlee075** [brookhong/Surfingkeys#185]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Please state

1. on which site, you're having this issue?
2. What did you do before the popup showed?

Thanks

**Comment by brookhong** [comment]
Fixed in 0.7.6
