### ISSUE TITLE
Dead link on README for "Add search alias"

### ISSUE THREAD

**Issue by janacm** [brookhong/Surfingkeys#1852]
https://github.com/brookhong/Surfingkeys#add-search-alias-to-omnibar 

This link is broken, and hyperlinked in the README.MD.

**Comment by chasing-freedom** [comment]
The right link is [addsearchalias](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#addsearchalias) in the https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md

**Comment by brookhong** [comment]
Thanks, fixed.
