### ISSUE TITLE
Uh-oh! The SurfingKeys extension encountered a bug.（Mode Insert pushed into mode stack again.）

### ISSUE THREAD

**Issue by ling-zhou** [brookhong/Surfingkeys#1854]
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

URL: https://www.google.com.hk/search?q=difference+between+coroutine+and+thread&newwindow=1&sxsrf=ALiCzsai5BQw6EJrP6_2uZnvqFe8terQqw%3A1665310171949&source=hp&ei=251CY_WHN5m_wAOX54KQDA&iflsig=AJiK0e8AAAAAY0Kr61cxprRt730470AERtVZ9wPV87LQ&oq=difference+&gs_lcp=Cgdnd3Mtd2l6EAEYADIFCAAQkQIyBQgAEJECMgUIABCRAjIFCAAQkQIyBQgAEIAEMggIABCABBCxAzIFCAAQgAQyCwgAEIAEELEDEIMBMgUIABCABDIFCAAQgAQ6BwgjEOoCECc6BAgjECc6CwgAELEDEIMBEJECOggILhCxAxCDAToOCC4QgAQQsQMQxwEQ0QM6DgguEIAEELEDEIMBENQCOgsILhCABBCxAxCDAToICAAQsQMQgwE6EQguEIAEELEDEMcBEK8BENQCOhEILhCABBCxAxCDARDHARCvAToICC4QgAQQsQM6CwguEIAEELEDENQCOgYIABAKEAM6BwguEIAEEAo6EAguEIAEEMcBENEDENQCEAo6BwgAEIAEEAo6FgguEIAEELEDEIMBEMcBEK8BENQCEAo6DQguEIAEEMcBEK8BEAo6EQguEIAEELEDEIMBEMcBENEDOg4ILhCABBDHARDRAxDUAjoECAAQAzoICAAQgAQQ5QQ6DQgAEIAEELEDEIMBEAo6FgguEIAEELEDEIMBEMcBENEDENQCEAo6EQguELEDEIMBEMcBENEDENQCOggIABCxAxCRAjoKCC4QgAQQsQMQClDTFViaUWCxkAFoDHAAeACAAWSIAeALkgEEMTguMZgBAKABAbABCg&sclient=gws-wiz

## Context

**
![image](https://user-images.githubusercontent.com/5524121/194750951-443718bb-3438-4135-93e1-7e2e3790e320.png)

当我输入一些字符，然后在输入框点击鼠标时出现了错误提示，在其他一些场景，比如腾讯文档也经常遇到。

When I enter some characters and click the mouse in the input box, an error message appears, which is often encountered in other scenarios, such as Tencent documents.

**

**Comment by zqni** [comment]
Run across the same warning many times recently. My SurfingKeys version is 1.0.9 and my Chromsome  version is 106.0.5249.103.

**Comment by Inginn** [comment]
and this borks your  text you have put in, so you cant even copy it to input in after a refresh.

**Comment by Inginn** [comment]
if you hold shift you can copy the text so you dont loose it at least.

**Comment by navakelvin** [comment]
Same. This happens to me many times.

**Comment by alex-courtis** [comment]
Occurs often on github issue and pull request pages.

**Comment by jdhao** [comment]
Same for me, occurs randomly for the text input area when I use the mouse to focus to the text input area, super annoying...

**Comment by GragonL** [comment]
当我出现这个问题时，我看到了这样的错误，不知道是否有用
![截屏2022-10-21 08 57 34](https://user-images.githubusercontent.com/30513470/197087201-03d729c0-05c8-4b23-a1ca-a890739bcda3.png)
<img width="739" alt="截屏2022-10-21 08 57 45" src="https://user-images.githubusercontent.com/30513470/197087207-3486602e-8cb9-4a16-ba94-9954a35b14b6.png">
<img width="1217" alt="截屏2022-10-21 08 58 13" src="https://user-images.githubusercontent.com/30513470/197087209-b981a9d8-9a44-45e8-b1ed-b1b9aa483e0c.png">

**Comment by brookhong** [comment]
The issue should be fixed in 1.1.0, but it is pending on CWS review for 6 days. Please wait for the update from CWS.
