### ISSUE TITLE
How to download PDF in Surfingkeys viewer?

### ISSUE THREAD

**Issue by navakelvin** [brookhong/Surfingkeys#1856]
I can't find a way to download PDF from the viewer.

Is there a button, command or key shortcut?

PS: At the moment i use the Ctrl+p browser option to print in pdf format. However, i would like to know if Surfingkeys had it own procedure.

**Comment by aasutossh** [comment]
For the moment what I do is, disable the surfingkeys, `chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html?r=https://www.path.to/file.pdf` remove the `chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html?r=` which opens the default pdf viewer of chromium.

**Comment by brookhong** [comment]
`;s` to disable the pdf viewer from Surfingkeys.
