### ISSUE TITLE
有方法可以map macOS上的cmd键吗

### ISSUE THREAD

**Issue by jheroy** [brookhong/Surfingkeys#1859]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: 1.0.6

Browser: Firefox 105.0.3, macOS 12.3

URL: all
## Context
我试了
```
map('go', '<Command-l>');
map('go', '<command-l>');
map('go', '<Cmd-l>');
map('go', '<cmd-l>');
```
都不行

**Comment by brookhong** [comment]
这个`Command-l`不是surfingkeys提供的，无法通过map映射，这个将来可能会通过定制版的Chromium来支持。

**Comment by jheroy** [comment]
> 这个`Command-l`不是surfingkeys提供的，无法通过map映射，这个将来可能会通过定制版的Chromium来支持。

多谢回复.  定制版的Chromium可以提供一个自动隐藏标签栏和地址栏的功能吗, firefox可以用userChrome.css来实现, 但chromium不支持. 具体效果是默认情况不显示任何ui,基本上所有的操作都能surfingkeys来操作, 但是如果有必要的话可以用`command-l`把焦点放到地址栏的时候自动显示地址栏和标签栏. 实在不想用chromium的标签和地址栏, 有了surfingskeys后除了占用显示面积外没啥用处.
