### ISSUE TITLE
Firefox version in addon store is much older than Chrome's

### ISSUE THREAD

**Issue by sethidden** [brookhong/Surfingkeys#1862]
The latest Firefox version of Surfingkeys is 1.0.6 but Chrome Surfingkeys is 1.0.9

Could you please push the latest release (1.1.0 or 1.0.9) to the Firefox addon store?

Firefox:
![image](https://user-images.githubusercontent.com/5359825/195435487-2a3411cc-5bad-4450-9845-cd8b21235f3f.png)
Chrome:
![image](https://user-images.githubusercontent.com/5359825/195435537-b84a92c1-52fd-424b-a15f-e01f1237a121.png)

**Comment by Stanpol** [comment]
Same with the Safari version, 1.0.6 in the app store as of today.
