### ISSUE TITLE
blank page for neovim

### ISSUE THREAD

**Issue by cliffxuan** [brookhong/Surfingkeys#1863]
First, thanks very much for making this awesome plugin.

I set up neovim integration in my Chrome on the Mac by following this guide https://github.com/brookhong/Surfingkeys/blob/master/src/nvim/server/Readme.md . 

I'm almost certain all steps are properly followed, however, It's showing a blank page.

It's probably something obvious that I've missed, but I cannot figure it out. Any help from anyone is really appreciated.

- neovim version: 0.8
- Chrome version: 106.0.5249.119

- nvim process is launched by chrome
<img width="1052" alt="Screenshot 2022-10-20 at 23 31 38" src="https://user-images.githubusercontent.com/640204/197072471-a7f121b5-91f0-4b86-94dc-de4ef7cd64cf.png">

- logs are written out
<img width="433" alt="Screenshot 2022-10-20 at 23 32 12" src="https://user-images.githubusercontent.com/640204/197072478-621e9e61-00d9-411b-8ef3-28f08be4db3a.png">

- the neovim page is blank and no error in the console
<img width="1194" alt="Screenshot 2022-10-20 at 23 33 28" src="https://user-images.githubusercontent.com/640204/197072479-a2551ce4-6e7a-4f3a-943a-019e2d69194f.png">

**Comment by brookhong** [comment]
Please update your server.lua file, which should fix the issue.

**Comment by cliffxuan** [comment]
I can confirm this fix works. It feels really nice to run neovim inside Chrome. Thanks a lot.
<img width="753" alt="neovim-in-chrome" src="https://user-images.githubusercontent.com/640204/204106393-358e7b96-da67-4f0d-ab9d-41cd007e741f.png">
