### ISSUE TITLE
Use / to search for a full white screen

### ISSUE THREAD

**Issue by AeonWorks** [brookhong/Surfingkeys#1867]
## Error details

Use / to search for a full white screen.

SurfingKeys: 1.0.3

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Could you please provide more information about this issue?

**Comment by AeonWorks** [comment]
I have updated to the M1 version of MBP and then found out that there is a new paid version (1.11) which I have repurchased and the problem is no longer present.
