### ISSUE TITLE
Stop the emojis!

### ISSUE THREAD

**Issue by EvanCarroll** [brookhong/Surfingkeys#1869]
That I can't type `09:00 ` without accidentally doing `09😀` is incredibly annoying. Please reconsider this functionality and interface.

For one example of a bug with this feature type `:sweat` right in a comment in GitHub comment you'll see it twice.

![Screenshot_2022-10-26_21-47-48](https://user-images.githubusercontent.com/19922/198179133-e2d45208-938c-431b-a2b2-735b3967c06e.png)

For another example of this feature messing up, see this video. Notice I'm clicking on it too to try to close the window but the click event isn't received reliably. Also, notice it persists until the page is hard-reloaded.

https://user-images.githubusercontent.com/19922/198179946-7eca872d-e345-4e99-8351-910fbbcf35fe.mp4

**Comment by jyungtong** [comment]
Yeah, very annoying, I added `iunmap(":");` in settings

**Comment by EvanCarroll** [comment]
> Yeah, very annoying, I added `iunmap(":");` in settings

I'm getting with that.

```
[SurfingKeys] Error found in settings: ReferenceError: iunmap is not defined
```

**Comment by jyungtong** [comment]
try `api.iunmap(":");`

**Comment by EvanCarroll** [comment]
Lol, that should have been obvious to me. Thanks @jyungtong. That's a good work around. I'll leave the issue open though: I'd still like to see this feature opt-in or removed. It's super annoying, buggy, and confusing for new users. Let @brookhong decide what to do with it.

**Comment by brookhong** [comment]
It does make trouble sometimes, I'll make it off by default.
