### ISSUE TITLE
Auto focusing not working on some pages

### ISSUE THREAD

**Issue by ligyxy** [brookhong/Surfingkeys#187]
The best example is translate.google.com, that it should have auto-focusing on the input field. Looks like this extension prevents it from working so.

**Comment by brookhong** [comment]
Yes, it is working as designed by Surfingkeys.

Disabling auto-focusing on page load help us to enter `Normal` mode directly, so that we could use most binding keys without pressing `<Esc>` to quit `Insert` mode.

**Comment by ligyxy** [comment]
For people who have the same "issue", you can do 
`settings.stealFocusOnLoad = false;`
if you need auto-focusing.
