### ISSUE TITLE
I cannot type options' characters

### ISSUE THREAD

**Issue by ghegheg** [brookhong/Surfingkeys#1874]
## Error details

SurfingKeys: 1.0.9

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context
Hi
I cannot change Surfingkeys' options in Chrome and Firefox because after open one options I can't change option's character.

**Comment by brookhong** [comment]
Should have been fixed in 1.12.
