### ISSUE TITLE
Trying to keybind "Alt-i" for pass through mode fails

### ISSUE THREAD

**Issue by Archie-2021** [brookhong/Surfingkeys#1875]
## Error details

SurfingKeys: 1.0.9 Brave
OS: EndeavourOS

Browser: Version 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit) , Endeavour
URL: <The_URL_Where_You_Find_The_Issue>

## Context

I am trying to keybind `<alt-i>` to another key but it doesn't work. I binded it to `za` right now but it shows blank i z menu:

```
api.mapkey('za' , '<alt-i>');
```

![image](https://user-images.githubusercontent.com/85870778/199050167-e3186d0d-fd3e-4839-bb2b-e3cd29749827.png)

It is so simple and I can't find a basic mistake , so I wonder it is related to binding keys to Alt key or maybe keybinding of "pass through mode" related.

**Comment by brookhong** [comment]
It should be 

    api.map('za', "<Alt-i>");

**Comment by Archie-2021** [comment]
> 

Thanks, Works like a charm. What is the difference between api.map and api.mapkey that causes this issue?

**Comment by brookhong** [comment]
`mapkey` is to create a shortcut with a new function, please see https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#mapkey, while `map` is just to change the keystroke for the original function.
