### ISSUE TITLE
Page does not scroll until after reload

### ISSUE THREAD

**Issue by ariel-frischer** [brookhong/Surfingkeys#1880]
## Error details

SurfingKeys: 1.1.0

Browser: Brave - [Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)]><MacOs 12.6 Monterey>

URL: [<https://zapier.com/blog/hyperlink-in-slack/>]

## Context

Just go to the page and try to scroll it does not work for me. I do see a console error:
<img width="545" alt="Screen Shot 2022-11-02 at 9 07 34 PM" src="https://user-images.githubusercontent.com/19893395/199645826-c0db62ba-7320-4fdc-a300-e0d08d8c3873.png">

If I refresh page it works, but I've seen this issue on multiple pages now.

**Comment by brookhong** [comment]
Can not reproduce it.
