### ISSUE TITLE
Cant remap keys in Orion browser after installing ventura, before that everythign worked fine.

### ISSUE THREAD

**Issue by xsykkox** [brookhong/Surfingkeys#1881]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys: <1.1.0>

Browser: <Version 0.99.121.1-beta (WebKit 614.1.20)><Ventura 13.0>

URL: <The option menu of Surfing keys>

## Context

Well, everything worked fine on monterey, after downloading ventura, everytime i want to change a key in the options, surfing keys is triggered and i cant write it. If i click on a key with no surfing keys command the key appears normaly in that little bracket. For example (,). I tried to dissable surfing keys but then i couldn delete nor write any key at all. On my macbook pro. Macos Monterey 12.6 with surfing keys 1.0.8 everything works fine just like with my macmini before the ventura update. Please help, i love this app so much and dont want to lose my workflow

**Comment by brookhong** [comment]
Should have been fixed in 1.12.

**Comment by tonyspiff** [comment]
Which extension should be user for Orion? The Chrome or the Firefox one? Is there any documentation or discussions around the integration with Orion? Thanks!
