### ISSUE TITLE
Yanking fails on some pages?

### ISSUE THREAD

**Issue by for-coursera** [brookhong/Surfingkeys#1882]
The page in question: http://rutor.is/ (it's a Russian torrent tracker, and sorry, it looks like hell, but unfortunately, I still use it...)

Any mapping related to yanking simply fails. For instance, if I press `yy`, Surfingkeys capture the first `y`, show a menu with the suggestions, but then I press the second `y` and nothing happens.

Other mappings (and re-mappings) seem to work, I tried both with the default config and also with my own config. Yanking on other pages works, too. Can reproduce both in Firefox and Brave. Tried both with uBlock origin on and off.

They probably have something on that page that breaks / blocks certain parts of Surfingkeys code? Any ideas may be how to fix it? Would be soo grateful :)

Surfingkeys v.1.1.1.

Firefox v.106.0.4.

**Comment by yaohappiness** [comment]
I had a similar problem. It seems a problem about "Permissions in Cross-Origin Iframes". It happens when the current frame and the main frame are cross site origins.

v1.0.9 don't have this problem. It should be caused by the commit [936edff](https://github.com/brookhong/Surfingkeys/commit/936edff32771338fd3ee031d43791d0487cb8c50).

Error message:

> DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.

[This link](https://www.runoob.com/try/try.php?filename=tryjs_postMessage) shows an example. It contains a cross origin frame. And the ad at the bottom of the page is also a cross origin frame. See picture below.

![Screenshots 2022-11-06 193744](https://user-images.githubusercontent.com/38402135/200174501-6054a024-2b06-4e8d-930f-c1d689cfbb38.png)

**Comment by 097115** [comment]
Thanks for the confirmation! Great to know I'm not the only one with that rubbish site :)

(With this policy of constant updates we can't downgrade while this being fixed? With Firefox, as I recall, you can disable updates for the installed extensions, but as for Chrome, there's nothing we can do, I think?)

**Comment by brookhong** [comment]
Thanks @for-coursera and @yaohappiness for the information, looks like we need revert that commit.

**Comment by yaohappiness** [comment]
> With this policy of constant updates we can't downgrade while this being fixed? With Firefox, as I recall, you can disable updates for the installed extensions, but as for Chrome, there's nothing we can do, I think?

Get an history version of the extension, e.g. this site <https://www.crx4chrome.com>. Unzip the crx extension file, and open the Developer mode on `chrome://extensions/`, and then click "Load unpacked" button to manually load the unzipped extension.

On Windows, I revoked the write permissions of Surfingkeys plugin directory which also works.

**Comment by clarkwang** [comment]
Also hit `yy` issues with v1.1.0 on Chrome.

**Comment by biteliang** [comment]
感谢Surfingkeys的作者.

**Comment by biteliang** [comment]
> > 有了这种不断更新的政策，我们不能在修复此问题时降级吗？我记得，使用 Firefox，您可以禁用已安装扩展程序的更新，但至于 Chrome，我认为我们无能为力？
> 
> 获取扩展的历史记录版本，例如此站点https://www.crx4chrome.com。解压缩crx扩展文件，打开开发人员模式，然后单击“加载解压缩”按钮手动加载解压缩的扩展名。`chrome://extensions/`
> 
> 在Windows上，我撤销了冲浪键插件目录的写入权限，该目录也可以工作。

Good idea

> > With this policy of constant updates we can't downgrade while this being fixed? With Firefox, as I recall, you can disable updates for the installed extensions, but as for Chrome, there's nothing we can do, I think?
> 
> Get an history version of the extension, e.g. this site https://www.crx4chrome.com. Unzip the crx extension file, and open the Developer mode on `chrome://extensions/`, and then click "Load unpacked" button to manually load the unzipped extension.
> 
> On Windows, I revoked the write permissions of Surfingkeys plugin directory which also works.

Good idea

**Comment by brookhong** [comment]
Fixed in 1.12.
