### ISSUE TITLE
Is there easy way to switch from visual range mode to visual caret mode?

### ISSUE THREAD

**Issue by yuyang0** [brookhong/Surfingkeys#1884]
I want to switch from visual range mode to visual caret mode in my config file. I've tried to dispatch the `<ESC>` keyboard event to window, but no luck. so is there any easy way to do this? thanks in advance.

**Comment by brookhong** [comment]
There is no easy way to do that so far, you can refer to https://github.com/brookhong/Surfingkeys/blob/master/src/content_scripts/common/visual.js#L641 and see if there is a hack way.

Just curious why you need this in config file, and how do you enter visual range mode in config file?

**Comment by yuyang0** [comment]
I want to integrate surfingkeys with SalaDict. In order to invoke SalaDict, I need enter visual mode and then navigate to the word i want to translate and then press `<q>` which bind to a custom function in my config.

```js
const invokeSalaDict = () => {

  // if saladict panel is opened, close it
  let saladict = document.querySelector("div.saladict-panel")
  if (saladict !== null) {
    document.querySelector("#saladict-dictpanel-root > div").shadowRoot.querySelector("div.dictPanel-Head button[title='关闭查词面板']").click()

    //TODO switch from visual range mode to visual caret mode.
    return
  }

  const sel = document.getSelection();
  let wordRng = util.getNearestWord(sel.focusNode.textContent, sel.focusOffset);
  let sOffset = wordRng[0]
  let eOffset = wordRng[0] + wordRng[1]
  let rng = document.createRange();
  rng.setStart(sel.anchorNode, sOffset);
  rng.setEnd(sel.focusNode, eOffset);
  sel.removeAllRanges();
  sel.addRange(rng);


  let cursor = document.querySelector("div.surfingkeys_cursor");
  let left = parseFloat(cursor.style.left);
  let top = parseFloat(cursor.style.top);
  let height = parseFloat(cursor.style.height);
  let fixedNodes = document.elementsFromPoint(left, top);
  let node = cursor;
  if (fixedNodes.length >= 2) {
    node = fixedNodes[1];
  }

  let downEvt = new MouseEvent('mousedown', {
    clientX: left,
    clientY: top + height / 2,
  });
  let upEvt = new MouseEvent('mouseup', {
    clientX: left,
    clientY: top + height / 2,
  });
  let clickEvt = new MouseEvent('click', {
    clientX: left,
    clientY: top + height / 2,
  });
  let dblClickEvt = new MouseEvent('dblclick', {
    clientX: left,
    clientY: top + height / 2,
  });
  // simulate double click
  node.dispatchEvent(downEvt);
  node.dispatchEvent(upEvt);
  node.dispatchEvent(clickEvt);
  node.dispatchEvent(downEvt);
  node.dispatchEvent(upEvt);
  node.dispatchEvent(clickEvt);
  node.dispatchEvent(dblClickEvt);
}
```
As you've seen, this function selects the word under the cursor and then simulates doubleclick. After finished query, press `<q>` to call this function again, it will close SalaDict panel and I also want to collapse the selection and switch to visual caret mode.

**Comment by yuyang0** [comment]
I registered a keyup listener to `document.body` and close SalaDict pannel in event callback. so pressing `<Esc>` can switch to visual caret mode and close SalaDict panel.
