### ISSUE TITLE
Restore closed tab is missing in Safari

### ISSUE THREAD

**Issue by m-zheng** [brookhong/Surfingkeys#1885]
The command "X" used to restore closed tab is missing in Safari. Is there any way to add it?

Alternatively, is there any way to map "X" to send key strokes "Command + Shift + t" so that I can reopen previously closed tabs in the order they were closed.

SurfingKeys: 1.1.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

**Comment by m-zheng** [comment]
I have tried `api.map('X', '<Meta-Shift-t>');`. But it does not work somehow.

**Comment by brookhong** [comment]
It is impossible to create a map to a shortcut from the browser itself. As to restore closed tab in Safari, the function is not available so far, as it depends on a web extension API which is not supported by Safari now.

Unfortunately, this issue can only be fixed after Safari supports `chrome.sessions.restore`. Now you can use `Command-z` from Safari as work around.
