### ISSUE TITLE
Shift + T - doesn't list recently used tabs - but orders the list in incremental order.

### ISSUE THREAD

**Issue by AlexIvasi** [brookhong/Surfingkeys#19]
Shift + T - modifier that lists opened tabs doesn't list tabs in recently viewed order as in Vimimum 
Steps to reproduce:
1. Imagine your have 10 tabs in your browser 
2. Switch / view tabs in following order 8, 9, 10 (10 would be the latest tab that you viewed)
3. Now press Shift + T to list your opened tabs - you would expect that tabs list is populated in the following order - as in Vimium - thus pressing one time shift + enter will bring you to tab number 9.
What is the problem ?  the problem that it lists the tabs in the following order 1.2.3.4.5.6.7.8.9.10 and not in recently used order.

10
9
8

p.s. Again your extension is the best - but still some issues like this bug persists - please, fix it once your get time for it.

**Comment by zldrq** [comment]
i confirm this. but because i rearranged windows, i'm not sure about the order at all. at least it is not recently used order for sure

and while i'm here, are you planning to implement favicons for tabs? it'd be cool!

**Comment by brookhong** [comment]
thanks @zldrq 

To have favicons in tabs overlay is a good idea, I implemented it, and will be in next release.

**Comment by brookhong** [comment]
Thanks guys, fixed in 0.3.0, please have a try.

**Comment by AlexIvasi** [comment]
Hi Brook, thanks for the fix. 
Just tested it. It works - Tabs are listed now in MRU mode (Most Recently Used) mode.

However instead of tab icons it display's a special character - refer to attached file.
Not sure whether you included your tab icons feature in that release as well.

Many thanks for keeping it up to date.
Great Work!

![screenshot - 12_29_2015 4_29_28 pm](https://cloud.githubusercontent.com/assets/16400983/12036878/423e67e2-ae4a-11e5-9b48-7dc45169fe5b.jpg)
