### ISSUE TITLE
Losing focus when searching/creating watch list in Youtube

### ISSUE THREAD

**Issue by ligyxy** [brookhong/Surfingkeys#190]
https://cl.ly/1O3l3Y2y2T3G

It keeps losing focus when typing an existed list in the input field above. That is "Add to" button of Youtube page.

I wonder if that is caused by the fix of issue [#173](https://github.com/brookhong/Surfingkeys/issues/173), since I have to wait about half a second to input next letter, if it returns at least one search result. 

https://cl.ly/3p0c0T3n460o

If you take a look of the screen record above, the second letter 'o' was not input into the field, but into some other mode and appears on the bottom right black popup.

**Comment by brookhong** [comment]
Thanks for reporting this.

I looked into your screen record, and verified it on youtube.

This seems to be a feature of youtube itself, when there are matched, it will blur the input, and let user to select a option in the list.

You could disable Surfingkeys thoroughly from chrome://extensions/, then verify it. 

Fix of #173 is just to keep Surfingkeys from breaking original event handler of INPUT.

**Comment by ligyxy** [comment]
Just confirmed it, that youtube will select an option when there is a match. However, the cursor is still in the input field, so you can continue typing immediately.

I've also checked how cVim and Vimium work in the same page, and both of them, as well as Surfingkeys, make it impossible to continue typing in a short time.
