### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by gou4shi1** [brookhong/Surfingkeys#1903]
## Error details

Modes in stack: mappingsEditor,Insert,Normal

SurfingKeys: 1.12

Chrome: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0

URL: moz-extension://016fa831-9100-4a48-ba5a-d9245e4267b6/pages/options.html

## Context
![image](https://user-images.githubusercontent.com/16915589/202997060-ffd23e1a-bda8-4966-9d4d-43d429335a67.png)

**Comment by brookhong** [comment]
Fixed in 1.13.0
