### ISSUE TITLE
codeforces.com is broken when extension is active

### ISSUE THREAD

**Issue by Ventu06** [brookhong/Surfingkeys#1906]
## Error details

When this extension is active, the site [Codeforces](https://codeforces.com) appears as a totally blank page.
To render the page correctly it is not enough to disable SurfingKeys from the button provided by the extension, but it's necessary to disable the extension from Firefox settings.

## Version info

SurfingKeys: 1.12

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

## SurfingKeys settings

settings.hintAlign = "left";

**Comment by 383494** [comment]
the issue remains for me :(
