### ISSUE TITLE
Fail to copy url into clipboard occasionally

### ISSUE THREAD

**Issue by hiberabyss** [brookhong/Surfingkeys#191]
Sometimes, after press `yy`, the current page's url is failed to be copied into clipboard. After open chrome javascript console, following errors are always shown.

![image](https://cloud.githubusercontent.com/assets/2898670/21959095/d0f598e4-da8a-11e6-93b0-1e6fdd601a23.png)

Thanks!

**Comment by axs221** [comment]
@hiberabyss I wasn't able to reproduce so far. Can you provide more context? I see it mention "cdn.github.com", so I am assuming you were on Github at the time? Are there any steps we can try to reproduce?

**Comment by hiberabyss** [comment]
I could not reproduce the issue because it occurred randomly. I will update if there is a way to reproduce the problem. Thanks!
