### ISSUE TITLE
Broken Website 

### ISSUE THREAD

**Issue by kings2u** [brookhong/Surfingkeys#1913]
# Error details

When this extension is active, [this site](https://pubapps.utcourts.gov/XchangeWEB/XchangeWebServlet) does not load.
To render the page correctly it is not enough to disable SurfingKeys from the button provided by the extension, but it's necessary to disable the extension from Firefox settings.

# Version info
SurfingKeys: 1.12
Browser: Mozilla 107.0 on Windows

**Comment by brookhong** [comment]
Should have been fixed in 1.15.
<img width="1153" alt="image" src="https://github.com/brookhong/Surfingkeys/assets/288207/f28ccd54-5b4f-4ff1-908f-f2344effcf1e">
