### ISSUE TITLE
Privacy ?

### ISSUE THREAD

**Issue by htammen** [brookhong/Surfingkeys#1917]
Hi,
your extension is really a great tool but I'm curious if you respect my privacy. Cause the extension get's information about everything I'm doing in the browser I would like to know if any of these informations and which ones are send to any server on the internet.

Best regards
Helmut

**Comment by brookhong** [comment]
Thanks for asking.

The extension does not collect any data, which means none of your data will be sent to any server. You can look into the source code, also you can use `network` from `Inspect` tool of your browser to inspect all the network requests.

**Comment by htammen** [comment]
Thank you very much for the answer
