### ISSUE TITLE
Can not edit advanced settings

### ISSUE THREAD

**Issue by matleh** [brookhong/Surfingkeys#1920]
## Error details

SurfingKeys: 1.12

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context

When I try to edit the advanced settings, after a few seconds an error overlay appears which says "Uh-oh! The SurfingKeys extension encountered a bug."

The console shows two errors:

- Refused to load the script 'chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/worker-javascript.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

-Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/worker-javascript.js' failed to load.
  
Seems to be some CSP misconfiguration?

**Comment by agomez225** [comment]
Having this same issue; unsure of what to do

**Comment by kzhang2** [comment]
Having the same issue.

**Comment by Tback1** [comment]
Having the same issus
even try a new install and profile it's still exist

**Comment by fengyeyer** [comment]
Having the same issue.

**Comment by piersolenski** [comment]
Getting the same error on Brave

**Comment by brookhong** [comment]
The error from console should not stop you from editing advanced settings.
