### ISSUE TITLE
how to disable surfingkeys only in some page?

### ISSUE THREAD

**Issue by XGHeaven** [brookhong/Surfingkeys#193]
with cVim or vimium, you can disable it in some page, such as github,evernote,etc..

but how to do this in surfingkeys? I only find `disable surfingkeys` not `disable surfingkeys in this page`

**Comment by axs221** [comment]
@XGHeaven Have you looked at the blacklist settings?

You can press "Alt+s" or enter it in the settings file.
https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys

It probably makes sense to make it an open in the icon menu. I might take a look at implementing that.

**Comment by XGHeaven** [comment]
Thanks.

I suggest that add `alt-s` to `usage` page. So people can find that key~~~ :)

**Comment by axs221** [comment]
@XGHeaven Good thinking, it looks like @brookhong added here:
https://github.com/brookhong/Surfingkeys/commit/63f6dbfccffbe67eeb1ad50dfdc3265b006e4847

![image](https://cloud.githubusercontent.com/assets/607938/22029086/70fc80dc-dca7-11e6-843c-d84e6afa0d85.png)
