### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by collinder** [brookhong/Surfingkeys#1943]
## Error details

Modes in stack: mappingsEditor,Insert,Normal

SurfingKeys: 1.12

Chrome: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0

URL: moz-extension://a4a29230-05b1-4ed0-b7ae-abff53413a21/pages/options.html

## Context
In settings:
If i try  to make selection or to somewhat innacurately click on editor to gain focus with mouse, it will crash. If i try to use right-click menu, it will crash. 

Suggestion to avoid problems with reliance on in-browser settings editor:
make command to yank settings to clipboard more visible for troubleshooting - on README
make command to replace current settings with clipboard content. Ofc only for advanced users.

**Comment by brookhong** [comment]
Fixed in 1.13.0
