### ISSUE TITLE
Unmap 'd' for a domain but still allow it for some fixed pages on this domain?

### ISSUE THREAD

**Issue by 097115** [brookhong/Surfingkeys#1945]
So, in my config I can do something like this:

    unmap('d', /domain\.com/);

But what if I still want `d` to work on `https://domain.com/foo/bar/page.html`? Can I have both, is it doable? :)

Thank you.

**Comment by brookhong** [comment]
You can write a regex to match only the pages on which you want to disable `d` from Surfingkeys, and use it as the second parameter of `unmap`.

**Comment by 097115** [comment]
@brookhong 

Thank you for your reply! My point was more like:

  - first unmap it for the whole domain
  - and them re-map it to deleting a tab only for some strict regexes

But then, what function to put into `mapkey` directive? :)

(Sorry, it's probably not `d` but `x` by default, remapped it so long ago that didn't even remember that right mapping at first :)
