### ISSUE TITLE
一些小bugs：搜索引擎图标错误；添加搜索引擎的相关功能失效；帮助文档的小错误。

### ISSUE THREAD

**Issue by draftman9** [brookhong/Surfingkeys#1946]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

Even not mentioned.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
yes

## Error details

SurfingKeys: 1.12

Browser: 星愿8.3.1000.2207 ( Chromium: 98.0.4758.139 Res: 2207.536 ) （64 位）

## Context

**Please replace this with a description of how you were using SurfingKeys.**

我往键`b`添加/更改为了cn.bing.com的搜索引擎，但是它的图标还是百度的。往键`l`添加了deepl.com，但是`sl`却不起效。

另外：[README_CN.md这里](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E6%90%9C%E7%B4%A2%E9%80%89%E4%B8%AD%E6%96%87%E6%9C%AC)还是`addSearchAliasX`，需要改过来吧。

**Comment by brookhong** [comment]
图标没更新，可以进Surfingkeys设置页面，打开开发者工具，如下图，删除对应的条目

<img width="920" alt="image" src="https://user-images.githubusercontent.com/288207/218490802-4ed2e96e-8892-4a26-941b-8156ab5502a4.png">

试试这样，`sl`在我这边可以用

    addSearchAlias('l', 'bilibili', 'https://search.bilibili.com/all?keyword={0}&from_source=nav_suggest_new');

是的，README里没更新。
