### ISSUE TITLE
页面有链接  按钮无法识别到

### ISSUE THREAD

**Issue by TomYule** [brookhong/Surfingkeys#1950]
## Error details
页面有链接  按钮无法识别到
https://wwnu.lanzouy.com/iskPo0kajv0b
![微信图片_20230217091925](https://user-images.githubusercontent.com/13266764/219525172-5b3e211f-0a07-4f9c-a5be-9a670c058c04.png)

SurfingKeys: 1.12

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
那些链接在一个iframe里面，你需要按`w`切换到相应的frame里，再按`f`.
