### ISSUE TITLE
突然插件不能使用

### ISSUE THREAD

**Issue by lyb200** [brookhong/Surfingkeys#1958]
## Error details

前面使用的好好的，突然在 https://www.jianshu.com/u/aff91a6cd8ab 不能使用了，不知为何？这个图标变暗了。其他页面还可以用。

SurfingKeys: 1.12

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-surfingkeys-only-on-current-site

你应该是不小心按了`Alt-s`。

**Comment by lyb200** [comment]
确实是这个原因，开始我想可以是这个网页我用得太多了。现在解决了。谢谢！！！
