### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by Ravenightwing** [brookhong/Surfingkeys#1962]
## Error details

Modes in stack: mappingsEditor,Insert,Normal

SurfingKeys: 1.12

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context
Once advanced mode is turned on and i want to add or change the configuration, the error message occur.

**Comment by brookhong** [comment]
Fixed in 1.13.0
