### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by Gaaruda** [brookhong/Surfingkeys#1963]
## Error details

Modes in stack: mappingsEditor,Insert,Normal

SurfingKeys: 1.12

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.27

URL: chrome-extension://kgnghhfkloifoabeaobjkgagcecbnppg/pages/options.html

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 1.13.0
