### ISSUE TITLE
Firefox: Unmap <ctrl-h> doesnt work

### ISSUE THREAD

**Issue by GodSaveEarth** [brookhong/Surfingkeys#1973]
Firefox 98.0 with Surfingkeys 1.12

Hi. 

My advanced config is only `api.unmap('<ctrl-h>');` But ctrl-h still acts as default "Mouse over elements". 

How can I debug that? Thanks.

**Comment by brookhong** [comment]
It should be `Ctrl`, instead of `ctrl`.

    api.unmap('<Ctrl-h>');

**Comment by GodSaveEarth** [comment]
I tried both ctrl and Ctrl - nothing helped.
