### ISSUE TITLE
On google search page, `gi` not work

### ISSUE THREAD

**Issue by zhixin-zhao** [brookhong/Surfingkeys#1982]
## Error details
On google search page, `gi` not work while `i` works. 
On other pages, `gi` works fine. 

SurfingKeys: 1.13.0

Browser: chrome

URL: [<The_URL_Where_You_Find_The_Issue>](https://www.google.com/search?q=conda+&sxsrf=APwXEdfBij5vPSo-sVWvYKEbCKiX1xMxSw%3A1681133632117&ei=QBA0ZKLaBp7ekPIPiLanwA8&ved=0ahUKEwii-tjntp_-AhUeL0QIHQjbCfgQ4dUDCA8&uact=5&oq=conda+&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIECCMQJzIECCMQJzIECCMQJzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzIHCAAQigUQQzoKCAAQRxDWBBCwAzoKCAAQigUQsAMQQ0oECEEYAFDtEViXFWC9F2gBcAF4AYABswOIAekFkgEFMy0xLjGYAQCgAQHIAQrAAQE&sclient=gws-wiz-serp)

**Comment by madjxatw** [comment]
same issue here.

**Comment by jiapeng123456** [comment]
same problem
