### ISSUE TITLE
use ACE editor to edit options 

### ISSUE THREAD

**Issue by xcv58** [brookhong/Surfingkeys#2]
It's better than just a text editor.

**Comment by brookhong** [comment]
Thanks @xcv58 

But this seems not be a high priority task, as text editor/syntax highlight is just a nice-to-have feature. As we discussed in another issue #3, `surfingkeys.js` is supposed to be edited in user's favorite editor, like vim/emacs. Synced through cloud service, loaded by a simple map key.

**Comment by xcv58** [comment]
Yes, it's not high priority if we have sync feature.

I will probably make a fork and integrate ACE editor in few days.

**Comment by brookhong** [comment]
Implemented in 0.3.2, use ACE as settings editor(with vim key binding).
