### ISSUE TITLE
window, session -> save as vim-like marks, or even better: as named. 

### ISSUE THREAD

**Issue by zldrq** [brookhong/Surfingkeys#20]
are you planning to implement saving of session/window to be able to open it later from menu, like you have for vim-like marks (with `os` and `ow`)? the only question is how to name them.. for example you may name them from clipboard. or may be straight up give them name while saving.

session is not much needed, but window is needed for sure.

*i was goind to add another request here, but i'll create new issue*

**Comment by brookhong** [comment]
You can create a named session from command mode.

Press `:` to enter command mode, then run

    createSession abc

to create a session named "abc", to open it with command:

    openSession abc
