### ISSUE TITLE
Unrecognized key event: <Meta>

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#200]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 92,
    "code": "ControlRight",
    "composed": true,
    "key": "Meta"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

## Context

I was switching workspaces in the window manager using my `Super_R + ,` key binding.  So actually the error is wrong - the modifier was `Super` not `Meta`.

**Comment by brookhong** [comment]
Thanks for the useful reporting, fixed in 0.7.2
