### ISSUE TITLE
Jump to tab overlay labels below each tab in the tabbar.

### ISSUE THREAD

**Issue by DasOhmoff** [brookhong/Surfingkeys#2001]
Hello, thank you for your nice work with this extension!

This extension is really nice, but there is one feature that I would love to have. Being able to jump to tabs via the tab jump label while also not having to look and search elsewhere. I would love to have something like this:

![image](https://github.com/brookhong/Surfingkeys/assets/16063186/16bd6adf-b789-46f5-bf64-1baa97be7244)
Here each yellow label represents the tab that one would jump to. That would make navigating tabs a lot easier, because one would not have to search for tabs or find the tabs via the current tab overlay.

Here is what I mean:
![image](https://github.com/brookhong/Surfingkeys/assets/16063186/b6c68ab0-4676-42e4-9b6f-65352ecec772)
Locating the desired tab is not that easy.

Thank you very much! :)

**Comment by brookhong** [comment]
It is impossible to align the positions of hint labels exactly with the titles of tabs, as we can not get the positions of tab titles within page content through JS code. Only the sequence of hint labels will align with the tabs, not sure that will help to mitigate the issue.

**Comment by DasOhmoff** [comment]
I see. So what if I could provide the size of the tab bar myself, and then the labels would adjust to it? For example, if I just specify the width of the tabbar to 900, then the 9 tab labels would each be 100 apart. If I set `settings.tabsThreshold` to more than 9, and I have for example 10 tabs open, then each label would be 90 (= 900 / 100) apart.
