### ISSUE TITLE
statusLine behaviour seems to have degraded

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#2005]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

    * Only partial (the info about `settings.showModeStatus`).

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

    * Yes.

## Error details

SurfingKeys: 1.14.0

Browser: Version 113.0.5672.92 (Official Build) (64-bit)

URL: all

## Context

As mentioned in https://github.com/brookhong/Surfingkeys/issues/1488#issuecomment-1590159602, SurfingKeys used to display a mode `statusLine` in certain situations, e.g. after pressing `Alt-i` or `p` for pass-through.  However now I don't see it at all.  If I add `settings.showModeStatus = true;` to my settings then I see it almost all the time (even in `Normal` mode).  But this is a change in behaviour, and I think the previous behaviour was better, where it's only visible when changed from the default mode for the site (e.g. to `Normal` when lurk mode is enabled, or to pass-through when normal is the default).

Another related issue is that the status line doesn't appear when a site is first loaded, but only after the first usage of SurfingKeys.

**Comment by aspiers** [comment]
Another example is that if I hit `Alt-s` to disable SK for the site, I get a permanent `Disabled` status line on the site:

![image](https://github.com/brookhong/Surfingkeys/assets/100738/23869a94-0358-4e6e-9433-fb2a8bd2d808)

If SK is disabled on a site, I don't think it should change that site's appearance in any way.

**Comment by brookhong** [comment]
Please verify the fix from 1.15.0.

**Comment by aspiers** [comment]
I upgraded to 1.15.0 and I still see the problem.  How to reproduce:

1. Don't set `settings.showModeStatus` (i.e. use default setting)
2. Visit a site where SK is enabled (i.e. no lurk mode)
3. Press `Alt-i`
4. Observe that there is no status line showing pass-through mode.

SK used to show something like `Pass-through` in the status line, but it doesn't show any more.

**Comment by brookhong** [comment]
It's the right behavior, isn't it?

If we need `pass through` visible in status line, we need set `settings.showModeStatus` true.

**Comment by brookhong** [comment]
> Another example is that if I hit `Alt-s` to disable SK for the site, I get a permanent `Disabled` status line on the site:
> 
> ![image](https://private-user-images.githubusercontent.com/100738/246258984-23869a94-0358-4e6e-9433-fb2a8bd2d808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjAzNDMsIm5iZiI6MTcwMzEyMDA0MywicGF0aCI6Ii8xMDA3MzgvMjQ2MjU4OTg0LTIzODY5YTk0LTAzNTgtNGU2ZS05NDMzLWZiMmE4YmQyZDgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMDU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzBiM2Y1Yzg4YWRhMDQ0MjdkNWY3NDNlOGRiM2ZmNDVlOTU0ZTYxYzkxYWM5ODQ1MWI4NDM5NGQ2ZmJhMjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7IW0bRt7kmYsopAYeXXLe6PTTzHeWYkGqmvb9HzbLU)
> 
> If SK is disabled on a site, I don't think it should change that site's appearance in any way.

And this is not true on my laptop.

**Comment by aspiers** [comment]
> It's the right behavior, isn't it?
> 
> If we need `pass through` visible in status line, we need set `settings.showModeStatus` true.

It's debatable what the "right" behaviour is, but I really don't like this - the previous behaviour was much better.

## Old behaviour (good)

1. `showModeStatus = false` - only showed `Pass-through` and other ephemeral statuses, but showed nothing when status was `Normal` (**good**)
2. `showModeStatus = true` - *always* showed a status, even `Normal` (**not useful**, because `Normal` is not needed and just gets in the way of the web page)

## New behaviour (worse)

3. `showModeStatus = false` - never shows any status (**not useful**, because it's too hard to track status without any feedback)
4. `showModeStatus = true` - *always* shows a status, even `Normal` (**not useful**, because `Normal` is not needed and just gets in the way of the web page)

## Suggestion

I can't understand why anyone would want behaviours 2., 3., and 4. above because they all have problems.  But if some people like those, they could still be supported without removing behaviour 1:

- `showModeStatus = "never"`
- `showModeStatus = "always"`
- `showModeStatus = "not-normal"`

**Comment by aspiers** [comment]
> > Another example is that if I hit `Alt-s` to disable SK for the site, I get a permanent `Disabled` status line on the site:
> > ![image](https://private-user-images.githubusercontent.com/100738/246258984-23869a94-0358-4e6e-9433-fb2a8bd2d808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjAzNDMsIm5iZiI6MTcwMzEyMDA0MywicGF0aCI6Ii8xMDA3MzgvMjQ2MjU4OTg0LTIzODY5YTk0LTAzNTgtNGU2ZS05NDMzLWZiMmE4YmQyZDgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMDU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzBiM2Y1Yzg4YWRhMDQ0MjdkNWY3NDNlOGRiM2ZmNDVlOTU0ZTYxYzkxYWM5ODQ1MWI4NDM5NGQ2ZmJhMjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7IW0bRt7kmYsopAYeXXLe6PTTzHeWYkGqmvb9HzbLU)
> > If SK is disabled on a site, I don't think it should change that site's appearance in any way.
> 
> And this is not true on my laptop.

It seems this got fixed somehow since I reported it.  But you can see from the screenshot that it was definitely an issue at that time.

**Comment by brookhong** [comment]
> > It's the right behavior, isn't it?
> > If we need `pass through` visible in status line, we need set `settings.showModeStatus` true.
> 
> It's debatable what the "right" behaviour is, but I really don't like this - the previous behaviour was much better.
> 
> ## Old behaviour (good)
> 1. `showModeStatus = false` - only showed `Pass-through` and other ephemeral statuses, but showed nothing when status was `Normal` (**good**)
> 2. `showModeStatus = true` - _always_ showed a status, even `Normal` (**not useful**, because `Normal` is not needed and just gets in the way of the web page)
> 
> ## New behaviour (worse)
> 3. `showModeStatus = false` - never shows any status (**not useful**, because it's too hard to track status without any feedback)
> 4. `showModeStatus = true` - _always_ shows a status, even `Normal` (**not useful**, because `Normal` is not needed and just gets in the way of the web page)
> 
> ## Suggestion
> I can't understand why anyone would want behaviours 2., 3., and 4. above because they all have problems. But if some people like those, they could still be supported without removing behaviour 1:
> 
> * `showModeStatus = "never"`
> * `showModeStatus = "always"`
> * `showModeStatus = "not-normal"`

Make sense, have brought the status indicator back for `pass through` in 1.16.0, could we close this now?

**Comment by aspiers** [comment]
Yes, it's good now thanks!
