### ISSUE TITLE
Tabs no longer sorted by MRU in the omnibar (when choosing a tab)

### ISSUE THREAD

**Issue by maxim-sm** [brookhong/Surfingkeys#2008]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

Yes, checked these first.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes, I tried with several keywords.

## Error details

SurfingKeys: 1.14.0

Browser: Chrome 114.0.5735.110 and Firefox 114.0.1 on Windows 10.

URL: Irrelevant

## Context

The issue started happening last week.

Steps to reproduce:
1. Install surfingkeys from the Chrome Web Store.
2. Go to surfingkeys settings and enable Advanced mode.
3. Set "settings.tabsThreshold = 0;" to always use the omnibar with tabs (also tried with other values).
4. Open several new tabs and go between them. Press Shift-t in order to open the omnibar in tabs view, the tabs will be sorted by their order in the browser and not in the order they were accessed as before.

I also tried adding "settings.tabsMRUOrder = true;" just to make sure, but it didn't change anything.

Please let me know if additional information is required.
Thanks!

**Comment by vcfvct** [comment]
@maxim-sm , It seems like the `tabsThreshold` default is changed from 9 to `100` in the [recent commit](https://github.com/brookhong/Surfingkeys/commit/6d0ee1dfda4e5231920bda0a20996134d1e0ba29): 

Now we have to add below line to the setting/configuration explicitly to keep the previous behavior, which I believe is more reasonable as it is impossible to locate the one from 100  tabs without a list view :

> settings.tabsThreshold = 9;

**Comment by maxim-sm** [comment]
> @maxim-sm , It seems like the `tabsThreshold` default is changed from 9 to `100` in the [recent commit](https://github.com/brookhong/Surfingkeys/commit/6d0ee1dfda4e5231920bda0a20996134d1e0ba29):
> 
> Now we have to add below line to the setting/configuration explicitly to keep the previous behavior, which I believe is more reasonable as it is impossible to locate the one from 100 tabs without a list view :
> 
> > settings.tabsThreshold = 9;

@vcfvct Thank you for the comment, but I'm afraid that setting settings.tabsThreshold = 9; or higher doesn't fix the issue.
If I understand correctly, the change in the commit shouldn't affect the order of the tabs when they are shown in the omnibar. 
The settings.tabsThreshold option controls how many open tabs you need to have before the omnibar is used when choosing a tab to go to. The commit changes this number to 100, so you need 100 tabs before the omnibar is used. If my understanding is correct, setting settings.tabsThreshold to 1, for example, will set the minimum opened tabs to 1. So if I have one open tab in the browser, the omnibar is used as expected.

My issue starts after the omnibar have opened. The order of the tabs in the omnibar should be from the most recent tab accessed to the least recent, but now the tabs are ordered in the order they appear in the browser.

Please let me know if I'm missing something> @maxim-sm , It seems like the `tabsThreshold` default is changed from 9 to `100` in the [recent commit](https://github.com/brookhong/Surfingkeys/commit/6d0ee1dfda4e5231920bda0a20996134d1e0ba29):
> 
> Now we have to add below line to the setting/configuration explicitly to keep the previous behavior, which I believe is more reasonable as it is impossible to locate the one from 100 tabs without a list view :
> 
> > settings.tabsThreshold = 9;

@vcfvct Thank you for the comment, but I'm afraid that setting settings.tabsThreshold = 9; or higher doesn't fix the issue.
If I understand correctly, the change in the commit shouldn't affect how the tabs are ordered in the omnibar. 
The settings.tabsThreshold option controls how many open tabs you need to have before the omnibar is used when choosing a tab to go to (Shift-T). The commit changes this number to 100, so you need a minimum of 100 tabs before the omnibar is used. If my understanding is correct, setting settings.tabsThreshold to 1, for example, changes the default minimum of opened tabs to 1, so if I have one open tab in the browser, the omnibar is used as expected.

My issue starts after the omnibar have opened (so it passed the "minimum number of tabs" test). The order of the tabs in the omnibar should be from the most recent tab accessed to the least recent, but now the tabs are ordered in the order they appear in the browser (the most left tab is first, the most right tab is last).

**Comment by wzqj** [comment]
I also have the same issue, Firefox 114.0.1 on Arch Linux. Tried adjusting the same settings as @maxim-sm as well, to no effect.

**Comment by brookhong** [comment]
Confirmed the regression bug, will be fixed in next release. Thanks for finding the issue.
