### ISSUE TITLE
Unrecognized key event: <Process>

### ISSUE THREAD

**Issue by autumnsun** [brookhong/Surfingkeys#201]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 229,
    "code": "KeyA",
    "composed": true,
    "key": "Process"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Thanks, fixed in 0.7.2
