### ISSUE TITLE
Surfingkeys not working in a new tab 

### ISSUE THREAD

**Issue by fakeowl1** [brookhong/Surfingkeys#2012]
Hi! Surfingkeys hotkeys not working in a new tab. I can't using hotkeys in a new tab. I tried Firefox but the same problem.  

Chromium 114.0.5735.133 
SurfingKeys 1.15.0

OC: ArchLinux x86_64

**UPD**: I mean the default Google search page. In the default search page I can't use any keybinds Surfingkeys. Other cases everything works fine.

**Comment by hok7z** [comment]
> Chromium disables plugins on its special pages like the new-tab page. When you create a tab, does it open Chrome's the special new tab page (default setting)? In that case you can work around this by:
> 
> * Setting Chrome to open a non-special page in settings
> * Using [Brooke's special build](https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html) that enables plug-ins on special pages

No, Chromium opens a simple tab page.

**Comment by hok7z** [comment]
> > No, Chrome opens a simple tab page.
> 
> Do you mean the default Google/DDG search page? In that case you are opening a special chrome tab, in which plugins don't work. Or have you actually set your default page to a 'normal' page, e.g. https://en.wikipedia.org/wiki/Main_Page via plugins like [New Tab Redirect](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna)? Does it still happen when you set it e.g. to Wikipedia?

Do you mean the default Google/DDG search page? - Yeah.

**Comment by towith** [comment]
@brookhong  I have tried your build of chromium, that's good, thanks
