### ISSUE TITLE
firefox not support Load settings from file:///

### ISSUE THREAD

**Issue by zxyqq** [brookhong/Surfingkeys#2015]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details
in advanced mode, try to load config from file using the url "file:///"
click the save button then failed msssage prompt: "failed to load settings from file"

SurfingKeys: 1.15.0

Browser: firefox win11

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by piersolenski** [comment]
Same issue on MacOS Brave, SK 1.15.0

**Comment by EuCaue** [comment]
Same issue on Linux, Firefox V121.

**Comment by zxyqq** [comment]
https://github.com/brookhong/Surfingkeys/discussions/1892

Firefox doesn't support loading settings from a local file. That's only available for Chromium-based browsers.
