### ISSUE TITLE
浏览网页过程中.弹出下面 Bug,无其他操作.也没有触发 SuffingKeys.

### ISSUE THREAD

**Issue by leebivip** [brookhong/Surfingkeys#202]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 40,
    "code": "ArrowDown"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

## Context

**360.极速浏览器 **

**Comment by brookhong** [comment]
Thanks, it should be fixed in 0.7.3.
