### ISSUE TITLE
is there a way to swap the keymap zi and zo?

### ISSUE THREAD

**Issue by edte** [brookhong/Surfingkeys#2020]
i had try
```
api.map('zo', 'zi');
api.map('zi','zo');
```
but it all become zo, i also had try

```
api.map('zo', 'zt');
api.map('zo','zi');
api.map('zi','zt');
```
but it also not work.

**Comment by brookhong** [comment]
It should be

    // save original function of zo into zt
    api.map('zt', 'zo');
    // use zo to replace zi
    api.map('zo','zi');
    // use zi to replace zt, which is the original function of zo
    api.map('zi','zt');
    
    // optional, clean zt
    api.unmap('zt')
