### ISSUE TITLE
[FR] a key for fuzzy find only in open tabs

### ISSUE THREAD

**Issue by Archie-2021** [brookhong/Surfingkeys#2022]
I know `t` can do that , but it also loads many other things and it makes it supper slow if one has too many bookmarks (I admit I need to clean up my bookmarks but still can happen to anyone). Can you please make the function to choose a tab only? I think binding it to `t` would be the best but It is not that important and anyone can bind it base on their performance.

Thanks for this awesome plugin.

**Comment by brookhong** [comment]
Have you tried `T`?

**Comment by Archie-2021** [comment]
> Have you tried `T`?

Yes, It is nice but when there is a lot of tabs open it is hard to find tabs. Fuzzy finding is an easier thing to so. Kinda like how vim buffers switched with `:b <...>`.

**Comment by brookhong** [comment]
Not sure if this what you want, `Tj` or just `T` with below settings

    settings.tabsThreshold = 0;
    
https://github.com/brookhong/Surfingkeys?tab=readme-ov-file#switch-tabs

**Comment by Archie-2021** [comment]
> Not sure if this what you want, `Tj` or just `T` with below settings
> 
> ```
> settings.tabsThreshold = 0;
> ```
> 
> https://github.com/brookhong/Surfingkeys?tab=readme-ov-file#switch-tabs

That is exactly what I was looking for. Thanks
