### ISSUE TITLE
Bug: Capture Full Screen no longer working, at all.

### ISSUE THREAD

**Issue by EvanCarroll** [brookhong/Surfingkeys#2024]
This functionality in `yG` is no longer working on Linux at all. It seems to scroll around the screen like it used to do, but it no longer seems to capture and stitch together the page so you can save it.

It looks like we're already using Chrome's method to capture the visibleTab which seems to do what we want but isn't working.

https://developer.chrome.com/docs/extensions/reference/tabs/#method-captureVisibleTab

**Comment by EvanCarroll** [comment]
It seems after every `yG` it tries to logs this to the console `GET https://<URL>/undefined 404` so somehow one of these paths isn't working.

**Comment by brookhong** [comment]
Below error raised from background, looks like we will have to make `yG` slower again, so that it won't breach the quota.
> This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.
