### ISSUE TITLE
Error found in settings: ReferenceError: aceVimMap is not defined

### ISSUE THREAD

**Issue by David-Else** [brookhong/Surfingkeys#2025]
## Error details

If I add this to the settings I get `Error found in settings: ReferenceError: aceVimMap is not defined`
```
aceVimMap('jk', '<Esc>', 'insert');
```

SurfingKeys: 1.15.0

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0

**Comment by David-Else** [comment]
Thanks! I added the info to the FAQ: https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-use-jk-for-escape-in-the-ace-editor
