### ISSUE TITLE
Arch用户无法使用Chromium.deb

### ISSUE THREAD

**Issue by fengyayel** [brookhong/Surfingkeys#2035]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

在Arch Linux下转换包格式安装时出错, 但仍想在Arch 下体验更彻底的surfingkeys,博主有没有想法将chromium打包到AUR?虽然编译和维护会耗费很多精力.

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by JuanZoran** [comment]
找到解决办法了吗， 同样希望在arch下使用chromium.deb
