### ISSUE TITLE
Can't go one tab left by pressing E in chrome://newtab

### ISSUE THREAD

**Issue by JuckZ** [brookhong/Surfingkeys#2042]
## Error details

In the new tab, when I want to press E to switch to the left TAB, the plugin doesn't work

SurfingKeys: 1.15.0

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

URL: chrome://newtab

**Comment by Georift** [comment]
Browsers will typically disable extensions on these "system tabs" as a way to prevent them doing dodgy things. I don't think there is any way to prevent this behavior.
