### ISSUE TITLE
Can't map the backslash?

### ISSUE THREAD

**Issue by 097115** [brookhong/Surfingkeys#2048]
Hi!

I can't seem to map the backslash in Firefox - this snippet works just fine in Brave but does nothing in Fx:

    mapkey('\\', '#3Open Some URL', function () {
        tabOpenLink("https://some.url");
    });

Any hints may be?

Thanks :)

**Comment by brookhong** [comment]
Works for me, do you forget to import `tabOpenLink`?

    const {
        aceVimMap,
        addVimMapKey,
        mapkey,
        imap,
        imapkey,
        getClickableElements,
        vmapkey,
        map,
        cmap,
        addSearchAlias,
        unmapAllExcept,
        removeSearchAlias,
        searchSelectedWith,
        tabOpenLink,
        readText,
        Clipboard,
        Normal,
        Front,
        Hints,
        Visual,
        RUNTIME
    } = api;
    
    mapkey('\\', '#3Open Some URL', function () {
        tabOpenLink("https://some.url");
    });
