### ISSUE TITLE
brookhong的chromium 117.0.5938.149版本异常

### ISSUE THREAD

**Issue by fengyayel** [brookhong/Surfingkeys#2049]
今天我更新了brookhong的chromium版本,重新打开后出现如下情况:
![image](https://github.com/brookhong/Surfingkeys/assets/128961593/381ee34d-5bf7-419c-b35f-f7bc623c6e66)

![image](https://github.com/brookhong/Surfingkeys/assets/128961593/b62eb623-5c44-4abd-8c75-0087e8b23a31)
这是更新后才出现的问题.我该怎么办?

**Comment by fengyayel** [comment]
扩展无法单击, 但却生效

**Comment by fengyayel** [comment]
经过测试, 只有当surfingkeys enable后才会出现上述情况,此时其它扩展单击都将崩溃, disable surfingkeys后恢复正常, 但存在地址栏无法搜索的情况, 即键入关键词按enter无反应.

**Comment by Kiraalla** [comment]
确实有此问题，使用很痛苦！

**Comment by Kiraalla** [comment]
请提升此问题为BUG，我用着好难受啊，一直崩溃崩溃

**Comment by brookhong** [comment]
刚更新了120.0.6099.106，解决这个问题了。
