### ISSUE TITLE
surfingkeys does not  access chrome:// pages

### ISSUE THREAD

**Issue by mohamadiarch** [brookhong/Surfingkeys#2053]
By default we cannot run Surfingkeys on a chrome:// url page.
But there is an option in chrome://flags/#extensions-on-chrome-urls:
I enable it but still I cannot access these urls while other extensions can.

**Comment by mohamadiarch** [comment]
I`m using dev.to extenstion for my new tab. How can I use Surfingkeys in this page?

**Comment by fengyayel** [comment]
u can try this --> https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html
