### ISSUE TITLE
Get "Unable to render code block" when copying from ipython notebook on Github

### ISSUE THREAD

**Issue by tshu-w** [brookhong/Surfingkeys#2060]
## Error details

When I select some text and press `cmd-c` (copy) in the notebook, I got "Unable to render code block", this issue also happen on Safari.

<img width="1057" alt="Screenshot 2023-12-19 at 14 45 52" src="https://github.com/brookhong/Surfingkeys/assets/13161779/ae8f00a4-29ef-48ab-b11a-6f1d4e46a818">

SurfingKeys: 1.15.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0

URL: https://github.com/stanfordnlp/dspy/blob/main/examples/knn.ipynb

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Basically this is an issue of github, and we cannot fix it in the extension context.

You can just run below code in the frame of `https://notebooks.githubusercontent.com` with Inspect tool to reproduce the issue.

    top.postMessage({}, "https://github.com/")

A workaround solution is to disable Surfingkeys on https://notebooks.githubusercontent.com.

1. Open https://notebooks.githubusercontent.com/ in a new tab.
2. Press `Alt-s` to disable Surfingkeys on the domain.
