### ISSUE TITLE
UI Indicator for PassThrough mode

### ISSUE THREAD

**Issue by flinesse** [brookhong/Surfingkeys#2062]
It would be really nice to have a visual element—something akin to [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight), to relay the current passthrough status to the end user (under both default and lurk).

**Comment by brookhong** [comment]
Should have been fixed in 1.16.0.

**Comment by flinesse** [comment]
@brookhong Could the indicator be shown when normal mode is activated under ***lurk*** as well? (as in an inverted logic for showing the ui statusline compared to ***default***).

- default: Show statusline indicator when disabling SK keybinds (passthrough)
- lurk: Show statusline indicator when enabling SK keybinds (normal)

**Comment by brookhong** [comment]
`lurk` is kind of `Disable`, showing indicator for it does not align with its purpose of lurking, besides that we already have a different icon in the toolbar when lurk mode is on.

**Comment by flinesse** [comment]
What I meant is an indicator when **un-lurking** and SK keybinds are **enabled**, i.e. showing when following key commands are used:

![image](https://github.com/brookhong/Surfingkeys/assets/31031753/fa485453-a8f6-48d0-aef2-c1daa2f98501)
I feel it would make sense then? Feel free to let me know you disagree.

My current use case is that I am running lurk on a web app (with its own keybinds) as a PWA, which means no toolbar icon. It would be nice to know when I unlurk and am able to use SK keybinds.

**Comment by Fred-Vatin** [comment]
I agree. The toolbar icon color is not visible enough to notify un-lurking. We need the same indicator as `passthrough` and `ephemeral`. I will open a feature request.

@flinesse Is the `lurk mode` group in the show usage modal there because you changed the default shortkeys ? Those keys are in the help group by default.
