### ISSUE TITLE
Custom annotation with `api.map` not working as expected 

### ISSUE THREAD

**Issue by flinesse** [brookhong/Surfingkeys#2063]
## Error details

SurfingKeys: 1.15.0

Browser: Brave Browser Version 1.61.109 [Chromium: 120.0.6099.144 (Official Build; arm64)], macOS

## Context

From the API documentation, `map` allows [custom annotation](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#map) (param `new_annotation`) to replace the old key sequence's annotation section and help text, but this is not working for me. 

For example:
```javascript
map('go', 'go', null, "#8Example text");
```
is not overwriting the old annotation, neither is
```javascript
map('g0', 'go', null, "#8Example text");
```
<br>
My use case for this is to make the keymap and help text more coherent and easier to parse for me.

**Comment by brookhong** [comment]
Should have been fixed in 1.16.0.
