### ISSUE TITLE
Omnibar Tabs will sometimes display a very large FavIcon

### ISSUE THREAD

**Issue by milomouse** [brookhong/Surfingkeys#2068]
## Error details

When opening the Omnibar for Tabs, the FavIcon on the left-hand side will appear way larger than the other FavIcons.

I'm not sure if this is a bug exactly, but could we have a way of limiting how large the FavIcons are allowed to be displayed so this doesn't happen?

This isn't the first time I've come across this problem but now that I've noticed it again I wanted to report it.

![sk-omnibar](https://github.com/brookhong/Surfingkeys/assets/76868/00487795-c4ed-4797-9c96-a6dd2ed485ac)

SurfingKeys: 1.16.0

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0

URL: https://cdromance.com

**Comment by brookhong** [comment]
Will be fixed in 1.16.1.
