### ISSUE TITLE
Omnibar `t` not showing history in Brave

### ISSUE THREAD

**Issue by cvincent** [brookhong/Surfingkeys#2070]
## Error details

SurfingKeys: 1.16.0

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

## Context

In Brave, hitting `t` to open a new tab doesn't show any history in the Omnibar. Instead, it shows a list of open tabs. This includes after resetting the extension to factory settings. It works as expected in Chrome and Chromium, so I suspect the issue may be specific to Brave.

**Comment by hytor-yang** [comment]
Reproduced in Chrome 120.0.6099.199 too.
devtool error logs show that "getHistory" and "getAllURLs" returned undefined.

**Comment by lcaturelli** [comment]
Reproduced in Vivaldi 6.4.3160.47 (Stable channel) too.

Devtool show this errors in console:

Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received, in chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html

Error handling response: TypeError: Cannot read properties of undefined (reading 'urls')
    at chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.js:11:121701

The problem did not occur in previous version (1.15.0)

PD: Thank you very much for this incredible extension!

**Comment by cvincent** [comment]
FWIW, in my own case in Brave, I don't see any error output in the console.

**Comment by nozaki87** [comment]
> Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received, in chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html
> Error handling response: TypeError: Cannot read properties of undefined (reading 'urls') at chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.js:11:121701
> The problem did not occur in previous version (1.15.0)
I have same error in 1.16.0.

**Comment by cvincent** [comment]
Is everyone seeing this error just in the regular web inspector console, without running any additional commands? I don't see the error at all, just the unexpected behavior. And again, I'm not seeing it in Chrome or Chromium.

**Comment by brookhong** [comment]
Thank you guys for reporting this issue, it will be fixed in 1.16.1.
