### ISSUE TITLE
更新到1.16之后，历史记录无法搜索。

### ISSUE THREAD

**Issue by hywlzx** [brookhong/Surfingkeys#2074]
## Prelude

没有在文档或issue中找到相应解决方案

## Error details

使用oh或者t进行搜索时，如果只输入一个字符，可以成功筛选。多于一个字符结果不变化，控制台报以下错误

![image](https://github.com/brookhong/Surfingkeys/assets/19977607/0fac18c5-7990-4342-a5b0-b317cd52e83d)

降级为1.15.0版本后，搜索功能正常。但chrome浏览器无法关闭扩展自动更新，过一段时间又会重新更新为1.16.0

SurfingKeys: 1.16.0

Browser: chrome 120.0.6099.217

**Comment by firefoxmmx2** [comment]
出现相同的问题

**Comment by firefoxmmx2** [comment]
我发现这个似乎和当前打开的标签url有关系。 你可以尝试全部关闭，然后重新打开，就好了。 但是目前我发现一个另外的问题，网站的图标视乎没有限制大小，导致有些标签的内容变形，图标超级大。

**Comment by brookhong** [comment]
duplicate of #2070
