### ISSUE TITLE
按f键之后点击任意链接会触发浏览器翻译插件的网页翻译功能

### ISSUE THREAD

**Issue by yangzexia** [brookhong/Surfingkeys#2081]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes

## Error details

SurfingKeys: 1.13.0

**Browser:** 
    Microsoft Edge版本 120.0.2210.121
    Windows 11 家庭中文版
    版本	23H2
    安装日期	‎2023/‎2/‎20
    操作系统版本	22631.3007
    体验	Windows Feature Experience Pack 1000.22681.1000.0

**URL:** www.zhihu.com

## Context

浏览器安装了[翻译插件](https://chromewebstore.google.com/detail/talent-immersive-ai-trans/lbcbipoloacjakecofjkohgllhojdhhp)的情况下，在任意网页上使用SurfingKeys的f键，点击任意一个链接之后，会触发翻译插件的网页翻译功能。关闭SurfingKeys之后按相同的按键不会触发翻译功能

示意：
![GIF 2024-1-17 16-05-24](https://github.com/brookhong/Surfingkeys/assets/37099022/10bb5740-707a-4373-888a-c84d6ddc67e0)

**Comment by brookhong** [comment]
这个应该找那个翻译插件来解决下，它对mouseup的处理逻辑有问题，你可以打开开发者工具，运行下面的语句复现同样的问题。

    window.dispatchEvent(new MouseEvent("mouseup"))
