### ISSUE TITLE
Is there a way to get notifications when there are updates?

### ISSUE THREAD

**Issue by ShayneWilliams** [brookhong/Surfingkeys#2084]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
I've searched and couldn't find an answer.
## Error details
In patch 1.16.1 you guys recently changed the omnibar to be vertical. I'm all for adding new features but I'd be very grateful if you guys didn't make these things the default without any warning. Is there some kind of newsletter or discord I can sign up for so that I can get notified when you guys make updates? You guys do a lot of great work and I'd like to follow the project more closely. 

SurfingKeys: <version>
1.16.1
Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

I was using the switch tabs functionality.

**Comment by az-pz** [comment]
You could use  github watch feature to get email updates on all the changes to the repo. And, you can create a filter in your email client to get only the relevant information.

**Comment by brookhong** [comment]
Sorry, there is no such channel so far. I would try to keep breaking changes as less as possible, and watching on this repo might help to some extend.
