### ISSUE TITLE
Unrecognized key event: <Meta-Meta>

### ISSUE THREAD

**Issue by 1984weed** [brookhong/Surfingkeys#209]
## Error details

{
    "metaKey": true,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 93,
    "code": "MetaRight",
    "composed": true,
    "key": "Meta"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Thanks, fixed in 0.7.2

**Comment by 1984weed** [comment]
👍
