### ISSUE TITLE
Issue with overlay on Github sidebar not showing on top

### ISSUE THREAD

**Issue by BraianPita** [brookhong/Surfingkeys#2096]
## Prelude
* Could you find answer in below documents? No

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes

## Error details

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

URL: https://github.com/

## Context

When I am trying to use the Github sidebar that opens when you click your profile picture, I cannot focus or do anything on is (cs does not seem to focus on it either). This is what I see:
<img width="469" alt="image" src="https://github.com/brookhong/Surfingkeys/assets/54162188/3cb6d6fe-1403-45ac-aa46-01bf462daf80">

And, when I (using my mouse 🤢) close the sidebar, I see this:
<img width="464" alt="image" src="https://github.com/brookhong/Surfingkeys/assets/54162188/42928eef-f958-4692-a0e8-a9f53c4df060">

It seems Github sidebar has either a higher z-index than the overlay, which makes it appear on top, or some cascading effect is making it be on top of everything else and not letting me interact with it. 

What I expected to happen:
I should be able to open the github sidebar using f > [letter for profile image] and then interact with it using the f key or any other command.

**Comment by soluty** [comment]
I found the same problem, Github  use  <dialog> tag which is the  top-layer element ,  to fix this  we must not use div as  surfingkeys_hints_host"s root ,  but to create it as a <dialog>, and this may be better because top-layer is a lifo stack. Maybe can use surfingkeys in fullscreen control.

**Comment by brookhong** [comment]
Fixed in 1.17.5.
