### ISSUE TITLE
rearrange tabs between windows, select tabs in current window, with title, containing substring

### ISSUE THREAD

**Issue by zldrq** [brookhong/Surfingkeys#21]
the ability to rearrange tabs between windows. i always have several windows, and from time to time sort tabs between them, accordingly to their topic.

usually i press ctrl in some window, select needed tabs and drag n drop them to another window. which is inconvenient and is connected with some difficulties

it would be great to press, say, capital `S`, enter substring (say, "stackoverflow"), tabs will be selected, then the command  to move them and a number (`1`..`0`) of window, where to move them (or `n` for new window). 

the same function, "select tabs", namely, may be used to close them, for example. or `p`in them, or `g`roup to the `l`eft side of window, or "`s`ave as" to `d`irectory, `s`ave `b`ookmarks, anything. (i understand that half of this is just pretty unneeded, but you get the idea).
in this case, `S` that was pressed to select tabs interpreted with keys that was pressed after tab search as single command to not occupy keys: `S`, [_search string_], `enter`, `m`, `1` (move tabs containing _search string_ from this window to window 1) and so on

**Comment by gdzwrk** [comment]
This would be fantastic, and would help me keep my workflows sorted in separate windows that I can then show/hide by window.  Even if only half of the things @zldrq mentioned were added.. moving tabs between windows by regex alone would be fantastic.

**Comment by vogler** [comment]
@brookhong did you decide against this or was it implemented in some way?

**Comment by brookhong** [comment]
I closed this for age, personally I don't have many circumstances that need such operations, but it is worthy to implement this if we see more votes.

**Comment by vogler** [comment]
Ok, thanks. Since #427 is required for this and has more votes, it should be reopened too then.
