### ISSUE TITLE
Unrecognized key event: <Process>

### ISSUE THREAD

**Issue by hwk603** [brookhong/Surfingkeys#210]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 229,
    "code": "KeyJ",
    "composed": true,
    "key": "Process"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

# When I type, the pop-up tips

![image](https://cloud.githubusercontent.com/assets/7033138/22092825/c8b9ee82-de3b-11e6-81cd-1d4df4b72c4d.png)

**Comment by brookhong** [comment]
Thanks, fixed in 0.7.2

It would be better if you could describe what you did before the popup came out, thank you.
