### ISSUE TITLE
Surfingkeys version on Microsoft Edge Addons still 1.13.0

### ISSUE THREAD

**Issue by kesdoputr** [brookhong/Surfingkeys#2100]
Hello, i found the version on Microsoft Edge Addons
https://microsoftedge.microsoft.com/addons/detail/surfingkeys/kgnghhfkloifoabeaobjkgagcecbnppg

Is still 1.13.0, but the newest version should be 1.16.1

Will there be an update on Microsoft Edge Addons?

Thanks for your reading.

**Comment by brookhong** [comment]
1.17.5 is released on Microsoft Edge Addons.
