### ISSUE TITLE
edge(mac) close surfingkeys automatically edge（mac平台）下会自动关闭surfingkeys

### ISSUE THREAD

**Issue by keyboardset** [brookhong/Surfingkeys#2109]
#edge
edge 下会不断自动关闭这个扩展 
我猜测是和edge的节能功能有关？ 不知道有没有遇到同样问题的。

我的surfingkeys的版本是1.13.0
重新打开后 也不会报错

在同一台电脑上的 chrome和firefox都没有类似的问题

**Comment by windily-cloud** [comment]
我的edge也是，windows11

**Comment by keyboardset** [comment]
试着关掉edge的 power saving model, 可能会有用.
