### ISSUE TITLE
Hints not showing on Pypi.org

### ISSUE THREAD

**Issue by svenko99** [brookhong/Surfingkeys#2111]
## Error details

SurfingKeys: 1.15.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15

URL: https://pypi.org/

## Context

When I press `f` hint characters are not shown. When I type a random sequence of characters, some link opens, but I don't see the hints. This problem only arises on the [Pypi](https://pypi.org/) page.

**Comment by brookhong** [comment]
There is some CSP policy on the site to prevent style injection, which causes the issue.

    Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.

Though style injection for hints now is done in a shadow DOM, but looks like Safari also applies the CSP policy in shadow DOM, which is not same as other browsers. So far we don't have a good solution for this.
