### ISSUE TITLE
请问如何将替换“Search selected with xxxx”“转变为 用xxxx搜索选中文本

### ISSUE THREAD

**Issue by Tback1** [brookhong/Surfingkeys#2114]
突然想修改这个，统一搜索效果。但是突然发现居然**没有这个参数支持**

![image|200](https://github.com/brookhong/Surfingkeys/assets/8872546/8e6b65d7-5a39-44e8-aba5-aad364ce7910)

而且挺有意思的是，**我将百度和bing的搜索触发快捷键做了替换**

```js
api.removeSearchAlias('d');
api.removeSearchAlias('b');
api.removeSearchAlias('s');
api.removeSearchAlias('y');
api.removeSearchAlias('w');

api.addSearchAlias('w', 'baidu', 'https://www.baidu.com/s?wd=', 's', 'https://suggestion.baidu.com/su?cb=&wd=', function (response) {
    var res = response.text.match(/,s:\[("[^\]]+")]}/);
    return res ? res[1].replace(/"/g, '').split(",") : [];
});

api.addSearchAlias('b', 'bing', 'https://www.bing.com/search?setmkt=en-us&setlang=en-us&q=', 's', 'https://api.bing.com/osjson.aspx?query=', function (response) {
    var res = JSON.parse(response.text);
    return res[1];
});

api.addSearchAlias('dq', '豆瓣电影', 'https://search.douban.com/movie/subject_search?search_text={0}&cat=1002', 's', 'https://search.douban.com/movie/subject_search?search_text={0}&cat=1002', function(response) {
    var res = JSON.parse(response.text);
    return res.map(function(r){
        return r.phrase;
    });
});

api.addSearchAlias('da', '豆瓣图书', 'https://search.douban.com/book/subject_search?search_text={0}&cat=1001', 's', 'https://search.douban.com/book/subject_search?search_text={0}&cat=1001', function(response) {
    var res = JSON.parse(response.text);
    return res.map(function(r){
        return r.phrase;
    });
});
```

**本以为，这样百度和bing也会变成 `Search xxx` 这样的效果， 结果这两者还是得到了中文支持**。看了一下代码，原来是编码里做了硬翻译。那这个问题能有解么？

![image|200](https://github.com/brookhong/Surfingkeys/assets/8872546/34721e76-26ed-4305-abee-511a37a0f4f6)

**Comment by TassdarZeratul** [comment]
在l10n.json里照葫芦画瓢把对应得翻译添加上去不就得了,
![image](https://github.com/brookhong/Surfingkeys/assets/29266528/99a434eb-4a00-416a-b262-dc9580ed99db)

**Comment by Tback1** [comment]
我都能定位到源代码位置了，我还不知道自己添加么。
问题是我是用的Chrome市场版本
第一，如果自己修改硬编码，每次更新，得不断重新手工注入
第二，Chrome的插件是做了hash验证的，手工直接修改json，Chrome直接报告插件损坏
![image](https://github.com/brookhong/Surfingkeys/assets/8872546/6694df08-ed84-4ac4-b88b-59986928830a)

**Comment by TassdarZeratul** [comment]
你都会自己添加了, 难道不会阻止更新? 难道不会加载自定义插件?

**Comment by Tback1** [comment]
> 你都会自己添加了, 难道不会阻止更新? 难道不会加载自定义插件? 或是不知道自己该问什么?

很简单，我希望保留Chrome发行版。开发者模式自加载不就回到第一点，每出一个版本，我就得跟着手工更新维护。

**Comment by TassdarZeratul** [comment]
每个版本都跟随更新的意义何在?
![image](https://github.com/brookhong/Surfingkeys/assets/29266528/8483eef6-4605-4ccc-8382-65dcd62f883b)

**Comment by Tback1** [comment]
我发这个issue只是希望开发者如果考虑能够添加一个自定义函数的入口。无意接受手工修改方案。无需您手把手教学

**Comment by Tback1** [comment]
问题是我无意于此，提个issue而已。你给出的方案我自己知道的，但是和我的目标不同。所以没必要这么做

**Comment by TassdarZeratul** [comment]
所以一揽子解决方案都是没必要的,  但"每次版本更新都跟着手工维护"则是必要的.

**Comment by wangjun-kai** [comment]
这个是哪里改，先加一个用kimi搜索，是在高级设置里面吗

**Comment by brookhong** [comment]
Fixed 1.17.5.
