### ISSUE TITLE
Failed to connect neovim, please make sure your neovim version 0.5 or above.

### ISSUE THREAD

**Issue by MrVBian** [brookhong/Surfingkeys#2116]
![2024-05-17_16-48](https://github.com/brookhong/Surfingkeys/assets/37790267/07f8e7fd-a05f-4b6a-bfc8-4508c66943e8)

As shown in the picture, my plug-in startup will report an error, but this is not always an error, occasionally it is normal to report an error. 
What can I do to solve the problem?

**Comment by MrVBian** [comment]
Add two pictures to better feedback issues

![image](https://github.com/brookhong/Surfingkeys/assets/37790267/df0964be-e658-4bba-a44d-d870a3282a94)

![image](https://github.com/brookhong/Surfingkeys/assets/37790267/834fe31f-1486-4af4-88ff-690a21e6ea48)

**Comment by keyboardset** [comment]
same problem: browser is edge

**Comment by brookhong** [comment]
If you don't need to use neovim in browser like this, the error is just harmless.
<img width="1525" alt="image" src="https://github.com/user-attachments/assets/1ee21d34-4972-449b-b815-81049f9a9aaa">

If you need the feature, please setup by following [the guide](https://github.com/brookhong/Surfingkeys/blob/master/src/nvim/server/Readme.md).
