### ISSUE TITLE
Is it possible to hide specific options in the Omnibar without disabling them directly?

### ISSUE THREAD

**Issue by XMahoniX** [brookhong/Surfingkeys#2117]
**If the alias in options displays Chinese, an error will be reported, but search engines can use Chinese, so I wonder if I can hide this option in options without disabling it**
![QQ截图20240518173919](https://github.com/brookhong/Surfingkeys/assets/44489677/aac720f0-399f-430a-8bfa-3bdc08b8d43c)

**Below is my code**
`api.addSearchAlias('百度', '百度搜索', 'https://www.baidu.com/s?wd=');`

**Since I am new to this, if there is any other way to achieve it, please tell me, thank you.**

**Comment by TassdarZeratul** [comment]
api.addSearchAlias('b', 'baidu', 'https://www.baidu.com/s?wd=','s',
  'https://www.baidu.com/s?wd=',
  (res)=>{
    res=JSON.parse(res.text).result.tag
    return res.map(x=>x.value);
  });

**Comment by TassdarZeratul** [comment]
api.addSearchAlias('bd', '百度搜索', 'https://www.baidu.com/s?wd=');

**Comment by brookhong** [comment]
The first parameter `alias` of the API must be english chars, https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#addsearchalias, and it is recommended to use single char, as some other shortcuts will be generated by the API such as `s<alias>` or `so<alias>`,  see https://github.com/brookhong/Surfingkeys/blob/master/README.md#search-selected-with
