### ISSUE TITLE
Unrecognized key event: <Process>

### ISSUE THREAD

**Issue by cblk** [brookhong/Surfingkeys#212]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 229,
    "code": "KeyF",
    "composed": true,
    "key": "Process"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## Context

**使用中文输入法在任何输入框按下任何按钮都会出bug.**

**Comment by brookhong** [comment]
Thanks, fixed in 0.7.2

你的问题报告是最有用的, 谢谢。

**Comment by cblk** [comment]
很喜欢用这个插件，今天突然不能用了感觉很蓝瘦。没想到这么快就修复了，给你点个赞！
