### ISSUE TITLE
Codeforces doesn't load with surfing keys installed (even when disabled)

### ISSUE THREAD

**Issue by lucasrpatten** [brookhong/Surfingkeys#2120]
## Error details

SurfingKeys: <1.16.1>

Browser: <Mozilla Firefox 115.11.0esr><Debian GNU/Linux 12><KDE Plasma 5.27.5><Kernel 6.1.0-21-amd64>

URL: <[CodeForces](https://codeforces.com/)>

## Context
I use codeforces to practice programming a lot. However, I noticed the page would just load blank. I traced it down to the surfingkeys extension, but couldn't figure out why, so I've had to globally disable surfingkeys. Just disabling for the website using alt+s doesn't work.

**Comment by brookhong** [comment]
Already fixed in 1.17.4.
