### ISSUE TITLE
PDF file not work.

### ISSUE THREAD

**Issue by hereis00** [brookhong/Surfingkeys#2121]
## Error details
PDF file not work when open a pdf file link.

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
[Please try `;s`.](https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-disable-pdf-viewer-from-surfingkeys)
