### ISSUE TITLE
总是自动转换PDF文件

### ISSUE THREAD

**Issue by frankelinli** [brookhong/Surfingkeys#2123]
每次打开PDF文件时，总是自动转换PDF文件为extension://kgnghhfkloifoabeaobjkgagcecbnppg/pages/pdf_viewer.html?r=

这样真的很不方便。又没有关闭的按钮。请问可以解决这个问题吗？谢谢。

**Comment by js0ny** [comment]
用;s禁用pdf viewer

**Comment by frankelinli** [comment]
迟来的回复。感谢给出的解决方案，完美解决
