### ISSUE TITLE
Unexpected token error when loading settings from URL

### ISSUE THREAD

**Issue by caseycronyn** [brookhong/Surfingkeys#2126]
## Prelude
* Could you find answer in below documents?
    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes
## Error details

SurfingKeys: <version>

Browser: <version><os version>

URL: <The_URL_Where_You_Find_The_Issue>

## Context

When loading settings from a URL in Safari, I am faced with the following error pop up message:
` [SurfingKeys] Error found in settings: SyntaxError: Unexpected token '<' `

**Comment by brookhong** [comment]
This is usually caused by that the URL is not accessible by the extension, such as some authentication/authorization is needed to access the URL.
