### ISSUE TITLE
edge 里自动关闭的问题

### ISSUE THREAD

**Issue by keyboardset** [brookhong/Surfingkeys#2128]
## Error details

edge 浏览器下不断的自己关闭, 尝试了多种办法没有什么用.

SurfingKeys: 1.13.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
#2109 This is not an issue that this extension can fix.
