### ISSUE TITLE
Why surfingkeys is disabled in google search page in chrome?

### ISSUE THREAD

**Issue by owenstake** [brookhong/Surfingkeys#2130]
SurfingKeys: 1.16.1

Browser: chrome win10

URL: https://www.google.com.hk

## Context

Why surfingkeys is disabled in google search page in chrome? Google search page reminds me to use slash to get into search box.

**Comment by buidlcat** [comment]
I'm noticing a similar issue, the Google Search Results aren't registering as targets that Surfingkeys can use. Switching my default search engine until there's a fix...

**Comment by brookhong** [comment]
Cannot reproduce.
