### ISSUE TITLE
Pressing q key gives hints to click but i cant see the key shortcut to disable it in settings

### ISSUE THREAD

**Issue by Greatz08** [brookhong/Surfingkeys#2131]
if i am nit typing on page and press q it gives hints to click panel the bottom and hights link which i dont want as i have setup different firefox shortcut with my alt and q combo and this gets interrupted with this behaviour of this addon. i am using firefox btw and installed today only.So if this is bug i request you to give option like others which i can see in setting so that i can disable this 
see if i press q when not typing this happens
![image](https://github.com/user-attachments/assets/298862f9-b339-44d9-97b7-91afa88aa3f1)
and if there is no Q keybind setup by me 
![image](https://github.com/user-attachments/assets/def09602-7cba-4a6f-a799-d04215307e4d)

**Comment by brookhong** [comment]
Enable `Advanced mode`, then edit your settings like
<img width="803" alt="image" src="https://github.com/user-attachments/assets/298fb10d-8d6e-4357-8c84-558d9365c0e6">
