### ISSUE TITLE
Codeforces' web page can not be displayed with surfingkeys

### ISSUE THREAD

**Issue by ayokaa** [brookhong/Surfingkeys#2132]
## Error details

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

URL: https://codeforces.com/

## Context
When I use surfingkeys, the content of the web page may not be displayed sometimes, and there is only a blank page. Refreshing sometimes will help. Block the plugin and everything will be fine, so i guess maybe something wrong there.

**Comment by hamegy08lleo** [comment]
I'm facing the same issue. I'm using Firefox on EndeavourOS with Hyprland

**Comment by pauldub04** [comment]
Same thing with Firefox for arch linux 129.0, surfingKeys 1.16.1. Just white page when trying to open [codeforces.com](https://codeforces.com/)

**Comment by awerty-noob** [comment]
Same issue here, Surfingkeys 1.16.1 with Firefox 130.

**Comment by 383494** [comment]
Downgrading surfingKeys from 1.16.1 to 1.13.1 resolves the issue.
