### ISSUE TITLE
not supported in newer google chrome

### ISSUE THREAD

**Issue by ixzh** [brookhong/Surfingkeys#2136]
<img width="865" alt="Screenshot 2024-08-03 at 21 11 10" src="https://github.com/user-attachments/assets/f374e762-22c2-4d82-a203-b5611dc813ad">

today I saw this reminder from google chrome. What are the implications? Can I safely ignore it atm?

**Comment by 42Craft** [comment]
I also would like to know

**Comment by b0o** [comment]
See #1821
