### ISSUE TITLE
Brook Build of Chromium 闪退

### ISSUE THREAD

**Issue by draftman9** [brookhong/Surfingkeys#2137]
OS: windows10 (Microsoft Windows [Version 10.0.17763.4252] )
Brook Build of Chromium: Version 120.0.6099.106 (Official Build) (64-bit)
Surfingkeys: 1.16.1

在打开新标签过程中关闭其他标签时，CPU占用率高，Chromium发生闪退。

**Comment by zxyqq** [comment]
我之前也遇到过，后面就放弃使用了

**Comment by brookhong** [comment]
130.0.6723.97 刚发布了，可以试试还有没有问题，我自己在windows下用这个版本没遇到问题。

先关了，如果还没有问题可以再打开这个issue.
