### ISSUE TITLE
bilibili的评论部分无法使用f触发点击查看的操作

### ISSUE THREAD

**Issue by firefoxmmx2** [brookhong/Surfingkeys#2139]
在b站的视频评论区域，有折叠的评论，点击查看使用f无法触发点击事件。实际表现为没有效果。

**Comment by yu-d** [comment]
Shadow DOM 具有封闭性，默认情况下，事件不会跨越 Shadow DOM 的边界，不会从 shadowRoot 内部冒泡到外部文档树，事件只能在 shadowRoot 内部传播，除非显式地使用 composed: true 选项。

@brookhong 请在[src/content_scripts/common/utils.js#L116](https://github.com/brookhong/Surfingkeys/blob/f152a9a831ed4c357f072a531400d62c226be974/src/content_scripts/common/utils.js#L116)处添加 composed: true 选项修复此问题。

**Comment by firefoxmmx2** [comment]
谢谢已经修复了
