### ISSUE TITLE
 输入中文时出错，通过ALT+S禁用后也同样遇到问题

### ISSUE THREAD

**Issue by seasonxuan** [brookhong/Surfingkeys#214]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 229,
    "code": "KeyF",
    "composed": true,
    "key": "Process"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## Context
输入英文时没问题，但输入中文时出错，通过ALT+S禁用后也同样遇到问题“Uh-oh! The SurfingKeys extension encountered a bug.”

**Comment by brookhong** [comment]
非常感谢，0.7.2解决了这个问题。
