### ISSUE TITLE
Maybe some JS guru could help me? I'd like to display the current time with Surfingkeys help...

### ISSUE THREAD

**Issue by for-coursera** [brookhong/Surfingkeys#2142]
Would it be possible to make such a mapping that would [toggle] display the current time?

Maybe using the same function that displays hints? Or maybe the one that prompts mappings or shows help? Or maybe just show the current time in the omnibar after a key press?

Surfingkeys has so many wonderful built-ins, would be great to somehow utilize one of those :)

Or, if it's not possible to call the built-ins, then maybe a function that would create a temp overlay over the page with the current time? I just know very little JS, and all I can is to call a static `alert()`... But probably something more advanced is possible? Would be grateful for a hint :)

Thanks!

**Comment by for-coursera** [comment]
So, I ended with this static thing:

    mapkey('cx', '#0Show current time', function () {
        function showMessage(message) {
            var myScroll = document.documentElement.scrollTop + 100;
            const myDialog = document.createElement("dialog");
            document.body.appendChild(myDialog);
            myDialog.style.cssText = 'position:absolute;top:' + myScroll.toString() + 'px;background:#495062;color:#EEEEEE;font-size:24px;';
            myDialog.innerText = message;
            myDialog.show();
            setTimeout(function () {
                myDialog.close();
            }, 2000);
        }
        const currentTime = new Date().toLocaleTimeString(["en-GB"], { hour: '2-digit', minute: '2-digit' });
        const currentTimeLoc = currentTime.toLocaleString();
        showMessage(currentTimeLoc);
    });

Sort of works but suggestions are certainly more than welcome :) 

(Will close this in a few days.)

**Comment by brookhong** [comment]
You can just use `Front.showPopup`, such as 

    mapkey('cx', '#0Show current time', function () {
        const currentTime = new Date().toLocaleTimeString(["en-GB"], { hour: '2-digit', minute: '2-digit' });
        const currentTimeLoc = currentTime.toLocaleString();
        Front.showPopup(currentTimeLoc);
    });

**Comment by for-coursera** [comment]
Thanks, @brookhong! I should have read the [API](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md) documentation before asking, sorry for that :( (And there's `showBanner()`, too!)

One more question, though: I can't somehow center text in `showPopup()` only for this call, can I?
