### ISSUE TITLE
Recommended browsers when Google Manifest V3 is required

### ISSUE THREAD

**Issue by jackmac92** [brookhong/Surfingkeys#2144]
Related to #1821 

I like using my surfingkeys config, I'd change browsers to keep it. Is there a recommended browser setup in the event that manifest v3 upgrade can't provide feature parity?

I've started to setup use in firefox because 

> Firefox, however, has no plans to deprecate MV2 and will continue to support MV2 extensions for the foreseeable future. 
[src](https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/)

I'm not sure what I'm asking other than the broad title Q, but my main subquestion is: Can Surfingkeys work with MV3 in its current spec?

**Comment by jackmac92** [comment]
Seems like Firefox is the best alternative. Correct me if I'm wrong

**Comment by brookhong** [comment]
There is no recommended browser from Surfingkeys' perspective, but I personally use my own Chromium build, so the issues that happens in Chromium-family browsers may get more of my attentions.
