### ISSUE TITLE
settings.interceptedErrors = ["*"] doesn't take over any error page

### ISSUE THREAD

**Issue by smyle10** [brookhong/Surfingkeys#2147]
## Error details
I just simply appended `settings.interceptedErrors = ["*"]` to advance mode, without changing anything else in advance mode. But it doesn't take over any error page (in my case, I want surfingkeys to take over unreachable websites so that I can easily add them to surfingkeys proxy setting).

```
// an example to create a new mapping `ctrl-y`
api.mapkey('<ctrl-y>', 'Show me the money', function() {
    Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});

// an example to replace `T` with `gt`, click `Default mappings` to see how `T` works.
api.map('gt', 'T');

// an example to remove mapkey `Ctrl-i`
api.unmap('<ctrl-i>');

// set theme
settings.theme = `
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #24272e;
    color: #abb2bf;
}
.sk_theme tbody {
    color: #fff;
}
.sk_theme input {
    color: #d0d0d0;
}
.sk_theme .url {
    color: #61afef;
}
.sk_theme .annotation {
    color: #56b6c2;
}
.sk_theme .omnibar_highlight {
    color: #528bff;
}
.sk_theme .omnibar_timestamp {
    color: #e5c07b;
}
.sk_theme .omnibar_visitcount {
    color: #98c379;
}
.sk_theme #sk_omnibarSearchResult ul li:nth-child(odd) {
    background: #303030;
}
.sk_theme #sk_omnibarSearchResult ul li.focused {
    background: #3e4452;
}
#sk_status, #sk_find {
    font-size: 20pt;
}`;
// click `Save` button to make above settings to take effect.</ctrl-i></ctrl-y>

settings.interceptedErrors = ["*"];
```

The others:
1. Try on Windows 10 / 11 , doesn't work
2. Beside my daily Chrome configuration, I've tried launching a new Chrome with no any profiles and installing surfingkeys, doesn't work either.

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

URL: any unreachable URLs: http://www.dgdgdggegea.com

**Comment by zxyqq** [comment]
same +1

**Comment by brookhong** [comment]
This has been removed since it is rarely used but need an extra permission `webRequest`, will update the doc soon.
