### ISSUE TITLE
Alt-P and Alt-M do not work on Librewolf browser

### ISSUE THREAD

**Issue by j8s0n** [brookhong/Surfingkeys#2151]
## Error details

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0

URL: Any

## Context

I was trying to pin a tab with Alt-P.  Instead of pinning the tab, I see the following at the bottom:
"ephemeral (1000ms) pass through"
P is supposed to enable ephemeral mode, so maybe it's not catching the Alt. I also tried Alt-M to mute a YouTube video and it did nothing on the first press. On the second, it created a mark "m", so it's clearly not getting the Alt key. Everything works as expected in the Firefox browser on the same machine, so I suspect it's Librewolf stealing the Alt.

**Comment by brookhong** [comment]
Cannot reproduce this on Mac with Firefox 131.0.2. and Surfingkeys 1.17.4.
