### ISSUE TITLE
Broken version on Chrome Web Store

### ISSUE THREAD

**Issue by AndreasNasman** [brookhong/Surfingkeys#2152]
The version uploaded to the Chrome Web Store yesterday is broken; at least `api.Hints.setCharacters` is missing.

![image](https://github.com/user-attachments/assets/611d3323-c4af-490f-8163-2252520121eb)

<img width="1362" alt="image" src="https://github.com/user-attachments/assets/8dc06441-1903-4adc-9bf4-7da0ce5826d5">

I turned off the extension due to security concerns. No commit has been made in the last two months, so uploading a new version to the Chrome Web Store (only) seems a bit suspect as if the extension could have been hacked.

**Comment by mdschmitt** [comment]
The commit you're looking for is here: 82691b006c03547c1385973fa3fced48d9d40ea2 .  Brookhong pushed an update to the web store that was supposed to handle Manifest V3, but it seems to have broken backward compatibility with some stuff.  A fix is incoming, see https://github.com/brookhong/Surfingkeys/issues/2150#issuecomment-2354349777 and #2149
