### ISSUE TITLE
The configurations are all lost

### ISSUE THREAD

**Issue by WillHu** [brookhong/Surfingkeys#2153]
## Error details

The configurations are all lost

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by psych3r** [comment]
Same issue on chrome with version 1.17.0
All configuration are lost and I can't set a configuration file via a file URL...

**Comment by awenaw** [comment]
same

**Comment by bo-ecoexpert** [comment]
Same here.
Vivaldi 6.9.3447.44 (Stable channel) stable (a 64 bit) 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by cvincent** [comment]
Same, I believe it happened sometime yesterday.

**Comment by prss-ad** [comment]
Same here with brave browser nightly or stable.

**Comment by psych3r** [comment]
Removing the extension and installing it again allowed me to load my settings file.
However, some functionalities are broken due to the migration to manifest v3.

**Comment by ljohnston** [comment]
Same here...

**Comment by brookhong** [comment]
Please turn on `Developer mode` from `chrome://extensions/` then restart your browser, it should work, see more https://github.com/brookhong/Surfingkeys/issues/2159

**Comment by WillHu** [comment]
> Please turn on `Developer mode` from `chrome://extensions/` then restart your browser, it should work, see more #2159

It doesn't work. "Developer mode" is always on. Reinstalling it still cannot sovle the issue. 
![Uploading iShot_2024-09-18_20.12.20.jpg…]()

**Comment by iovis** [comment]
Developer Mode worked for me

**Comment by WillHu** [comment]
It works after upgrading chrome to the version 'Version 129.0.6668.59 (Official Build) (arm64)'.

**Comment by MD7GIT** [comment]
Developer Mode worked for me! (Thank you for your work! I really love this extension! I've been using it for a long time)
