### ISSUE TITLE
[SurfingKeys] Error found in settings: TypeError: Hints.setCharacters is not a function - after most recent update

### ISSUE THREAD

**Issue by Stvad** [brookhong/Surfingkeys#2155]
## Error details

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

URL: any

## Context

I have the following line in my settings:
`Hints.setCharacters('arstdqwfpgzxcvbneiouym')`

and that started throwing an error after the latest update

**Comment by clarkwang** [comment]
See discussions here:

* https://github.com/brookhong/Surfingkeys/issues/1821#issuecomment-2353171764
* https://github.com/brookhong/Surfingkeys/issues/1821#issuecomment-2353287958

**Comment by nathanielescribano** [comment]
I'm hitting a similar issue with setNumeric.
[SurfingKeys] Error found in settings: TypeError: Hints.setNumeric is not a function

Looks like it's still a function when i pulled the repo, but not sure if that's whats displayed in the chrome extension store.
(using brave btw)

Any help would be appreciated!

**Comment by allamedo** [comment]
Seems like it can be temporarily fixed with this: https://github.com/brookhong/Surfingkeys/issues/1821#issuecomment-2353171764

**Comment by NoRePercussions** [comment]
Watch out -- it doesn't look like this is a fix. Since `api.Hints.setCharacters`, is not exported, this actually creates a new variable, which is never used. It is effectively equivalent to just removing that line.

**Comment by clarkwang** [comment]
> Watch out -- it doesn't look like this is a fix. Since `api.Hints.setCharacters`, is not exported, this actually creates a new variable, which is never used. It is effectively equivalent to just removing that line.

Right. See Brook's comment here: https://github.com/brookhong/Surfingkeys/issues/1821#issuecomment-2353287958

**Comment by brookhong** [comment]
Fixed in 1.17.1.
