### ISSUE TITLE
[SurfingKeys] Error found in settings: TypeError: Cannot read properties of undefined (reading 'local')

### ISSUE THREAD

**Issue by everiori** [brookhong/Surfingkeys#2156]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

Yes

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes, nothing related found

## Error details

SurfingKeys: 1.17

Browser: Arc Browser 1.60, MacOS

URL:  All the URLs I opened

## Context

**Please replace this with a description of how you were using SurfingKeys.**

Starting from today, I got below error when I open any URL in my browser, I did not update anything in three days, and it worked fine before.

![image](https://github.com/user-attachments/assets/27f496cd-c87b-4b1b-81ec-fdc49ed7db3d)

**Comment by bernieke** [comment]
Same. Downgraded to 1.16.1 as it is completely unusable now.

**Comment by bernieke** [comment]
Fixed it by replacing "chrome.storage.local.set({"noPdfViewer": 1});" with "settings.noPdfViewer = true;" in my config.

(The chrome.storage.local is no longer permitted in the new Mv3 version.)

**Comment by brookhong** [comment]
> Fixed it by replacing "chrome.storage.local.set({"noPdfViewer": 1});" with "settings.noPdfViewer = true;" in my config.
> 
> (The chrome.storage.local is no longer permitted in the new Mv3 version.)

Yes, `chrome.storage` is not allowed in setting snippets, which is a user script from the perspective of Chrome.

**Comment by alwyn** [comment]
Is this something that will be addressed in a plugin release or is the user supposed to go and configure something locally?

**Comment by brookhong** [comment]
There is no way to use `chrome.storage` in setting snippets, but I see most people are using it to turn off pdf viewer, so it makes sense to make sure `settings.noPdfViewer` work well(I believe it does not now).
