### ISSUE TITLE
Only Brave Browser unstable. But other browser has no problem

### ISSUE THREAD

**Issue by datetaku** [brookhong/Surfingkeys#2158]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

## Error details

SurfingKeys:  1.17.0

Browser:  Brave Browser 128.0.6613.138. OS: Windows11 23H2, EndeavourOS (Arch linux),  Linux MInt Mate (Ubuntu)

URL: <The_URL_Where_You_Find_The_Issue>

## Context

Hello, everyone.

I always enjoy using Surfingkeys comfortably. I would like to share my findings regarding the issue where the latest version 1.17.0 does not work. In conclusion, “turning on the developer mode of the extension” is the solution.

Since yesterday, many issues have been created, and I was in the same situation. In my case, it only did not work on the Brave Browser. There were no problems with Google Chrome, Firefox, and Edge. Using the OS, I used were Windows 11, Arch Linux (EndeavourOS), and Ubuntu (Linux Mint Mate), and in all environments, only Brave was unstable.

Lastly, I hope this is helpful. Sorry for my poor English.

**Comment by brookhong** [comment]
Yes, you're absolutely right. To turn on `developer mode` will fix most problems. Thank you, I'll close this.
