### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by qianc62** [brookhong/Surfingkeys#2160]
## Error details

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Please check out https://github.com/brookhong/Surfingkeys/issues/2159
