### ISSUE TITLE
chrome浏览器只能一个用户使用高级模式, 其他用户不能使用本地文件或者网络配置文件

### ISSUE THREAD

**Issue by LoinApex** [brookhong/Surfingkeys#2161]
![image](https://github.com/user-attachments/assets/32d4be9a-acbc-494d-807b-908e20b5b2b4)

 点击保存没有反应

**Comment by brookhong** [comment]
请看下https://github.com/brookhong/Surfingkeys/issues/2159

**Comment by nitang22** [comment]
https://github.com/brookhong/Surfingkeys/issues/2159

**Comment by LoinApex** [comment]
可以了 谢谢~
