### ISSUE TITLE
1.17 now triggers on key presses in fake text elements

### ISSUE THREAD

**Issue by dmfay** [brookhong/Surfingkeys#2163]
## Error details

In the previous version, I could type normally in fake text elements (e.g. [mermaid.live](https://mermaid.live)'s div-and-span editor, Figma/FigJam canvas) without SurfingKeys picking up. After the upgrade, if I try to type "work" in an object that's displaying a text entry cursor, the "w" instead triggers SurfingKeys' focus reset. The letter "r" refreshes the page, "x" closes the tab, "a" pops the usual menu, every keybind is active. Unbound keys like "-" pass through.

Some other fake text entry controls, such as [JSPaint](https://jspaint.app) (which uses a canvas like FigJam), don't seem to be affected.

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by brookhong** [comment]
Fixed in 1.17.3.
