### ISSUE TITLE
mapkey function not working on certain domains 

### ISSUE THREAD

**Issue by Eternity-J** [brookhong/Surfingkeys#2164]
I am creating and using a `api.mapkey` function on a specific domain.

The `api.mapkey` I created for the google.com domain works, 
but the `api.mapkey` I created for my internal groupware domain does not work.

I can't tell you the URL of my internal groupware for security reasons.
It looks like this: https://{---}.or.kr

SurfingKeys: 1.17.0
Browser: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

**Comment by Eternity-J** [comment]
I checked again.
The local configuration file that I set to Advanced mode in a specific domain doesn't work.

**Comment by brookhong** [comment]
Cannot reproduce this.
