### ISSUE TITLE
1.17.0 Advanced settings do not take effect.

### ISSUE THREAD

**Issue by tamanishi** [brookhong/Surfingkeys#2166]
SurfingKeys: 1.17.0
Browser: 129.0.6668.60 (Official Build) (arm64) macOS Version 15.1

When Advanced mode is enabled, the contents of the Advanced settings do not take effect.

I checked the contents of the Advanced settings in Developer tools, it appears that the closing brackets are commented out.

<img width="863" alt="Screenshot 2024-09-26 at 23 21 33" src="https://github.com/user-attachments/assets/4d0f40e1-b1f9-4770-afa9-f06a77e2141b">

<img width="1042" alt="Screenshot 2024-09-26 at 22 55 02" src="https://github.com/user-attachments/assets/f66f677b-a3e8-4f2f-9bb1-4767328b6870">

The last line of the Advanced settings field does not end with a new line character.
<img width="707" alt="Screenshot 2024-09-26 at 22 56 43" src="https://github.com/user-attachments/assets/b7bc7ab9-a8da-4e4a-aa11-c9aac4f3100a">

**Comment by brookhong** [comment]
Looks like there is a bug here. For now, could you just delete the last line then try?

**Comment by tamanishi** [comment]
Thank you for your confirmation.
After removing the last comment line, the Advanced settings now takes effect.

![image](https://github.com/user-attachments/assets/db7d9825-8005-4050-b886-5840db260237)

**Comment by brookhong** [comment]
Fixed in 1.17.1
