### ISSUE TITLE
Is there a keybinding for `Go to previously-visited tab`?

### ISSUE THREAD

**Issue by blurm** [brookhong/Surfingkeys#2167]
Something like `gp` in Vimium. I checked the help page could found it

**Comment by clarkwang** [comment]
`Ctrl-6`

**Comment by blurm** [comment]
> `<Ctrl-6>` - Go to last used tab

Thanks! That's exactly what I want.


> Try `B`
And this is also a very useful keybinding

**Comment by blurm** [comment]
Solved
