### ISSUE TITLE
Shortcut(s) not working on vivaldi

### ISSUE THREAD

**Issue by FabC77** [brookhong/Surfingkeys#2168]
## Error details
I use Vivaldi on my laptop and main PC and use SurfingKeys since 14 months. Since few days I realized that I can't close a tab with the 'x' key. 
I have no idea if something changed on your side or if it's browser related but 'x' doesn't work anymore for me.
By trying to fix the problem, I tried to access the settings with ;e  but it didn't work as well. I think something is glitched.

SurfingKeys: (i don't know how to find the version and the dropmenu doesn't show the version
Browser: Vivaldi - 6.9.3447.48

Sorry if I wasn't very helpful, I don't have the time to read all the tickets, changelogs, etc.

**Comment by FabC77** [comment]
I just noticed I can't open link with "cf" anymore

**Comment by brookhong** [comment]
Have you read the pinned issue -- https://github.com/brookhong/Surfingkeys/issues/2159?

**Comment by FabC77** [comment]
Thank you! It solved the issue.
