### ISSUE TITLE
1.17.1 Many custom settings do not work

### ISSUE THREAD

**Issue by gdm257** [brookhong/Surfingkeys#2169]
## Error details

SurfingKeys: 1.17.1

Browser: Chromium 127.0.6533.100 Windows

URL: -

## Context

`settings.smoothScroll = false` is woking in 1.17.0. After today's update of 1.17.1, it takes no effect.

Update: According to other users' feedback, many custom settings also do not work.

**Comment by rubaboo** [comment]
After 1.17.1 update, I cannot disable Surfingkeys itself. Not via Alt+S nor from the extension button's popup menu.
My browser is Vivaldi, if that matters.

**Comment by gdm257** [comment]
> After 1.17.1 update, I cannot disable Surfingkeys itself. Not via Alt+S nor from the extension button's popup menu. My browser is Vivaldi, if that matters.

Same

**Comment by ljohnston** [comment]
Using Vivaldi also. After 1.17.1 update, many of my settings are being ignored. For example, I have the following keys mapped:

```
api.mapkey('gh', "Open google in the current tab", function() {
    window.location.href = 'https://google.com';
});

api.mapkey('gH', 'Open google in a new tab', function() {
    api.tabOpenLink('https://google.com');
});

```
After the 1.17.1 upgrade those key mappings are totally ignored. Bringing up the help screen shows the following:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/e400beec-3fb7-41b0-b67c-81627607724a">

I also have key mappings like this that are being ignored:
```
api.map('<Ctrl-[>', '<Esc>');
```
My theme settings are being ignored also.

Interestingly, I don't see any of these issues with 1.17.1 in Google Chrome.

**Comment by momotaro** [comment]
> Using Vivaldi also. After 1.17.1 update, many of my settings are being ignored. 

Same

**Comment by zoommine** [comment]
> After 1.17.1 update, I cannot disable Surfingkeys itself. Not via Alt+S nor from the extension button's popup menu. My browser is Vivaldi, if that matters.

Same

**Comment by clarkwang** [comment]
+1

**Comment by 42Craft** [comment]
Same

**Comment by hengfei-wang** [comment]
same

**Comment by LawlietNot** [comment]
same

**Comment by owenstake** [comment]
+1

**Comment by brookhong** [comment]
This should also be fixed in 1.17.3.

**Comment by clarkwang** [comment]
> Vivaldi w/ 1.17.3 all custom configuration is still ignored.

I have the same issue (#2179) after 1.17.3 update. For me, disable and then re-enable "Advanced mode" works.

**Comment by ljohnston** [comment]
Thank you @clarkwang - toggling "Advanced mode" in that setting worked for me. I also had to restart Vivaldi after doing so.

**Comment by petobens** [comment]
I did all the toggling advance mode thing and restarting but for mappings like:
```
mapkey('<Ctrl-c>', 'Close tab', function () {
    RUNTIME('closeTab');
});
```
I still need to press the mapkey `Ctrl-c` twice for  it to take effect. Any pointers @brookhong? Thanks

**Comment by Madd0g** [comment]
@petobens - I'm suffering from this too, today I wrote this silly helper that runs it twice.

```js
function getActiveTab() {
  return new Promise((resolve) => {
    RUNTIME("getTabs", { queryInfo: {}, query: {} }, (response) => {
      const activeTab = response.tabs?.find((t) => t.active && t.selected);
      resolve(activeTab);
    });
  });
}
async function fixedCloseTab() {
  let oldActiveTab = await getActiveTab();
  RUNTIME("closeTab");
  await new Promise((resolve) => setTimeout(resolve, 20));
  let newActiveTab = await getActiveTab();
  if (newActiveTab?.id === oldActiveTab?.id) {
    RUNTIME("closeTab");
  }
}
```

Not sure how well this works with multiple windows

**Comment by clarkwang** [comment]
> I did all the toggling advance mode thing and restarting but for mappings like:
> 
> ```
> mapkey('<Ctrl-c>', 'Close tab', function () {
>     RUNTIME('closeTab');
> });
> ```
> 
> I still need to press the mapkey `Ctrl-c` twice for it to take effect. Any pointers @brookhong? Thanks

Mapping `<Ctrl-c>` to `x` (Close current tab) works just fine for me.
