### ISSUE TITLE
SurfingKeys does not disable on Chrome

### ISSUE THREAD

**Issue by Hey-S1r1** [brookhong/Surfingkeys#2171]
## Error details

SurfingKeys refuses to disable on chrome.

SurfingKeys: 1.17.1

Browser: Chrome/129.0.0.0 

URL: EVERYWHERE

## Context

I was trying to disable SurfingKeys for schoolwork, and later for YouTube, but it refused to disable unless I disabled the entire extension from the extension manager on chrome. Alt+s shows text saying that it has been disabled, but the extension keeps working. Clicking on the extension itself and disabling it for the browser does not work either. I tried reinstalling the extension, but nothing changed. Fortunately, I have not seen such an issue on Firefox yet, but I am unable to use Firefox for some of my schoolwork.

**Comment by abdelkarimjaja** [comment]
same issue :)

**Comment by JvdB01** [comment]
same issue here
> I'm not sure whether to report if, but yes, same issue here.
> 
> for a workarround:
> 
> ```
> api.unmapAllExcept(['yy'], /whatsapp.com/);
> ```
> 
> I'm sure there is a better workarround, this was already in my config.

I'd say removing the ```['yy'],``` part makes it work a bit more like expected, as it otherwise also maintains number functionality, meaning pages that require number buttons to be pressed won't work as they should, but aside from that, this does seem like it's a good workaround for now.

**Comment by leroyz84** [comment]
> same issue here
> 
> > I'm not sure whether to report if, but yes, same issue here.
> > for a workarround:
> > ```
> > api.unmapAllExcept(['yy'], /whatsapp.com/);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm sure there is a better workarround, this was already in my config.
> 
> I'd say removing the `['yy'],` part makes it work a bit more like expected, as it otherwise also maintains number functionality, meaning pages that require number buttons to be pressed won't work as they should, but aside from that, this does seem like it's a good workaround for now.

Sorry, it worked for me :-) 
you could use 
```
 api.unmap('/docs.google.com/');
```
 perhaps?

**Comment by brookhong** [comment]
Fixed in 1.17.3.
