### ISSUE TITLE
cannot go to next page with ]] on 1.17.1

### ISSUE THREAD

**Issue by AnabasisXu** [brookhong/Surfingkeys#2172]
Uncaught TypeError: t.test is not a function
  at content.js:3:34214
    at g (content.js:3:29072)
    at U (content.js:3:34062)
    at n.nextPage (content.js:3:89022)
    at re.handleMapKey (content.js:3:45018)
    at content.js:3:48439
    at se (content.js:3:41686)
    at keydown (content.js:3:42040)

function U(e, t) {
    return P(g(document.body, NodeFilter.SHOW_ELEMENT, (function(n) {
        return n.offsetHeight && n.offsetWidth && "pointer" === getComputedStyle(n).cursor 
            && (n.matches(e) || (t instanceof RegExp && (t.test(n.textContent) || t.test(n.getAttribute("aria-label")))));
    })));
}

**Comment by brookhong** [comment]
Fixed in 1.17.3.

**Comment by AnabasisXu** [comment]
Thanks Brook!
