### ISSUE TITLE
Disable and Enable keybinding won't working any More on Chrome 

### ISSUE THREAD

**Issue by abdelkarimjaja** [brookhong/Surfingkeys#2173]
## Error details
As mentioned in the default configuration, Alt-S enables users to disable and enable Surfingkeys keybinding for the actual tab on **Chrome Version 129.0.6668.89 (Build officiel) (64 bits)**. 
Recently I've encountered this issue whenever I want to disable/enable it it doesn't work 
Do you have any tips to resolve this issue?

SurfingKeys: 1.17.1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by candera** [comment]
Same.

**Comment by kubeliv** [comment]
Seeing the same behavior. I tried uninstalling and reinstalling the extension from the Chrome Web Store (I am on Vivaldi). The little popup shows up saying turned "OFF" or "ON" for a website - but regardless of what state it is in, it is still enabled and makes it impossible to use certain websites.

**Comment by cliffxuan** [comment]
I've got the same issue. 
Now I use a different browser for websites which I need the hotkeys of the website itself.

**Comment by yg-i** [comment]
Anyone's found any solutions? I need to disable the extension for youtube.com, but the solution suggested on another recent thread (`api.unmap('/youtube.com/');`) doesn't work for me.

**Comment by Archie-2021** [comment]
Same here, I am using Brave on Linux. The message shows for "On" and "Off" state, but has no effect and surfingkeys keeps working nevertheless.

**Comment by mizagog** [comment]
Same on Chrome

**Comment by clarkwang** [comment]
See https://github.com/brookhong/Surfingkeys/issues/2157

**Comment by Archie-2021** [comment]
> See #2157

Reading that , doesn't look like to be the same. people say it works but it is not persistent per site there. But my problems is that it doesn't work at all anymore.

**Comment by clarkwang** [comment]
> > See #2157
> 
> Reading that , doesn't look like to be the same. people say it works but it is not persistent per site there. But my problems is that it doesn't work at all anymore.

According to Brook it's not fixed yet: https://github.com/brookhong/Surfingkeys/issues/2157#issuecomment-2381360983

**Comment by yet-another-tim** [comment]
+1

**Comment by pendulm** [comment]
+1

**Comment by patrick-zhang-work** [comment]
+1

**Comment by ed-chiang-tw** [comment]
same

**Comment by brookhong** [comment]
Fixed in 1.17.3.
