### ISSUE TITLE
`T` (Choose a tab) doesn't work in a window with single tab

### ISSUE THREAD

**Issue by iSeeU816** [brookhong/Surfingkeys#2178]
Hello,

Here are some scenarios where `T` ("Choose a tab") doesn't function as
it should be.

These scenarios tested with this setting in mind:

```javascript
// Always use Omnibar to search/choose opened tabs.
settings.tabsThreshold = 0;
```

## Scenario A

A window with single tab.

1. Hitting `T` does nothing.

## Scenario B

Several tabs in two windows.

1. Hit `W` ("Move current tab to another window") in a random tab.
   1. Choose the prompt of "Move current tab to window" Omnibar to
      create a new window.
   2. Hit `enter` to confirm that.
2. A new window is now created with that tab, will refer to it as "foo" tab.
3. In this "foo" tab, hitting `T` will do nothing.

## Scenario C

Same scenario B but with a minor change.

1. Follow steps in scenario B.
2. In the new window, where the "foo" tab is in, create another tab.
3. Go back to the "foo" tab, hit `T`. Now it's WORKING!
4. But, if you close this new tab, and now have only the "foo" tab, the
   issue is back with `T` key binding.

## Remarks

From the scenarios above, `T` doesn't work if a window has one tab.
This makes it hard to work with multiple windows.

I hope you fix this. Thank you!

## Info

- Google Chrome.
- Surfingkeys: v1.16.1; rev f152a9a on 2024-10-11

**Comment by brookhong** [comment]
This is expected, `T` is built to choose tab within current window.
