### ISSUE TITLE
[v1.17.3] All my key mappings are not working

### ISSUE THREAD

**Issue by clarkwang** [brookhong/Surfingkeys#2179]
Example conf <sup>(works fine with v1.16.1)</sup> to reproduce:

~~~js
const {
    Hints,
    Normal,
    RUNTIME: Runtime,
    imap,
    map,
    mapkey,
    tabOpenLink: tabopen,
    unmap,
    unmapAllExcept: unmap_ex,
} = api;

//
// go one tab left
//
map  ('__E', 'E');
unmap('E');
map  ('H', '__E');

//
// go one tab right
//
map  ('__R', 'R');
unmap('R');
map  ('L', '__R');
~~~

**Comment by clarkwang** [comment]
I dont know the exact steps but after disable/enable dev mode and disable/enable surfingkeys it started working again. Closing for now...

**Comment by clarkwang** [comment]
Tried on a few other computers and confirmed disabling "Advanced mode" and then re-enabling it works for me.

**Comment by blurm** [comment]
Just saved my day. Thanks
