### ISSUE TITLE
Unrecognized key event: <AltGraph>

### ISSUE THREAD

**Issue by svigneux** [brookhong/Surfingkeys#218]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 225,
    "code": "AltRight",
    "composed": true,
    "key": "AltGraph"
}

SurfingKeys: 0.7.2

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## Context

Trying to type the @ sign on a canadian french keyboard. 

```
➜  ~ setxkbmap -query | grep layout
layout:     ca
➜  ~ 
```

Thanks for this wonderful extension!

**Comment by brookhong** [comment]
Thanks, it should be fixed in 0.7.3.

**Comment by svigneux** [comment]
:+1:
