### ISSUE TITLE
[Bug] `api.Front.showEditor` does not work

### ISSUE THREAD

**Issue by letuanhai** [brookhong/Surfingkeys#2183]
## Error details
Mapping a key map with the api `Front.showEditor` does not work, while `Front.openOmnibar` and others work correctly.
When I invoke the key map, an error is show in console: `Uncaught TypeError: api.Front.showEditor is not a function`

SurfingKeys: 1.17.3

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

URL: `example.com`

## Context
Below is my config file:
```js
api.mapkey(';v', 'Test showEditor', function() {
    api.Front.showEditor(window.location.href, function(data) {
        window.location.href = data;
    }, 'url');
});
```

**Comment by brookhong** [comment]
`showEditor` has never been exported before, for your case, it would better to remap `;u`.

**Comment by letuanhai** [comment]
Thanks for your reply. In that case, shouldn't it be removed from the docs, or at least add a "not implemented" note to avoid the confusion?

**Comment by brookhong** [comment]
Looks like I missed something, `showEditor` had been published before, will publish it. @blacklight Thank you for your PR, but your PR does not work for MV3.
