### ISSUE TITLE
vmap setting not work

### ISSUE THREAD

**Issue by kesdoputr** [brookhong/Surfingkeys#2184]
SurfingKeys: 1.17.3

Browser: Microsoft Edge 130.0.2849.46  Windows 10 Home x64 22H2

SurfingKeys  still 1.13.0 on edge addon, so i install 1.17.3 on chrome

I have two vmap setting can't work after update

```
const {
    aceVimMap,
    mapkey,
    vmapkey,
    imapkey,
    map,
    unmap,
    unmapAllExcept,
    imap,
    iunmap,
    cmap,
    vmap,
    vunmap,
    getClickableElements,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME
} = api;

vmap('i', '0');
vmap('o', '$');
```

The key i and o can't work when i press on visual mode, how can i fix it? 
Thanks for your reply.

**Comment by Tback1** [comment]
I have this question too. from 1.17.0 to  1.17.3, both have this question

我也遇到这个问题,从1.17.0到1.17.3都存在该问题.所有的api.unmap等配置都没有起任何作用
