### ISSUE TITLE
User settings don't work in `file:///` and PDF viewer of SK (v1.17.3)

### ISSUE THREAD

**Issue by iSeeU816** [brookhong/Surfingkeys#2186]
Hello,

User settings don't work with pages of the type `file:///` and PDF
viewer of Surfingkeys. I've tested this with a clean profile of Google
Chrome and Surfingkeys v1.17.3 that I installed it from Chrome Web Store
and, also, with a version that I built from "mv3" branch.

## Steps to reproduce the bug

1. Install latest version of Surfingkeys (currently v1.17.3).
2. In "chrome://extensions" page: Enable "Developer mode".
3. In this extension's "Details" page, enable "Allow access to file
   URLs".
4. Click on the extension's icon on the toolbar of Chrome then on
   "Settings".
   1. Enable "Advanced mode" then click on "Save".
5. Try one of these steps to reproduce the bug:
   1. Visit a local HTML file.
   2. Visit a PDF to view it with Surfingkeys PDF viewer.
6. Now, try to call `oh` ("Open URL from history"). Notice that the
   theme still light and NOT dark as it should be, and that based on the
   provided settings in Surfingkeys's settings page.
    - This is just an example. Another example is when a user unbound a
      key binding, it must still be unbound in all pages.

## Remarks

This is a serious bug since the user expects the extension to function
the same in all pages. A user might unbound a key binding that deletes
something, and might trigger that key binding by accident in one of the
aforementioned pages (`file:///` and PDF viewer).

Thank you!

## Info

- Google Chrome.
- Surfingkeys: 1.17.3; rev 4915664 on 2024-10-13

**Comment by brookhong** [comment]
It would be possible make user snippets work with `file:///`, but it seems to be impossible to make it work with PDF viewer in `chrome-extension://` as which is restricted by Chrome itself. You could try https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html
