### ISSUE TITLE
Visual mode: sentence, paragraphboundary, documentboundary functions don’t work on Firefox

### ISSUE THREAD

**Issue by Fred-Vatin** [brookhong/Surfingkeys#2188]
### Issue
In visual mode using any of those functions fail:
![image](https://github.com/user-attachments/assets/563e3f77-dfe1-4314-ab33-7f8c80ba6b27)

With this function, only the paragraph fails.
![image](https://github.com/user-attachments/assets/523a100c-56c7-4c5b-9ee6-aeb452bcc4dd)

I tried to remap the keys to see if it was a problem with my layout or else. No avail.

It works with v1.17.3 on Vivaldi.

### Setup
- ❌ Firefox 131.0.3, SK 1.16.1
- ✅ Vivaldi 7.0.3495.6, SK 1.17.3
- OS Win 10 pro 22H2

**Comment by brookhong** [comment]
`(, ), {, }` won't work due to this

<img width="678" alt="image" src="https://github.com/user-attachments/assets/55836c1d-a5c7-4052-85e3-e78f57cdad8d">

https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify

`G, gg` should work.

**Comment by Fred-Vatin** [comment]
Thanks. For later reference, there is an open bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1699087 and the w3c describe the api at https://w3c.github.io/selection-api/#dom-selection-modify.
