### ISSUE TITLE
Unrecognized key event: <GroupFirst>

### ISSUE THREAD

**Issue by hypnoglow** [brookhong/Surfingkeys#219]
## Error details
```
{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 0,
    "code": "CapsLock",
    "composed": true,
    "key": "GroupFirst"
}
```

SurfingKeys: 0.7.2

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## Context

Pressing CapsLock is bugged for me. It shows **Uh-oh! The SurfingKeys extension encountered a bug.** popup each time CapsLock is pressed.

**Comment by brookhong** [comment]
Thanks, it should be fixed 0.7.3
