### ISSUE TITLE
Continued support for Manifest V2

### ISSUE THREAD

**Issue by agguser** [brookhong/Surfingkeys#2197]
As some functions do not work in Manifest V3, and some browsers will continue support Manifest V2 (e.g. Firefox, Edge), so please make an updated release (with bugs fixed, new features) for V2 in those browsers (and maybe in addition to a V3 release, like uBlock Origin having both V2 and V3 (as uBlock Origin Lite)).

**Comment by brookhong** [comment]
I'm considering to merge the branches, so that both V2 and V3 can be built from a single branch, and then V2 and V3 will be released in same cadence as before.

**Comment by brookhong** [comment]
Closing this as now V2 and V3 will be released from a single branch.

**Comment by agguser** [comment]
Please release a V2 version too (you may name it something like "Suringkeys V2"), which is more permissive that V3.
