### ISSUE TITLE
All hints have the correct theme, except `;fs` to focus scrollable elements

### ISSUE THREAD

**Issue by clementpoiret** [brookhong/Surfingkeys#2199]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

NO

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

YES

## Error details

SurfingKeys: 1.16.1

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0

## Context

All hints have the correct theme, except `;fs`.

When triggering [`;fs`](https://github.com/brookhong/Surfingkeys/blob/f152a9a831ed4c357f072a531400d62c226be974/src/content_scripts/common/api.js#L713), the theme of the hints is as follows:

![2024-11-05-At-06h58m47s](https://github.com/user-attachments/assets/93b15784-863e-4c14-a325-85727873f567)

However, when using [`f`](https://github.com/brookhong/Surfingkeys/blob/f152a9a831ed4c357f072a531400d62c226be974/src/content_scripts/common/api.js#L670) to hint links to open them in the current tab, the theme is correct:

![2024-11-05-At-06h59m11s](https://github.com/user-attachments/assets/143010b2-0e27-4ff7-ae78-5bad221f1b13)

Link to my current config: https://github.com/clementpoiret/nixos-config/blob/b84c3e7e7f27370f79bafe9a3a7dc52692ba773a/misc/firefox/surfingkeys.js

**Comment by brookhong** [comment]
That's because hints for scrolling are created with an extra class `hint-scrollable` for differentiation -- https://github.com/brookhong/Surfingkeys/blob/728e01168b800d6e83909642558b8327c186d65e/src/content_scripts/common/hints.js#L48.

Text color changes as you can see.

**Comment by clementpoiret** [comment]
Oh nice, thanks for the pointer, I updated my config to make it work! Thanks again for surfingkeys, it's miles ahead of other plugins
