### ISSUE TITLE
is there a chance arrow keys will be added to visual mode and menus? (+couple more suggestions)

### ISSUE THREAD

**Issue by zldrq** [brookhong/Surfingkeys#22]
after i left comment on chrome webstore, i saw you said it is better to add issues, so i decided to duplicate as issue here. i've created enough issues already, so all left suggestions here:
- is there (or will be) way to bind caret movement keys also to arrow keys and pgup,pgdn,home,end in visual mode?
- and also in menus (which are navigated with tab/shift+tab now)
- another one: bind 'V' to go back from range mode to caret mode?
- also, i've seen you mention big caret for visibility. i may suggest you to "borrow" mechanics from here:
  https://chrome.google.com/webstore/detail/caret-browsing/fklpgenihifpccgiifchnihilipmbffg
  (first option (black rectangle) is better imho, btw)
- introduce "learning mode"! for noobs as i am. when user presses key, it is not only a key displayed in lower right conner, but all possible key combinations with descriptions: 
  let's assume he presses `o` and in lower right he sees (alignet by right side):

| _ | **o** |
| --- | --- |
| Open URL from history | **~h** |
| Open URL from vim-like marks | **~m** |
| Open Search with alias b | **~b** |

and so on. in some cases the tooltip will be large, but that's ok, as it is just for the learning time,
there may be another option, to show later only custom definitions like for searches with alias for example

**Comment by dufferzafar** [comment]
Yeah, I'm missing arrow keys in the visual caret mode as well. I'll have a look at the default bindings to see if I can do something.

**Comment by nimser** [comment]
For my use this is essential. I tried the following, which does not work. Could it be that the browser (Firefox) is interpreting the key before the extension?

```
vmap('<Left>', 'h');
vmap('<Down>', 'j');
vmap('<Up>', 'k');
vmap('<Right>', 'l');
```
