### ISSUE TITLE
Unrecognized key event: <AltGraph>

### ISSUE THREAD

**Issue by krzemian** [brookhong/Surfingkeys#220]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 225,
    "code": "AltRight",
    "composed": true,
    "key": "AltGraph"
}

SurfingKeys: 0.7.2

Chrome: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36

## Context

It seems that pressing right alt causes the plugin to crash. I have already reset the mapping settings and checked it in Chromium Incognito mode with other plugins disabled, both to no avail.
An additional clue is that it started somewhere around the same time I plugged in an external bluetooth keyboard. I sometimes experience system-wide problems with keycoding (not able to use Polish diacritics at times). My workaround for this was to type something on the built-in laptop keyboard, which seemed to bring back the correct language mapping in the external keyboard for some time.

**Comment by brookhong** [comment]
Thanks, it should be fixed 0.7.3
