### ISSUE TITLE
unmap for subpage only work after refreshing the page

### ISSUE THREAD

**Issue by cantfindname** [brookhong/Surfingkeys#2200]
## Prelude
Custom unmap does not work going from website to subwebsite, but does work after refreshing the said subwebsite page. 

## Error details

SurfingKeys: 1.17.3

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

URL: Going from https://www.youtube.com/ to https://www.youtube.com/watch?v=Hxu8YQFjXew&t=34s

## Context

I only want to unmap keybindings when I click into a Youtube video (e.g. https://www.youtube.com/watch?v=l8E5GpRuiqg) while maintaining the ability to use vim keybindings on youtube homepage (https://www.youtube.com/). I can still use all SurfingKeys keybindings after clicking into a video from YouTube homepage, however, this bug resolves itself upon refreshing the YouTube video page.

This is what I have in settings: 

api.unmapAllExcept(['r', 'yy', 'J', 'K', 'I', 'U'], /youtube.com\/+.+/);

**Comment by brookhong** [comment]
Yes, that is expected just after you updated your settings, as the extension needs to detect the change and register it into user script on first page loading, then it will run the newly update snippets on second page loading. But that happens only once, the new snippets will be used since then.

**Comment by cantfindname** [comment]
> But that happens only once, the new snippets will be used since then.
This behavior of refreshing webpage for that specific line of user script to take effect does not disappear after the first time. 
Unless you are saying that every time I get to that specified webpage, it is expected to refresh the page for user script to have an effect, then that defeats the purpose of having this function, I believe.

**Comment by brookhong** [comment]
Ok, I misunderstood the issue.

And now I think I found the cause of this issue -- there is actually no page reloading when going from https://www.youtube.com/ to https://www.youtube.com/watch?v=Hxu8YQFjXew&t=34s, and I thought the URL might be changed by [History: pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState), but some tricky code seems to be used here -- the URL even doesn't change on `navigate` event.

You can run below code on https://www.youtube.com/ with Inspect tool

    navigation.addEventListener('navigate', () => {
        console.log(document.location.href);
    });

then click on any video, you can see only https://www.youtube.com/ printed.
