### ISSUE TITLE
The  video of recommendation bar of bilibili.com can not be opened using f

### ISSUE THREAD

**Issue by linzhi555** [brookhong/Surfingkeys#2204]
## Error details

![surfkey_issue](https://github.com/user-attachments/assets/544b3798-97a6-4c12-a918-c7d7c8dfdbf6)

SurfingKeys: 1.74.1

Browser: brave 1.59.100
URL:  https://www.bilibili.com/video/BV1aPDHY7EDP/?spm_id_from=333.1007.tianma.1-2-2.click&vd_source=0a01ef124c1fc3845a6f97d2c394c81a

## Context
I find  there is no response when i try to choose  one link. There is no response, no matter clicking the image or the title.
I find the URL of the page is changed  but the video still is the old. Maybe the page is a single page App originally.
I have read the source code of SurfingKey a little. And I modify the src/content_scripts/common/hints.js:204 to always use openLink  rather than dispatch mouse event when click href element.  
It's work for me, but I do not know  the modification is safe. I need professional advice.
``` js

            var tabbed = behaviours.tabbed, active = behaviours.active;
            if (behaviours.multipleHits) {
                const href = element.getAttribute('href');
                if (href !== null && href !== "#") {
                    tabbed = true;
                    active = false;
                }
            }

            //my modification: alway open element with href using openLink rather than simulate mouse click
            const href = element.getAttribute('href');
            if (href !== null) {
                tabbed = true;
                active = true;
            }

            if (shiftKey && runtime.conf.hintShiftNonActive) {
                tabbed = true;
                active = false;
            } else if (shiftKey && getBrowserName() === "Firefox") {


```

**Comment by brookhong** [comment]
Such change will make all links to be opened in a new tab, which is not acceptable from user experience. For now, as a workaround, you can just use `af` for those links.
