### ISSUE TITLE
Hint overlay is off (how to make hints show at the `start` of the link like Vimium/Vimari)

### ISSUE THREAD

**Issue by nikitavoloboev** [brookhong/Surfingkeys#2213]
This is [Vimium](https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en):

<img width="913" alt="image" src="https://github.com/user-attachments/assets/2225cf90-f219-42f3-abcf-64f3a5871bf0">

And this is Surfingkeys:

<img width="929" alt="image" src="https://github.com/user-attachments/assets/ba2d6658-5ee7-4111-81e1-17f5dc9e69dd">

I personally prefer Vimium as it actually overlays the hints on the links. Perhaps it's personal preference but is it possible to make Surfingkeys to work like Vimium for hints?

**Comment by nikitavoloboev** [comment]
I just realized that Vimium's model is simple. It starts the hint at the `start` of the hyperlink.

Whilst Surfingkeys algorithm is weird, it's like at 60% of the hyperlink.

Is it possible to make it work like Vimium and start it at the `start` of the link?

**Comment by nikitavoloboev** [comment]
I also use Safari and [Vimari](https://github.com/televator-apps/vimari) extension and in there it works like Vimium too:

<img width="922" alt="image" src="https://github.com/user-attachments/assets/bb642cba-5003-4ca2-9935-905646ca93d4">

So yes, I really wish I can make Surfingkeys work the same way too. 🙏

**Comment by badxnach** [comment]
You can put this in your (advanced) settings:
settings.hintAlign="left";
