### ISSUE TITLE
SurfingKeys not working on specific site in Firefox, though works in Chrome

### ISSUE THREAD

**Issue by kings2u** [brookhong/Surfingkeys#2216]
## Context

Surfingkeys works with the website https://le.utah.gov/xcode/code.html on Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit), but it does not work on Firefox Version 133.0 (64-bit). I've checked that my SurfingKeys config is the same for both browsers.

(Sorry if this is not a worthy bug report; I looked in the FAQ and couldn't find a different way to report such a bug) 

Thank you!

**Comment by brookhong** [comment]
Works for me with 1.17.5.
<img width="863" alt="image" src="https://github.com/user-attachments/assets/c202a89b-8e49-48a8-8c2a-c5bc7ca71b9f">

**Comment by kings2u** [comment]
I'm so sorry, I had accidentally hit the Alt+s shortcut, temporarily disabling Surfingkeys on the site. I'll close this issue. 

It would be nice to have the option to disable that keyboard shortcut in the browser settings, but I can't complain: I can't live without this extension!
