### ISSUE TITLE
two questions and a feature request

### ISSUE THREAD

**Issue by raulchen** [brookhong/Surfingkeys#225]
Hi there,

Thanks for developing such an awesome app. I've been playing with Surfingkeys for a while and have some questions about it:

1) is it possible to return to normal mode with query highlighting (instead of visual mode) after search with '/'? 
2) is there a way to use Chrome's native order for opening a tab in the background? I searched around the code, it seems that only available options are 'left', 'right', and 'first'.
3) A feature request: it would be nice if Surfingkeys could have the functionalities of attaching a tab to another window and dettaching a tab from current window, like cVim does.

Thanks

**Comment by brookhong** [comment]
1. There is no better way to jump among the occurrences if we don't enter visual mode.

1. just use "default", such as,

        settings.newTabPosition = "default";

1. Thanks, will be released in next version, `W` is created to toggle current tab as a separated window.

**Comment by raulchen** [comment]
@brookhong thanks for your reply. 
As for point 1, what cVim does is going back directly to normal mode and allowing you to jump through occurrences with n/N. In this way, you can also navigate with j/k if you want to check the context of an occurrence.
IMHO, that feels more natural. Also understand other people have different different preference. So, it would be great if this can be added as an option.
Thanks again.
