### ISSUE TITLE
g0 and g$ break because of dependency on E and R keybindings

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#228]
In my settings file I remap <kbd>E</kbd> and <kbd>R</kbd> to <kbd>J</kbd> and <kbd>K</kbd> to match Vimium's behavior.  When I unmapped the now unused commands, <kbd>g0</kbd> and <kbd>g$</kbd> broke because they had definitions that depended on them.  I tried the following remapping but to no avail.

```javascript
map('K', 'R');
map('J', 'E');
map('g0', ':feedkeys 99J', 0, "#3Go to the first tab");
map('g$', ':feedkeys 99K', 0, "#3Go to the last tab");
unmap('R');
unmap('E');
```

**Comment by brookhong** [comment]
Above settings work for me. Are you still having this issue with 0.7.3?

**Comment by ddickstein** [comment]
Yes, and now on 0.7.4.

**Comment by ddickstein** [comment]
My current work-around is

```
mapkey('K', '#3Go one tab right', 'RUNTIME("nextTab")'); //map('K', 'R');
mapkey('J', '#3Go one tab left', 'RUNTIME("previousTab")'); //map('J', 'E');
map('g0', ':feedkeys 99J', 0, "#3Go to the first tab");
map('g$', ':feedkeys 99K', 0, "#3Go to the last tab");
unmap('R');
unmap('E');
```
