### ISSUE TITLE
Omnibar does not support regular URLs

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#229]
The "Open a URL" (<kbd>t</kbd>) / "Open a URL in current tab" (<kbd>go</kbd>) commands launch the Omnibar but can't actually open a standard URL...  I think a much more useful and intuitive behavior would be for options to be populated below but for the default, at least for those commands, to be to just enter the URL as typed.  Currently the default just dumps you into Google, so if you type a new URL for the first time you end up Google searching for that URL.  Especially given that there are a ton of shortcuts for running Google searches, I think it's the wrong default behavior here.

More user-friendly behaviors would be:

1. Try to interpret what is typed as a URL, fall back to Google if it can't be interpreted that way (same way Google Chrome's omnibox works).

2. Do not start highlighting the first option in the dropdown.  If I type "facebook.com" into the omnibar and hit enter, I don't want to be taken to the first link from my history that matched facebook.com, I want to be taken to facebook.com proper.  Show me those options, but let me choose that behavior by pressing <kbd>Tab</kbd> to drop into the list.

**Comment by deluxghost** [comment]
same problem

I just don't wanna press F6

**Comment by isaif** [comment]
So how does this feature work? I still go to search instead of opening the url while using 'go' or 't'.
