### ISSUE TITLE
[question] Can we remove the default search engines?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#230]
Is there a way to remove default search engines?  There seems to be an option for `addSearchAlias` but not `removeSearchAlias` to disable the defaults.  Optionally, the defaults other than Google could be removed and recommended as optional configs users could add on their own.  Keeping the defaults minimalistic seems like a better approach for encouraging adoption (I unmapped many defaults because they don't fit my workflow).

**Comment by brookhong** [comment]
Thanks, will be released in next version.
