### ISSUE TITLE
[question] what is "mouse out last element"?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#231]
What does the "mouse out last element" (mapped to <kbd>;m</kbd>) do?

**Comment by brookhong** [comment]
Follow link(`f`) by default will trigger events -- 'mouseover', 'mousedown', 'mouseup', 'click', but no 'mouseout`.

It works fine for 99% of links, but for some javascript href targets, some popover are triggered, then `;m` here is to dismiss the popover.
