### ISSUE TITLE
[question] What is the difference between a frame and a scroll target?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#232]
The scroll options map <kbd>cs</kbd> to "Change scroll target" and <kbd>w</kbd> to "Switch frames."  Can you clarify what a frame is, how it differs from a scroll target, and when <kbd>w</kbd> would come in handy over <kbd>cs</kbd> or any of the mouse clicking options?

**Comment by brookhong** [comment]
`w` is to switch focus between windows in frames -- [iframe](http://www.w3schools.com/tags/tag_iframe.asp).

`cs` is to change scroll target, when there are multiple elements in current window could be scrolled, whether it is a `body` or a `div`.

With them, you could use keyboard as much as it could.
