### ISSUE TITLE
[feature request] Allow option for syncing settings with Chrome profile

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#233]
I'd like to be able to sync my settings with my Chrome profile so updates appear on all my computers.  It looks like I can do this by maintaining my settings in a common repository, but this would be a nice option to have.

**Comment by zeltak** [comment]
+1

**Comment by brookhong** [comment]
It is now using chrome.storage.sync to sync settings, but Chrome has quota for each item, so that sync will not work if snippet is too long.

**Comment by ddickstein** [comment]
It seems like a small quota / pretty easy for a heavy user's settings to exceed that limit, and the syncing then causes settings to disappear, which is far worse than just not syncing imo.  That's a disappointing Chrome limitation.  Maybe allow syncing to be toggled?

**Comment by ddickstein** [comment]
I didn't notice the "Load settings from" feature, which makes updating settings much less painful.  Given that, I think this is probably pretty low pri.
