### ISSUE TITLE
When not connected to Internet this plugin may lead to issues.

### ISSUE THREAD

**Issue by ClassicOldSong** [brookhong/Surfingkeys#235]
When Internet connection broke, this plugin will refresh new pages again and again, making the browser unusable. Plz fix this, thanks.

**Comment by brookhong** [comment]
I can not reproduce this issue, could you reset your settings to see if it could fix your problem?

**Comment by ClassicOldSong** [comment]
It says `reload triggered by runtime disconnection.`
It seems to getting worse recently even when connection is stable but I have no idea about what's happening.

**Comment by mu-yu** [comment]
sam issue for me, and even worse. `win10 chrome 56`
it will reload every page i load for infinity loop.

I found some error log in popup.html

```
popup.html:1 Refused to load the script 'chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/common_content.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'sha256-k6whJ99igQgqhch6A63JlRxd/4DZ7RT1fWyunKDcZ3U='".

popup.html:1 Refused to load the script 'chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/popup.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'sha256-k6whJ99igQgqhch6A63JlRxd/4DZ7RT1fWyunKDcZ3U='".
```

**Comment by bietsch** [comment]
Hi, I've been using Surfingkeys for a while now and suddenly I'm having the same problem on Firefox Developer 72.0b2 on a Mac High Sierra. Found the message "reload triggered by runtime disconnection" in the console & google brought me here.

**Comment by bietsch** [comment]
Seems to be a Firefox beta issue, works fine in the release edition

**Comment by NgoKimPhu** [comment]
Confirm that it's a Firefox beta issue.
For reference, on Firefox Developer 72.0b7 (64-bit) (Windows 10), below is the error object caught by runtime disconnect listener after the common_content.js script calls `chrome.runtime.connect({ name: 'main' })`
```
{…}
    ​disconnect: function disconnect()
    ​error: Error
        ​​columnNumber: 1
        ​​fileName: "undefined"
        ​​lineNumber: 0
        ​​message: "Could not establish connection. Receiving end does not exist."
        ​​stack: ""
        ​​<prototype>: Object { … }
    ​name: "main"
    ​onDisconnect: Object { addListener: addListener(), removeListener: removeListener(), setUserInput: false, … }
    ​onMessage: Object { addListener: addListener(), removeListener: removeListener(), setUserInput: false, … }
    ​postMessage: function postMessage()
    ​<get error()>: Restricted {  }
    ​<prototype>: Object { … }
```
