### ISSUE TITLE
Korean and Japanese characters do not work properly in Omnibar

### ISSUE THREAD

**Issue by Anongh** [brookhong/Surfingkeys#237]
I can enter the first character in Omnibar, but I can not input the second character. So I can not create a word and force a google search instead of a bookmark or tab search.

Perhaps there is a problem with double-byte character handling.

**Comment by brookhong** [comment]
It works fine for Chinese.

I don't know Korea and Japanese, just have had a random test with Korea IME, it also works.

![237](https://cloud.githubusercontent.com/assets/288207/22647639/ac182f2a-ecad-11e6-8a4c-e70205d8d9ba.gif)

**Comment by Anongh** [comment]
Hmm, your typing in the picture was a list of meaningless characters :)
But now I can input Korean and Japanese correctly in Omnibar.

Thank you.
