### ISSUE TITLE
Mode Disabled pushed into mode stack again.

### ISSUE THREAD

**Issue by JWhiteford** [brookhong/Surfingkeys#240]
## Error details

Modes in stack: TopHook,Disabled,Normal

SurfingKeys: 0.7.3

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 0.7.6
