### ISSUE TITLE
[feature request✨] Emoji tab completion in the editor 

### ISSUE THREAD

**Issue by YasserKaddour** [brookhong/Surfingkeys#241]
Hi @brookhong, 
Thank you for all the work you put on this superb extension :+1: 

I would like to propose to add emoji completion after you hit `:` and `tab` in insert mode like [vim-emoji](https://github.com/junegunn/vim-emoji) does. 
![68747470733a2f2f7261772e6769746875622e636f6d2f6a756e6567756e6e2f692f6d61737465722f656d6f6a692d636f6d706c6574652e676966](https://cloud.githubusercontent.com/assets/7279640/22618498/1fb1b93c-eade-11e6-8233-86d96bb55a01.gif)
I found a [json](https://github.com/ahfarmer/emoji-search/blob/master/src/emojiList.json) from [emoji-search](https://github.com/ahfarmer/emoji-search) with a list of keywords that I think would be helpful for the completion. It would be nice :100:  to maybe remember the recently used emoji.

I think this would be a great addition for your extention since emoji are ubiquitous now on the web.

As a side note maybe add words from a dictionary for tab completion, and even a spellchecker as options for the editor.

What do you think? Thanks :v:

**Comment by YasserKaddour** [comment]
:tada:
Thanks this is awesome!!
I just tried 0.7.7, but I couldn't get it to work, I typed `:` with some keyword, but nothing happened. Am I missing something?
Anyway, when this will work, I would love to help documenting it with a gif, If that's okay? :v:

**Comment by enterit** [comment]
Is there any way to disable emoji? They are too big, and I do not want to see them in every input.
I use Surfingkeys mainly for a great navigation capabilities and Vim key bindings.
Please 🌷

**Comment by brookhong** [comment]
Now emoji only works in insert mode, it does not work in ACE vim editor.

Add below in your settings to disable it:

    iunmap(":");
