### ISSUE TITLE
when update chrome to 56, background page can't load script because of CSP

### ISSUE THREAD

**Issue by XGHeaven** [brookhong/Surfingkeys#243]
When I update chrome to 56, all page is reloading after restart. I have to disable surfingkey to stop reloading.
So I enter surfingkey background page console, find some errors.
![image](https://cloud.githubusercontent.com/assets/9291212/22680475/24c3a356-ed43-11e6-9aca-9ff4b60fd1a1.png)

I remember 'unsafe-eval' should allow any code. I don't know why...

`cVim` have same problem... perhaps it's because of `content-security-policy` field in manifest.json

**Comment by brookhong** [comment]
Version 46 is too old for Chrome. 56 has been released, please try to upgrade your chrome.

**Comment by XGHeaven** [comment]
@brookhong sorry, It's 56. I'm write wrong.

**Comment by brookhong** [comment]
I can not reproduce this with Chrome 56 / Surfingkeys 0.7.4.

**Comment by mu-yu** [comment]
![image](https://cloud.githubusercontent.com/assets/3822774/23116811/8f43078c-f787-11e6-8f11-cd9bdf31fbd4.png)

**Comment by XGHeaven** [comment]
I fix this by reinstall chrome... So you can try it. @mu-yu ...
maybe chrome bug.
