### ISSUE TITLE
设置界面卡死的Bug

### ISSUE THREAD

**Issue by ipcjs** [brookhong/Surfingkeys#244]
环境：Window10 + Chrome 56.0.2924.87 (64-bit) + Surfingkeys 0.7.3
概率：必现
描述：进入扩展的设置界面 > Default mappings > 依次按`/'s`，之后扩展所有的功能就都卡死了，Chrome进程CPU占用25+%。必须重启Chrome才恢复正常。

看样子像是跑到死循环里去了？

**Comment by brookhong** [comment]
![v2ex](https://cloud.githubusercontent.com/assets/288207/22791283/d1cbaf9e-ef23-11e6-9e27-676a26a913f4.png)

**Comment by ipcjs** [comment]
是Chrome的bug？
我这里说的扩展设置界面，是指这个扩展的设置界面，不是指chrome的扩展管理界面

**Comment by brookhong** [comment]
我跟你一样的环境，没有这个问题呢。

**Comment by ipcjs** [comment]
(-_-#)是不是你复现步骤错了？
我又试了下，进到这个扩展的设置里面，按`/`进入查找模式，输入到第二个字符的时候就会卡死。

**Comment by brookhong** [comment]
好的, 我重现了, 谢谢报告这个问题。
