### ISSUE TITLE
[question] When is extension updated with bug fixes?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#245]
When bugs are fixed, how long does it take for them to appear as an update to the Chrome extension?  Is there a way to use the "nightly" version of Surfingkeys?

**Comment by brookhong** [comment]
![image](https://cloud.githubusercontent.com/assets/288207/22787880/c45b32e0-ef18-11e6-874e-39f5ef87b80e.png)


There is no nightly build, you could download source of(or git clone) this project, enable developer mode of Chrome, then load unpacked extension to use the latest code.
