### ISSUE TITLE
Option to hide link hints that are not actually visible?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#247]
Normally when one div is blocking another a user has no way of interacting with the links that are covered - the blocking div needs to be dismissed.  Hints for links that are covered still display though, so if the blocking div also has a lot of links you end up with a bit of a mess.

![screen shot 2017-02-09 at 3 23 41 pm](https://cloud.githubusercontent.com/assets/802511/22807494/22cbec9e-eedc-11e6-877b-8a40caad22b1.png)

**Comment by brookhong** [comment]
Should have been fixed.
