### ISSUE TITLE
"双击某个单词获取中文翻译"在哪里打开?

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#25]
好像没看到相关的功能

**Comment by brookhong** [comment]
这个功能不是每个人都需要的，所以默认的设置里面没有，你需要自己把下面的代码添加到你到设置里面，`se`打开设置。

    $(document).dblclick(function(event) {
        var sel = window.getSelection().toString();
        if (sel && sel.length) {
            httpRequest({
                'url': 'https://api.shanbay.com/bdc/search/?word=' + sel
            }, function(res) {
                var res = eval("a=" + res.text);
                var b = window.getSelection().getRangeAt(0).getBoundingClientRect();
                var pos = [b.top - 18, b.left + b.width / 2 - 12];
                Normal.showBubble({
                    top: pos[0],
                    left: pos[1]
                }, res.data.definition || res.msg);
            });
        }
    }).click(function() {
        Normal.hideBubble();
    });

**Comment by yech1990** [comment]
我已经暂时把Surfingkeys给disabled掉了，习惯了vimium很多功能没适应过来
我觉得应该弄一个类似vimium的配置模板，不然迁移的成本太大

谢谢您，不过还有一个问题没解决，我又开了一个issue
