### ISSUE TITLE
Cannot remap `f`

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#251]
When I try remapping `f` to another key, I get `TypeError: Cannot set property 'word' of undefined`.  Repro is inconsistent.  Perhaps the issue is with certain keys and not others?  The remapping of `f` to `ff` was giving me problems.

**Comment by ddickstein** [comment]
I think this might have been the result of some bad combination of settings?  Not repro-ing for me.

**Comment by ddickstein** [comment]
If I try this work-around, the key I want to re-map it to still doesn't work.

```javascript
mapkey('ff', '#1Open a link, press SHIFT to flip hints if they are overlapped.', 'Hints.create("", Hints.dispatchMouseClick)');
unmap('f');
```

**Comment by ddickstein** [comment]
Okay, I dug into this and figured out the issue.  It seems that mappings that use a currently mapped sequence as a prefix will not work, even if that sequence is unmapped afterward.  So for example, `gff` could not be used as a mapping until `gf` were unmapped.  This is why mapping `f` to `ff` broke - the prefix `f` was already in use as a command.  It seems the workaround to this is to invert the two lines in my failed workaround:

```javascript
unmap('f');
mapkey('ff', '#1Open a link, press SHIFT to flip hints if they are overlapped.', 'Hints.create("", Hints.dispatchMouseClick)');
```

**Comment by brookhong** [comment]
You got that.

Yes, `ff` won't work if `f` has already been mapped, as action for `f` will be triggered as soon as `f` is pressed, it will not listen to the next key event.

To make `ff` work, you need change `f` to someone else, such as `fa`.

This is by design.

**Comment by gary02** [comment]
how about double-shift:
```
map('<Shift-Shift>', '>_t');
map('<Shift><Shift>', '>_t');

```
both are not working.  it does not seem to be the same case above.
