### ISSUE TITLE
[feature request] close tab without navigation

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#252]
Is there a way to write a command that will close a tab other than the current one without leaving the current page?  Or can this feature be added?  There might be limitations in Chrome permissions that would prevent this; I'm not sure.  Would be especially cool if I could close a group of tabs, e.g. "close tabs 4 to 7" or "close tab 4 and the 3 that follow."

**Comment by zeltak** [comment]
wow thats a great idea.  +1 on that 

Z

**Comment by ddickstein** [comment]
I saw this was added with "gx" that's amazing thank you so much.
