### ISSUE TITLE
[feature request] integrate with Mercury Reader extension

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#255]
This might be totally impossible, in which case feel free to close, but it would be awesome if I could use surfingkeys extensions on the reformatted pages generated by the [Mercury Reader](https://chrome.google.com/webstore/detail/mercury-reader/oknpjjbmpnndlpmnhmekjpocelpnlfdi) extension.  I don't want to have to choose :P

**Comment by idd79** [comment]
Mercury Reader is nice, but if you are willing to give another reader mode extension a try, you can use Surfingkeys with [Just Read](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod?hl=en).

**Comment by vcfvct** [comment]
> Mercury Reader is nice, but if you are willing to give another reader mode extension a try, you can use Surfingkeys with [Just Read](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod?hl=en).

Thanks for the suggestion! The `JustRead` works with Surfingkeys like a charm. Sold! 😃

**Comment by duranivan** [comment]
@vcfvct Happy to help. Actually, I am recently using [clearly](https://chrome.google.com/webstore/detail/clearly/odfonlkabodgbolnmmkdijkaeggofoop?hl=en) which I find a bit better than Just Read, and also works with Surfingkeys and Vimium!
