### ISSUE TITLE
[Feature] Display hints to enter visual mode

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#256]
I really like Chrome and Surfingkeys. However right now I am using Firefox due to Vimfx. One of the reasons is that I use visual mode quite frequently and I find the implementation of caret/visual mode much easier in vimfx than in surfingkeys.

By hitting 'v', Vimfx first displays hints just like when you hit 'f', which allows to you go right away to the sentence, box, or sometimes word that you want to highlight in visual mode, which I find it extremely faster and convenient over searching for a keyword first and then enter visual mode in surfingkeys.

It woud be great if you could implement this feature. Thanks in advance.

**Comment by brookhong** [comment]
Thanks for suggestion, will be released in next version.

**Comment by idd79** [comment]
Thanks a lot, I just noticed it has been implemented and is working great :)
