### ISSUE TITLE
after searching with '/' ESC dosent respond, cant get out of search (caret?) mode until page refresh 

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#258]
Hi

something i noticed recently is that after i search (using '/') i cant get out of search (caret?) mode until page refresh. is this a known issue? am i missing something?
using arch linux, latest chrome and surfinkeys.

will be happy to help debug and provide any info necessary

best

Z

**Comment by brookhong** [comment]
It should be fixed in 0.7.5, please verify that.

**Comment by tlegutko** [comment]
I'm sporadically having this issue in 0.7.5, it happened twice in hour of browsing, once when just moving through caret/visual mode on one page, the second time when I came back to tab left with caret mode. Couldn't find a direct way to reproduce it though.

**Comment by zeltak** [comment]
yeah this is also still present for me in 0.7.5

thx!

Z

**Comment by mingliangguo** [comment]
I still see the problem with the latest version `0.8.7`.
