### ISSUE TITLE
Cannot scroll through Google search results with j and k

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#259]
Holding down <kbd>j</kbd> or <kbd>k</kbd> does not scroll through the results page, and when I release usually the letter just appears in the search bar.  I tried refreshing and mashing escape before attempting to scroll, but no luck.  Some other keybindings, such as <kbd>o</kbd> for omnibar, seem to work.

**Comment by ddickstein** [comment]
Seems to be affected by whether or not the search bar is visible on the page (if I'm already scrolled down with my mouse, <kbd>j</kbd> and <kbd>k</kbd> seem to work until it comes back into view).

**Comment by Ps-Pencil** [comment]
Sometimes I have this issue. It seems "sometimes" after immediately loading the google results screen, scrolling doesn't work. But as soon as I move the page using the mouse's scroll bar, it starts to work.

**Comment by brookhong** [comment]
Are you still seeing the problem?

**Comment by Ps-Pencil** [comment]
Sorry. Yes you can close it. It doesn't happen to me now.
