### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by zhictory** [brookhong/Surfingkeys#260]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

SurfingKeys: 0.7.5

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

URL: http://tech.sina.com.cn/it/2017-02-10/doc-ifyameqr7410948.shtml

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 0.7.6
