### ISSUE TITLE
Broken settings page in 0.7.5

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#261]
Regression?  Page is unresponsive.

<img width="1440" alt="screen shot 2017-02-12 at 10 28 24 pm" src="https://cloud.githubusercontent.com/assets/802511/22873114/a441517c-f172-11e6-9b0b-39449efaa91d.png">

**Comment by ddickstein** [comment]
I think this is probably a bug and not a regression.  It's likely related to the [syncing issue](https://github.com/brookhong/Surfingkeys/issues/233).  If on one computer I source my settings from a local file, Surfingkeys is effectively disabled on my other one.  There should probably be some sort of detection here that if the file is locally sourced no sync should happen.  Manual toggle would probably also be fine.

**Comment by brookhong** [comment]
Thanks for reporting this issue.
