### ISSUE TITLE
Unable to scroll in any way on some pages.

### ISSUE THREAD

**Issue by tlegutko** [brookhong/Surfingkeys#262]
Example: [Aurelia Framework Docs](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start)
Okay, to be honest that page definitely has some hacks under the hood, it confuses the hell out of all vim-simulating extensions and I understand that some stuff will not be working. But I happen to use that a lot recently and Vimium scrolls it just fine, so I though't I'd let you know there (I tried all commands from `Scroll Page / Element`section in `Show usage` shortcut, none of them works).

**Comment by brookhong** [comment]
Please use `cs` to change scroll target, then it will work.

**Comment by tlegutko** [comment]
nice, didn't catch that, thanks! I wonder why it's the only site with wrong default, but I can definitely live with it, thanks again :+1:
