### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by phlips5437** [brookhong/Surfingkeys#263]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

SurfingKeys: 0.7.5

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

URL: http://tech.sina.com.cn/it/2017-02-14/doc-ifyamkpy9338482.shtml

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 0.7.6
