### ISSUE TITLE
Mode Disabled pushed into mode stack again.

### ISSUE THREAD

**Issue by adamdavislee** [brookhong/Surfingkeys#264]
## Error details

Modes in stack: TopHook,Disabled,Normal

SurfingKeys: 0.7.5

Chrome: Mozilla/5.0 (X11; CrOS armv7l 8872.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.105 Safari/537.36

URL: https://duckduckgo.com/?q=waiting+for+emacs+emacsclient&atb=v20a_&ia=web

## Context

**I disabled Surfingkeys temporarily and went to bed, in the morning I saw the error message.**

**Comment by brookhong** [comment]
Fixed in 0.7.6
