### ISSUE TITLE
希望能够给指定域名指定配置

### ISSUE THREAD

**Issue by utick** [brookhong/Surfingkeys#265]
例如这种
site '*://*.reddit.com/*' {
      map('A','B');
      map('C','D');
}

**Comment by asetsuna** [comment]
You can check the documentation for this feature.  In section:  'Map a keystroke to some action'.

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-add-domain-specific-settings
