### ISSUE TITLE
[Suggestion] HintsForKeystroke

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#267]
Hi,

Thanks a lot for the continuos development of this extension, I really love it, and for keep adding new features as per request. Just noticed the new feature `HintsForKeystroke` and I think it is a really good idea, the only suggestion I might add is to allow for some time delay before the hints table shows up, maybe half or one second, in a way that it shows up only when you really need help or hints to remember a keystroke.

Thanks again!

**Comment by ldong** [comment]
Hi @idd79 ,

I think this commit addressed that, https://github.com/brookhong/Surfingkeys/commit/50c12872dfb1d39e5b4ec14d87f52f757305bccb.

**Comment by idd79** [comment]
Hi @ldong... it looks like the commit you point at is either to enable or to disable `HintsForKeystroke` completely. What I meant was to allow for some time delay before the hints help box shows up, but this is really not a problem so I'm just closing this issue
