### ISSUE TITLE
Toggle showModeStatus?

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#269]
Is there (or can there be) a way to toggle showModeStatus?  It's often useful but less so if blocking underlying text / buttons or when watching a fullscreen video.

**Comment by brookhong** [comment]
Add below in your settings:

    settings.showModeStatus = false;
    settings.showProxyInStatusBar = false;

**Comment by clflowers5** [comment]
The readme should be updated as it currently lacks the ```settings.``` prefix.

**Comment by ddickstein** [comment]
It would be nice if there were a command or hotkey though to toggle it rather than always returning to the settings page when I want to watch Netflix.

**Comment by cbrwizard** [comment]
Phew, thanks for the settings, because that status was driving me nuts

**Comment by 0xR** [comment]
I don't like the status bar either. Would it be possible to have it off by default?

**Comment by brookhong** [comment]
Thanks guys for heads-up.

| key | default value | explanation |
|:---------------|:-----|:-----|
| settings.showModeStatus | false | Whether always to show mode status. |
| settings.showProxyInStatusBar | false | Whether to show proxy info in status bar. |
| settings.richHintsForKeystroke | true | Whether to show rich hints for keystroke. |


* To hide mode status, false by default from 0.7.7, you don't need any more.

    settings.showModeStatus = false;

* To hide proxy info in status, false by default from 0.7.7, you don't need any more.

    settings.showProxyInStatusBar = false;

* To hide rich hints for keystroke, true by default, you'll need this line if you don't like the feature.

    settings.richHintsForKeystroke = false;
