### ISSUE TITLE
i键激活编辑框，当只有一个的时候，能否直接进入？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#270]
目前按了i后还要按A才行，如果只有一个编辑框，是否可以跳过按A的步骤。

**Comment by vitmy0000** [comment]
或者可以设置一个对应的event，直接编辑第一个编辑框。
然后可以用户可以选择映射到，比如`a`

**Comment by hyaray** [comment]
新手，还不会JavaScript，如果可以完善，建议作者更新，不然因为此功能又单独设置一键感觉没那么好了

**Comment by brookhong** [comment]
Fixed in 0.7.7.
