### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by cuiweifu** [brookhong/Surfingkeys#272]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

SurfingKeys: 0.7.5

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36 QQBrowser/4.1.4132.400

URL: http://portal.gridsum.com/tech-engineer/_layouts/15/start.aspx#/SitePages/%E4%B8%BB%E9%A1%B5.aspx

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 0.7.7.
