### ISSUE TITLE
右下显示当前状态的bar

### ISSUE THREAD

**Issue by lirikirikiri** [brookhong/Surfingkeys#273]
能否增加隐藏那个bar的选项或措施，有时全屏看视屏的时候那个bar不会自动隐藏。还有那个bar上的‘clear’有什么用吗？怎么用？

**Comment by brookhong** [comment]
在你的设置里加入：

    settings.showModeStatus = false;
    settings.showProxyInStatusBar = false;


`clear`显示是当前Surfingkeys不接管代理设置, 可以参考https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE

**Comment by lirikirikiri** [comment]
谢谢。
