### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by kaelwu** [brookhong/Surfingkeys#274]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

SurfingKeys: 0.7.5

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

URL: http://tech.sina.com.cn/mobile/n/c/2017-02-27/doc-ifyavvsk3644206.shtml

## Context

when i open the website and nothing to do

**Comment by brookhong** [comment]
Fixed in 0.7.7.
