### ISSUE TITLE
Mode GetBackFocus pushed into mode stack again.

### ISSUE THREAD

**Issue by asetsuna** [brookhong/Surfingkeys#275]
## Error details

Modes in stack: TopHook,GetBackFocus,Normal

SurfingKeys: 0.7.6

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

URL: http://tech.sina.com.cn/mobile/n/n/2017-02-26/doc-ifyavvsh6855259.shtml

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Fixed in 0.7.7.
