### ISSUE TITLE
How to hide "xx | clear" text and popup help overlay?

### ISSUE THREAD

**Issue by fancyoung** [brookhong/Surfingkeys#276]
There is a box at the bottom in new version, it shows the operate state.
And when press a key, a popup box will be shown at right bottom, it shows hit of usage.

Is there anyway to hide them?

**Comment by Salvar** [comment]
I'd like to know this too. Took me a while to figure out where this annoying overlay was coming from, and had to uninstall Surfingkeys to get rid of it. Would like to have it back.

**Comment by brookhong** [comment]
| key | default value | explanation |
|:---------------|:-----|:-----|
| settings.showModeStatus | false | Whether always to show mode status. |
| settings.showProxyInStatusBar | false | Whether to show proxy info in status bar. |
| settings.richHintsForKeystroke | true | Whether to show rich hints for keystroke. |


* To hide mode status, false by default from 0.7.7, you don't need any more.

    settings.showModeStatus = false;

* To hide proxy info in status, false by default from 0.7.7, you don't need any more.

    settings.showProxyInStatusBar = false;

* To hide rich hints for keystroke, true by default, you'll need this line if you don't like the feature.

    settings.richHintsForKeystroke = false;
