### ISSUE TITLE
[feature request] Scroll with <Ctrl-N> and <Ctrl-P> on Omnibar

### ISSUE THREAD

**Issue by skitimoon** [brookhong/Surfingkeys#278]
Is there any way to select result in omnibar by using `<Ctrl-N>` and `<Ctrl-P>`. I don't know how to map it in custom setting (don't know if this is possible?). I'd prefer using <Ctrl-N> and <Ctrl-P> rather than `<TAB>` and `<Shift-TAB>`.

**Comment by brookhong** [comment]
Implemented in 0.7.8

**Comment by sail456852** [comment]
** Hi noob here, I am on 0.9.38 version.
I need this feature too. just like in Emacs I this feature everywhere
while browsing.
C-n (Ctrl+N) == Down Arrow key, C-p (Ctrl+P) == Up Arrow key.
I read the wiki, but I tried map('Ctrl+N', Down), but it won't work
Any tutorial exclusively on how to define a customized key combination for this awesome Surfingkeys?

**Comment by fanlushuai** [comment]
确实是个难受的问题
