### ISSUE TITLE
"Disabled" not actually disabled

### ISSUE THREAD

**Issue by Ps-Pencil** [brookhong/Surfingkeys#279]
Since it seems to be written in Javascript, it seems to mess with Google Doc's own scripts. Some functions do not work. That is fair enough.

I set `fd` to be the shortcut to escape from insert mode. When in google doc, it seems everytime I type `f` it got swallowen. So I need to type two `f` to enter one. I tried disabling it for this site but the behaviour persists.

**Comment by brookhong** [comment]
This should have been fixed.
