### ISSUE TITLE
prevent steal focus on page load 

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#28]
vim操作网页最烦的两事：
- 1. 打开网页后光标在输入框，每次操作变成了输入
- 2. pdf和newtab之类的tab，所有操作失效

第一个vimium基本解决了，可在surfingkeys是否有类似的解决方案？

第二个firefox没任何问题，可chrome目前我还没看到合适的插件能解决，这个在chrome是不是无解？

**Comment by brookhong** [comment]
第一个已在0.3.0里解决了。

**Comment by yech1990** [comment]
0.3.0怎么设置这个功能呢? 我在chrome store 下载的没看到

**Comment by brookhong** [comment]
不需要设置的，自动开启，如果你碰到有不好使的网站，请贴到这里。

**Comment by lingkz** [comment]
你好，我是小白一个，想请教一下，想在设置文件中加个淘宝和优酷搜索的自动补全，搜索会写，不知道怎么自动补全。谢谢。

**Comment by brookhong** [comment]
// 淘宝搜索
    addSearchAliasX('t', 'taobao', 'https://s.taobao.com/search?q=', 's', 'https://suggest.taobao.com/sug?code=utf-8&q=', function(response) {
        var res = eval("a=" + response.text);
        res = res.result.map(function(r) {
            return r[0];
        });
        Omnibar.listWords(res);
    });

    // 优酷搜索
    addSearchAliasX('y', 'youku', 'http://www.soku.com/search_video/q_', 's', 'http://tip.soku.com/search_tip_1?query=', function(response) {
        var res = eval("a=" + response.text);
        res = res.r.map(function(r) {
            return r.w;
        });
        Omnibar.listWords(res);
    });

**Comment by lingkz** [comment]
多谢多谢

**Comment by haoxuexiaoyao** [comment]
你好，请问下这个淘宝搜索如何向输入og一样，弹出一个Google搜索框，并且根据关键字提示搜索的内容

**Comment by haoxuexiaoyao** [comment]
@brookhong 你好，请问下这个淘宝搜索如何向输入og一样，弹出一个Google搜索框，并且根据关键字提示搜索的内容

**Comment by haoxuexiaoyao** [comment]
@brookhong 已经解决了 

`
// 淘宝搜索
addSearchAliasX('tb', '淘宝网', 'https://s.taobao.com/search?q=', 's', 'https://suggest.taobao.com/sug?code=utf-8&q=', function(response) {
    var res = eval("a=" + response.text);
    res = res.result.map(function(r) {
        return r[0];
    });
    Omnibar.listWords(res);
});
mapkey('Otb', '#13Open Search with alias tb', 'Normal.openOmnibar({type: "SearchEngine", extra: "tb"})');
mapkey('ot', '#8打开淘宝搜索栏', 'Front.openOmnibar({type: "SearchEngine", extra: "tb"})');
`
