### ISSUE TITLE
Scrolling with j, k... not working in PDFs

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#281]
Hi again,

I'm wondering if there is any way around this issue. Vimium does not work with PDFs at all, but I just noticed that some features of Surfingkeys do work in PDFs (in the default Chrome PDF viewer, that is), for example opening the Omnibar or switching tabs... (I tried it in this [website](https://devnull.li/~jerojasro/twgr2e/The_Well-Grounded_Ru.pdf))

It would be great if we could scroll in pdfs as well and even use `f` to open content in the pdf (Vimfx in Firefox allows for all this, but may be this something specific to the browser and not the extension itself).

Thanks in advance!

**Comment by EdwinvRooij** [comment]
Not an ideal solution, but the way I work _around_ this currently is by converting the PDF file as a whole.

I've found this website to be useful for this task: http://www.zamzar.com/

**Comment by brookhong** [comment]
Thanks to [pdf.js](https://github.com/mozilla/pdf.js), this is implemented in 0.8.4.

Please have a try.

**Comment by idd79** [comment]
It's working great. Thanks a lot!

**Comment by maximbaz** [comment]
Nice work @brookhong!
