### ISSUE TITLE
搜索地址出现两处关键词时怎么写？

### ISSUE THREAD

**Issue by haoever** [brookhong/Surfingkeys#283]
https://search.jd.com/Search?keyword=test&enc=utf-8&wq=test

以上是京东搜索，如果没有第一个“test”后面的一段，搜索中文关键词时就会变成乱码或空白。

**Comment by brookhong** [comment]
http://search.jd.com/Search?enc=utf-8&keyword=test

    addSearchAliasX('j', 'jd search', 'http://search.jd.com/Search?enc=utf-8&keyword=');

这样就可以。
