### ISSUE TITLE
<Ctrl-n> in Omnibar doesn't work as expected

### ISSUE THREAD

**Issue by lxhillwind** [brookhong/Surfingkeys#287]
`<Ctrl-n>`, `<Ctrl-t>` and `<Ctrl-w>` are occupied by Chrome on Windows and Linux, so they won't work for extensions by default.

It seems that there is some method to make them work. You can search `cncpcompletion` [here](https://github.com/1995eaton/chromium-vim) to get some information.

Edit:
version info: 0.7.8;
platform info: Chromium 56.0.2924.87 (64-bit) on Linux / Windows; Chrome OS 56.0.2924.110.

**Comment by cibinmathew** [comment]
It is a nice to have feature. Ctrl-n to move to next item is already favorite for emacs lovers.

**Comment by masaeedu** [comment]
Is there a way to manually disable the `Ctrl+N` shortcut in these browsers?

**Comment by cibinmathew** [comment]
Can we add a new command here to capture Ctrl-n and implement this
https://github.com/brookhong/Surfingkeys/blob/3102cdadcfff0366179554c245bd9123494f721d/manifest.json#L12-L28

**Comment by lixiao-tap4fun** [comment]
For anyone reach here, this issue can be solved by using custom Chromium build [Brook Build of Chromium](https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html); this link is also in Surfingkeys README.md, but may not be as visible.
