### ISSUE TITLE
Surfingkeys isn't working for local pages (http://192.168.1.1/)

### ISSUE THREAD

**Issue by fohrums** [brookhong/Surfingkeys#288]
Once surfingkeys is installed and it doesn't seem to work a refresh should resolve the problem. But, in the case of local pages this extension isn't working. A great example is

http://192.168.1.1/

Or in other words when *accessing the modem* page.

**Comment by borgnix** [comment]
Turning on the "Allow Access to file URLs" options in the extension page may fix this.

**Comment by maximbaz** [comment]
It's not about file URLs, but I just figured it out - in my case, the page had several frames, and looks like some of them are invisible. @fohrums try to press <kbd>wd</kbd> several times, the <kbd>w</kbd> will switch frames and on a third try I hit a correct frame, where <kbd>d</kbd> began to scroll.

**Comment by brookhong** [comment]
This should be fixed.

For the admin page of router or modem, `frameset` is usually used. So you could use `w` to switch frame first.
