### ISSUE TITLE
Cursor position in input box is not consistent with the displayed text

### ISSUE THREAD

**Issue by dexter0195** [brookhong/Surfingkeys#289]
Whenever I open the insert box with "I" and I start writing the cursor position gets ahead of the displayed text.

attached there is a screenshot of the issue
![2017-03-09-080857_1366x730_scrot](https://cloud.githubusercontent.com/assets/22595280/23739565/b75b955c-049f-11e7-82a7-29f19d5e78bc.png)

It's like the actual text is bigger than the displayed text
I am using latest Chromium on Linux with monospace as fixed-width font, the zoom is at 100%.
I read that this is a common issue in Chrome but none of the fixes I found online solved this problem.

**Comment by borgnix** [comment]
You are not using a monospace font. Set the monospace font in chrome settings to a proper monospace font then the page may display properly. 

I have encountered the same problem on Linux chrome. Sometimes the fonts setting in chrome just don't work well. You could try to reset font settings.

**Comment by dexter0195** [comment]
I am using monospace font but this does not solve the problem.
I even tried to add a custom css in the settings but nothing happens

**Comment by dexter0195** [comment]
You were right, I managed to solve the issue. I was missing the font Dejavu-Sans. Just installed `ttf-dejavu` (on Arch Linux) and selected it from chrome://settings/search#font
