### ISSUE TITLE
Unable to save settings after latest update

### ISSUE THREAD

**Issue by 15cm** [brookhong/Surfingkeys#29]
I fail to save my settings using version 0.3.0 with Chrome 47.0.2526.106 on Mac OS. All mappings remain as default despite of many times of clicking on saving.

**Comment by brookhong** [comment]
0.3.0 was refactored, some APIs are changed like `Normal.getContentFromClipboard`, there may be some errors in your own settings.

I tried to avoid such cases to split default settings from user-defined settings, but some APIs are affected in code refactor. Sorry about that.

Please check default settings to see if you used any changed APIs, or post your settings here, let's see what stops your settings from saving.

**Comment by 15cm** [comment]
`settings.tabsThreshold=25;`
This is the cause. What is it in the changed APIs?

**Comment by brookhong** [comment]
Yes, it is.

Please use `runtime.settings` instead of `settings`.

**Comment by 15cm** [comment]
I got it. Thanks.
Suggestion: Maybe error messages could be added in the future.
