### ISSUE TITLE
Key mapping for `Alt-s` does not works on Mac

### ISSUE THREAD

**Issue by alswl** [brookhong/Surfingkeys#290]
First, thanks for creating such amazing Chrome extension.

I encounter a error, I want map 'Alt-s' to `Ctrl-i`.

configuration is:

```
map('<Ctrl-i>', '<Alt-s>');
```

But it does not works, `Alt-s` can works.

I have tried `map('<Ctrl-i>', '<Meta-s>');`, but this is not works too.

My Chrome version: Version 56.0.2924.87 (64-bit),
Surgfingkeys version: 0.7.8

**Comment by alswl** [comment]
My configuration is here: https://github.com/alswl/.oOo./blob/master/.surfingkeys.js#L10

**Comment by alswl** [comment]
Awesome, I build a package from master, it works!! 😄

Give a donate link please.

**Comment by brookhong** [comment]
Great, [Donation link](https://www.paypal.me/brookhong)

**Comment by alswl** [comment]
@brookhong paypal.me need receiver's phone number or email. Maybe you need create a Paypal donate button.

**Comment by brookhong** [comment]
Thanks, updated. Please try the new link.
