### ISSUE TITLE
Ctrl-f not work in text input field

### ISSUE THREAD

**Issue by alswl** [brookhong/Surfingkeys#291]
How to reduce:

*   focus in a text input
*   type some letters
*   type `Ctrl-f`

What I expected:

The cursor move forward one letter.

What actually happened:

The cursor moved to first position of current line.

Version:

*   Chrome: 56.0.2924.87 (Official Build) (64-bit)
*   Surfingkeys: 0.7.8

**Comment by lxhillwind** [comment]
This is the default behavior of `<Ctrl-f>`, from [here](https://github.com/brookhong/Surfingkeys#insert-mode).

**Comment by alswl** [comment]
Thanks @lxhillwind 

```
iunmap('<Ctrl-f>');
```

solved my problem.
