### ISSUE TITLE
Discussion: using "emoji-cheat-sheet" as an alternative emoji set

### ISSUE THREAD

**Issue by maximbaz** [brookhong/Surfingkeys#296]
@brookhong would you consider using [this](https://www.webpagefx.com/tools/emoji-cheat-sheet/) emoji set as a replacement for the current one?

Benefits of switching:

- They are much more popular, they are used in apps like Github and Slack, and people are already used to them.
- They are generally shorter to type.
- It is easier to find the right emojis, the search produces less duplicates (just see how many of current emojis start with "smiling face").

To be clear, I'm only suggesting to update the text description of emojis, I really like that you map text to a unicode symbol, without using any extra images. We should keep that.

I could help in investigations on how to do this transition easier, but I also want to know if you would agree to do the switch.

**Comment by maximbaz** [comment]
Since it was not too difficult to generate this file, I sent a PR - that way you can play with.

**Comment by brookhong** [comment]
Thank you so much for making this better. I like it.
