### ISSUE TITLE
[Features] Go to last visited tab and Shift-v

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#298]
Could it be possible to add a shortcut, say `gl` to go to the last visited tab? I find myself normally going back and forth between two tabs, and to do this with Surfingkeys I have to use the combo `B`, `F`. It would be ideal, at least for me, to just press the same command to go back and forth between two tabs.

Also, Vimium allows in caret mode to highlight the whole sentence and enter visual mode (independent of where the cursor is) with `Shift-v`. We have the same behavior in Vim, and right now in Surfingkeys I have to use the `0-v-$` combo to accomplish the same. It would be great if you could add this one as well :)...

Thanks in advance!

**Comment by brookhong** [comment]
`gT`Go to first activated tab
`gt`Go to last activated tab


In visual mode, 
`V`Select a word(w) or line(l) or sentence(s) or paragraph(p)
`y`Yank a word(w) or line(l) or sentence(s) or paragraph(p)

**Comment by idd79** [comment]
Thanks for the new additions based on the request. However `gt` looks like it is not working well for me, not sure why. I'll keep trying it out.
