### ISSUE TITLE
surfingkeys not working on a loading google search page

### ISSUE THREAD

**Issue by kongse** [brookhong/Surfingkeys#299]
When using t <keywords> to create a new google search page, before the page is fully loaded, the surfingkeys is totally not working on that opened new page.

e.g. if want to use E to back to the left tab , it can not be done .

**Comment by Kongse** [comment]
BTW, I'm using Linux / Chromium 57.0.2987.110 (64-bit).

**Comment by RiseAgainst9192** [comment]
Same. Surfingkeys is greyed out and disabled on www.google.com
Chromium: 62.0.3202.89 (latest stable)
Ubuntu: 17.04
Surfingkeys: 0.9.14 (latest I believe).
