### ISSUE TITLE
customize letter set for "Hints.pointers"

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#30]
Everyone has his own preference on typing, and the time to press different keys varies.
In order to achieve max speed, the hints pointer letter should be editable for the users.

in vimium, I set "jkladfpoet..." as default.

**Comment by brookhong** [comment]
Add below settings(will be in next release)

    Hints.characters="jkladfpoet";

Hints.pointers is not for your case, it's actually a css selector.

**Comment by yech1990** [comment]
Can you show me a example of Hints.pointers css setting? 
For example, I want to change the color and font of the selector.


BTW, is there a detailed user manual for customized setting? 
Sorry for keeping asking such stupid questions.

**Comment by brookhong** [comment]
css selector is not to set color/font, it's to pick up the elements to follow with Hints.

So far, there is no support to customize css style like color/font.
And unfortunately, the only help doc for settings is [here](https://github.com/brookhong/Surfingkeys/blob/master/README.md#edit-your-own-settings), and you can find all the settings examples in default settings(chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/default.js).
