### ISSUE TITLE
用t打开新标签页，输入中文的时候前几个拼音会变成英文字母形式

### ISSUE THREAD

**Issue by jokeryg** [brookhong/Surfingkeys#301]
比如 按t，拼音输入“张”会变成“zhan张”这样，不知道是不是新版chrome的原因

Surfingkeys 0.7.9

Google Chrome:Windows/版本 57.0.2987.110 (64-bit)

**Comment by av2000ii** [comment]
确实不是新版chrome的问题，我用360浏览器也有同样的问题。这个还是SurfingKeys对ime支持的问题吧。
