### ISSUE TITLE
Controls | SHIFT-T | View current buffers

### ISSUE THREAD

**Issue by fohrums** [brookhong/Surfingkeys#303]
Regardless of the view buffers threshold, it's much more easier to work w/ using the search bar rather than the floating tab-bubbles.

If the tabs aren't clustered it's easier to navigate the opened tabs traditionally as opposed to the tab-bubbles.

**How to set SHIFT-T to always use the view buffers via search bar w/ listed results?**

**Comment by brookhong** [comment]
add blow in your settings:

    settings.tabsThreshold = 0;
