### ISSUE TITLE
Sort Omnibar results

### ISSUE THREAD

**Issue by smic1909** [brookhong/Surfingkeys#304]
[Improvement]

When pressing `t` to open the omnibar and start typing something, the result should be ordered.

Example:

The history contains the following URL´s.

https://www.google.com/1/2/3
https://www.google.com/1
https://www.google.com/1/2
https://www.google.com/

When pressing `t`, I would assume that the ordering is 

https://www.google.com/
https://www.google.com/1
https://www.google.com/1/2
https://www.google.com/1/2/3

Today the result is arbitrary sorted.

**Comment by ljohnston** [comment]
This would be awesome!
