### ISSUE TITLE
Surfkingkeys steals focus

### ISSUE THREAD

**Issue by bennyn** [brookhong/Surfingkeys#306]
I like the Surfingkeys emoji feature but I just realized when I open a new tab in Chrome (Ctrl+T) and then visit https://translate.google.de/, I cannot immediately type a text (starting with an "S") in the translator's input box. Surfingkeys seems to steal the autofocus from that textarea. Is there a way to prevent this?

**Comment by brookhong** [comment]
Add below in your settings:

    settings.stealFocusOnLoad = false;
