### ISSUE TITLE
Help key breaks SK on https://web.whatsapp.com/

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#307]
## How to reproduce

- Ensure that you have WhatsApp Web set up
- Visit https://web.whatsapp.com/
- (Optional: Try some SurfingKeys commands other than `?` for help, and notice that everything works)
- Press `?` and observe that SurfingKeys help is shown
- Press `Escape` to clear the help
- Press `?` and observe that nothing happens
- Observe that most key bindings are now ineffectual, except for some prefix keys like `g` and `s`

## Workaround

Reload the page.  Everything should work until `?` is next pressed.

**Comment by brookhong** [comment]
Try it with 0.8.1

**Comment by aspiers** [comment]
Works now, thanks!
