### ISSUE TITLE
SurfingKeys conflicts with Google Doc

### ISSUE THREAD

**Issue by xcv58** [brookhong/Surfingkeys#309]
The focus lost immediately after selection in Google Doc.

I did try this from #306
```
settings.stealFocusOnLoad = false;
```
and it doesn't work.

![image](https://cloud.githubusercontent.com/assets/503123/24885030/24222208-1e01-11e7-8e89-e881eccabdb0.png)

**Comment by brookhong** [comment]
Thanks for reporting this, fixed in 0.8.2

**Comment by xcv58** [comment]
Thank you so much!
