### ISSUE TITLE
Escape key passed through to WhatsApp Web in insert mode

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#310]
(Following on from #307)

## How to reproduce

- Ensure that you have WhatsApp Web set up
- Visit https://web.whatsapp.com/
- Press `i` and observe that SurfingKeys correctly goes to the search box
- Type a search query
- Press `Escape` to exit edit mode (e.g. in order to scroll the search results, or select one result)
- Observe that `Escape` was passed to WhatsApp, and it cancelled the search

## Workaround

Click outside the search box with the mouse, which of course defeats the point of SK.

**Comment by febs** [comment]
This happens on plenty of other sites as well.

**Comment by Shamaoke** [comment]
I use the _Tab_ key as a workaround. That way focus moves to the next focusable element, e. g. the search button, and defocusing occurs without input cancellation.
