### ISSUE TITLE
i键应该判断的是输入框，但是会把非输入框也列进来，能否改善？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#311]
比如http://www.sobaidupan.com会把搜索按钮列入，
QQ邮箱首页，会把【星标邮件】和【漂流瓶】也列入。

**Comment by brookhong** [comment]
i键对应就是各类输入, 输入框是输入, select也是输入。你如果希望只是输入框, 可以在你的设置里加入下面的代码,

    mapkey('i', '#1Go to edit box', 'Hints.create("input[type=text]:visible, textarea:visible", Hints.dispatchMouseClick)');
