### ISSUE TITLE
一个关于自动识别文本网址的新功能探讨

### ISSUE THREAD

**Issue by leacoleaco** [brookhong/Surfingkeys#313]
插件非常赞，现在上手后已经离不开了。
作者大神可否考虑开发一个功能：
有些页面里的网址是文本方式显示的，不是超链接显示的。我每次想打开的时候，都需要先按 V，进入选择模式，然后再按一堆motion键选中网址，再按cc...
是否可以增加一个功能，按某个快捷键，自动按照正则表达式查出当前页面的网址文字，并标记字母，我直接输入对应字母就可以自动选中，或者是干脆直接打开对应的网页？（类似目前按q点击图片的情况）这样能省事不少，而且这种情况还是经常遇到的。
类似这样的情况还有：
1、网址
2、迅雷下载链接
3、种子下载链接
4、邮箱地址
5、手机号码

感谢

**Comment by brookhong** [comment]
谢谢建议。

按小写v定位可以稍微精确些。
另外这种场景并不具有普遍性, 而且实现起来可能影响性能, 先留着问题, 如果有更多需求的话, 会考虑。

**Comment by leacoleaco** [comment]
@brookhong 感谢回复。
或许这个场景您用的不多。我这边经常浏览博客论坛，论坛系统限制比较多，很多论坛超链接都不会显示，所以大多数情况作者都会直接给出文本形式的超链接，而不会刻意去加上 <a></a> 标签（很多系统也不允许加）。这样的情况我每天浏览网页都会遇到。
所以从普遍性来看，我不清楚大多数人是否也存在这个问题，反正我这边这个情况是非常普遍，所以我是非常非常需要这个功能的 ；-）

 比如我现在要用surfingkeys打开这个超链接网页 `http://www.baidu.com` 《= 就比较的麻烦，这里按 f 没法命中超链接。。。

后面我想了一个办法能临时给出我想要的功能。就是在配置中加上如下代码：

`mapkey("gv", '#15查找页面上文本形式的超接', function() {`
`      Visual.visualEnter(/[a-zA-z]+:\/\/[^\s]*/gi);`
`});`
`Visual.mappings.add("gy", {`
       ` annotation: "复制标记文本",`
       ` feature_group: 9,`
        `code: function() {`
          `  Visual.toggle();`
          `  var h=$(".surfingkeys_cursor").next().text();`
           ` Front.writeClipboard(h);`
`        }`
` });`
`Visual.mappings.add("go", {`
`        annotation: "新窗口打开标记文本",`
`        feature_group: 9,`
`        code: function() {`
`            Visual.toggle();`
`            var h=$(".surfingkeys_cursor").next().text();`
`            tabOpenLink(h);`
`        }`
`   });`

虽然有些简陋，但是至少能凑合用了 ๑乛◡乛๑   ，
方法就是先按  gv  ，然后一直按 n 找到自己超链接后，  按 gy 复制到剪贴板，或 按 go 直接跳转网页。
增加配置后可以再来这个回复页面试试是不是访问我上面写的超链接会比之前方式效果好很多๑乛◡乛๑
同理如果要复制其他内容也可以修改为对应正则表达式。

后面也遇到和我一样的朋友们可以尝试下这个方案，暂时不知道会不会有BUG 
也希望作者大神看到更多需求后能及时加上这个功能，让体验更优，让这个插件更加好用。

再次感谢，晚安

**Comment by brookhong** [comment]
0.8.4里增加了`O`打开文字中的超级链接, 默认只匹配http/https对应的链接

    settings.clickablePat = /https?:\/\/\S+/ig;

你可以修改这个正则表达式匹配相应的URL，比如

    settings.clickablePat = /(https?|thunder|magnet):\/\/\S+/ig;

**Comment by leacoleaco** [comment]
今日使用的时候看到了更新，已经用上了，十分感谢 ✧*｡٩(^㉨^*)و✧*｡

**Comment by sgrjyb** [comment]
@leacoleaco @brookhong  O 改成 u 键保存提示错误 ,而且输入 O 无效 ! 0  滚动到最左边 也无效 !

mapkey('O', '#1Open detected links from text', function() {
    Hints.create(runtime.conf.clickablePat, function(element) {
        $(`<a href=${element[2]}>`)[0].click()
    }, {statusLine: "Open detected links from text"});
});

**Comment by sgrjyb** [comment]
@leacoleaco @brookhong 添加 settings.clickablePat = /(https?|thunder|magnet):\/\/\S+/ig; 之后还是无法识别 magnet

[福利吧评论magnet](http://fuliba.net/%e5%b2%9b%e5%9b%bd%e5%ad%97%e5%b9%95.html)

**Comment by leacoleaco** [comment]
@sgrjyb 你正则表达式写错了。在“：”后少写了一个转义符 “\” 应该是：
`settings.clickablePat = /(https?|thunder|magnet):\/\/\S+/ig;`

另外，你附的那个链接果然是老司机专用啊哈哈，我点进去后差点翻车

**Comment by sgrjyb** [comment]
@leacoleaco  能不能分享你的Surfingkeys 配置 ?

**Comment by leacoleaco** [comment]
@sgrjyb 可以呀，但是我的是个人习惯设置，可能你不一定适用。
https://gist.githubusercontent.com/leacoleaco/e7e4a61228e58e9f8e1bce6f0dba031c/raw/ea13e8bd4b88465a3cdfac5d277e9e735d3f4486/surfingkeys-custom-setting.js

**Comment by sgrjyb** [comment]
@leacoleaco  帮忙看一下 为什么不能保存 ?

var url = window.location.href.match(/^(https?://)?(.+?)(/)?$/)[2];

**Comment by leacoleaco** [comment]
@sgrjyb 还是那个问题啊， 你的  “/”  没有转义。 应该是：
`var url = window.location.href.match(/^(https?:\/\/)?(.+?)(\/)?$/)[2];`

**Comment by sgrjyb** [comment]
@ 都是复制别人的 , 问一下 mapkey('gi', '#1定位第一个输入框', function()  是争取 gi 还是 为什么我这不起作用 ?

**Comment by leacoleaco** [comment]
@sgrjyb 你可以不用管这个。我后面都计划吧这个配置删掉了，其实surfingkeys 直接点击  `i` 后就可以找到所有输入框，如果网页只有一个输入框，那么会自动focus 进去。
添加定位第一个输入框这个功能我本是参考  chromium 插件的。但现在想想有点多余了。

**Comment by sgrjyb** [comment]
@leacoleaco 默认配置已经增加 定位第一个输入框了 ! 我觉得定位第一个输入框 挺好用的 i 还要选择!

怎么添加v2ex 翻页支持 https://www.v2ex.com/recent?p=2

要是能让所有网页都自动翻页就好了 !

**Comment by leacoleaco** [comment]
@sgrjyb 你说的那种没有上一页下一页的这种网页，作者应该没打算处理这个使用场景吧。  我想只能通过自己在配置中写一个 功能，点击某个键后， 先取出网页中的标示页码的那个数字，然后 +1 或者 -1 后，重新访问新的网址来实现。 比如你给我看的这两个网址，他们不同的页码就是：
http://btkitty.pet/search/e7F_78t9MwE/**5**/1/0.html
http://btkitty.pet/search/e7F_78t9MwE/**6**/1/0.html
http://btkitty.pet/search/e7F_78t9MwE/**7**/1/0.html
我想只要有办法能自动识别到里面的“5，6，7”，并能修改，应该就能实现你说的翻页了吧。
你要是写出了这个功能也期待共享配置给我下呢^_^

**Comment by sgrjyb** [comment]
@leacoleaco 指望他了 @brookhong

**Comment by leacoleaco** [comment]
@brookhong 我估计作者不会开发这个功能的，因为不同网址的 页码参数 都是不同，不太好实现所有网站通用。

其实如果只是针对某个网址实现自动某个字符+1也还好办，以你刚刚那个网址为例：

`
mapkey('ae', 'btkitty网址自动调整链接到下一页', function() {
   var url=location.href;
   var page=parseInt(url.replace(/http:\/\/btkitty.pet\/search\/([\s\S]*)\/1\/(\d+)\/0.html/,"$2"));
   var newUrl=url.replace(/http:\/\/btkitty.pet\/search\/([\s\S]*)\/1\/(\d+)\/0.html/,"http://btkitty.pet/search/$1/1/"+(page+1)+"/0.html");
   location.href=newUrl;
});

`
不过我觉得为了偷懒的话没这个必要，直接点  f 然后在点击对应的页码不是也可以么，浪费不了多少时间的

**Comment by sgrjyb** [comment]
@leacoleaco   不支持打开 magnet ?

Visual.mappings.add("cc", {
    annotation: "新窗口打开光标后的高亮文本",
    feature_group: 9,
    code: function() {
        var h = getMarkUnderCursor().text();
        tabOpenLink(h);
        //Visual.toggle();
        Visual.hideCursor();
        Visual.exit();
        Visual.visualClear();
    }
});

直接添加settings.clickablePat = /(https?|thunder|magnet):\/\/\S+/ig;  还是不能识别  magnet

**Comment by sgrjyb** [comment]
@leacoleaco 
Visual.mappings.add("cc", {
annotation: "新窗口打开光标后的高亮文本",
feature_group: 9,
code: function() {
var h = getMarkUnderCursor().text();
tabOpenLink(h);
//Visual.toggle();
Visual.hideCursor();
Visual.exit();
Visual.visualClear();
}
});

怎么设置打开磁力链接 ,不自动加 http ?
