### ISSUE TITLE
为什么插件在Chrome自带的界面都无效呢？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#314]
比如【新标签页】和【扩展程序】等界面，就不能使用。

**Comment by programscape** [comment]
Google出于安全考虑而做的的限制，插件作者无解。

**Comment by leacoleaco** [comment]
楼上正解，这些页面只能用原生映射来解决问题，比如用   ctrl+tab  来做切换Tab页面， ctrl+w 关闭窗口 等等。。。有点尴尬

**Comment by hyaray** [comment]
这个设定，易用性大打折扣啊，是个遗憾！
再请教下，我通过命令行打开网址，想实现功能：
1、如果该网址已存在，则激活该页面，不要重复打开两个相同页面。
2、该网页优先在Chrome已经存在的空白【新标签页】打开，目前每次都是新建个标签页打开，原来的【新标签页】都得手动切换回来关闭，太麻烦了！！

**Comment by BarryLiu1995** [comment]
Google 对于安全问题好像特别重视

**Comment by brookhong** [comment]
我给Chromium打了个patch，专门放开了对Surfingkeys的限制，build了一个，可以在这些受限页面使用Surfingkeys，有人需要吗？

![image](https://user-images.githubusercontent.com/288207/31435705-282aaf70-ae46-11e7-8487-1792bdd5fd2c.png)

**Comment by hyaray** [comment]
Chromnim插件的存在就是为了操作Surfingkeys页面吗，我感觉那个作者要崩溃了，哈哈！！！

**Comment by BarryLiu1995** [comment]
@brookhong 我需要

**Comment by hyaray** [comment]
@brookhong 支持配置界面，点击SAVE键吗？这个有需求

**Comment by hyaray** [comment]
@brookhong 支持Surfingkeys的options.html界面，点击save按钮吗？这个有需求

**Comment by brookhong** [comment]
Surfingkeys的options.html界面现在就支持啊！用官方Chrome就可以

**Comment by hyaray** [comment]
这下可以用脚本，F5加载设置后自动点击save键了，不错不错！！

**Comment by brookhong** [comment]
有兴趣的可以看看这个

https://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages.html

**Comment by hyaray** [comment]
@brookhong 太厉害了，就冲这点，我果断卸载了Chrome，就是可惜了不是便携的~~~遗憾！

**Comment by yech1990** [comment]
@brookhong linux下有改好的么

**Comment by hominlinx** [comment]
@brookhong pdf查看也有问题

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/35612561-2647dd02-06a4-11e8-93f7-fb3cc53eea7d.png)
@hyaray 哪个网站的视频看不了，我试了iqiyi和youtube都没问题。

**Comment by brookhong** [comment]
@hominlinx pdf查看需要使用Surfingkeys内嵌的pdf阅读器才行，`;s`切换。

**Comment by hyaray** [comment]
@brookhong 淘宝啊，你试试这个链接https://detail.tmall.com/item.htm?id=38892350352
