### ISSUE TITLE
反馈使用感受：实际需要点的位置每次都是2个字母的

### ISSUE THREAD

**Issue by shifujun** [brookhong/Surfingkeys#316]
Surfingkeys非常好用。用了10来天了，主要有两个小问题。

一是页面加载中或偶尔有兼容性问题，导致Surfingkeys不能使用，还是要用鼠标点一下才行。这个问题显然是技术层面的。

但第二个问题，应该就不是技术层面的问题了。其实工作中需要浏览网页的情况，只是偶尔切换到浏览器搜索个什么东西，并不需要Surfingkeys这样的全键盘操作的工具。我大量长时间使用浏览器都是看一些资讯类的网站，或者逛逛论坛什么的。最多的网站就是cnbeta、知乎、淘宝、威锋，这种网站。

这种网站都有个共同的特点就是链接超级多。在浏览这种网站是，用F或者Q键的时候，分配出来的单个字母，像asdf，都被页面顶部的导航栏或者广告占用了。我大部分实际上要点的都是页面中间部分的链接。所以几乎都是V开头的两个字母的。

所以有两个简单的改进想法，一是，简单的给几种选择字母的分配策略，比如从顶部开始、从中间开始、从左到右或者从右到左。二是，考虑有没有可能“智能”一点，记录我每次实际选择的链接在屏幕中的位置，形成一个优先级，按这个优先级分配字母。以便让ASDF能更容易分配到我经常点的链接上。

再次感谢开发此插件。

**Comment by brookhong** [comment]
第一个问题, 你可以按按`w`试试, 有时候页面里会有frame拿走了focus。

**Comment by shifujun** [comment]
到今天都一直在用，非常好用，再次感谢！
