### ISSUE TITLE
希望能把常用功能的函数说明下，让新手也可以写功能。

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#317]
比如写剪切板，对JavaScript新手来说，写这个功能可能比较困难，
后来想起Surfingkeys已经自带很多复制的功能，所以参考代码发现了Front.writeClipboard()。
类似这种日常应用，希望能说明下方便新手使用

**Comment by brookhong** [comment]
是的。实在精力有限, 欢迎帮忙写文档。

目前, 可以点开设置里的`Default mappings`, 参考里面的用法。
