### ISSUE TITLE
[Suggestion] Leave visual model after yanking text and about gt

### ISSUE THREAD

**Issue by duranivan** [brookhong/Surfingkeys#318]
Normally I find myself having to press `v` or `esc` after yanking some text in order to leave visual mode. Wouldn't it be better to go into normal mode right after yanking text (`y`) by default?

Also, I'm not sure how `gt` and `gT` are useful right now. I'm really missing just one keybinding that toggles back and forth from the last two activated tabs, instead of using `B` and `F`, just like `^` (visit the previously-visited tab) in Vimium.

Thanks,

**Comment by brookhong** [comment]
From 0.8.5, you could use below setting to achieve that.

    settings.modeAfterYank = "Normal";

**Comment by jaredbidlow** [comment]
i would like to send an upvote to @idd79 for the suggestion for most recent active tab switcher

**Comment by brookhong** [comment]
Use `Ctrl-6` since 0.9.13.

**Comment by duranivan** [comment]
The go to last active tab is working great. Thanks!
