### ISSUE TITLE
ctrl-i not opening vim editor

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#319]
As in version 0.84, `Ctrl-i` is not opening the vim editor while in `insert-mode`. It is opening the vim editor if entered in `insert-mode` with `I` though.

**Comment by leacoleaco** [comment]
Maybe  keys `Ctrl-i` are unbinded with your settings?

**Comment by idd79** [comment]
Thanks for pointing it put @leacoleaco, you were right. I hadn't noticed that I had some application with the same global key binding. My bad!
