### ISSUE TITLE
Can't disable surfing keys for certain websites

### ISSUE THREAD

**Issue by 0xR** [brookhong/Surfingkeys#32]
sometimes surfingkeys causes me not to be able to fill in an input field. I want to disable surfingkeys for that url, but I can't find the option.

Another reason to disable is that it might conflict with websites like github / gmail which already have conflicting hotkeys.

**Comment by brookhong** [comment]
Fixed in 0.3.2, add `alt-s` as [hot key to toggle Surfingkeys](https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys).
