### ISSUE TITLE
Please add setting to disable the default action of replacement of pdf viewer

### ISSUE THREAD

**Issue by asetsuna** [brookhong/Surfingkeys#320]
For a user who is used to default pdf viewer, it is annoying to type `;s`  to trigger default pdf viewer.

**Comment by brookhong** [comment]
From 0.8.5, the setting is persisted into storage, so that you don't need to toggle it each time when you open a pdf file.

**Comment by rosshadden** [comment]
The toggle doesn't work for me, so I ended up adding `chrome.storage.local.set({ "noPdfViewer": 1 });` to my settings file, forcing it to run every time.

A setting would be much appreciated.
