### ISSUE TITLE
https://chrome.google.com/webstore/search/?hl=en&_category=extensions   怎么修改为搜索引擎

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#322]
https://chrome.google.com/webstore/search/%s?hl=en&_category=extensions 怎么改成 =？

sg 搜索Google 我想在当前标签打开怎么设置？ 还有我在 Default mappings 找不到相关代码？ 谢谢

**Comment by brookhong** [comment]
mapkey('H', '#8Open opened URL in current tab', 'Front.openOmnibar({type: "URLs", extra: "getTabURLs", tabbed: false})');

**Comment by sgrjyb** [comment]
https://chrome.google.com/webstore/search/%s?hl=en&_category=extensions  怎么改成  =？

sg 搜索Google 我想在当前标签打开怎么设置？ 为什么我在 Default mappings 找不到相关代码？ 谢谢

**Comment by brookhong** [comment]
0.8.5以后, 你可以使用

    https://chrome.google.com/webstore/search/{0}?hl=en&_category=extensions
