### ISSUE TITLE
visual mode hints styling

### ISSUE THREAD

**Issue by CarloDePieri** [brookhong/Surfingkeys#323]
Hints.style( .. ) allows to style the hints appearance of `#sk_hints > div`.
There seems to be something overwriting the background of `#sk_hints[mode="text"] > div` which prevents to customize the hints background for entering visual mode (the text color or the border get changed though, only the background seems to be affected).

**Comment by yech1990** [comment]
+1 
I met the same issue.

**Comment by yech1990** [comment]
How to change the Color of hints in visual mode?
I use this conf, and it is almost unable to see any word in hints.

https://gist.github.com/coramuirgen/94ba1d587cb2093c71f6ef4f0b371069


![image](https://user-images.githubusercontent.com/5415510/29911177-84ca8ef0-8e5f-11e7-93d4-6337d648f3ac.png)

**Comment by yech1990** [comment]
目前只发现可以自定义`f`键触发的颜色， 而不能自定义`v`键触发的颜色么？

**Comment by yech1990** [comment]
@brookhong 9.10的最新版本依然不行，能否给个设置文件？

**Comment by brookhong** [comment]
试试下面这个：

    Hints.style("border: solid 8px #C38A22;padding: 1px;background: #e39913", "text");

**Comment by yech1990** [comment]
It works!!

非常感谢。

![image](https://user-images.githubusercontent.com/5415510/30794094-d8348170-a1f8-11e7-9378-c31da91166bb.png)
![image](https://user-images.githubusercontent.com/5415510/30794104-e0e0c932-a1f8-11e7-85eb-1443f6f5e54b.png)

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#hintsstyle
