### ISSUE TITLE
Some tabs refuse to close

### ISSUE THREAD

**Issue by intre4si32** [brookhong/Surfingkeys#324]
I do not understand what prevents them. Found myself on this page
[https://www.ghacks.net/2017/03/15/intro-to-customizing-vivaldis-interface-with-css/](url)
and doesn't close anymore. I keep hitting xxxxxx ( mapped like in vimium) but no, it stays there.
Ctrl+w also not working.
Tried one youtube page, doesn't close either.
 Tried gxt also. Nope.
Anyway how to debug this?

**Comment by intre4si32** [comment]
After investigating further found that one can  kill it (this time some google page) only after opening some other pages on spot with "go". Like in making it oblivious of the offending page. this other page allows closing. Annoying like hell and it drove me to dump google altogether and choose another search engine for now.

**Comment by brookhong** [comment]
I could close the page from that URL with `x`.

Do you have special settings opened with `se`?

**Comment by intre4si32** [comment]
@brookhong 
I cleaned the configuration file. they all work fine now.
thank you.

**Comment by intre4si32** [comment]
They all worked. Now precisely this page, I am writing the comment in, is refusing to close.
I will show the whole config:

> // an example to create a new mapping `ctrl-y`
> mapkey('<Ctrl-y>', 'Show me the money', function() {
>     Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
> });
> 
> // an example to replace `u` with `?`, click `Default mappings` to see how `u` works.
> map('?', 'u');
> unmap('t');
> // an example to remove mapkey `Ctrl-i`
> 
> // create a new key `o` for saved temp key `>_t`
> map('gi', 'i');
> map('F', 'af');
> map('gf', 'w');
> // create a new key `o` for saved temp key `>_t`
> map('o', 'og');
> map('H', 'S');
> map('L', 'D');
> map('gt', 'R');
> map('gT', 'E');
> map('K', 'R');
> map('J', 'E');
> 
> // click `Save` button to make above settings to take effect.
> // set theme
> settings.theme = `
> .sk_theme {
>     background: #000;
>     color: #fff;
> }
> .sk_theme tbody {
>     color: #000;
> }
> .sk_theme input {
>     color: #317ef3;
> }
> .sk_theme .url {
>     color: #38f;
> }
> .sk_theme .annotation {
>     color: #38f;
> }
> 
> .sk_theme .focused {
>     background: #aaa;
> }`;

Any thought?

**Comment by intre4si32** [comment]
Sorry to tell but although I managed to get it working, it was way slower for me than firefox + vimperator or perhaps I have slower machine and that makes the difference. It shows slugginess when navigating tabs left and right, when initiating searches with /, when leaving the search, visual caret by Esc. If browser starts only with google.com, it takes lots of seconds to respond to my pressing of keys. Lots of hit and miss.
At this point is for me clear that Vimperator still surpasses what one can get from chrome + javascript.
