### ISSUE TITLE
Issues on some websites

### ISSUE THREAD

**Issue by drod3763** [brookhong/Surfingkeys#325]
Take a website throttle.com for example. You look at a list of emails and press 'f'. You get a lot of hints, a few of which are not even visible on the page:
![screen shot 2017-05-03 at 5 02 44 pm](https://cloud.githubusercontent.com/assets/7785716/25681496/7b08eeb6-3022-11e7-89bd-21ec84a817bb.png)
So you decide to persist and open an email anyway. In this case I am typing 'ba'. That gives you a screen like the below:
![screen shot 2017-05-03 at 5 03 05 pm](https://cloud.githubusercontent.com/assets/7785716/25681593/d399e3aa-3022-11e7-86fb-6efd5cdecceb.png)
I press the 'f' key so I can click the arrow at the bottom of the screen to see the next email in the list but that link is not an option as you can see in the screenshot. If I want to scroll the email visible on the right I cannot do so by default --> so I press 'w' to switch frames. However, once I press the 'w' key I lose all SurfingKeys functionality until I reload the page.

This also happens on other websites. Like Visual Studio Team Services for example. I won't show the screenshots here but if you open a task and make it full screen, you will lose all Surfingkeys until refresh.

These pages work fine with Vimium. Here are the same two screens using Vimium:
1. Fewer links, more based on what's visible.
![screen shot 2017-05-03 at 5 10 57 pm](https://cloud.githubusercontent.com/assets/7785716/25681786/9487ba74-3023-11e7-8a6f-3aa319e0dc72.png)
2. The "Next" arrow is clickable now using 'kw' as seen in this screenshot:
![screen shot 2017-05-03 at 5 12 12 pm](https://cloud.githubusercontent.com/assets/7785716/25681806/aaa1cbe2-3023-11e7-848a-6c27059b4756.png)
3. Change Frames also works using 'gf'. Note the yellow border on the email indicating I can scroll there:
![screen shot 2017-05-03 at 5 12 45 pm](https://cloud.githubusercontent.com/assets/7785716/25681828/c1337b12-3023-11e7-9421-5a358b79a40c.png)
I really like the functionality of Surfingkeys over Vimium and I would definitely use it once issues like these are resolved.

**Comment by brookhong** [comment]
Thanks for reporting this.

I don't have account on throttlehq.com, and there is no free account that could be signed up.
It would be better if you could provide some other site for me to investigate.

**Comment by drod3763** [comment]
I didn't realize they no longer offer free accounts. My account was free but I guess they changed their model. MS Team Services is the second site I mentioned. They still offer free accounts. I'll put some screens together.
