### ISSUE TITLE
Please add support to Firefox 

### ISSUE THREAD

**Issue by gynet** [brookhong/Surfingkeys#329]
Please add support to Firefox

**Comment by ghosthoughts** [comment]
With its latest WebExtensions API, Firefox claims compatibility with Chrome API and, by extension, portability. So, may be, the current codebase doesn't have to reoriented that much. I am not sure about the ground reality though.

surfingkeys is by far the most elaborate keyboard-control extension I've seen. Here is hoping that you are planning to port it to Firefox.

**Comment by adouzzy** [comment]
Please consider.

**Comment by b0o** [comment]
I spent some fiddling around, attempting to add Firefox support via the new WebExtensions API. It seems there would be a large amount of refactoring necessary to accomplish this, as many Chrome-specific APIs are heavily used in the codebase.

**Comment by Stvad** [comment]
+1 I think it's especially relevant now that Firefox is deprecating its old extension API - most of the similar extensions for it have not been adopted to a new one.

**Comment by kalbasit** [comment]
@brookhong what are the known issues? For instance, are you able to load settings from the filesystem?

**Comment by b0o** [comment]
@brookhong 

I'm really excited to hear this! 

Unfortunately, however, it does not appear to be working for me at all. Nothing seems to happen when I press default binding keys like `j`, `k`, etc.

I've tried in both Firefox  `59.0a1` and `57.0`.  

The only message in the console is this:

![image](https://user-images.githubusercontent.com/21299126/33101855-f017d424-cece-11e7-982c-c8b76e002a46.png)

I'm using Arch Linux (`Linux 4.13.12-1-ARCH x86_64 GNU/Linux`).

**Comment by kalbasit** [comment]
It works for me, but it does so intermittently. Try going to the settings page and hit save.

**Comment by b0o** [comment]
@kalbasit That doesn't seem to help for me. :woman_shrugging:

**Comment by b0o** [comment]
It works for me after the latest update from the Mozilla marketplace! Thanks @brookhong, it's perfect so far.

**Comment by brookhong** [comment]
@b0o that is great, but as @kalbasit mentioned, loading settings from local file still not working.

other issues, which seem are not critical.
* many Chrome built-in links not working in firefox, and no alternatives for them, such as new tab.
* sync settings across devices for same account
* proxy settings
* markdown preview

please list what you found if there is.

**Comment by gynet** [comment]
Does the extension got removed from the store?

**Comment by brookhong** [comment]
0.9.15 released for Firefox, closed this.

**Comment by kalbasit** [comment]
@brookhong any known issues with the final release?

**Comment by brookhong** [comment]
Loading settings from local file is fine with 0.9.15.

Below features won't work.
* sync settings across devices for same account
* proxy settings
* markdown preview

**Comment by kalbasit** [comment]
@brookhong I'm getting a 404 when opening https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/ does it work for you?

**Comment by brookhong** [comment]
Please see http://brookhong.github.io/2017/12/09/surfingkeys-for-firefox.html.
