### ISSUE TITLE
Special keys (especially Alt+S) are not shown on help screen (showUsage)

### ISSUE THREAD

**Issue by zsoltika** [brookhong/Surfingkeys#330]
While trying to convert one of my colleagues, I used to tell her just use the `?` key to show the help, but she's always asking how to disable the extension for specific sites and it's (keyboard shortcut (`alt+s`) not listed on the help screen, please add it.

**Comment by brookhong** [comment]
Thanks.

This is indeed necessary, added in 0.8.5.
