### ISSUE TITLE
关于代理问题

### ISSUE THREAD

**Issue by CharlesYaoXing** [brookhong/Surfingkeys#333]
人在国外，有时候需要代理翻墙回国内使用优酷视频等，如何关闭surfingkey自带的代理权限限制

**Comment by brookhong** [comment]
按`spc`, 把Surfingkeys的代理模式设置成`clear`。

这样Surfingkeys就不管代理了。

**Comment by CharlesYaoXing** [comment]
Thanks a lot!!
