### ISSUE TITLE
Make omnibar results editable

### ISSUE THREAD

**Issue by mastersimon** [brookhong/Surfingkeys#336]
After pressing `t` and start typing something, e.g. `hello` the result could look like this:

`https://www.example.com/hello?page=1`

It would be really nice to have the opportunity to edit the suggested URL in order to immediate jump to page 25.

**Comment by brookhong** [comment]
![image](https://cloud.githubusercontent.com/assets/288207/25857957/23857de0-350d-11e7-9e32-148ec746a531.png)

You could press `Ctrl-i` to achieve that.

**Comment by mastersimon** [comment]
That´s great. I didn´t know. Will close this issue.
