### ISSUE TITLE
Commandline popup and search don't work with Google Input Tools

### ISSUE THREAD

**Issue by GordonGustafson** [brookhong/Surfingkeys#337]
I use the [Google Input Tools](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab?hl=en) extension for chromium, but it doesn't work in the 'popup commandline' that comes up when I press `:` or `og`, and doesn't work when searching with `/`. By 'doesn't work', I mean the text I enter in the command line and search is processed as normal english qwerty, instead of obeying the input method I've specified in the Google Input Tools extension (when typing in a text field on a webpage, the method I've specified does get used). This means I can't search the web or current page using my preferred input method.

Is it possible to achieve what I'm looking for? I'm new to both extensions, but I would think that Input Tools would work if the SurfingKeys commandline and search were html text inputs. Are they some different creature that's harder to integrate with Input Tools?

Thanks!

**Comment by brookhong** [comment]
![image](https://cloud.githubusercontent.com/assets/288207/25888677/a698c958-3599-11e7-8a5b-4462d41a4a02.png)
