### ISSUE TITLE
translate.google.com “f” key can not select language

### ISSUE THREAD

**Issue by KnightPublic** [brookhong/Surfingkeys#339]
In [translate.google.com](https://translate.google.com/#auto), when i input 'f', just translate can be select, language button can not be selected.

**Comment by kalbasit** [comment]
I confirm this issue, I don't see the hint even with `settings.clickableSelector = "*.jfk-button, *.goog-flat-menu-button";`

**Comment by brookhong** [comment]
This was just released in 0.8.6, please have a try.

**Comment by KnightPublic** [comment]
![image](https://cloud.githubusercontent.com/assets/27807615/26612625/a4e25e4e-45e8-11e7-99a3-22bf0b203d91.png)

In version 0.8.6 still exists this problem, in [this page](https://translate.google.com/#auto/en/%E5%A4%A9%E6%B0%94)

**Comment by KnightPublic** [comment]
OK, it work. Thank you.
