### ISSUE TITLE
书签栏乱码

### ISSUE THREAD

**Issue by aihuasxy** [brookhong/Surfingkeys#34]
按b时，书签栏乱码

**Comment by cuiweifu** [comment]
![image](https://cloud.githubusercontent.com/assets/719025/12376838/9304226e-bd42-11e5-8dfa-2e2d64132a49.png)

提同样的问题, 截图为证.

**Comment by brookhong** [comment]
谢谢，操作系统是啥？chrome的版本呢？

**Comment by fuhui81** [comment]
我的情况也一样,判断是改变默认自定义字体引起的。 
我自定义默认字体全换成"微软雅黑"后出现这情况，所有omnibar里雅黑不能正常显示字符都这样了。

**Comment by brookhong** [comment]
谢谢，我在一个新装的windows虚拟机里复现了。

0.3.3已解决。
