### ISSUE TITLE
Links shown for 'f' key different than for 'cf' or 'af'

### ISSUE THREAD

**Issue by drod3763** [brookhong/Surfingkeys#340]
Example page: https://store.playstation.com
'f' shows this:
<img width="793" alt="screen shot 2017-05-12 at 3 46 38 pm" src="https://cloud.githubusercontent.com/assets/7785716/26014372/41afcb3a-372a-11e7-8c32-dfb8a80bc443.png">

'af' and 'cf' show this. Note that Games/Movies/TV Shows are not clickable.
<img width="749" alt="screen shot 2017-05-12 at 3 46 46 pm" src="https://cloud.githubusercontent.com/assets/7785716/26014382/47d65448-372a-11e7-8018-027e42b8815e.png">

**Comment by brookhong** [comment]
This is by designed.

When using `af` or `cf`, user usually means to open target in a new tab, thus only hints for `a` links  will be showed.
