### ISSUE TITLE
Breaks facebook messenger input box

### ISSUE THREAD

**Issue by rehnarama** [brookhong/Surfingkeys#341]
**Problem**
When entering facebook messenger (either via messenger.com or facebook.com/messages) the input box fails to show with the error message "Could not display composer"
![could_not_display_composer](https://cloud.githubusercontent.com/assets/1352555/26029038/5a9dc8b0-382c-11e7-9f03-82b74643686a.png)

**Expected behaviour**
The input box should be visible and able to type into

**Steps to reproduce**
1. Install Surfingkeys addon
2. Go to messenger.com

**Work-around**
In surfing keys settings, enter
`
settings.blacklistPattern = /.*messenger\.com.*/i;
`

**Related issues**
People have posted on facebook about the same issue: https://www.facebook.com/help/community/question/?id=10154083228007484

Someone mentioned the extension emoji input as the cause of the issue. Maybe Surfingkeys own emoji input is what's causing the issue?

**Comment by brookhong** [comment]
Could not reproduce it on my side.
![image](https://cloud.githubusercontent.com/assets/288207/26400542/ff8aa976-40b3-11e7-8a1c-9bfb45f46258.png)

**Comment by rehnarama** [comment]
That looks like the pop-up Facebook chat on facebook.com, is that right?

The bug only happens specifically on messenger.com and facebook.com/messages

**Comment by teranex** [comment]
Vimium has the same issue: https://github.com/philc/vimium/issues/2501
For vimium it is caused by the option which prevents input fields from automatically getting the focus when a page is loaded.

**Comment by rehnarama** [comment]
@teranex Ah yes, can confirm that setting `settings.stealFocusOnLoad = false` in Surfingkeys settings make messenger.com work again

**Comment by rafaeln** [comment]
I was getting the same problem, and disabling Surfingkeys was the workaround I used. I wonder, though, if it would be possible to set `settings.stealFocusOnLoad` to `false` only on facebook.

**Comment by brookhong** [comment]
Sure, you could add below in your settings:

    if ( document.origin === "https://www.facebook.com" ) {
        settings.stealFocusOnLoad = true;
    }
