### ISSUE TITLE
[Question] opening Omnibar with t

### ISSUE THREAD

**Issue by idd79** [brookhong/Surfingkeys#345]
When omnibar is opened with `t` the first search hit from history or bookmarks is automatically selected, so it will be opened after hitting `enter`. Is it possible to just show the search results from history and bookmarks without selecting by default, so after hitting `enter` it takes me to the default search engine results instead?

I know I can open the omnibar with `og` for example to search via the search engine, but in this way urls from history and bookmarks are not suggested. So basically I would like a sort of merge between `t` and `og`. Is this possible via settings?

Thanks in advance.

**Comment by brookhong** [comment]
Fixed in 0.8.7.

A new setting -- `settings.focusFirstCandidate` was added for this, to achieve previous behaviors, user must add below setting:

    settings.focusFirstCandidate = true;

**Comment by idd79** [comment]
Great! Thanks a lot for implementing this!
