### ISSUE TITLE
Slow response times - 'letter tooltips' are shown after 1-2 seconds

### ISSUE THREAD

**Issue by igorwojda** [brookhong/Surfingkeys#347]
This issue happens on quite powerful desktop (i7-7700K, Win 10x64, 32GB Ram), so this is probably much slower on laptops and older computers.

I have noticed it on GitHub pull request page (unfortunately it's private repo) with over 40 comments. There is a lot of content - In total this page takes 20 screens to scroll to bottom in in FullHD. Usually it takes 1-2 delay from key press to display 'letter tooltips'

**Comment by shiro** [comment]
On a slower computer I also experience a delay as described in OP, although it works rather smooth on Vimium...

**Comment by crocket** [comment]
Vimium is substantially faster to display hints than surfingkeys.
