### ISSUE TITLE
想请教一下，改样式在哪里改？

### ISSUE THREAD

**Issue by BeliefanX** [brookhong/Surfingkeys#348]
想请教一下，改样式在哪里改？我在设置里面改了，总是不生效。。。

**Comment by brookhong** [comment]
`se`打开设置，这样写就可以的，

    settings.theme = `
    .sk_theme {
        background: #000;
        color: #fff;
    }
    .sk_theme tbody {
        color: #000;
    }
    .sk_theme input {
        color: #317ef3;
    }
    .sk_theme .url {
        color: #38f;
    }
    .sk_theme .annotation {
        color: #38f;
    }
    
    .sk_theme .focused {
        background: #aaa;
    }`;
    

你可以把你的设置贴出来, 我帮你看看哪有问题。

**Comment by BeliefanX** [comment]
哦哦，我刚才试了一下可以了，应该是我油猴脚本里面的插件冲突了，刚才我差了几个插件就可以了，太谢谢你啦！
