### ISSUE TITLE
How to auto show 'F' shortcut?

### ISSUE THREAD

**Issue by linglung** [brookhong/Surfingkeys#350]
How to auto show 'F' shortcut without pressing F button in every web page when opened?
so when i open a web page, there is always any characters which auto shown, then i just need to press a character that shown by F hints

**Comment by lennonwoo** [comment]
@linglung Add the following code snippet to settings works for me
`
window.onload = function () {
    Normal.feedkeys('F');
};
`

**Comment by linglung** [comment]
@lennonwoo  thank so much. It works like a charm
