### ISSUE TITLE
在一些已经网站上不能用快捷键吗？比如 zhihu,oschina

### ISSUE THREAD

**Issue by lovemacs** [brookhong/Surfingkeys#352]
在一些已经网站上不能用Surfingkeys的快捷键吗？
比如 zhihu,oschina,
有什么解决办法吗？

**Comment by brookhong** [comment]
我在zhihu上用得没问题。

提issue时请说明你在哪个页面哪些按键不能用, 最好有截图说明。

**Comment by lovemacs** [comment]
哦哦，试试这个页面，https://www.zhihu.com/question/60199862/answer/173589421
试一下 j或者k上下移动可以不 ..◔ ‸◔???

**Comment by brookhong** [comment]
可以上下滚动的, 没问题

**Comment by liango2** [comment]
卸载重装了一下,确实是可以的,不好意思,谢谢,很好用的插件.

**Comment by wavebit** [comment]
有时快捷键会失效，但是我还没发现重现的规律。
只有刷新页面才能正常。
