### ISSUE TITLE
Go to edit box does not work for FB comments

### ISSUE THREAD

**Issue by ddickstein** [brookhong/Surfingkeys#353]
When trying to jump to an edit box FB's search bar is recognized, as are other fields like composing a new message or a new post.  The "Write a comment..." box is not.

![screen shot 2017-05-22 at 12 26 02 pm](https://cloud.githubusercontent.com/assets/802511/26324968/e2545c24-3ee9-11e7-9712-2c5572dcb73e.png)

**Comment by brookhong** [comment]
It works for me. Do you have your own binding for `i`?

![image](https://cloud.githubusercontent.com/assets/288207/26349917/059c9480-3fe4-11e7-85d4-8b853f332d51.png)

**Comment by ddickstein** [comment]
I'm going to close this for now until I can repro more reliably.
