### ISSUE TITLE
this tab opens often when I start my browser

### ISSUE THREAD

**Issue by vt8235** [brookhong/Surfingkeys#354]
chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html
What would be the cause?

**Comment by brookhong** [comment]
The file is used by Surfingkeys to accommodate UI elements like Omnibar/Help popover, it should be opened in an `iframe`.

I don't see any reason that it is opened in a tab, could you inspect your new tab when starting browser with chrome-dev-tools?
