### ISSUE TITLE
我不能输入gT  yS yG 类似的按键？

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#355]
键入 caps lock 后 提示消失

**Comment by oenstep** [comment]
shift-t  相当于 大写 T
gT = g+ shift+t

**Comment by sgrjyb** [comment]
sg 用谷歌搜索选中文本 ，怎么设置在当前标签打开？

**Comment by sgrjyb** [comment]
sg 用谷歌搜索选中文本 ，怎么设置在当前标签打开？ @oenstep

**Comment by oenstep** [comment]
@sgrjyb 
我不懂javascript,不过在帮助文档 ? 中 go 是在当前标签页面用谷歌搜索
可以先复制选中文本  再  go  艘检索
个人感觉比较麻烦  还是直接向作者提问吧

**Comment by brookhong** [comment]
可以加入这样的设置

    mapkey('og', '#8Open Search with alias g', 'Front.openOmnibar({type: "SearchEngine", extra: "g", tabbed: false})');
