### ISSUE TITLE
Is it possible to edit page url and stay on the current page?

### ISSUE THREAD

**Issue by Ps-Pencil** [brookhong/Surfingkeys#356]
I see in the default mapping, `su` uses `tabOpenLink`. I fiddled around with it a bit but failed to find a counterpart for open link in current page.

**Comment by brookhong** [comment]
add below in your settings

    mapkey('su', '#4Edit current URL with vim editor', function() {
        Front.showEditor(window.location.href, function(data) {
            window.location.href = data;
        }, 'url');
    });

**Comment by Ps-Pencil** [comment]
Cool. I didn't know you could assign to that. Thank you!
