### ISSUE TITLE
请问怎么设置，打开一个页面的时候不自动焦点进入输入框

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#359]
你好，每次打开百度或者淘宝首页的时候，焦点会聚焦到输入框;请问这个怎么设置一下，可以避免呢，之前用过一个插件可以设置不自动聚焦到输入框，谢谢！

**Comment by lennonwoo** [comment]
@haoxuexiaoyao  settings.stealFocusOnLoad = true; 文档里面大多都有的，请仔细看下。

**Comment by haoxuexiaoyao** [comment]
非常感谢
