### ISSUE TITLE
om可以查看你已创建的标示,请问删除这个标示的话怎么操作呢？

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#360]
你好，现在使用类vim标成功，通过om查看的时候，里面的标示如果要删除的话，应该怎么操作呢？谢谢

**Comment by lennonwoo** [comment]
Ctrl-D可以删除Onmibar中的内容

**Comment by lennonwoo** [comment]
@haoxuexiaoyao Ctrl-d可以删除Omnibar中的当前选项
