### ISSUE TITLE
Unrecognized key event: <Hyper>

### ISSUE THREAD

**Issue by kalbasit** [brookhong/Surfingkeys#361]
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 0,
    "code": "ControlLeft",
    "composed": true,
    "key": "Hyper"
}

SurfingKeys: 0.8.6

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html

## Context

In my `.Xmodmap` I have the following:

```
! Turn CapsLock into Control, and LeftControl into Hyper
! https://wiki.archlinux.org/index.php/xmodmap#Turn_CapsLock_into_Control.2C_and_LeftControl_into_Hyper
clear      lock
clear   control
clear      mod1
clear      mod2
clear      mod3
clear      mod4
clear      mod5
keycode      37 = Hyper_L
keycode      66 = Control_L
add     control = Control_L Control_R
add        mod1 = Alt_L Alt_R Meta_L
add        mod2 = Num_Lock
add        mod3 = Hyper_L
add        mod4 = Super_L Super_R
add        mod5 = Mode_switch ISO_Level3_Shift
```

The control key is bound to Hype_L. When I hit `spk` to show me which character did I type, I get an error.

P.S: amazing error handler, I <3 this project!

**Comment by brookhong** [comment]
Thanks, fixed in 0.8.7.
