### ISSUE TITLE
你好,添加的youtube搜索功能出现了问题

### ISSUE THREAD

**Issue by oenstep** [brookhong/Surfingkeys#362]
addSearchAliasX('y', 'youtube search', 'https://www.youtube.com/results?search_query=', 's', 'https://suggestqueries.google.com/complete/search?hl=en&ds=yt&client=youtube&hjson=t&cp=1&q=', function(response) {
    var res = eval(response.text);
    Omnibar.listWords(res[1]);
});

mapkey('oy', '#8youtube', 'Front.openOmnibar({type: "SearchEngine", extra: "y"})');

按oy调出的omni框,输入文本出现自动补全选项,
但是每个选项后面都出现了  ,0  符号
是不是addSearchAliasX 设置错了
![2017-05-29_221705](https://cloud.githubusercontent.com/assets/12694723/26553086/b274ec02-44bc-11e7-95ce-425a6492e89f.png)

**Comment by brookhong** [comment]
改成这样就好了，那个0是YouTube返回的

    addSearchAliasX('y', 'youtube search', 'https://www.youtube.com/results?search_query=', 's', 'https://suggestqueries.google.com/complete/search?hl=en&ds=yt&client=youtube&hjson=t&cp=1&q=', function(response) {
        var res = eval(response.text);
        res = res[1].map(function(u) {
            return u[0];
        });
        Omnibar.listWords(res);
    });
