### ISSUE TITLE
How to prevent automatic loading of next/previous pages?

### ISSUE THREAD

**Issue by thameera** [brookhong/Surfingkeys#364]
I noticed that next/previous pages are automatically loaded when trying to scroll past the top or bottom. (`smartPageBoundary`?)

Is there a way to disable this?

**Comment by brookhong** [comment]
Add below in your settings:

    settings.smartPageBoundary = false;

**Comment by thameera** [comment]
Thank you!

PS: This is the best Vim emulator for Chrome I've used. Awesome work!
