### ISSUE TITLE
sj sz sx 怎么设置在当前标签页打开

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#365]
sj Search selected with 京东

sz Search selected with zhihu search

sx Search selected with 虾米 ......

**Comment by lennonwoo** [comment]
add `tabbed:false` when you use mapkey
for instance
`mapkey('o', '#8Search via Google in current tab', 'Front.openOmnibar({type: "SearchEngine", extra: "g", tabbed: false})');
`

**Comment by sgrjyb** [comment]
@lennonwoo 你这个需要按 o 然后输入文本！ 我问的是 sz 知乎搜索选中文本并在当前标签页打开

**Comment by lennonwoo** [comment]
@sgrjyb 这样的话，可以自己写个函数调用内部的接口函数
`function searchFromClipboard(url) {
    Front.getContentFromClipboard(function(response) {
        let query = window.getSelection().toString() || response.data;
        let search_url = constructSearchURL(url, encodeURIComponent(query));
        RUNTIME("openLink", {
            tab: {
                tabbed: false
            },
            url: search_url
        });
    });
}
var zhihu_url = "https://www.zhihu.com/search?type=content&q=";
// var xiami_url = "http://www.xiami.com/search?key={0}&pos=1";
// var jingdong_url = "https://search.jd.com/Search?keyword={0}&enc=utf-8&spm=2.1.2";
mapkey('sz', '#8Search via zhihu from clipboard in current tab', function () {
    searchFromClipboard(zhihu_url);
});
// mapkey('sx', '#8Search via zhihu from clipboard in current tab', function () {
//     searchFromClipboard(xiami_url);
// });
// mapkey('sj', '#8Search via zhihu from clipboard in current tab', function () {
//     searchFromClipboard(jingdong_url);
// });
`

**Comment by lennonwoo** [comment]
@sgrjyb 那得调用内部的函数了
``` js
function searchFromClipboard(url) {
    Front.getContentFromClipboard(function(response) {
        let query = window.getSelection().toString() || response.data;
        let search_url = constructSearchURL(url, encodeURIComponent(query));
        RUNTIME("openLink", {
            tab: {
                tabbed: false
            },
            url: search_url
        });
    });
}
var zhihu_url = "https://www.zhihu.com/search?type=content&q=";
// var xiami_url = "http://www.xiami.com/search?key={0}&pos=1";
// var jingdong_url = "https://search.jd.com/Search?keyword={0}&enc=utf-8&spm=2.1.2";
mapkey('sz', '#8Search via zhihu from clipboard in current tab', function () {
    searchFromClipboard(zhihu_url);
});
// mapkey('sx', '#8Search via zhihu from clipboard in current tab', function () {
//     searchFromClipboard(xiami_url);
// });
// mapkey('sj', '#8Search via zhihu from clipboard in current tab', function () {
//     searchFromClipboard(jingdong_url);
// });
```

**Comment by sgrjyb** [comment]
@lennonwoo  我再问问 比如我正在 https://pan.baidu.com 页面 然后我想到greasyfork 搜索脚本 而我又不想复制pan.baidu.com 我该怎么设置才能在 https://pan.baidu.com 页面直接搜索？

2 .能不能 h 键设置为 settings.historyMUOrder= true  t 键 设置为 settings.historyMUOrder= false

**Comment by sgrjyb** [comment]
@lennonwoo gh 打开历史记录和  cc 打开选中的网址或系统剪贴板里的网址，怎么设置为在当前标签页打开？

**Comment by sgrjyb** [comment]
@lennonwoo  cc 怎么修改为在当前标签页打开？
mapkey('cc', '#7Open selected link or link from clipboard', function() {
    if (window.getSelection().toString()) {
        tabOpenLink(window.getSelection().toString());
    } else {
        Front.getContentFromClipboard(function(response) {
            tabOpenLink(response.data);
        });
    }
});，
