### ISSUE TITLE
How to disable replacement of default chrome pdf viewer?

### ISSUE THREAD

**Issue by melihovv** [brookhong/Surfingkeys#366]

**Comment by maximbaz** [comment]
Press `;s`. Not sure if this is a permanent toggle though.

**Comment by brookhong** [comment]
Yes, it is a permanent toggle.

Your setting will be persisted in to storage.

**Comment by benjamin-thomas** [comment]
Could you please recommend another way to disable the pdf viewer?

This keyboard shortcut does not work with my current setup.

Thanks

**Comment by erszcz** [comment]
I'd also like to know how to permanently disable the PDF viewer from Surfingkeys config. `;s` does not seem to be persistent.

The viewer built into Surfingkeys doesn't have an option to save the opened PDF, which is handy in Chrome's built-in viewer.

**Comment by b0o** [comment]
To make sure it’s always disabled, I believe you can add the following line to your config:

```js
chrome.storage.local.set({"noPdfViewer": 1})
```

I haven’t tested this, though.

**Comment by benjamin-thomas** [comment]
For what it’s worth, I managed to fix my problem by uninstalling then reinstalling the plugin. I guess some auto update caused some kind of corruption and behavior change. Maybe something to try out?

**Comment by erszcz** [comment]
@b0o This works, indeed! Thank you 🙏

**Comment by Archie-2021** [comment]
> Yes, it is a permanent toggle.
> 
> Your setting will be persisted in to storage.

How can I reenable it?

**Comment by pablospe** [comment]
@b0o Is this still valid?
> chrome.storage.local.set({"noPdfViewer": 1})

I get the following error: `"[SurfingKeys] Error found in settings: TypeError: Cannot read properties of undefined (reading 'local')"`

**Comment by pablospe** [comment]
Fixed it by replacing `chrome.storage.local.set({"noPdfViewer": 1});` with `settings.noPdfViewer=true;` in the config.

From this comment: [here](https://github.com/brookhong/Surfingkeys/issues/2156#issuecomment-2357808392)
