### ISSUE TITLE
京东 输入 s键 光标会进入搜索框 其余按键没问题

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#367]
('cc', '#7Open selected link or link from clipboard', function() {
    if (window.getSelection().toString()) {
        tabOpenLink(window.getSelection().toString());
    } else {
        Front.getContentFromClipboard(function(response) {
            tabOpenLink(response.data);
        });
    }
});

cc 怎么设置为在当前标签页打开？

**Comment by brookhong** [comment]
谢谢。标题里说的是个问题, 下个版本会修复。

另外, 请注意标题和内容尽量相关, 不要随意更改。如果是使用讨论, 可以加我微信。

![image](https://user-images.githubusercontent.com/288207/26862546-cc60eb0c-4b7e-11e7-9d5d-2e1e770abc21.png)
