### ISSUE TITLE
github部分页面无法使用插件

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#369]
页面具体地址：https://github.com/wechat-group/weixin-java-tools
在这个页面上插件直接失效

**Comment by haoxuexiaoyao** [comment]
http://www.cnblogs.com/ityouknow/p/5833560.html  这个页面也是无法正常使用上下浏览网页

**Comment by brookhong** [comment]
谢谢, 0.8.7中已解决。
