### ISSUE TITLE
Bug: settings don't save

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#37]
I've tried multiple ways of saving settings: Local, Global, and gist. All have a problem where Surfinkeys seems to periodically clear the settings and restore them to default. Yesterday, I used a Gist with Global Sync turned on. Today I opened chrome and found the settings reset to default.

**Comment by brookhong** [comment]
I can not reproduce the issue.
Surfingkeys will reset settings to default in case of there is some error in user's settings, could you post your gist link here so that I can help to check?

**Comment by jaredbidlow** [comment]
Here is my config. Also, I had to comment out a few lines like 'b' '/' 'ob' because they weren't working and the default settings work just fine.
    mapkey ('', 'switch tabs', 'Normal.chooseTab ()');
    mapkey ('c-i', 'display help information', 'Normal.showUsage ()');
    mapkey ('u', 'display help information', 'Normal.showUsage ()');
    mapkey ('e', 'half of the screen to scroll up', 'Normal.scroll ("pageUp")');
    mapkey ('d', 'scroll down half a screen', 'Normal.scroll ("pageDown")');
    mapkey ('j', 'fine scroll down the window', 'Normal.scroll ("down")');
    mapkey ('k', 'up subtle rolling window', 'Normal.scroll ("up")');
    mapkey ('h', 'left subtle rolling window', 'Normal.scroll ("left")');
    mapkey ('l', 'right subtle rolling window', 'Normal.scroll ("right")');
    mapkey ('gg', 'jump to the top of the page', 'Normal.scroll ("top")');
    mapkey ('G', 'jump to the bottom of the page', 'Normal.scroll ("bottom")');
    mapkey ('cs', 'switch scroll objects', 'Normal.changeScrollTarget ()');
    // define all the css selectors that can be followed
    Hints.pointers = "a:visible, button, *:visible:css(cursor=pointer), select:visible, input:visible, textarea:visible:not([surfingkeys])";
    mapkey ('f', 'select link', 'Hints.create (Hints.pointers, Hints.dispatchMouseClick)');
    mapkey ('F', 'Open link in new tab', 'Hints.create (Hints.pointers, Hints.dispatchMouseClick, {tabbed: true})');
    mapkey ('gf', 'open a new tab in the background link', 'Hints.create (Hints.pointers, Hints.dispatchMouseClick, {tabbed: true, active: false})');
    mapkey ('i', 'select the input box', 'Hints.create ("input: visible, textarea: visible: not ([surfingkeys])", Hints.dispatchMouseClick)');
    mapkey ('q', 'Selected Click on the image or button', 'Hints.create ("img, button", Hints.dispatchMouseClick)');
    mapkey ('E', 'cut to the left tab', 'RUNTIME ("previousTab")');
    mapkey ('R', 'cut to the right of the tab', 'RUNTIME ("nextTab")');
    mapkey ('B', 'jump back just tabs', 'RUNTIME ("historyTab", {backward: true})');
    mapkey ('gF', 'B inverse operation', 'RUNTIME ("historyTab", {backward: false})');
    mapkey ('S', 'backward', 'history.go (-1)');
    mapkey ('D', 'forward', 'history.go (1)');
    mapkey ('r', 'refresh', 'RUNTIME ("reloadTab", {nocache: false})');
    mapkey ('t', 'Enter to open the link', 'Normal.openOmnibar (OpenURLs)');
    //mapkey ('b', 'From Favourites Open Link', 'Normal.openOmnibar (OpenBookmarks)');
    //mapkey ('oh', 'open from history link', 'Normal.openOmnibar (OpenHistory)');
    mapkey ('om', 'Open links from vim-marks', 'Normal.openOmnibar (OpenVIMarks)');
    mapkey ('v', 'switch visual mode', 'Visual.toggle ()');
    //mapkey ('/', 'Find', 'Find.open ()');
    mapkey ('x', 'closed', 'RUNTIME ("closeTab")');
    mapkey ('X', 'recovery just closed tabs', 'RUNTIME ("openLast")');
    mapkey ('n', 'next search results', 'Find.next (false)');
    mapkey ('N', 'before a search result', 'Find.next (true)');
    mapkey ('w', 'switch frame', 'Normal.rotateFrame ()');
    mapkey('p', 'open the clipboard','tabOpenLink(window.getSelection().toString() || Normal.getContentFromClipboard())');
    mapkey('[[', 'click on the previous link', function() {
        walkPageUrl(-1) || clickOn($('a').regex(/((<<|previous|prev(ious)?)+)/i));
    });
    mapkey(']]', 'click on the next link', function() {
        walkPageUrl(1) || clickOn($('a').regex(/((>>|next|load more|next)+)/i));
    });
    mapkey('ys', "copy the source code of this page", function() {
        var aa = document.documentElement.cloneNode(true);
        $(aa).find('div.surfingkeys_css_reset').remove();
        Normal.writeClipboard(aa.outerHTML);
    });
    mapkey('yt', 'copy the current tab', 'RUNTIME("duplicateTab")');
    mapkey('yf', "Copy this page's URL", 'Normal.writeClipboard(window.location.href)');
    //mapkey('ob', 'upen b results', 'Normal.openOmnibar(SearchEngine, "b")');
    //mapkey('og', 'open g results', 'Normal.openOmnibar(SearchEngine, "g")');
    //mapkey('ow', 'open w results', 'Normal.openOmnibar(SearchEngine, "w")');
    mapkey('on', 'new tab', 'tabOpenLink("chrome://newtab/")');
    mapkey('gb', 'bookmarks', 'tabOpenLink("chrome://bookmarks/")');
    mapkey('gj', 'open the JavaScript settings', 'tabOpenLink("chrome://chrome/settings/contentExceptions#javascript")');
    mapkey('gc', 'cache', 'tabOpenLink("chrome://cache/")');
    mapkey('gd', 'downloads', 'tabOpenLink("chrome://downloads/")');
    mapkey('gh', 'history', 'tabOpenLink("chrome://history/")');
    mapkey('gk', 'Cookies', 'tabOpenLink("chrome://settings/cookies")');
    mapkey('ge', 'extensions', 'tabOpenLink("chrome://extensions/")');
    mapkey('gn', 'proxy', 'tabOpenLink("chrome://net-internals/#proxy")');
    mapkey('gs', 'view source', 'RUNTIME("viewSource", { tab: { tabbed: true }})');
    mapkey('gu', 'open the parent links', 'window.location.href = getParentURL()');
    mapkey('se', 'open set', 'RUNTIME("editSettings", { tab: { tabbed: true }})');
    mapkey('sr', 'reset settings', 'Normal.resetSettings()');
    mapkey('si', 'inspect tools', 'tabOpenLink("chrome://inspect/#devices")');
    mapkey(';q', 'insert jQuery', 'Normal.insertJS("//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.min.js")');
    
    
    addSearchAliasX('g', 'google', 'https://www.google.com/search?q=', 's', 'https://www.google.com/complete/search?client=chrome-omni&gs_ri=chrome-ext&oit=1&cp=1&pgcl=7&q=', function(response) {
        var res = eval(response.text);
        Omnibar.listWords(res[1]);
    });
    addSearchAliasX('b', 'baidu', 'https://www.baidu.com/s?wd=', 's', 'http://suggestion.baidu.com/su?cb=eval&wd=', function(response) {
        var res = eval(response.text);
        Omnibar.listWords(res.s);
    });
    addSearchAliasX('w', 'bing', 'http://global.bing.com/search?setmkt=en-us&setlang=en-us&q=', 's', 'http://api.bing.com/osjson.aspx?query=', function(response) {
        var res = eval(response.text);
        Omnibar.listWords(res[1]);
    });
    addSearchAliasX('l', 'linkedin', 'https://www.linkedin.com/vsearch/f?type=all&keywords=', 's', 'http://api.linkedin.com/v1/people-search:(people:(id))?keywords=', function(response) {
        var res = eval(response.text);
        Omnibar.listWords(res[1]);
    });
    addSearchAliasX('s', 'stackoverflow', 'http://stackoverflow.com/search?q=');
    addSearchAliasX('h', 'github', 'https://github.com/search?type=Code&utf8=%E2%9C%93&q=');

**Comment by brookhong** [comment]
It looks like there is no other error except the lines you commented out. For `Normal.openOmnibar`, the API has changed since 0.3.0, it would be

     Normal.openOmnibar({type: "SearchEngine", extra: "w"})

Please refer the default settings(`se` then `ff`) for new usages. And a better way to change keystroke for functions carried in default mappings is using `map`,

    // an example to replace `u` with `?`
    map('?', 'u');

As the functions tied to the keys may be changed, though I always try to keep default.js stable, but it is not safe to copy default.js to your own settings.

**Comment by jaredbidlow** [comment]
I think that part of my issue is pressing Save twice because I do that a lot. The second save resets the settings to default. The gist textbox contains my gist link however, so I think that  the second pressing of save should have reloaded from gist?
