### ISSUE TITLE
导致 class.hujiang.com 的一些页面打开空白

### ISSUE THREAD

**Issue by alswl** [brookhong/Surfingkeys#370]
使用 Surfingkeys 会导致 http://class.hujiang.com/15217034/intro 高概率出现页面空白（只有 Header）出现。

不确定是否由于 `frontend.html` 加载 cancel 导致的。

**Comment by brookhong** [comment]
我一次都没有重现。

`frontend.html` canceled应该也不会导致页面加载失败的。可以试着清理下chrome cache。

**Comment by alswl** [comment]
@brookhong 我的配置文件：https://github.com/alswl/.oOo./blob/master/.surfingkeys.js

**Comment by alswl** [comment]
@brookhong 我找出原因了，是我配置里面的 `addSearchAlias` 导致了页面无法打开。

**Comment by alswl** [comment]
@brookhong 请问能不能帮我看看我的配置文件，`addSearchAlias` 使用上有什么问题么？
