### ISSUE TITLE
any code to have omnibar appear anywhere on a page

### ISSUE THREAD

**Issue by intre4si32** [brookhong/Surfingkeys#372]
When I scroll down many pages and perform bookmarking of a page or I want to open some new page the omnibar opens at the top of the page but I find myself in the middle or at the bottom and so it remains invisible to me.
Is there something that can achieve this, to have the omnibar pop on the current page, area?

**Comment by brookhong** [comment]
There is no way so far, but you could position the Omnibar at bottom of current page with below setting:

    settings.omnibarPosition = "bottom";
