### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by slifin** [brookhong/Surfingkeys#373]
chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/top.js:1 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Port at index 0 is already neutered.
    at HTMLIFrameElement.e (chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/top.js:1:924)

**Comment by brookhong** [comment]
Do you find this issue occasionally?

Or you can reproduce this issue certainly?
