### ISSUE TITLE
Pressing Enter in Bookmarks bar opens Google Search instead of first matched link

### ISSUE THREAD

**Issue by enterit** [brookhong/Surfingkeys#376]
In previous version of Surfingkeys, I was able to open Bookmarks bar (by pressing B), then I could start typing few letters of the link I am interested in, and pressing Enter would open this link.

In new version 0.8.7, when I type a few letters in Bookmarks, the matches are still highlighted. But pressing Enter opens Google search results for the entered text.
Now I have to select the link using arrow keys before pressing Enter.

Previous behavior was much more useful. Could you please revert it back?

**Comment by kalbasit** [comment]
I have the same problem, it's also affecting the `t` (for open url). I do like this feature/bug where it makes sense (for the `t` for me) and would love a settings controlling it per context.

**Comment by brookhong** [comment]
Please see this issue #345 .

A new setting -- `settings.focusFirstCandidate` was added for this, to achieve previous behaviors, user must add below setting:

    settings.focusFirstCandidate = true;

**Comment by enterit** [comment]
@brookhong the setting works for me, thanks a lot!
Should I close the bug?

**Comment by brookhong** [comment]
Glad that helps. Feel free to close it next time since you're the reporter.
