### ISSUE TITLE
is there a way to find a word (lying between conventional word boundaries) within a page?

### ISSUE THREAD

**Issue by 429IhD0** [brookhong/Surfingkeys#377]
say if i want to find occurrences of the word 'men' on a page but want to exclude 'recommend', 'mend', etc.

there are existing chrome extensions that allows you to do regex search, but doesn't seem to work very well. 

then it occurred to me that there might be an easy way to do this in surfingkeys, either natively or by adding some scripts. 

any pointers would be appreciated. thanks!

**Comment by brookhong** [comment]
Released in 0.8.8

You could press `Ctrl-enter` to search the whole word input.

Or you could input `\bmend\b`, then `enter` to search exactly `mend` without matching `recommend`.
