### ISSUE TITLE
icloud 输入 i 没有进入输入框

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#378]
https://www.icloud.com

**Comment by brookhong** [comment]
当有多个输入框时，你需要按提示键选择哪个输入框。

**Comment by sgrjyb** [comment]
它没有让我选择？
mapkey('i', '#1Go to edit box', 'Hints.create("input[type=text]:visible, textarea:visible", Hints.dispatchMouseClick)');

**Comment by sgrjyb** [comment]
@brookhong 它没有让我选择？
mapkey('i', '#1Go to edit box', 'Hints.create("input[type=text]:visible, textarea:visible", Hints.dispatchMouseClick)');
