### ISSUE TITLE
你好,Omnibar能否修改透明程度(不会阻挡背景).

### ISSUE THREAD

**Issue by oenstep** [brookhong/Surfingkeys#381]
比如这个Omnibar样式,好像能做到一定透明.

mapkey('Q', '#8Open omnibar for word translation', function() {
    Front.openOmniquery({
        url: "https://api.shanbay.com/bdc/search/?word=",
        query: Visual.getWordUnderCursor(),
        style: "opacity: 0.8;",
        parseResult: function(res) {
            var res = eval("a=" + res.text);
            if (res.data.definition) {
                var tmp = [];
                for (var reg in res.data.pronunciations) {
                    tmp.push(`[${reg}] ${res.data.pronunciations[reg]}`);
                    tmp.push(`<audio src="${res.data[reg+'_audio']}" controls></audio>`);
                }
                tmp.push(res.data.definition);
                return [ `<pre>${tmp.join('\n')}</pre>` ];
            }
            return [res.data.definition || res.msg];
        }
    });
});

**Comment by brookhong** [comment]
Add below in your settings:

    settings.theme = `
        #sk_omnibar {
            opacity: 0.8;
        }
    }`;
