### ISSUE TITLE
Question: SurfingKeys unmapAllExcept with GMail (previously: What is the best way to get to SufringKeys (enabled) page from New Tab or page where we disabled it?)

### ISSUE THREAD

**Issue by bojanjovicic** [brookhong/Surfingkeys#384]
Hi there  @brookhong and others,
First of all, I appreciate the work so far! I have been long time user of Vimperator, but this excellent!!!

I have a question in relation to getting to SurfingKeys functionality when on page (e.g. gmail) where I disabled it. So I am on GMail and want to get my Omnibar to do some commands. Previously I would use Ctrl + T for new tab, and then pres TAB on keyboard to remove focus from Chrome's address bar and then type "go" to get omnibar. This doesn't work anymore (maybe Chrome updated), and isn't the fastest way in general.

Any suggestions?

**Comment by bojanjovicic** [comment]
Current solution is to have a page where SufringKeys is enabled (e.g. www.example.com) opened in first tab, so I can quickly jump to it using CTRL + 1, and then get omnibar, etc. But if I do jump to a page (using **'** and then pageshortcut) I lose this tab.

**Comment by brookhong** [comment]
Looks like below setting could help you well:

    unmapAllExcept(['go'], /mail\.google\.com/i);

Above line will clear all mapping keys from Surfingkeys except `go` on gmail.

**Comment by bojanjovicic** [comment]
@brookhong you are Mr. Wizard! 10x

Related question, can I and how add some keyboard bindings using this command (also OK if not possible currently. E.g. I tried, but doesn't work:
`unmapAllExcept(['go', '<Ctrl-i>'], /mail\.google\.com/i);`

And unrelated in general, but maybe for omnibar: is it possible to invoke JavaScript functions that I defined in SurfingKeys options from SurfingKeys's omnibar or something similar? (I know how to bind it to keyboard, and this works fine).

Once again, thanks for great product, and fast response!

**Comment by bojanjovicic** [comment]
Hi @brookhong,
Sorry to create confusion, but Omnibar gets probably in conflict with GMails JS, as then TAB doesn't work properly. Or maybe it doesn't work for me. Here it is how it behaves:

1. Setup: Gmail with SurfingKeys on and added command unmapAllExcept(['go'], /mail\.google\.com/i);
2. Press "go", and SK's omnibar popsup.
3. Enter some text, omnibar filters
4. Press TAB it doesn't move through selections in omnibar, but more in general, so 3 TAB presses get you back to omnibar focus, but none gets you to move the selection of options (links) in omnibar.

Probably this is not a simple issue, especially to debug.

A final question: what is the fastest way (configuration or keyboard) to invoke SF's omnibar from new tab?

**Comment by brookhong** [comment]
Thanks. What you found about the TAB key in omnibar for this case is a bug. It will be fixed in next released. For now you could include the fix in your settings to get around this.

    function unmapAllExcept(keystrokes, domain) {
        shouldWorkFor(domain, function() {
            var modes = [Normal, Insert];
            modes.forEach(function(mode) {
                var _mappings = new Trie();
                keystrokes = keystrokes || [];
                for (var i = 0, il = keystrokes.length; i < il; i++) {
                    var ks = encodeKeystroke(keystrokes[i]);
                    var node = mode.mappings.find(ks);
                    if (node) {
                        _mappings.add(ks, node.meta);
                    }
                }
                delete mode.mappings;
                mode.mappings = _mappings;
                mode.map_node = _mappings;
            });
        });
    }
    unmapAllExcept(['go'], /mail\.google\.com/i);

**Comment by brookhong** [comment]
And `unmapAllExcept` works for multiple commands, such as

    unmapAllExcept(['go', '<Ctrl-i>'], /mail\.google\.com/i);

works fine.

**Comment by bojanjovicic** [comment]
Hi @brookhong,
All that you wrote works like a charm. I will raise a separate topic for other issue I experienced.

I renamed the issue so it reflects the last posts in this thread.
