### ISSUE TITLE
Hide HUD

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [brookhong/Surfingkeys#385]
Is there a setting for hiding the HUD. More specifically the box that pops up on pressing 's' and the one that states how many ms it took to generate link hints. And how do you specify font and font size for link hints because I've had no luck myself. Thank you.

**Comment by brookhong** [comment]
You could hide the rich hints(the box that pops up on pressing `s`) with setting:

	settings.richHintsForKeystroke = false;


But for the status message of link hints, there is no way to hide them so far.


To set font size of link hints, you could use:

	Hints.style("border: solid 3px #C38A22;font-size: 22pt;");

**Comment by eyvindbjartiandersen** [comment]
Thank you that solves exactly what I was looking for. I know what the keys does and don't need extra help. Is all the settings listed somewhere?. If there was a list I could find and configure just to my liking.

**Comment by eyvindbjartiandersen** [comment]
I just noticed a small box down in the right corner indicating which key has been pressed. Can I get rid of it?. I just want minimal UI interaction.

**Comment by eyvindbjartiandersen** [comment]
How to increase the size of the boxes or padding in order to accomodate larger font sizes?.

**Comment by brookhong** [comment]
Do you mean size of the boxes for hints? If yes, you could simply add style for padding as others, such as

    Hints.style("border: solid 3px #C38A22;font-size: 22pt;padding: 5px");


And for your previous questions,

> Is all the settings listed somewhere?

https://github.com/brookhong/Surfingkeys#properties-list

> Can I get rid of it?

So far, there is no way.
