### ISSUE TITLE
When using unmapAllExcept with Gmail and mapping commands starting with g (i.e. "go" for omnibar) GMails shortcuts starting with g don't work (e.g. "gi" for going back to inbox)

### ISSUE THREAD

**Issue by bojanjovicic** [brookhong/Surfingkeys#386]
When using _unmapAllExcept_ with Gmail and mapping commands starting with g (i.e. "go" for omnibar) GMails shortcuts starting with g don't work (e.g. "gi" for going back to inbox)

Setup is from #384

**Comment by brookhong** [comment]
Then you could use below settings:

    // use Ctrl-t instead of `go` for opening Omnibar
    map('<Ctrl-t>', 'go');
    // clear all mappings except Ctrl-t
    unmapAllExcept(['<Ctrl-t>'], /mail\.google\.com/i);

You could choose other shortcut you'd like for `Ctrl-t` here.

**Comment by bojanjovicic** [comment]
Thank you very much @brookhong! I understand the idea, and used this to map Ctrl-o for Omnibar and tried Ctrl+t for Omnibar in new tab, but it seems Chrome doesn't allow Ctrl+t to be overriden, so I mapped it to Ctrl+r. 

Here is my setup:
```javascript
// use Ctrl + R instead of `t` for opening new Tab Omnibar
map('<Ctrl-r>', 't');
// use Ctrl + O instead of `go` for opening Omnibar
map('<Ctrl-o>', 'go');
unmapAllExcept(['<Ctrl-o>', '<Ctrl-r>', '<Ctrl-d>'], /mail\.google\.com/i); // Clear all keyboard mappings for Gmail except the ones listed (Ctrl-d is my mapping for a custom Javascript function for Gmail search by subject)
```

@brookhong , I will close this one, as it is solved, and for Ctrl+t you decide. I have a general question: is there some manual for SurfingKeys that I am missing, or if there is not, could I contribute by starting or adding to the existing one? Just the stuff that you helped me achieve in past few days?

**Comment by brookhong** [comment]
Thanks.

Currently [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) is the only document for user to refer.
But you could edit [wiki](https://github.com/brookhong/Surfingkeys/wiki) here. Everyone should have permission on that.
