### ISSUE TITLE
Surfkeys takes up 100% of CPU

### ISSUE THREAD

**Issue by chinchin96** [brookhong/Surfingkeys#388]
Every time I have the surfkeys extension on and using it on a page, my Chrome CPU utilization quickly shoots to 100% or more. This makes the webpage completely unusable and it doesn't matter what page I go to. 

Are others seeing this? Can this be resolved?

**Comment by brookhong** [comment]
This is interesting.

Could you provide more info? such as OS / chrome version and on which page you find this issue?

**Comment by chinchin96** [comment]
Hey brookhong,

Rather than type, see attached video​
 SurfKeys CPU Usage.mp4
<https://drive.google.com/file/d/0B4RKgy4DVz6JYVdDYlFKU2NZZ0E/view?usp=drive_web>
​
I'm using Chrome Canary.

[image: Inline image 1]

--------------------------------
Chinedu Ezeamuzie
(404) 514-7910

**Comment by brookhong** [comment]
Thanks a lot for the video, which helps.

I identified the cause and fixed it. Released in 0.8.8, please have a try.

**Comment by chinchin96** [comment]
Hey man,

Thanks for taking a look at this.  Your fix help a lot. I still get 100%
CPU utilization from time to time but it's a bit harder to replicate
consistently. Sometimes it happens when I'm trying to use it rapidly or
repeatedly (e.g. with browser automation like Keyboard Maestro etc.).  If I
can get a reproduceable scenario, I will post and re-open issue.

Thanks,

--------------------------------
Chinedu Ezeamuzie
(404) 514-7910
