### ISSUE TITLE
Disable j and k default behavior while navigating PDF file

### ISSUE THREAD

**Issue by jmolero** [brookhong/Surfingkeys#394]
When holding j key for example, the pages start to jump. Can that be disabled and just use normal scroll while holding j or k?

Thanks!

**Comment by brookhong** [comment]
Fixed.

**Comment by jmolero** [comment]
I can't see any difference. 

When holding "j" for a short moment the pages start to jump one by one. I would like it to keep the smooth scrolling if possible.

Thanks for this awesome plugin btw!
