### ISSUE TITLE
俩问题

### ISSUE THREAD

**Issue by ufwfqpdgv** [brookhong/Surfingkeys#399]
1 内置vim的设置说明能详细些？好像不支持非递归？即nnoremap，还有配置的时候最好可以兼容一般的.vimrc，实在是不想再改一遍。。。
2 搜索模式有bug（如t进入那个），使用搜狗五笔输入法时，会连带英文编码一起输入，例：搜索“黑莓”，但输入栏会出现，“lfat黑莓”

**Comment by ufwfqpdgv** [comment]
1

**Comment by ufwfqpdgv** [comment]
插入框的判断并不准备，经常明明只有一个输入框，但却标记多了边上的链接或按钮。。。

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/issues/311

没有打算考虑兼容vimrc, 如果需要兼容vimrc, 可以试试[cVim](https://github.com/1995eaton/chromium-vim)

你说的第二个问题是在哪个系统下发现的？

**Comment by vefish** [comment]
按T输入五笔时确实有此问题，
比较多出现在两个字中间比如打为何
![mid](https://user-images.githubusercontent.com/2961937/28911600-b8f9335c-7839-11e7-8938-236dc9f40e55.png)
，最前面也有
![fro](https://user-images.githubusercontent.com/2961937/28911608-c0d412b8-7839-11e7-8dbe-db5312df6a3b.png)

操作系统WINXP，极点五笔

另外我想请问下，按t后输入网址，比如bing.com，回车默认为搜索，怎样改成回车后直接访问对应的网址呢谢谢
