### ISSUE TITLE
Add a method for mapping "F" to open link in new tab via hint.

### ISSUE THREAD

**Issue by aaronbieber** [brookhong/Surfingkeys#4]
I'm not sure if this is already possible. If it is, an example in the documentation would be helpful. I am unsure how to use `Hints.create()` and get back the URL so that I can do something like `window.open()` or similar.

Ultimately I want to have the binding like in cVim where "F" shows hints and opens the selected hint in a new tab.

**Comment by brookhong** [comment]
just hold `shift` when you press the hint chars, actually you don't need to hold shift from the beginning. Holding shift at the last char is good to go.

**Comment by brookhong** [comment]
And here is an example to create your own `F`, if you'd like, though it's not necessary.

    mapkey('F', 'Open a link in new window', function() {
        Hints.create("a:visible", function(link, event) {
            window.open(link.getAttribute('href'));
        })
    });
