### ISSUE TITLE
Auto-hide cursor on keydown

### ISSUE THREAD

**Issue by b0o** [brookhong/Surfingkeys#400]
I'm not sure if this is an issue on MacOS/Windows, but on Linux the mouse cursor is not automatically hidden on keydown/during scrolling. This is somewhat annoying, especially while scrolling through an image gallery or while reading an article as the cursor often gets in the way.

cVim has a setting for this called "autohidecursor" - here's the [changelog entry](https://github.com/1995eaton/chromium-vim/blob/fb4add1bc7ff0b1eb78d553a47d6bd130a6b6a40/CHANGELOG.md#1251) describing the feature when it was initially added:

> Added autohidecursor option (useful for Linux operating systems, which don't automatically hide the mouse cursor when a key is pressed). You can test this out by running the command :set autohidecursor and scrolling with j/k (might have to nudge mouse cursor then scroll to see it disappear initially).

And here's the full commit where the feature was implemented: https://github.com/1995eaton/chromium-vim/commit/e54c35dbf08628660f0ef1513f0a50dd33c387ab

If you (@brookhong) think this is a good idea, I can try and implement it some time soon.

**Comment by brookhong** [comment]
The issue does not happen on MacOS, but IMHO, this is a good idea as it helps people using Linux(maybe also Windows).

PR is welcomed for this, thanks for the idea and passion to implement it.

**Comment by b0o** [comment]
After some research, I've come across a utility named [xbanish](https://github.com/jcs/xbanish).  

I think, rather than implementing this feature inside of surfingkeys, this tool is a better solution to this problem. 

I'm going to go ahead and close this issue.
