### ISSUE TITLE
[Feature] Go to first input

### ISSUE THREAD

**Issue by guilhas** [brookhong/Surfingkeys#401]
Hello,

Would it be possible to add key combination 'gi' as go to first input field?

It is present in VimFx and cVim
https://github.com/akhodakivskiy/VimFx/blob/master/documentation/commands.md#gi-1

Regards,
Lino

**Comment by brookhong** [comment]
add below in your settings:

    mapkey('gi', '#1Go to the first edit box', function() {
        Hints.create("input[type=text]:nth(0)", Hints.dispatchMouseClick);
    });

**Comment by guilhas** [comment]
Wow fast.  Looks good.

Thank you
