### ISSUE TITLE
open new tab on next right from current tab

### ISSUE THREAD

**Issue by SugeunOh** [brookhong/Surfingkeys#404]
thank you for surfingKeys. 
I'm very happy with that. 

I really want to open new tab on next right from current tab 
in every openning new tab action. 

Is there any flag or option?

Because my use-case is searching A / B / C category in a day.
and then looking A -> open new Tab for a1, a2, a3 => A / B / C / a1 / a2 / a3
after that, looking C -> open new Tab for c1, c2, c3 => A / B / C / a1 / a2 / a3 / c1 / c2 / c3

So if I didn't move new tabs, it's too mixed.

I want below order of tabs like .. A / a1 / a2 / a3 / B / C / C1 / c2 / c3 

thank you again!!

**Comment by brookhong** [comment]
Add below in your settings:

    settings.newTabPosition = "right";

**Comment by SugeunOh** [comment]
thanks a lot !!
I'm so happy with that option.
