### ISSUE TITLE
在Surfingkeys的设置界面使用`/`搜索会导致插件无响应

### ISSUE THREAD

**Issue by gitterliu** [brookhong/Surfingkeys#405]
1. 打开Surfingkeys设置界面
2. 打开Default mappings
3. 使用`/`搜索某字母
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/31594508-ed6832f0-b1fa-11e7-8162-09a27b884062.png)

应该已解决了。

**Comment by gitterliu** [comment]
Thank you for fixing this.
