### ISSUE TITLE
Hints are broken on http://www.metafilter.com/

### ISSUE THREAD

**Issue by thedward** [brookhong/Surfingkeys#407]
On [metafilter.com](http://www.metafilter.com/), the hints all show up uselessly clustered just below(?) the bottom of the page. That is, if I press for example `f`, I don't see any hints, but if I scroll down past where the bottom of the page used to be all the hints are clustered along the horizontal access there.

Very odd.

**Comment by brookhong** [comment]
Thanks for reporting the issue.

The site has an abnormal css style for `html:*`, and it seems the site has already fixed the style.

Anyway,  I have committed a fix to work around the issue.
