### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by rosshadden** [brookhong/Surfingkeys#408]
Is there a reference somewhere for all the available commands?  The best I could find is the default mappings file.

**Comment by rosshadden** [comment]
Also where are the input mappings defined?  I only see two occurrences of `imapkey` in the default mapping file.

**Comment by simonwjackson** [comment]
@brookhong I'd like to tackle this issue. It's a fairly large undertaking, so I wanted to get your thoughts on this before I get started.

**Comment by brookhong** [comment]
@simonwjackson 
It would be a great favour if you could help to address the API Reference doc.

As you said, it is a fairly large task, it needs much understanding of current code, also may lead some discussions and code changes if we saw something improper to publish as an API.

Feel free to start it.

[Default mappings](https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js) could be a referrence.

**Comment by brookhong** [comment]
@rosshadden 

Most mappings in Insert mode are defined within [insert.js](https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/insert.js#L23).

`imapkey` is a kind of `wrapper` function.

**Comment by simonwjackson** [comment]
@brookhong great! Looking forward to this 😄 

Can you assign the task to me?
