### ISSUE TITLE
Show multiple text box hint on google homepage

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#411]
I like to go to the search box using "i" on google homepage, but it show multiple hint. I need to type "a" again to finish the action.

**Comment by brookhong** [comment]
Try the solution here, which will be added to default mapping in next release.

https://github.com/brookhong/Surfingkeys/issues/401

**Comment by laphylee** [comment]
Thanks for your quick response! I think going to the first one and showing all inputs are separate and both meaningful tasks. Maybe we can map "f" using `Hints.create("input[type=text]", Hints.dispatchMouseClick)`? Do you think other types of input element can be filtered out instead of text type?
