### ISSUE TITLE
"Open an url in current tab" turns into google>> prompt if text not in history

### ISSUE THREAD

**Issue by wleese** [brookhong/Surfingkeys#418]
1. use the default key binding: go
2. omnibar opens.
3. type in any string that does not exist in your history such as wesdwesd
4. the moment you type the character that stops matching any (sub)string of your history, the prompt changes to google>> no longer allowing you to type in an url.

This is very jarring. For example if I copy and paste and URL (if it's not in my history) it will google search the url.

**Comment by wleese** [comment]
I tested this with a clean profile:
1. create new person in chrome
2. install surfingkeys
3. type: goabc.com<enter>

Result: google.nl/search?q=abc.com ...

Expected result: abc.com

**Comment by brookhong** [comment]
Already fixed.

**Comment by vefish** [comment]
it there a setup to fix it?
I run a test on a new chrome on a new win7, still not open 'abc.com' directly,  just google for it.
![1](https://user-images.githubusercontent.com/2961937/30807135-21615eb8-a22b-11e7-8031-cf33a3a12714.png)

**Comment by brookhong** [comment]
Please see https://github.com/brookhong/Surfingkeys/issues/486#issuecomment-329808404
