### ISSUE TITLE
Mode Normal pushed into mode stack again.

### ISSUE THREAD

**Issue by livelazily** [brookhong/Surfingkeys#419]
## Error details

Modes in stack: GetBackFocus,Normal

SurfingKeys: 0.9.0

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

URL: https://cowlevel.net/article/1899133

## Context

Just open the page

**Comment by brookhong** [comment]
Thanks a lot.

Fixed in 0.9.1.
