### ISSUE TITLE
pass current youtube url to vlc or mpv video player

### ISSUE THREAD

**Issue by valdoonicanlives** [brookhong/Surfingkeys#42]
I don't know javascript , I would like to pass the current url to vlc or mpv , something like?
mapkey("Mod1 m", function () { 
  system.spawn("sh -c 'vlc $(" + tabs.current.uri + ")'"); 
});

**Comment by brookhong** [comment]
There is no support to launch external program with javascript. But you can create mapping below

    mapkey('a-m', "create vlc command line", function() {
        Normal.writeClipboard('vlc ' + window.location.href);
    });

Then pressing `alt-m` will build a command line in clipboard, which you can paste within a launcher like `alt-f2` / `win-r` to run.

**Comment by 097115** [comment]
@brookhong 

> There is no support to launch external program with javascript.

Just a clarification: nothing has changed here, no workaround possible because of security reasons, right?
