### ISSUE TITLE
How can I make surfingkeys working on other extension pages?

### ISSUE THREAD

**Issue by ffplayer** [brookhong/Surfingkeys#421]
Such as  "tab suspender" When a tab was suspended by it the url will change to like this:
`chrome-extension://fiabciakcmgepblmdkmemdbbkilneeeh/park.html?title=Google&url=https%3A%2F%2Fwww.google.com*****`

when I switch tabs to this suspended tab, all the hotkeys will not work, and I have to  switch to other tabs to make surfkeys working.

Is it possible to make surfingkeys working on other extension pages like tab suspender?

**Comment by brookhong** [comment]
Chrome does not allow that for security.

Same as that extensions could not work for chrome.google.com/webstore and chrome://extensions/.

**Comment by brookhong** [comment]
Please see http://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages.html

**Comment by TwoLeaves** [comment]
Vimium-C implements an "[injection mode](https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions)" which makes this possible. Feasibly this could be added to Surfingkeys.
