### ISSUE TITLE
Too many console logs when vue-devtools is open

### ISSUE THREAD

**Issue by mu-yu** [brookhong/Surfingkeys#422]
1. open dev tools with vue-devtools installed 
2. switch to vue-devtools panel,
3. switch to components panel,
4. move mouse over components and there will be so many console logs caused by `console.log(_message)` in `top.js`.

![image](https://user-images.githubusercontent.com/3822774/28448065-b48dae92-6e07-11e7-812f-70e2ed0a6c12.png)

**Comment by brookhong** [comment]
Thanks a lot.

Fixed in 0.9.1.
