### ISSUE TITLE
你好,今天打开surfingkeys设置是弹出提示.

### ISSUE THREAD

**Issue by oenstep** [brookhong/Surfingkeys#426]
settings sync may not work throughtly because of :quota_bytes_per_item quota exceeded
![2017-08-01_235826](https://user-images.githubusercontent.com/12694723/28836131-5acae818-771a-11e7-8168-c0dbc18f9eb6.png)

不太清楚是什么,是不是chrome同步不了surfingkeys的设置.

**Comment by brookhong** [comment]
是的, 这个提示说明你设置里的JS脚本已经超过chrome可以同步的单项大小限制了。

你可以选择用gist同步设置, 或者, 从文件加载设置, 然后用github/网盘之类的服务来同步改文件。
