### ISSUE TITLE
Feature request: Tab Attach/Detach

### ISSUE THREAD

**Issue by paradox460** [brookhong/Surfingkeys#427]
We currently have the ability to detach a tab, via the default `W` binding.

However, I don't believe we can attach/move a tab to an existing window. This was a feature that i found particularly useful in cVim, and would love to see it return.

In cVim, you could open the command console, type `tabattach`, and you would be presented with a list of open windows. Selecting one would allow you to move the current tab to the specified window

**Comment by rosshadden** [comment]
I notice you can hit `W` again on the recently-detached tab and it reattaches it.

**Comment by paradox460** [comment]
Thats true, and very handy. But the particular feature I was thinking about was the ability to basically send tabs between windows, on the fly. Say I open 20 tabs, and skim through them. I could split each tab off into its own window, save each window as a session, and then have multiple starting points.

Since chrome doesn't support TabStacks, like Vivaldi/Brave, this was the next best thing.

Think of how you can send panes from one TMUX window to another.

**Comment by rosshadden** [comment]
Yeah I get it, I only very recently switched from mouseless (cvim fork) to surfingkeys, and for a while I maintained both configs side-by-side just so I could merge tabs/windows with mouseless and so I could scroll (until #432 was fixed).  But that had side-effects I got tired of dealing with.

**Comment by Stvad** [comment]
Another former cVim user here and tabattach/detach is indeed very handy!

**Comment by Tanath** [comment]
I need this feature to stay organized. I have many tabs in multiple windows, and keep related tabs together in the same window. The ability to send a tab to a particular window is very useful to me and would be much appreciated.

**Comment by Omnihil** [comment]
Often I just need to write things from one tab into some form into another, would be so SO useful to have that feature like in cVim
