### ISSUE TITLE
[feature] Mouse cursor move to selected element

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#428]
Example. When i press some keys a menu appears where I want to go (like pressed "f") and mouse cursor moved to selected place.

new features:
- mouse move
- left mouse click
- right mouse click

Some sites do not work well with "f" and sometimes the list of links appears only after you hover the cursor over them.

**Comment by b0o** [comment]
@D1mon I don't believe it is possible to move the user's mouse cursor with JavaScript as that would have large security implications. See https://stackoverflow.com/a/4752512/8202881

**Comment by petr-tik** [comment]
@b0o what about mouse click? You can do mouse out and mouse over elements, is it possible to do a mouse left click?
