### ISSUE TITLE
在知乎阅读全文链接不起作用等问题

### ISSUE THREAD

**Issue by vefish** [brookhong/Surfingkeys#429]
1. 知乎  如果是刚打开，按f后阅读全文是有hint的，但只要向下一滚动就不行了
![default](https://user-images.githubusercontent.com/2961937/28912917-d6764686-783e-11e7-850c-018bbe7d158b.png)
类似的，在workflowy.com里HOME上也是不出现hint；经过简悦插件转化阅读模式的文章里的链接不出现hint
2. 文本框里已经输入的内容有什么办法做到一键清除吗（比如在当前搜索页做第二次不同关键字完全不同的搜索的时候）
3. 浏览器默认搜索引擎更改后按t的搜索引擎还是原来的，需要在哪单独定义吗

**Comment by brookhong** [comment]
1. 重新不了这个问题。
2. 这个应该不需要插件帮忙的。我觉得Ctra-a全选之后，直接输入挺方便的。
3. 是的，你需要在设置里添加下面这行，

        settings.defaultSearchEngine = 'b';

可参考 https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#搜索选中文本

**Comment by vefish** [comment]
感谢回复，3解决了，2估计要求比较小众
1目前我这个环境下还是有问题的，又试了试，如图
刚打开首页时可以
![zh1](https://user-images.githubusercontent.com/2961937/29024008-c68753c2-7b78-11e7-84fc-748bc13fe9c2.png)
向下翻页就不行了
![zh2](https://user-images.githubusercontent.com/2961937/29024019-cf1beb24-7b78-11e7-8b3f-6c961205d9cd.png)
workflowy.com里进入二级以下想返回HOME的时候无hint
![wf](https://user-images.githubusercontent.com/2961937/29024103-178d832c-7b79-11e7-9328-6a65f7e20f8c.png)
经简悦转化阅读模式的页面上无效
![js](https://user-images.githubusercontent.com/2961937/29024126-33ee3fca-7b79-11e7-9c17-93164701b305.png)

PS: #399 issue中遇到了和提问人一样的问题，已贴图

THX
