### ISSUE TITLE
Next/Previous page on scroll stopped working

### ISSUE THREAD

**Issue by paradox460** [brookhong/Surfingkeys#433]
Recently, the Next/Previous page scroll feature has stopped working.

Previously, when I would get to the bottom of a page and continue to hit the scroll-down binding, it would navigate to the next page. Some time in the near past, say, 3-5 days ago, it stopped working.

The site in question didn't change the way they render the Next/Previous buttons, the regular expression in the default settings still match, but it just doesn't work anymore.

I've tried disabling all my browser extensions save for Surfingkeys, reinstalling surfingkeys, resetting surfingkeys settings, and nothing can get it working again.

----

The site I've been using for testing is [the elixir getting started guide](https://elixir-lang.org/getting-started/introduction.html), which I previously used the next page navigation feature to great success

**Comment by brookhong** [comment]
`smartPageBoundary` was turned off by default in this commit https://github.com/brookhong/Surfingkeys/commit/81503cf6d10926c393f99915ea496356d023baac#diff-0532715f02861898205027463cc52dfe , as I got some negative feedback on the feature.

You could enable it with below in settings,

    settings.smartPageBoundary = true;

or specially only for some sites

    if (document.origin === "http://global.bing.com"
        || document.origin === "https://www.google.com"
    ) {
        settings.smartPageBoundary = true;
    }

**Comment by paradox460** [comment]
Thank you!
