### ISSUE TITLE
你好,这里提一些建议(虽然不知道能不能实现)

### ISSUE THREAD

**Issue by oenstep** [brookhong/Surfingkeys#437]
surfingkeys版本,0.9.1版本   chrome版本 60.0.3112.90（正式版本） （64 位）
1. 对于使用'se'打开surfingkeys设置,能否加上检验当前打开的标签功能,如果当前标签已经打开了的话直接跳转到打开的surfingkeys设置标签.

2. 对于'b'打开bookmark,能否添加记忆功能,读取一下打开次数优先按照打开次数排序,这样对于经常打开的网址就非常友好,虽然可以直接在chrome的书签栏添加,不过好像不能添加太多.

3. 对于'gk'打开cookie页面,原本的chrome://settings/cookies已经不能打开了,我直接在chrome设置打开的地址为chrome://settings/content/cookies,应该不是我装了其他插件到导致的,我是直接在用户重新mapkey添加chrome://settings/content/cookies

4. 对于删除收藏的网址,目前好像只能在't'的Omnibar上Ctrl - d删除,希望能添加在'b'bookmark上删除功能,以及打开中的页面的快捷删除.

5. 对于不能直接用X删除chrome系统的页面有点难受,能否直接替换ctrl-w,虽然不知道能不能(之前看issue说是chrome本身的设定)

差不多就这些了,提要求确实很简单,做就不太容易,谢谢作者,很喜欢这款插件,要求这么多会不会有点过分XD.

**Comment by oenstep** [comment]
还有一个,对于Visual mode,这里好像有两个阶段一下V为光标移到,再一下V才是选择文本,在按一次ESC为返回到光标阶段,第二次才ESC会退出Visual mode,能否添加一些设置按一次ESC直接退出Visual mode.

**Comment by oenstep** [comment]
你好作者,这里发现一个chrome的扩展Bookmark Sidebar,他可以通过surfingkeys的javascript来控制,这种和原本的chrome的bookmark排序一样的侧边栏(也可以按照最近使用,我是这样来实现第二个问题的)真的不错,原本的chrome不支持javascript控制这样就很好的解决,况且它不占用'gb'的命令,希望作者试试,看一下能不能有新的方向.

**Comment by brookhong** [comment]
任何有价值的问题都是受欢迎的，不会过分。

1. `se`如果直接跳转到打开的surfingkeys设置标签。如果想重复打开设置就不方便了，这是个习惯问题，而且打开设置的次数也不会太多。没有人总想改设置。

2. 你可以用`t`键，那里出来就不只有收藏夹里的，包括所有的访问历史。

3. 多谢，下个版本会改过来，好久没用这个按键了。

4. `b`出来的Ctrl-d也是可以删除的，`;db`是从收藏夹中删除当前页。

5. 不能，这个目前没有办法。

**Comment by oenstep** [comment]
谢谢作者回答,都了解了,原来b下可以用ctrl-d删除,页面可以用;db删除啊,谢谢,虽然想利用autohotkey在chrome程序中修改Ctrl-d为X,不过我要用X来输入就有点尴尬,对了Visual mode按两次退出能否改为一次退出(就是添加一下个人的设置),还有建议作者去试试看Bookmark Sidebar这个插件,能直观的查看bookmark(目录树结构,与本身的chromebookmark一致)并且可以用surfingkeys控制,很喜欢这款插件,再次感谢.
