### ISSUE TITLE
为什么电脑朗读，总是只读一行就没有了

### ISSUE THREAD

**Issue by wagic520** [brookhong/Surfingkeys#440]
为什么电脑朗读，总是只读一行就没有了
还有朗读速度可以加快点吗？

**Comment by brookhong** [comment]
你读的是英文还是中文？

还有你是怎么读的？是选中文本按`gr`, 还是在omnibar里输入命令的？

**Comment by wagic520** [comment]
读的中文 ，用v   v ｝｝ gr ，读到第一行70%的位置

**Comment by wagic520** [comment]
是不是google的有时间限制，每回读到一定时间就停了
