### ISSUE TITLE
[Feature Request] Domain specific settings

### ISSUE THREAD

**Issue by gnosticscrounger** [brookhong/Surfingkeys#442]
I'm aware that you can assign domain specific keymapping but it would be cool if you could have more general settings that are specific to a domain. For example, I might want to automatically go incognito when visiting a certain URL.

I'm not 100% sure if this is even possible within the constraints that Chrome extensions have but Surfinkeys already seems to be capable of things that I previously thought Chrome Vim-like interfaces were not so I am hopeful.

**Comment by brookhong** [comment]
You could add domain specific settings as below,

    if ( document.origin === "https://www.google.com" ) {
        settings.smartPageBoundary = true;
    }

But now there is no API for you to open URL in incognito mode.

**Comment by gnosticscrounger** [comment]
Ah, thank you! 

That's a shame. Really wish Google opened up their API more but that particular constraint is certainly workaround-able.
