### ISSUE TITLE
Can I change the cursor mode in visual/caret mode?

### ISSUE THREAD

**Issue by jaimehrubiks** [brookhong/Surfingkeys#443]
First of all, I am new to this extension and I am ejoying it a lot, so thanks for your work.

I'd like to know if it is possible to change how the cursor works in visual/caret mode.
Currently, it is an **I-beam shaped** cursor that displaces the rest of the characters when it is moved.

I'd like to be able to use a **block shaped** cursor (like in vim indeed). I also don't like that 'effect' of it displacing all other characters.

Clarification on cursor types: https://i.stack.imgur.com/zn6C1.png
(we have vertical bar and I was expecting to have block as in vim)

**Comment by brookhong** [comment]
Not now, but thanks for the suggestion.

Block shaped cursor seems to be better choice here, will add this to backlog.

**Comment by jaimehrubiks** [comment]
Cool!

**Comment by jaimehrubiks** [comment]
@brookhong 

I found a "trick" to make a block cursor for visual mode without re-coding it. I guess it is kind of too "hacky" so didn't make PR. Even it is funny that making a negative margin would work.

https://github.com/brookhong/Surfingkeys/compare/master...jaimehrubiks:cursor?expand=1#diff-768ab14daacdf04aa2ae6857d478934d

**Comment by brookhong** [comment]
Thanks @jaimehrubiks.

I have implemented this, please have a try.

**Comment by jaimehrubiks** [comment]
@brookhong Thanks so much, it works perfectly, and it selects each character very good and nicely.

Although there are little issues with visual mode that are easier to notice now (they existed probably before this patch) regarding how "w" and "e" . 

However these are **minor issues** as they don't affect too much when yanking for example.

* First is that w does not select the first character, but the space before.
* E does not select last character but space after instead.
* When text changes style (anchors, bold, italics...) the first character of that word is not selected and a kind-of space before is selected.
* Lastly, spaces do not really have a block cursor, they are shorted.
