### ISSUE TITLE
Search not finding all results on page

### ISSUE THREAD

**Issue by GordonGustafson** [brookhong/Surfingkeys#444]
1. navigate to https://github.com/brookhong/Surfingkeys
2. search for the letter 'e' on the page by pressing `/e<Enter>`. Sometimes the correct number of results (about 2391 at the moment) is briefly displayed in the status bar: `Visual - Caret   1 / 2391`, but in about half a second the result numbers disappear from the status bar, leaving `Visual - Caret`.
3. When I press `n` to go to the next result, the status bar shows a much smaller number of results, around 84 for me: `Visual - Caret   2 / 84`. When I press `n` 84 times the search wraps around to the first result of the letter 'e', as if the other 2300 results further down the page didn't exist.

Where did all the other results go? 

When I change these lines in `content_scripts/front.js`:

```
    var _pendingQuery;
    _actions["visualUpdate"] = function(message) {
        if (_pendingQuery) {
            clearTimeout(_pendingQuery);
            _pendingQuery = undefined;
        }
        _pendingQuery = setTimeout(function() {
            Visual.visualUpdateForContentWindow(message.query);
        }, 500);
    };
```

To this:

```
    _actions["visualUpdate"] = function(message) {};
```

I get the desired behavior: after pressing `/e<Enter>`, the status bar displays  `Visual - Caret   1 / 2391`, does *not* stop displaying the `1 / 2391`, and pressing `n` many times lets me iterater through *all* the results.

Why does the code currently work the way it does? Always showing all the results, even if it takes over 500ms, is the behavior I would expect (not getting all the results can be **very** confusing when searching documentation). Is this a bug?

**Comment by brookhong** [comment]
Thanks for reporting this.

It is a bug, fixed in 0.9.2.
