### ISSUE TITLE
Google绘图中禁用扩展后依然有冲突

### ISSUE THREAD

**Issue by cyio** [brookhong/Surfingkeys#447]
https://docs.google.com/drawings

想在 Google 绘图页面禁用 Surfingkeys，按`Alt-s`后，有些样式和快捷键不正常，看起来插入的一些脚本和样式，并没有移除。

![image](https://user-images.githubusercontent.com/3146103/29482302-78936046-84c1-11e7-91c6-eccd0504f2a9.png)
图中正在输入文字，有两个问题， 一是看不到光标，二是系统的中文输入法无法使用
完全禁用 Surfingkeys，再刷新页面，功能就正常了。

我暂时想到的办法是 fork 下来，在 `content_scripts` 中作排除 `"exclude_matches": ["https://docs.google.com/*"],`，不知有没有更通用的解决方法？

另外，请问如何开发调试这个插件，每次改完手动`npm build`？

**Comment by MichaelHu55** [comment]
我也遇到一样的问题。alt+s对docs.google.com也无用。看不到光标，也调不出系统的中文输入法。只能禁用surfingkeys。

**Comment by cyio** [comment]
@MichaelHu55 https://github.com/cyio/Surfingkeys/commit/30b815646bc36e430dee3cd51a9a3752f6713be2

**Comment by MichaelHu55** [comment]
只要在surfingkeys里的设置里加载这个mainfest的js文件就行了吗

**Comment by cyio** [comment]
需要自己 clone => yarn => gulp，会编译到 dist 目录

**Comment by brookhong** [comment]
`Alt-s`禁用之后是可以的。
![image](https://user-images.githubusercontent.com/288207/29720883-d843e1ba-89ed-11e7-99f7-72b9f09e9c48.png)

你可以`yj`复制设置, 粘贴到文本编辑器里看看`blacklist`里有没有

    "blacklist": {
        "https://docs.google.com": 1
    },


这个问题是由一个新功能导致的，下个版本会增加一个设置`settings.enableAutoFocus`默认值为`true`来解决这个问题。

另外如果希望调试, 可以通过load unpacked extension来做, 这样你不需要build。

**Comment by bojanjovicic** [comment]
Hi guys,
I guess I am with you on this topic. My issues is #445 (In Gmail "Label" functionality lost auto focus after Version: 0.9.2).

**Comment by brookhong** [comment]
Thanks, fixed in 0.9.3
