### ISSUE TITLE
settings.newTabPosition is not intuitive and default is not correct

### ISSUE THREAD

**Issue by jaimehrubiks** [brookhong/Surfingkeys#449]
Hi!
I just found this issue https://github.com/brookhong/Surfingkeys/issues/404  
and wanted to clarify some aspects about it

Supposing I have three tabs A/B/C and I open links from A (a1 and a2) and from B (b1,b2) this is what happens right now depending on what is the option I chose:

**default**  
All tabs go to the last position: A/B/C/a1/a2/b1/b2 so this option should instead be called **last**

**right**  
All tabs go right after (right) from current tab: A/a2/a1/B/b2/b1/C  (Same happens with **left** but on the other side)

**first**
All tabs go first position: b2/b1/a2/a1/A/B/C (This is similar to **last** but the opposite)

But There is one option missing, the **default** (the chrome-like behaviour) which would lead to the following tab order: A/a1/a2/B/b1/b2/C If you notice, this is not what current **right** nor **default** are doing.

So, if I am not wrong then:
1. current default should be 'last''
1. default should follow chrome behaviour

Thanks for your patience! :P

**Comment by jaimehrubiks** [comment]
I've been checking the chrome API and it seems that there is no option for achieving what I ask, probably they missed it when they made the API.
So one possible solution is to implement the chrome behaviour manually which should do the following:
(Only for default mode)
1. Each time we move to another Tab, we reset a global counter: **defaultNewTabPosition = 0**
1. Each time we open a link in a new tab [ if (message.tab.tabbed) { ]  we should set the tab index to **newTabPosition = sender.tab.index + 1 _+ counter_** and then increase the counter: **defaultNewTabPosition++**

I can try it but don't know where should I store that 'global' variable. If anyone tell me I try to do it.

**Comment by sgrjyb** [comment]
@jaimehrubiks How to set up ?

**Comment by jaimehrubiks** [comment]
@sgrjyb My pull request has not been accepted. So you would need to:
1. fork this repo 
2. Bring my commits (from my fork) to that repo.
3. Install extension offline
4. Use "chromelike" option in the settings 
(For testing you can just test my repo and mix 1 and 2)
