### ISSUE TITLE
key sequences no longer working if second key in sequence is used by Surfingkeys

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#45]
I reloaded the default settings and I encountered a problem where the 'f' when put at the _end_ of a key combination will do what 'f' by itself only should do. It points out all of the links. The intended key combination does not succeed.

**Comment by brookhong** [comment]
mapkey('of', 'Show me the money', function() {
        Normal.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
    });


In above example, `of` works fine for me. What key combination do you use?

**Comment by jaredbidlow** [comment]
`yf`

**Comment by brookhong** [comment]
Sorry, I changed the default `yf` to `yy` to respect vimium users.
