### ISSUE TITLE
某些Input控件下自动跳出

### ISSUE THREAD

**Issue by CharlesLiuyx** [brookhong/Surfingkeys#450]
额外插件：对页面有影响的只有Google Translate
比如知乎的评论区域
![image](https://user-images.githubusercontent.com/21956621/29502073-32709314-85e2-11e7-8f60-eb8d00a0af37.png)
空格之后，Focus失去
![image](https://user-images.githubusercontent.com/21956621/29502080-426740ec-85e2-11e7-8aed-ee6df802059a.png)
再次按下拨号键盘F无法再次Focus
![image](https://user-images.githubusercontent.com/21956621/29502088-503e3d9c-85e2-11e7-8f74-8567e034e05d.png)

**Comment by brookhong** [comment]
0.9.3已解决。
