### ISSUE TITLE
Is there way to unfocus the chrome navigation bar?

### ISSUE THREAD

**Issue by MaikoID** [brookhong/Surfingkeys#453]
Hi guys, I was wondering if there is any option to unfocus the Chrome url navigation bar. When I click in it I can't unfocus and so this extension cannot be trigged because all my keystroke go to the url text;

**Comment by Campanula** [comment]
You can type <Tab> to move to page

**Comment by MaikoID** [comment]
Thanks, it worked. What you guys think about detecting this behavior and exit the url focus automatically?

=)
