### ISSUE TITLE
"/"搜索卡死

### ISSUE THREAD

**Issue by CCluv** [brookhong/Surfingkeys#455]
"?"打开帮助,想要搜索一下"o"键有什么绑定,发现太多于是想改成\bo\b,就点了一下退格,然后卡住了,所有的页面都卡会出现在正处理请求,只有停一次扩展,再打开才能恢复正常.

**Comment by wanghaocun** [comment]
**我也刚发现这个问题了，  /搜索?帮助页面卡死当前页面后 ， 其他页面也无法使用surfingkeys了，  要么停用扩展，  要么直接重启了chrome才得以解决。  后来又试了好多次，  发现这个问题不是必现问题，  概率性的出现。  不知道到底怎么回事，  是有什么冲突吗？**

**Comment by wanghaocun** [comment]
**又测试了几次，  卡死均出现在?帮助页面/搜索框中`输入后再删除`，  必现页面卡死情况  一般都是在删除至`最后一个字符时`就卡死，  不知道其他人是什么情况？**

**Comment by brookhong** [comment]
谢谢。
下个版本会修复。
