### ISSUE TITLE
Mode mappingsEditor pushed into mode stack again.

### ISSUE THREAD

**Issue by yuanjie007** [brookhong/Surfingkeys#457]
## Error details

Modes in stack: Disabled,mappingsEditor,Normal

SurfingKeys: 0.9.2

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by bojanjovicic** [comment]
Hi @yuanjie007,
Can you explain what "stack" mode means?
And how did you get (easily) all the debugging info you provided?

I have some issue with GMail or other Google for Business Apps in general when using SurfingKeys mapped only for few keys using unmapAllExcept as listed in issue #445, and maybe this is related, or would help me overcome this issue.
