### ISSUE TITLE
; and , (repeat last f, F) not working in visual-range mode

### ISSUE THREAD

**Issue by jaimehrubiks** [brookhong/Surfingkeys#459]
There seems to be a bug in visual range mode where you cant perform the repeat key.

Sequence to replicate

1. Press v (to enter visual caret mode)
1. Press hint
1. Press v (to enter visual range mode)
1. Press f\<char\> (It will find that char)
1. Press ; (It will not perform a second search, you need to press l; (advance one, and then search))

It will, on the other side, work in visual-caret mode, 

AND it will perform the reverse repeat command ,

But, if we use F (reverse search), then , will work, and ; will not.

**Comment by brookhong** [comment]
Thanks, fixed in 0.9.3
