### ISSUE TITLE
swich scroll, inoreader.com issue

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#46]
I am trying to use `cs` on inoreader.com. It does not work usually. After opening chrome and the inoreader site for the first time, the Surfingkeys scrolling box, when I use `cs`, does not show up. To get around this, I must already be in "List View" and then click on the tag/folder I want to view. Then I have to press space and finally I can press `cs` and scroll using keys. This happened after a recent Surfingkeys update

**Comment by brookhong** [comment]
Thanks, fixed in 0.3.7
