### ISSUE TITLE
Unrecognized key event: <Alt->

### ISSUE THREAD

**Issue by nedp** [brookhong/Surfingkeys#461]
## Error details

{
    "metaKey": false,
    "altKey": true,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 83,
    "code": "KeyS",
    "composed": true,
    "key": "Unidentified"
}

SurfingKeys: 0.9.3

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2984.0 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html

## Context

Produced by:

1. Use the `show pressed key feature`,
2. Use a keyboard layout which sends `<Option-s>` combinations as `<Alt-s>`, instead of as a sending the `ß` character.
3. Press `<Option-s>`

A work around is to not use such a layout; however the symbols conflict with other applications which use `<Alt-<anything>>` keybindings, so this isn't good.

**Comment by brookhong** [comment]
Are you using `Alt-s` on Mac?

It works for me and many others.
