### ISSUE TITLE
Conflict with switchyomega proxy

### ISSUE THREAD

**Issue by Tocaz** [brookhong/Surfingkeys#462]
It firstly appears in 27th Aug. My swithchyomega dosen't work as a result of conflict. I know there is a swithsharp module in surfingkeys. Is there any way to disable it ?

**Comment by brookhong** [comment]
use `spi` to look up your proxy mode, it should be `clear`, in which mode, Surfingkeys will not take control of proxy settings, this is the default mode.

If it's not, use `spc` to set it to `clear`.
