### ISSUE TITLE
[Feature Request] More versatile Caret/Visual mode - ala Vimfx

### ISSUE THREAD

**Issue by gnosticscrounger** [brookhong/Surfingkeys#464]
This issue could be considered a continuation of #256 

While the current implementation of caret mode in this addon is already better than 90% of other keyboard  driven extensions, it still lacks a fair bit of versatility that Vimfx has as illustrated in their doc on it: https://github.com/akhodakivskiy/VimFx/blob/b82618ee7c9c7641b34a84ca7dc7b5c5943a5c69/documentation/commands.md#the-v-commands--caret-mode

For my workflow in particular, it would be very nice to be able to go into hint mode, pick a text element to copy and then jump back into normal mode automatically without ever entering caret mode.

Even nicer would be a way to incorperate "rapid fire" style hinting where I can stay in the visual hint mode and copy multiple text elements. I tend to copy paste a lot of text between my browser window and a database search form so this would save me a lot of keystrokes.

Thanks for your excellent extension and reading this.

**Comment by brookhong** [comment]
Thanks for suggestions.

Implemented in 0.9.4.
