### ISSUE TITLE
在 mac 谷歌浏览器下无法使用

### ISSUE THREAD

**Issue by Egi0lg** [brookhong/Surfingkeys#465]
win 下正常,mac 下不起作用了,原先是没事的,最近突然不可以用了

**Comment by Egi0lg** [comment]
Surfingkeys 0.9.3
chrome 版本 60.0.3112.113（正式版本） （64 位）

**Comment by brookhong** [comment]
我的chrome版本和你一样, 没有问题。你是不是disable了, 看看工具栏里Surfingkeys的图标是不是灰掉了？

**Comment by Egi0lg** [comment]
并没有,我甚至重新安装都不行,刚刚我再次确认了下,也并没有 disable 及在 chrome 扩展里禁用

**Comment by wukun0451** [comment]
同样的问题

**Comment by wukun0451** [comment]
同样的问题， mac os:10.11.6     chrome版本: 62.0.3202.75
