### ISSUE TITLE
In Google Applications Auto Focus doesn't work with Version: 0.9.3

### ISSUE THREAD

**Issue by bojanjovicic** [brookhong/Surfingkeys#469]
Hi @brookhong ,
I am not sure, but for me at least it appears that the issue still remains with version 0.9.3. (I reported it in #445 and commented there that it is still not working for me with v0.9.3, but since the issue is closed, I can't re-open it, so I am creating new issues).

In order to help reproduce I created a video (sorry for flv to gif conversion), or opening google.com with SurfingKeys on without autofocus and then with autofocus after disabling SurfingKey. 
In Gmail it doesn't have autofocus still in combination with unmapAll 

Here is the video, but if more data is needed, don't hesitate to ask me (if some debug mode, etc. I know my basic way around JavaScript as language, but don't have experience with debugging addons, etc):
![2017-08-27-07-42-57](https://user-images.githubusercontent.com/4491442/29747448-dfcc79c4-8afb-11e7-8de4-bb7602e23b05.gif)

**Comment by brookhong** [comment]
Please try 0.9.4 to see if this gets fixed.

And the animation you provided is about `settings.stealFocusOnLoad`, which is different with `settings.enableAutoFocus`. Please see more https://github.com/brookhong/Surfingkeys/blob/master/README.md#properties-list

**Comment by bojanjovicic** [comment]
Hi @brookhong,
I tried it. Works good. Thank you very much!
