### ISSUE TITLE
Add a shortcut that shows the pressed keys after it

### ISSUE THREAD

**Issue by nightscape** [brookhong/Surfingkeys#47]
Hi @brookhong,

I am having similar problems as #16, using  a NEO keyboard layout and many shortcuts don't work because in this layout e.g. `CAPS+i` is used for generating a `/`.
I could easily work around that and create custom keyboard bindings if I knew as which key sequence my key presses are registered in Chrome.

Would it be possible to add a shortcut with any ordinary number or letter key (that should hopefully work on all layouts) that calls a function which waits for another key-press and displays what that key-press was?

Thanks a lot!
  Martin

**Comment by brookhong** [comment]
Hi Martin,

I added one shortcut `Ctrl-1` to do that, so you can press `Ctrl-1` first, then press the key you want to display.

Could you please git clone this project, and click the `Load unpacked extension` button to use the development version to verify if it works and is what you want?

**Comment by nightscape** [comment]
It works (almost) perfectly, the only thing that I've noticed is that when you press e.g. `Alt + some_other_key`, it shows just `Alt`.
But for my needs it solved the problem beautifully:
When I press the `CAPS` key, it is recognized as `á`, so I can now e.g. add
```
map('ái', '/');
```
To have the slash working as it should :smile: 

Thanks a lot! :+1:

**Comment by brookhong** [comment]
Great to hear that. :)

The problem about `Alt` was fixed in https://github.com/brookhong/Surfingkeys/commit/8c60b0b2cb3a3f1107ef80b6fccc842ba3eb0caa.

BTW: why `CAPS` plus `i` is `/` in your keyboard layout? Are `i` and `/` on a same key?

**Comment by nightscape** [comment]
I just checked and can confirm that e.g. pressing `Alt` + `a` now correctly displays as `<Alt-a>`.

The Neo layout has multiple "levels", so if you press e.g. `i` it will do different things depending on what additional modifier keys you press:
* `CAPS + i` => `/`
* `Alt Gr + i` => `←` (Cursor left)
* `Alt Gr + CAPS + i` => `∫`

My feature request is hereby fully fulfilled :smile:

Thanks a lot!
