### ISSUE TITLE
在chrome 61.0.3163.79 (64bit) 不能用了

### ISSUE THREAD

**Issue by yangbull** [brookhong/Surfingkeys#472]
至少上下翻页功能不能用了。问号还好使，其它没测

**Comment by jajpater** [comment]
Same here. Can not use j and k to navigate the page. Very very annoying. 

61.0.3163.79
Operating System: Linux (x86_64) | Browser Engine: WebKit (537.36)

**Comment by programscape** [comment]
Yes, I also find thees Bug, I use Linux / Chrome 61 ,other keys is normal.

**Comment by gzmask** [comment]
Version 61.0.3163.79 (Official Build) (64-bit) 
macOS: 10.12	
can't scroll j/k and u/d.

**Comment by MaxTan** [comment]
win10也是，更新后ed和hjkl不能使用，其他功能正常

version: 版本 61.0.3163.79（正式版本） （64 位）

**Comment by brookhong** [comment]
谢谢！

0.9.6已修复。
