### ISSUE TITLE
0.9.6滚动的操作全部失效

### ISSUE THREAD

**Issue by Leoongithub** [brookhong/Surfingkeys#473]
d,e,h,j,k,l均无法使用

chrome  60.0.3112.113

**Comment by Leoongithub** [comment]
升级到chrome61之后好像问题解决了，是不兼容旧版吗

**Comment by dslztx** [comment]
我也遇到了，用着用着就失灵了，可以取消自动更新插件吗？以后经常会出现这种情况？

**Comment by dulek** [comment]
Well, I can confirm that stuff doesn't work for me either on 60.0.3112.113. No reaction for scrolling keys (d, e, j, k) or f.

**Comment by brookhong** [comment]
Thank you all for your prompt reports.

Fixed in 0.9.7.
