### ISSUE TITLE
Cannot enter text in the Lumio extension

### ISSUE THREAD

**Issue by cwagner22** [brookhong/Surfingkeys#476]
I can't enter any text when I try to write a note in the [Lumio](https://chrome.google.com/webstore/detail/hgomdfbclcjpeecbjckbbojbmmjegpek) extension. When I focus the note field Surfingkeys doesn't switch to insert mode (even if I press i) so entering text triggers the Surfingkeys shortcuts instead of letting me write text. It's working with Vimium.

![image](https://user-images.githubusercontent.com/5314435/30247180-486d6dde-9638-11e7-9e36-44357e126d01.png)

**Comment by brookhong** [comment]
Thanks.

Fixed in 0.9.8
