### ISSUE TITLE
建议适配 简悦 - Simpread

### ISSUE THREAD

**Issue by Kenshin** [brookhong/Surfingkeys#478]
Surfingkeys 的开发者，你好：
我叫 Kenshin，是 [简悦](https://github.com/Kenshin/simpread) 作者。由于我的孤陋寡闻，要不是之前有个简悦的用户，我还不知道 Surfingkeys 这款神器的存在。😁

由于找不到你的联络方式，所以在这里发个 issues。

**联系你的原因：**
Surfingkeys 与 简悦 在操作上绝大多数功能都可以使用，但有些少许冲突，当然这是因为 [简悦的一些原因造成的](https://github.com/Kenshin/simpread/wiki/FAQ#%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%E5%BF%AB%E6%8D%B7%E9%94%AE%E7%9A%84%E5%86%B2%E7%AA%81)

***

**无法使用 简悦 的功能：（快捷键）**

> 1. 简悦的快捷键，包括了： `聚焦模式` 与 `阅读模式`

**解决办法：**
> 最好能排除掉简悦已经 `设置过的快捷键`，即可解决。

**无法使用 Surfingkeys 的功能：（鼠标点击）**

> 2. 模拟 `鼠标点击` 类的操作。

**原因：**
- `阅读模式` 为了防止 CSS 干扰，所以并没有在 `<body>` 而是在 `<html>` 节点下，所以基于判断 `<body>` 节点下的扩展在阅读模式下都不好用。

- `聚焦模式` 虽然节点在  `<body>` 下，但不清楚为什么不好使...

**解决办法：**
> 如果能监听 `简悦的节点` 而非 `<body>` 即可解决。

***

看到后，希望可以得到进一步的联络。（ 联络方式在 [在这里找到](https://github.com/Kenshin/simpread/wiki#%E8%81%94%E7%BB%9C%E6%96%B9%E5%BC%8F) 😀 ）

**Comment by Kenshin** [comment]
感谢修改，用以兼容 简悦，请问新版什么时候发布？

还有个疑问： Surfingkeys 如何能排除掉某些快捷键操作呢？（ 它会托管全部的键盘操作，简悦支持的某些快捷键上因此失效）

**Comment by brookhong** [comment]
不客气，需要过两天。

Surfingkeys的按键都可以在设置里通过`unmap`函数取消的，默认的按键按问号就都能看到。

https://github.com/brookhong/Surfingkeys#remove-a-keystroke-mapping

**Comment by lyserenity** [comment]
不好意思，我在 surfingkeys 的设定里 `unmap('ll');` 结果无法

> 不客气，需要过两天。
> 
> Surfingkeys的按键都可以在设置里通过`unmap`函数取消的，默认的按键按问号就都能看到。
> 
> https://github.com/brookhong/Surfingkeys#remove-a-keystroke-mapping

我在 surfingkeys 的设定里 `unmap('ll');`，但没有效果（无法进入简阅的阅读模式）；禁用 surfingkeys 就可以了，请问有没有其他办法或设定是需要注意的？谢谢。
