### ISSUE TITLE
Not detecting scrollable elements

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#48]
I cannot scroll on a page using the provided default shortcuts until after I manually scroll using either the mouse or the scrollbar.

**Comment by brookhong** [comment]
Could you show me the page URL so that I can check it?

**Comment by jaredbidlow** [comment]
Not specific to URLS. It is all pages

**Comment by jaredbidlow** [comment]
I can't reproduce this on my home computer so I closed it. But on my work computer I still cannot scroll after initially opening a page. SurfingKeys will allow me to scroll single pages after using the scrollbar or pressing space, even after refreshing the page. A page opened from clicking on a link on a page that is not scrollable will be scrollable (eg. if i follow a link from a Google search, it is scrollable)

**Comment by brookhong** [comment]
Do other keystrokes, like `u`(to show usage) or `yt` to duplicate a tab, work in that case?

**Comment by jaredbidlow** [comment]
yea it looks like an extension is messing with it even though I though I ruled that out by disabling half/half the other day

**Comment by jaredbidlow** [comment]
This issue still persists: If I go to a url using Chrom's url bar, I cannot scroll until I manually scroll the page.
