### ISSUE TITLE
特意定义了功能键<F9>，但是在输入状态下还是不能用

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#480]
特意定义了F9功能键来避免输入状态下的问题，结果还是无效，不知道能否修正？

**Comment by brookhong** [comment]
把你的设置贴出来看看呢

**Comment by hyaray** [comment]
我在脚本里加了这么一段，每次离开输入框就可以用，在输入状态下就无效。
顺便请教下，最详细的中文手册在哪里？细节问题想学下，谢谢！！
mapkey('<F9>', 'Enter', function(){
    if (url.indexOf('cnblogs.com') != -1)
        document.getElementById('Editor_Edit_lkbPost').click();
});

**Comment by brookhong** [comment]
你的脚本里有两个错误：

1、输入状态的按键映射用`imapkey`

2、你用了一个没定义的变量`url`。

正确的应该是下面这样的，

    imapkey("<F9>", 'Enter', function(){
        console.log(document.location.href);
        if (document.location.href.indexOf('cnblogs.com') != -1)
            document.getElementById('Editor_Edit_lkbPost').click();
    });
