### ISSUE TITLE
Open selected link in non-active tab is not work on non-complete URL.

### ISSUE THREAD

**Issue by skitimoon** [brookhong/Surfingkeys#481]
I defined funtion to open selected link in background tab like this:
```
function openLinkInBackgroundTab(url) {
    RUNTIME("openLink", {
        tab: {
            tabbed: true,
            active: false
        },
        url: url
    });
}

mapkey('ct', 'Open selected link or link from clipboard in background', function() {
    if (window.getSelection().toString()) {
        openLinkInBackgroundTab(window.getSelection().toString());
    } else {
        Front.getContentFromClipboard(function(response) {
            openLinkInBackgroundTab(response.data);
        });
    }
});
```
When I use it to "google.com", it is not work, instead it open the URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/google.com in the background. But when I use it on "https://www.google.com" it work as expected.
PS: the `cc` work on both link.

Is there any way to let the browser decide whether to go to selected text (`cc`) or search it (`sg`) i.e. the same as we copy and paste the text to the omnibar.

**Comment by brookhong** [comment]
Thanks.

Fixed in 0.9.8
