### ISSUE TITLE
Bug: t -> http://... or *.com defaults to google search

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#486]
![capture](https://user-images.githubusercontent.com/189379/30485879-5e17c598-99f4-11e7-92f0-7dddae911341.PNG)

**Comment by brookhong** [comment]
You need press `tab` to focus the first item, then `enter`.

If need the the first item auto focused, please add below setting:

    settings.focusFirstCandidate = true;

**Comment by simonwjackson** [comment]
This is great. thanks!

**Comment by simonwjackson** [comment]
Actually, if I have never typed in the address before.. it defaults to google again

**Comment by brookhong** [comment]
Yes, this pattern of URL is missed.

Thanks for reporting.

**Comment by brookhong** [comment]
Fixed in 0.9.9.
