### ISSUE TITLE
Bug: Can't unmap <Ctrl-j>

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#487]
The following does not seem to work

```js
unmap('<Ctrl-j>');
```

I would like to map this to `navigate down in menu`

**Comment by brookhong** [comment]
It works for me.

**Comment by simonwjackson** [comment]
@brookhong For you, when you use `unmap('<Ctrl-j>')` it no longer binds to toggling the location of the popup menu?
