### ISSUE TITLE
如何取消所有的默认设置,omnibar操控除了tab外如何绑定别的按键.

### ISSUE THREAD

**Issue by nopcall** [brookhong/Surfingkeys#49]
我重新设置了我的按键 但是好像默认的按键配置一直被加载 
还有omnibar的控制好像只有输入字母来匹配选项或者使用Tab来移动.我想改成Ctrl+n/p 怎么设置.

**Comment by brookhong** [comment]
取消某个按键

    unmap('<Ctrl-i>');


Omnibar里面还不支持按键绑定，目前只能用`tab`/`shift-tab`键

**Comment by nopcall** [comment]
我确实注意到了这个方法了 
但是默认的配置 有点多啊   而且个人来说很多功能我确实用不上.
不应该是用户定义了自己的配置之后 默认的配置就不应该加载了么?

**Comment by brookhong** [comment]
不是的，用户自定义的设置是叠加在默认设置上面的。

你用不上的可以不理会就好，如果担心误按某个按键，只能用unmap。
