### ISSUE TITLE
我想在很多网站自定义按键，可否推荐个设计思路？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#490]
是通过domain，每个网站单独设计热键，
还是根据热键，根据网址执行相应的功能呢？
就怕写多了太乱了，有没有导入文件的功能呢？这样可能更规范。
这方面教程里都没涉及到，不知道能去哪里了解，希望能给个建议，谢谢！！！

**Comment by hyaray** [comment]
补充下：函数内能否知道刚刚按了哪个键？
比如a键和b键功能基本一样，我就可以写一个函数，在内部根据按键执行不同的功能

**Comment by brookhong** [comment]
用document.origin区分当前网站，给同一个按键针对不同网站设置不同的操纵，比如

    if (document.origin === "https://github.com") {
        mapkey(';e', 'toggle experiment', function() {
            $('#toc').hide();
        });
    } else if (document.origin === "https://www.baidu.com") {
        mapkey(';e', 'toggle experiment', function() {
            $('#top').show();
        });
    }

看readme.md，或者在issue里搜索，大部分问题之前都有人问过的。

**Comment by sgrjyb** [comment]
@hyaray  能不能分享设置 ?

**Comment by hyaray** [comment]
@sgrjyb 我只是在想框架，因为以后一直用，我会慢慢地添加自定义的键，所以才有此提问。
Surfingkeys的配置文件内容真的很少。我把我定义热键的方式分享下吧，很可能不成熟的哈~

`
var url = window.location.href.match(/^(https?:\/\/)?(.+?)(\/)?$/)[2]; //去除http://前缀和末尾的/

//针对新浪网修正[[和]]键的功能（因为没技术做通用的[[和]]，所以此法过渡，这两个函数应该可以合并）
mapkey('[[', '上一页', function(){
    if (url.indexOf('blog.sina.com.cn/s') === 0)
    {
        var page = url.match(/(_\w+)\.html/)[1];
        window.location.href = $('#new_nextprev'+page).find('a').eq(0).attr('href');
    }
}, {domain:/blog\.sina\.com\.cn/});

mapkey(']]', '下一页', function(){
    if (url.indexOf('blog.sina.com.cn/s') === 0)
    {
        var page = url.match(/(_\w+)\.html/)[1];
        window.location.href = $('#new_nextprev'+page).find('a').eq(1).attr('href');
    }
}, {domain:/blog\.sina\.com\.cn/});

//定义一个万能键（有些网址我们常用的可能就1个功能，所以针对各网址设置了万能键）
mapkey('a', '万能键', function(){
   if (url.indexOf('dicts.cn') != -1) //一键查询剪切板
    {
        Front.getContentFromClipboard(function(s)
        {
            $('#word').val(s.data);
            $('#cigencizui-search').click();
        });
    }
    else if (url.indexOf('study.163.com') === 0) //网易云课堂
        document.getElementById('j-next').click();
    else if (url.indexOf('vip.qq.com') === 0) //QQ会员
        document.getElementsByClassName('ui-signin')[0].click(); //点击签到
    else if (url.indexOf('www.imooc.com') === 0) //慕课网_下一节
        document.getElementsByClassName('J-next-btn next-auto btn btn-green')[0].click();
});

//跳转到输入框
mapkey('i', 'Go to edit box', 'Hints.create("input[type=text]:visible, textarea:visible", Hints.dispatchMouseClick)');
mapkey('cs', '打开插件商店', 'window.open("https://chrome.google.com/webstore/category/extensions?hl=zh-CN")');
mapkey('co', '打开设置', 'tabOpenLink("chrome://settings")');

`

**Comment by sgrjyb** [comment]
@hyaray 谢谢 , 最好在你的主页创建一个项目 ,以便日后更新

**Comment by sgrjyb** [comment]
@hyaray  var url = window.location.href.match(/^(https?://)?(.+?)(/)?$/)[2];  不能添加到 Surfingkeys

**Comment by hyaray** [comment]
@sgrjyb 不客气，我还不太会github，数据都是用U盘同步的。
创建个全局变量似乎没问题啊，我一直这样用的~

**Comment by sgrjyb** [comment]
var url = window.location.href.match(/^(https?://)?(.+?)(/)?$/)[2];  全部代码就这谢吗 ?创建全局变量不会啊 !

**Comment by hyaray** [comment]
对啊，你就把这个放Surfingkeys第一行，然后在函数里就可以用啊。

**Comment by sgrjyb** [comment]
@hyaray 感叹号 ,无法保存 !
![sv](https://user-images.githubusercontent.com/28247198/31339208-a6efa4ea-ad34-11e7-8edc-f401c7201ff2.PNG)

**Comment by hyaray** [comment]
不知道诶，我反正这样用着没问题啊
