### ISSUE TITLE
怎么指定快捷键打开 url （和小书签）？

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#493]

**Comment by mslxl** [comment]
这个配置其实就是一个 JavaScript  , 直接
```javascript
mapkey('n','Test',()=>{
    window.open("https://www.google.com"); 
    //or window.location.href="https://www.google.com"; 
})
```

**Comment by sgrjyb** [comment]
@mslxl 小书签呢?

**Comment by mslxl** [comment]
我不是很理解什么是小书签 , 能描述一下吗

**Comment by sgrjyb** [comment]
@mslxl javascript:x=''+window.getSelection();window.open('magnet:?xt=urn:btih:'+x)

**Comment by mslxl** [comment]
很抱歉但是我还是理解不了.

你指的是打开一个网页 , 网址是当前选中内容加 `magnet:?xt=urn:btih: ` 前缀吗?

**Comment by sgrjyb** [comment]
@mslxl 恩  
Bookmarklet ，大陆这边一般都称呼为小书签，台湾那边称呼为书签列小程式or 书签小程式。它是一段JavaScript 脚本

**Comment by mslxl** [comment]
```javascript
mapkey('m','Bookmarklet',()=>{
    window.open("magnet:?xt=urn:btih:" + window.getSelection().toString()); 
})
```

**Comment by sgrjyb** [comment]
感谢

**Comment by sgrjyb** [comment]
@mslxl javascript:(function(){document.location.href=document.location.href.replace('http:','https:')})();
像这样的不知道怎么弄? 有没有什么办法直接复制上面的代码就可以了 ?

还有这个 javascript:(function(){var u = "https://script.google.com/macros/s/AKfycbyUWJda1KGh6v-_p35CW5qGeT6IWSPUiK8oFzteuBnm6fNh88c/exec?mid=";var l = location;if(l.host!="space.bilibili.com"){alert('%E8%AF%B7%E5%9C%A8up%E4%B8%BB%E7%9A%84bilibili%E7%A9%BA%E9%97%B4%E4%BD%BF%E7%94%A8%E3%80%82');return}if ((mid = /^(http|https):\/\/space\.bilibili\.com\/(\d+)/.exec(window.location.href)) !== null){u += mid[2];window.open(u);}})()

**Comment by mslxl** [comment]
直接去掉 `javascript:(` 和 `)();` , 然后传给 `mapkey` 的第三个参数 ,变成

```javascript
mapkey('your_key','description',function(){
    document.location.href=document.location.href.replace('http:','https:')
})
```

第二个同理,变成

```javascript
mapkey('your_key','description',function() {
    var u = "https://script.google.com/macros/s/AKfycbyUWJda1KGh6v-_p35CW5qGeT6IWSPUiK8oFzteuBnm6fNh88c/exec?mid=";
    var l = location;
    if (l.host != "space.bilibili.com") {
        alert('%E8%AF%B7%E5%9C%A8up%E4%B8%BB%E7%9A%84bilibili%E7%A9%BA%E9%97%B4%E4%BD%BF%E7%94%A8%E3%80%82');
        return
    }
    if ((mid = /^(http|https):/ / space.bilibili.com / (\d + ) / .exec(window.location.href)) !== null) {
        u += mid[2];
        window.open(u);
    }
})
```
没有通用的办法复制粘贴  , 不过都是把函数拿出来传给 `mapkey`

记得把 `your_key ` 和 `description` 换成自己的快捷键和描述

**Comment by mslxl** [comment]
不过我感觉第二段代码本身有问题...

**Comment by sgrjyb** [comment]
@mslxl 第二段保存不了 ? 我在书签栏用没问题 !

**Comment by mslxl** [comment]
那就是我错了...
正则原来是这么用的吗...

**Comment by sgrjyb** [comment]
怎么修改?

**Comment by mslxl** [comment]
既然你用着没错那就不改了...
能用就行

**Comment by sgrjyb** [comment]
添加到Surfingkeys 无法保存 !

**Comment by mslxl** [comment]
果然...
我感觉这段代码是想用正则来获取 `https://space.bilibili.com/`后面的那一串数字 , 但是我也不会正则啊...
稍等,我改成普通的截取字符串...

**Comment by mslxl** [comment]
```javascript
mapkey('your_key', 'description', function () {
    var u = "https://script.google.com/macros/s/AKfycbyUWJda1KGh6v-_p35CW5qGeT6IWSPUiK8oFzteuBnm6fNh88c/exec?mid=";
    var l = location;
    if (l.host != "space.bilibili.com") {
        alert('%E8%AF%B7%E5%9C%A8up%E4%B8%BB%E7%9A%84bilibili%E7%A9%BA%E9%97%B4%E4%BD%BF%E7%94%A8%E3%80%82');
        return
    }
    var o = "bili.com/"
    var url = window.location.href
    var temp = url.substring(url.indexOf(o) + o.length)
    u += temp.substring(0,temp.length-1);
    window.open(u);
})
```

这样就没问题了

**Comment by sgrjyb** [comment]
你这个人不错 , 哈哈

**Comment by mslxl** [comment]
Gradle 还在 Maven 仓库里下载东西
没钱买 SS , 只能慢慢等 , 现在闲的没事...

**Comment by sgrjyb** [comment]
比那些就知道忙的人强多了

多了第二段代码 invalid uid , 书签栏用正常
网址: https://space.bilibili.com/7458285?from=search&seid=14619020589768705603#!/

**Comment by mslxl** [comment]
改成
```javascript
mapkey('your_key', 'description', function () {
    var u = "https://script.google.com/macros/s/AKfycbyUWJda1KGh6v-_p35CW5qGeT6IWSPUiK8oFzteuBnm6fNh88c/exec?mid=";
    var l = location;
    if (l.host != "space.bilibili.com") {
        alert('%E8%AF%B7%E5%9C%A8up%E4%B8%BB%E7%9A%84bilibili%E7%A9%BA%E9%97%B4%E4%BD%BF%E7%94%A8%E3%80%82');
        return
    }
    
    var o = "bili.com/"
    var url = window.location.href
    var temp = url.substring(url.indexOf(o) + o.length)
    u += temp.substring(0, (temp.indexOf('?') === -1) ? temp.length - 1 : temp.indexOf('?'));
    window.open(u);
    
})
```

加我 QQ 1302485739 说吧
或者把你的邮箱留下来 .
把这条 Issues 还有 [另外一条](https://github.com/brookhong/Surfingkeys/issues/510) 关了吧

**Comment by sgrjyb** [comment]
以后我能你发邮件请教吗 ? 这是你email : doyo101@outlook.com ?

**Comment by mslxl** [comment]
可以 , 这是我的邮箱 , 但是最好还是给 1302485739@qq.com 发吧 ,outlook 我不常用 .
还有就是我是个学生 , 开学之后只有晚上有时间 , 可能回复会很慢

**Comment by brookhong** [comment]
除了使用`mapkey`，我更推荐你们用类[vim标示](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E7%B1%BBvim%E6%A0%87%E7%A4%BA)。

它的好处不光在于创建方便，而且也支持[Bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet)。

**Comment by sgrjyb** [comment]
@brookhong 从收藏夹里按住Ctrl，加上标示符来创建。不起作用 ?

按下b打开收藏夹。
随便输点啥，定位到你要标示的网址。
按住Ctrl，加上你选中的标示符，比如f。
之后，按'F就可以直接打开该网址来。
