### ISSUE TITLE
Finding hints by entering text?

### ISSUE THREAD

**Issue by fd0** [brookhong/Surfingkeys#495]
Hi,

first, thank you very much for this extension!

Is there a way to activate hints/links based on the text they display? I've used this feature extensively with vimperator, pentadactyl and cvim, but it does not seem to be available in Surfingkeys. Users can enter a text, which is matched against the texts for all links and buttons so that the list of possible hints is reduced. The hints in this mode are labelled with numbers instead of characters.

Is this mode implemented in Surfingkeys? How do I activate it? If not, would you be willing to add it?

Thanks!

**Comment by jaredbidlow** [comment]
This is a useful suggestion. I have been looking for a way to filter hints on inoreader.com and other sites with a high density of links

**Comment by leacoleaco** [comment]
This feature is very useful for English website, but for the chinese,it is not good...

**Comment by fd0** [comment]
I understand, my use case does not include visiting website in Chinese :)

**Comment by fd0** [comment]
Wohoo, thanks!
