### ISSUE TITLE
Scrolling is broken

### ISSUE THREAD

**Issue by rleppink** [brookhong/Surfingkeys#496]
Unable to scroll using either j, k or any other bound keys. Did not update Google Chrome. I do think SurfingKeys got updated. Did not change any settings.

In console, this error shows up: 
`Uncaught TypeError: Cannot read property 'scrollHeight' of null`

**Comment by Harjot1Singh** [comment]
I'm also getting the same, it was working before, and I haven't even closed Chrome since I installed it. Reloading or opening next pages does not work to resolve the issue for me either.

**Comment by haoxuexiaoyao** [comment]
I'm also.

**Comment by seasonxuan** [comment]
so am I .

**Comment by brookhong** [comment]
Fixed in 0.9.10.
