### ISSUE TITLE
快捷键e和d失效

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#497]
今天打开页面发现，浏览任何网页使用快捷键e和d都失效了，唯有在Surfingkeys settings页面有效

**Comment by haoxuexiaoyao** [comment]
自动昨天自动更新了Surfingkeys之后，最新版的e 、 d 、h 、 j、k、l以及gg等快捷键均无法使用，而且使用ob打开百度出现乱码，如图
<img width="1454" alt="wx20170925-094044 2x" src="https://user-images.githubusercontent.com/4811366/30789119-de0f2b68-a1d5-11e7-9fb9-4a577719ebe0.png">

**Comment by brookhong** [comment]
能提供下chrome和OS的版本吗？

**Comment by SexyC** [comment]
Hi,
我的surfingkeys也出现了同样的问题。
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
OS: macOS 10.12.6

Thanks.
BR

**Comment by haoxuexiaoyao** [comment]
版本 60.0.3112.113（正式版本） （64 位）
mac os版本 10.12.6 (16G29)

**Comment by haoxuexiaoyao** [comment]
@brookhong 和移动相关的快捷键都失效，按下快捷键？这个帮助页面 可以使用移动键（e、d、h、j、k、l）其他页面均无效，另外乱码问题好像浏览器重启后 过一会就自动好了，之前从未遇到过

**Comment by brookhong** [comment]
滚动的问题0.9.10应该没有了吧？你试试

乱码我无法重现，下次你再发现时再报吧。

**Comment by haoxuexiaoyao** [comment]
@brookhong 0.9.10解决了，移动没有问题了 谢谢
