### ISSUE TITLE
Unstable/slow scrolling

### ISSUE THREAD

**Issue by shiro** [brookhong/Surfingkeys#499]
Scrolling is often slow *(as in unstable)* in general, sometimes the scrollbar jumps a little, especially on larger sites and when using the go to top/bottom command.
Tested on a mid-range laptop, although the scrolling in Vimium worked just fine on the same sites.

Also randomly scrolls up or down at a random speed if scrolled up and down rapidly (and sometimes just stops scrolling at all).

**Comment by brookhong** [comment]
Should be improved since 0.9.12, please give back your feedback.
