### ISSUE TITLE
Can't disable Surfing Keys for specific domains or on demand for specific sites

### ISSUE THREAD

**Issue by travisbhartwell** [brookhong/Surfingkeys#50]
First of all, loving SurfingKeys!

I'm running 0.3.8, the latest, with Chromium 49.0.2623.75 (64-bit) on Linux and also Google Chrome 49.0.2623.87 on OS X.

The documentation states that I should be able to disable SurfingKeys on demand for a specific page but hitting 'alt-s'.  This does not seem to work.  I even tried rebinding this by setting `Events.hotKey` in my settings but nothing seems to take effect.

I see on #32 there used to be a functionality to disable SurfingKeys for a specific domain entirely.  For sites like Gmail this would be ideal.  This is one feature from cVim that was very useful.

Similarly, in cVim, I could hit "i" to go to insert mode and it would send the keys through to the website.  This was useful say in Twitter so I could use the Twitter bindings for a time, but then could go back out.

**Comment by brookhong** [comment]
Thanks for reporting this issue.

You could add below line into your own settings to work arount it before next release published.

    Events.hotKey="<Alt-s>";

**Comment by travisbhartwell** [comment]
Thanks for the quick response!  The work-around works for now.  I couldn't get it to work previously because I hadn't capitalized "Alt".
