### ISSUE TITLE
窗口滚动

### ISSUE THREAD

**Issue by libingyu** [brookhong/Surfingkeys#504]
在youtube上中或者斗鱼,页面有聊天窗口时候使用按键只能滚动聊天部分, 需要怎么设置吗???

**Comment by brookhong** [comment]
一个页面上由多个部分可以滚动时，按`cs`切换滚动目标。

**Comment by wuseal** [comment]
有个问题,窗口滚动cs键,按了后,并没有在当前所示内容范围内切换滚动目标,有的时候会切到最上面,导致当前浏览的位置瞬间跳到上面去

请问有没有方法可以指定滚动窗口的?
