### ISSUE TITLE
修改配置导致主题莫名改变

### ISSUE THREAD

**Issue by libingyu** [brookhong/Surfingkeys#506]
我增加知乎的搜索之后,主题变成黑色了,之前的代码没有动,恢复默认好像也不太好使,只能删除全部保存会恢复初始的主题.

**Comment by JimmyLv** [comment]
any way switch back to white theme?

**Comment by brookhong** [comment]
`se`打开设置，删除下面这样一段

    settings.theme = `
    ...
    }`;
