### ISSUE TITLE
Map to All Modes

### ISSUE THREAD

**Issue by cbejensen** [brookhong/Surfingkeys#508]
Is there a way to create a mapping that works in all modes without writing out the same multiple times, once with `mapkey`, once with `imapkey`, once with `vmapkey`, etc? For example, if I fill out a particular form a lot, and I want to map `<Ctrl-s>` to save the form, but I want it to work whether I am in an input or not, what's the cleanest way to write that? Currently, I have this:

    const clickBtn = selector => {
      const btn = document.querySelector(selector);
      if (btn) btn.click();
    };
    mapkey(
      '<Ctrl-s>',
      'Save on Sugar',
      () => clickBtn('.action_buttons input[title="Save"]'),
      { domain: /clienthistory\.com/i }
    );
    imapkey(
      // make the above work on inputs
      '<Ctrl-s>',
      'Save on Sugar',
      () => clickBtn('.action_buttons input[title="Save"]'),
      { domain: /clienthistory\.com/i }
    );

**Comment by walramb** [comment]
For this use case I would write a little wrapper function like this if no built-in equivalent exists
```javascript
const allmapkey = (...args) => {
  mapkey(...args);
  imapkey(...args);
  vmapkey(...args);
};

allmapkey(
  '<Ctrl-s>',
  'Save on Sugar',
  () => clickBtn('.action_buttons input[title="Save"]'),
  { domain: /clienthistory\.com/i }
);
```
