### ISSUE TITLE
Can't execute code on page

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#509]
I'm trying to auto edit some text on the page.
I've tried several methods, but nothing seems to work on page load.
The only time i can get the code to execute is when i click the save button in SE settings.
But when i reload the page it doesn't work.

**Immediate**
-------------------------
```js
  if (document.origin === 'https://codetree.com') {
        document.querySelector('.total-size').innerHTML = 'some_new_text'
  }
```
**After DOM loads**
-------------------------
```js
  if (document.origin === 'https://codetree.com') {
      document.addEventListener('DOMContentLoaded', () => {
        document.querySelector('.total-size').innerHTML = 'some_new_text'
      })
  }
```
**10 second timeout**
-------------------------
```js
  if (document.origin === 'https://codetree.com') {
      setTimeout(() => {
        document.querySelector('.total-size').innerHTML = 'some_new_text'
      }, 10000)
  }
```

Am I missing something here?

**Comment by brookhong** [comment]
The way of `DOMContentLoaded` works for me.

**Comment by simonwjackson** [comment]
This may have been a caching issue for me. Closing the issue.
