### ISSUE TITLE
SurfingKeys doesn't work for files opened locally

### ISSUE THREAD

**Issue by travisbhartwell** [brookhong/Surfingkeys#51]
I have HTML files that I edit locally and then want to load in my browser to view.

Unfortunately, SurfingKeys does not seem to be active for these pages.  Is it possible to enable it for these or is this a limitation of Chrome extensions?

If not, I suppose the workaround is to just run a local webserver and load from http://localhost/.

**Comment by brookhong** [comment]
There is a checkbox -- `Allow access to file URLs` for each extension at page chrome://extensions/. If it is checked then the extension will have access to file:///.

**Comment by travisbhartwell** [comment]
Awesome, thank you!
