### ISSUE TITLE
Does'nt work on new tab page

### ISSUE THREAD

**Issue by bytex0a** [brookhong/Surfingkeys#511]
Even if focus is changed on any element on a new tab page, hotkeys do not work although  the Surfingkeys icon is not greyed out. Is there a way to use it on a new tab?

**Comment by jaimehrubiks** [comment]
Same thing here

**Comment by Harjot1Singh** [comment]
I'm not sure this is possible in Google Chrome, the new tab page and any `chrome://` URLs

**Comment by simonwjackson** [comment]
My workaround was to set the new tab page to a blank webpage: https://a.pomf.space/dxnljhjqpygw.html

**Comment by brookhong** [comment]
Please see https://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages.html
