### ISSUE TITLE
Can not selection text on linux chrome

### ISSUE THREAD

**Issue by mslxl** [brookhong/Surfingkeys#513]
I am sorry for my poor English.

When I select text on some website(such google translate) and right-click, the text will cancel selection, and sometimes this extension makes some text can not be select.

**Comment by brookhong** [comment]
Try add below setting

    settings.cursorAtEndOfInput = false;

**Comment by mslxl** [comment]
thanks

**Comment by ligyxy** [comment]
@brookhong I feel like it behaves more like a bug than a feature, since the documents of cursorAtEndOfInput doesn't mention this right-click behavior at all. If it is intentional, could you please describe more details in the documents?
