### ISSUE TITLE
Request: Search improvement

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#514]
When 'select first option' is enabled and you preform a search, the first result should be exactly what you type.

The first suggested search result is typically not what i am requesting.

Also, it would be nice to have the option to disable suggested results altogether.

---

![capture](https://user-images.githubusercontent.com/189379/31279856-26c8018e-aa70-11e7-8858-f9c0a90da649.PNG)

**Comment by sgrjyb** [comment]
I also want to know how to disable the suggested results, Or select the first option when the search is disabled.
