### ISSUE TITLE
Files with extension 'html'

### ISSUE THREAD

**Issue by componhead** [brookhong/Surfingkeys#515]
Hi. Seems that the plugin doesn't works well with files ending in `html`.

**Comment by brookhong** [comment]
Please provide the problematic URL.

It should work, for example, it works fine on http://docs.groovy-lang.org/latest/html/documentation/grape.html

**Comment by componhead** [comment]
Sorry, you are right.
I can't use, for example, `f` key on my bookmark file `file:///Users/MyUser/Desktop/bookmarks.html`

**Comment by brookhong** [comment]
For the `file:///` scheme, please go to `chrome://extensions/`, and check `Allow access to file URLs`.

**Comment by componhead** [comment]
Oh, gosh, I totally missed it.

thank you.
