### ISSUE TITLE
[豆瓣电影](https://movie.douban.com/tv)  按f 后出现BE 怎么直接把BE 映射到 d 键 ?

### ISSUE THREAD

**Issue by sgrjyb** [brookhong/Surfingkeys#517]
[豆瓣电影](https://movie.douban.com/tv)  按f 后出现BE 怎么直接把BE 映射到 d 键 ?

**Comment by leacoleaco** [comment]
@sgrjyb 这里的“BE” 不可能映射吧。。。能映射的都是那些具有固定功能的快捷键，这种拨号分配的快捷键都是动态生成的哎

**Comment by sgrjyb** [comment]
@leacoleaco 怎么映射具有固定功能的快捷键 ?(详细例子谢谢)  豆瓣电影怎么加载更多 ?

![default](https://user-images.githubusercontent.com/28247198/31323105-00c446a2-acd5-11e7-91b6-7ea612e33173.PNG)

**Comment by leacoleaco** [comment]
@sgrjyb 这个我有个简单办法，吧”加载更多“ 当作”下一页“处理，可以在配置中写入：
`settings.nextLinkRegex = /((加载更多|下一页|>>|next)+)/i;`
然后在需要加载更多的时候，点击   `]]`  就可以了。

![image](https://user-images.githubusercontent.com/17734288/31325037-5160174c-aceb-11e7-85d1-2f71c874a74f.png)

如果你非要把他当作一个单独的功能，比映射到 `AA`  这个按键，并且不影响之前‘下一页’的快捷键设置，不妨尝试在配置中加入下面的代码即可：

`
mapkey('am', '#1点击加载更多按钮', function() {
    var prevLinks = $('a').regex(/(加载更多)/i);
    if (prevLinks.length) {
        clickOn(prevLinks);
    } else {
        walkPageUrl(-1);
    }
});
`
然后点击`am` 就可以自动点击加载更多按钮，不影响之前的下一页的快捷键设置。

ps: 这个得感谢插件作者大神，写的方法还是挺好用的，๑乛◡乛๑

**Comment by sgrjyb** [comment]
@leacoleaco 能不能把 步骤写下来 ,学会了我好自己设置 ?

{pasted.co](http://pasted.co/36fc64d3/fullscreen.php?hash=c1d79988c33c485dc2bb9b3bf6025dd6&linenum=false) 怎么识别上面的链接 ?

**Comment by leacoleaco** [comment]
@sgrjyb 额。。建议你可以看下作者的中文说明：
[https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md](url)

以第一种方法为例，设置步骤：
1、点击 `se` 进到 surfingkeys 的设置界面。
2、编辑配置（和使用vim编辑器一样）, 增加一行设置代码：

`settings.nextLinkRegex = /((加载更多|下一页|>>|next)+)/i;`

3、点击左上角的 “save” 按钮，成功后，刷新原来的网页，就可以当滚动到有‘加载更多’ 的时候，点击  `]]`  按钮实现翻页了。
4、如果继续加入设置 `settings.smartPageBoundary=true;` 则可以自动检测这个按钮并点击自动翻页，设置为 false 则不会自动翻页。

第二种方法也是一样的，就修改配置，就当做配置是一个  js 文件，编写后保存就可以了。。。

**Comment by sgrjyb** [comment]
@leacoleaco 再请教一个问题 我只想创建 mapkey('oz', '#8Open Search with alias z', 'Front.openOmnibar({type: "SearchEngine", extra: "z"})'); 

 怎么才能不用添加 addSearchAliasX('z', 'zhihu search', 'https://www.zhihu.com/search?type=content&q=');

因为我已经创建了 addSearchAliasX('ｈ', 'zhihu search', 'https://www.zhihu.com/search?type=content&q=', 'ｚ');

settings.smartPageBoundary=true; 没有自动翻页 [豆瓣tv](https://movie.douban.com/tv)

**Comment by sgrjyb** [comment]
@leacoleaco  [配置参考](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83)

![md](https://user-images.githubusercontent.com/28247198/31346019-41da8550-ad4a-11e7-868d-0e7d8a1b013b.PNG)

**Comment by sgrjyb** [comment]
@leacoleaco  识别文本链接

**Comment by jin6220** [comment]
@leacoleaco  你这个am代码 是在哪里学的啊 
需要学习js代码吗

**Comment by leacoleaco** [comment]
@jin6220 我认为作者写的这个软件的强大之处，就在于插件的配置。 插件配置时候你可以认为是在单独写一个 js 文件，只要熟悉javascript语言的话，多看看作者的 default-Settings ，甚至是作者的源码就会了。
由于代码调整会比较频繁，作者没精力一一吧暴露的接口写到说明文件中的，要开发超出可配置范围的特殊的功能就多看看作者源码吧。
牛逼的话，直接在配置中添入一个不依赖surfingkeys 暴露的方法的全新的功能都完全有可能。

**Comment by jin6220** [comment]
@leacoleaco 朋友你好 能不能请教你一个问题啊  知道怎么按大写o之后 打开文字中的url 在新窗口中打开吗？原版是当前窗口打开。
代码是：
mapkey('O', '#1Open detected links from text', function() {
    Hints.create(runtime.conf.clickablePat, function(element) {
        $(`<a href=${element[2]}>`)[0].click()
    }, {statusLine: "Open detected links from text"});
});

**Comment by leacoleaco** [comment]
@jin6220 其他方式不清楚，不过我这样写是有效的：
```
mapkey('O', '#1Open detected links from text', function() {
    Hints.create(runtime.conf.clickablePat, function(element) {
        RUNTIME("openLink", {
                    tab: {
                        tabbed: true,
                    },
                    url: element[2]
                });
        
    }, {statusLine: "Open detected links from text"});
});
```
似乎作者没提供  tabbed=true 的配置。。。
你问问 @brookhong 大神吧
