### ISSUE TITLE
在刚打开的页面里点击文本栏（比如搜索栏）第1次没有光标

### ISSUE THREAD

**Issue by z1314007** [brookhong/Surfingkeys#52]
如题，在刚打开的页面里点击文本栏（比如搜索栏）第1次没有光标，需要点第2次才会出现光标，之后如果不刷新页面的话就不会有这个问题了。不知道各位是不是也有这个问题？

PS：用了几年chrome终于找到的我想要的“选中→按键→搜索”功能了，这个功能太爽了。

**Comment by brookhong** [comment]
Fixed in 0.4.1.
