### ISSUE TITLE
弱弱地问下插件怎么更新？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#522]
github里没找到版本信息，我看Chrome的目录文件和github上对不起来，是作者还没发布吗？目前是0.9.10

**Comment by leacoleaco** [comment]
想最快体验新版，当然是自己在本地建立个文件夹然后git拉取下来。然后再浏览器中启用开发者模式。点击加载已解压的扩展程序后选择文件夹。。。
不过我觉得现在功能足够我用了，就慢慢等作者发布吧，哈哈

**Comment by hyaray** [comment]
我也试过把文件夹git下来覆盖，结果就出错了。。。

**Comment by brookhong** [comment]
@leacoleaco 说的对。是`Load unpacked extension`，不是覆盖。
![image](https://user-images.githubusercontent.com/288207/31431372-2044b024-ae39-11e7-98d4-70aeca2ce652.png)
