### ISSUE TITLE
How to disable surfingkey "new tab" and reset it to default

### ISSUE THREAD

**Issue by LovingYoung** [brookhong/Surfingkeys#529]
How to disable surfingkey "new tab" and reset it to default.

I have no idea why I need to review the shortcuts every time I open a tab.

**Comment by brookhong** [comment]
The newtab override is turned on by default, currently no way to turn off.

It is there not only for new users to get quick start, but aslo to make SurfingKeys work on new tab.

Let's vote, and keep it there for a while to get feedback for users.

**Comment by rainplus** [comment]
support to disable the newtab,I want custom it by myself!

**Comment by PrestanceDesign** [comment]
Yeah making this optionnal seems good for users who use another extension like Momentum https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca...or maybe we can extend this "new tab" with a daily photo and quote :)

Anyway, thank you for your nice work. SK is great (I've moved recently from Vimium).

Best regards.

**Comment by iwestlin** [comment]
please disable newtab asap
i can't live without surfingkeys or speed dial 2
but now only one of them can work...

**Comment by PrestanceDesign** [comment]
@brookhong 
> but aslo to make SurfingKeys work on new tab.

Do you have a use case ?

**Comment by mrdear** [comment]
对于new tab,大多数人还是想自己定制,或者使用专业的tab插件来定制,这种强制绑定的行为并不友好,希望提供一个开关.

**Comment by sgrjyb** [comment]
现在的新标签页太简单 也不美观 ,  Top Sites 改成标签页动态信息 像默认 new tab 然后可以自定义 类似于 Speed Dial2

**Comment by NicholasAsimov** [comment]
Make this toggle, please. A lot of people use extensions to change their new tab experience and now SurfingKeys just forces everyone to use theirs.

**Comment by sgrjyb** [comment]
@brookhong  1.更新之后怎么启用 surfingkey "new tab"  ? 2.使用 Google搜索时 不自动选择第一个匹配的结果

**Comment by simonwjackson** [comment]
@NicholasAsimov Yes, option to toggle and on by default.

**Comment by simonwjackson** [comment]
@brookhong What about an option to customize the sections or all html on this page?

**Comment by brookhong** [comment]
@PrestanceDesign The use case is to enable Surfingkeys on new tab,  URL with`chrome://` scheme is forbidden to run content script from any extension by the browser, so that you could not use any shortcuts from Surfingkeys.

@simonwjackson That's what I expected to do, but looks like most users prefer to their own choices on the new tab setting. So this feature will hold on, until we got a better solution. Dynamically override of new tab with Javascript does not work as nicely as `chrome_url_overrides` in manifest.json so far.

**Comment by brookhong** [comment]
Thanks all.

Newtab override has been disabled from 0.9.12.

**Comment by PrestanceDesign** [comment]
Thanks @brookhong (y)
