### ISSUE TITLE
Surfingkeys new tab page

### ISSUE THREAD

**Issue by karlicoss** [brookhong/Surfingkeys#536]
Hi. Last friday my browser somehow switched to a non-default new tab page, and I think it was [that page](https://github.com/brookhong/Surfingkeys/blob/master/pages/start.html). I don't know how it switched, but I loved it so I assumed it was a plugin update or something. However, when I came to work this morning, this new tab page was gone, and again was the default chrome new tab. I am still able to access start.html via `chrome-extension://<blahblahblahextentionid>/pages/start.html`, but apparently it's not easy to change default new tab in chrome without installing other plugins. I don't even mind using another plugin for it, but I am pretty sure it worked without my intervention (or did it? Maybe I'm going mad and just imagining things).
Anyway, is there a setting to turn this page on? Thanks :)

**Comment by brookhong** [comment]
Finally you are here.

What you have seen last Friday is an experiment feature for new tab override, which had been turned off hours later.

It was surprise to me that there was no one vote for that feature. Please see #529 for why I added the feature and why I turned it off just hours later.

As the override setting is a static configuration in `manifest.json`, users could not turn it on or off by themselves. I may bring it back if there were more votes like you.

**Comment by karlicoss** [comment]
Ah thanks for explanation, I see. Yeah, I can understand people's frustration, but even though it is static, doesn't mean one can't hack it ;) 
I grepped in chrome settings in `~/.config/google-chrome` and apparently if you add
```
 "chrome_url_overrides" : {		
       "newtab": "pages/start.html"		
     },
``` to the plugin's `manifest.json`, start the Chrome, close it again, and then in `Default/Preferences` set `active` to `true` next to `newtab` setting, once you start the Chrome you're gonna have surfingkeys newtab page :) 
It's not very sustainable, not sure if it will survive the plugin update, but they are not that often anyway, so I'll probably make a script to fix that for me after update.

But ultimately, there must be ways of changing that dynamically, given that extensions to change new tab page do exist? E.g. some of them are open source (https://github.com/jimschubert/NewTab-Redirect), but not sure how easy is that to support.

**Comment by breneser** [comment]
I was using another new tab extension to load Surfingkeys frontend.html (which I assume keeps changing with an id in extension with each release? )

I was pleasantly surprised when I saw new tab page, and have been scratching my head wondering what I did that made it disappear :)

Please bring it back ? :heart:

**Comment by maximbaz** [comment]
@brookhong no need for a vote, here's how to optionally override new tab: [link](http://kushagragour.in/blog/2017/07/conditional-newtab-override-chrome-extension/)

I think it is totally fine to even have this feature enabled by default, just please make it very easy to find how to disable this - for example, publish exact configuration in #529 where a lot of interested people are already subscribed for new messages.

**Comment by brookhong** [comment]
@maximbaz Yes, but there is a problem with this way. Please see the comment under the 1st answer  of https://stackoverflow.com/questions/30437737/programmatically-or-optionally-override-chromes-new-tab-page

**Comment by maximbaz** [comment]
The required permissions are already requested, so the problem is a not-very-beautiful URL on the new tab page? Annoying, but much less annoying than Surfingkeys suddenly blocking other extensions that provide custom new tab 🙂

Another idea, maybe consider creating a second browser extension in the webstore? In other words, you will have a single codebase in this repository, but when you make a chrome extension out of it, make two extensions, one with new tab page and another one without it.

**Comment by bizzyman** [comment]
Is there any chance the start page will ever make it back as a toggle? I can't seem to make it work by loading it locally

**Comment by crocket** [comment]
I'd like to set the new tab page to be a blank page from surfingkeys so that I can press surfingkey shortcuts in a blank page.
