### ISSUE TITLE
Open tab number <gtX>

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#537]
gtX - replace X with the number of tabs
Example:
Press 'gt4' - open tab number 4

**Comment by simonwjackson** [comment]
@D1mon Maybe `4gt` would be a better approach. Otherwise, you would need a timeout to differentiate `1gt` from `11gt`. this syntax also matches code navigation: `44gg`

**Comment by D1mon** [comment]
Yes, so too it is possible. No matter how to do it, the main thing is that there was such an opportunity.

**Comment by brookhong** [comment]
Looks like this is a same issue as #413, which was resolved by using prefix number as parameter of `Front.chooseTab`.

You could use `11T` to jump to the 11th tab.

**Comment by D1mon** [comment]
Yes that's it. But you need to do as in vim. `4gt`

**Comment by brookhong** [comment]
You could add below in your settings:

    map('gt', 'T');

**Comment by D1mon** [comment]
Do not you want to add this to the main code? This will be useful to others.
