### ISSUE TITLE
Bug: Omnibar URL input triggers search

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#538]
@brookhong Where is the code that parses input for URL detection?

![url](https://user-images.githubusercontent.com/189379/31612785-8e502dda-b246-11e7-839d-2bc65147cc61.gif)

related #486

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/d1ceb678de8c2312618e495b47a55c774fdc5b53/pages/omnibar.js#L392 Here it is.
