### ISSUE TITLE
请问如何实现Vim里的 Ctrl-^ 和 Ctrl-[ 功能？

### ISSUE THREAD

**Issue by qxj** [brookhong/Surfingkeys#542]
在搜索cVim相关问题时候看到Surfingkeys，立刻被吸引住了，感谢作者提供这么强大的chrome插件。

但试用过后有两个问题无法解决：

- vim里可以用`Ctrl+^`快速切换最近访问的Buffer，cVim里也可以同样的快捷键切换最近访问的Tab。
- vim和cVim可以直接用`Ctrl-[`替代`Esc`，这样操作避免频繁离开主键盘区，比较便捷。

请问该如何配置能够实现如上功能？谢谢。

**Comment by brookhong** [comment]
在0.9.13默认设置里增加`Ctrl-6`，如果要使用`Ctrl-[`，请自行添加如下设置

    map("<Ctrl-[>", "<Esc>");
