### ISSUE TITLE
提示弹出框文字颜色修改？

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#543]
![image](https://user-images.githubusercontent.com/5415510/31812059-5c847b64-b5b4-11e7-8b6b-9fe1259c572b.png)

无法查看该元素的source code， 颜色无法看

**Comment by brookhong** [comment]
如下设置：

    settings.theme = `
        #sk_keystroke .annotation {
            color: blue;
        }
    }`;

**Comment by yech1990** [comment]
It work!

**Comment by evadknarf** [comment]
visual mode 的popup keys  深蓝字体黑背景 怎么改深蓝?
