### ISSUE TITLE
光标定位偏移及配色出错

### ISSUE THREAD

**Issue by feng84** [brookhong/Surfingkeys#544]
1、配置页面，光标向右偏移4个位。如图，我定位在最后的";"，光标在右4位，这样配置很难修改

![y](https://user-images.githubusercontent.com/32972859/31847346-013d4d1e-b64d-11e7-9073-32677e1c4486.png)

2、开启自带theme设置后，Omnibox显示如下图。btw，github展示插件配色超赞！

![x](https://user-images.githubusercontent.com/32972859/31847372-d7677428-b64d-11e7-87e4-9637bbf59e2b.png)

捣鼓半天，不知问题在哪，望有高人指点。
环境：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

**Comment by brookhong** [comment]
更新到0.9.13，重置一下再保存，原来自带的设置示例有问题。

**Comment by feng84** [comment]
重置后，配色差不多了，谢谢！

偏移的我也查出了，ace editor要求等宽字体，如果系统没这些字体或者浏览器设置等宽字体不对，就会出现光标问题，希望对后来者有用

**Comment by sgrjyb** [comment]
@feng84  怎么设置成像这样的的 ? 能分享 你的 Surfingkeys 配置吗 ?

![](https://user-images.githubusercontent.com/32972859/31847372-d7677428-b64d-11e7-87e4-9637bbf59e2b.png)

**Comment by caiheyao** [comment]
把微软雅黑换成等宽的宋体，问题解决了:D

**Comment by 0x018** [comment]
> 把微软雅黑换成等宽的宋体，问题解决了:D

怎么换字体?换整个系统的??

**Comment by 0x018** [comment]
settings.theme = `
    #sk_status,#sk_find,#advancedSetting,#mappings,.ace_editor,.ace_content{
        font-family: "DejaVu Sans Mono", "Noto Sans CJK SC", "WenQuanYi Zen Hei", sans-serif;
        font-size:12px;
        background:red!important;
    }
}`;
改了不生效
