### ISSUE TITLE
Mode mappingsEditor pushed into mode stack again.

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#553]
## Error details

Modes in stack: Disabled,mappingsEditor,Normal

SurfingKeys: 0.9.13

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

URL: chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Should have been fixed in 0.9.14.
