### ISSUE TITLE
SurfingKeys does not properly disable with blacklist

### ISSUE THREAD

**Issue by djgalvan** [brookhong/Surfingkeys#555]
When a website is blacklisted, either manually in settings, or through a key press, SurfingKeys does not properly stay disabled. In my case, when I log into TestOut, which is blacklisted, I find that SurfingKeys is still registering my keys, I would have to re-enable and then re-disable SurfingKeys through a double use of 'Alt+s'.  This workaround does not stay persistent and does not work with the domain manually blacklisted in my config.

**Comment by brookhong** [comment]
`;s` is to Toggle PDF viewer from SurfingKeys.

`Alt-s` is the one to toggle Surfingkeys.

**Comment by djgalvan** [comment]
Oops, that's the combo I meant to report, updated.
