### ISSUE TITLE
Mouse scroll doesn't work in chrome pdf viewer

### ISSUE THREAD

**Issue by melihovv** [brookhong/Surfingkeys#559]
When chrome opens pdf with its default pdf viewer (not the one shipped with this extension) mouse scroll doesn't work. If I disable this extension or use pdf viewer which is shipped with this extension mouse scroll works. This bug appeared maybe a few weeks ago. Before mouse scroll works normally.

**Comment by FangliangBai** [comment]
I have the same issue, which is described above, in the latest Chrome (Version 79.0.3945.130 (Official Build) (64-bit))
