### ISSUE TITLE
请问一下如何清空所有的 mark

### ISSUE THREAD

**Issue by fyang93** [brookhong/Surfingkeys#563]
在 vim 里面 mark 是可以通过 delmarks 命令清空的，但是在 default mappings 里面没有找到类似的功能，觉得有点奇怪。现在是没有实现清空 mark 或者删除指定 mark 的功能吗？

**Comment by hqabcxyxz** [comment]
> 在 vim 里面 mark 是可以通过 delmarks 命令清空的，但是在 default mappings 里面没有找到类似的功能，觉得有点奇怪。现在是没有实现清空 mark 或者删除指定 mark 的功能吗？

你好 请问你解决这个问题了么？

**Comment by fyang93** [comment]
> > 在 vim 里面 mark 是可以通过 delmarks 命令清空的，但是在 default mappings 里面没有找到类似的功能，觉得有点奇怪。现在是没有实现清空 mark 或者删除指定 mark 的功能吗？
> 
> 你好 请问你解决这个问题了么？

并没有，干脆不用这个功能了

**Comment by lonelykid** [comment]
om显示所有marks，可以按Ctrl+D一个个删，没找到全部删除的功能。挺好一个extension，可惜开发者不维护了
