### ISSUE TITLE
Download image hint?

### ISSUE THREAD

**Issue by paradox460** [brookhong/Surfingkeys#564]
I've been trying to add a hint command for download image, but have run into a snag.

Chrome has the `chrome.downloads.download` API for triggering a download from the browser, and I see that Surfingkeys has the permission already established in its manifest. But I cannot get a binding to work with the command.

Here is the attempt I made at writing a binding:

```js
mapkey('ci', '#2Download Image', function() {
    Hints.create('img', function(element) {
      chrome.downloads.download({url: element.src});
    });
});
```

**Comment by malokroman** [comment]
I am new to SurfingKeys and I would like to have this feature as well. Really looking forward to see this happen.

**Comment by snowman** [comment]
Is there any workaround for this?
