### ISSUE TITLE
[Feature request] Following link hints by typing title

### ISSUE THREAD

**Issue by Lchu613** [brookhong/Surfingkeys#566]
I'm migrating over from Vimium and Vimperator and I'm enjoying the easy customizability and default left-handedness, however, I don't think there's currently an option for this. Several other vim-like extensions have link-hint following that allows you to start typing the text of the link (which requires setting the link hints to numbers but makes it more intuitive to follow buttons with text).

**Comment by Lchu613** [comment]
Never mind - I see there is indeed an option for this, using Hints.numbericHints = true;
(Although I would point out that it should maybe be numeric, haha)

**Comment by brookhong** [comment]
Thanks for reporting this.
