### ISSUE TITLE
在搜索栏中正确使用下一页结果的方法

### ISSUE THREAD

**Issue by dirtyluke** [brookhong/Surfingkeys#568]
0.9.14上不能使用，是我打开方式错了么，还是取消了 @brookhong

**Comment by brookhong** [comment]
`Ctrl-.`，你是用的这个吗？

**Comment by dirtyluke** [comment]
嗯，Windows下Ctrl 和 . 一起按，无效 @brookhong

**Comment by brookhong** [comment]
刚在windows下试了，没有问题。

你是不是切到中文输入法了？

**Comment by dirtyluke** [comment]
我试了一下，默认输入法可以，搜狗输入法不行，我搜狗输入法里面没有设置`Ctrl - .`的热键

**Comment by dirtyluke** [comment]
谢谢，原来搜狗输入法'Ctrl-.'默认切换标点符号状态，貌似改不了 @brookhong
