### ISSUE TITLE
配置界面如何实现【重新加载配置文件并保存】的方法呢？

### ISSUE THREAD

**Issue by hyaray** [brookhong/Surfingkeys#569]
在调试时才经常用到，不知Surfingkeys本身能否实现该功能，用的是您提供的Chromium

**Comment by brookhong** [comment]
你可以使用从文件加载设置，这样只要修改保存文件就行，每次页面刷新会自动从文件加载设置的。

![image](https://user-images.githubusercontent.com/288207/32784048-4e6d9d72-c913-11e7-99f6-078c1826fa2c.png)

**Comment by hyaray** [comment]
我一直是用本地文件的方式的，刷新页面是会重新加载设置，但是要生效每次要点击【save】按钮吧，能不能我刷新页面，Surfingkeys自动加载文件并生效（相当于点击save）呢

**Comment by brookhong** [comment]
就是自己加载的，你不需要点save按钮。只要第一次指定文件路径时，点下save按钮，也是唯一一次需要点击save按钮的时候。

**Comment by hyaray** [comment]
好吧！竟然我多余劳动了这么久，真是万分感谢回答！！！给别人参考也是极好的
