### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by lb8023lyy** [brookhong/Surfingkeys#57]
支持开发者，很喜欢书签功能（以文件夹显示）
暂时发现两点：
没有[[和]]翻页功能，不知道是不是没找到
在chrome的newtab下插件不起作用

**Comment by brookhong** [comment]
`[[`和`]]`是默认的，但中文用户需要在你的配置里加入下面的设置来识别中文“上一页”

    mapkey('[[', 'Click on the previous link on current page', function() {
        var prevLinks = $('a').regex(/((上页|上一页|<<|prev(ious)?)+)/i);
        if (prevLinks.length) {
            clickOn(prevLinks);
        } else {
            walkPageUrl(-1);
        }
    });
    mapkey(']]', 'Click on the next link on current page', function() {
        var nextLinks = $('a').regex(/((下页|下一页|>>|next)+)/i);
        if (nextLinks.length) {
            clickOn(nextLinks);
        } else {
            walkPageUrl(1);
        }
    });

**Comment by yech1990** [comment]
有没有优先级的设置。
比如百度搜索出现了这样一个链接 `更多关于XXX的问题>>`
当要点击`下一页`的时候后优先点到 `>>`
