### ISSUE TITLE
[Bug] <Number>T doesn't work well if there are multiple windows

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#570]
<Number>T (switch to the Nth tab) doesn't switch to the right tab if there are multiple windows opened.

**Comment by JohnnRen** [comment]
+1 for this

**Comment by HaleTom** [comment]
@brookhong I'm still experiencing this issue.  `T` gives me a picklist, but `1T` does nothing (apart from temporarily showing `1` bottom right of the window).

There is no commit associated with the closure... was this perhaps closed in error?

**Comment by HaleTom** [comment]
Hi @brookhong, just following up on the previous enquiry after two weeks.

**Comment by brookhong** [comment]
Sorry for late reply. Yes, this must be closed in error. Reopening it and will look into it next week hopefully.
