### ISSUE TITLE
请问什么时候支持下火狐浏览器呢

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#572]

**Comment by rainplus** [comment]
同问！firefox 57版本 已经迁移到WebExtensions，SwitchOmega在个版本也兼容了，希望早日能在firefox上用到suringkeys!

**Comment by brookhong** [comment]
0.9.15已开始支持Firefox。
https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/

**Comment by haoxuexiaoyao** [comment]
@brookhong https://www.jd.com/在这个京东页面 火狐浏览器下这个插件是无法使用 f 键的

**Comment by haoxuexiaoyao** [comment]
@brookhong 浏览器版本 Firefox quantum 57 淘宝也有很多页面插件失效,浏览器打开的页面标签移动也失效

**Comment by brookhong** [comment]
@haoxuexiaoyao 0.9.16已解决，试试看。

**Comment by haoxuexiaoyao** [comment]
谢谢 已测试使用 没有问题了
