### ISSUE TITLE
Support for FireFox Quantum

### ISSUE THREAD

**Issue by phillipwei** [brookhong/Surfingkeys#574]
Hi! I would love to be able to use this in FireFox Quantum.

**Comment by Stvad** [comment]
's a duplicate of https://github.com/brookhong/Surfingkeys/issues/329

**Comment by brookhong** [comment]
https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/

0.9.15 released for Firefox, closed this.

**Comment by zzxqd** [comment]
is it had closed?why can't i search on https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/  it show that :Page not found
