### ISSUE TITLE
Allow optional domain pattern for (some) settings

### ISSUE THREAD

**Issue by deadcyclo** [brookhong/Surfingkeys#575]
It would be great if one could add multiple versions of the same setting, with domain patterns, for those settings where such an option makes sense.

An example of where this would be a great feature is the focusFirstCandidate setting. Generally nice to have set to 'false', but on some individual url's 'true' is nice, such as on pages that contain a from you continuously fill out.

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-add-domain-specific-settings
