### ISSUE TITLE
Emacs-keybindings in ace?

### ISSUE THREAD

**Issue by deadcyclo** [brookhong/Surfingkeys#578]
I would greatly appreciate if you could add a setting to allow one to choose emacs keybindings in the implemented ACE-editor, rather than vim-keybindings. Shouldn't be much work since ACE has emacs keybinding support out of the box.

**Comment by Naheel-Azawy** [comment]
Any updates on this??
Plus it would be really appreciated if emacs bindings are added as an option for the extension in general

**Comment by JSpenced** [comment]
Any update on this? I care less about bindings as a whole because these can be customized with the config file but is there a way to get emacs keybinding support in ACE. It's difficult to switch back and forth between the two sets of bindings for editing text.

**Comment by JSpenced** [comment]
`Ctrl+x Ctrl+s` doesn't work for me to save the input? How to remap this to a different keybinding to test if it is working?
