### ISSUE TITLE
E,R两键进入Chrome设置页和本地HTML在浏览器中打开页时就会失效

### ISSUE THREAD

**Issue by congzhaoyang** [brookhong/Surfingkeys#579]
切换网页的时候,遇到例如`chrome://inspect/#devices`或者`file://Users//page/activity-entry.html`这两种类似的链接,E.R键就无法切换页面了.

**Comment by brookhong** [comment]
对`file:///`这些页面，你需要到`chrome://extensions/`，找到`Surfingkeys`然后点下图中的勾勾。
![image](https://user-images.githubusercontent.com/288207/33237369-64cd4068-d237-11e7-981b-45c197999bce.png)

对`chrome://`这些页面，请看
http://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages-cn.html
