### ISSUE TITLE
Firefox 57 插件失效问题

### ISSUE THREAD

**Issue by dangoron** [brookhong/Surfingkeys#583]
操作系统: Win10, arch linux
测试环境: Firefox Quantum 57 (64-bit)
问题描述: 在网页 https://bbs.saraba1st.com/2b/forum.php 中，先用 f 键访问任意链接，再用 S 键返回原网页，插件会失效，必须要刷新一次才能恢复正常，测试了其他网页暂时没有发现此问题。希望能够解决 :)

**Comment by azuwis** [comment]
在 http://bbs.nga.cn 上碰到同样的问题。

**Comment by yuyang0** [comment]
天猫，淘宝的商品页面似乎也会失效，有些页面会提示阻止弹出窗口

**Comment by brookhong** [comment]
0.9.16中已解决，大家请试试看。

**Comment by yuyang0** [comment]
FF提示阻止弹出窗口，这个问题还是有

**Comment by dangoron** [comment]
arch linux，上述问题依然存在

**Comment by brookhong** [comment]
0.9.17 解决了S退回后按键失效的问题。

但FF提示阻止弹出窗口这个问题，是firefox阻止的，可以点那个提示，选择总允许，以后就不会阻止了。

**Comment by dangoron** [comment]
确认问题已经解决，谢谢作者修复！
