### ISSUE TITLE
FF57中剪贴板的问题

### ISSUE THREAD

**Issue by xiangsheng** [brookhong/Surfingkeys#584]
FF57中cc的行为在直接选择一个链接时效果正常，即在新标签页中打开一个链接，但是如果尝试打开剪贴板中的链接，则会产生无任何相应的情况。类似的;pp的行为也有一些异常。

另外，是否可能把在在新标签中打开链接的行为设置成如同导航栏一样的效果，即如果是链接就直接打开链接，如果是文字则使用默认搜索引擎搜索。

**Comment by zzxqd** [comment]
在哪里找的呀,没搜到
