### ISSUE TITLE
Feature request: a way to share configuration files

### ISSUE THREAD

**Issue by snoblenet** [brookhong/Surfingkeys#585]
Love SurfingKeys. I spend a good deal of time setting up configuration files for individual websites that have set up certain desirable keyboard shortcuts but not others. It would be really great to have a way to chop these settings up into one-site files that could be shared on the surfing keys equivalent of greasespot.

**Comment by b0o** [comment]
+1

I've thought about a plugin system plus a community site like [Package Control](https://packagecontrol.io/), (Stylish](https://userstyles.org/), or Greasespot as you mentioned, which I think would be excellent for Surfingkeys. 

Something like this would really set Surfingkeys apart from all similar extensions and give it many more possibilities.
