### ISSUE TITLE
Any CHANGE LOGS ?

### ISSUE THREAD

**Issue by alswl** [brookhong/Surfingkeys#588]
After 0.9.17 released, my configuration is break by some changes.

eg.: https://github.com/alswl/.oOo./commit/089e3e9a4e66a99f09e00af3a9e24bb4dcc6e2d4

*   `Front.getContentFromClipboard` -> `Clipboard.read`
*   `Front.writeClipboard` -> `Clipboard.write`

Is there any changes logs?

**Comment by brookhong** [comment]
Now, changelog could be accessed from the popup menu by clicking on Surfingkeys icon.

**Comment by alswl** [comment]
Is is possible provide a API **break** change log document?
