### ISSUE TITLE
this plugin has potential to be great but lacks one critical API

### ISSUE THREAD

**Issue by redguardtoo** [brookhong/Surfingkeys#589]
I think current APIs are too specific and don't trust the users the full freedom.

A simple extra API `Front.read` will make this plugin great.
```javascript
const config = {
   prompt: 'Find:',
   collection: ['item1', 'item2',]
   action:  itemSelected => console.log(itemSelected)
};
Front.read(config);
```

**Comment by brookhong** [comment]
I can not get your point.

Could you please elaborate your case?

**Comment by redguardtoo** [comment]
When calling API, I need some UI to filter and select a give item in the collection.

The UI is similar to the pop when pressing `b` (select bookmark).

For example, I use only bookmark service http://pinboard.in instead brower's built in bookmarks. So all I need implement my own command with similar UI to bookmark selection.
