### ISSUE TITLE
请增加对Safari的支持

### ISSUE THREAD

**Issue by cuiweifu** [brookhong/Surfingkeys#59]
目前很多流行的插件也是有Safari版本的, 因为都是基于Webkit内核,应该代码迁移上不会做太多的工作, 包格式上有所差异. 

在mac上, 感觉chrome的耗电量比Safari要高不少. 如果能对Safari进行支持就完美了.

**Comment by brookhong** [comment]
safari插件开发需要一个每年99$的开发者账号来生成一个证书，我没有这样的账号。

如果有人能帮忙提供一个证书先，我可以试试移植到safari。如果可行的话，我随后会正式注册一个开发者账号，并且针对safari版本需要购买。对于预先提供测试证书的人，免费提供。😃
