### ISSUE TITLE
Many PDF files fail to display properly

### ISSUE THREAD

**Issue by abastardi** [brookhong/Surfingkeys#591]
Here is an example:

https://www.opm.gov/healthcare-insurance/healthcare/plan-information/plan-codes/2018/brochures/73-828.pdf

In the above and other PDFs, no text displays, though images do display.

Below are some of the errors from the browser console:

```
pdf_l10n.js:1 no resource to load, early way out

pdf_l10n.js:1 #of_pages is undefined.
h @ pdf_l10n.js:1
get @ pdf_l10n.js:1
_updateUIState @ pdf_viewer.js:5
_localized @ pdf_viewer.js:5
Promise resolved (async)
_bindListeners @ pdf_viewer.js:5
e @ pdf_viewer.js:5
(anonymous) @ pdf_viewer.js:1
_initializeViewerComponents @ pdf_viewer.js:1
(anonymous) @ pdf_viewer.js:1
Promise resolved (async)
initialize @ pdf_viewer.js:1
run @ pdf_viewer.js:1
r @ pdf_viewer.js:5

pdf.worker.js:13 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
(anonymous) @ pdf.worker.js:13
(anonymous) @ pdf.worker.js:13
t @ pdf.worker.js:1
t @ pdf.worker.js:19
t @ pdf.worker.js:1
Object.defineProperty.value @ pdf.worker.js:1
(anonymous) @ pdf.worker.js:1
(anonymous) @ pdf.worker.js:1
(anonymous) @ pdf.worker.js:1

pdf_l10n.js:1 #thumb_page_title is undefined.
h @ pdf_l10n.js:1
get @ pdf_l10n.js:1
t @ pdf_viewer.js:4
(anonymous) @ pdf_viewer.js:4
Promise resolved (async)
setDocument @ pdf_viewer.js:4
load @ pdf_viewer.js:2
o.promise.then.t @ pdf_viewer.js:2
Promise resolved (async)
open @ pdf_viewer.js:2
ce @ pdf_viewer.js:2
(anonymous) @ pdf_viewer.js:1
Promise resolved (async)
a @ pdf_viewer.js:1
Promise resolved (async)
run @ pdf_viewer.js:1
r @ pdf_viewer.js:5

pdf_viewer.js:2 PDF 3df4bd9e5eb66f40f8e142f79c8d720e [1.7 PDFlib 8.0.1p3 (.NET/Win64) / -] (PDF.js: 1.8.355)
pdf.js:1 Warning: Error during font loading: Maximum call stack size exceeded
pdf.js:1 Warning: Error during font loading: Maximum call stack size exceeded

pdf_l10n.js:1 #toggle_sidebar_notification is undefined.
h @ pdf_l10n.js:1
get @ pdf_l10n.js:1
value @ pdf_viewer.js:4
(anonymous) @ pdf_viewer.js:4
(anonymous) @ pdf_viewer.js:1
dispatch @ pdf_viewer.js:1
value @ pdf_viewer.js:3
value @ pdf_viewer.js:3
(anonymous) @ pdf_viewer.js:2
Promise resolved (async)
(anonymous) @ pdf_viewer.js:2
Promise resolved (async)
load @ pdf_viewer.js:2
o.promise.then.t @ pdf_viewer.js:2
Promise resolved (async)
open @ pdf_viewer.js:2
ce @ pdf_viewer.js:2
(anonymous) @ pdf_viewer.js:1
Promise resolved (async)
a @ pdf_viewer.js:1
Promise resolved (async)
run @ pdf_viewer.js:1
r @ pdf_viewer.js:5
```

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/33707212-52e841b8-dafc-11e7-8c29-aec710f89db9.png)

Works for me.

What's your OS? Chrome version?

**Comment by abastardi** [comment]
I'm using Chrome 63.0.3239.84 64-bit on Windows 10 Pro. Here's what I see:

<img width="741" alt="pdf" src="https://user-images.githubusercontent.com/1295688/33725785-2d21b14a-db41-11e7-85cf-bcba2e411066.png">

Any ideas?

**Comment by dansbandit** [comment]
I had the same problem. I'm on Google Chrome Version 63.0.3239.84 (Official Build) (64-bit) and Windows 10.

Example pdf: https://cseweb.ucsd.edu/~hovav/dist/rop.pdf

The example pdf gives me lines.

![pdfjsinchrome](https://user-images.githubusercontent.com/4530687/32109312-a75ca91a-bb34-11e7-92a2-a2201955dc51.png)

However it works on Google Canary Version 65.0.3289.0 (Official Build) canary (64-bit).

![pdfjsincanary](https://user-images.githubusercontent.com/4530687/32109313-a77eff06-bb34-11e7-973d-b663507a24b3.png)

[log for Chrome](https://github.com/brookhong/Surfingkeys/files/1422411/gfbliohnnapiefjpjlpjnehglfpaknnc-1509098728776.log)

The [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm/reviews) viewer extension displays the pdf correctly.

[log for Canary](https://github.com/brookhong/Surfingkeys/files/1422412/gfbliohnnapiefjpjlpjnehglfpaknnc-1509098767698CANARY.log)

I have tried to disable hardware acceleration and 2d canvas but the problem remains. The problem remains in Chrome Beta as well.

**Comment by brookhong** [comment]
https://github.com/mozilla/pdf.js/issues/7044
https://github.com/mozilla/pdf.js/issues/7326

Looks like there is bug when Chrome running minified JS code, and the bug seems to be fixed in Canary, as you could see from @dansbandit 's testing result.

**Comment by abastardi** [comment]
The PDF viewer appears to be working again in the latest Chrome, so this issue can probably be closed.

**Comment by naefl** [comment]
Is there a chance to get the PDF viewer working from a locally stored PDF? only works for me from pdfs redirected from links

**Comment by purgat0ri** [comment]
In Vivaldi, PDFs either: crash the browser, or don't show up at all (this tends to be the outcome when turning off Surfingkey's own pdf.js with :s), or don't show up at all with an additional error: https://imgur.com/a/L2EkKfq

**Comment by ertwro** [comment]
Exactly the same problem with Vivaldi. It crashes when opening a pdf and ```;s``` doesn't help at all.

**Comment by januz** [comment]
I experience the same issues on Vivaldi. Is there any workaround?

**Comment by yetyman** [comment]
i had this exact issue, here is a reference to the issue that solved it for me.
i had to add the iis entry for the .properties mime type
in my case i added .properties=> application/l10n and it started working!
https://github.com/mozilla/pdf.js/issues/9643#issuecomment-381997152
