### ISSUE TITLE
请问关于go打开历史记录与书签里没有的链接时永远启用google搜索的问题……

### ISSUE THREAD

**Issue by Anaheim55** [brookhong/Surfingkeys#592]
如果历史记录与书签里没有的链接在go状态下打开时，会强制使用浏览器当前搜索引擎对次链接进行搜索……
这个特性是chrome地址栏的问题么？还是可以在surfingkeys下做修改？
因为不知道该去哪里求助，所以来issues这里反馈了，作者大大抱歉啊……

**Comment by brookhong** [comment]
这个是Surfingkeys的一个功能，你在设置里加入下面这行：

    settings.defaultSearchEngine = 'b';

使用百度搜索。
