### ISSUE TITLE
在选中文字上右键单击时，会清除选中的文字

### ISSUE THREAD

**Issue by qwertyyb** [brookhong/Surfingkeys#593]
![oUngO.gif](https://s1.ax1x.com/2017/12/05/oUngO.gif)
如上图

**Comment by ewgasdf** [comment]
在输入框内选中文字后右键会取消选中

**Comment by brookhong** [comment]
在设置里加入下面这行：

    settings.cursorAtEndOfInput = false;

**Comment by brookhong** [comment]
#618
