### ISSUE TITLE
火狐插件库中搜索不到这个插件

### ISSUE THREAD

**Issue by zzxqd** [brookhong/Surfingkeys#597]
打开之前issues里出现的火狐插件库的页面显示的没有找到是下架了吗还是怎么

**Comment by pgain2004** [comment]
同问

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/33795221-0fa68ccc-dca3-11e7-9928-f8ea126cd5c9.png)

有管理员review时提了个问题，我没看到，不知道啥问题？在等他回复。

**Comment by brookhong** [comment]
http://brookhong.github.io/2017/12/09/surfingkeys-for-firefox.html

暂时可以从这里下载。
http://brookhong.github.io/assets/downloads/surfingkeys-0.9.17.xpi

**Comment by zzxqd** [comment]
![default](https://user-images.githubusercontent.com/23022401/33811573-1627e330-de50-11e7-8756-649f7064f2c8.png)
感谢!
虽然我这里已经装上了,但网址不知道谁给举报了为了恶意软件
库主看看有无必要进行处理

**Comment by zzxqd** [comment]
感谢!
虽然我这里已经装上了,但网址不知道谁给举报了为了恶意软件
库主看看有无必要进行处理
![default](https://user-images.githubusercontent.com/23022401/33811634-cd07a6d0-de50-11e7-860d-4cba5e5f8cc8.png)
