### ISSUE TITLE
按 `T` 选择标签时，对标签缩略块前后排序

### ISSUE THREAD

**Issue by kelly-apollo** [brookhong/Surfingkeys#599]
提一个不成熟的小建议，按 `T` 选择标签时，对标签缩略块前后排序，在选择标签时会更直观，选中速度更快。

**Comment by brookhong** [comment]
现在就是有序的，不过缩略块大小不一，打算改成大小一致的。

**Comment by kelly-apollo** [comment]
![image](https://user-images.githubusercontent.com/4319332/33920378-9be750f6-dff8-11e7-9933-50c884ade58d.png)

请问顺序不应该是  `Hacker News -> JS -> Twitter -> reddit` 吗？

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E5%88%87%E6%8D%A2%E6%A0%87%E7%AD%BE%E9%A1%B5

呃，忘了还有个设置

    settings.tabsMRUOrder = true;

你需要改成false。
