### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by blackdaemon** [brookhong/Surfingkeys#600]
Suddenly I am unable to save the settings of Surfingkeys.
I am getting following error after hitting the Save button:

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://www.google-analytics.com".

I basically lost all changes made to the settings in last week as they did not persist after the Chrome restart (I was not seeing any such error before the Chrome restart, it was failing silently. I just realized this problem when I noticed that my theme changes were not persisted).

SurfingKeys 0.9.19
Google Chrome Version 54.0.2840.100 (64-bit) on RHEL 6.9

**Comment by brookhong** [comment]
Sorry about that.

The issue was cause by removal of `unsafe-eval` from `content_security_policy` in manifest.

Fixed in 0.9.20
