### ISSUE TITLE
火狐浏览器下面天猫详情页无法使用插件

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#605]
https://detail.tmall.com/item.htm?spm=608.7065813.ne.1.7f083ddeKy3ueC&id=558291073507&tracelog=jubuybigpic

在这个页面f 键以及其他快捷按键均失效

**Comment by haoxuexiaoyao** [comment]
火狐浏览器版本:Firefox Quantum 57.0
Surfingkeys 0.9.16

**Comment by brookhong** [comment]
0.9.22应该已解决。
