### ISSUE TITLE
最新版更新后，自定义的搜索失效

### ISSUE THREAD

**Issue by breezeit** [brookhong/Surfingkeys#608]
addSearchAliasX('z', '知乎 search', 'https://www.zhihu.com/search?type=question&q=');
mapkey('oz', '#8知乎 search', 'Front.openOmnibar({type: "SearchEngine", extra: "z"})');

比如我添加过的一个搜索，按了oz,右下角的文字提示是有的，但搜索条不出来了

![image](https://user-images.githubusercontent.com/17754387/33921900-e6a9a1f8-e001-11e7-80d7-d31521252b5b.png)

**Comment by brookhong** [comment]
改成

    mapkey('oz', '#8知乎 search', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "z"});
    });

直接使用字符串定义动作，已经不支持了。可以点击浏览器工具栏里Surfingkeys的图标看下changelog。
