### ISSUE TITLE
Mode Normal pushed into mode stack again.

### ISSUE THREAD

**Issue by dougluce** [brookhong/Surfingkeys#610]
## Error details

Modes in stack: Disabled,Normal

SurfingKeys: 0.9.21

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

URL: https://github.com/Neetless/sqlfmt

## Context

I had maybe 40 open tabs in this session across a dozen websites, hitting that Github site resulted in the "please file a bug" message so I'm doing so. I did not notice any problems outside the bug message.

**Comment by dougluce** [comment]
Was there a relevant fix or is this closed for age?

**Comment by brookhong** [comment]
Closed for age, are you still seeing the problem?

**Comment by dougluce** [comment]
Cannot seem to reproduce any longer.
