### ISSUE TITLE
有些界面不能使用快捷键？

### ISSUE THREAD

**Issue by hominlinx** [brookhong/Surfingkeys#613]
在有些界面不能使用surfingkeys吗？
比如：
![image](https://user-images.githubusercontent.com/1886121/34078261-84473acc-e351-11e7-894b-129abd9be82f.png)

![image](https://user-images.githubusercontent.com/1886121/34078266-965bae3c-e351-11e7-98eb-a151b8d2f472.png)

![image](https://user-images.githubusercontent.com/1886121/34078310-a9ef84e0-e352-11e7-8c16-f2b1a0de1e64.png)

这几个网页不能用， 有方法让它使用吗？

**Comment by Egi0lg** [comment]
> 插件能工作最基本的前提就是必须能截获键盘事件，在工具栏／插件面板，Chrome不接受addEventListener，所以不可能了
[来源](https://www.zhihu.com/question/20584125) 评论中找

**Comment by hominlinx** [comment]
使用Chromium 后， pdf看不到了 @Egi0lg

**Comment by friendfish** [comment]
最后一个页面没有解决，会跳出戏的。
由于查资料，经常遇到一些打不开的网站（原因你懂的），surfingkeys在网页打开失败的情况下不生效。
本来很流利的操作，立马跳戏，这个能否解决下。

**Comment by CQUTWangHong** [comment]
为啥这个插件在github界面不起作用，我下的是最新版的0.9.60，系统是mac catalina

**Comment by CQUTWangHong** [comment]
可以，原来是我之前关闭了。。
