### ISSUE TITLE
以X开始的Hint, 会直接关闭标签

### ISSUE THREAD

**Issue by dupontjoy** [brookhong/Surfingkeys#615]
忘了说明, 使用的是**Firefox版**
以"f" Hint模式打开网页时, 遇到Hint以X开头, 如"XB"时, 按X时, 标签就关闭了, 无法用XB打开页面
发现是在部分网站上有这个问题, 比如: http://dig.chouti.com/

另外, 希望"f"模式时, 总是在当前标签页打开

**Comment by Egi0lg** [comment]
1、chrome 你说的这些问题都是不存在的，作者的这个插件是捕获键盘事件，你的可能是浏览器原因。你给的网址，跟我自己找测试都 OK
2、f 模式时，如果链接是到现在访问的网站的，是会在标签页打开的，如果是其它域名则会打开新窗口。如果是想一个标签页访问所有网址。。嗯 ~emmmm

**Comment by dupontjoy** [comment]
@Egi0lg 
1. 我使用的是Firefox, 看来是Firefox版的bug
2. 这样设置也OK. f模式, 所有链接都强制本标签打开, 是vimfx的操作习惯

**Comment by zzxqd** [comment]
我也是firefox,目前除了在zhihu这个站点上会出现你的说的问题,其他网页上正常,但我这里有别的问题就是'T'切换标签的时候能出现hint,但后续无论输入什么都没用,无论是在chrome还是在firefox(V58.dev.editor),浏览器和扩展(0.9.22)都是最新版本('t'切换标签没问题,但是需要输入关键词就有点麻烦),还有就是在zhihu这个网站上'f'打开hint后再输入hint字符会被当做新的命令,(x关闭就是这样产生的)

**Comment by dupontjoy** [comment]
@zzxqd 
我用的Nightly版, 整体来说这个扩展非常强大, 几乎达到了原vimfx的程度, 就是bug有点多

**Comment by zzxqd** [comment]
各有长短,vimfx因为api的原因能对浏览器级别的元素起作用,但局限性就在于功能不算全,surfingkeys功能很全,体验也不错,我现在除了在fiefox上的zhihu中'f'命令输入hint字符无用外,已经没有其他问题,现在chrome和vivaldi也都装了这个插件

**Comment by threefcata** [comment]
news.mydrivers.com上也会。按f或者af之后再按联接上的字母，要么没反应，要么就触发别的命令

**Comment by brookhong** [comment]
0.9.23已解决。

**Comment by dupontjoy** [comment]
多谢
