### ISSUE TITLE
FF中的某些网站使用'f'命令后输的的hint字符不被识别,会被当做新的命令

### ISSUE THREAD

**Issue by zzxqd** [brookhong/Surfingkeys#616]
目前在知乎就是这样
![default](https://user-images.githubusercontent.com/23022401/34088297-6ac4fd2c-e3e3-11e7-82aa-e0913d5674bd.png)

**Comment by zzxqd** [comment]
还有就是"T"命令切换tab便签在FF下也无法使用,出现hint之后输入的字符也是没被接受,直接就结束了这个命令,"t"可以使用

**Comment by brookhong** [comment]
duplicate issue of #615 
closed this one.
