### ISSUE TITLE
关于代理快速切换的问题

### ISSUE THREAD

**Issue by itgoyo** [brookhong/Surfingkeys#617]
之前的`spd`   `sps`这个快捷键去掉了，现在只能用命令行格式输入：`:set ProxyMode direct`这种操作了么，还是换成了别的什么快捷键。?中并没有看到

现在用是`switchy sharp`没有之前使用的快捷键好用

**Comment by brookhong** [comment]
并没有去掉，你直接按就是可以，只是它们的rich hints暂时没显示出来。

**Comment by itgoyo** [comment]
好的，谢谢
