### ISSUE TITLE
Firefox版, 输入框文字选中右键菜单出错

### ISSUE THREAD

**Issue by dupontjoy** [brookhong/Surfingkeys#618]
启用surfingkeys后, 输入框中文字选中后, 再点击右键, 选中状态消失, 导致右键菜单错误

启用surfingkeys:
![2](https://user-images.githubusercontent.com/4965288/34138375-1efcf1fc-e4aa-11e7-804f-d2118f6e4780.jpg)
禁用surfingkeys:
![3](https://user-images.githubusercontent.com/4965288/34138383-26ef8ff0-e4aa-11e7-8719-f8bbc8b05df1.jpg)

**Comment by zzxqd** [comment]
问一下,"T"切换标签的功能在你的FF运行正常吗?我的这里不管是FF还是chrome都不能切换

**Comment by dupontjoy** [comment]
@zzxqd 可以吧, 如图:
![1](https://user-images.githubusercontent.com/4965288/34187278-8a946d0c-e56b-11e7-911a-5b4a06a1dcaf.jpg)

**Comment by zzxqd** [comment]
能切换?我的hint也能出来,就是不能切换

**Comment by dupontjoy** [comment]
@zzxqd 可以切換

**Comment by zzxqd** [comment]
好吧,谢谢,我卸掉重装试试

**Comment by brookhong** [comment]
在设置里加入下面这行：

    settings.cursorAtEndOfInput = false;

**Comment by dupontjoy** [comment]
多谢
