### ISSUE TITLE
forbid capslock in chrome：禁用capslock

### ISSUE THREAD

**Issue by SUFisherman** [brookhong/Surfingkeys#620]
in order to write assembler i often open caps lock but forget to cancel it using surfingkeys in chrome,so i want to block it in chrome
我经常写汇编所以要用caps键，但切进chrome使用surfingkeys时经常忘记关闭。希望能加上禁止caps的功能

**Comment by brookhong** [comment]
这个没办法，Surfingkeys目前不检查CapsLock键，只是Surfingkeys的按键都是区分大小写的，也不太可能让Surfingkeys忽略大小写。
