### ISSUE TITLE
Couple of issues in Firefox

### ISSUE THREAD

**Issue by ivanddm** [brookhong/Surfingkeys#621]
I have been using your extension in Firefox recently, and although it works quite good, almost as good as in Chrome, I have noticed a couple of issues:

- Go to last used tab (`Ctrl-6`) is not working at all.
- Pinning/unpinning is not working either (`Alt-p`).
- When entering visual mode either with `v` or `zv` (especially `zv`), right after typing the hit keys the window scrolls up leaving the selection at the top of the page (sometimes even out of focus). In chrome, no scrolling takes place which I find it ideal.
- Only `select line` is working with `shift-v` but not `select sentence` or `select paragraph`. Also, `select line` only selects from the position of the cursor till the end of the line (in chrome it used to be the same but not anymore 👍).

Thanks again for your great work!

**Comment by ericdwang** [comment]
Concerning selecting sentences and paragraphs, it looks like Firefox unfortunately doesn't implement those granularities for modifying selections: https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify#Syntax
