### ISSUE TITLE
Front.getContentFromClipboard找不到了

### ISSUE THREAD

**Issue by lovemacs** [brookhong/Surfingkeys#622]
我有个定制类似：
mapkey('p', "Open the clipboard's URL in the current tab", function() {
    Front.getContentFromClipboard(function(response) {
        window.location.href = response.data;
    });
});

但是，最近发现Front.getContentFromClipboard这个方法现在怎么找不到了，我的定制都失效了

**Comment by liango2** [comment]
找到了，
 Clipboard.read(function(response) {

**Comment by brookhong** [comment]
Replace

    Front.getContentFromClipboard(function(response) {
    });

with

    Clipboard.read(function(response) {
    });

Replace

    Front.writeClipboard(text);

with

    Clipboard.write(text);
