### ISSUE TITLE
chrome浏览器里，Advanced mode 里面自己定制的js代码行数（貌似超过172行）太多会报错啊

### ISSUE THREAD

**Issue by liango2** [brookhong/Surfingkeys#623]
chrome浏览器里，Advanced mode 里面自己定制的js代码行数（貌似超过172行）太多会报错啊
报错如下：
![image](https://user-images.githubusercontent.com/5696817/34325865-6b1c077a-e8d9-11e7-894e-a654427b2a17.png)
已经确认了配置没有语法错，貌似不可以太多的配置吗？

**Comment by brookhong** [comment]
嗯，我的配置文件有654行，没有这个问题。
