### ISSUE TITLE
Problem w/ Mermaid Diagram Gen (calling from Surfingkeys ext menu)

### ISSUE THREAD

**Issue by rackstraw** [brookhong/Surfingkeys#624]
Click on Surfingkeys icon in Chrome, click on drop down, select Mermaid and get:

`Parse error on line 1: ./SurfingkeysDefault ^ Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'DOT'`

And none of the listed commands (for example ";f") have any effect.

**Comment by brookhong** [comment]
What's your Surfingkeys version?

Latest version 0.9.22 should work.

**Comment by PrestanceDesign** [comment]
Me too, I having the same error since some months.
My actual version 0.9.23.

**Comment by hzfmer** [comment]
The same error. My version if 0.9.43.

Besides, I know it's not related but it's not worthy of a new issue: 
On my Mac High Sierra, the `<Option - >` keyboard binding prints special characters instead of vim-style editing in **insert mode**.
Anyone has an idea of this?
