### ISSUE TITLE
How to navigate the tab while the page is loading如何在网页加载的时候也能切换标签

### ISSUE THREAD

**Issue by jackychao0226** [brookhong/Surfingkeys#625]
不好意思作者，非编程人员，好像issue不该这么用，帮助里实在没找到再来问的，用vimium也是有这个最大的痛点，我好像在pull里看到了Browser-wide tab navigation已经merge了，但是好像还是没用啊

**Comment by liango2** [comment]
我一直是按ctl-tab

**Comment by jackychao0226** [comment]
ctrl-tab知道，现在没办法也是用这个不过我是autohotkey设置成alt-s了，就是想surfingkey对标签的各种操作也能变成universal的，不然还是挺麻烦的，不过扩展的原理是不是一定要网页加载才能运行，不是很清楚

**Comment by brookhong** [comment]
只要页面开始加载，就可以切换了，不需要等到页面加载完成。

**Comment by jackychao0226** [comment]
我仔细试着看了一下，意思是不是左下角显示了网址正在响应之后网站响应了算开始加载，网站还没响应surfingkeys的快捷键是不能用的是吧？归根结底是我网速太渣连接，解析主机都得等。。如果是这样就close吧，谢谢。
