### ISSUE TITLE
How to rewrite settings were previously done through onAceVimKeymapInit

### ISSUE THREAD

**Issue by kalbasit** [brookhong/Surfingkeys#627]
Hello,

I have this in my [`.surfingkeys.js`](https://github.com/kalbasit/dotfiles/blob/2e7991e7fe3116a707d6599447380095a3a1346c/.surfingkeys.js.dtmpl#L177-L492) that uses `onAceVimKeymapInit()` to setup Ace editor bindings but that was removed in [here](https://github.com/brookhong/Surfingkeys/commit/f270a8bd0ab5058df355fb97c6051a2e36b879c5#diff-cad428a512d52f77b49a97dde3ee938cL238). How can I rewrite the settings to accomplish the same thing?

**Comment by brookhong** [comment]
use `addVimMapKey`, for example,

    addVimMapKey(
        {
            keys: 'n',
            type: 'motion',
            motion: 'moveByCharacters',
            motionArgs: {
                forward: false
            }
        },

        // down
        {
            keys: 'e',
            type: 'motion',
            motion: 'moveByLines',
            motionArgs: {
                forward: true,
                linewise: true
            }
        }
    );

**Comment by kalbasit** [comment]
That worked, thanks @brookhong
