### ISSUE TITLE
Show tab numbers

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#629]
Mmm I've read the docs and skimmed through the issues but I cannot figure it out how to actually show tab numbers (indices) in the tab titles. I've used to use chromium-vim where I had to explicitly enable this with the following setting:
```
set showtabindices
```
Is there a similar setting in surfingkeys? Thanks!!!

**Comment by brookhong** [comment]
New feature added in 0.9.23, please use below settings:

    settings.showTabIndices = true;

**Comment by petobens** [comment]
Thank you!! Now one last question: i would like to press `,3` and move to the third tab. I now I can do that with `3T` but I would like to do it with `,`. I tried the following mapping which doesn't work:
```
map(',3', '3T');
```
Is this doable? Thanks

**Comment by petobens** [comment]
ping @brookhong

**Comment by brookhong** [comment]
@petobens 

No. So far the map target could not contains prefix digits, `3` in your case.

**Comment by petobens** [comment]
Oh I see. Is this in the roadmap? Thank you for the quick reply.

**Comment by petobens** [comment]
@brookhong is this now possible with https://github.com/brookhong/Surfingkeys/issues/731?
