### ISSUE TITLE
regex for disabling (or just programmatic disabling on the page)

### ISSUE THREAD

**Issue by WuTheFWasThat** [brookhong/Surfingkeys#63]
I just found this extension and it's great!  there's one thing I miss, though, which is being able to specify a domain to disable on, rather than a page.  

I think I'd like a function which sets/toggles whether surfingKeys is active.  i.e. when called, it disables everything in surfingkeys except the hotkey to re-enable it.  It should be more or less whatever `Alt-s` is mapping to.  

ideally i could then write stuff in the configuration like
```
if (document.domain is in my whitelist of regexes) {
   disableSurfingKeys();
}
```

**Comment by brookhong** [comment]
Added it in https://github.com/brookhong/Surfingkeys/commit/ca4220ce4b3e677b02931fccbfd7229aec244e42

Please add setting as below

    settings.blacklistPattern = /.*somethingneedexcluded/i;

To delete the pattern:

    settings.blacklistPattern = undefined;

**Comment by WuTheFWasThat** [comment]
thanks!  this is good enough for my problem, which was wildcard subdomains.  but i do still think a list/function would be a bit nicer!

**Comment by HaleTom** [comment]
Is there a smart way to split this regex over multiple lines to blacklist more than one site?

**Comment by jaekyeom** [comment]
I agree with @HaleTom. We need settings.blacklistPattern**s**.

**Comment by HaleTom** [comment]
I'm using:
```
unmapAllExcept([], /\/todoist.com\//);
```
This can be used multiple times.

**Comment by lee-tts** [comment]
It's possible to string together multiple patterns using pipe | as a separator. I figured that out from this gist showing some kind soul's settings:

https://gist.github.com/thameera/8c846c48fd1c9f859cf602931e18a502

Their example:

`settings.blacklistPattern = /.*mail.google.com.*|.*inbox.google.com.*|trello.com|duolingo.com|youtube.com|udemy.com/i;`

**Comment by kalbasit** [comment]
@lee-tts this works because `settings.blacklistPattern` is nothing more than a [Javascript Regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

**Comment by sebastianst** [comment]
Shouldn't we also escape the `.`s?

**Comment by lee-tts** [comment]
Good point. It depends how explicit you want to be. There might be some edge cases where using `.` in place of `\.` might cause problems but I can't think of any off hand, given the limited scope of web URIs.

**Comment by LearnDifferent** [comment]
The setting is not working in version 1.0

**Comment by HaleTom** [comment]
Note that [this has changed to `blocklistPattern`](https://github.com/brookhong/Surfingkeys/issues/1581#issuecomment-1002608763)
