### ISSUE TITLE
Jump to second edit box and cycle between them

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#630]
I have two questions:

i) is there way to jump directly to the second edit box? I tried the following (which obviously doesn't work):
```javascript
mapkey('gI', 'Go to the second edit box', function() {
    Hints.create('input[type=text]:nth(1)', Hints.dispatchMouseClick);
});
```

ii) Can you show me how to cycle between edit boxes using `<TAB>` i.e if there are two edit boxes and i'm in the first one (in insert mode) i would like to press `<TAB>` and jump to next one.

Thanks!

**Comment by brookhong** [comment]
Press `gi`, then `<TAB>` will cycle through the edit boxes in view.

**Comment by petobens** [comment]
@brookhong thanks for your quick reply. What I meant was that, in a situation where you have two edit boxes and you are inside the first one in insert mode,  i would like to press `<TAB>` while in insert mode to jump to the second edit box (so for instance I can quickly fill out a form). Can this be achieved somehow?

Regarding my other question, is there a way to jump to the second input box (even if is not visible)? The use case is that in general the first input box is some sort of search field and I would like to avoid jumping to that one and instead go to the second one.

Thanks for the help

**Comment by brookhong** [comment]
Once you enter `insert` mode, `TAB` will work following browser's native behaviors, it won't move to next edit box certainly, may to next link/select/radio etc that has tab-stop.

To jump to the 2nd edit box, your script works for me. Did you see any error? or what does it do when you press `gI`?

**Comment by ericdwang** [comment]
I'm guessing that @petobens  has `settings.enableAutoFocus = false;` in his config because I noticed I wasn't able to cycle between inputs either with that. Looking through the code that seems unintentional though, so I pushed a small fix (hoping there's no side effects from removing that line).
