### ISSUE TITLE
pdf isn't displayed correctly

### ISSUE THREAD

**Issue by idosilverwater** [brookhong/Surfingkeys#634]
## Error details

The PDF viewer supplied with the extension doesn't display PDFs correctly. when i opened the PDF viewer it appeared blank, while I opened it in another and it worked perfectly

Other then that the extension is amazing!!

thanks a lot.

SurfingKeys: 0.9.23

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Looks like a duplicate issue of #591
