### ISSUE TITLE
`:quit` doesn't actually quit the application on Mac

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#635]
Running `:quit` doesn't actually exit Chrome/Firefox (it simply closes all windows). Can you add an option to actually exit the application? Thanks!

**Comment by brookhong** [comment]
No solution from this project for this issue.

Please see https://superuser.com/questions/53935/getting-mac-os-x-applications-to-close-after-last-window-closed

PS: `Command+q` is more convenient than `:quit` for me.

**Comment by petobens** [comment]
Ok. Thanks
