### ISSUE TITLE
Firefox版, 一些网站无法拖动

### ISSUE THREAD

**Issue by dupontjoy** [brookhong/Surfingkeys#636]
我发现的3个问题中, 目前只剩这一个问题未解决:
![3](https://user-images.githubusercontent.com/4965288/34657052-4b84c02a-f45d-11e7-8761-41b1af74b3db.jpg)

**Comment by brookhong** [comment]
能供一个相关的URL，用于重现这个问题？

我试了下google doc里拖拽没有问题。

**Comment by dupontjoy** [comment]
因为要账号登陆, 不方便公开贴出来
有没有邮箱, 我单独发给你

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/34704270-05a09c1a-f533-11e7-9a44-406d8b8ee19b.png)
加我微信吧。
