### ISSUE TITLE
Cannot edit text inputs or textareas on page load via tab key or custom script

### ISSUE THREAD

**Issue by cbejensen** [brookhong/Surfingkeys#639]
After a page initially loads, text inputs and textareas are not editable if I focus them via the tab key or a custom script unless I click somewhere on the page first. Also, even though they seem to have focus, the usual focus ring is not there. Note on the example below that a blue focus ring does show around other input elements (buttons and radios), but the text input and textarea do not receive input.

Example: https://codepen.io/cbejensen/full/RxQMrW/

If I use the `i` key to select an input, it does work. However, if I create a custom script that focuses a textarea or text input, it does not work.

Example script you can use in the above Codepen:
```javascript
mapkey('za', 'input focus test', () => {
  const input = document.querySelector('#text-input');
  if (input) {
    input.focus();
  } else {
    alert('No input found with an ID of #text-input');
  }
});
```

_Chrome - Version 63.0.3239.132 (Official Build) (64-bit)
Windows 10 (64 bit)_

**Comment by cbejensen** [comment]
I apologize, setting this seemed to resolve it:

`settings.stealFocusOnLoad = false;`

**Comment by cbejensen** [comment]
However, it seems like leaving the `stealFocusOnLoad` setting on should not prevent a script from being able to focus an input element.

**Comment by brookhong** [comment]
Please add below settings,

    settings.enableAutoFocus = true;

And refer to description for enableAutoFocus in https://github.com/brookhong/Surfingkeys#properties-list
