### ISSUE TITLE
Disable mapping when online hosted config cannot be parsed

### ISSUE THREAD

**Issue by balzss** [brookhong/Surfingkeys#642]
## Problem
I host my config file on github and currently it is going under some kind of maintenance  and the link for my raw config returns a 503 server error therefore surfingkeys tries to parse that html message and obviously fails so every time I want to open a page I get a popup: "unexpected symbol: <"

## Solution suggestion no.1:
Don't show a popup when the config cannot be parsed. Maybe do a console.log or change the color of the extension's icon.

## Solution suggestion no.2:
Disable config parsing when surfingkeys is disabled so when my config is unavailable I can just disable surfingkeys completely.

If you agree on any of the suggestions let me know and I'll submit a PR.

---

PS: Thanks for the awesome extension. I tried vimium and cvim before and wasn't satisfied. This one wins by a huge margin.

**Comment by brookhong** [comment]
Popup clearly warn users why their settings do not work, console.log / color change of icon may be ignored by users.

For Solution 2, if we skip user snippets on load when Surfingkeys is disabled, we need load user snippets whenever user turns on Surfingkeys later with `Alt-s`, which makes things complex.

What do you think of Solution 3 -- empty the `url` set by `Load settings from` when it is unavailable?
