### ISSUE TITLE
can't search in help

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#645]
It used to be possible to press `?` to bring up the SK help window and then `/` to search within it, but this is no longer the case; the `/` press does nothing.

**Comment by jaredbidlow** [comment]
the search input was hidden under the help section, so i had to zoom out first. is it covering the bottom of the window? then you need to zoom out first, but it would be better to have the search input be on top of the help section.

**Comment by aspiers** [comment]
The search input is definitely not just hidden for me, it is not there at all. If I try to search in the help regardless of any visual feedback, nothing happens.

**Comment by brookhong** [comment]
To make a slim frontend at https://github.com/brookhong/Surfingkeys/commit/f270a8bd0ab5058df355fb97c6051a2e36b879c5 ,
some default mappings have been removed from frontend UI including help popup, now `/` has been put back to frontend UI in 0.9.24.

Please try this in 0.9.24.

**Comment by aspiers** [comment]
Yes, it works again now. Thanks a lot!!
