### ISSUE TITLE
腾讯视频页面无法使用

### ISSUE THREAD

**Issue by haoxuexiaoyao** [brookhong/Surfingkeys#648]
## Error details

SurfingKeys: 0.9.24

Browser: oogle Chrome 已是最新版本 版本 63.0.3239.132（正式版本） （64 位）

URL: https://v.qq.com/

## Context

**腾讯视频页面无法使用,按F 键没有反应**

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/34912207-e2c8607e-f915-11e7-9298-74f3169d34a3.png)

我这没问题

**Comment by wch352136** [comment]
@brookhong   我估计他想问的是  视频的播放页面。  我以前没用过vim的工具，这个扩展是第一次用，我也又类似的疑问，怎么用这个扩展控制网页的的视频播放的呢，例如全屏，前进后退，音量大小（方向键在有的页面不起作用，另外方向键也不能控制全屏与否）。 举个例子，我在斗鱼，进入一个直播间，如果纯靠键盘把视频全屏。昨天试了半天没成功。

**Comment by Iy204** [comment]
@wch352136 这是网站支持的问题。斗鱼还在使用Flash自然不行。像其他视频网站配合启用HTML5脚本很容易做到你要的效果。alt+s 临时停用后用网站自己的设置快捷键就能全屏了。比如youtube是F，腾讯是回车。前进后退音量全屏后用方向键就随便调了。不停用也可以，操作要快点，不然有点网站控制界面隐藏后就不能操作了。
