### ISSUE TITLE
scrolling

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#65]
I cannot scroll correctly using the navigation keys (J,k.l,d, etc.) until I press the space bar a couple of times. this issue is not appearing to be happening on every page I visit, so I would like if someone else could say if they also have experienced it.

**Comment by wildtron** [comment]
In my experience, movement keys totally does not work..

**Comment by seletskiy** [comment]
Same issue. Scrolling via j/k feels broken, scroll offset just jump around.

**Comment by jaredbidlow** [comment]
closing because I was unknowingly using chrome's dev channel. Using stable, scrolling initializes on the page-load (I no longer have to manually scroll for surfingkeys scrolling keys to work).

**Comment by sivan** [comment]
I solve this problem by disable **Experimental Web Platform features** at chrome://flags/

**Comment by jaredbidlow** [comment]
That does allow scrolling with Surfingkeys. However, the issue I have very
often is that scrolling keys are not responsive until manual scroll of the
page occurs
