### ISSUE TITLE
first letter of double-character hints should default to same hand as "f" key

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#651]
Following links via `f` should be as quick as possible, since it's so common.  The default value for `Hints.characters` is a bit strange, because it only uses letters from one hand.  That means that if you have more than 13 links on a page, the hints will go into double characters straight away, which means an extra keystroke for each of these links.  So I configured my setttings with:

    Hints.characters = "asdfgqwertzxcvblkjhpouiymn";

Now the first 26 links are still single character, which is better.  However, now all the double-character hints start with either `n` or `m`, which is bad because they *all* require two hands (left hand types `f`, right hand types `n` or `m`, then either hand types the second character of the hint).  It would be better if the first letter of double-character hints was on the same hand  as the `f` key, so that hints like `aa`, `as`, `ad`, `af` etc. can all be typed with one hand.

**Comment by brookhong** [comment]
No, that is not doable.

When `a` is used for a link, then `aa`, `as` etc could not be used for other links, as whenever you press `a`, the link labelled with `a` will be hit, there is no chance for you press the following letter. Of course, we could introduce a timeout here, but that will make things complex.

The same for other letters.

And why `n` or `m` could be used for 2-letters hints? Because they are reserved for, there is no single-letter hint named `n` or `m`.

Thus if you prefer 2-letters hints to start with `a`, you could put `a` at end of `Hints.characters`, such as

    Hints.characters = "dfgqwertzxcvblkjhpouiymnas";

**Comment by aspiers** [comment]
Sorry for the slow reply.  I think you misunderstood what I was asking for ...

[**@brookhong**](https://github.com/brookhong) commented on [24 Jan 2018, 04:59 GMT](https://github.com/brookhong/Surfingkeys/issues/651#issuecomment-360021202 "2018-01-24T04:59:03Z - Replied by Github Reply Comments"):
> No, that is not doable.

It is - you gave me the answer below :-)

> When `a` is used for a link, then `aa`, `as` etc could not be used for other links, as whenever you press `a`, the link labelled with `a` will be hit, there is no chance for you press the following letter. Of course, we could introduce a timeout here, but that will make things complex.

I know that, but I'm not asking for `a` to be used both as a 1-letter link *and* a prefix to 2-letter links.

> Thus if you prefer 2-letters hints to start with `a`, you could put `a` at end of `Hints.characters`, such as
> 
>     Hints.characters = "dfgqwertzxcvblkjhpouiymnas";

Ahah!  So you are saying that the last few letters of this string are the ones which will be used as prefixes when prefixes are required?  I've tried this and it seems to work - thanks!  I think it would be worth documenting it.

**Comment by aspiers** [comment]
Thanks for documenting!  I think this is resolved now :sunglasses:

**Comment by lee-tts** [comment]
For some reason I couldn't get this to turn into a proper PR though. Complete Github noob haha (although I've created PRs in the past ... this one just took me around in circles so I must have done something wrong.)
