### ISSUE TITLE
如何设置链接字母的透明度

### ISSUE THREAD

**Issue by wch352136** [brookhong/Surfingkeys#653]
有个问题想请教一下，就是如何设置f键呼出的拨号字母的透明度？尤其是在一些链接密集的页面上拨号字母已经完全遮挡了我想要跳转的链接，这时候就只能关闭拨号然后再重新确认想要跳转链接的位置，挺麻烦的，然后我在设置里面发现好像只能设置主题的透明度，对于拨号界面好像没有设置（小白，基本上看不懂代码，如果我看错了，请勿喷）。

![snipaste_2018-01-20_17-41-28](https://user-images.githubusercontent.com/17609338/35182093-2fc609f6-fe09-11e7-8cdb-f91a8ad811a2.png)

**Comment by brookhong** [comment]
你可以按空格键暂时隐藏所有的拨号字母，松开空格即恢复。修改透明度并不能解决问题，你如果想试试，可以在设置里加入下面的代码：

    Hints.style("opacity: 0.6");

**Comment by wch352136** [comment]
哦原来是有快捷键暂时隐藏拨号字母的啊，明白了，这也是解决的办法，另外我试了试第二种方法发现确实不能解决问题，所以用第一种，谢谢。
