### ISSUE TITLE
能否（如何）增加查看Tab History的命令等……

### ISSUE THREAD

**Issue by av2000ii** [brookhong/Surfingkeys#66]
您好
1，能否（如何，请麻烦告诉我）增加查看Tab History（带有显示在tab上的title，而不仅仅是url【在cvim上只能显示tab history的url】）的命令，如果将这项功能合并至omnibar或许也是不错的。
2，另外Surfingkeys当前如果使用命令“f”，后如果不想选取链接只能通过按Esc键取消，这颗键比较不顺手，能否自定义至其他键盘上不常用的键。
3，能否提供其他方便的途径获取surfingkeys，例如增加打包后的zip文件。谢谢

**Comment by av2000ii** [comment]
谢谢，最近在使用0.5.3的surfingkeys，发现了拨号功能的提示符在有许多链接的页面会出现显示较慢的情况，而cvim和vimium相比之下会快些。本人小白，所以来问问，是这两款扩展实现此功能的方式不一样造成的吗？

**Comment by brookhong** [comment]
![bad_performance_jquery](https://cloud.githubusercontent.com/assets/288207/17324583/d60711ba-58d9-11e6-806e-fc4342953291.png)

**Comment by av2000ii** [comment]
1.Surfingkeys在使用 f 遇到两个相叠的 Hint 情况时，好像就有问题了，cvim的做法是按Alt键能够交换两个相叠 Hint 的位置。类似功能我没有在0.5.4的版本的帮助中发现。
2.Surfingkeys的拨号功能能否通过按下不属于 Hint 里的字符（例如默认的是sadfjklewcmpgh，那么当按下;时因不属于默认的字符，则退出拨号，cvim是这样设计的）来退出拨号功能。

**Comment by brookhong** [comment]
谢谢，你的建议很好。

**Comment by brookhong** [comment]
以上功能在0.5.5中发布了，但交换重叠hint的按键是`Shift`。
