### ISSUE TITLE
opening links

### ISSUE THREAD

**Issue by idosilverwater** [brookhong/Surfingkeys#665]
In other vim like extensions, the keys used to follow links are from the home row.
in this one the keys are usually not from the home row, which makes it harder and slower... 
is it possible to make the hints use only home row keys?

**Comment by keenahn** [comment]
make this a configurable option please.

**Comment by keenahn** [comment]
Actually I solved my own problem. You can set the hint keys using

`Hints.characters = 'asdfjkl;'` 

etc
