### ISSUE TITLE
如何加一个快捷键可以直接用Chrome自带的翻译页面

### ISSUE THREAD

**Issue by richarduncle** [brookhong/Surfingkeys#673]
chrome浏览器翻译页面好像没有快捷键，怎么用Surfingkeys设置一个快捷键啊？求大神指导

**Comment by KhaosChow** [comment]
在chrome内按菜单键，出现右键菜单，然后再按T就会翻译了。菜单键是在键盘右边Alt、Ctrl那块区域[https://zh.wikipedia.org/zh-hans/%E8%8F%9C%E5%8D%95%E9%94%AE](url)

**Comment by richarduncle** [comment]
我用的mac电脑，好像没有这个键。

**Comment by KhaosChow** [comment]
好吧。。。我把这茬给忘了。

**Comment by richarduncle** [comment]
就是因为mac没有这个键，所以才想用surfingkeys里面自定义一个，但是不知道怎么弄。

**Comment by KromaLee** [comment]
> 在chrome内按菜单键，出现右键菜单，然后再按T就会翻译了。菜单键是在键盘右边Alt、Ctrl那块区域https://zh.wikipedia.org/zh-hans/%E8%8F%9C%E5%8D%95%E9%94%AE

我想在源语言和目标语言之间切换,不用键盘做不到--有什么好招吗?

**Comment by Justgogoal** [comment]
同求，不知道如何自定义。

**Comment by wangboak** [comment]
> > 在chrome内按菜单键，出现右键菜单，然后再按T就会翻译了。菜单键是在键盘右边Alt、Ctrl那块区域https://zh.wikipedia.org/zh-hans/%E8%8F%9C%E5%8D%95%E9%94%AE
> 
> 我想在源语言和目标语言之间切换,不用键盘做不到--有什么好招吗?

你好，请问你找到在MAC下的解决方案了吗？我也是想找到一个快捷键（然后映射到我的鼠标自定义按键上），实现一键翻译和切换原文。

**Comment by yulingao** [comment]
我有同样的问题

**Comment by 1024zzq** [comment]
同问题，看了扩展插件，想绑定。没有翻译的选项

**Comment by 1024zzq** [comment]
现在都是鼠标右键+T

**Comment by Zero-Yi7** [comment]
我也想知道，应该如何实现一键翻译和切换原文

**Comment by Pankaipeng** [comment]
我发现沙拉查词有这个功能，不过在部分网页会禁用脚本，你看能不能帮到你@Alphabet1226
![image](https://user-images.githubusercontent.com/37923136/230342493-98e4c962-a7ef-41d0-8013-eccad7da6782.png)

**Comment by chenqing145** [comment]
> > 我发现沙拉查词有这个功能，不过在部分网页会禁用脚本，你看能不能帮到你@Alphabet1226 ![图像](https://user-images.githubusercontent.com/37923136/230342493-98e4c962-a7ef-41d0-8013-eccad7da6782.png)
> 
> ❤️谢谢！用了这么久的沙拉查词，才发现还有这个小功能！
已经不能用了  显示无法加载

**Comment by threecha** [comment]
原来大家都有相同的困惑

**Comment by kele527** [comment]
为什么谷歌官方不支持一下

**Comment by zzq8** [comment]
> 现在都是鼠标右键+T

Google插件 沉浸式翻译   超好用

**Comment by Inspector-DAI** [comment]
> > > 我发现沙拉查词有这个功能，不过在部分网页会禁用脚本，你看能不能帮到你@Alphabet1226 ![图像](https://user-images.githubusercontent.com/37923136/230342493-98e4c962-a7ef-41d0-8013-eccad7da6782.png)
> > 
> > 
> > ❤️谢谢！用了这么久的沙拉查词，才发现还有这个小功能！
> > 已经不能用了  显示无法加载

请问是在哪个页面的设置，没有看到呢

**Comment by feiazifeiazi** [comment]
现在都是鼠标右键+T

**Comment by eokoo** [comment]
![Image](https://github.com/user-attachments/assets/3eedcdc4-1fb2-4bc7-a6a7-2cc68288e14e)

看来大家都有这个问题，第三方扩展也用过效果参差不齐，有点位置还翻译不了，我来贡献一个自用的终极chrome内置翻译快捷键脚本，脚本需要安装autohotkey软件即可，实现功能如下，按alt+1时翻译网页为中文，再次按下alt+1时切换回原文，可自行更改快捷键，切换回原文是利用autohotkey屏幕捕捉点击的，我的屏幕是4K，chrome最大化后英文位置固定才起作用，可自行替换【英文】按钮像素xy位置（ps之类的截全屏查看按钮位置），代码如下：

#SingleInstance Force ; 确保脚本只运行一个实例
#IfWinActive ahk_exe chrome.exe ; 只在 Chrome 窗口激活时生效

; 定义一个变量来跟踪 Alt+1 的按次，0 表示奇数次，1 表示偶数次
global toggleState := 0

!1:: ; Alt+1 触发
{
    Send "{Shift down}{F10}{Shift up}"
    Sleep 100
    Send "t"
}

if (toggleState = 1) { ; 如果是偶数次按下
    CoordMode, Mouse, Screen ; 设置鼠标坐标模式为屏幕绝对坐标
    MouseMove, 2980, 200, 0 ; 移动到屏幕绝对坐标 (x: 2980, y: 200)
    Sleep, 200 ; 等待鼠标移动到位
    Click, Left ; 点击恢复到原始语言
    Sleep, 1000 ; 等待页面恢复
    MouseMove, %xpos%, %ypos%, 0 ; 将鼠标移回原来位置
    toggleState := 0 ; 重置为奇数次
} else { ; 如果是奇数次按下
    toggleState := 1 ; 设置为偶数次
}
return

#IfWinActive ; 结束特定窗口的条件

**Comment by Y2N95** [comment]
> chrome浏览器翻译页面希望没有快捷键，怎么用Surfingkeys设置一个快捷键啊？求大神指导

ctrl+r

**Comment by LZSYSTEMl** [comment]
Application（或者鼠标右键）+T是Google翻译快捷键，Ctrl+Tab是语言切换快捷键，我叫AI在GHUB上写了一个lua文件，调用两个组合键宏，可以实现一键翻译并且一键切换
————————————————
EnablePrimaryMouseButtonEvents(true)

-- 状态变量：0=初始, 1=切换模式
local cycle_state = 0

--[[
  防抖功能变量：
  last_press_time: 记录上一次有效按键的时间戳。
  debounce_delay:  防抖延迟，单位毫秒。50毫秒足以过滤掉绝大多数物理抖动。
--]]
local last_press_time = 0
local debounce_delay = 50

function OnEvent(event, arg)
  
  -- 检查事件是否为“鼠标按键按下”
  if (event == "MOUSE_BUTTON_PRESSED") then
    
    -- 条件一：如果按下的是按键 G8
    if (arg == 8) then
      
      ------------------- 防抖判断 -------------------
      local current_time = GetRunningTime()
      if (current_time - last_press_time < debounce_delay) then
        OutputLogMessage("防抖：已忽略一次过快的点击。\n")
        return -- 直接退出函数
      end
      last_press_time = current_time
      ----------------------------------------------------------
      
      -- 执行状态机逻辑
      if (cycle_state == 0) then
        OutputLogMessage("首次点击: 执行 'Google翻译'。\n")
        PlayMacro("Google翻译")
        cycle_state = 1 -- 进入切换模式
        
      elseif (cycle_state == 1) then
        OutputLogMessage("后续点击: 执行 '翻译切换'。\n")
        PlayMacro("语言切换")
        -- 状态保持在 1，以便连续切换
      end
      
    -- 条件二：如果按下的不是按键 G8 
    else
      if (cycle_state ~= 0) then
        OutputLogMessage("非8键点击，循环已重置。\n")
        cycle_state = 0 -- 重置回初始状态
      end
    end
    
  end
  
end
————————————————
