### ISSUE TITLE
[bug] wrong map key

### ISSUE THREAD

**Issue by Cologler** [brookhong/Surfingkeys#679]
I try to use `imapkey('<Shift-Alt-f>', 'Insert DateTime', ...)` to map some function, but it become

<img width="189" alt="snipaste_2018-02-20_16-24-37" src="https://user-images.githubusercontent.com/10906962/36413727-9a602684-165a-11e8-8757-cf7717edca67.png">

**Comment by brookhong** [comment]
Please use `<Alt-F>`, for example,

    mapkey('<Alt-F>', 'test', function() {
        Front.showBanner("abff");
    });
