### ISSUE TITLE
open url in current tab

### ISSUE THREAD

**Issue by kovetskiy** [brookhong/Surfingkeys#68]
Hi, thanks for the great plugin, but I've noticed that I can't open link (like `t`) in current tab without creating new.

I've tried passed `tabbed: false`, but it didn't help:
```
mapkey('o', '', function() {
    Normal.openOmnibar({
        type: "URLs",
        extra: "getTopSites",
        tab: {
            tabbed: false
        },
        position: runtime.settings.newTabPosition,
    })
})
```

**Comment by brookhong** [comment]
Thanks for reporting the issue.

Fixed in 0.5.3.

**Comment by brookhong** [comment]
mapkey('o', '#8Open an URL in current tab', 'Normal.openOmnibar({type: "URLs", extra: "getTopSites", tabbed: false})');

**Comment by kovetskiy** [comment]
@brookhong thanks!

**Comment by gynet** [comment]
Seems not working now @brookhong
