### ISSUE TITLE
[Bug ?] The window closes when you right-click.

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#680]
If you select the text inside the textarea tag and click the right mouse button (to copy), the window closes.

**Comment by ligyxy** [comment]
It has different behavior for me. When selecting text in textarea, right-click on the text will limit the highlight text to one word.
Example: https://cl.ly/1u2138040v1L

It is like this on my Mac and Windows, so I am wondering if it's a feature, although I don't have any mouse clicking related setting.

**Comment by liutf** [comment]
I had the same problem.

**Comment by brookhong** [comment]
SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Not seeing this issue.
![aa](https://user-images.githubusercontent.com/288207/38170524-62ce7a0c-35ba-11e8-9ba5-da2511dc62d5.gif)

**Comment by D1mon** [comment]
Now he's working for me. Apparently after updating the browser.
