### ISSUE TITLE
Slow when there are too many tabs

### ISSUE THREAD

**Issue by jaekyeom** [brookhong/Surfingkeys#687]
## Error details

SurfingKeys: 0.9.26

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

URL: https://www.reddit.com

## Context

I currently have a few hundreds (around 350) of tabs. Yes, it's quite a lot, but many of them are swapped out by [The Great Suspender](https://chrome.google.com/webstore/detail/klbibkeccnjlkjkiokjodocebajanakg).

I used to be a Vimium user, but recently switched to Surfingkeys. This extension is excellent, but one issue I'm having is that it is pretty slow given that there exists a large number of tabs.

For instance, if I press `x` to close a tab, it takes about 1 second on average. Pressing `T` takes ~3 seconds to display the UI. Sometimes, it takes about 3 seconds for it to open a new tab as a result of pressing `on`.

The reason I think that it has something to do with the number of tabs is that on the same machine, using Surfingkeys in a new Chrome user while leaving the tabs of the original user open, is perfectly fine. Also, I tried profiling the background page of Surfingkeys, and it seemed very busy when I was doing some actions in each tab. Granted that I have no knowledge about Surfingkeys' internal structure, but maybe the background page can be the bottleneck..?

Thank you.

**Comment by brookhong** [comment]
I have made some improvements in 0.9.54, such as
* create ui frame only for active tab to reduce memory usage
* deprecate long-live ports for message passing

Please have a try, and let me know if it works for you.
