### ISSUE TITLE
Speed up and slow down shortcuts not passing through

### ISSUE THREAD

**Issue by bhajneet** [brookhong/Surfingkeys#69]
Fullscreen YouTube

Shift + > or <

**Comment by brookhong** [comment]
I tested, Shift + > or  < works fine on fullscreen YouTube.

**Comment by bhajneet** [comment]
I cannot get it to work on Linux
Google Chrome Version 53.0.2785.8 dev (64-bit)

Another thing that won't work is typing in "dropdown" boxes. For instance when choosing your state for billing info, try a state starting with "M" and you'll set a mark with the next character.

Lastly cannot even disable the extension from the menubar, have to go into extensions to manually uncheck the extension.

Could be my system, I suppose. Can you help me figure it out?

**Comment by brookhong** [comment]
For your case on YouTube, please make  sure cursor focus on background instead of any element that accept input like `input`/`select` etc.

For typing in drop down, please make sure cursor focus on the element, which should be `select` instead of  background.

**Comment by bhajneet** [comment]
Went to youtube, opened a video using mouse, clicked twice on background to pause and replay, tried shortcuts, verified on cog icon. No change in speed for linux.

Tried to reproduce on windows canary build as well. Couldn't even get it to work on that one. Will re-test with stable chrome.

"Disabling" extension didn't work (or didn't communicate a toggle) using the menubar icon in either Windows/Linux.

Tried a dropdown using this site: http://semantic-ui.com/modules/dropdown.html

Picked first one for "gender" and tried to type "ma" with the mouse ontop of the input. No go. Will post again testing chrome stable.

**Comment by bhajneet** [comment]
Re-tested & unworking in Linux, Chrome Stable Version 51.0.2704.106 (64-bit)

**Comment by bhajneet** [comment]
Re-tested and unworking in Win 10, Chrome Stable Version 51.0.2704.103 m

Will re-try with new version of chrome stable...

**Comment by bhajneet** [comment]
Re-tested and both working and unworking in Win 10, Chrome Stable Version 51.0.2704.106 m

Youtube -- Unworking
Dropdown -- Working (had to use this site: http://lab.artlung.com/50states/ to test a state starting with 'm')

**Comment by brookhong** [comment]
I thought you were meaning `Shift` + `Left Arrow` or `Right Arrow`.

If you mean the greater-than / less than sign on keyboard, you have to add below in your settings:

    unmap("<<", /youtube.com/);
    unmap(">>", /youtube.com/);
