### ISSUE TITLE
cant remap "h" key

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#691]
```js
unmap('h')
mapkey('h', 'backward', 'history.go (-1)')
```
This worked in the past, but stopped working one day
Now, this just popups the letter `h` in the bottom right of the browser

**Comment by brookhong** [comment]
use

    mapkey('h', 'backward', function() {history.go (-1);});

instead, please refer to https://github.com/brookhong/Surfingkeys/blob/master/pages/changelog.md#0919
