### ISSUE TITLE
【功能建议】保存和跳转阅读进度

### ISSUE THREAD

**Issue by LongerPro** [brookhong/Surfingkeys#697]
## 建议描述
在浏览网页时，可能会出现一处或多处需要联系上下文理解的内容，这时候就需要在多个位置之间来回跳转，而不是慢慢翻页再瞪大眼寻找。

## 功能参考
vimium 中有该功能，使用方法为：m+按键 添加新的 mark， `+按键 跳转到对应的 mark。

**Comment by brookhong** [comment]
请阅读https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E7%B1%BBvim%E6%A0%87%E7%A4%BA
