### ISSUE TITLE
掘金插件页无法使用

### ISSUE THREAD

**Issue by liutf** [brookhong/Surfingkeys#698]
* 问题描述
在插件 [掘金-Chrome](https://chrome.google.com/webstore/detail/%E6%8E%98%E9%87%91/lecdifefmmfjnjjinhaennhdlmcaeeeb) 中无法使用神器`SK`
![](http://p2oheco53.bkt.clouddn.com/201803141431_804.png)

* 期望
可以在此页面中使用`SK` 或者想知道能做得到的吗？

**Comment by ffplayer** [comment]
https://github.com/brookhong/Surfingkeys/issues/421
参考我之前问过的问题，唯一的办法就是用作者编译的chromium，我目前在用

**Comment by brookhong** [comment]
是的，请看https://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages-cn.html

**Comment by liutf** [comment]
好的， 多谢。

 我试了下，要是能用键盘控制下拉就好了。
