### ISSUE TITLE
[Bug?]Chrome中 'Ctrl + x'  剪切却关闭窗口了

### ISSUE THREAD

**Issue by liutf** [brookhong/Surfingkeys#699]
* 问题
  Win10中在Chrome里，输入框中对文本进行剪切（`Ctrl+x`）操作， 结果把窗口关闭了。做了`x` 操作。
关闭掉`Surfingkeys` 插件，剪切正常。 

* 版本
```
版本： 0.9.26
最后更新日期： 2018年2月2日
```

```
Google Chrome 已是最新版本
版本 65.0.3325.162（正式版本） （64 位）
```

-------------------------

Surfingkeys: 0.9.29
Chrome: 65.0.3325.181

 也是一样问题。

为何在我的Chrome中按`Ctrl + x` 却执行了 `SK `的`x`操作？

**Comment by liutf** [comment]
请问下作者这个问题可以解决吗？等了很久了。

  真的非常影响使用！

**Comment by brookhong** [comment]
我试了几次都没有问题啊

Surfingkeys: 0.9.29
Chrome: 65.0.3325.181

**Comment by liutf** [comment]
:joy:  
我在两个同事的电脑机器上也都没问题。

可是我在公司的电脑和家里电脑的Chrome都有同一个问题困扰着。。

请问下大佬有什么解决办法吗？印象中我貌似是更新了Chrome到64后开始才有这个问题的。:sob:

**Comment by liutf** [comment]
卸载掉Chrome和Surfingkeys，清掉缓存等文件。重新安装Chrome和Surfingkeys就好了！:triumph::sob::smiley:
