### ISSUE TITLE
Missing documentation on settings.blacklist

### ISSUE THREAD

**Issue by seletskiy** [brookhong/Surfingkeys#70]
Can you, please, add documentation about adding sites to the blacklist? I can't find it in the README.md.

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys

When Surfingkeys is turned off on some site by `Alt-s`, the status will be persisted in settings, for example,

    "blacklist": {
        "https://github.com": 1
    },

`Alt-s` once more will remove it from settings.blacklist. By the way, `yj` to dump all settings into clipboard.

Another way to disable Surfingkeys is to use `settings.blacklistPattern`, please refer to [regex for disabling](https://github.com/brookhong/Surfingkeys/issues/63).

**Comment by seletskiy** [comment]
@brookhong: Great, thanks!
