### ISSUE TITLE
选择模式下Google翻译 ;t 和查找功能冲突

### ISSUE THREAD

**Issue by Leoongithub** [brookhong/Surfingkeys#700]

**Comment by brookhong** [comment]
`;t`只在normal模式下有效，如果你在visual模式需要同样的功能，可以增加如下设置：

    vmapkey('<Space>', 'Translate selected text with google', function() {
        searchSelectedWith('https://translate.google.com/?hl=en#auto/en/', false, false, '');
    });

这样按空格就是翻译选中文本。在visual模式下，`;`已经用于`Repeat latest f, F`，所以你不能再映射到任何`;`开头的组合了。
