### ISSUE TITLE
打开自定义搜索引擎bug

### ISSUE THREAD

**Issue by chenbin11200** [brookhong/Surfingkeys#701]
在firefox 59下，
假设按照readme这样写：
addSearchAliasX('s', 'stackoverflow', 'http://stackoverflow.com/search?q=', 's');

快捷键ss可以直接搜索选中文字内容，但是os不能打开stackoverflow快速搜索框。

进一步测试：
addSearchAliasX('w', 'stackoverflow', 'http://stackoverflow.com/search?q=', 's');
此时sw，ow均正常。

进过测试，只有g，b，w这三个快捷键，打开空的快速搜索框（o+自定义搜索引擎别名）正常，别的都不能用。

**Comment by brookhong** [comment]
o+自定义搜索引擎别名不是默认支持的，g/b/w这个能用，是因为默认设置里有

    mapkey('ob', '#8Open Search with alias b', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "b"});
    });
    mapkey('og', '#8Open Search with alias g', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "g"});
    });
    mapkey('ow', '#8Open Search with alias w', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "w"});
    });

使用自定义搜索引擎除了使用`s+自定义搜索引擎别名`，其它的姿势就是`t`打开搜索栏，在搜索栏里使用别名+空格。

如果一定需要o+自定义搜索引擎别名，可以按照上面的代码自行设置。

**Comment by chenbin11200** [comment]
了解了，谢谢！测试可用。你觉得把这段map og 的内容加入addSearchAliasX是不是个好主意呢？如果你觉得不错，我可以回头fork一下。

**Comment by brookhong** [comment]
最开始之所以不自动绑定`o+自定义搜索引擎别名`，就是怕意外的覆盖了用户自己`o`开头的绑定，所以还是不加了。
