### ISSUE TITLE
copy broken in settings editor

### ISSUE THREAD

**Issue by nkkPb** [brookhong/Surfingkeys#708]
while cut and paste work as expected in insert mode in settings editor, copy does not.

**Comment by brookhong** [comment]
Please provide your browser / OS versions.

You could report issue by clicking dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.

**Comment by nkkPb** [comment]
SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3386.1 Safari/537.36

issue exists on the firefox version of SurfingKeys as well.

**Comment by tsaber** [comment]
Version 66.0.3359.170 (Official Build) Arch Linux (64-bit)

same issue on chromium
