### ISSUE TITLE
jianshu.com

### ISSUE THREAD

**Issue by rainplus** [brookhong/Surfingkeys#709]
## Error details
jianshu.com  chrome 无法使用,突然不可用，应该不是我设置了什么吧。印象中也没有单独可以设置某个网站不生效。

SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
你看看工具栏里`Surfingkeys`的图标在jianshu.com的标签页是不是灰的？
应该是你不小心在jianshu.com的页面按了`Alt-s`，请查看https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E5%BC%80%E5%85%B3%E7%83%AD%E9%94%AE

`单独可以设置某个网站不生效`的功能从0.0.1版本开始就有，热键`Alt-s`。

**Comment by rainplus** [comment]
是的，谢谢。一直没有发现
