### ISSUE TITLE
Binding Ctrl-[ to Escape

### ISSUE THREAD

**Issue by uandrews** [brookhong/Surfingkeys#71]
I cannot set an alternative key combination to avoid having to reach the escape key.  I would like to bind Ctrl-[ to Escape, but map doesn't seem to allow this with `map('<Ctrl-l>', '<Esc>');` .  Is this possible already and if not can it be implemented in the future.

**Comment by brookhong** [comment]
`Esc` is kind of special, will think about it in future.

**Comment by brookhong** [comment]
With this commit https://github.com/brookhong/Surfingkeys/commit/1fb35b0992933fa142e69a812b04015d71e78d35, below line works

    map('<Ctrl-l>', '<Esc>');

Will be released in next version.

**Comment by brookhong** [comment]
Released in 0.5.4.
