### ISSUE TITLE
Positioning containing element at top of viewport after using / to search is sometimes problematic

### ISSUE THREAD

**Issue by ghost** [brookhong/Surfingkeys#710]
Here is a test case, using Firefox 59.0.2 and Surfingkeys 0.9.28:

1. Visit https://perldoc.perl.org/perlre.html
2. Press / then search for any word that the document contains but is not yet visible in the viewport, such as "scalar"
3. Observe that, for each match, the text is invisible, while the highlight/caret remain visible

The reason for this is that the document uses a fixed content header:

```css
#content_header {
	position: fixed;
	background-image: url(content_bg.png);
	top: 0;
	width: 731px;
	height: 85px;
	z-index: 1;
}
```

Thus, `content_bg.png` masks out the top-most 85 pixels of content within `#centre_column`.

Strictly speaking, Surfingkeys isn't doing anything wrong. However, because Surfingkeys scrolls to the first match in such a way that it is positioned exactly at the top of the viewport, the matching element ends up being hidden beneath `#content_header`, whereas Surfingkey's highlight and caret are rendered above it. This looks very odd to the user.

Using the native Ctrl/Cmd+F search in Firefox does not run into this problem, because - if it has to scroll the viewport - it positions the matching element in the vertical centre of the viewport (imagine running `/` followed by `zz`). This same behaviour also means that other extensions, such as Vimium, do not run into the same problem.

**Comment by brookhong** [comment]
Thanks for reporting this, same issue as #706

**Comment by maxigaz** [comment]
I can reproduce the same issue with Surfingkeys 0.9.43 and Firefox 66.0.3.

Similarly to the webpage mentioned by OP, when I go to a FANDOM site (such as [Wookieepedia](https://starwars.fandom.com/wiki/Main_Page)) the highlighted word is "hidden" under the navbar on top.
