### ISSUE TITLE
key<Q>, translation fail to esc

### ISSUE THREAD

**Issue by iitzex** [brookhong/Surfingkeys#711]
After playing voice, ESC failed to escape omnibar.

**Comment by brookhong** [comment]
Please provide your browser / OS versions.

You could report issue by clicking dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.

**Comment by iitzex** [comment]
SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/39614555-6048977e-4fa3-11e8-8476-46203af7c4d6.png)
