### ISSUE TITLE
Content security policy allows https://www.google-analytics.com/analytics.js in mainfest.json

### ISSUE THREAD

**Issue by nkkPb** [brookhong/Surfingkeys#712]
Is there a reason why the extension can load scripts from google analytics (content-security-policy meta-tag in manifest)?

**Comment by brookhong** [comment]
That is for analysis of feature preferences, such as how many people would like start page, or using built-in pdf viewer.

Please see:

https://github.com/brookhong/Surfingkeys/blob/master/pages/ga.js
https://github.com/brookhong/Surfingkeys/blob/master/pages/start.html#L55
https://github.com/brookhong/Surfingkeys/blob/master/pages/pdf_viewer.html#L330

**Comment by nkkPb** [comment]
thanks for the response. I understand. It would make the extension more transparent if these information was stated somewhere in the readme. Also I would prefer this to be an opt in feature as well.
