### ISSUE TITLE
Incompatible with Google Docs, please considering add Whitelist to SurfingKeys

### ISSUE THREAD

**Issue by leo-mao** [brookhong/Surfingkeys#717]
## Error details

SurfingKeys regards all input as commands when editing Google Docs online. 
In this case, a user cannot type anything to Google Docs unless turning off SurfingKeys.

**Please considering add Whitelist to SurfingKeys**

SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

URL: [Testdoc for Surfingkeys](https://docs.google.com/document/d/1FXiV1NdT2cLHHvnwdau-H7FtJwZ4AFjQ2DqfbuoDCYY/edit)

**Comment by brookhong** [comment]
This is a Firefox-only issue, please use `Alt-s` to turn Surfingkeys off on google docs.

https://github.com/brookhong/Surfingkeys#hotkey-to-toggle-surfingkeys

**Comment by leo-mao** [comment]
Thanks for quick reply.
