### ISSUE TITLE
Feature request: save proxy setting and config setting in $HOME/.config/surfingkeys folder by default

### ISSUE THREAD

**Issue by QiangF** [brookhong/Surfingkeys#718]

**Comment by sebastianst** [comment]
Exactly what I just wanted to request :) I share my config among different machines and browsers and would like to keep them synchronized with my other dot files via git.

**Comment by brookhong** [comment]
This is not doable, as Chrome extension has no permission to write local file.

**Comment by QiangF** [comment]
If extension can read from local file, what about a work around:

    1. check if the config file exist in local system
    2. if it exist use it.
    3. else use the default one
