### ISSUE TITLE
createSession does nothing

### ISSUE THREAD

**Issue by brandenbyers** [brookhong/Surfingkeys#72]
When using `createSession <session-name>`, nothing happens. When I enter `listSession` afterwards, the only session that is listed is `LAST` from the last time I used `ZZ`.

**Comment by brookhong** [comment]
Thanks for reporting this issue.

Fixed, will be released in next version.

**Comment by yardsale8** [comment]
I am running into the same issue.  Each time I create a session nothing happens and listSession is empty after the fact.  I am having the same issue with marks, ma doesn't appear to do anything and 'a does nothing after the fact.  Is there a global chrome setting that I need to change to allow these items to change?
