### ISSUE TITLE
Firefox下QQ邮箱在写信时不会进入插入模式

### ISSUE THREAD

**Issue by duguyipiao** [brookhong/Surfingkeys#721]
Firefox下QQ邮箱在写信时不会进入插入模式，只能暂时停用Surfingkeys，但chrome下似乎是正常的，不知道是有解决方案？

Firefox 59.0.2, Surfingkeys 0.9.29

**Comment by brookhong** [comment]
#717 
按`Alt-s`在qq邮箱禁用Surfingkeys，再次`Alt-s`打开Surfingkeys.

**Comment by duguyipiao** [comment]
额...我一直是用`Alt-s`临时禁用的，只是想能不能像chrome一样可以自动进入插入模式，看来是firefox本身的问题了。
