### ISSUE TITLE
Is there a way to define your own commands?

### ISSUE THREAD

**Issue by sandric** [brookhong/Surfingkeys#723]
I would like to define my own js commands, but struggling to find how to do this. I found `frontend.js` in `pages` directory, and see how commands implemented there - through simple calls to `command` js function. But that `command` function is not available inside my local config, I got error alert noticing that. If I copy/paste `command` function definition I then getting error that `Commands` array is not defined, its used in that function and as I understand its global.

What am I missing, is it allowed? It seems to me that defining your own functions is the most basic thing should be allowed to do.

**Comment by brookhong** [comment]
`command` was deprecated because that `unsafe-eval` was removed from `content_security_policy` in manifest.json.

Please see https://github.com/brookhong/Surfingkeys/blob/master/pages/changelog.md#0922

**Comment by Stvad** [comment]
Is there any perspectives of making this possible again some time in the future?
