### ISSUE TITLE
谷歌页面使用不了插件

### ISSUE THREAD

**Issue by MaxTan** [brookhong/Surfingkeys#726]
## Error details
谷歌的任何页面都使用不了

图表是灰色的，但确定是启用了

SurfingKeys: 0.9.29

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
请查看[在Chrome禁用的页面使用Surfingkeys](https://brookhong.github.io/2017/10/15/surfingkeys-across-all-pages-cn.html)
