### ISSUE TITLE
how to using youtube own hotkeys with surfingKeys

### ISSUE THREAD

**Issue by SugeunOh** [brookhong/Surfingkeys#728]
SurfingKeys is very nice extension.

I'm using surfingKeys, but youtube also has useful hotkeys like 1,2,3,..9, <<, >>, etc..

Is there any way to using youtube own hotkeys with surfingKeys on.

my use-case :
bookmark youtube - by "a - b" from surfingKeys
move movie bar by "1,2,..9" from youtube

thank you again.!!

**Comment by kronolynx** [comment]
I switch between youtube and surfingKeys using PassThrough, <Alt-i> when I need to use youtube hotkeys then esc to continue using surfingKeys.

**Comment by brookhong** [comment]
Please refer to [How to unmap many keys for some sites?](https://github.com/brookhong/Surfingkeys/wiki/FAQ#how-to-unmap-many-keys-for-some-sites)

**Comment by SugeunOh** [comment]
thank you guys!!
