### ISSUE TITLE
Surfingkeys own settings working in PDF viewer

### ISSUE THREAD

**Issue by duranivan** [brookhong/Surfingkeys#729]
I seems that my own Surfingkeys settings are not being loaded when interacting with the pdf viewer (only the default settings are being loaded). Would it be possible to have my own settings also working in the pdf viewer?

Thanks in advance!

**Comment by brookhong** [comment]
This is because that `unsafe-eval` was removed from `content_security_policy` in manifest.json.

And for security reason, there is no possibility to bring it back.

**Comment by brookhong** [comment]
Duplicate issue of #716
