### ISSUE TITLE
能否为特定页面禁用surfingkeys

### ISSUE THREAD

**Issue by phlips5437** [brookhong/Surfingkeys#73]
我的路由器管理页面上有个webshell功能，可以直接在页面上输入命令行控制路由器

但输入字符的话会映射为surfingkeys的功能

请问能否对这类页面单独禁用？

**Comment by philia** [comment]
Alt+s, 我有类似需求, 这个状态是可以保存下来的, 下次再访问同一个页面的时候SurfingKeys也会被禁用.

**Comment by kovetskiy** [comment]
che za huinya?

**Comment by brookhong** [comment]
@phlips5437 
https://github.com/brookhong/Surfingkeys/blob/master/README.md#hotkey-to-toggle-surfingkeys

https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E5%BC%80%E5%85%B3%E7%83%AD%E9%94%AE
