### ISSUE TITLE
Enabling Mapping of Numeric Keys

### ISSUE THREAD

**Issue by akai1831** [brookhong/Surfingkeys#731]
Hi, @brookhong . We would need to map the following keys using USB Numeric Keypad, this function was working with cVim and Vimium
![sk1](https://user-images.githubusercontent.com/20372600/39488337-9a4b556c-4d8a-11e8-89ba-e66e452bf476.JPG)

![sk2](https://user-images.githubusercontent.com/20372600/39488341-9e2a95e4-4d8a-11e8-993d-dac3df360a9d.JPG)

map 2 scrollDown
map 3 scrollPageDown
map 4 previousTab or (Go one tab left)
map 5 reloadTab or (Reload the page)
map 6 nextTab or (Go one tab right)
map 8 scrollUp
map 9 scrollPageUp

I'm pretty sure that the reason behind that, is this
https://github.com/brookhong/Surfingkeys#repeats-action-by-pressing-number-before-mapkey

It would be great to have this feature from your plugin since this is the only plugin I have tried without issue on scrolling. Thanks much to this and hope to support this feature

**Comment by brookhong** [comment]
Yes, you're right.

But what is strong reason to use only digits for mapping? Since digits are reserved for action repeats.

And actually for me, digits is less convenient to press than letters.

**Comment by akai1831** [comment]
Hi, @brookhong. To be honest, the reason why we do need to map numeric keys only is we're planning to use USB Numeric Keypad as a control in our Dashboard Monitor, it would be handy to use the Numeric Keypad rather than whole Keyboard. This USB Numeric Keypad will be hanged near to Dashboard Monitor for the users (who is viewing) to have limited control and to make it more interactive.
![20180505_080229](https://user-images.githubusercontent.com/20372600/39660056-f09199d8-503f-11e8-8b7c-ed41976a8564.jpg)

I think we could just create an exception when mapping numeric keys then the repeat action will no longer be available or much more better idea. Thanks!

**Comment by akai1831** [comment]
Wonderful! I have tested the new feature and however, I've encountered an issue under 737
