### ISSUE TITLE
Hint styles no longer applied

### ISSUE THREAD

**Issue by dmfay** [brookhong/Surfingkeys#735]
SurfingKeys: 0.9.30
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.36
URL: any

My config contains the following link hint style:

```
Hints.style('border: solid 3px #552a48; color:#efe1eb; background: none; background-color: #552a48;');
```

After upgrading to 0.9.30, they're no longer applied and I see the default black-on-yellow link hints. All other custom styles (including text hints) are still present, so it's just the link hints having the problem.

**Comment by Philipp0205** [comment]
This still applies for me.

SurfingKeys: 0.9.45
Browser: Moziala Firefox 68.0.1 (64-Bit)
OS: Ubuntu 19.04
URL: any
