### ISSUE TITLE
Manipulating Tabs via Numeric Keys [BUG]

### ISSUE THREAD

**Issue by akai1831** [brookhong/Surfingkeys#737]
Hi, @brookhong. Thank you for adding this feature from 731. However, I've encountered some issues.

## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

-No

## Error details

SurfingKeys: 0.9.31

Browser: Chrome Windows7

## Context

I have remapped the following keys. It only happens when numeric keys are used for mapping and when resetting to default mapping, there's no issue at all.

```
settings.digitForRepeat = false;
map("3", "d"); - Scroll a page down
map("6", "R"); - Go one tab right
map("4", "E"); - Go one tab left
map("9", "e"); - Scroll a page up
map("2", "j"); - Scroll down
map("5", "r"); - Reload the page
map("8", "k"); - Scroll up
map("7", "g0"); - Go to the first tab
map("1", "g$"); - Go to the last tab
```

I just noticed that `Go to the first tab` and `Go to the last tab` has the same behavior of `Go one tab right` and `Go one tab left` and most likely the `Scroll a page up` and `Scroll a page down` won't work in scrollable divs. I did not encounter any issue when pressing 2 (Scroll down), 4 (Go one tab left), 5 (reload the page), 6 (Go one tab right), 8 (Scroll up). Thanks much!

**Comment by akai1831** [comment]
Ping @brookhong

**Comment by brookhong** [comment]
You could find below in default mappings:

    map('g0', ':feedkeys 99E', 0, "#3Go to the first tab");
    map('g$', ':feedkeys 99R', 0, "#3Go to the last tab");

That means `g0` is a shortcut for `:feedkeys 99E`, which is just like pressing `99E`, you could figure out that `99` here is for repeat.

And you have disabled digitForRepeat, that why `Go to the first tab` behaves like `Go one tab left`. So far there is no good solution for this.

For `Scroll a page up` and `Scroll a page down`, your setting works well for me.

**Comment by akai1831** [comment]
Thanks for your response. I have tried using below mappings and still `Go to the first tab` and `Go to the last tab` behaves like `Go one tab left` and `Go one tab right`

```
settings.digitForRepeat = false;
map("3", "d"); - Scroll a page down
map("6", "R"); - Go one tab right
map("4", "E"); - Go one tab left
map("9", "e"); - Scroll a page up
map("2", "j"); - Scroll down
map("5", "r"); - Reload the page
map("8", "k"); - Scroll up
map('g0', ':feedkeys 99E', 0, "#3Go to the first tab");
map('g$', ':feedkeys 99R', 0, "#3Go to the last tab");
map("7", "g0"); - Go to the first tab
map("1", "g$"); - Go to the last tab
```

or using this order

```
settings.digitForRepeat = false;
map("3", "d"); - Scroll a page down
map("6", "R"); - Go one tab right
map("4", "E"); - Go one tab left
map("9", "e"); - Scroll a page up
map("2", "j"); - Scroll down
map("5", "r"); - Reload the page
map("8", "k"); - Scroll up
map("7", "g0"); - Go to the first tab
map("1", "g$"); - Go to the last tab
map('g0', ':feedkeys 99E', 0, "#3Go to the first tab");
map('g$', ':feedkeys 99R', 0, "#3Go to the last tab");
```

Let me know where's my mistakes there or should I download the latest copy of plugin from this. I just installed it via WebStore. Thanks

**Comment by leotaku** [comment]
Is there still no solution to this problem? Can we somehow manually send a repeat counter to the `nextTab` call?
