### ISSUE TITLE
基于用户输入的自定义行为

### ISSUE THREAD

**Issue by leafOfTree** [brookhong/Surfingkeys#738]
期望：输入 1234 回车，跳转到 localhost:1234。

现状：目前好像并不支持自定义带参数的命令 #723。

建议解决方案： openOmniquery 会根据用户输入拼接到网址中，处理返回的数据。当未提供网址时，直接处理用户输入。

最后实现的效果
```javascript
mapkey('p', 'Open URL like http://localhost:<port>', function () {
    Front.openOmniquery({
        parseResult: function(input) {
            window.location.href = 'http://localhost:' + input;
        }
    });
})
```

**Comment by mwxxhdb** [comment]
我有个需求，希望能根据搜索框自己拼接自动完成的选项列表。

这样可以自动拼接 JIRA 里常用项目前缀+数字
以及可以输入数字就跳转到 sonar 的 issue 说明页面

例如输入数字: 1512
自动完成列表里的结果是：
{title: 'LPD-1512', url: 'https://jira.site.com/jira/browse/LPD-1512'}
{title: 'LRM-1512', url: 'https://jira.site.com/jira/browse/LRM-1512'}

输入 LPD-1512 结果里就只有第一条
