### ISSUE TITLE
Shift+J deletes everything

### ISSUE THREAD

**Issue by chaorace** [brookhong/Surfingkeys#739]
## Error details

SurfingKeys: 0.9.31

Browser: Version 66.0.3359.139 (Official Build) (64-bit) / Windows 7

URL: http://google.com

## Context

When editing an input field in ACE editor (Ctrl+I or Shift+I summoned), the shift+j function causes all written text to irrecoverably disappear (undo does not work). The expected behavior is collapsing the next line into the current line.

**Comment by brookhong** [comment]
Fixed in 0.9.32.
