### ISSUE TITLE
Surfingkeys no longer works on PDF viewer for firefox 60+

### ISSUE THREAD

**Issue by duguyipiao** [brookhong/Surfingkeys#741]
Surfingkeys no longer works on PDF viewer for firefox 60+.

Yes, this is a new "feature" of firefox!

Related to:
https://discourse.mozilla.org/t/extensions-on-pdfjs-pages/28441
https://bugzilla.mozilla.org/show_bug.cgi?id=1456485
https://www.mozilla.org/en-US/security/advisories/mfsa2018-11/

**Comment by brookhong** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454760
