### ISSUE TITLE
Return/enter don't work in omnibar!

### ISSUE THREAD

**Issue by mhertz** [brookhong/Surfingkeys#744]
The last weeks i've been unable to use return/enter in omnibar e.g. when using 't'. I tried uninstalling/reinstalling to no avail. Using latest surfingkeys with chromium from repo on fully up-to-date arch linux. Very annoying honestly and hoping it could be fixed so not having to revert to cvim again. Thanks in advance!

Edit: I can though use tab and select a completion-entry with return/enter, but not use return/enter on the search-field i.e. I cannot press 't', type a search-string and press return/enter .

**Comment by tsaber** [comment]
me too! just posted my issue and then I saw yours!

**Comment by octavz** [comment]
It still happens for me on Vivaldi and Ubuntu. It used to work fine.
Press `t` write something, press `Enter` => DNS error.
