### ISSUE TITLE
Can't open URL in omnibar, only via searchalias or history

### ISSUE THREAD

**Issue by tsaber** [brookhong/Surfingkeys#745]
* Could you find answer in below documents?
No
* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes but haven't found anything including "enter" or "open url"
## Error details
I can hit enter but nothing will happen when I type in the url in the omnibar (go) and want to open it. A temp workaround is opening urls with Ctrl+l. 
SurfingKeys: 0.9.31

Version 66.0.3359.170 (Official Build) Arch Linux (64-bit)

URL: all :(

##Context
I don't think anything I did in my  
[config](https://gist.github.com/tsaber/b8b4319ac542c8e34112f7309f896dd3/raw) caused this issue I have been trying to undo my settings to no avail. I have the suspicion that a recent update caused this

**Comment by brookhong** [comment]
Is this a same issue as #740 and #744 ?

**Comment by tsaber** [comment]
while I welcome the addition to the codebase based on these issues mine is different in that Enter is not accepted at all while in their case it didn't leave them with choice.

**Comment by brookhong** [comment]
Fixed in 0.9.32.
