### ISSUE TITLE
使用过程中遇到的问题

### ISSUE THREAD

**Issue by hereis00** [brookhong/Surfingkeys#747]
1. 知乎视频怎么播放，进入播放怎么退出（esc无效）。
2. 知乎更多评论按钮点击后直接进入评论框输入焦点，退出无法再进入输入框（除非收起评论列表，再打开评论列表，这时候又会再聚焦那个评论的输入框了）。
3. 有一个c-h的功能应该是模拟鼠标悬停，但是对于知乎评论中该功能可以捕捉到这样需要悬停的位置，捕捉到之后却不能真正像鼠标悬停一样显示“回复”、“评论”之类的文字。

**Comment by hereis00** [comment]
4. 打开知乎的一个问题，在浏览答案时，向下滚动，页眉是该问题的描述，向上滚动会显示导航栏，而使用d/e/j/k都不能触发这样的事件，除非用鼠标的滚轮操作过一次，之后才能正常触发。

**Comment by brookhong** [comment]
1. 知乎视频在一个`frame`里，按`w`切换到top window
2. 0.9.33已修复
