### ISSUE TITLE
Vimium-like local marks

### ISSUE THREAD

**Issue by gtoast** [brookhong/Surfingkeys#75]
I would love to see Vimium's local/global mark system immplemented in Surfingkeys. 

ma, mA  set local mark "a" (global mark "A")
`a, `A  jump to local mark "a" (global mark "A")
``      jump back to the position before the previous jump -- that is, before the previous gg, G, n, N, / or `a

Besides allowing you to have more marks by making all lowercase marks local to a page, if the page is already loaded in the tab, vimium merely moves you back to the location as opposed to Surfingkeys which reloads the entire page then moves you to the location. 

Thank you for all your hardwork on Surfingkeys!

**Comment by brookhong** [comment]
Vim-like mark has been implemented, but it works slightly different with vim/vimium. Now vim-like marks in Surfingkeys all work in global way, and they are case insensitive.

**Comment by gtoast** [comment]
Yes. I would like to see the implementation be closer to the one found in vimium. Are you happy with the current implementation?

**Comment by brookhong** [comment]
Added, will be release in next version.

**Comment by brookhong** [comment]
Released in 0.5.5.
