### ISSUE TITLE
Additional Settings

### ISSUE THREAD

**Issue by akai1831** [brookhong/Surfingkeys#755]
Could you add an additional settings to disable Return or Enter key in Choose a tab Omnibar, choosing a tab via an overlay is not an alternative way in our case as we have limited keys to be used, meaning that the Return or Enter key cannot be used to input text field but can be used when choosing a tab. That was consider a bug since 0.9.31 though still useful for some cases like what we have. Thanks in advance.

Another option is to disable or remove the input text field when choosing a tab, that is just an additional option for purely choosing a tab with the use of tab and enter key only. I hope you would find this into consideration.

**Comment by akai1831** [comment]
Ping @brookhong

**Comment by brookhong** [comment]
I could not get your point here.

By Omnibar(with input box), you must use `enter`. By Overlay, you switch tab just as in Hint mode.

**Comment by akai1831** [comment]
What we would like in Choose a Tab Omnibar is to have an Option to disable the Enter key in an input box or if possible is to entirely remove the input box, reason is we would need to get rid of opening a new tab when pressing an Enter key to an input box

**Comment by akai1831** [comment]
Hi, @brookhong. Here it is. Thanks in advance

**Comment by akai1831** [comment]
Hi, @brookhong . Did SurfingKeys had some sort of settings to optionally disable the input text search field from an Omnibar especially in Choose a Tab omnibar, in this case, we'll just use the Tab key to select an item from the Omnibar and Enter key to open selected item. Thanks for the greatwork!

**Comment by hellola** [comment]
Firstly @brookhong I absolutely love this extension!
I have a similar frustration with the omnibar @akai1831 , I don't always want to push tab before pushing enter. Could there be an option for it to work like this:
You type some filtering text
There is only one result to switch to
You push enter and switch to that tab
If there are more than one, it can be chosen by using tab. 

Would this be something that anybody else would want/ benefit from?

**Comment by brookhong** [comment]
Please set `settings.focusFirstCandidate` as true for the case.
