### ISSUE TITLE
window.origin对象在360安全浏览器上不可用

### ISSUE THREAD

**Issue by dirtyluke** [brookhong/Surfingkeys#756]
360安全浏览器上面安装surfingkeys后，页面加载会报错然后无法使用。
排查后发现common_content.js中e.postTopMessage方法使用的window.origin在360浏览器中无法获取正常值，需要替换成window.location.origin。
这个问题更新了好几版都没有修改，每次手动更换比较麻烦，希望后续版本解决这个问题 @brookhong

**Comment by brookhong** [comment]
谢谢，下个release会修改。
