### ISSUE TITLE
'Q' option setting is need to changed for langauge users. 

### ISSUE THREAD

**Issue by mindgitrwx** [brookhong/Surfingkeys#758]
mapkey('Q', '#8Open omnibar for word translation', function() {
    Front.openOmniquery({
        url: "https://api.shanbay.com/bdc/search/?word=",
        /*
         * or
        url: function(q) {
            return "https://api.shanbay.com/bdc/search/?word=" + q
        },
        */
        query: Visual.getWordUnderCursor(),
        style: "opacity: 0.8;",
        parseResult: function(res) {
            var res = JSON.parse(res.text);
            return [ renderShanbay(res) ];
        }
    });
});

It would be nice if user can change setting of 'Q'. Shanbay is not useful to non-chinese people.

I've tried to change dictionary to google translator, but failed. I used this way. 
https://gist.githubusercontent.com/958/9f4d93e8308920478159566008c56f8b/raw/c06698bbc057290feaea27096a4a9bce0630e69e/SurfingkeysSetting.js

If this Q function is chinese specific function, please document this fact. Or not, tell me how to change the dictionary of Q function. 

Thanks.

**Comment by brookhong** [comment]
Please see https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query.
