### ISSUE TITLE
[0.9.32] 搜索功能疑问

### ISSUE THREAD

**Issue by loseloner** [brookhong/Surfingkeys#764]
addSearchAliasX('z','zhihu', 'https://www.zhihu.com/search?type=question&q=', 's');
mapkey('oz', '#8打开知乎搜索栏', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "z"});
});
mapkey('sz', '#8用知乎搜索选中文本', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "z"});
});

addSearchAliasX('i','MEZW', 'https://so.mezw.com/Search?wd=', 's');
mapkey('oi', '#8打开MEZW搜索栏', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "i"});
});
mapkey('si', '#8用MEZW搜索选中文本', function() {
        Front.openOmnibar({type: "SearchEngine", extra: "i"});
});

settings.interceptedErrors = ['*'];

提问：【以上我自定义添加的，可是无法实现 sz，si 直接搜索剪切板**（如sb,sg）**】，哪里不对请指出，谢谢！

<img width="401" alt="20180608164311" src="https://user-images.githubusercontent.com/39988865/41148382-715c1b90-6b3b-11e8-8a4d-bafc82d5c3f2.png">
<img width="416" alt="20180608164326" src="https://user-images.githubusercontent.com/39988865/41148414-826eb21c-6b3b-11e8-88e0-80b506ab7643.png">

**Comment by brookhong** [comment]
有下面这一行就能实现`sz`搜索剪切版里的内容啊：

    addSearchAliasX('z', '知乎 search', 'https://www.zhihu.com/search?type=question&q=');

**Comment by loseloner** [comment]
addSearchAliasX('z', '知乎', 'https://www.zhihu.com/search?type=question&q=');
mapkey('oz', '#8打开知乎搜索栏', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "z"});
});
addSearchAliasX('k','MEZW', 'https://so.mezw.com/Search?wd=');
mapkey('ok', '#8打开MEZW搜索栏', function() {
    Front.openOmnibar({type: "SearchEngine", extra: "k"});
});

我不知道和以前有 什么不一样，反正按上面 的编辑后，就好了
多谢了！

**Comment by loseloner** [comment]
A.问了不痛不痒的问题：
图中 si 提示 如何换成中文？ 
<img width="149" alt="20180611171926" src="https://user-images.githubusercontent.com/39988865/41223307-03b75876-6d9c-11e8-9164-b52efe59c664.png">  

B.遇到站内搜索如何处理？
比如 appinn.com 中搜索【测试】，搜索结果网页地址是：
https://search.appinn.com/cse/search?q=%E6%B5%8B%E8%AF%95&click=1&s=5999676002387380177&nsid=

我该如何addSearchAliasX ?

addSearchAliasX('s', 'appinn', 'https://search.appinn.com/cse/search?q=**%s**&click=1&s=5999676002387380177&nsid=');
这里该如何写？
