### ISSUE TITLE
[0.9.32] 在当前标签页打开输入网址(go) 无效

### ISSUE THREAD

**Issue by loseloner** [brookhong/Surfingkeys#766]
<img width="117" alt="20180608165055" src="https://user-images.githubusercontent.com/39988865/41148777-5a5cd014-6b3c-11e8-8f2b-4c08300b4c49.png">

go -> 执行结果是 搜索输入的网址    

这是个bug吗? 

还是说 **go=t=多功能书签地址栏**

**Comment by brookhong** [comment]
`go`和`t`的功能类似，差别在于`go`打开的搜索栏输入之后是在当前标签页打开。

**Comment by loseloner** [comment]
学习了！
