### ISSUE TITLE
Wrong colors in omnibar after recent update

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#767]
I set my theme colors like this:

```javascript
settings.theme = `
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #24272e;
    color: #abb2bf;
}
.sk_theme tbody {
    color: #fff;
}
.sk_theme input {
    color: #d0d0d0;
}
.sk_theme .url {
    color: #61afef;
}
.sk_theme .annotation {
    color: #56b6c2;
}
.sk_theme .omnibar_highlight {
    color: #528bff;
}
.sk_theme .omnibar_timestamp {
    color: #e5c07b;
}
.sk_theme .omnibar_visitcount {
    color: #98c379;
}
.sk_theme ul>li:nth-child(odd) {
    background: #303030;
}
.sk_theme ul>li.focused {
    background: #3e4452;
}
#sk_status, #sk_find {
    font-size: 20pt;
}`;
```
However with the lastest version (i believe after commit https://github.com/brookhong/Surfingkeys/commit/66bcf00a3bf0de76dbcc7f403d18811f52133c56) the omnibar shows a white background on some of candidates:

<img width="1226" alt="screen shot 2018-06-10 at 14 53 56" src="https://user-images.githubusercontent.com/2583971/41204675-27841bce-6cbe-11e8-83a6-94e8747f6794.png">

With the previous version colors look like this:

<img width="1186" alt="screen shot 2018-06-10 at 14 55 19" src="https://user-images.githubusercontent.com/2583971/41204684-5a648db2-6cbe-11e8-9250-82fca1b39b17.png">

How can i recover those colors? Thanks

**Comment by brookhong** [comment]
Please add `#sk_omnibarSearchResult` before `ul>li`:

    settings.theme = `
    .sk_theme {
        font-family: Input Sans Condensed, Charcoal, sans-serif;
        font-size: 10pt;
        background: #24272e;
        color: #abb2bf;
    }
    .sk_theme tbody {
        color: #fff;
    }
    .sk_theme input {
        color: #d0d0d0;
    }
    .sk_theme .url {
        color: #61afef;
    }
    .sk_theme .annotation {
        color: #56b6c2;
    }
    .sk_theme .omnibar_highlight {
        color: #528bff;
    }
    .sk_theme .omnibar_timestamp {
        color: #e5c07b;
    }
    .sk_theme .omnibar_visitcount {
        color: #98c379;
    }
    .sk_theme #sk_omnibarSearchResult>ul>li:nth-child(odd) {
        background: #303030;
    }
    .sk_theme #sk_omnibarSearchResult>ul>li.focused {
        background: #3e4452;
    }
    #sk_status, #sk_find {
        font-size: 20pt;
    }`;

**Comment by petobens** [comment]
@brookhong thanks! One thing i still notices is that there is white bar on the right:
<img width="1187" alt="screen shot 2018-06-10 at 22 05 57" src="https://user-images.githubusercontent.com/2583971/41208488-87b01e80-6cfa-11e8-84e1-c50934fa2218.png">

Is that a feature or bug?

**Comment by akai1831** [comment]
I have encountered this as well when pressing T, to choose a tab

**Comment by brookhong** [comment]
It should be a bug, please provide your OS and Chrome versions?

**Comment by akai1831** [comment]
I have my Windows 10 and 7 SP1 OS with Google Chrome v66

**Comment by petobens** [comment]
In my case:
```

Google Chrome | 67.0.3396.79 (Official Build) (64-bit)
Revision | 161bdad7314804dc8c72f850396fcd696e8863e8-refs/branch-heads/3396@{#755}
OS | Mac OS X
```

**Comment by akai1831** [comment]
Now it is fixed in 0.9.34
Thanks, @brookhong!
Could you also put into consideration my request in #755

**Comment by petobens** [comment]
@akai1831 where can I find version 0.9.34? I only se 0.9.33 on github

**Comment by akai1831** [comment]
I have my SurfingKeys installed via Chrome Web Store, there you should see the version 0.9.34

**Comment by akai1831** [comment]
I have my SurfingKeys installed via Chrome Web Store, there you should see the version 0.9.34, @petobens

**Comment by petobens** [comment]
@akai1831 indeed. Thanks

**Comment by petobens** [comment]
Hi I'm using 0.9.64 on and I'm seeing this issue again on Brave browser with:
```javascript
settings.theme = `
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #24272e;
    color: #abb2bf;
}
.sk_theme tbody {
    color: #fff;
}
.sk_theme input {
    color: #d0d0d0;
}
.sk_theme .url {
    color: #61afef;
}
.sk_theme .annotation {
    color: #56b6c2;
}
.sk_theme .omnibar_highlight {
    color: #528bff;
}
.sk_theme .omnibar_timestamp {
    color: #e5c07b;
}
.sk_theme .omnibar_visitcount {
    color: #98c379;
}
.sk_theme #sk_omnibarSearchResult>ul>li:nth-child(odd) {
    background: #303030;
}
.sk_theme #sk_omnibarSearchResult>ul>li.focused {
    background: #3e4452;
}
#sk_status, #sk_find {
    font-size: 20pt;
}`;
```
Any change of fixing it?

**Comment by brookhong** [comment]
Replace all the `>` with SPACE in your scripts after 0.9.64, such as

    .sk_theme #sk_omnibarSearchResult ul li:nth-child(odd) {
        background: #303030;
    }
    .sk_theme #sk_omnibarSearchResult ul li.focused {
        background: #3e4452;
    }

**Comment by petobens** [comment]
Awesome. Thanks
