### ISSUE TITLE
Feature Request: copy all tab urls (yY)

### ISSUE THREAD

**Issue by sadid** [brookhong/Surfingkeys#768]
There are many situations which the user end up with lots of tabs. It would be great to press something like `yY` to copy all open tabs url and move on (e.g. copy them somewhere and save memory by closing them). Unfortunately I don't have the JavaScript knowledge to figure this out.

**Comment by slavaGanzin** [comment]
```js
mapkey('yY', '#1Copy all tabs url', function() {
	runtime.command({action: 'getTabs'}, function (response) {
	 Clipboard.write(response.tabs.map(tab => tab.url).join('\n'))
	})
})
```

**Comment by brookhong** [comment]
Why not use session? Please see https://github.com/brookhong/Surfingkeys#session-management

**Comment by slavaGanzin** [comment]
1. I need to save some links to work on them on another machine (work/home)
2. I need to send my colleague bunch of tabs I'm working on
3. I want to bookmark(using some service like google keep, or delicious, etc) my current state, tag it. And I'll use it in some time

**Comment by sadid** [comment]
I copy your javascipt code to my option page for Surfingkeys. Didn't work. Then I allow file access to extension and load it from my local file system still doesn't work. I'm using Chromium/Linux does `Clipboard.write` cross platform?

Regarding use case I sometimes researching a topic and have lots of tabs opened. But I need to move on and then store the links somewhere and use it later, when come back to the project. Using `ZZ` is good just sometimes it quits the chromium and don't any access to URLs easily. Having them in my clipboard is more flexible  solution.

**Comment by sadid** [comment]
@brookhong, Regarding use case I sometimes research a topic and have lots of tabs opened. But I need to move on and then store the links somewhere and use it later, when come back to the project. Using `ZZ` is good just sometimes it quits the chromium and don't any access to URLs easily. Having them in my clipboard is more flexible  solution.

**Comment by slavaGanzin** [comment]
@sadid	Use "advanced mode":
![2018-07-02-114135_1920x1200_scrot](https://user-images.githubusercontent.com/1011721/42153949-2f17e074-7ded-11e8-9876-f248ce457267.png)

**Comment by sadid** [comment]
@slavaGanzin, Thanks I used a name in the box and that prevents overwrite the setting. I just used `:w` without an empty name and now it's working both on Chromium and Firefox. Thanks for the code!

One thing I noticed is when I press the `yY` it copy all the tab urls except the current one. It's quite satisfactory but just wanted to make sure if this is expected.

**Comment by slavaGanzin** [comment]
> One thing I noticed is when I press the yY it copy all the tab urls except the current one.

It was unexpected for me too.

**Comment by brookhong** [comment]
That is because `getTabs` from background has filtered out current tab, please see https://github.com/brookhong/Surfingkeys/blob/master/background.js#L629

**Comment by slavaGanzin** [comment]
@sadid 
```
mapkey('yY', '#1Copy all tabs url', function() {
	runtime.command({action: 'getTabs'}, function (response) {
	 Clipboard.write([window.location.href].concat(response.tabs.map(tab => tab.url)).join('\n'))
	})
})
```

**Comment by sadid** [comment]
@slavaGanzin Thanks, I test it on both Firefox and Chromium (Linux) and they both work as expected. Great!

**Comment by for-coursera** [comment]
@brookhong This seems not to be working any more? `runtime.command` should be replaced with `RUNTIME` with some tweaks probably?

**Comment by brookhong** [comment]
Yes, `runtime.command` has been removed, please use below,

    mapkey('yY', '#1Copy all tabs url', function() {
        RUNTIME('getTabs', null, function (response) {
            Clipboard.write([window.location.href].concat(response.tabs.map(tab => tab.url)).join('\n'))
        })
    });

**Comment by vogler** [comment]
@brookhong That will move the active tab's URL out of order and to the front.
I avoid `getTabs` filtering out the currently active tab by setting `tabsThreshold: 999`.

```js
const markdownLink = (title, url) => {
    const escapedTitle = title.replace(/[\[\]]/g, "\\$&").replace(/\\$/, "");
    return `[${escapedTitle}](${url})`;
}
mapkey('yM', '#7Copy page URL/title as Markdown link', function() {
    Clipboard.write(markdownLink(document.title, window.location.href));
});
mapkey('yw', '#7Copy window tabs URLs', function() {
    // chrome.tabs.query({ currentWindow: true}, console.log); // will output all tabs, but can't call query here (works in Console via 'Ext > Inspect pop-up')
    // getTabs does some more stuff: https://github.com/brookhong/Surfingkeys/blob/c0b34133cef5f17ef4fda19cd161b1a5a75b88e2/src/background/start.js#L736
    // by default it will filter out the currently active tab; setting message.tabsThreshold high to avoid it:
    RUNTIME('getTabs', { queryInfo: { currentWindow: true }, tabsThreshold: 999 }, function (response) {
        Clipboard.write(response.tabs.map(tab => tab.url).join('\n'))
    })
});
mapkey('yW', '#7Copy window tabs Markdown links', function() {
    RUNTIME('getTabs',{ queryInfo: { currentWindow: true }, tabsThreshold: 999 }, function (response) {
        Clipboard.write(response.tabs.map(tab => markdownLink(tab.title, tab.url)).join('\n'))
    })
});
```
