### ISSUE TITLE
怎么把焦点从地址栏移动到html body?

### ISSUE THREAD

**Issue by Jefung** [brookhong/Surfingkeys#773]
有时候会不小心失去焦点,就没法用f查找,o打开搜索引擎,虽然用鼠标点一下浏览器就可以,但是还是想找到快速回到body的方法

**Comment by duguyipiao** [comment]
试试 `F6`、`Tab`或者`Ctrl+L`，Chrome和Firefox的效果不一样，不同系统效果可能也不一样。

**Comment by brookhong** [comment]
You could also refer to

* https://github.com/philc/vimium/issues/840
* https://superuser.com/questions/324266/google-chrome-mac-set-keyboard-focus-from-address-bar-back-to-page

**Comment by hbt** [comment]
@brookhong I wrote a chrome extension to restore the focus from anywhere in the browser by calling  a browser action via a keyboard shortcut. Works from search bar and from devtools inspector/console input. 

Check it out https://github.com/hbt/chrome-restore-focus

Perhaps there is a way to integrate this into this project
