### ISSUE TITLE
Doesn't work on github

### ISSUE THREAD

**Issue by idosilverwater** [brookhong/Surfingkeys#774]
Hello, 

I have a bug with surfing keys.
Non of the keybindings work on git hub...

Can you fix this?

Thanks alot!

Ido-Moshe Silverwater
AgH<sub>2</sub>O

**Comment by xcv58** [comment]
Duplicated to #770

I'll try to fix this.

**Comment by ma11hew28** [comment]
I'm not sure which keybindings @idosilverwater is referring to, but <kbd>t</kbd> no longer activates the file finder on GitHub because Surfingkeys uses that key "to open URL."
