### ISSUE TITLE
Can't input in a certain inputbox

### ISSUE THREAD

**Issue by Leoongithub** [brookhong/Surfingkeys#778]
## Error details

SurfingKeys: 0.9.36

Browser: chrome  67.0.3396.99, win10 1803

I can't input anything in a certain inputbox. But it works when I disable Surfingkeys.

Cause this page is in an intranet, I saved it and deleted most unrelated content. I hope it will be helpful to debug.
[login.zip](https://github.com/brookhong/Surfingkeys/files/2147533/login.zip)

**Comment by krystah** [comment]
Same here. When attempting to access a page prompting me with a login-box, the login-box is hidden and I am unable to enter anything. Disabling Surfingkeys via the context menu for the extension does not help, but disabling the extension in its entirety from chrome://extensions/ works.

**Comment by brookhong** [comment]
![image](https://user-images.githubusercontent.com/288207/62632877-cc2f5400-b965-11e9-897f-2937da8f0e09.png)

I can input on your login.html. @Leoongithub 

Are you still having the issue?

@krystah Could you show me an URL of such page?

**Comment by krystah** [comment]
@brookhong In our case it's also a case of being an intranet page, so I can't provide a link unfortunately. If I come across the problem on a public domain, I'll let you know!
