### ISSUE TITLE
copy link and apply a shortener

### ISSUE THREAD

**Issue by rpietro** [brookhong/Surfingkeys#782]
yy copies the current link, but is there a way to automatically shorten it?

**Comment by slavaGanzin** [comment]
This is out of scope of this project. But you can do it by yourself for yourself:

Here is how you can do you own keybindings
https://github.com/brookhong/Surfingkeys#edit-your-own-settings 

Here is bitly api documentation:
https://dev.bitly.com/v4_documentation.html

And there is a way to do http from browser:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
