### ISSUE TITLE
 'soG' cursor not going to the input box

### ISSUE THREAD

**Issue by jaredbidlow** [brookhong/Surfingkeys#794]
The cursor does not go to the input box when i do "search this site for" keystrokes. It briefly shows blue, as in the text is selected, but focus does not stay in omnibar. I have to click on it.

## Error details

SurfingKeys: 0.9.36

Browser: chrome win10

## Context
Any "search on" action, soB, soG, etc. has the same behavior. This started a couple weeks ago.

**Comment by brookhong** [comment]
Thanks for reporting this.
