### ISSUE TITLE
[Feature Request] Smart Link Hints

### ISSUE THREAD

**Issue by akai1831** [brookhong/Surfingkeys#798]
Hi, @brookhong. Could you add an option to have an smart link hints, like for example in below image
![link](https://user-images.githubusercontent.com/20372600/42573900-00ca8d08-8526-11e8-94ae-407e6b7aada6.JPG)
![link2](https://user-images.githubusercontent.com/20372600/42573902-013d3f1a-8526-11e8-8bf6-f3e4f18c7df8.JPG)

Link Hints will only be generated to all links started by `BA-`, `BB-`, `3003-`, `3003H-` depends on what have been defined in property list else no link hints will be Generated. I hope that it is feasible

**Comment by akai1831** [comment]
Hi, @brookhong. I do hope you consider this feature.
Thanks in advance

**Comment by karlicoss** [comment]
Second this, I think it would generally be useful, e.g. with Reddit, for instance I never click on 'give gold' or 'report', etc, so would be useful to suppress hints for them.

![image](https://user-images.githubusercontent.com/291333/43805952-b8b1a66c-9a99-11e8-9239-13fb6d519e6c.png)

**Comment by akai1831** [comment]
Hi, @brookhong May we have this into consideration

**Comment by b0o** [comment]
@akai1831 Can you provide a link to a sample page? I need to see the HTML, but I may be able to help.

@karlicoss Here's an example mapping which would prevent hints from being created for 'give gold' and 'report' links on Reddit:

```javascript
mapkey('gR', '#1Open reddit link', function() {
    Hints.create('a[href]:not([class*="give-gold"]):not([class*="reportbtn"])', Hints.dispatchMouseClick)
}, { domain: /reddit\.com/ });
```

**Comment by akai1831** [comment]
@b0o I'll do what you instruct when I got the time.

Thanks much

**Comment by dufferzafar** [comment]
@b0o I have this for reddit:

```javascript
mapkey('gR', '#1Open reddit link', function() {
    Hints.create('a.title[href]', Hints.dispatchMouseClick, {active: false})
}, { domain: /reddit\.com/ });
```

But the `active: false` thing doesn't work!

I want the link to open in a new tab!

**Comment by b0o** [comment]
Try this:

```js
mapkey("gR", "#1Open reddit link", () => {
  Hints.create("a.title[href]", (e) => RUNTIME("openLink", { tab: { tabbed: true, active: false }, url: e.href }))
}, { domain: /reddit\.com/ })
```

`tabbed: true` is what causes the URL to open in a new tab, while `active: false` causes the tab to not be focused.

**Comment by dufferzafar** [comment]
@b0o Thanks that worked! 

This is what I have till now:

```js
unmap('F')
mapkey('F', 'Open links in new tab (custom)', function() {
    select = "";
    url = window.location.href;
    
    // Hacker News
    if (/.*news\.ycombinator\.com/.test(url)) {
        select = 'td.title > a, td.subtext > a:nth-child(7)';
    } 
    else if (/.*waybackhn\.com/.test(url)) {
        select = 'td.title > a, td.subtext > a:nth-child(4)';
    } 
    
    // Reddit
    
        // Home Page
    else if (/^.*reddit\.com$/.test(url)) {
        select = 'a.title, a.comments';
    } 
        // Comments Page
    else if (/.*reddit\.com.*?\/comments\//.test(url)) {
        console.info('Reddit comments');
        select = 'a.title, .comment .usertext-body a';
    }
    
    Hints.create(select, (e) => RUNTIME("openLink", { tab: { tabbed: true, active: false }, url: e.href }));
});
```

Please let me know if there is an obvious way of improving it!

**Comment by b0o** [comment]
That looks good. 

The only thing I could mention is that long if-elseif-elseif-... chains can easily become hard to read, especially if you plan to add more sites in the future. 

You could maybe use a switch statement (which is complicated a bit in this case since you're testing against a regexp, but see [this thread](https://stackoverflow.com/questions/2896626/switch-statement-for-string-matching-in-javascript) for possible solutions), or you could define an object or array containing all of the `regexp:selector` pairs and loop over it. 

The latter option is basically what I do in my config - see [here](https://github.com/b0o/surfingkeys-conf/blob/master/keys.js#L508) for domain/keymap definitions and [here](https://github.com/b0o/surfingkeys-conf/blob/master/util.js#L83) for the loop to process the object. My usage is a bit different since I'm creating mappings for a lot of different actions, but the gist is similar.

**Comment by dufferzafar** [comment]
Thanks a lot for reviewing!

I skimmed over your configs and they're insane! How long have you been doing this! 😅

That'll take me quite some time to go through. Have bookmarked!

**Comment by b0o** [comment]
@dufferzafar Hah, I've probably gone a bit too far with my configs 😅 I might be a bit obsessive.... If you want any other tips feel free to open an issue over on my repo, I don't wanna spam this issue anymore!
