### ISSUE TITLE
Mapping to move between tabs in google docs

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#799]
Hi, I know I can disable surfingkeys completely in Google docs sites with
```js
settings.blacklistPattern = /.*docs\.google\.com.*/i;
```
What I would like to do is to disable surfingkeys completely except for the mappings to move to the previous and next tab. I tried with the following two settings but without succes:
i) 
```js
unmapAllExcept(['<Ctrl-p>, <Ctrl-n>'], /.*docs\.google'.com.*/);
```
ii)
```js
mapkey('<Ctrl-p>', 'Previous Tab', function () {
    RUNTIME('previousTab');
}, {
    domain: /.*docs\.google\.com.*/i
});
```
Is this possible? Thanks in advance!

**Comment by MrZeroo00** [comment]
I am interested by this use-case as well.

**Comment by brookhong** [comment]
This is possible, but please keep `unmapAllExcept` at end of your snippets.

**Comment by petobens** [comment]
@brookhong I don't follow what you suggest. I have the following global unmap all at the beginning of my rc file:
```
unmapAllExcept([ 'f', '/', '*', ':', '.', 'i', 'I', '<Ctrl-i>', 'v', 'm', ]);
```
How can I add the google docs specific one? And where should I add it?

**Comment by MrZeroo00** [comment]
I confirm that the following command doesn't work as expected.
`unmapAllExcept(['E', 'R', 'f', '/', '?'], /.*docs.google\.com\/.*/i);
`
https://dsc.cloud/badr/Screen-Shot-2018-07-17-14-02-26.png

**Comment by brookhong** [comment]
There is an iframe on google doc page, in which the body is content-editable, thus there is no way to get back to Normal mode.

You can try `imapkey` to make it work:

    imapkey('<Ctrl-p>', 'Previous Tab', function () {
        RUNTIME('previousTab');
    }, {
        domain: /.*docs\.google\.com.*/i
    });
    imapkey('<Ctrl-n>', 'Next Tab', function () {
        RUNTIME('nextTab');
    }, {
        domain: /.*docs\.google\.com.*/i
    });

**Comment by brookhong** [comment]
Adding to blacklist will disable SurfingKeys completely on the page, you could add below to clear all default bound keys.

    unmapAllExcept([], /.*docs\.google\.com/i);
    imapkey('<Ctrl-p>', 'Previous Tab', function () {
        RUNTIME('previousTab');
    }, {
        domain: /.*docs\.google\.com.*/i
    });
    imapkey('<Ctrl-n>', 'Next Tab', function () {
        RUNTIME('nextTab');
    }, {
        domain: /.*docs\.google\.com.*/i
    });

But I'm wondering why you need disable default keys, since all default keys from Normal mode are not available after Insert mode is activated?

**Comment by petobens** [comment]
Fair point. Thanks for the kind help :). Closing since the issue has been solved.
