### ISSUE TITLE
使用Shadowsocks无法翻墙

### ISSUE THREAD

**Issue by ChJJin** [brookhong/Surfingkeys#80]
使用Shadowsocks进行翻墙，但是开启该插件后则不能翻墙，关闭后则能正常翻

**Comment by brookhong** [comment]
按`spi`看看当前的代理设置是什么？

**Comment by ChJJin** [comment]
是direct模式，但是也切换不了proxy模式，应该是跟我没用SwitchySharp有关？

**Comment by brookhong** [comment]
按`:`进入命令模式，然后输入

    setProxyMode clear


Surfingkeys默认是不接管代理的(clear)，你现在是direct，是不是按过`spd`?

**Comment by ChJJin** [comment]
clear掉之后就可以了，谢谢了。
因为想做更多的控制，所以在阅读源码，可能在调试的时候按过了。
