### ISSUE TITLE
static keymap's for video players (youtube, vimeo, ..., html5, flash)

### ISSUE THREAD

**Issue by D1mon** [brookhong/Surfingkeys#801]
SurfingKeys: 0.9.36
Browser: Chromium 67 (Manjaro x64)

it would be nice if the keys did not change for the video players. For example, to open the video in full screen for the first video - you need to press the "ZC" keys, for the second video "ХЕ". It is necessary that the keys do not change for all videos, assign for example "FF" for full-screen mode. And also for other combinations - play, pause, next video, settings, speed x2 (key s2) ...

**Comment by Pain-and-Love** [comment]
good idea

**Comment by LxPvlv** [comment]
&lt;Alt-s&gt; Toggle SurfingKeys on current site
&lt;Alt-i&gt;  enter PassThrough mode to temporarily suppress SurfingKeys

and then use native Youtube's keys

**Comment by crocket** [comment]
Press `p` to suppress surfingkeys for 1 second during which you can press youtube shortcuts.
