### ISSUE TITLE
Page error.html doesn't work in Incognito Mode

### ISSUE THREAD

**Issue by akai1831** [brookhong/Surfingkeys#803]
Hi, @brookhong. When the property list `settings.interceptedErrors = ["*"]` is defined it should be redirected to `error.html` page. It is working in normal mode but not working in incognito mode. I also checked `allow access to file URLs`
Here's an error I've encountered

![sk_net_issue](https://user-images.githubusercontent.com/20372600/42723468-ff94c69a-8766-11e8-92e9-cf3eef22c84a.JPG)

**Comment by akai1831** [comment]
ping @brookhong

**Comment by brookhong** [comment]
https://developer.chrome.com/extensions/manifest/incognito

Should be fixed in next release.

**Comment by akai1831** [comment]
Would it be possible to redirect `error.html` to a local file path and this local file path can be defined in user settings or in property list, with this, we can use our own defined settings.
