### ISSUE TITLE
How can I add custom search with search string in the middle of the search url?

### ISSUE THREAD

**Issue by ffplayer** [brookhong/Surfingkeys#804]
For example, I wanna add a search alias like
www.search.com/%s/1-0-0/  (%s is the string I want to search)

but now I can only add custom search like this:
addSearchAliasX('z', 'zhihu search', 'https://www.zhihu.com/search?type=question&q=');

Is this problem resolvable ?

Thanks~

**Comment by fiocui** [comment]
@ffplayer  Surfingkeys中用{0}表示%s

www.search.com/{0}/1-0-0/

**Comment by ffplayer** [comment]
@fiocui 非常感谢！！
顺便请教一下这种信息您是从哪里看到的呢？我也尝试去翻了半天帮助文档都没找到。。
