### ISSUE TITLE
Cant't make mappings with <Ctrl-,> and <Ctrl-.>

### ISSUE THREAD

**Issue by keiex** [brookhong/Surfingkeys#812]
## Error details

SurfingKeys: 0.9.37

Browser: Chrome/67.0.3396.99 

## Context

I've tried:
map('<ArrowLeft>','<Ctrl-,>');
map('<ArrowRight>','<Ctrl-.>');

and

map('<Ctrl-ArrowLeft>','<Ctrl-,>');
map('<Ctrl-ArrowRight>','<Ctrl-.>');

but neither of those work, i know that you can map arrows and it works, but i can't make it work with those commands.

Thanks for the great Extension.

**Comment by cibinmathew** [comment]
@keiex if you are trying to map **Ctrl-,** to another key, try something like this
` map('<Ctrl-,>','E');`
