### ISSUE TITLE
Register inline query issue

### ISSUE THREAD

**Issue by rastaclaus** [brookhong/Surfingkeys#813]
## Error details

SurfingKeys: 0.9.26

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

URL: any
## Context
when i use example from https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query i got this when open any url:
Error found in settings: TypeError: Front.registerInlineQuery is not a function

**Comment by brookhong** [comment]
Some reviewer of addons.mozilla.org could not build the addon from source code I provided. And I missed the last minute to give him more detail instruction on how to build it. Then he disabled 0.9.37.

I have re-submitted latest version and build instructions, please just wait the latest version to be approved.

**Comment by rastaclaus** [comment]
Okay, I'll wait for the new version. Anyway, thank you for the great work! With respect.
