### ISSUE TITLE
PDF Viewer 情况下单词查询没有结果显示。

### ISSUE THREAD

**Issue by kohang** [brookhong/Surfingkeys#814]
###第一次报问题，因为实在太爱这个工具了。

## 问题：  PDF Viewer 模式下，按Q查单词可调用出窗口，却没有结果显示。
是我不会用？ 还是真的这个功能的问题？

**Comment by brookhong** [comment]
请按模版提交问题，模版里的信息有利于我分析可能产生问题的原因。
