### ISSUE TITLE
中国知网网页，必须禁用Surfingkeys才能正常检索

### ISSUE THREAD

**Issue by rLry** [brookhong/Surfingkeys#816]
浏览器：firefox
系统：windows1803
无论是开启还是使用alt-s临时禁用Surfingkeys，都只能检索出2条条目，只有在附加组件界面禁用Surfingkeys才能正常显示检索结果.换用chrome正常。

**Comment by rLry** [comment]
已解决。似乎是与firedog冲突。

**Comment by brookhong** [comment]
这个是在0.9.38里解决的, 与firedog无关, 你可以再启用firedog试试。
