### ISSUE TITLE
short Q: where does one get the list of all action_codes?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#819]
Not exactly an issue but for the life of me where does one  list of all action_codes?

I know im probably an idiot but how does one find all the commands such as the one to close the tab etc?

thx

Z

**Comment by lee-tts** [comment]
@brookhong ? If you can point me to somewhere it's written down (in the code even?) I will create a wiki page :)

**Comment by DecoyJoe** [comment]
@zeltak The shortcut reference can be found here: http://brookhong.github.io/2015/09/15/surfingkeys.html

**Comment by lee-tts** [comment]
Thanks Joe, but that's not really what we're after. 

This is the action code according to the readme on Github:

**Map a keystroke to some action**
    mapkey(keystroke, help_string, action_code, [options])


**action_code** | function, a Javascript function to be bound. If the function needs an argument, next pressed key will be fed to the function.

Action codes are probably just ... Javascript. But for someone not too familiar with js, there are few examples to follow and I haven't had time to dig through the source code to figure out how it's supposed to work.
