### ISSUE TITLE
Is this a fork of Vimium?

### ISSUE THREAD

**Issue by ryanmclaughlin** [brookhong/Surfingkeys#82]
Looks awfully similar and I see no credit. https://github.com/philc/vimium

**Comment by brookhong** [comment]
Hi,

Thanks for the question.

No, it is not, most code are new.

vimium is awesome, I used it for almost one year, and I also used [cVim](https://github.com/1995eaton/chromium-vim), which is better than vimium for me, for half a year.

This extension, Surfingkeys, is just another wheel. I did refer some code of vimium when creating this wheel, such as the [KeyboardUtils](https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/utils.js), will add credit to vimium soon.
