### ISSUE TITLE
Can't load custom settings from file

### ISSUE THREAD

**Issue by mgrimpo** [brookhong/Surfingkeys#822]
## Error details

SurfingKeys: 0.9.38a

Browser: Firefox 61.0.2, MacOS 10.13.16

## Context
Up until Firefox 61.01 Surfingkeys worked without any problems for me. After the Firefox update Surfingkeys 0.9.36 and 0.9.37 did not respond to any shortcuts at all and also didn't seem to load my external config file.
0.9.38a restored most of the functionality for me, but I still can't get Surfingkeys to load my config file.
When I enter the path  and click save in the settings, it does say "Loading settings from file: <path to my .surfingkeys.js>", but in effect nothing happens.

I can paste my custom settings from the file into the text box on the Surfingkeys settings page and that works as a work-around

**Comment by petobens** [comment]
I'm having the same problem.

**Comment by ericdwang** [comment]
This is also happening to me with Firefox 64.0 and Surfingkeys 0.9.42. These errors show up in the Browser Console on every page load: `Security Error: Content at moz-extension://.../_generated_background_page.html may not load or link to file://...`

Surfingkeys 0.9.41 on Firefox was fine, as well as 0.9.42 on Chromium. I also tried building the extension off the latest master branch (which still seems to be 0.9.41) but couldn't replicate the issue.
