### ISSUE TITLE
Updating patched Chromium

### ISSUE THREAD

**Issue by sevensidedmarble** [brookhong/Surfingkeys#824]
I saw on your blog an explanation of how to patch chromium to make surfingkeys work on every page, but it was on an older version... Will that still work on the newer versions?

Is there any chance we could get like a community PKGBUILD put together for a patched chromium for surfingkeys on the AUR for us Arch users? I know how to put together the PKGBUILD but I don't really know how to patch it... but if it was a patch that could be applied with a script we could make it work even for new versions of chromium.

**Comment by brookhong** [comment]
The patch does not work for all versions of Chromium, it needs a few change if there is an incompatible update from Chromium code base.

Plus building Chromium is not a easy task, it usually takes hours to build and dozens of gigabtyes disk space.
