### ISSUE TITLE
Firefox下无法保存配置

### ISSUE THREAD

**Issue by LArctic** [brookhong/Surfingkeys#828]
WIN10 62 Firefox 61正式版

你好，打扰了。我遇到了这几个问题：

1，如何指定配置文件？关于它的说明似乎是针对谷歌浏览器的，有关于Firefox的说明吗？
[img]http://img03.sogoucdn.com/app/a/100520146/DF8CECE8CD29AEB2374E447F38489EFE&oname=20180914215128.png[/img]

2，为什么自定义的配置无法保存？

我搜索到有个相同问题的帖子：https://github.com/brookhong/Surfingkeys/issues/777
但下面的回复："那一行有没有多余字符...我被坑过"，我实在无法理解。

3，请问如何清除所有默认配置，然后在配置只应用这两个热键呢？帮助文档都是在说配置文件的内容，完全没说配置文件如何操作啊。
（个人是程序小白，完全搞不懂VIM式操作，只想找一个在新Firefox下可用的快捷键定制扩展。）
```
mapkey('<Ctrl-Alt-Shift-F9>', '#3Close all tabs on left', function() {
    RUNTIME("closeTabsToLeft");
});
mapkey('<Ctrl-Alt-Shift-F10>', '#3Close all tabs on right', function() {
    RUNTIME("closeTabsToRight");
});

```

**Comment by mgrimpo** [comment]
至于1，和2，我有同样的问题#822

**Comment by CyshallChan** [comment]
同样的问题，Firefox下更改按键无法保存，麻烦作者看一下- - 。
