### ISSUE TITLE
How can I open a new tap with the address inputed? NOT SEARCH with it

### ISSUE THREAD

**Issue by gou4shi1** [brookhong/Surfingkeys#829]
In the bar after press 't'
If I input a address which don't match any history
It will use search engine to search it
But I think it should be same as the address line of browser
If the input is a address, just open it!

**Comment by marwy** [comment]
When you press 't' and paste in the address, you need to press the down arrow key and then press Enter key to actually go to that address. 
One way around it is to put this in your config file:
`settings.defaultSearchEngine = "";`
The downside of doing _that_ is that the address needs to include a protocol, so "example.com" won't work, and you need to use "http://example.com" or "https://example.com".
