### ISSUE TITLE
Can't write html tags at first try

### ISSUE THREAD

**Issue by bumbeishvili** [brookhong/Surfingkeys#83]
When I try to write less than sign in inputs, this small black box appears in bottom right corner and symbol is not written in inputs.

![untitled](https://cloud.githubusercontent.com/assets/6873202/17836307/078f3cd4-679f-11e6-8986-72e8c84818ad.png)

As I understand , this extension is written for programmers, so I think , '<' sign writing should not be restricted, because we are using it very often

**Comment by brookhong** [comment]
Hi, 

It's because that you're in insert mode when in textarea or input, and there is mapping `<Ctrl-i>` in insert mode to open vim editor.

You could press `<` again(twice in total) to insert `<`.

**Comment by bumbeishvili** [comment]
Can I override this behaviour?

**Comment by brookhong** [comment]
A new API will be provided for this,

    function iunmap(keystroke, domain) {
        if (!domain || domain.test(window.location.origin)) {
            Insert.mappings.remove(keystroke);
        }
    }

**Comment by brookhong** [comment]
Released in 0.5.7

    iunmap('<'); // to remove Ctrl-i mapping in insert mode

**Comment by bumbeishvili** [comment]
![up](http://screencrush.com/442/files/2013/03/thumbs-up.jpg)

**Comment by brookhong** [comment]
To input `<` directly, you don't need `iunmap('<');` from 0.6.5.
