### ISSUE TITLE
Scrolling broken on sites using `scroll-behavior: smooth`

### ISSUE THREAD

**Issue by b0o** [brookhong/Surfingkeys#837]
The relatively obscure CSS rule `scroll-behavior: smooth` conflicts with SurfingKey's scroll behavior.

Test this issue by applying `scroll-behavior: smooth` to the `<html>` element of a page, then try to use SurfingKeys to scroll that page using `j`, `k`, `G`, `gg`, _etc_. You should see some odd scroll acceleration/easing and (especially in the case of `G`/`gg`) the page should stop scrolling earlier than normal.

Some sites which use this style in the wild: 
- [Mozilla Developer Network ](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook)
- https://mathiasbynens.be/notes/html5-id-class
- https://www.hotukdeals.com/

See https://github.com/philc/vimium/pull/3111 for a solution to the same issue in Vimium. 

See also [this discussion](https://news.ycombinator.com/item?id=18210132) on HN.

I will try to submit a PR if I get around to it, but no guarantees as I am very busy currently. Thanks!

**Comment by brookhong** [comment]
Thanks!

Fixed in 0.9.39.
