### ISSUE TITLE
shortcuts doesn't work on the page "chrome-extension://"

### ISSUE THREAD

**Issue by salcin** [brookhong/Surfingkeys#84]
First I want to thank you for this wonderful project. I discovered hardly but I love it already.

I have a little issue when i'm at the address "chrome-extension://" for example with l'extension onetab. I can not use the shortcuts.

Is it possible to circumvent this problem?

Thank you in advance,

**Comment by brookhong** [comment]
Chrome does not allow that, I also need it.

**Comment by ashkrosh** [comment]
Guys are you sure this is still impossible? I see other chrome extensions having access to "chrome-extension://" resources, of course with an explicit user consent.
