### ISSUE TITLE
document what "capture" means

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#845]
The help shows the default bindings:

- `yG` Capture current full page
- `yS` Capture scrolling element
- `yg` Capture current page

but I can't find any explanation anywhere what "capture" means in this context, or why it would be useful.  It would be great if this was documented explicitly.

**Comment by aspiers** [comment]
Thanks! 😁

**Comment by x61** [comment]
I take it that Capture provides the means of taking screenshots of a page. When I do `yS`, `yG`, for example, I see that the screenshot is "captured" but there is no option to save the captured page. Also, it would be good to automatically put the captured file in Download. The primary issue is there is no way to save the captured page.

**Comment by polinom11** [comment]
What's the difference between:
yG Capture current full page
yS Capture scrolling element
