### ISSUE TITLE
feature request: open a link in a specific Firefox Container

### ISSUE THREAD

**Issue by petr-tik** [brookhong/Surfingkeys#846]
Thanks for a great extension that keeps us all further away from Carpal tunnel syndrome and makes browsing that much easier. Great work and your effort is appreciated! 

An idea for a feature. Judging from #https://github.com/brookhong/Surfingkeys/commit/de504487668fdaafa62fd36882e060703fc8ec1d, firefox exposes an API to get current tab's container ID. 

Is it possible to add to settings a rule that resolves the URL that needs to be opened and opens it in a tab with a specific firefox container. 

eg. if I have a container called "FaceGooAmazon"
It would be great to add a function that opens links like
*.facebook.com
gmail.com
maps.google.com
google.co*

in such a container. Happy to work on a PR, if someone can point to good reading material. 

Thanks!

**Comment by beanaroo** [comment]
Any more information on this? I'd love to be able to avoid relying on the new tab button

**Comment by hatredholder** [comment]
@brookhong why was this issue closed? is this a feature in surfingkeys now?

**Comment by brookhong** [comment]
It was closed as a stale issue, just committed a change for this, please have a try if you're using your own build. https://github.com/brookhong/Surfingkeys/commit/1bb8108e612a3e6cba0c292f0fc5b7df459a9b3d

**Comment by hatredholder** [comment]
is there a way to make it choose a link via hints first and choose the container through omnibar second?
