### ISSUE TITLE
[Feature Request]Better link hints letter combination

### ISSUE THREAD

**Issue by DrakeXiang** [brookhong/Surfingkeys#848]
The priority of letter combination should be:
1. Single letter (e.g. A/B/C..)
2. Two identical letters (e.g. AA/BB/CC...)
3. Rest combinations

The hint now often requires to look carefully to recognize if it's 'ED' or 'DE', with single letter or two same letters, this would be a lot easier, even with default setting only trigger left hand keyboard area, you got 30 links covered in these two simple combination

**Comment by Madd0g** [comment]
I very much agree, it should also take the character order into account, so if the `Hints.characters` starts with `hjkl` it should create doubles of those letters first.

**Comment by DrakeXiang** [comment]
oh...wait, I just find out that 1 and 2 cannot exist at the same time... that's awkward.. unless we use a leader key (e.g. space) to prefix the single letter hint
