### ISSUE TITLE
Global quickmarks with lowercase and new tab and re-use if found?

### ISSUE THREAD

**Issue by Madd0g** [brookhong/Surfingkeys#853]
I'm interested in the following behavior, is it possible to achieve with settings?

* `m<a-z0-9>` to create a global mark (lowercase letters + numbers)
* `'<a-z0-9>` open in a new tab by default, but switch to it if already open

Basically I'm not interested in local marks at all and want to avoid pressing `Ctrl+'` (for new tab) and shift for global marks.

This is the behavior I had configured with vimium and I really like the simplicity.

**Comment by Madd0g** [comment]
Due to the awesome API SK has, I managed to solve half of the problem myself :)

With this I can use lowercase letters to navigate to global marks in a new tab. Pretty happy. Now if it could also select the tab instead of opening a new one every time... 

```js
mapkey("'", '#10Jump to vim-like mark', function(mark) {
    Normal.jumpVIMark(mark.toUpperCase(), true);
});
```

**Comment by fiocui** [comment]
@brookhong Open a vim-like mark with one letter and save it to the default settings

**Comment by vogler** [comment]
How do I open a mark in the current tab?

**Comment by brookhong** [comment]
Please try `Shift-Enter`, and read https://github.com/brookhong/Surfingkeys#key-bindings-in-omnibar

**Comment by vogler** [comment]
I meant opening a mark directly with `'x`. Using the omnibar defeats the purpose with `om` `x` `tab` `shift-enter` (best case, first result).
