### ISSUE TITLE
钉钉扫码自动跳转,无法扫码!

### ISSUE THREAD

**Issue by summerKK** [brookhong/Surfingkeys#857]
## Error details

SurfingKeys: 0.9.40

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

URL: https://oapi.dingtalk.com/connect/oauth2/

## Context

打开需要钉钉扫码的网站的时候,还没有扫码自动跳转.显示
![1](https://user-images.githubusercontent.com/19187969/48330962-8c169b80-e689-11e8-9bd4-af886d2b73f8.png)

我在隐身模式没有加载 surfingkeys插件就不会出现这个问题
![2](https://user-images.githubusercontent.com/19187969/48330984-a0f32f00-e689-11e8-968d-fc5dfd23d563.png)

**Comment by msconfig711** [comment]
我也遇到了同样的问题。。。。只好使用没装surfingkeys的其他浏览器了

**Comment by vfbiby** [comment]
我也遇到了这个问题，一打开就自动跳转了。请作者处理一下。

**Comment by brookhong** [comment]
这看起来像是钉钉的问题, 你只要在Inspect tool里选择`qrcode.htm`, 然后在console里输入

    top.postMessage("a", "https://oapi.dingtalk.com/")

再回车就会跳到无权限页面。

![image](https://user-images.githubusercontent.com/288207/50054886-2767c880-0182-11e9-8303-26c8e978f87c.png)

有途径的用户请给钉钉提个bug，让他们修复下。
