### ISSUE TITLE
Avoid parentheses in find command when searching multiple words

### ISSUE THREAD

**Issue by Madd0g** [brookhong/Surfingkeys#858]
I'm wondering if I can do this myself somehow, or if this should be a feature request. `statusbar.js` doesn't look very hackable.

Searching for multiple words is my single biggest use of regex in the browser, I want to write `apple|orange` in find without putting parentheses around them `(apple|orange)`, is there a reason not to surround all regex searches? Maybe I don't know all the capabilities of the find feature, but it seems like always surrounding the expression with parens should be harmless?

Thanks

**Comment by lee-tts** [comment]
Why do you need parentheses? It works fine for me if I just type apple|orange.

![image](https://user-images.githubusercontent.com/39074607/48389863-436aeb00-e73a-11e8-9782-74d0e47ed532.png)

As for parentheses being harmless, they have a function in regex, so they can't be used un-escaped.

**Comment by Madd0g** [comment]
huh, that's weird, it does work, I thought I tried multiple times before opening this ticket.
