### ISSUE TITLE
wierd gmail issues latest release?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#860]
## Prelude
* Could you find answer in below documents?

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
yes 

## Error details
gmail cursor position jumps around when surfinkeys is enabled 
SurfingKeys: <version>

Browser: <version><os version>
osx chrome and ubuntu linux

URL: <The_URL_Where_You_Find_The_Issue>
gmail.com

**You could simply click dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.**
SurfingKeys: 0.9.40

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by PrestanceDesign** [comment]
Same issue here since two or three days.

**Comment by brookhong** [comment]
`gmail cursor position jumps around` could you explain more?

which cursor do you mean?

**Comment by PrestanceDesign** [comment]
For me, when I click **reply** to an email, the cursor loose the focus when I begin to typing.
On multiples lines email, the cursor sometimes jump at the first line.

**Comment by lvalkov** [comment]
Not sure, but might be related. Ever since the Nov 10 update, on sites where tag-insertion is supported, pressing `Ctrl` will bump the cursor out of the inserted tag to the end of file. You can test it with GitHub's reply box here. Insert a tag, press `Ctrl`, cursor just jumped.

**Comment by zeltak** [comment]
> "For me, when I click reply to an email, the cursor loose the focus when I begin to typing.
> On multiples lines email, the cursor sometimes jump at the first line."
> 

thats exactly what happens here.

z

**Comment by brookhong** [comment]
@PrestanceDesign and @zeltak  I can not reproduce that by clicking the `reply` button. For me, the cursor stays in the textarea well. Could you both reproduce lvalkov's issue?

@lvalkov I could not reproduce your issue too.

**Comment by PrestanceDesign** [comment]
@brookhong Do you have tried on the new Gmail interface ?

I just tried on the classic version and no bug here.

**Comment by brookhong** [comment]
Guys, please put below line in your settings and see if it could solve your problems:

    settings.cursorAtEndOfInput = false;

**Comment by zeltak** [comment]
hi!

yeah that seems to have worked and resolved this for me

**Comment by PrestanceDesign** [comment]
Great, this work again! 
Thx Mr @brookhong ;)

**Comment by brookhong** [comment]
Sure, with 0.9.41 installed, you could remove it safely.
