### ISSUE TITLE
Cursor position in input box gets reset on mouseclick/tab change

### ISSUE THREAD

**Issue by steerio** [brookhong/Surfingkeys#861]
## Error details

Cursor position in text fields on React-powered (that seems to be the connection) sites get reset to the first character if one tries to reposition it using a mouseclick into text (or to select text with the mouse in order to overwrite or cut it), or after moving to another tab. This means that moving the cursor is only possible with the keyboard.

The problem goes away by switching SK off with alt-S. The problem started appearing today.

SurfingKeys: 0.9.40

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

URL: Facebook.com, messenger.com

## Context

Start writing e.g. a Facebook comment, click into your text, continue typing - boom, you're inserting at the beginning of the text. Move to another tab, come back, same effect.

**Comment by steerio** [comment]
This might be related to #860, in which case the React connection is bogus, or at least not the full picture.

I just checked Gmail. Repositioning the cursor with a mouseclick works fine, but changing tabs and back will reposition the cursor to the *end* of the content in the subject box of the compose dialog for example.

In fact the same happens in this very input field on Github. Goes away with alt-S, comes back right away after another alt-S.

**Comment by steerio** [comment]
Same issue in Disqus.

**Comment by brookhong** [comment]
Guys, please put below line in your settings and see if it could solve your problems:

    settings.cursorAtEndOfInput = false;

**Comment by dmfay** [comment]
I was noticing it on Invision and the LinkedIn messenger popin and that appears to have stopped it in both places, at least at a quick test. What's that setting supposed to do?

**Comment by brookhong** [comment]
The setting (default value as true) makes cursor to be put at end of the input when entering Insert mode.

But it should be false in some cases, 0.9.41 is released to fix this issue.
