### ISSUE TITLE
Pressing 'Enter' in Ace editor will sometimes incorrectly close the editor in multiline fields

### ISSUE THREAD

**Issue by chaorace** [brookhong/Surfingkeys#864]
Normally, pressing 'Enter' in the Ace editor will either input a new line or close the editor.
The editor is only supposed to close like this if the field being edited is single-line.

Currently, however, this will also happen when editing multiline fields if a single-line field on the same page has also been edited.

Steps to replicate:
1) Find web-page with both a single-line field and a multi-line field (example: Github 'Submit new issue' page)
2) Edit the single-line field, press enter
3) Edit the multi-line field, press enter to attempt inserting a new line. This should close the editor.

This issue has been affecting me in both Firefox and Chrome

I think it may have something to do with this line:
https://github.com/brookhong/Surfingkeys/blob/29f96ec61294d0ce79780af952b690638b0d6033/libs/ace/keybinding-vim.js#L870

**Comment by brookhong** [comment]
The Ace editor is a Vim editor, to insert a new line, you need enter Vim's insert mode first with `i`, then press `Enter`.

If you press `Enter` directly in Ace editor, it will close the editor, it is by design.

**Comment by brookhong** [comment]
I see that you have called the Vim editor 3 times, and the problem you're talking about happened at 3rd time.

But I don't see what's the difference of your operations between the 3rd and the 2nd or 1st, could you please describe what you have done in the 3rd time?

**Comment by chaorace** [comment]
The only difference is that I've opened the ace editor on a single-line input field first. The editor gets stuck in 'close on enter' mode which is only supposed to apply in single-line fields
