### ISSUE TITLE
Incorrect mode displayed in Slack

### ISSUE THREAD

**Issue by masaeedu** [brookhong/Surfingkeys#865]
## Error details

SurfingKeys: 0.9.41

Browser: Firefox 63.0

OS: Linux morpork 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux

URL: https://functionalprogramming.slack.com

## Context

Surfingkeys reports the wrong mode when switching between Slack channels; when you enter a new Slack channel the cursor is focused on the text field at the bottom (as is visible from the blinking cursor), but Surfingkeys reports "Normal" mode.

![image](https://user-images.githubusercontent.com/3674056/48686103-46c20480-eb88-11e8-8eb2-755ec9d1b590.png)

**Comment by brookhong** [comment]
Do the shortcuts from Normal mode work in that time, such `gg` / `G` / `E` / `R` etc?

If yes, then it's fine, otherwise that might be a problem. And will it enter into Insert mode after you pressing `i` or clicking the input with mouse?

**Comment by masaeedu** [comment]
@brookhong No, keystrokes at that point type into the text field, which is primarily why it's an issue. I use that mode indicator to know whether to hit escape before using shortcuts, but in this case it seems to be misreporting the status.
