### ISSUE TITLE
doesn't work on inbox.google.com

### ISSUE THREAD

**Issue by adrian-gierakowski** [brookhong/Surfingkeys#866]
## Error details

doesn't work on inbox.google.com

SurfingKeys: 0.9.41

Browser: Chrome/70.0.3538.102, (Macintosh; Intel Mac OS X 10_12_6) 

URL: inbox.google.com

## Context

the keyboard shortcuts such as `f` or `t` don't do anything. There is no error/warnings in dev console
previously I thought it was due to #746 but this one has now been fixed and it still doesn't work

**Comment by brookhong** [comment]
All shortcuts don't work or just some of them?

Everything works fine for me.

![image](https://user-images.githubusercontent.com/288207/48742768-423a4080-ec9b-11e8-89b7-662eaf79572a.png)

**Comment by adrian-gierakowski** [comment]
@brookhong after removing and reinstalling the extension everything works. Thanks for your great work!
