### ISSUE TITLE
Surfingkeys interferes with Chrome PDF display

### ISSUE THREAD

**Issue by fnurl** [brookhong/Surfingkeys#87]
Viewing a PDF in Chrome results in a black, blank page when Surfingkeys is enabled. After disabling Surfingkeys, the PDF is displayed.

Here is a PDF that suffers from this issue: http://www.axmag.com/download/pdfurl-guide.pdf

I am using Surfingkeys 0.5.9 on Chrome 52.0.2743.116 (64-bit) and OS X 10.11.6.

**Comment by soultice** [comment]
This issue seems to appear again. I need to completely disable Surfingkeys to be able to view PDFs in chrome.

**Comment by pacop** [comment]
Same here

**Comment by brookhong** [comment]
So `;s` does not work for you guys?

**Comment by soultice** [comment]
checked 2 minutes after I made my comment, ;s is working but the problem is still the same: the pdfs are blank if surfinkeys pdf plugin is enabled.

**Comment by yuyang0** [comment]
I also got this problem
