### ISSUE TITLE
Feature Request: userAgent documentation and UI improvement.

### ISSUE THREAD

**Issue by EvanCarroll** [brookhong/Surfingkeys#871]
When I hit `:` one of the things that I can autocomplete is `userAgent`. This interests me. Frequently I prefer to use read mobile sites than desktop sites. I use `i3` and there is less bloat on a mobile site, and they tend to make better use of vertical space without assuming they're on a wide screen monitor.

Documentation fixes
====
I was new to Surfing Keys ,and didn't know how to use the `userAgent` setting. To set the user agent, you use a space:

    : userAgent new user agent string

I thought it would be `:set userAgent="string"`, but I tried `:userAgent('foo')` and `:userAgent=foo` just didn't try it with the space. 

It would be cool if this was documented in <kbd>?</kbd>

Preset options
====

Though I still think it would be cool to have a few options there (for mobile).

UserAgent per-site
====

It would be cool to be able to apply and remember a user agent for just one site. Rather than global for the whole browser.

**Comment by EvanCarroll** [comment]
To set the user agent, you use a space:

    : userAgent new user agent string

I thought it would be `:set userAgent="string"`, but I tried `:userAgent('foo')` and `:userAgent=foo` just didn't try it with the space. 

Though I still think it would be cool to have a few options there (for mobile).

**Comment by EvanCarroll** [comment]
Wow. I'm looking forward to seeing this. You're awesome @brookhong.

**Comment by brookhong** [comment]
I closed this because of the age of the issue, feel free to reopen it if you still hope this to be implemented.

**Comment by EvanCarroll** [comment]
I can't reopen. You mean you want me to resubmit it as a new issue?

**Comment by brookhong** [comment]
The command been removed since it is rarely used but need an extra permission `webRequest`. Related issue #2147.
