### ISSUE TITLE
visual mode selecting parent tag

### ISSUE THREAD

**Issue by lluke777** [brookhong/Surfingkeys#872]
## Feature request
SurfingKeys: 09.38
Browser: Chromium 66.0.3359.139 (64bit), Windows 7 64bit
URL:  https://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118
## Context
When I want to select whole paragraph sometime there are inner / child html tags inside and Surfing keys catches (`v` key or `zv` keys) these child tags instead whole paragraph. It would be nice to have option to select whole paragraph or jump to parent tag so whole operation would be faster. 
You can check at above url that after `v` or `zv` key press there are only `<code>` tag marked with letters but `<p>` tag is not marked

**Comment by brookhong** [comment]
This feature has been implemented in 0.9.42.

Just press `p` to expand selection to parent element in visual mode.
