### ISSUE TITLE
From hint -> possible actions

### ISSUE THREAD

**Issue by Madd0g** [brookhong/Surfingkeys#875]
`Hints.create` is the wild wild west, I have like 7 different ones and if I don't use them for a while I forget the shortcuts and forget they even exist.

Would be nice to have a "registry" for them like we have with the mapped keys, so I could run one special command and get a menu after picking the hint instead of an action.

Does that make sense? Do you have the same problem with custom `Hints.create` functions?

**Comment by dufferzafar** [comment]
@Madd0g I'm new to surfingkeys and want to experiment with Hints. Can I have a look at what you custom Hints.create function you have?
