### ISSUE TITLE
按b进入书签搜索页后无法翻页

### ISSUE THREAD

**Issue by Rentu** [brookhong/Surfingkeys#878]
每页显示10个,怎么才能看到之后的记录呢?

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E6%90%9C%E7%B4%A2%E6%A0%8F%E6%8C%89%E9%94%AE
* `Ctrl-.` 显示下一页搜索结果
* `Ctrl-,` 显示上一页搜索结果
