### ISSUE TITLE
Feature: add minimum browser version in manifest

### ISSUE THREAD

**Issue by hbt** [brookhong/Surfingkeys#879]
in manifest.json please add:

`"minimum_chrome_version": "69",` or whatever the minimum is for this extension.

Rationale:

Recent code using `flatMap` is only supported at version 69
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#Browser_compatibility

**Comment by brookhong** [comment]
Thanks for reporting this.

Reference of `flatMap` is newly committed, I'm not aware of that it is only supported since 69.
