### ISSUE TITLE
Surfingkeys interferes with Google Maps

### ISSUE THREAD

**Issue by xcv58** [brookhong/Surfingkeys#88]
It causes a blank page for https://www.google.com/maps

**Comment by brookhong** [comment]
Thanks, but I could not reproduce it.

**Comment by xcv58** [comment]
Chrome Version 52.0.2743.116 (64-bit)
OS: Mac OS EI Capitan Version 10.11.6 (15G31)

I'll try to use a fresh profile to reproduce this issue.

**Comment by xcv58** [comment]
I reset my Chrome profile and it fixed. Thank you!
