### ISSUE TITLE
Activating extensions through the keyboard

### ISSUE THREAD

**Issue by rpietro** [brookhong/Surfingkeys#881]
This is probably easy but I just couldn't find the answer: is there a way to activate an extension using a keyboard shortcut?

**Comment by brookhong** [comment]
It is impossible with official chrome from Google, as an extension is not allowed on some pages, let alone to control other extensions.

But you can try my custom build of Chromium, please see https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html
