### ISSUE TITLE
Is it possible to have a hybrid URL lookup/search like the google omnibar?

### ISSUE THREAD

**Issue by alok** [brookhong/Surfingkeys#883]
## Prelude
* Could you find answer in below documents? No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? Yes

## Context

**Please replace this with a description of how you were using SurfingKeys.**

I use the google omnibar both to find relevant URLs and to google search. This ability seems to be split in Surfingkeys, where you can do one (with `t`) or the other (with `og`), but not both at the same time. Is there a way to do this?

**Comment by EvanCarroll** [comment]
My complaint is precisely the opposite and I think you're wrong. If you hit t and you type "Adsfojdsaofkdsaofke" does it not take you to a Google Search of that? It does for me and **I hate it**.

**Comment by Madd0g** [comment]
@EvanCarroll - actually if you don't have a default search engine defined, it doesn't happen

    settings.defaultSearchEngine = '';

**Comment by brookhong** [comment]
Closing this as it seems not to be a favorable feature.
