### ISSUE TITLE
shortcuts are not listed in a logical order

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#884]
SurfingKeys has a lot of shortcuts, so it's hard to remember them all and I find myself pressing `?` a lot to see the help which lists them all.  However I find it quite hard to find the right shortcut quickly, because within each section related shortcuts don't seem to be grouped together.

For example, the following shortcuts are all related to tab selection:

- Go to the first tab
- Go to the last tab
- Go one tab left
- Go one tab right
- Choose a tab

but they are listed in three different places within the "Tabs" section.  This is just one example but there are several other examples like this.  Would it be possible to group the shortcuts together in a more logical way?

**Comment by Madd0g** [comment]
also, if you're changing that screen, please add a filter to search for commands, the screen is huge and once you start adding custom actions it becomes huger!

(it also looks a bit funky when the page is zoomed in)

**Comment by brookhong** [comment]
You can use `/` on help popup.

**Comment by aspiers** [comment]
Sorry @brookhong, searching is useful, but it is not a complete solution.  I already used `/` a lot, but that only works when you are searching for one specific thing.  Grouping related shortcuts together is needed to make them easy to discover and learn as a group.
