### ISSUE TITLE
Can't exit github comment insert boxes with escape key

### ISSUE THREAD

**Issue by petobens** [brookhong/Surfingkeys#886]
I'm using latest version on latest chromium. I've recently noticed that I cannot exit insert mode in Github comment boxes (such as this one) by pressing the escape key. 
A similar thing happens with gitlab pages.

Thanks in advance for looking into this.

**Comment by petobens** [comment]
Hi @brookhong any updates on this? I find it terribly annoying and maybe there is a fix. Also I don't know if this is related to https://github.com/brookhong/Surfingkeys/issues/140 or not. Thanks in advance for the help.

**Comment by brookhong** [comment]
Already fixed.
