### ISSUE TITLE
Search link or text depending on contents

### ISSUE THREAD

**Issue by alok** [brookhong/Surfingkeys#888]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md) 

No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)? 

Yes.

## Error details

SurfingKeys: 9.4.2

Browser: Latest stable chrome, MacOS 10.12

## Context

I notice that you can use `cc` to open the selected link from the clipboard. Is there a way to do this?:

1. If the contents of the clipboard are a link, go to that link (in a new tab).
2. If the contents of the clipboard are *not* parseable as a link, do a google search.

`sg` does the latter and `cc` does the former, but what I'd like is a mapping that intelligently switches between them.

**Comment by brookhong** [comment]
Closing this for similar reason as #883.
