### ISSUE TITLE
Key binding not working in google or duckduckgo

### ISSUE THREAD

**Issue by yotama9** [brookhong/Surfingkeys#893]
## Error details

SurfingKeys: 0.9.42

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.106

URL: www.google.com/www and duckduckgo.com

## Context

The key binding does not work on these sites. There appear to be some recent update to these websites as the it used to work.

**Comment by atomdmac** [comment]
This happens for me on quite a few sites (including certain pages on GitHub, though I haven't been able to discern why it works sometimes and doesn't for others).

For sites that are already hotkey-heavy (like many Google products) that makes some amount of sense as there might be collisions between hotkey assignments but this seems to happen even on some basic web pages.  (For example: http://www.keyboardmaestro.com/main/)
