### ISSUE TITLE
Possible to map 'Ctrl-[' to 'Esc' in ACE editor popup box?

### ISSUE THREAD

**Issue by ljohnston** [brookhong/Surfingkeys#897]
I'm wondering if it's possible to map 'Ctrl-[' (or any key) to 'Esc' in the Ace editor for form field input? In insert mode, 'Ctrl-[' cancels insert mode, but I'd like to be able to close the editor input box (from normal mode) with 'Ctrl-['.

The ACE editor input box can be closed with `<Esc>`.

I tried the following in my surfingkeys settings, but it didn't work:

`aceVimMap('<Ctrl-[>', '<Esc>', 'normal');`

Thanks,
Lance

**Comment by meijieru** [comment]
Any possible solution?
I use `<Ctrl-[>` to replace `<ESC>` in vim and suffer from this inconsistency.

**Comment by brookhong** [comment]
`Ctrl-[` works as `Esc` for me on MAC without bother to add config.

**Comment by spigelli** [comment]
Doesn't work on arch or windows for me

**Comment by milanglacier** [comment]
> `Ctrl-[` works as `Esc` for me on MAC without bother to add config.

I am using macbook air m1 now. `<c-]>` cannot leave edit area, only esc works.
