### ISSUE TITLE
Emoji completion makes entering times in Google spreadsheets difficult

### ISSUE THREAD

**Issue by cumber** [brookhong/Surfingkeys#898]
Somewhat related to #282.

I need to enter times of day into cells in a Google spreadsheet reasonably often. When I type something like `8:45`, I then want to hit <kbd>Enter</kbd> or <kbd>Tab</kbd> to move to the next cell. Unfortunately the emoji completion list has popped up, and neither of those keys will work (<kbd>Enter</kbd> accepts the emoji, <kbd>Tab</kbd> just selects a different one). Trying <kbd>Esc</kbd> to close the popup results in the spreadsheet cancelling the whole edit, leaving the cell blank.

For now I've worked around this by setting `settings.startToShowEmoji = 3`, but it was very confusing for a while (I didn't even know Surfingkeys had emoji completion; at first I thought it was something Google sheets was doing).

Slack appears to prevent this form being a problem by only triggering emoji completion if the colon was typed following whitespace, another emoji, or nothing at all. (Slack also doesn't find any emoji for most 2-digit numbers, whereas Surfingkeys pops up a list of emoji for every time I tried; is this because it's searching the numeric identifiers as well as the text labels?).

Adopting a similar rule would prevent emoji completion being triggered when typing times, ipv6 addresses, code in certain languages (e.g. things like `a:as` or `y:ys` are not-uncommon fragments of Haskell code that trigger emoji completion), colon-separated key-value pairs without spaces in general (e.g. `foo:bar`).

If not, I'd suggest making `settings.startToShowEmoji = 3` the default, since times are a *very* common 2-character false positive.

**Comment by Pivert** [comment]
OMG, after 2h searching, I finally found out that this terrible behaviour is coming from SurfingKeys. Definitely 12:45  should not turn to 12🙅 !! The Readme also mention another way to disable this behaviour : iunmap(":"); 



Those Emoji also trigger another bug, at least in Google Sheet:
- If you enter a time like 12:45 in sheet, it displays the emoji, but if you move to another cell, the emojis will stay in foreground, and it will be impossible to make them disappear without remembering the cell from which it was triggered, and adding a space or any other way. An other option to overcome this bug if you forgot which cell it's comming from, is to key in : in any other cell.

The emoji conversion should only be proposed when : follows a space, not directly attached like when you specify a time. 
In applications like Google Sheet, SurfingKeys cannot be disabled with Alt+s, and is completely useless. I would propose SurfingKeys to auto-disable itself (or most of it) in such application with too many possible shortcuts or maybe based on the Keyboard key listening from the base web application. An option to auto-disable SurfingKeys when Alt+s is already mapped maybe ?

**Comment by dominsights** [comment]
Just to make it clear, to disable the emoticons you must add `api.iunmap(":");` to the Surfingkeys settings. You need to enable advanced mode and copy the setting there as in the image below:

![imagem](https://user-images.githubusercontent.com/23655208/195608651-80ccd342-58e1-4a7c-b07c-63f291670fd4.png)

**Comment by brookhong** [comment]
Emoji completion has been turned off by default.
