### ISSUE TITLE
need way to pass Escape through pass-through mode

### ISSUE THREAD

**Issue by aspiers** [brookhong/Surfingkeys#908]
When in pass-through mode, sometimes it's useful to be able to pass Escape through to the website.  Example use case:

- Go to a GitHub page
- Press `Alt-i` to enable pass-through mode
- Press `?` to see the GitHub keyboard shortcuts modal dialog
- Now I want to hide the GitHub dialog

However Escape simply cancels pass-through mode, so this is currently impossible.  What seems to work instead is pressing Escape twice: the first cancels the mode, and the second somehow reaches the website.  But of course then I have to press `Alt-i` to switch back into pass-through, which is not ideal.

SurfingKeys: 0.9.42

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

**Comment by aspiers** [comment]
Yes but it has the other disadvantages described [here](https://github.com/brookhong/Surfingkeys/issues/656#issuecomment-359719154).

**Comment by brookhong** [comment]
Nice finding.

But the problem here is that SurfingKeys has no idea whether a Site has handled `Esc` or not.

**Comment by brookhong** [comment]
When in PassThrough mode, user presses `Esc`, currently it will quit PassThrough mode. If we need pass `Esc` through, we need know when we should pass it through and when we should just quit PassThrough mode. Another work-around here is we won't use `Esc` to quit PassThrough mode, but which will break the usual flow, as people are used to use `Esc` to escape from something.

**Comment by PrestanceDesign** [comment]
Maybe toggle PassThrough with the same keys`Alt+i` ?

**Comment by aspiers** [comment]
[**@PrestanceDesign**](https://github.com/PrestanceDesign) [commented](https://github.com/brookhong/Surfingkeys/issues/908#issuecomment-457186136 "2019-01-24T12:53:42Z - Replied by Github Reply Comments"):
> Maybe toggle PassThrough with the same keys`Alt+i` ?

Ahh, that's an interesting idea, but I agree with @brookhong that not everyone would expect or like this.  So maybe make it an option whether PassThrough is exited via `Esc` or `Alt+i`?  The default configuration would be the current behaviour, and people like me could reconfigure the exit key to be `Alt+i` instead of `Esc`.

**Comment by lkhphuc** [comment]
Having the same problem. Would be great if there is a way to change the exit Passthrough mode without the Escape key.

**Comment by brookhong** [comment]
Please try ephemeral Passthrough mode with `p`, see more at https://github.com/brookhong/Surfingkeys/blob/936284a3c4abd4c859b5157a5dd8f945671ba724/README.md#passthrough-mode
