### ISSUE TITLE
Select hints by their text/content

### ISSUE THREAD

**Issue by BlackLight** [brookhong/Surfingkeys#912]
This feature is present in all the other extensions I have tried (cVim, Vimium, Vrome, vimperator, pentadactyl...) but not in Surfingkeys.

When in hint mode I would like to be able to select the element either by hint code/string or part of the element text/content.

For instance, if a page comes with a big button with "Login" text, I'd like to select that button in hint mode by starting typing "log".

**Comment by brookhong** [comment]
Use below settings:

    Hints.numericHints = true;

**Comment by BlackLight** [comment]
Thanks, that worked!
