### ISSUE TITLE
[Suggestion] Swap the visual mode to appear first with a word preselected on a caret

### ISSUE THREAD

**Issue by vlad-terin** [brookhong/Surfingkeys#913]
## Context

- Using Visual mode to quickly search text on page
- to search for a word in visual mode currently you have to click `v` to go into *visual caret* mode, select a word using either `w` or `e`, then click `v` to go into *visual range* mode, click `sg` to search with google

## Suggestion

1. Have the word under the cursor preselected
2. *optional* - Swap visual caret and range modes

**Comment by brookhong** [comment]
Please try `zv`.
