### ISSUE TITLE
[Feature Request] Import vimium settings to Surfingkeys

### ISSUE THREAD

**Issue by az-pz** [brookhong/Surfingkeys#917]
## details
I have customized vimium for my needs ( mainly key mappings and website specific partial disabling). Is there any way to import those settings? It would be really helpful in switching from vimium to surfing keys. 

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
Not in my plan.
