### ISSUE TITLE
搜索栏 有乱码 是缺少什么字体呀

### ISSUE THREAD

**Issue by tabris233** [brookhong/Surfingkeys#921]
RT

系统： manjaro-deepin

![_ _20190202224230](https://user-images.githubusercontent.com/29500388/52165553-5b507a80-273d-11e9-9922-775547c9bf85.png)

**Comment by yech1990** [comment]
Lack of emoji font.

```bash
pacman -S note-fonts-emoji
```

then restart PC.

**Comment by tabris233** [comment]
> Lack of emoji font.
> 
> ```shell
> pacman -S note-fonts-emoji
> ```
> 
> then restart PC.

thank you very much .

but pakage's name is `noto-fonts-emoji`, not `note-fonts-emoji`
