### ISSUE TITLE
[Feature Request] Ability to yank in markdown format current website url

### ISSUE THREAD

**Issue by vlad-terin** [brookhong/Surfingkeys#922]
## Context

I have a code that yanks urls on a page in vmode following markdow format: 
```js
vmapkey('mly', "Markdown link", function () {
    Clipboard.write('[replaceit](' + window.getSelection().toString() + ')');
});
```

This is only possibly for links on the page. 

**Is it possible to yank current website url following markdown link format?**

**Comment by Madd0g** [comment]
current? like this?

```js
Clipboard.write('[replaceit](' + window.location.href + ')');
```

**Comment by vlad-terin** [comment]
@Madd0g works like a charm!
