### ISSUE TITLE
[Feature Request] Ability to preselect line/sentence in visual mode

### ISSUE THREAD

**Issue by vlad-terin** [brookhong/Surfingkeys#923]
## Context

**Currently, there is an option to preselect a word in visual mode using `zv`**

To select a line, you would need to go into visual mode and enter `$` to select a line

Is it possible to preselect a line/sentence similar to a word preselect with `zv`

**Comment by brookhong** [comment]
No such single mapping now, but you use `v` to enter visual mode, then press `p` to select parent element, which should be the line/sentence you would like.
