### ISSUE TITLE
Vim marks in tabs

### ISSUE THREAD

**Issue by jaimehrubiks** [brookhong/Surfingkeys#924]
I'm a long user of this extension but for some reason never used global marks (capital marks such as mA). I see that whenever I create one, it seems to be only saving the URL as if it was a bookmark. Maybe I'm missing something but it seems to be that it has the same utility as bookmarks, but with letters.

What I would find more logical is that tabs were considered as files in vim such as if I am in tab 15 and save mA, then I move to tab 1, pressing 'A should take me back to tab 15, allowing to move very fast between tabs.

Is there an alternative to what I want to accomplish? Would this feature be of interest for the community if implemented? I could help in that case.

**Comment by Madd0g** [comment]
If you end up doing that, please make it configurable via the API.

I'm using the following code to avoid pressing shift for my global marks. I would love if your new solution would be just another argument here (maybe the 2nd argument (true = newTab) can become an object?)

```js
mapkey("`", '#10Jump to vim-like mark', function(mark) {
    Normal.jumpVIMark(mark.toUpperCase(), true);
});
```

**Comment by brookhong** [comment]
Some changes have been made for vim-like marks in 0.9.44, since which there is no differentiation between local and global marks, all marks are global, and if a mark has been opened, `jumpVIMark` will jump to the tab automatically instead of open it.
