### ISSUE TITLE
not able to navigate in Google Drive

### ISSUE THREAD

**Issue by russelld58** [brookhong/Surfingkeys#925]
## Error details

can't navigate around in Google drive page to select mouse-clickable items.

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

URL:  drive.google.com/drive
## Context

I use Surfing Keys to move to a tab with Google Drive (GD) that is already open in my GD account.  Then I  attempt to navigate around the page with open edit <i>. GD responds with its own dialog box which is a drop down box to choose a new GD document.  So I have to mouse click to select the folder and open the GD document I am after.

**Comment by brookhong** [comment]
Cannot reproduce.
