### ISSUE TITLE
Color property in text hints not configurable

### ISSUE THREAD

**Issue by alexalekseyenko** [brookhong/Surfingkeys#927]
It appears that the following style in `content_scripts.css` might be overriding the `color` property set by `Hint.style(css, "text")` due to its specificity:
https://github.com/brookhong/Surfingkeys/blob/ee08b07fa92b431cb7e74193ede0c109c5c33f5d/content_scripts/content_scripts.css#L33-L35
Since `#00f` doesn't always end up being the most readable color, could we make this configurable?

A hacky way to do that might be to initialize `_styleForText` with the default property here:
https://github.com/brookhong/Surfingkeys/blob/025bbdb63a2cb396805ae3415cb4e6ab63c5a6e6/content_scripts/hints.js#L627

**Comment by alexalekseyenko** [comment]
Looks like I missed the 5 year anniversary of this issue 🥳

@brookhong would you be open to changing the styling of the text begin hints? I don't think it was ever very clear to me why this particular CSS property should be `!important`(?)

In any case, thank you very much for creating this excellent extension!

**Comment by brookhong** [comment]
This should have been fixed already, please try

    api.Hints.style("div{border: solid 3px #707070; color:#efe1eb; background: none; background-color: #707070;} div.begin{color:#0ff;}", "text");
