### ISSUE TITLE
copy link at point?

### ISSUE THREAD

**Issue by Chaformbintrano** [brookhong/Surfingkeys#929]
Can I somehow copy a link with a mechanism similar to visiting it (like «f», «C» etc.)?

**Comment by dotiful** [comment]
Yes, you can copy a link URL with `yc`, or copy multiple link URLs with `yma`.
Check default mappings for more useful shortcuts.

https://github.com/brookhong/Surfingkeys/blob/025bbdb63a2cb396805ae3415cb4e6ab63c5a6e6/pages/default.js#L151-L162

**Comment by Chaformbintrano** [comment]
thanks, I couldn't spot it in the help panel
