### ISSUE TITLE
Search Function can cause the extension to Freeze (100% CPU)

### ISSUE THREAD

**Issue by Mobalt** [brookhong/Surfingkeys#93]
1. Open up the options page
2. By default the textbox has focus, so "esc" a few times to make sure to transfer focus to document.body
3. "/" to bring up search
4. Followed by any character (eg "a")
5. Freeze

There is probably an infinite loop somewhere in the code. I just installed this extension today so I don't know if this bug pops up anywhere outside the options page, but think it might be worth investigating just in case.   Chrome Taskmanager (shift-esc) clocks the process at 100% cpu, and the memory slowly climbed from 50-80MB before I killed the process and had to "reload" the extension.

**Comment by brookhong** [comment]
Thanks for finding this issue.
