### ISSUE TITLE
[Feature Request] Implement option to copy links in Markdown, Asciidoc format with yXX command

### ISSUE THREAD

**Issue by vonHabsi** [brookhong/Surfingkeys#933]
The `y` key options such as `ya` and `yma` enable copying of links.

Can it be extended to include copy links in Asciidoc, Markdown and other user-configured formats the way [Link Text and Location Copier](https://addons.mozilla.org/en-US/firefox/addon/link-text-and-location-copier/) does?

Can you point me to a place in the code where I can implement this if I want to do it myself?

**Comment by brookhong** [comment]
That is not hard to implement, here is an example:

    mapkey('yL', "#7Copy current page's URL as markdown", function() {
      Clipboard.write('[' + document.title + '](' + window.location.href + ')');
    });

**Comment by vonHabsi** [comment]
How do you extend it to multiple items, like the way `yma` copies multiple links?

**Comment by brookhong** [comment]
Please refer to https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js#L156
