### ISSUE TITLE
cant select local files from open a url (t)

### ISSUE THREAD

**Issue by grenzionky** [brookhong/Surfingkeys#941]
SurfingKeys: 0.9.43

Browser: firefox 66.0.1 (64 bit) arch linux 4.20

i cant open local files from the Open a URL menu (the one that opens when u press 't'). everything else works just fine, its just files on my computer that dont work.  
what happens is that when i press enter on a local file, the popup just closes without it opening the file. if the file is already open in a tab then it goes to that tab, but thats not what this issue is about.

this is different than #51 cuz surfigkeys works fine on local pages, it just doesnt open up the file from the open a url menu.

**Comment by brookhong** [comment]
This is a limitation for security by Firefox, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

    For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
    chrome: URLs
    javascript: URLs
    data: URLs
    file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
    privileged about: URLs (for example, about:config, about:addons, about:debugging). Non-privileged URLs (e.g., about:blank) are allowed.
    The New Tab page (about:newtab) can be opened if no value for URL is provided.
