### ISSUE TITLE
Scrolling Interferes With Website's Native Implementation Of Vi-Keys

### ISSUE THREAD

**Issue by fweth** [brookhong/Surfingkeys#942]
SurfingKeys: 0.9.43

Browser: Chromium 73.0.3683.86 on Fedora 29

URL: twitter.com

Scrolling on Twitter interferes with Twitter's own implementation of vi-like scrolling (Surfingkeys fires consistently, Twitter fires unpredictably).

Facebook also implements some vi-keys, but here Surfingkeys successfully manages to override the behaviour, just as I would expect.

Also, messenger websites like WhatsApp or Telegram sometimes steal focus as soon the tab is brought to view.  (Vimium and Saka Key behave the same here, cVim manages to handle WhatsApp but not Telegram.)

Would it be possible to feed all keystrokes into Surfingkeys and block them from the website, until insert mode is activated?

**Comment by fweth** [comment]
OK, this seemed also connected to the key repeat rate.  After turning off key repeat, Twitter causes no problems.  It seemed as if Surfingkeys intercepted the first key event but the repeated events get through to Twitter and cause that behaviour.

**Comment by Shamaoke** [comment]
It would be great if you specified the _exact_ setting which eliminates the issue.

**Comment by fweth** [comment]
I turned off key repeat in the GUI (Settings/Universal Acess/Repeat Keys:Off).  It's not a perfect solution, since I like key repeat, but it will do for now.  Please note that Fedora 29 uses Wayland, maybe the method how the repeated keys are handed to the browser differs here from Xorg.
