### ISSUE TITLE
Double character doesn't work

### ISSUE THREAD

**Issue by The33Coder** [brookhong/Surfingkeys#947]
## Error details

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

## Context

I want to map dd for close tab and gt, GT for next and preview tab but this doesn't work.

```
unmap('x');
mapkey('dd', '#3Close current tab', function() {
    RUNTIME("closeTab");
});
unmap('gt');
map("gt","R");
unmap('GT');
map("GT","E");
```

If I press G for GT I go down of page and "Choose a tab" while showing. With dd I go down

**Comment by Shamaoke** [comment]
// unmap the key for scrolling a page down (should go before any binding with this key)
    unmap('d')
    
    // close the current tab
    mapkey( 'dd', '#3Close the current tab', ( ) => RUNTIME('closeTab') )
    
    // go left on {count} tabs
    mapkey( 'gT', '#3Go left on {count} tabs', ( ) => RUNTIME('previousTab'), {repeatIgnore: true} )
    
    // go right on {count} tabs
    mapkey( 'gt', '#3Go right on {count} tabs', ( ) => RUNTIME('nextTab'), {repeatIgnore: true} )

**Comment by The33Coder** [comment]
You solution work but I would like to keep `d` key for scroll down, for this reason I didn't want to do an unmap and for left tab I want `GT` and not `gT`

**Comment by Shamaoke** [comment]
1\. You can't bind two functions on the same key. So, you either use the `d' key for scrolling or as a prefix for a group of keys;
2\. If you want to emulate the Vim editor behavior, you should stick with `lower-gT'.
