### ISSUE TITLE
PDF viewer cannot be disabled in Brave

### ISSUE THREAD

**Issue by alexalekseyenko** [brookhong/Surfingkeys#948]
## Error details

SurfingKeys: 0.9.43

Browser: Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

URL: https://www.orimi.com/pdf-test.pdf

## Context

The "noPdfViewer" setting is not respected in Brave.

Toggling the setting using `;s` seems to set the appropriate value in `chrome.storage.local`, but regardless whether `{"noPdfViewer": 1}` is set or not, PDFs are displayed inside the Surfingkeys PDF viewer.

**Comment by alexalekseyenko** [comment]
Looks like this just has to do with how Brave currently handles PDFs, and it's going to be fixed:
https://github.com/brave/brave-browser/issues/3846

**Comment by pablospe** [comment]
Have you tried replacing `chrome.storage.local.set({"noPdfViewer": 1});` with `settings.noPdfViewer=true;` in the config.

From this comment: [here](https://github.com/brookhong/Surfingkeys/issues/2156#issuecomment-2357808392)
