### ISSUE TITLE
bind a key to switch to previous tab?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#949]
## Prelude
* Could you find answer in below documents?
no
    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
yes 
## Error details
cant find the command in order to bind a key to switch to previous tab
surfingKeys: <version>
latest 0.9.43
Browser: <version><os version>
chrome mac os
URL: <The_URL_Where_You_Find_The_Issue>

**You could simply click dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.**
![image](https://user-images.githubusercontent.com/288207/39614555-6048977e-4fa3-11e8-8476-46203af7c4d6.png)
SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/normal.js#L1006 is where the default binding.

Below way is recommended for change the binding:

**Comment by zeltak** [comment]
thx 
this seems to move a tab left? I wanted more if possibe to toggle between the last 2 focused tabs, is that possible?

**Comment by brookhong** [comment]
`Ctrl-6` should be what you want, please see https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js#L270

**Comment by 097115** [comment]
Thanks a lot! Sorry for missing :(

**Comment by draftman9** [comment]
> `Ctrl-6` should be what you want, please see https://github.com/brookhong/Surfingkeys/blob/master/pages/default.js#L270

is there any chance that I could use `ctrl-<tab>` to reach this function? I think `Ctrl-6` is hard to touch. :(
