### ISSUE TITLE
使用't' ，'b'等打开历史记录与书签，历史记录与书签记录多于10条，只展示10笔记录，无法翻页

### ISSUE THREAD

**Issue by jieYM** [brookhong/Surfingkeys#950]
## Error details

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

## Context

如题。

**Comment by brookhong** [comment]
https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md#%E6%90%9C%E7%B4%A2%E6%A0%8F%E6%8C%89%E9%94%AE

* `Ctrl-.` 显示下一页搜索结果
* `Ctrl-,` 显示上一页搜索结果
