### ISSUE TITLE
No support for summary tag

### ISSUE THREAD

**Issue by faissaloo** [brookhong/Surfingkeys#951]
## Error details
Cannot expand/collapse \<summary\> tags

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.75 Chrome/73.0.3683.75 Safari/537.36

URL: https://ratwires.space

## Context

Hit F, you will see that you cannot expand the post box in the bottom right.

**Comment by e-volusian** [comment]
Add to your configuration:

`settings.clickableSelector = 'summary'; `

This should probably be the default behavior.

**Comment by faissaloo** [comment]
Yeah that works, yeah I definitely think it should be default behaviour

**Comment by InnovativeInventor** [comment]
I've tested it on vimium and it works. This should 100% be default behavior.
