### ISSUE TITLE
似乎无法新建书签文件夹？

### ISSUE THREAD

**Issue by hundan2020** [brookhong/Surfingkeys#952]
## Error details

SurfingKeys: 0.9.43

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

**我在上述文档中都尝试寻找过“新建书签文件夹”的功能，但是并没有找到(或许是我没看到？)，似乎并没有这个功能？请问能否在未来的版本中添加支持？**

**Comment by brookhong** [comment]
嗯，是的，这个文档里漏掉了，谢谢。

你按`ab`添加书签时，可以输入新的目录名，并以`/`结尾，比如我选中了`/Bookmarks Bar/tool/`，然后在后面输入`abc/`，会把当前页加到`/Bookmarks Bar/tool/abc/`这个目录里。
![image](https://user-images.githubusercontent.com/288207/57563728-a8468b80-73d3-11e9-9b1b-f8107f9234d7.png)
