### ISSUE TITLE
URLs cannot be opened in Omnibar when Google as a default engine is replaced

### ISSUE THREAD

**Issue by maxigaz** [brookhong/Surfingkeys#954]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No.

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes. I've found issues similar to this, like #486, but this one isn't exactly the same.

## Error details

SurfingKeys: 0.9.43

Browser: Firefox 66.0.3 for Linux (64 bit)

URL: any page

## Context

I've replaced Google as the default search engine with a Searx instance in the settings of Surfingkeys (I don't know if it's the best way of doing that, but it seems to work):

```
addSearchAlias('g', 'Searx', 'http://search.disroot.org/?q=');
mapkey('og', 'Search Selected with Searx', function() {
    searchSelectedWith("http://search.disroot.org/?q=");
});
vmapkey('og', 'Search Selected with Searx', function() {
    searchSelectedWith("http://search.disroot.org/?q=");
});
```

After that, when I type the URL of a website (e.g. example.com) in the Omnibar, the only option I see is to look it up on Searx.

However, if I use the alias "d" for DuckDuckGo first and type in the same URL, the option to go directly there appears on top of the search suggestions. (So I can press `Tab` and `Enter`.) Maybe it has something to do with whether autosuggestions are supported or not?

Edit: I've also tried removing Google with `removeSearchAliasX('g', 'google');` and not using the search alias "g", but the results are the same.

**Comment by brookhong** [comment]
Yes, your guess is right. Currently url detection in input is only enabled when there are suggestions, this should be a bug, will be fixed in next release. Thanks.
