### ISSUE TITLE
What is for ? Copy form data (JSON/POST)

### ISSUE THREAD

**Issue by PrestanceDesign** [brookhong/Surfingkeys#956]
Hi @brookhong, 

First of all, thx you very much for this awesome extension !

Not a issue here, but I just curious how can I and for what using the **copy form data** 
`yp `, `yf` functionalities ? How can I use the JSON copied in clipboard ?
I'm sure it's very useful so I ask the question ! :)

Best regards.
Mike

**Comment by brookhong** [comment]
This feature is for the case when you need to refill some form repeatly. The workflow is like this.

There is a form(may be more) on a page, the form has been filled. Now you come to the same page with different account or for different project, but you want this form filled same(or almost same) as the former one. You could act in following steps.

1. press `yf` on old page to copy the form data.
2. press `;pf` on new page, if there is only one form, the form will be refilled with the data copied, if there are several forms, hints like those for `f` will be displayed for you to choose the form you'd like to refill.

**Comment by PrestanceDesign** [comment]
Alright!

I did well to ask the question because I knew it was going to be very useful!
As a web developer, I will be able to use these features between different website versions (local dev, staging, production, etc.). Great!
However, you confirm that I must manually edit the domain name in the JSON copy so that `;ypf` works?

**Comment by brookhong** [comment]
Yes, for now if you have different domain names for different stages, you probably need to modify the copied JSON so that `;pf` works.

`yf` just copies all the forms, but `;pf` will let you select the form you want to re-fill, so a key is generated for each form, which is the form method plus the form action URL, such as

    "get::https://github.com/brookhong/Surfingkeys/search": {
        "utf8": "✓",
        "q": "",
        "type": ""
    },

But you rasied a good question here, we should remove the domain name from the form key, so that the workflow could work across different sites. I just quickly made the modification, could you please try below in your case, to see if it works well without bothering to manipulate copied JSON data before `;pf`.

    function generateFormKey(form) {
        return (form.method || "get") + "::" + new URL(form.action).pathname;
    }
    mapkey('yf', '#7Copy form data in JSON on current page', function() {
        var fd = {};
        document.querySelectorAll('form').forEach(function(form) {
            fd[generateFormKey(form)] = getFormData(form, "json");
        });
        Clipboard.write(JSON.stringify(fd, null, 4));
    });
    mapkey(';pf', '#7Fill form with data from yf', function() {
        Hints.create('form', function(element, event) {
            var formKey = generateFormKey(element);
            Clipboard.read(function(response) {
                var forms = JSON.parse(response.data.trim());
                if (forms.hasOwnProperty(formKey)) {
                    var fd = forms[formKey];
                    element.querySelectorAll('input[type=text]').forEach(function(ip) {
                        if (fd.hasOwnProperty(ip.name)) {
                            ip.value = fd[ip.name];
                        }
                    });
                } else {
                    Front.showBanner("No form data found for your selection from clipboard.");
                }
            });
        });
    });

**Comment by PrestanceDesign** [comment]
> But you rasied a good question here, we should remove the domain name from the form key, so that the workflow could work across different sites.

Yes great idea, thank you !

>  I just quickly made the modification, could you please try below in your case, to see if it works well without bothering to manipulate copied JSON data before ;pf.

I just tried to override `yf` and `;pf` settings with your snippet, but it doesn't works, the fields are not fills up.

**Comment by brookhong** [comment]
Maybe caused by the selector in `element.querySelectorAll('input[type=text]')`, I tried on https://addons.mozilla.org/en-US/firefox/users/edit with below snippet, it works.

    function generateFormKey(form) {
        return (form.method || "get") + "::" + new URL(form.action).pathname;
    }
    mapkey('yf', '#7Copy form data in JSON on current page', function() {
        var fd = {};
        document.querySelectorAll('form').forEach(function(form) {
            fd[generateFormKey(form)] = getFormData(form, "json");
        });
        Clipboard.write(JSON.stringify(fd, null, 4));
    });
    mapkey(';pf', '#7Fill form with data from yf', function() {
        Hints.create('form', function(element, event) {
            var formKey = generateFormKey(element);
            Clipboard.read(function(response) {
                var forms = JSON.parse(response.data.trim());
                if (forms.hasOwnProperty(formKey)) {
                    var fd = forms[formKey];
                    element.querySelectorAll('input').forEach(function(ip) {
                        if (fd.hasOwnProperty(ip.name) && typeof(fd[ip.name]) !== "object") {
                            ip.value = fd[ip.name];
                        }
                    });
                } else {
                    Front.showBanner("No form data found for your selection from clipboard.");
                }
            });
        });
    });

**Comment by PrestanceDesign** [comment]
Yeah I confirm, it works now! :+1: 
I close this issue which is more than answer, thank you!

Do you plan to create a commit for this change?

**Comment by brookhong** [comment]
Yes, here is the commit https://github.com/brookhong/Surfingkeys/commit/32a6b1208a0352464fd0517002f597364b541997
