### ISSUE TITLE
Any way to replicate  CVim-like view full image hint?

### ISSUE THREAD

**Issue by purgat0ri** [brookhong/Surfingkeys#959]
In CVim it's possible to map a key to a function called 'fullImageHint,' which essentially hints all images on a page and then displays whatever one selects in a new tab. The isolated image can then be saved with CMD/ctrl+s, providing a mouse-free way of saving images. In every other way, Surfingkeys is the superior extension, so is something like this possible, or could it be added?

**Comment by brookhong** [comment]
Just add below in your settings:

    mapkey('q', '#1Click on an Image to open it in new tab', function() {
        Hints.create("img", function(element, event) {
            tabOpenLink(element.src);
        });
    });

**Comment by purgat0ri** [comment]
That works! Many thanks.
