### ISSUE TITLE
Global Vim-like marks : wrong URL

### ISSUE THREAD

**Issue by jlnbdt** [brookhong/Surfingkeys#96]
Hi,

Trying to create global vim-like marks, I can't get it working correctly. All marks have the same URL: "chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/frontend.html"

Thanks

**Comment by brookhong** [comment]
What's version of your installation?

I can not reproduce this issue in 0.6.1.

**Comment by jlnbdt** [comment]
Hi,

Same version here.

**Comment by jlnbdt** [comment]
Sorry, I was not clear. Problem occurs when I try to add global mark from Omnibar diplaying bookmarks.
