### ISSUE TITLE
如何实现关闭位于当前页面左侧或右侧的标签页

### ISSUE THREAD

**Issue by av2000ii** [brookhong/Surfingkeys#97]
您好，此功能您觉得是否有必要加入surfingkeys中，我用浏览器因为网速、性能等多种原因，设置默认后台打开链接，所以当我切换到新的标签页时常常需要关闭之前浏览的页面，因此觉得这种功能挺好的。当然如果可以通过自定义功能实现，麻烦您告诉我下。

**Comment by philia** [comment]
这个要看你的使用习惯, 我一般也是会在后台开启一些新标签页留着一会儿看, 当要切换到新标签同时关闭当前标签时我会用x(SurfingKeys快捷键)先关闭当前页, 再用Cmd+数字(Chrome快捷键)或T(SurfingKeys快捷键)+标识来切换到想要看的标签页.

**Comment by av2000ii** [comment]
cVim中提供了这方面的快捷键，主要还是每个人使用习惯不同，众口难调。

**Comment by brookhong** [comment]
`cf`打开多个页面，然后R切到右边，看一个就x掉一个。剩下那些就依次出现了。之后你就只需要按x就行了。

这个用法在vimium/cvim还有其他的应该是一样的，除了`cf`(continuously follow)这个按键有所不同。
