### ISSUE TITLE
Deleting a mark

### ISSUE THREAD

**Issue by CaptainDaVinci** [brookhong/Surfingkeys#971]
I have accidentally created a bunch of markings, how do I go about deleting them?

**Comment by vcfvct** [comment]
same here. 
Was trying to hit `delete` in the `om` list, seems not working.

**Comment by brookhong** [comment]
`om` to show the mark list, `tab` to select your item to delete, then hit `Ctrl-d`.

This works same for history/url/bookmark in Omnibar.

**Comment by generic-user** [comment]
Hi
I think it would be useful if it would be stated in the help how to remove the bookmarks, and vim marks.

![image](https://user-images.githubusercontent.com/1516035/67498915-85a5e780-f680-11e9-8f55-08fa66e0a540.png)
