### ISSUE TITLE
Get the URL of marks in setting js file

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#975]
Since 0.9.44, Surfingkeys doesn't support opening the mark in the same tab. I want to write a customized script to bring the experience back. But I don't know how to get the URL of marks in setting js file. Is there a variable like "settings.marks"?

Could you help to point it out? Thanks!

**Comment by laphylee** [comment]
Solved after reading the code. Share the code to open mark in the current tab for some domains:

```
mapkey("'", '#10Jump to vim-like mark', function(mark) {
    runtime.command({
        action: 'getSettings',
        key: "marks"
    }, function(response) {
        var markInfo = response.settings.marks[mark];
        if(markInfo) {
            openLinkInCurrentTab(markInfo.url);
        } else {
            Front.showBanner(`No mark of: ${mark}`);
        }
    });
}, {domain: /xxxx/});
```

**Comment by Madd0g** [comment]
good stuff, solves my problem with #957

**Comment by for-coursera** [comment]
@laphylee Does this snippet still work for you? Somehow I'm struggling a bit...

**Comment by laphylee** [comment]
> @laphylee Does this snippet still work for you? Somehow I'm struggling a bit...

Yes, it works.

**Comment by for-coursera** [comment]
OK, so I have this in my config:

    unmap('go');
    mapkey('go', '#10Jump to vim-like mark', function(mark) {
        runtime.command({
            action: 'getSettings',
            key: "marks"
        }, function(response) {
            var markInfo = response.settings.marks[mark];
            if(markInfo) {
                openLinkInCurrentTab(markInfo.url);
            } else {
                Front.showBanner(`No mark of: ${mark}`);
            }
        });
    });

And I have `h` mark set (`'h` does open it in a new tab). But when I press `goh`, just nothing happens :(. 

Any ideas may be? :)

**Comment by laphylee** [comment]
@for-coursera 

Seems the runtime.command() is not valid, you could use following:

```
unmap('go');
mapkey('go', '#10Jump to vim-like mark', function(mark) {
    RUNTIME('getSettings', {
        key: "marks"
    }, function(response) {
        var markInfo = response.settings.marks[mark];
        if(markInfo) {
            openLinkInCurrentTab(markInfo.url);
        } else {
            Front.showBanner(`No mark of: ${mark}`);
        }
    });
});
```
