### ISSUE TITLE
alt+s not toggling surfing keys in firefox 67

### ISSUE THREAD

**Issue by simontong** [brookhong/Surfingkeys#979]
## Error details

SurfingKeys: 0.9.44

Browser: Firefox 67, Arch Linux

URL: All pages

## Context

alt+s does not appear to be toggling Surfing Keys.

**Comment by Crandel** [comment]
Confirm this issue
Surfingkeys: 0.9.47
Firefox: 69
OS: Arch Linux

**Comment by brookhong** [comment]
Please try to disable `resistFingerprinting` in about:config, it looks like the setting breaks key event by setting keyCode to 0.

**Comment by MrZeroo00** [comment]
Same issue here. `resistFingerprinting` is disabled.

**Comment by aw-bib** [comment]
Alt-S is not working as soon as I set `Enhanced Tracking Protection` _beyond_ `Standard`. It _does_ work however, as soon as I add a page to the exceptions for enhanced tracking protection.

This allows to address my initial issue that Surfingkeys does not play too well with this other commercial collaboration software from Australia.

Firefox 78.6.1esr (64-bit) on Debian GNU/Linux 10.
