### ISSUE TITLE
previousPage/nextPage ([[/]]) should respect the rel HTML attribute

### ISSUE THREAD

**Issue by stepnem** [brookhong/Surfingkeys#989]
(Cf. e.g. the relevant [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-rel).)

One example of a web page where \[\[/]] currently fails to do anything useful:
https://magit.vc/manual/forge/

There is even an old pull request for this: #678

I've put the following in my settings, but it should really be fixed
in core:

```javascript
function myNextPage (next) {
  let direction = next > 0 ? 'next' : 'prev';
  let links = document.querySelectorAll('[rel=' + direction + '][href]');
  if (links.length) {
    window.location.assign(links[links.length - 1].href);
    return true;
  }
  let regexProp = direction + 'LinkRegex';
  let nextLinks = getClickableElements("a, button", runtime.conf[regexProp]);
  nextLinks = filterOverlapElements(nextLinks);
  if (nextLinks.length) {
    clickOn(nextLinks);
    return true;
  }
  return walkPageUrl(next);
};

mapkey('[[', '#1Click on the previous link on current page', function() {
  return myNextPage(-1);
});

mapkey(']]', '#1Click on the next link on current page', function() {
  return myNextPage(1);
});
```

**Comment by EvanCarroll** [comment]
I agree with this. I was browsing the rust book and tried to use `]]` to find that it didn't look. The rust book uses the text `>` for their next button.

That said, I'm not sure I agree with this patch.

* I don't believe we should ever be applying `runtime.conf.nextLinkRegex` and the `runtime.conf.prevLinkRegex`. These behaviors were likely made out of innocent ignorance. The right behavior is *only* to select the rel="next" or rel="prev" attributes, as that's a standard.
* I don't believe we should be doing `window.location.href = linkPrev.attr('href');` as this won't work on single page apps. Instead, we just need to `document.querySelector('a[rel="next"]').click()` which sends the event to the page to be handled as desired.

**Comment by stepnem** [comment]
> * I don't believe we should ever be applying `runtime.conf.nextLinkRegex` and the `runtime.conf.prevLinkRegex`. These behaviors were likely made out of innocent ignorance. The right behavior is *only* to select the rel="next" or rel="prev" attributes, as that's a standard.

Unfortunately I think the same kind of ignorance applies to some web
page authors, so the regexp based link scraping might still have some
value as a fallback.

> * I don't believe we should be doing `window.location.href = linkPrev.attr('href');` as this won't work on single page apps. Instead, we just need to `document.querySelector('a[rel="next"]').click()` which sends the event to the page to be handled as desired.

I think a[rel] is too narrow, not all followable elements with a "rel"
attribute are As.

Regarding reliability of the click() method cf. commit be08a74e2cd.

(Also, you're apparently referencing the old pull request, but that's
more of historical value now; it wouldn't work unmodified with the
current code base anyway.)

**Comment by vogler** [comment]
Some pages don't have `rel` set *and* don't have regex-able text but img/svg inside.
Just made a tampermonkey script to add `rel=next/prev` to such elements querying text in `aria-label`: https://gist.github.com/vogler/d3b4622033837df8597fb2ab993888a8
I only run it on one website, but you could run it for any URL if you generalize it and don't mind the overhead.

It would be nice to be more flexible and just be able to define a `querySelector`, where it would e.g. first check for `rel=next`, then `nextLinkRegex`, then `nextLinkQuerySelector`.
