### ISSUE TITLE
搜索栏的对齐

### ISSUE THREAD

**Issue by weakbeing** [brookhong/Surfingkeys#99]
比如按下og后，google>>前缀是居中的而输入的文字是偏下的。

**Comment by brookhong** [comment]
无法复现你说的问题，能说说你用的Surfingkeys版本和chrome版本吗？

还有你的浏览器（屏幕）分辨率？

**Comment by weakbeing** [comment]
@brookhong 
Surfingkeys : 0.6.2
Chrome: Version 53.0.2785.116 (64-bit)
分辨率 1920*1080

**Comment by brookhong** [comment]
重现不了，贴个截图看看，还有你是在哪个网页上发现的？还是你在任意网页都有这个问题？

**Comment by weakbeing** [comment]
是我表述的不清楚让你误会了吗？我借用了你的介绍里的一个截图，第一行里 “baidu”等 和后面的输入不在一条水平线上。
![](https://cloud.githubusercontent.com/assets/288207/17644214/759ef1d4-61b3-11e6-9bd9-70c38c8b80e0.gif)

**Comment by brookhong** [comment]
谢谢，0.6.3里改了。
