### ISSUE TITLE
The "O" mapping is broken on Firefox

### ISSUE THREAD

**Issue by stepnem** [brookhong/Surfingkeys#990]
For example, on https://brookhong.github.io/2018/11/18/bring-focus-back-to-page-content-from-address-bar.html after pressing "O" the hints display, but trying to follow either of them has no effect.

The click() method on the created element apparently doesn't work as expected.

The change below works for me, but I don't know if it's the preferred fix. (If so, I can submit a PR if desired.)

``` diff
index 05897c0..f4dfe40 100644
--- a/pages/default.js
+++ b/pages/default.js
@@ -212,7 +212,7 @@ mapkey('I', '#1Go to edit box with vim editor', function() {
 });
 mapkey('O', '#1Open detected links from text', function() {
     Hints.create(runtime.conf.clickablePat, function(element) {
-        createElement(`<a href=${element[2]}>`).click();
+        window.location.assign(element[2]);
     }, {statusLine: "Open detected links from text"});
 });

```

**Comment by brookhong** [comment]
`O` is to detect URLs(rather than a link with href) from plain text. Maybe the description should be refined. There is no plain text containing URLs on https://brookhong.github.io/2018/11/18/bring-focus-back-to-page-content-from-address-bar.html, for `links`, `f` should be used.

**Comment by stepnem** [comment]
I'm sorry, but I think you are confused/misunderstand.

Strictly speaking, there is no "plain text" there (for a plain text
document Surfing keys would not even work at all AFAICT), but there are
two URLs inside text nodes (as opposed to element nodes with a href
attribute), which is what O should work for (and doesn't). The two URLs
in question are

    https://superuser.com/questions/324266/google-chrome-mac-set-keyboard-focus-from-address-bar-back-to-page

    https://github.com/philc/vimium/issues/840

Could you please take time to reconsider and try the recipe I provided?

**Comment by brookhong** [comment]
What does `O` do for you on https://raw.githubusercontent.com/brookhong/brookhong.github.io/master/_posts/2018-11-18-bring-focus-back-to-page-content-from-address-bar.md ?

**Comment by stepnem** [comment]
Oh, so apparently it's some kind of Firefox vs Chrome thing. I sincerely
apologise! (But please bear with me, see the report below.)

I had no idea you could use extensions on text/plain documents in
Chromium.

The behaviour I'm seeing is somewhat confusing and can be summarized as
follows (everything with Surfingkeys 0.9.45 on Linux):

FF 67, clean profile:

On
https://raw.githubusercontent.com/brookhong/brookhong.github.io/master/_posts/2018-11-18-bring-focus-back-to-page-content-from-address-bar.md
nothing happens, I can't use any Surfingkeys mappings no matter how much
I reload the page etc. On non-text/plain documents I get the broken
behaviour described in my original post ('O' hints display on text node
URLs but following them has no effect). 

FF 67, clean profile with my changed 'O' mapping:

Still no Surfingkeys on text/plain, but elsewhere it's fixed as I described.

[Strangely enough, it does work on FF with my regular profile and many
other extensions and customizations, including the 'O' change above,
_if_ I reload the page, ie. not after first navigating to it. What a
mess...]

Chromium 74.0.3729.169, clean
profile:

It works as you describe everywhere.

That said, on Chromium it works just the same with my change, too, so I
think something like that would be nice to make it work on FF as well
(barred the text/plain problem).

Thank you for your patience (and the extension!).

**Comment by brookhong** [comment]
## `O` work for plain text doc in Chrome.
![image](https://user-images.githubusercontent.com/288207/59983760-21cdcc80-9656-11e9-9e87-26383d64fb37.png)
## `O` work for plain text in a html doc in Firefox.
![image](https://user-images.githubusercontent.com/288207/59983870-c223f100-9656-11e9-8507-188d0b547b97.png)

Yes, this extension does not work plain text doc in Firefox at all. That is a limitation from Firefox itself. The key binding of `O` just works.

For the links on a html doc, `f` should be used regardless of your browser, here is a screenshot from Firefox.
![image](https://user-images.githubusercontent.com/288207/59983939-5beb9e00-9657-11e9-9bfc-99963b30ec7b.png)

**Comment by stepnem** [comment]
> ## `O` work for plain text in a html doc in Firefox.

Not really: as I explained earlier, the hint overlays (divs) do _show_
after pressing 'O', but trying to follow them has no effect (apparently
the click() method doesn't work on the autogenerated elements). That's
why I'm suggesting something like the change from my original posting:
that way this use case of 'O' is fixed for FF, and Chromium continues to
work same as before.

> For the links on a html doc, `f` should be used regardless of your
> browser, here is a screenshot from Firefox.

Of course, that's different and unrelated to this issue. I never
suggested otherwise.

**Comment by brookhong** [comment]
Yep, exactly.

Please send the PR for that, thanks.

**Comment by stepnem** [comment]
Done, thank you!
