### ISSUE TITLE
enhancement : omnibar always pick the first search result

### ISSUE THREAD

**Issue by KamiGim** [brookhong/Surfingkeys#995]
I think It would be a good idea that we have settings about pick the first search result. right now we always have to use tab at least once to pick the first one

**Comment by Shamaoke** [comment]
I'm against it.

**Comment by yusufaktepe** [comment]
There is already an option for this, you just need to enable it:
```
settings.focusFirstCandidate = true;
```

**Comment by KamiGim** [comment]
> There is already an option for this, you just need to enable it:
> 
> ```
> settings.focusFirstCandidate = true;
> ```

Thanks for point that out
